### ISSUE TITLE
Tilt not working in Special Actions

### ISSUE THREAD

**Issue by RathX** [Ryochan7/DS4Windows#1001]
I've tried and assigned every possible Tilt trigger to different actions, like battery checking or pressing the Windows key. But the triggers won't activate the action, even though they are recognized in the Controller Readings.
Other trigger work perfectly fine, so I assume that the Tilt triggers do not work as intended.

**Comment by Ryochan7** [comment]
I could have sworn that I at least checked Tilt Up as a Trigger for the Battery Check special action while testing. I will double check this.

**Comment by Ryochan7** [comment]
Testing Tilt triggers for Special Actions now. I have tested Check Battery Life, Launch a program, and Press/Toggle key Special Actions. Tilt triggers work for me. Please make sure that you enable the Special Action in the list after creating a new Special Action.

I specially wanted to deviate from the old decision and leave newly created Special Actions off in a profile by default. I cannot remember why I made that decision though.

**Comment by Ryochan7** [comment]
I think I remember why I made the decision. Due to the way that the Special Actions are bound to a profile from those controls, the Special Action would be usable upon first creation rather than on profile save like with the older versions of DS4Windows. Maybe I should just let that slide and make newly created Special Actions enabled in the current profile by default. It would be a very minor change in the code.

**Comment by RathX** [comment]
Sounds good, thank you!

Special Actions work for me when using button combinations, except swiping and tilting. Funny enough, gyro works perfectly fine when mapped on the Right Stick for example. I've made sure the Special Actions are activated.
