### ISSUE TITLE
BT connectivity

### ISSUE THREAD

**Issue by viottiz** [Ryochan7/DS4Windows#1004]
Been playing rocket league (through steam) for awhile now. Using a DS4 v2 wired. Recently just bought a 4.0 USB Adapter that works perfectly with connectivity to DS4s controller mapping yet doesn’t show readings on either joy.cpl or html5, 

I ended up seeing an issue about BT and i got to the point of renaming the DS4 exe, and then when I went to joy.cpl I could see one wireless controller (that didn’t map at all) and another one that would only show for a second and then disappear for 2, then repeat over and over. Tried to click on it and it said I didn’t have the necessary files so I reinstalled ps4 remote play and restarted. Come back and the controller that actually was working (I could tell it was because rocket league started reading my Bluetooth connectivity as ps4 buttons) is not showing up at all anymore. 

When the the profile setting is set to PlayStation 4 controller it will not work in joy.cpl but will when shown as a XBox controller.

I just saw that it was almost picking up my DS4 finally so I can only assume there is a way to show it’s a PS4 controller and use Bluetooth some how maybe?

Pls help and thanks.

**Comment by mika-n** [comment]
DS4Windows and BT and dualshock4 profile does work as long BT receiver and a gamepad are compatible. 

Are you using exclusive mode (=Hide DS4 Controller option in DS4Windows) or HidGuardian tool to hide the original physical controller device? 
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

The problem in BT in DS4 gamepads is that when the original HID device in WindowsOS is switched over to native DS4 mode (DS4Windows application does this) then the original HID device "Wireless Controller" is seen by WinOS as a dead device. WinOS doesn't know how to use it over BT. DS4Windows app solves this by using the original gamepad in "RAW dinput" mode and outputting all buttons/touchpad/lightbar/rumble/axies to a virtual xbox360 or dualshock4 gamepad. Games should use this virtual output gamepad device and not the original "dead" dinput gamepad device. ExclusiveMode or HidGuardian tool are used to hide the original device from games and leaving just the virtual gamepad device visible.

However, if you suffer from periodic connect/disconnection problem then it is something else. What do you see in Logs tab page or in "%APPDATA%\DS4Windows\Logs" folder?

**Comment by viottiz** [comment]
I have both the Hide DS4 Controller option ticked on as well as using HidGuardian tool to hide the physical controller. (dont know if its bad using both at the same time). 

I honestly dont remember how I even got it to become playable in Rocket League. It stays connected and works properly on DS4, it is only not reading in joy.cpl, but (and by sheer luck) it worked for a bit while i was messing around with the configs while playing RL (wish i could be of more help but i really dont remember what i did as i was in a rush before work). 

Joy.cpl showed the dead controller you mentioned, but also had another identically named "wireless controller" that would cycle through connecting/disconnecting (and when shown on the list it let my inputs work in game) but my ds4 logs itself showed nothing wrong, (would show logs but dont have any in that folder you mentioned from before i left work today).

Controller read correctly on joy.cpl while on BT without running ds4windows but as soon as i run it, becomes "dead"

**Comment by mika-n** [comment]
> I have both the Hide DS4 Controller option ticked on as well as using HidGuardian tool to hide the physical controller. (dont know if its bad using both at the same time).

Usually it is not necessary to use both HideDS4Controller option and HidGuardian tool. If you are using HidGuardian tool then try unticking "Hide DS4 Controller" option because HidGuardian is more "bullet proof" way to hide the original physical controller (as long it is setup correctly).

If you untick HideDS4Controller and connect a gamepad then you should see just one gamepad device in JOY.CPL controlPanel applet. If you see two and one of them is a dead device then you have not setup HidGuardian properly. Check its AffectedDevices sysreg entry and make sure DS4Windows.exe process identifier appers in WhiteList sysreg entry when you launch DS4Windows app.


>but my ds4 logs itself showed nothing wrong, (would show logs but don't have any in that folder you mentioned from before i left work today).

Hmmm...... Connect/Disconnect events should be shown in Logs tab page in DS4Windows app and in log files (ie. if you are using V2.x version of DS4Windows app. Older V1.7.x didn't create any logfiles but it did show events in Logs tab page). The location of logfile folder is either APPDATA or PROGRAMDATA folder depending on which one you chose as a profile folder when you launched DS4Windows for the first time. APPDATA usually works better (permissions).

 
> Controller read correctly on joy.cpl while on BT without running ds4windows but as soon as i run it, becomes "dead"

Yes. But without running DS4Windows app the BT connected DS4 gamepad is running in so called "PC-friendly mode" and only normal buttons and axies work. It doesn't support touchpad/lightbar/rumble unless a game has native built-in support for DS4 dinput devices. Some games may support it, but most games don't have a clue. Don't know about Rocket League.

The original gamepad device becomes "dead" as soon DS4Windows app forces the BT connected "PC-friendly" gamepad to switch over to native DS4 gamepad mode. This is a problem in WinOS and there is nothing DS4Windows app can do about it.

If you connect the gamepad via USB cable then it doesn't suffer from this "dead device" issue because DS4 gamepad goes automatically to native DS4 mode in USB connections. The "dead device" is a problem only in BT connections (unless you purchase $50 official Sony Wireless Adapter BT gadget which workarounds this dead device issue in a hardware level).

**Comment by viottiz** [comment]
I have unticked the hide ds4 option and when i open the joy.cpl, there is only 1 wireless controller which is dead

I would also like to ask for more information on the whitelist sysreg entry you were talking about and how exactly to do that... albeit i have been in there before for my rev2 ds4. 

again, sorry but i have any dating back to when the disconnectivity occured (around 3.30PM CST jan 3rd with my oldest log in appdata being 12:05 AM jan 4th *below* 

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4021747/ds4windows_log.txt)
