### ISSUE TITLE
Scrolling on right touchpad edge (like on laptops)?

### ISSUE THREAD

**Issue by S-trace** [Ryochan7/DS4Windows#1007]
Hello.

On Kubuntu 19.10 right touchpad edge works for scrolling on my DS4v2, just like on laptops.
Is it possible to add this feature to DS4Windows?

Thank you for supporting and developing DS4Windows.

**Comment by mika-n** [comment]
DS4Windows does support scrolling in touchpad options, but it is mapped to "double finger" gesture. Enable "scroll" option in "Touchpad" options and set a desired scroll speed (the default 100 speed is a bit too fast for my taste).

But nice idea of having an option to set scrolling to right or left side of the touchpad (and up/bottom for horizontal) instead of always using the "built-in" double-finger gesture for scrolling.

![DS4Win_ScrollerTouchpad](https://user-images.githubusercontent.com/35538525/71783277-1720c680-2fed-11ea-9677-6c26573b0d20.png)

**Comment by Ryochan7** [comment]
I guess that option could be added to the "Use As Mouse" mode. It would naturally take away a portion of the Touchpad from being usable as a mouse. The appropriate output mode would have to be checked on first touch.

**Comment by Ryochan7** [comment]
I don't see myself getting around to implementing this so I am going to close this issue. Going to have to settle with the current Multi-touch Scroll functionality.
