### ISSUE TITLE
Auto profiles

### ISSUE THREAD

**Issue by Tiberiusmoon** [Ryochan7/DS4Windows#1013]
Is there a way to select a none or empty profile as selected profile?
As referenced here: https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules#setting-do-not-change-profile-rule
This can basically disable the controller while not in use to avoid unwanted input and have the controller active when a pinged program is selected for auto profile.

If not;
Could there be some method of selecting none in the selected profile list?

I know this can be done currently by creating a custom profile and removing the keybinds but i feel this can help with user experience.

**Comment by mika-n** [comment]
Auto-profile feature has "Turn off DS4Windows temporarily" which disables DS4Windows app to re-map gamepad keys, but it is true that it doesn't disable the original gamepad. It will be available after DS4Windows app is temporarily in stopped state. However, if you use HidGuardian tool to hide the original physical controller then any other app but DS4Windows won't see the original controller.

If you use "Hide DS4 Controller" (=exclusive mode) in DS4Windows options then the result is a bit different. The original gamepad becomes visible when DS4Windows app is in stopped state.

So, at the moment one way to do what you described is to use HidGuardian to hide the origial physical controller instead of "Hide DS4 Controller" exlusive mode option (those are alternative ways to avoid double input problems).
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

If you use BT connection then there is one trick to do what you described. Over BT connection the original gamepad is in "dead state" when DS4Windows switched it over to native DS4 mode. If you create a profile with "Use DInput only" option checked then DS4Windows app won't output re-map keys to an output virtual controller because it let's the original dinput gamepad interface to work for those app which support native dinput DS4 gamepads. However, because the original dinput interface is now in dead state in BT connection mode the net result is non-functional gamepads.

This "Use DInput only" trick won't work in USB connections because the original gamepad interface doesn't suffer from this "dead gamepad interface in DS4 mode" issue (dead interface is WinOS level problem, not Ds4Windows app problem), but HidGuardian works with both BT and USB connections.

Anyway. You can always "create an empty profile" where all output re-map rules have been removed. DS4Windows app could also provide such a pre-set "empty" profile along side the default profile file. If you go through the effort to clear all gamepad re-maps in a profile then feel free to share such a profile file here for those who might wanna use the same "empty profile" trick to temporarily disable gamepad output events.

**Comment by Tiberiusmoon** [comment]
Ahh, i see.
But why doesnt the app just go into stopped state when Hide DS4 is enabled?
A lot of things in DS4 just briefly say what they do but not so much what they are for, which makes it confusing and probably would not need as much online documentation tbh.

**Comment by mika-n** [comment]
> But why doesnt the app just go into stopped state when Hide DS4 is enabled?

Do you mean that when auto-profiler uses "Turn off DS4Windows Temporarily" option then DS4Windows app would NOT release the exclusive lock, but just to temporarily stopping feeding gamepad outputs to virtual gamepad but still holding an exclusive lock on the physical gamepad to prevent other apps to use it?

Technically it would possible to do it like that, but then again some user might wanna use the current logic of "Turn off DS4Windows Temporarily" in scenarios where an app needs to use the physical gamepad interface directly. This functionality is the original idea of this "Turn off DS4Windows temporarily" option. 

I think the "Turn off DS4Windows temporarily" option name implies that the option will temporarily stop doing anything DS4Windows app is doing at the moment (including "Hide DS4 Controller" exclusive locking thing). But I agree there are for sure valid scenarios where the exclusive lock should be left as it is while just stopping feeding output to a virtual gamepad. Then again that alternative functionality can be achieved already by creating a dummy profile where all gamepad keys/sticks/touchpad are set to unbound state. When auto-profiler is set to use that dummy profile then HideDS4Controller option is still doing its job even when the virtual gamepad is "silent".


> A lot of things in DS4 just briefly say what they do but not so much what they are for, which makes it confusing and probably would not need as much online documentation tbh.

True. There are too few context sensitive tooltip help texts explaining more about various options when just an option name is not self explanatory. I'm sure there will be more and more tooltip texts once the dust settles down in the new V2.x GUI system. 

It is also true that Wiki documentation page (especially Settings section) is no where near to be complete. The Settings page needs more screenshots and better structure to explain what each of the option groups and single options are doing and in what kind of scenarios those options are supposed to be used. The app Settings GUI itself could show a clickable URL link to this Settings page because not all users can even find the Wiki page (or know that there even exists one).
https://github.com/Ryochan7/DS4Windows/wiki/Settings

**Comment by Ryochan7** [comment]
> A lot of things in DS4 just briefly say what they do but not so much what they are for, which makes it confusing and probably would not need as much online documentation tbh.

That is very much true. Very little of DS4Windows has ever been documented. Doing anything beyond using a Default profile pretty much requires experimentation to see what some options do. There is only a little bit of documentation in the Wiki. It does not help when I keep changing how certain operations behave depending on what I am trying to accomplish. That has been much less of an issue nowadays as behavior has been becoming more concretely defined since around version 1.7.

It also did not help that I was hesitant on adding some features that I wanted due to how brittle the old app could be. Sometimes even one small change to the code could drastically change the performance of the entire application. Part of the big reason for the transition to DS4Windows 2.0 was to make application maintenance much easier so hopefully features can be added more quickly. Luckily It has worked out so far.

Part of the plan for 2020 is to add some extra documentation in the application and also online. The social media push is a part of that as I do want to record some tutorial videos and also record some demo videos showing what can be done using DS4Windows. The main point of reference for DS4Windows on YouTube is still the older Jays2Kings 1.4.52 build. There are many different features that are only available with the current build that allow more ways to play certain games.

**Comment by Tiberiusmoon** [comment]
Nvm i just realised i needed to turn off DS4 via the button on the bottom right and it would automatically toggle it on when needed. https://i.imgur.com/bhxUfEP.jpg

@Ryochan7 
It sounds like your coding in a rats nest from past Dev's.
Have you considered coding the App from scratch so there is less clutter and potentially make it more efficent?
If your up for it i can suggest some changes to the wording of some settings to make it easier to understand its process.
