### ISSUE TITLE
auto profile switching 

### ISSUE THREAD

**Issue by eclipsaa** [Ryochan7/DS4Windows#1016]
I try to use the auto profile switcher but the problem is it will switch profiles when i mess with other windows like Chrome or steam and so forth.   

Is there a way so it just switches the profile fully instead of temp.  When it dose this switch it freezes games or it takes the game 20 or so seconds to re find the controller again like it forgot everything.  Some games cant even find the controller again unless i restart DS4windows

**Comment by mika-n** [comment]
This "revert back to default profile on unknown process" thing is a known issue. At the moment you can workaround it by creating a "catch all - do nothing" type o auto-profile rule as the last rule in auto-profile list.
https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules#setting-do-not-change-profile-rule

However, the next version o DS4Windows 2.x release has a new option in auto-profile screen. By using the new upcoming option user can decide what happens when auto-profiler detects "an unknown process". By default the app reverts back to default profile but the new option makes it possible to leave the current profile active as it is.

**Comment by eclipsaa** [comment]
Yeah thats my biggest issue.  I play FFXIV witch runs better using the Dualshock4 but almost every other game uses Xbox360 better...   Causes massive issues

**Comment by mika-n** [comment]
>Sooo im not sure how to use this work around. What do i do exactly?

Just follow instructions in the Wiki page or wait for the next release of DS4Windows.

At the moment there is no way to avoid the short disconnection when a profile uses DIFFERENT output type than the previous profile. The trick described in Wiki page just prevents unnecessary profile switches on unknown processes but it doesn't solve the disconnect/connect issue if you really have to switch between different type of output profiles.

There has been discussions about a new feature where DS4Windows app would do a connection pooling with output controllers and this way the app would not disconnect the existing output controller right away (maybe after X minutes idling it would close abandoned output controllers). If the new profile uses another connection type from the pool of cached output connections then old connection is technically still connected but it doesn't receive any gamepad key events. This way game would not see connect/disconnect events at all because the game thinks the old gamepad is still connected while in fact DS4Windows app is just feeding outputs to another output connection when user switched over to new app which required different controller type (xbox vs ds4). Someday this kind of optional connection pooling probably make its way into DS4Windows app but when? Who knows....

**Comment by eclipsaa** [comment]
Yeah i read the wiki it just went right over my head ;P
