### ISSUE TITLE
App Locked up/crash: trackball is enabled

### ISSUE THREAD

**Issue by Tiberiusmoon** [Ryochan7/DS4Windows#1018]
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4030870/ds4windows_log.txt)

When editing a profile > Controls > Touchpad > Use As Mouse.
Disable Slide then enable Trackball, save the use the trackball on the controller.
The App locks up and the logs just spams whats mentioned in the logs.

Edit: Trackball is causing this issue and happens regardless of what other setting are set.

**Comment by Tiberiusmoon** [comment]
Apparently the trackball function is suppose to "roll" a bit after you let go like a normal track ball.
Is this function bugged and needs to be disabled until a fix has been made?

**Comment by Tiberiusmoon** [comment]
Edit: track ball causes freezing when enabled full stop, i realised that once the logs start spamming the app slows and locks up.

**Comment by mika-n** [comment]
i could not replicate the issue (V2.0.3) and didn't see any "index out of bounds: touchpad" exception error messages (disabled Slide option in "Use touchpad as mouse" screen and enabled Trackball option). 
Would you please post a screenshot of the "Use touchpad as mouse" sceren or the whole profile file?

The "index ouf of bounds: touchpad" exception is definitely something which causes major problems and slow downs if the exception is thrown everytime a gamepad data packet is processed. If you use touchpad as a "normal mouse" (no trackball or scroll enabled) then does it work without problems and no out-of-bounds errors? The strange thing is that if the error is coming from a routine handling incoming touchpad data packets then it is identical routine in all cases (use as mouse, with or without slide, trackball, scroll options).

**Comment by Tiberiusmoon** [comment]
Video of the issue: https://www.youtube.com/watch?v=A56QCzPdUCI
when i start circling the track pad it triggers it

[test.zip](https://github.com/Ryochan7/DS4Windows/files/4031317/test.zip)

**Comment by Tiberiusmoon** [comment]
the Zip has the profile used

**Comment by Ryochan7** [comment]
Tried reproducing the problem on my end but I cannot get the program to throw errors. Although, the error is likely not the out of bounds error that is being printed. With the way the code is set up, that is a blanket message that is displayed when any exception is thrown in the touchpad routine. That should probably be changed to display the original exception message with a mention of the touchpad routine as the source.

**Comment by mika-n** [comment]
I could not replicate the issue even when using the profile file in TEST.ZIP file and trying to do all kind of crazy movements in a touchpad. 

Tiberiusmoon seems to have "Razer Raiju PS4" (usb) gamepad. I have only Sony DS4 rev1 and rev2 gamepads here. Could be that the RazerRaijuPS4 gamepad may have something to do with the issue. Maybe RaijuPS4 sends wrong or incomplete touchpad data fields when a finger makes rapidly some wild movements? Anyway. I guess the exception handler should be modified to show the real error message and call stack and hope it gives more clues why touchpad routines fail.

@Tiberiusmoon  Did you try to use touchpad as a normal mouse without trackball or scroll options in DS4Windows "use as mouse" screen? And then doing the same wild finger movements. If the problem is in the data packets sent by RaijuPS4 gamepad then it should give the same exception even without trackball option. If the error does not pop up in this "normal" scenario then the issue is somewhere in trackball routines.

**Comment by Tiberiusmoon** [comment]
@mika-n the use as a mouse will function normally when enabled its just as soon as the trackball is enabled it comes up with errors.

**Comment by mika-n** [comment]
@Tiberiusmoon  Here is a link to debug version of V2.0.3 DS4Windows app which should show more details about the "index out of bounds: touchpad" scenario. You can extract the debug zip file into the same folder with official V2.x release and then run the DS4WindowsDebug.exe instead of the official exe version.  

Looks like Sony DS4 gamepads don't seem to suffer from this error (can't get it to crash in the same scenario), but hopefully the more detailed log file will tell us why and where exactly the app crashes in your environment.

https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by Tiberiusmoon** [comment]
[Debug.txt](https://github.com/Ryochan7/DS4Windows/files/4036987/Debug.txt)

The spammed log mentions <Function does not accept floating point Not-a-Number values>

**Comment by mika-n** [comment]
Still difficult to say exactly where the error happens based on that error message. There is now a new debug version which does additional checks in touchpad/trackball routines and hopefully these messages help to pinpoint the exact problem. Please try to run the new DS4WindowsDebug.exe version.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by Ryochan7** [comment]
Not sure where it could be but it seems like the routine is likely failing when calling one of the static Math functions. It looks like **System.ArithmeticException** is the exception being thrown based on the message.

**Comment by Tiberiusmoon** [comment]
[debug.txt](https://github.com/Ryochan7/DS4Windows/files/4047987/debug.txt)

**Comment by Tiberiusmoon** [comment]
Oh btw, im learning C# to understand OW's workshop better and have visual studio installed.
If some of the tools in that can help a lot better, you can guide me through it

**Comment by Ryochan7** [comment]
Learning how to use the Visual Studio Debugger will definitely help find the issue. VS should stop program execution when **System.ArithmeticException** is thrown so you can take a look at the current values of variables on the stack. From what I see, the only time this type of issue should ever happen is if the for loop the iterates over the two buffer arrays is never executed. That would cause a division by zero problem and then result in Double.NaN being passed to **Math.Sign**. That situation should never happen though.

**Comment by Tiberiusmoon** [comment]
I keep getting this: https://i.imgur.com/EyXSNxp.jpg

**Comment by Ryochan7** [comment]
You need to compile a Debug build of the program so you can set up breakpoints in VS. Also, please compile against the x64 target not the AnyCPU target.

![ds4win_config_example](https://user-images.githubusercontent.com/581968/72192466-786cdf00-33cb-11ea-8d61-76a8281ddaf3.png)

**Comment by Tiberiusmoon** [comment]
what am i doing wrong? the build keeps failing https://i.imgur.com/SOBsLRG.jpg

**Comment by mika-n** [comment]
Hmm... The new exception logfile does help to pinpoint the location where the trackball bug happens there. However because it doesn't seem to happen with native DS4 gamepads (or some other difference in environment) it is a bit difficult to "virtually debug". Anyway. Here is yet-another-debug version with additonal checks in Mouse.TouchesEnded method to check if finalWeight will end up being zero value (it is used as divider) and if so then why.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by Ryochan7** [comment]
Can't see the output where building fails. Which tools have you installed in VS? You should have everything needed to compile DS4Windows if you have installed the **.NET desktop development** Workload and also the **.NET Framework 4.6.2 development tools** optional component. You can navigating to **Tools > Get Tools and Features** in the main menu and click the item to open the Visual Studio Feature Installer window.

**Comment by Tiberiusmoon** [comment]
[debug.txt](https://github.com/Ryochan7/DS4Windows/files/4049814/debug.txt)

**Comment by Tiberiusmoon** [comment]
@Ryochan7  Ahh it was one of those im missing. 
Okay so once its running what thing to i need to bring up to identify the issue once the break point is done?

**Comment by mika-n** [comment]
Hmm.. Strange. The problem was not Mouse.TouchesEnded finalWeight variable being zero (could happen in theory if ring buffer trackBallBuffer was never iterated). Veeeery strange. Looks like you have to debug this with VC debugger to get the actual context around the problem. I don't understand how trackballXVel and trackballYVel variables could end up being "not available/undefined". I assume the exception comes when TouchesEnded method does Math.Sign(trackballXVel) call.

**Comment by Tiberiusmoon** [comment]
@mika-n I was thinking, once i finish studying up the C# in codeacademy i could look at modifying DS4 visually and see how it goes, if its too complicated then ill just leave it xD

**Comment by Tiberiusmoon** [comment]
@Ryochan7 
Is this it? https://i.imgur.com/eLEcquF.jpg
The breakpoint wont stop the debug

Im just not sure how to gather use Visual studio to identify what line of code is run

**Comment by mika-n** [comment]
hopefully the latest version has fixed this issue as part of other changes. closing as "inactive" ticket.
