### ISSUE TITLE
How to emulate gyro and touchpad as normal?

### ISSUE THREAD

**Issue by daninthemix** [Ryochan7/DS4Windows#1026]
Having a profile run in DS4 mode (to present the controller AS a PS4 controller) is helpful, but how do we ensure the gyro and touchpad controls are as normal? I don't want to map them to keys or other commands - I just want the gyro to be a gyro, and the touchpad to be a touchpad.

Thanks

EDIT: For context, this is useful when a game natively supports DS4, but for example Heavy Rain - has native DS4 support, but doesn't recognise my wireless DS4 unless I'm running DS4Windows. Not to mention all the lightbar functionality, remapping and other things that you can when running DS4Windows as opposed to not.

**Comment by mika-n** [comment]
Sorry, but at the moment "passthrogh touchpad and gyro" functionality is not possible. ViGem driver used by DS4Windows app does not support true touchpad/gyro events (yet).
https://github.com/Ryochan7/DS4Windows/issues/952#issuecomment-569121355

This has been discussed in ViGem site, but no "landing time" for such a feature yet.
https://github.com/ViGEm/ViGEmBus/issues

You should be able to use touchpad and gyro as a native DS4 gamepad over USB connection, but unfortnately WinOS doesn't support those extra DS4 features over BT. DS4Windows app solves this issue by using the gameapd in "raw true DS4 mode" even in BT, but the result of this "true ds4 mode in BT" is a dead DS4 gamepad device in WinOS. DS4Windows app solves this by creating a virtual output gamepad device on the fly (by using ViGem driver services). Unfortunately current version of Vigem doesn't expose true touchpad and gyro events, so DS4Windows app cannot passthrough those events to a virtual dualshock4 gamepad.

You may be able to do all this if you spend $50 to purchase Sony Wireless Adapter gadget. It sits between BT and DS4 gamepad and fools WinOS to see the gamepad in true native DS4 mode. However, it is a hardware level solution and Sony probably released the gadget because of those WinOS level issues ("dead HID ds4 device in BT").

**Comment by daninthemix** [comment]
That's a shame, and annoyingly Sony no longer makes the official wireless dongle.

**Comment by Ryochan7** [comment]
People gave the Sony Wireless Adapter a lot of hate but it is actually a pretty good piece of hardware. It is my preferred way to connect my DS4 to my PC. Some games that natively support the DS4 don't support the adapter though (Rocket League, The Witcher 3) so DS4 emulation is required for proper button prompts.

**Comment by cascardian** [comment]
I suggest submitting this to the Windows 10 Feedback Hub as a feature request for the BT stack and then post about it on the [Windows 10 subreddit](www.reddit.com/r/windows10) for good measure. This honestly _should_ be properly handled by the OS instead of a hardware device or third-party driver working around the issue.
