### ISSUE TITLE
DS4Windows not detecting controller

### ISSUE THREAD

**Issue by Piotr88e** [Ryochan7/DS4Windows#1030]
When i plug in my controller it doesn't do anything, the controller is just charging.

**Comment by Tiberiusmoon** [comment]
Is the controller detected by DS4 Windows in the controller tab?

**Comment by mika-n** [comment]
See the Troubleshooting doc page for more info. If you still cannot get the gamepad working then please provide the minimum information required because now your original message really didn't give any details (WinOS version? Gamepad type and model? DS4Windows app version? Content of Logs tab page in DS4Windows app or "%APPDATA%\DS4Windows\Log" logfile?)
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

There is also a special debug version available which should give more details about potential gamepad connection issues. Please download the debug ZIP file from the Troubleshooting page and follow the instructions to generate a detailed log file.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems
