### ISSUE TITLE
@mika-n DS4 windows Log system 

### ISSUE THREAD

**Issue by Tiberiusmoon** [Ryochan7/DS4Windows#1032]
Why not have the debug stuff included with the normal DS4 install?
You could move the Auto profile debug check box to the log tab along with a Advanced debug check box for this:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by mika-n** [comment]
"Auto-profile debug messages" option is specifically meant to be used only while debugging auto-profile rules (if it is not clear what process name or window title should be used as a keyword to detect a certain app or window). That's why the option is in auto-profile screen. It is just a runtime option and it is never saved to any of the config files because otherwise people would just accidentally forget it on even when the app or PC is restarted.

The debug version does a lot more than just dumps out those additional messages. There are some special tricks to handle (incoming and outgoing HID data packets) and detect previously unknown gamepads and that code is not very clean (it is a quick-and-dirty just-do-it type of code). 

But you are correct that some of the debug messages would be handy in the vanilla version also to diagnose various problems to connect or use gamepads. The old WinForms version didn't have log file (text file, not just Logs tab page) support at all, so messages were kept at minimum to avoid flooding the Logs tab page. Now when V2.x version support proper log files then having an option "LogLevel=Nothing/Error/Warning/Info/Debug" would be possible.

**Comment by Tiberiusmoon** [comment]
sounds good :)
