### ISSUE TITLE
l10n

### ISSUE THREAD

**Issue by DragonZX** [Ryochan7/DS4Windows#1041]
Did you find any tool to parse [that](https://docs.google.com/spreadsheets/d/1ZyHta7h1Zuirq6X84fp8_eFszGFsxNlICjnG_CfuKMc/edit?usp=sharing), when forking?

**Comment by DragonZX** [comment]
I've found old resx translations in the original repo, working on it

**Comment by Ryochan7** [comment]
The resx files are just XML files so it wouldn't be too hard to make a parser if necessary. Due to how incomplete many translations were, I made the executive decision to just start from scratch at least for the form specific translation strings. The general Resource strings could probably just be carried over from the old code base; I would have to check with diff to see how much the old base Resources.resx and new Resources.resx files differ.

You don't have to go back to the old repo to find the previous resx files. The version 1.7.28 source code is available in the winforms branch. I wanted to keep a reference to the old code around for code review. Having easier access to the old code has come in handy a few times already.

https://github.com/Ryochan7/DS4Windows/tree/winforms

**Comment by mika-n** [comment]
What is the difference between Resource.resx string and Strings.resx localization strings in V2.x code base? All textual localizations could be in the same Strings.resx file?

**Comment by Ryochan7** [comment]
Resources.resx is mainly used by some classes in the DS4Control package; IIRC it was also used to populate the hover text for the old Options form. Strings.resx could be considered a replacement for the various old form specific resx files. The old Resources.resx file was not touched much to minimize differences in the non-form code while I was maintaining both code base.

At this point, the two could potentially be merged. The old Resources.resx file could then just be delegated to holding references to some images used by the program.

**Comment by DragonZX** [comment]
So DS4forms.resx is deprecated and doesn't need anymore
