### ISSUE TITLE
controller doesn't properly recognized USB 2.0

### ISSUE THREAD

**Issue by trans19** [Ryochan7/DS4Windows#1044]
DS4Windows can't read the battery percent and can't load the profiles when connected via USB 2.0, but if connected via USB 3.0 it works properly
![image](https://user-images.githubusercontent.com/21072243/72496166-64a5fa80-385b-11ea-949b-7620749b5a51.png)
USB 3.0
![image](https://user-images.githubusercontent.com/21072243/72496208-7f786f00-385b-11ea-87ce-fd1e59b27a51.png)
USB 2.0

**Comment by Tiberiusmoon** [comment]
What motherboard do you have?

**Comment by mika-n** [comment]
Very weird. I don't understand why you cannot change a profile in USB2 connection because the gamepad is clearly recognized (MAC address shown in the screenshot) and seems to be in "connected" state. Do you see any error messages in Logs tabpage or in "%APPDATA%\DS4Windows\Log" logfile folder?

Maybe the usb2 cable is bad? I have several mobile phone usb cables which can charge DS4 gamepad, but PC or PS4 console doesn't recognize those over usb. Those cables probably don't connect all required data lines. Try different cable or usb2 ports or hub. Well, if it works over USB3 then no big issue and I must say that the issue is 999.999% in your PC and not in DS4Windows app.

**Comment by trans19** [comment]
> What motherboard do you have?

ASRock AB350 Pro

**Comment by trans19** [comment]
> Very weird. I don't understand why you cannot change a profile in USB2 connection because the gamepad is clearly recognized (MAC address shown in the screenshot) and seems to be in "connected" state. Do you see any error messages in Logs tabpage or in "%APPDATA%\DS4Windows\Log" logfile folder?
> 
> Maybe the usb2 cable is bad? I have several mobile phone usb cables which can charge DS4 gamepad, but PC or PS4 console doesn't recognize those over usb. Those cables probably don't connect all required data lines. Try different cable or usb2 ports or hub. Maybe the power rail of your usb2 ports is bad?
> 
> Well, if it works over USB3 then no big issue and I must say that the issue is 999.999% in your PC and not in DS4Windows app.

Well, I already tried using other cables, still no luck
my problem of using USB3 is all of them are occupied with external hdd, the only one available is the one on the front panel which is on top of the case and I don't have a cable that long enough for it
and probably you're right, maybe there's some problem with my windows installation because it used to worked before. I'll try reinstall my windows once the SSD are coming. Thanks for helping me

**Comment by Tiberiusmoon** [comment]
> 
> 
> > What motherboard do you have?
> 
> ASRock AB350 Pro

Hmm have you checked your drivers and bios is up to date?
https://www.asrock.com/mb/AMD/AB350%20Pro4/#Download

There is a way to repair OS files in windows 10,
Open cmd prompt in admin.
Then run this: DISM.exe /Online /Cleanup-image /Restorehealth
after its done do: sfc /scannow

lastly you can open device manager and check all your usb 3.0 hubs, storage controllers and chipset devices (under system devices)
if that all fails then idk
