### ISSUE TITLE
(Gyro) Improper value reporting on gyro X-axis

### ISSUE THREAD

**Issue by BlackPowerade** [Ryochan7/DS4Windows#1045]
DS4Windows seems to be giving an incorrect value on the gyro X axis.
Tilting to the right shows all is working normal:

![Screenshot (43)](https://user-images.githubusercontent.com/21957509/72496646-380cc700-37f8-11ea-9dd2-2975d79ac8b4.png)

However tilting to the left shows the reported value as all the way to the right: 

![Screenshot (44)](https://user-images.githubusercontent.com/21957509/72496688-5e326700-37f8-11ea-96b9-9c151fc62e94.png)

Seems like this might be somewhat related to #929. 
I'm using a V2 DS4, if that matters.

**Comment by mika-n** [comment]
The issue you linked #929 is probably not what you are seeing here. To my knowledge only some DS4 revision1 gamepads had that inverted gyro axis problem. Never seen anyone reporting it with DS4 rev2 gamepads. I guess some earlier batch of DS4 rev1 gamepads had the inverted gyro hardware or firmware bug. Anyway. DS4Windows app workarounds that issue nowadays in software side.

Your issue is probably because of the profile settings you are using (or there is a bug in DS4Windows with certain profile settinsg). The black dot in ControllerReadings shows the physical gyro reading and if the gamepad had the "inverted gyro bug" then this should be inverted also. The gray dot is a result of output re-map rules. If it goes wild then there is something weird in the profile or bug in SD4Windows settings. 

Please share the profile file here (attach it to comment here). 
And try creating a new default profile with default values. Is ControllerReading showing correct gyro movement with a default profile? If it is then the issue is not in your hardware, but in profile settings.

**Comment by BlackPowerade** [comment]
The same behavior is shown when using a new default profile. Tilting to the left results in the reported value all the way to the right.
Here is my profile:
[Gyro stick.xml](https://github.com/Ryochan7/DS4Windows/files/4074195/Gyro.stick.txt)

**Comment by BlackPowerade** [comment]
@mika-n I have found a new development.
It looks like the source of the problem is the Enhanced-Precision output curve. Using the linear output gives correct readings.
I will test the other output curves later and see if they have this issue as well.

**Comment by mika-n** [comment]
Confirmed. Actually the same effect (=gyro X-axis jumps all the way to right on ControllerReadings) happens with other custom output curves also, not just with EnhancedPrecision curve. The strange thing is that the bug does't hit right away but after a while tilting the controller left to right (and up to down). There comes a short half a second freezing in ControllerReadings values and then the bug hits.  The bug is "temporarly fixed" when the output curve is changed to other value until the bug hits there also.

This must be some weird bug in output curve handling in V2.x version (some internal state or output re-direction goes wooooe). Nothing wrong in your gamepad. For now until the bug is fixed you may have to use Linear output curve in GyroX and GyroY axies.

**Comment by Ryochan7** [comment]
There were two problems involved with the Gyro controls. The big one was due to invalid type casting being done for some of the output curves. It was mainly due to not adapting the code after a copy paste. There was also a calculation problem with the Easeout Cubic curve for the Gyro.
