### ISSUE TITLE
Alternately being detected as a XBox and a PlayStation controller in log

### ISSUE THREAD

**Issue by Cupbox** [Ryochan7/DS4Windows#1047]
While I don't have any problems in day to day operation (wired), I do get slight lag sometimes. On checking the log I found the following. I'd appreciate some help
Windows 10 
01/17/2020 00:14:50: DS4Windows version 2.0.4
01/17/2020 00:14:50: Starting...
01/17/2020 00:14:50: Connection to ViGEmBus 1.16.112.0 established
01/17/2020 00:14:50: Searching for controllers...
01/17/2020 00:14:50: Using Shared Mode
01/17/2020 00:14:51: Found Controller: A4:15:66:87:65:68 (USB) (DS4 v.1)
01/17/2020 00:14:51: Plugging in DS4 Controller for input #1
01/17/2020 00:14:51: Controller 1 is using Profile "Anki"
01/17/2020 00:45:49: Unplugging DS4 Controller for input #1
01/17/2020 00:45:49: Plugging in X360 Controller for input #1
01/17/2020 00:46:20: Unplugging X360 Controller for input #1
01/17/2020 00:46:20: Plugging in DS4 Controller for input #1
01/17/2020 08:26:05: Unplugging DS4 Controller for input #1
01/17/2020 08:26:05: Plugging in X360 Controller for input #1
01/17/2020 08:26:08: Unplugging X360 Controller for input #1
01/17/2020 08:26:08: Plugging in DS4 Controller for input #1
01/17/2020 08:26:10: Unplugging DS4 Controller for input #1
01/17/2020 08:26:10: Plugging in X360 Controller for input #1
01/17/2020 08:26:20: Unplugging X360 Controller for input #1
01/17/2020 08:26:20: Plugging in DS4 Controller for input #1
01/17/2020 08:26:37: Unplugging DS4 Controller for input #1
01/17/2020 08:26:37: Plugging in X360 Controller for input #1
01/17/2020 08:26:38: Unplugging X360 Controller for input #1
01/17/2020 08:26:38: Plugging in DS4 Controller for input #1
01/17/2020 08:26:40: Unplugging DS4 Controller for input #1
01/17/2020 08:26:40: Plugging in X360 Controller for input #1
01/17/2020 08:27:16: Unplugging X360 Controller for input #1
01/17/2020 08:27:16: Plugging in DS4 Controller for input #1
01/17/2020 08:27:33: Unplugging DS4 Controller for input #1
01/17/2020 08:27:33: Plugging in X360 Controller for input #1
01/17/2020 08:27:35: Unplugging X360 Controller for input #1
01/17/2020 08:27:35: Plugging in DS4 Controller for input #1
01/17/2020 08:37:38: Unplugging DS4 Controller for input #1
01/17/2020 08:37:38: Plugging in X360 Controller for input #1
01/17/2020 08:37:50: Unplugging X360 Controller for input #1
01/17/2020 08:37:50: Plugging in DS4 Controller for input #1

**Comment by mika-n** [comment]
hmmmm... The log file shows that DS4Windows app keeps switching between x360 and ds4 output modes. 

Do you use auto-profile feature to switch between different profiles? Maybe the default profile is in x360 mode and the Anki profile is in ds4 mode. By default DS4Windows app reverts back to default profile when auto-profile feature detects an unknown process. You can change this logic by unticking "Revert back to default profile on unknown process" option in auto-profile screen. Also, if you enable the "Show auto-profile debug messages" option  then you should see detailed messages if this issue is because of auto-profiler.

If you don't use auto-profile feature then I can't think of anything else but you have a loose USB cable connection and the connection is sometimes lost.

**Comment by Cupbox** [comment]
That solved it. Some of my older profiles had X360 selected. 
Thank you so much for the help.
