### ISSUE TITLE
Flash lightbar at High Latency

### ISSUE THREAD

**Issue by Dyna-007** [Ryochan7/DS4Windows#1053]
Hello im not sur if is a bug but the ''Flash lightbar at hight latency'' cant be edited
my controller rarely hit 13ms i want to change the value be default but dont semble to work or afect at all event putting 100ms he dont work still trigger the 10ms warring is a bug ?
thank you

**Comment by mika-n** [comment]
Confirmed. There is a bug in how "Flash lightbar at high latency XX ms" value is shown and saved in the GUI (ie. always showing the default value).

Fortunately there is a local workaround you can use until the bug is fixed. Open "%APPDATA%\DS4Windows\Profiles..xml" config file in a Notepad and modify FlashWhenLateAt option to 100 value. DS4Windows app uses this value from the config file even when the GUI shows a wrong value.

```
<FlashWhenLate>True</FlashWhenLate>
**<FlashWhenLateAt>100</FlashWhenLateAt>**
```

**Comment by Dyna-007** [comment]
Hello i noticed thos line are no be default in the file .xml
so i entred thos value in my  Default.xml and still dont work still getting the warring 10ms some time
thank for you time

**Comment by mika-n** [comment]
This FlashWhenLateAt option is NOT profile specific, but an application level option (ie. common value for all profiles). Just edit the file I mentioned and not those XML files below Profiles folder.

If you use the "Profile Folder" link in DS4Windows app to open a profile folder then just navigate from there one step above to the root of the DS4Windows settings folder. There should be Profiles.xml file.

**Comment by Dyna-007** [comment]
Oh ok understand what you mean now 
well hope this will get fixed 
thank for your time and help.

**Comment by Dyna-007** [comment]
last update fxed the probleme
