### ISSUE TITLE
DS4Windows doesn't support more than 4 DS4?

### ISSUE THREAD

**Issue by apoklyps3** [Ryochan7/DS4Windows#1054]
my friends and I do alot of bomberman sessions and yesterday we got a 5th player, but was unable to get any DS4 beyond no.4 to show up in DS4Windows, neighter via BT or wired...
Can this be fixed?

**Comment by mika-n** [comment]
This has been discussed before and the current code base has zillions of locations where it is assumed that the max number of gamepads is 4. Technically it would be possible to have something like 4 gamepad profiles in xbox360 mode and 4 gamepad profiles in dualshock4 mode to have 4+4 gamepads. But I doubt this kind of code change is anywhere in near future because the magical number 4 is so wide spread in the code.

**Comment by apoklyps3** [comment]
bummer :(
