### ISSUE TITLE
Color by Battery %

### ISSUE THREAD

**Issue by mccorkled** [Ryochan7/DS4Windows#1061]
I have enabled the color by battery percent option but since I have my colors dimmed down to 10% they are mixing the colors. Is there any way to have them controlled separately? 

10% blue - full charge
10% orange - at 50% charge
10% red - 10% charge

Also, when I enable "Pulse at", the controller goes to full brightness when the selected percentage is hit rather than staying at the 10% I have selected for the main color.

**Comment by Ryochan7** [comment]
The full and empty colors are supposed to mix when using "Color by Battery %" mode. The color will transition from the Full color to the Empty color as the controller's battery gets depleted. Also, Pulse At is likely using a different color than what you set for the Main color. You would need to set the Pulse At color to Black in order to have it use the profile's Main color while pulsing.

**Comment by mccorkled** [comment]
Sorry I had not seen your reply. 

The problem I see with the colors transitioning, is that you cannot use primary colors. As far as the pulse, I want it to pulse red, which is what I have set, but like I mentioned it is full brightness. If this was added in a future version I would really appreciate it.
