### ISSUE TITLE
Stick drift and jittering only with DS4Windows

### ISSUE THREAD

**Issue by dom19111** [Ryochan7/DS4Windows#1070]
Hey! 

I am trying to setup a wireless setup and would prefer to use DS4Windows over the native Steam integration is it appears to have much more input lag for some reason.

However DS4Windows is unfortunately giving me crazy left and right stick drift. I have to mention that my right stick occasionally has a slight drift itself when it is wired and in other tools but nowhere near the level that I am currently experiencing and definitely not with the left stick too.

Below you can see my settings as well as the actual drift.
Thanks so much for any help!

![Capture](https://user-images.githubusercontent.com/60272024/73096925-476dcd80-3ee6-11ea-9e86-166361867e3c.PNG)

**Comment by mika-n** [comment]
Please share the profile file as an attachment in a comment field here.
You do seem to have deadzone which is often required to avoid drifting in LS/RS sticks. But you also have anti-deadzone set, so that's why the profile file you use might be useful to see if there is something else also going on. 
https://github.com/Ryochan7/DS4Windows/wiki/Settings#deadzone

**Comment by MrInterBugs** [comment]
I am also getting drift but only with this fork of DS4Windows the main repo is fine and so is using the controller through steam.

**Comment by mika-n** [comment]
You seem to have zero deadzone. The Jay2Kings and Steam apps have a built-in deadzone you cannot remove. This Ryochan7 version of DS4Windows allows to use zero deadzone because in some scenarios it is useful, but in most cases LS/RS/gyro needs to have some deadzone to avoid that hardware level jittering. See the earlier post and link to Settings-DeadZone.

Also, are you using anti-deadzone or output curve setting? Make sure you have the latest version because some earlier 2.x version had a bug in output curve and anti-deadzone calculations.
https://github.com/Ryochan7/DS4Windows/releases

**Comment by Ryochan7** [comment]
Found the post I wanted to reference. People had mentioned similar posts before but I could never reproduce the results even when using said profiles. Due to a related issue and tweaking the Controller Readings tab, I decided to experiment with something quick and I think I finally see what is being observed. Not enough contextual info was given in prior posts.

As mentioned in issue #1149, any profile opened from the Profiles tab will associate the readings tab with the first controller. However, the output values (gray squares) shown in the Controller Readings tab will reflect the mapping associated with the currently assigned profile for input slot 1 rather than the current profile being edited. I know the old WinForms code base worked the same way but I will go back to the Jays2Kings version to see how it works there.

That is the primary reason the values do not match up with the settings in the Profile Editor. Also, this is another case of people using DS4Windows in a way that I do not. For the most part, if you want to make use of the Controller Readings tab, make sure to select the profile to Edit from the Controllers tab rather than from the Profile tab. Also, it would usually be better to check the final output from HTML5 Gamepad Tester. There is a link in the Settings tab.

https://html5gamepad.com/

**Comment by Ryochan7** [comment]
Jays2Kings version of Controller Readings did very little and was completely dependent on the values in the UI elements. Output from curve and sensitivity changes were calculated in the UI layer as opposed to using the final values from the input thread.
