### ISSUE TITLE
DS4Windows(?) causing system reboot while gaming

### ISSUE THREAD

**Issue by Omniphantasm** [Ryochan7/DS4Windows#1074]
Update: Crashed again, DS4Windows was shut off and yet reliability report says DS4Windows.exe stopped working....even though the exe wasn't even loaded according to Task Manager.

OS: Windows 10

Problem: In both Arkham Knight and Styx 2 I've gotten a complete reboot with no warning on multiple occasions. Usually it just says "Windows was not shut down properly" in the reliability report but this time I actually got a "DS4Windows stopped working" as well so it's led me to thinking it may actually be the issue.

Upgraded from GTX 970 to RX 5700 and thought it might be some wonky driver issue but after a lot of troubleshooting, reinstalled drivers and even a complete format of the system it's starting to look a lot like DS4Windows may be the culprit to some degree. 

"Fix" so far: ~~Turned off~~ (didn't work) **Uninstalled** DS4+ViGeM and haven't crashed again two hours of game play in known affected games. Usually I'll crash within 30-60 minutes when it's on.

If anyone's got any suggestions on what the hell's going on I'd be happy to try them.

Things I've checked.
PSU Isn't faulty and has enough power
Ran Furmark+Prime95 for over an hour and temps were fine and system stayed stable

Reliability Report:

Source
DS4Windows

Summary
Stopped working

Description
Faulting Application Path:	O:\DS4Windows\DS4Windows.exe

Problem signature
Problem Event Name:	CLR20r3
Problem Signature 01:	DS4Windows.exe
Problem Signature 02:	2.0.6.0
Problem Signature 03:	98948424
Problem Signature 04:	DS4Windows
Problem Signature 05:	2.0.6.0
Problem Signature 06:	98948424
Problem Signature 07:	530
Problem Signature 08:	0
Problem Signature 09:	System.NullReferenceException
OS Version:	10.0.18363.2.0.0.768.101
Locale ID:	1033
Additional Information 1:	61ef
Additional Information 2:	61efa3ebcd26784f16d0bab9b78f6582
Additional Information 3:	631c
Additional Information 4:	631c6b3f0fc267b788fffea9e1f8a25b

Extra information about the problem
Bucket ID:	201b195728ce4b035a5656df89c0c9dd (1897799811072051677)

**Comment by mika-n** [comment]
>Update: Crashed again, DS4Windows was shut off and yet reliability report says DS4Windows.exe >stopped working....even though the exe wasn't even loaded according to Task Manager.

Hmmm... I have to say that something like this is not technically possible because if DS4Windows process is really not running then the app doesn't leave behind any background services etc..... So somehow the DS4Windows process must have been still running (or being stuck in shutdown sequence and then eventually crashed).

NullReferenceException sounds like a bug somewhere in the app (trying to access no existent or already deleted objects), but where? Difficult to tell based on that error message. Do you see anything in folder "%APPDATA%\ds4windows\log\" and log files?

Or maybe the error was thrown from .NET framework libraries? Try installing the latest .NET Framework library versions from Microsoft web site.

**Comment by Omniphantasm** [comment]
Bleh, seems like it wasn't after all. I completely stripped DS4 from system last night didn't crash after 2 hours of gameplay but just experienced the crash after 30 minutes of game-play today.

Back to trying to find an unknown cause of instability with little to no information!
