### ISSUE TITLE
PS4 Controller

### ISSUE THREAD

**Issue by Emanuele-1998** [Ryochan7/DS4Windows#1082]
Why DualShock 4 in game as a watch dogs 2 recognize the DualShock 4 as a xbox controller? In the watch dogs there is a possibility the ability to set in ps4 instead of xbox

**Comment by Ryochan7** [comment]
From README.

> DS4Windows is an extract anywhere program that allows you to get the best DualShock 4 experience on your PC. By emulating a Xbox 360 controller, many more games are accessible.

![zoomer](https://user-images.githubusercontent.com/581968/73403650-84a2d880-42b5-11ea-93d6-00eeee637700.png)

On a more serious note, for games that have native support for the DS4, check out the Controller option in the Profile Editor and set it to **DualShock 4**. Just take note that neither the touchpad nor gyro capabilities of the DS4 will be usable due to limitations in the ViGEmBus driver. You would need to resort to using the DS4 without running DS4Windows for games that utilize those features; some examples would be the PC ports of Heavy Rain and Detroit: Become Human.

![ds4win_output_controller](https://user-images.githubusercontent.com/581968/73404050-62f62100-42b6-11ea-9ba2-40ffdbee0efe.png)

**Comment by Emanuele-1998** [comment]
This piece there isn’t in readme 

On a more serious note, for games that have native support for the DS4, check out the Controller option in the Profile Editor and set it to DualShock 4. Just take note that neither the touchpad nor gyro capabilities of the DS4 will be usable due to limitations in the ViGEmBus driver. You would need to resort to using the DS4 without running DS4Windows for games that utilize those features; some examples would be the PC ports of Heavy Rain and Detroit: Become Human.
