### ISSUE TITLE
Add switchable touchpad special action

### ISSUE THREAD

**Issue by apoklyps3** [Ryochan7/DS4Windows#1083]
Please add possibility to switch between mouse and controls on the touchpad as a special action.

**Comment by apoklyps3** [comment]
Please add possibility to switch between mouse and controls on the touchpad as a special action.

**Comment by mika-n** [comment]
Why not to use two profiles, one with "Use as mouse" and other one "Use as control" option and switch between these profiles via a special action trigger key. There is no point creating a spec action to switch between single profile options because it would be a never ending story. Someone else might wanna switch other options and so on. The ability to switch whole profiles works with all options available per profile.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#how-to-change-a-profile-on-the-fly-via-a-certain-gamepad-button-using-a-special-action

If you have done lots of re-map rules in your existing profile then take a copy of the profile and then just change the touchpad option on the copy and there you go....

**Comment by Ryochan7** [comment]
That type of functionality would be better implemented as an Action Set for the profile. Unfortunately, I don't see Action Set functionality ever getting implemented in DS4Windows. It would be too much of a hassle to try to adapt the current mapping routine. Work was being done on a different mapping system but I have not worked on it in the past few months. I would like to get something out by the end of 2020.

**Comment by apoklyps3** [comment]
Agreed
