### ISSUE TITLE
bluetooth pairs then disconnects 

### ISSUE THREAD

**Issue by Toastysunlight** [Ryochan7/DS4Windows#1086]
DS4 windows was working fine then all the of the sudden my controller loses connection 
i've reinstalled DS4 and updated bluetooth no luck Plugging does nothing.
[log.txt](https://github.com/Ryochan7/DS4Windows/files/4141886/log.txt)

**Comment by mika-n** [comment]
Hmm... The gamepad seems to be official DS4 v2, but for some reason BT communication fails. You could try tweak DS4WindowsDebug.exe.config option to disable, for example, gyro calibration  (set Debug_GyroCalibration option to false value). And if it still doesn't work then try to set Debug_SendRumbleLightbarData to false also.

Anyway. This seems to be more like a PC/WindowsOS side issue and not DS4Wndows issue if bluetooth communication stack fails. Try to update BT drivers and settings, remove all BT pairings.

If you really cannot get it to work then maybe trying to remove BT drivers and letting Windows to re-install those in the next reboot (in case BT stack is screwed up at the moment).

If you have old ScpVBus driver installed then try to get rid of those because it is often a source of all sort of incompatibility problems.

**Comment by Toastysunlight** [comment]
No changes same result from logs. I've reinstalled BT. Removed all pairings. SCP driver was not installed. I've check using driver store explorer. any more suggestions?

**Comment by mika-n** [comment]
Is the BT gamepad shown in WinOS JOY.CPL controlPanel applet as WirelessController when you pair and connect it WITHOUT running DS4Windows app? Of course this way rumble/lightbar/touchpad won't work, but all "normal" buttons should work. If the gamepad doesn't show up there then there must be something broken in WinOS side because the minimum requirement is to get WinOS to recognize the BT gamepad even when WinOS doesn't know how to use those extra DS4 features.

**Comment by Toastysunlight** [comment]
I'm not sure what i first downloaded Version 1.7.28 nothing happened. I downloaded Jays2Kings's DS4. By some miracle my ps4 controller was labeled and installed as a 360 controller then as a HID-game controller automatically  i closed and load up Ryochan's DS4 current version and they both read the controller now. There's two controllers I'm so confused. 
[Log2.txt](https://github.com/Ryochan7/DS4Windows/files/4145708/Log2.txt)
![Screenshot (91)](https://user-images.githubusercontent.com/60496353/73617259-9a740e80-45d1-11ea-9dec-594da9f0e053.png)

**Comment by mika-n** [comment]
Starnge. Recently there has been at least one other report that simply downloading the latest DS4Wndows version directly from Releases-page and re-installing it fixed weird BT connection issue (https://github.com/Ryochan7/DS4Windows/issues/1089#issuecomment-581156586)

I don't understand how and what is different in re-installation that it fixes BT connection issues. DS4Windows app itself should not have direct impact on how BT stack works on WinOS level.

Anyway, the new debug logfile you provided looks perfect and what is expected from a DS4 gamepad in BT connection.

Releases: https://github.com/Ryochan7/DS4Windows/releases

**Comment by Toastysunlight** [comment]
Thanks for you help Mika, everything works fine now.  i still find it strange how a version from 2016, was able to detect my controller. and not cause any incompatibility issues.
