### ISSUE TITLE
Razer Raiju TE & Ultimate support in vanilla version?

### ISSUE THREAD

**Issue by AMBIztw** [Ryochan7/DS4Windows#1087]
Hey @Ryochan7 & @mika-n!

Do you remember [this](https://github.com/Ryochan7/DS4Windows/issues/988) topic?

Waiting for **Razer Raiju TE & Ultimate** support in vanilla version so much!
Now we only can use the debug version.

Thanks a lot in advance!

**Comment by mika-n** [comment]
Yes. This is in my TODO list. Soon.

**Comment by AMBIztw** [comment]
@mika-n all good? Soon? :)

**Comment by mika-n** [comment]
Sooner than you think. I already have the code ready to be submitted. Just syncing and testing it with the latest source branch.

**Comment by AMBIztw** [comment]
Nice!

**Comment by mika-n** [comment]
@AMBIztw  @Zaphyr-Z   The latest vanilla version of Ds4Windows now has a support for various non-standard DS4 wanna-be controllers. Please test the vanilla version with the gamepads you have if it works. There is no need to do any config file tweaks like you had to do with debug version because the vanilla version should automagically detect that those gamepads need a custom protocol logic.

**Comment by AMBIztw** [comment]
Yes @mika-n! Many thanks!
Works well, but I don't have time now for long testing, sorry.
