### ISSUE TITLE
Gyro handling - improvements in UI and documentation

### ISSUE THREAD

**Issue by madcrow** [Ryochan7/DS4Windows#1088]
Hey Travis,
Hey mika-n,

I've spent my last couple of evenings figuring out how the gyro handling features of DS4W work (by experimentation, reading the wiki and analyzing community-made profiles).
Now that I mostly understand what they do, I'd like to share some constructive criticism on them. I hope you find it useful.

(1) Units and ranges
There should be some way (label / tool-tip / wiki article / whatever) to let the user know what the unit and range of each numeric input is.
Or better yet, unify them to a reasonable degree.
As of now, the units are undocumented and inconsistent across the different controls:
E.g. on the gyro / mouse joystick tab, Minimum X and Y, Weight seem to be ratios [0.00;1.00].
Vertical scale appears to be a percentage [0;100], which is a ratio * 100. (Then why not handle it as a ratio as well?)
As for the unit and range of Dead and Max Zone, I can only guess. Looking at the default values, they are surely not ratios/percentages. I suspect they represent the 16-bit raw angular velocity [HID report fields](https://www.psdevwiki.com/ps4/DS4-BT).
Am I correct? Why not use simple ratios instead, like in the Axis config tab?

(2) Limitation in numeric inputs
It would be a good idea to double-check if the limits applied by the numeric input fields are reasonable.
Dead Zone and Max Zone seem to be some kind of absolute values, with a top limit of 999999999. Does that upper limit make sense?
Vertical scale is allowed to go above 100, but when a number >100 is entered, the internally calculated value often overflows, resulting in reverse motion.

(3) Nomenclature
It would be advisable to maintain consistency in the naming conventions across the application.
E.g., if I understand correctly, in Mouse Joystick mode, the Minimum X are Minimum Y fields are effectively "Anti-Deadzones" - the profile XML even calls them so.
Then why use a different name? It just leads to confusion.

(4) UI layout
It would help tremendously with making the UI more intuitive, if it was functionally organized, and more consistent across similar tabs.
The Eval Cond., Toggle and Turn Behavior controls are all related to the trigger handling feature, so they should be located near the Triggers control, ideally grouped together and separated from the other controls visually.
In the Mouse Joystick view, Deadzone one of the first controls, while in the Mouse view it is the one before last. Weird.
In Mouse view, the labels of Eval Cond. and X axis are placed on top, while in Mouse joystick view to the side. Sure, not the end of the world, but could be improved.

(5) Lacking descriptions in app and wiki
There are multiple places in the application where gyro related settings can be made, but it is unclear how the are related to one another:
What is the purpose of the "Axis Config/SixAxis/X and Z" controls?
They seem to have no effect in Mouse and Mouse Joystick gyro output modes.
Are they only relevant in Controls output mode?

Speaking of... What is the Controls output mode exactly? Is it for assigning _binary_ actions (e.g. button presses) to movements?
When I first started experimenting with the gyro, I mapped the RS axes to the gyro axes in Controls mode.
It resulted in strange behavior. The RS axes were momentarily assigned 1.0 or -1.0 on _very quick rotations_, as if when passing a certain threshold in angular velocity. They would take no intermediate values, just 1.0, -1.0 and (when stationary) 0.
Then I moved on to Mouse Joystick mode which allowed gradual mapping between gyro and RS axes - what my original intention was.

Anyways, congrats on the feature! It is indeed very powerful, with lots of customizability.
And as a result it is also very difficult for users to wrap their head around, even with the wiki in place.
But I am convinced you could make it much more intuitive and accessible for them by making the simple adjustments described above.

**Comment by mika-n** [comment]
I agree in all points. Especially documentation and consistency here and there would need a massive review. 

The history of the app is shown here. Originally Jay2Kings made the ground work (and actually his work was a fork of some even more earlier experimentation by someone). When Jay2Kings left to do some other things and the app had many issues in Win8 and was no longer compatible with Win10 then Ryochan7 took over the app and kept it alive (for his own needs and it was just a bonus if someone else found his work useful. He could have keep the new code private, but fortunately he didn't). I got involved here only at later stages when I wanted to use DS4 gyro as a steering wheel in EuroTruckSimulator2, but the existing gyro-to-LStick re-mapping feature was very limited and didn't work well as a "steering wheel" (https://github.com/Ryochan7/DS4Windows/pull/491#issuecomment-439821245).

There was never any major re-designing of GUI and when new features were introduced then options were just dropped in somewhere. Anyway. The old V1.7.x version had all those excuses and no one wanted to touch the old GUI because small changes there had all kind of nasty side effects. 

Now when Ryochan7 did a major overhaul with the GUI in V2.x version there are better chances to do GUI modifications and improvements without fearing to break up something else. Not everything can be documented in tooltip text fields within the app, but Wiki documentation definitely needs major overhaul also to be consistent with V2.x and explaning more how certain options are supposed to be used and what it does in general. And maybe a URL link within the app itself to make it clear for people that there exists such documentation page.


>Speaking of... What is the Controls output mode exactly? Is it for assigning binary actions (e.g. button presses) 

OutputMode=Controls in Gyro tab and TiltUp/Dn/Left/Right events there are handled like "raw" gyro values. Tilt left and right can be mapped as analog LS- and LS+ stick axies, but it has major limitations because of "raw" mapping (my primary reason why I got involved the app in the first place). When you tilt the gamepad "too far" in either side then the raw yaw/pitch/roll value is wrapped around. In practice it supports only 45 degree angle until to wrap around. This is why you see the LS stick to sort of going backward when the gamepad is tilted enough. This is clear also when you take a look at the ControllerReadings tab page and see how the raw gyro dot moves.

The steering wheel emulation mode there was my first contribution to this app and it calculates tilting left or right as a linear movement in either side and supports more than 360 degree turn range (keeps track of "how many times" the gamepad has been turned around since the center point). This is perfect for ETS2/ATS2 truck simulators and for many other driving games. Works surprisingly well in ETS2/ATS2.

Now, those other output modes (OutputMode=Mouse or Mouse Joystick) are specifically made to emulate mouse or joystick type of movements (sensivity, linearity, etc). Those modes map the limited raw gyro tilt values to behave more like a mouse or joystick.

Anyway. Very good points about using a bit different scaling values in similar options here and there.  Wiki documentation page will be improved for sure at some point, but when? Good question. 

I'm sure some users are scared away after they test the app and find it difficult to understand. But, not many other apps can do all these re-map things and special features but it does add a bit complexity to GUI (or developer knows the hidden secrets behind the option, so doesn't pay enough attention to make it more obvious for other users also).

**Comment by Ryochan7** [comment]
My fork of DS4Windows has had a weird history behind it. There have been a lot of struggles trying to improve the speed of the mapping routine and adding new features. Many of those struggles made me only put in the minimum amount of work to get a feature to work out of fear of breaking something or the app responsiveness slowing down.

Part of the big motivation of rewriting the UI and converting the app to WPF has been to try to allow DS4Windows to be much easier to develop and maintain. Despite some initial pitfalls, that has been the case so far and new changes can be added much more quickly without app degradation.

Addressing some concerns outlined:

1: In Mouse Joystick and Gyro Mouse, the Dead zone and Max Zone units are expressed in raw values given by the HID report. I would prefer those relative value settings to be more granular so a per unit setting is used. Some of the inconsistencies in the units of various settings is from old cruft. I would rather use percentages rather than ratios for most of the Axis Config section. That would be much easier to change now but I have kept many settings (Dead Zone, Max Zone, etc.) expressed as ratios to minimize confusion ironically.

Smoothing weight is expressed as a ratio so type conversion would not be required between the backend and the UI. Also, I always think of the weight as a ratio so it makes sense to me to have it expressed in the UI as a ratio. This is also something that would be much easier to change now thanks to the View Models that are used in the code.

2: There are no bounds set for those controls. It does not make sense to try to set those values so high. That was probably just overlooked but I don't want to restrict the value used too much.

3: The use of Minimum X and Y is mainly because that is the label Steam uses for Mouse-like Joystick. There are other cases where I ended up using the label used in Steam expecting that people are familiar with Steam Input (Trigger Behavior - Turns Gyro). I still test Steam Input on occasion even though it does not do what I want.

4: Changing the layout of the controls is much easier with WPF and can scale much better than the old Windows Forms UI. The initial WPF version GUI was mostly just a straight port of the old layout to learn how to structure a layout in XAML. Control layout was a major pain before so many controls were just appended to a section as features were added.

5: I have not done any active Wiki editing in a long time especially for the Settings page. I made a revision when Mouse Joystick was implemented. Documentation of any kind has always been a weak point of mine. I have the typical mindset that I would rather work on tweaks or implement new features rather than update documentation.

There might be a bug with the Gyro Controls to Xbox axis routine; I will look into that. The Controls mode for Gyro is mostly meant for binding a controller Tilt to a key press. Binding LX to Gyro Controls used to be what was required to use the DS4 as a Steering Wheel before the 360 Steering Wheel mode was added by mika-n. For that use case, the 360 Steering Wheel mode is a much better option.
