### ISSUE TITLE
Problem with high latency "Input Delay"

### ISSUE THREAD

**Issue by Veronika133** [Ryochan7/DS4Windows#1089]
Hi,
Excuse my bad English, my primary language is Czech.
My gamepad is this: Sony PS4 DualShock 4 Sunset Orange V2
OS: Windows 10 (v10.0.17763 Build 17763)
Notebook: Acer Predator Helios 300 (PH317-51-746B)

Gamepad over cable (2 meters long) works well = Input Delay 4 ms
But via bluetooth I have an Input Delay in the range over 600-1000.
(gamepad I have one meter from the notebook)
I tried different OS and DS4Windows settings but nothing worked for me.
https://i.imgur.com/NUDiJCP.png

https://www.acer.com/ac/en/US/content/support-product/7309?b=1
Bluetooth_Intel_19.50.0.5_W10x64_A.zip
I also installed the bluetooth drivers from the Acer site but it wouldn't affect anything.
(in fact I do not understand what these drivers are, all bluetooth drivers have the date of the drivers still 2006)

Please help :-P

**Comment by Veronika133** [comment]
Here is the log of "DS4WindowsDebug.exe" (Default profile=NORMAL)
[log1.txt](https://github.com/Ryochan7/DS4Windows/files/4142726/log1.txt)

I changed my mac address to: 10:10:10:10:10:10

**Comment by mika-n** [comment]
Hmmmm....  Gyro calibration seems to work (ie. DS4Windows app writes and reads data from the gamepad). This is good because if a gamepad is a fake chinese copy then usually those fake gamepads fail in this step.

But, later on incoming data packets are not in expected format (crc32 error) and type0=1 (ie. the data packet is in PC-friendly mode and not in native DS4 mode). Almost like the PCFriendlyMode -> DS4 native mode switch command was never received by the gamepad.

Eventually "ERROR. writeOutput failed" error message breaks the neck and DS4Windows app ignore the gamepad because it doesn't seem to behave like a first class Sony DS4 or compatible BT gamepad.

For testing purposes try tweaking following DS4WindowsDebug.exe.config options:
Debug_SendRumbleLightbarData=false

This option disables "data writing" (ie. DS4Windows app sends data to gamepad) of lightbar and rumble information. By disabling this we can verify if at least the data reading part works. Do you see any button activity after setting the mentioned option as FALSE? How about touchpad?

Does everything work OK over USB connection? Rumble/Lightbar/Gyro/Touchpad?

**Comment by Veronika133** [comment]
Only a combination of both of these options to "false" results in bluetooth delay 1ms
"Debug_GyroCalibration" value="false"
"Debug_SendRumbleLightbarData" value="false"

interestingly, I set
"Debug_GyroCalibration" value="false" and the gyroscope works.
when I added the second combination "Debug_SendRumbleLightbarData" value="false" the gyroscope stopped working.

I tried the combination: 
"Debug_GyroCalibration" value="false"
"Debug_ReadGyroData"  value="false"
the gyroscope did not work but the delay was still 300ms+

the same thing when I set only: "Debug_SendRumbleLightbarData" value="false" > 300ms+

can I copy the settings like this: DS4WindowsDebug.exe.config > DS4Windows.exe.config
and use DS4Windows.exe normally?

**Comment by mika-n** [comment]
No, you cannot copy these debug tweak options to the vanilla version. It doesn't support those (at least in current vanilla version).

>Only a combination of both of these options to "false" results in bluetooth delay 1ms
>interestingly, I set "Debug_GyroCalibration" value="false" and the gyroscope works.

Yes. Even when gyro calibration is FALSE then gyro may work, but calibration could be a bit off (well, there are numerous DS4 compatible gamepads which support gyro but doesn't do/need/support calibration like genuine DS4 gamepad needs in BT).

>when I added the second combination "Debug_SendRumbleLightbarData" value="false" the gyroscope stopped working

Okey. This is important piece of information. It means that the gamepad stays in "PC-friendly mode" in BT (a bit like xbox360 compatible interface in WinOS) and the gamepad didn't made an internal DS4 native mode switching. 

This is understandable because PCFriendly->DS4 native switch is made when DS4Windows app either sends the gyro calibration data OR sends out lightbar/rumble data. Now when both calibration and SendLightbarRumble are false then the gamepad stays in PC-friendly mode.

But, the interesting part is that when GyroCalibration=FALSE and SendRumbleLightbar=TRUE then the ds4 mode switch is received by the gamepad even when it complains about crc32 and write data failure.

Please send a complete log file from the case where you have GyroCalibration=FALSE and SendRumbleLightbarData=TRUE. So, gyro works in this mode. How about touchpad? You can easily test it by mapping touchpad as a mouse in DS4Windows.  And what happens when you press "test rumble" buttons in DS4Windows? Any write data failure errors in logfile?

GyroCalibration does make an additional tweak. It sends the calibration data AND sets the BT update frequency of ds4 gamepad. This frequency value is taken from DS4Windows profile option "BT Poll rate". What happens when you try different poll rate options? Significant changes in lag? Anyway, when GyroCalibratio=FALSE then this frequence rate value is not modified and the gamepad stays in some default rate.

**Comment by Veronika133** [comment]
> Please send a complete log file from the case where you have GyroCalibration=FALSE and SendRumbleLightbarData=TRUE.

[log2.txt](https://github.com/Ryochan7/DS4Windows/files/4143197/log2.txt)
touchpad gamepad work but not work remap in the DS4Windows (remapping keys has no effect).

Test Rumble full work nothing errors.

„BT Poll rate“ change settings has no effect, still bad delay.

**Comment by mika-n** [comment]
>touchpad gamepad work but not work remap in the DS4Windows (remapping keys has no effect).

Make sure "Use controller for readout" option is checked in DS4Windows/Other tab page screen (while editing a profile).

If you open JOY.CPL controlpanel applet (run JOY.CPL command or click "Control Panel" link in DS4Windows Settings tab page) then do you see one or two gamepad devices? If you check properties and press buttons and move LS/RS then do you see any activity? Or do you see L2/R2 trigger and gyro activity in "Controller Readings" tab page in DS4Windows?

The latest log file confirms that for some reason the gamepad you have doesn't send "normal" DS4 input data packets (ie. button and analog axis activity and touchpad data). This is normal for xbox360 type of gamepads, but this is veeeeery strange with genuine Sony DS4 gamepads. I have seen this kind of behaviour only with couple Nacon (ie. not Sony) DS4 compatible gamepads (ie. those send PC-friendly data packets in BT connection but the standard xbox360 data packet is appended with an additional DS4 touchpad data which normally is sent by gamepad in native DS4 mode). The support for these kind of gamepads is in the debug version, but is still waiting for to be integrated with the official version.

Did you try to tweak "Debug_HidDSetNumInputBuffers" debug config option in exe.config file? Any changes in BT lag?

**Comment by Veronika133** [comment]
I will do big tests tomorrow and send results :-)

**Comment by Veronika133** [comment]
Today I wanted to test everything again and send logs.
To be sure, I deleted the program DS4Windows folder and extracted everything again, and something incredible happened.

Works Gyroscope, Light, Rumble, Touchpad, and delay is 4-5ms!
I do not understand what has changed, I do not understand how possible.
here is the log: [log1.txt](https://github.com/Ryochan7/DS4Windows/files/4144774/log1.txt)

**Comment by mika-n** [comment]
So the vanilla version with default settings work now just fine? Strange. Simply re-installing the same version of DS4Windows should not have such effect. In theory it is possible that some old config files may have some weird option combinations causing bugs or conflicting re-mapping rules. Or there has been bugs in the past with auto-updater tool and maybe some file was not updated by the auto-updater tool. Who knows...

Anyway. Now the log file you provided looks perfect and the result is what is expected from an official Sony DS4 gamepad.

If you have not enabled "Hide DS4 Controller" option (=exclusive mode) in DS4Win settings then it is normal that JOY.CPL shows two WirelessControllers and other one is dead controller. The dead one is actually the original physical DS4 controller, but WinOS has a problem that after switching the BT connected DS4 gamepad to native DS4 mode the original HID device is no longer usable by WinOS. DS4Windows app solves this problem by reading the gamepad in raw mode and creating an another virtual output controller which works.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

When both GyroCalibratio and SendLightbarRumbleData are set to FALSE in debug version then BT delay is probably a bit better because BT communication link sends a lot less information (no gyro data, not updating lightbar color and rumble etc). But having both of these FALSE means that those features don't work.

Anyway, great to hear that everything is now back in order even when I don't fully understand why re-installation helped.

**Comment by Veronika133** [comment]
Thank you for all the help, it's really special...
Before I wrote here I did a clean install + remove all user data some 4x and no effect.
And suddenly it works, I don't understand but I'm happy :-)

**Comment by Veronika133** [comment]
My laptop was under repair and I had to reinstall the operating system and guess what happened :-D

yes. I have a delay again: ![obrazek](https://user-images.githubusercontent.com/60544130/79036989-c3b2ab80-7bcd-11ea-8ff1-62b4d7afc3d6.png)

after 6 hours I haven't figured out what causes this problem, but I know that my laptop can work with this gamepad and bluetooth.

Use version: 2.0.15

I want to send new logs, but debug is only in version 2.0.13 doesn't matter?

**Comment by mika-n** [comment]
I just updated the debug version to use V2.0.15 branch. But, it shouldn't have much of a difference because there are nothing which should change how the BT communication works between this and the older version.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

This is really getting a mystery. Are you using WLAN network connection or ethernet cable? Try disabling WLAN in the PC because some cheap BT chipsets are integrated with WLAN chipset and sometimes those may cause interference with each other. Also, shutdown nearby WLAN client machines (mobile phones, tablets etc) just to test if those cause issues (the older WLAN standard and BT both use the same 2.4ghz radio frequency).

Mr and Ms Google may also help if you search for "bluetooth lag windows". Usually those complains are related to BT audio and BT mouse lag, but in low level it is almost the same thing with mysteries of drivers and radio frequencies.
