### ISSUE TITLE
Touchpad acting as mouse buttons

### ISSUE THREAD

**Issue by fedamerd** [Ryochan7/DS4Windows#1093]
When clicking the touchpad it always results in a mouse click, even when the touchpad is toggled off. Changing to _use as controls_ also doesn't make a difference as the keybindings remain the same. This is a problem for games that utilize the touchpad to open the in-game map, like Star Wars Jedi: Fallen Order. There seems to be dual input between native touchpad buttons and mouse clicks, as sometimes my character will attack and other times the map will open.

A solution seems to be to just unbind the touchpad buttons, but a more preferable solution would be to use the touchpad for mouse buttons when it's toggled on and use the native touchpad buttons when it's toggled off. I would also like to be able to map other buttons (like the share button) to the touchpad. Currently there are no selectable actions for the touchpad when rebinding buttons.

**Comment by Ryochan7** [comment]
The virtual touchpad buttons operate independent of the Touchpad mode. When using DS4 emulation, the real DS4 Touchpad Click button cannot be rebound so the state is of the Touchpad Click is transferred to the virtual controller. If you don't want mouse click actions bound to the Touchpad, you would have to set the three virtual Touchpad buttons to Unbound.

**Comment by fedamerd** [comment]
I see. Thanks for clarifying.

**Comment by mika-n** [comment]
And if you want to handle the touchpad (or touchpad click) a bit differently at certain points of the game then instead of using "touchpad toggle button" to disable/enable the touchpad to mouse remapping, you could define a special action trigger key to change between two profiles. These profiles could have different settings for touchpad. This way you can easily switch between two operating modes of touchpad simply by clicking (or holding) a trigger key almost like you would click a toggle key.

See LoadProfile specAction description and three different operating modes of the specOp trigger key.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#how-to-change-a-profile-on-the-fly-via-a-certain-gamepad-button-using-a-special-action

PS. Pro tip. You can use different lightbar color settings to indicate which profile is active.

**Comment by fedamerd** [comment]
Good tip! Thanks.
