### ISSUE TITLE
Stick Squaring Changes Direction

### ISSUE THREAD

**Issue by MaybeItsEstrogen** [Ryochan7/DS4Windows#1094]
Hello!

I'm not really sure whether this could be considered a _standard_ issue, but something I've noticed is when using the stick squaring function in DS4Windows, it causes the direction of input to change. The change in direction is more severe as the input is squared more. It's obviously a side-effect of the squaring algorithm, but is there no way to apply the squaring radially as to maintain the correct direction of input? The difference in direction becomes greater as the roundness of the squaring increases.

Thank-you for your time!

**Comment by Ryochan7** [comment]
That is the way the algorithm is meant to work. The normal routine attempts to keep the inner portion of the stick circular and then go to square output towards the high end. Here is an example of input versus output with Roundness = 5.

![Roundness 5](http://theinstructionlimit.com/wp-content/uploads/2009/11/rounder-small.png)

What you probably want is a pure linear interpolation which can be done with Roundness = 0.

![Roundness 0](http://theinstructionlimit.com/wp-content/uploads/2009/11/square-small.png)

However, DS4Windows currently limits the minimum value to 1.0 so that restriction will have to change.

Source article:
http://theinstructionlimit.com/squaring-the-thumbsticks

**Comment by Ryochan7** [comment]
This change has been introduced in version 2.0.10.
