### ISSUE TITLE
Have an problem with Controller as Dualshock 4 mode.

### ISSUE THREAD

**Issue by droidtoss** [Ryochan7/DS4Windows#1095]
A few days ago i was updated my ds4windows Version 1.4.52 to version 2.0.8
and have try to use new feature for me Dualshock4 mode, and everything worked awesome. Next day was turn on my pc and that mode isn't worked, ill try to reinstall everything and nothing helped me.
So that why im here, in video u can see all my stuff. When i switch to DualShock 4 mode and alt+tab into game im pressing buttons and no reaction. How do i can fix that?

https://youtu.be/AuVh5mRlQiY

**Comment by mika-n** [comment]
Please provide a logfile (export button in Logs tabpage of DS4Windows or  %APPDATA%\ds4windows\logs file). Following page has more info how and what information to provide.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

What do you see in JOY.CPL ControlPanel applet and any activity in gamepad keys in there? One or two gamepads? Run this command or click ControlPanel link in DS4Windows settings screen.

Are you using Steam ds4 controller support and Steam games? See the following tip.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

If you use BT connection and not USB then maybe the game sees the origianl BT gamepad device? The problem is that WinOS doesn't know how to use DS4 gamepad in native ds4 mode (touchpad/lightbar/gyro/rumble), so the original physical device is seen as dead device by WinOS.  This is WinOS issue and not DS4Windows app issue. The workaround is to make sure the original device is hidden from games and those see only the virtual output controller created by DS4Windows and Vigem driver.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by droidtoss** [comment]
> Please provide a logfile (export button in Logs tabpage of DS4Windows or %APPDATA%\ds4windows\logs file). Following page has more info how and what information to provide.
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting
> 
> What do you see in JOY.CPL ControlPanel applet and any activity in gamepad keys in there? One or two gamepads? Run this command or click ControlPanel link in DS4Windows settings screen.
> 
> Are you using Steam ds4 controller support and Steam games? See the following tip.
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type
> 
> If you use BT connection and not USB then maybe the game sees the origianl BT gamepad device? The problem is that WinOS doesn't know how to use DS4 gamepad in native ds4 mode (touchpad/lightbar/gyro/rumble), so the original physical device is seen as dead device by WinOS. This is WinOS issue and not DS4Windows app issue. The workaround is to make sure the original device is hidden from games and those see only the virtual output controller created by DS4Windows and Vigem driver.
> https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

There is all my logfiles
https://drive.google.com/open?id=1bIKGPKIXEJukk39m5-OXqOnxPKq2a9FR
https://prnt.sc/qy4g3g

JOY.CPL with turned on  Dulshock 4 mode
https://prnt.sc/qy4hio
and with turned on Xbox 360 mode
https://prnt.sc/qy4i9d

That all is without steam. 
if i hide DS4 Controller in settings then it still doesn't work

**Comment by mika-n** [comment]
Hmmm... Interesting. I didn't see anything strange in logfiles. The "Wireless Controller" shown in JOY.CPL screen is probably the original physical controller, but there should be another "Wireless Controller" created by DS4Windows and VigEm drivers (in dualshock4 profile mode). For some reason it is not there, almost like the creation of virtual dualshock4 object has failed.

Maybe the debug version would tell more info. It dumps out a lot more detailed debug messages.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

Or maybe profile file has something weird. Please post the profile using dualshock4 output for closer inspection. At least make sure UseDInputOnly option is NOT checked.

**Comment by droidtoss** [comment]
@mika-n there is logs with debug DS4W.exe and some video of all process with that
https://drive.google.com/open?id=1sAxrZWxq20JSBySlnA9WWlV6MLQ7p3n1

There was lot of errors, rly no clue what is wrong

**Comment by droidtoss** [comment]
|INFO|DEBUG: performDs4Input. WARNING. F4:93:9F:D0:0B:68 crc32 check of BT input packet failed. btInputReport type0=1  type2=123

**Comment by mika-n** [comment]
The "crc32 check of BT input packet failed" warning" message is a problem, but it is just a warning not a fatal in the debug version. The debug version tries to use the gamepad even when this error is thrown. Do you see any activity in the virtual output gamepad in xbox360 mode even when this warning is thrown? 

However, the fatal error is "sendOutputReport. ERROR. writeOutput failed. Force quiting output thread. LastErrorCode=1167" message. If this is thrown then the output virtual gamepad is not created.

However, I don't understand why this message is shown with dualshock4 profile, but not with xbox360 profile?!? The output controller mode has absolutely nothing to do with how DS4Windows app reads data from the physical controller.

If you tweak DS4WindowsDebug.exe.config options then does it work better:
Debug_SendRumbleLightbarData=false

And if you test following config tweaks then how it goes:
Debug_SendRumbleLightbarData=true
Debug_SendRumbleLightbarDataAPI=1

Or even
Debug_SendRumbleLightbarData=true
Debug_SendRumbleLightbarDataAPI=2

Remember to close DS4Windnows app when modifying DS4WindnowsDebug.exe.config file and restart the app after saving config file changes. When you post a logfile then after testing new config tweaks then take a copy logs\DS4Windows_log.txt file (this is the latest version, other timestamped files are old copies). Try generating separate logfile from each test run because it makes it easier to interpret the logfile when there is less semantic noise.

Recently there has been couple similar issues (ie. BT connection doesn't work, but USB connection worls). Try using USB connection. Any luck? There is slight difference in how DS4 physical gamepad behaves in USB and BT mode. See following issues for similar cases: 
#1086 
https://github.com/Ryochan7/DS4Windows/issues/1085#issuecomment-581376962
#988 

Hmmmmm Volume 2.0.....   I wonder if Sony has released some new batch of DS4 gamepads which work a bit differently in BT mode in PC. Usually DS4 gamepad is in PC-friendly mode in PC (in BT) and it needs to be switched over to native DS4 mode before it sends "DS4 input data packets". Those "warning crc32 error" messages complain about this because the incoming data packet is not in expected format. Almost like the DS4 gamepad is still in PC-friendly mode. There are couple Razer gamepads which behaves like this. Now I wonder if Sony has released some updated DS4 gamepads with a new firmware code in PC mode. #988 

Anyway. The gamepad you have probably works just fine over USB cable?

**Comment by droidtoss** [comment]
@mika-n 
Yea 360 Xbox mode is working fine and exclusive mode and prob ds4 mode same working fine, but there must be shown another controller, i mean if i turn on ds4 mode and exclusive mode, there  hide xbox controller and ds4 controller, and there must be another one ds4 controller i think. It was worked couple days ago with native support in non exclusive mode and ds4 mode together, now it isn't work and i don't know why. Probably in previously i have bad experience with using program or something else, it shown another issues. I have reset my windows to default and it didn't help, that shows now in the logs, that's interesting
`2020-02-07 11:55:16.8116|INFO|DEBUG: performDs4Input. BT ReadWithFileStream failed. ErrorCode=ReadError WinError=997
2020-02-07 11:55:16.8116|INFO|DEBUG: sendOutputReport. ERROR. writeOutput failed. Force quiting output thread. LastErrorCode=1167
2020-02-07 11:55:16.8116|INFO|Unplugging DS4 Controller for input #1
2020-02-07 11:55:16.8116|INFO|Controller 1 was removed or lost connection`

And when i plug my controller with cable it was working in native mode with any active mode in ds4windows

**Comment by droidtoss** [comment]
That what im talking about. Have installed ds4windows to my laptop and connected gamepad that's all and everything is fine. And it was worked on my pc 2-3 days ago, what happened?
https://youtu.be/5kEF0ioCnZ8

**Comment by mika-n** [comment]
Something wrong in the BT drivers in PC? 

Some users have reported that weird issues were fixed when they downloaded the latest version of DS4Windows and installed it, instead of doing auto-update in DS4Windows app.
https://github.com/Ryochan7/DS4Windows/releases

Try unpairing the gamepad and re-pair the BT connection in PC.

**Comment by droidtoss** [comment]
I don't know how, but i fixed it.
Little bit information what i figure out, really important what is yours BT adapter, if it is Cambridge Silicon Radio (CSR) chip inside then u got lot of issues with compatibility DS4Windows and yours BT adapter. 
Great choice is Sony, Microsoft, ASUS, Logitech and i guess gigabyte.

As for what I did, that would work for me. I backup all drivers related with BT, GamePad and something else in my laptop where was working everything great and just paste that on my pc, in real i planed to install that all to my main pc, but that got fixed just when i paste drivers to desktop lol.
There is ScreenShots and Backup Drivers from my laptop, probably it help someone.

https://drive.google.com/open?id=1DY05sxOyjfW5reB4qAtBB6jPzmKvdjKw
To install drivers u need app: Double Driver

And now question is can we get audio speaker and audio jack working on BT mode? That would be great.

**Comment by Ryochan7** [comment]
Experiments have been done with audio support for a BT controller but nothing really materialized. I consider it a lost cause. Even getting the possibility of audio support would probably require a driver for creating the audio sink that would be routed through to the DS4. I use the Sony Wireless Adapter most of the time and having access to the headphone jack on the DS4 is a nice feature.

**Comment by droidtoss** [comment]
You are very responsive, ty for help!
