### ISSUE TITLE
radial menu?

### ISSUE THREAD

**Issue by powerpuffboysz** [Ryochan7/DS4Windows#1100]
steam's input mapper has functionality where where the right touch pad on steam controllers could be a radial menu for hotkeys. would it be possible to implement similar functionality in ds4windows?

**Comment by Ryochan7** [comment]
I don't think that there isn't enough surface space on the DS4 touchpad to make something like that feasible. It does not work out too well with Steam Input DS4 support.

Besides that, the biggest technical problem is making some kind of overlay window that will display over games even in fullscreen mode. The DLL overrides that Steam performs when it launches a game help work around the problem for the Steam client. The closest thing to a working implementation that works system-wide right now is in Kozec SC Controller. The overlay does not work with some games (Might and Magic 8) so that implementation is only a partial solution.

That software has an OSD that can be used for switching profiles, virtual keyboard display, and also menus. I have not played with that software in a long time so I don't know if a menu can be mapped to the DS4 touchpad or if DS4 support is even available on the Windows beta build. It would be nice to have an equivalent in DS4Windows someday but I am not that hopeful.

https://github.com/kozec/sc-controller/
