### ISSUE TITLE
controller 1s latency over 10 ms

### ISSUE THREAD

**Issue by ludoff21** [Ryochan7/DS4Windows#1106]
hello, I have a problem with my ps4 controller and my scuf controller, I have these messages that appear every 1 second, can you help me please, the one who solves this problem I send him paypal money /
https://preview.redd.it/r5qqwa6v0ag41.png?width=846&format=png&auto=webp&s=4d6648cc5bd0246c432602b72c5966893393e4f2
thank you for the work you provided

https://www.reddit.com/r/DS4Windows/comments/f26uig/controller_1s_latency_over_10_ms/

**Comment by mika-n** [comment]
Please share the complete log file. It would show the version and connection method (usb or bt) you are using. The log file is shown in Logs tab page in DS4Windows or in %APPDATA%\ds4windows\log folder.

Anyway. you are probably using bluetooth connection? The bad news is that not all BT chipsets are compatible with DS4 gamepads (Sony or 3rd party copies). You may be able to workaround these issues by tweaking few options
- "BT Poll Rate" setting in DS4 profile settings (profile editor and Others tab page). 
- If "Flush hid" is checked then untick it (this option is usually not needed).

Another way to fix the issue is to make sure WinOS bluetooth drivers are up to the task and in good shape. Try to update those. 
Or unpair the BT gamepad and re-pair it.

Here are few links to  similar topics where users have solved these weird BT compatibility issues using all or some of the mentioned tweaks.
https://github.com/Ryochan7/DS4Windows/issues/1089
https://github.com/Ryochan7/DS4Windows/issues/896

These posts mention a special debug version of DS4Windows app which supports certain additional "Debug_xxx" ds4windows.exe.config options you may wanna try to diagnose lag issues.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

Using the debug version try this:
- set "Debug_GyroCalibration=false" and "Debug_SendLightbarRumbleData=false". Any difference in lag?
- set "Debug_HidDSetNumInputBuffers" to value 3 or 4. Any difference? How about value 0?
- set "Debug_SendLightbarRumbleData=true" and then "true/false" one by one in Debug_ReadTouchpadData/Debug_ReadGyroData/Debug_ReadBatteryData" options. Any difference?

**Comment by ludoff21** [comment]
thank you for your quick response, yes i use a bluetooth connection.

here are the logs ; https://www.transfernow.net/FG0Y6t022020

apparently you gave me the right solution, thank you I no longer have an input lag. I have another problem that I already had several times, I have a problem with sensitivity on fortnite, that is to say, that my sensitivity is slow and then accelerates, it's bizzare, I have impression that there is an input lag, but that ds4 does not detect it because the light is not red. the joystick movements are late.

Do you have a solution ?

**Comment by ludoff21** [comment]
"Using the debug version try this:

     set "Debug_GyroCalibration = false" and "Debug_SendLightbarRumbleData = false". Any difference in lag?
     Try setting only Debug_SendLightbarRumbleData = true and set Debug_GyroCalibration = false. Any difference in lag?
     set "Debug_HidDSetNumInputBuffers" to value 3 or 4. Any difference? How about value 0?
     set "Debug_SendLightbarRumbleData = true" and then "true / false" one by one in Debug_ReadTouchpadData / Debug_ReadGyroData / Debug_ReadBatteryData "options. Any difference?
"

I tried these solutions and still have a latency problem

**Comment by mika-n** [comment]
You seem to have veeeery old ViGem driver (1.14.3.3) The latest vigem driver version is 1.16.112. I recommend you to download the latest ViGem version directly from ViGem web site and install it. And while you are updating stuff then it doesn't hurt to make sure you have the latest .NET Framework libraries from Microsoft. See the link list for details where to download various compnents.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

If you use DS4Windows auto-updater tool then it updates only the DS4Win app, not ViGem driver so this is why you may have the ancient Vigem 1.14.3.3 version still in use.

Please share the logfile from DS4WindowsDebug.exe test run while you had set Debug_GyroCalibration=false and Debug_SendLightbarRumbleData=false and Debug_ReadBatteryData=false debug options in ds4windowsdebug.exe.config configuration file. Anyway, if you still get BT lag with these three FALSE options then I'm afraid that you may have BT receiver chipset issue or driver issue.

Troubleshooting doc page lists couple WinOs powerSavingPlan and battery saving options you could try in WinOS settings.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#gamepad-connection-over-bluetooth-bt

**Comment by ludoff21** [comment]
https://transferxl.com/08j6kD4PjYbJb2 log 2 

again thank you for your answer,
here is the log with the new update and the modifications in the debug file.

it still doesn't work, what should i do? buy a bluetooh key?

**Comment by ludoff21** [comment]
what I don't understand is that it worked for a while, minimum 2 weeks

**Comment by mika-n** [comment]
Jep. Could be that the BT chipset in your PC is not up to the task. Some cheap chipsets share WIFI and BT. Try disabling WIFI in PC to see if it makes any difference.

If nothing else helps then you may have to find a more compatible BT receiver. Sony used to sell their own DS4 Sony Wireless Adapter BT dongle for ds4 gamepad, but it is no longer available (difficult to find from any story). Using those standard BT dongle is a trial and error process to find a working chipset. Make sure the supported BT standard is 4.0 or newer and LE+EDR protocol is supported. 

This should give you some idea what BT specs to look for from a new BT dongle.
https://shop.cronusmax.com/CronusMAX-BT400-Bluetooth-v4.0-USB-Adapter-Certified-Full-Speed.html

**Comment by ludoff21** [comment]
Merci 
thanks for your help, that's what i was going to do buy a bluetooh key

**Comment by ludoff21** [comment]
135/5000
I bought this adapter
https://www.amazon.fr/Avantree-Bluetooth-Adaptateur-%C3%A9quipements-Enceintes/dp/B00VWEK4IG/ref=sr_1_8?keywords=adaptateur+bluetooth+ps4&qid=1581614434&sr=8-8
I have the impression of having a latency, however there is nothing in the logs. even in usb

it's possible ?135/5000

**Comment by SiTWulf** [comment]
@mika-n Thanks for the Info!
I updated my old ViGem 1.14.3.0 to the lastest 1.16.112.0 and now not more Latency problems!

Things i make, I uninstall everything and reinstall again, DS4Windows, HidGuardian, ViGem.. and now works like a charm!
