### ISSUE TITLE
Keyboard and Mouse stopped working randomly

### ISSUE THREAD

**Issue by Perseonn** [Ryochan7/DS4Windows#1112]
![Common](https://user-images.githubusercontent.com/36249699/74598435-1e36fc00-50a4-11ea-9bf3-140bb5fcf6fc.png)
Hello!
I have a random issue that the controller working for some time, then suddenly stopped working with these symptoms:
1. Assigned LED color turns off, USB Disconnected sound does not play.
2. Wireless Keyboard stopped taking inputs 
3. Wireless Mouse stopped taking inputs
This is a rare issue, but apparently, just a while ago, it did this several times. The PC isn't frozen as I can see Discord still receive messages, it's just the inputs are disabled completely.

Attached are all the logs that pops when this occurs and common programs that runs concurrently on my computer.

[ds4windows_log_20200214.1.txt](https://github.com/Ryochan7/DS4Windows/files/4205002/ds4windows_log_20200214.1.txt)
[ds4windows_log_20200214.2.txt](https://github.com/Ryochan7/DS4Windows/files/4205003/ds4windows_log_20200214.2.txt)
[ds4windows_log_20200214.3.txt](https://github.com/Ryochan7/DS4Windows/files/4205004/ds4windows_log_20200214.3.txt)
[ds4windows_log_20200214.4.txt](https://github.com/Ryochan7/DS4Windows/files/4205005/ds4windows_log_20200214.4.txt)
[ds4windows_log_20200214.5.txt](https://github.com/Ryochan7/DS4Windows/files/4205007/ds4windows_log_20200214.5.txt)

**Comment by mika-n** [comment]
Loose/faulty cable or usb port? Try different cables and usb ports. But why wireless keyboard or mouse are having a hard time because of ds4 gamepad? No idea because those two don't have anything to do with each other. 

Are you having those issues only when ds4 gamepad is connected? How about if you keep the gameapd connected without Ds4windows app running? Any difference?

Are you using HidGuardian tool? In theory it could cause such issues if the driver is in bad shape (it's registration is broken in WinOS level).

**Comment by Perseonn** [comment]
My cable is indeed a bit loose, but if the connection lost by that, the system plays the USB device Disconnected sound (I'll add that). When this occurs, the USB device disconnected does not play.

I cannot confirm if this will occur if DS4Windows not running since this is a rare issue

I am not using a HidGuardian tool.

I see this as potential problem with DS4Windows, since everytime this happens, it generates a log. perhaps at least it knows something? My guess is that the DS4 Windows deplyoment (Software, driver, etc) does something that might interfere with the entire USB driver.

**Comment by mika-n** [comment]
>it generates a log. perhaps at least it knows something? My guess is that the DS4 Windows deplyoment (Software, driver, etc) does something that might interfere with the entire USB driver.

No, don't see how that would be possible even in theoretical level. DS4Windows app or ViGem driver doesn't have anything to do with WinOS usb drivers. DS4Windows app just reads data coming from usb ports, but still it is WinOS drivers taking care of the physical connection to the usb port, not DS4Win app or ViGem driver.

If you are using veeeeery old Jay2Kings version of DS4Windows app (ver 1.4.x) and ScpVBus driver then the story is a bit diffrent. ScpVBus does all kind of nasty things with bluetooth drivers in WinOS. But the DS4Windows app were talking here has nothing to do with Scpvbus and doesn't use that unsupported driver.

**Comment by Perseonn** [comment]
I'm trying to narrow down the possibilities here since the log isn't readable. To be honest, I expected a developer would be more cooperative than this, like asking what other programs that I run (which just occurs to me).

I attached the list of common programs that runs at once on my computer, perhaps something else might interfere.

**Comment by mika-n** [comment]
Don't see anything suspicious in the process list picture. I know only ScpVBus, NVidia G-Sync and MSI Afterburner apps which are known to sometimes cause problems with DS4Windows app.

ScpVBus = This is no longer supported by the original author and this driver hijacked a bluetooth WinOS driver. Source of potential problems with newer VigEm driver.
NVidia GSync = Gsync may be confused by Windows WPF libraries and apps (the V2.x of DS4Windows uses Microsoft's WPF libraries). This issue is with all WPF apps, not just DS4Windows. However, should not have anything to do with USB connectivity issues.
MSI Afterburner directX hooking app = May cause issues in WPF apps because directx hooking is a very nasty thing to do.
Some corporate security apps = Some corporate security apps scan usb conections and devices. These may cause problems, but home PCs usually don't have these apps installed. 

Maybe you should try to run DS4 gamepad for a longer period without DS4Windows app to see if the issue popups even without DS4Windows app? 
Is this issue only in certain USB port or in all ports?
Try to reset DS4 gamapad (there is a small hole on the back of the gamepad you can press with a paperclip or with a sharp pen).

Based on the logfiles and errors there indicate that there has been connection issues to the gamepad (write failed error comes when the gamepad fails to receive DS4 commands and errors in reading serial# means that DS4Windows app failed to read data from the gamepad).

Warning about exclusive access is another story and probably not related to USB issues:
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by Perseonn** [comment]
Thanks for the reply :)

> Maybe you should try to run DS4 gamepad for a longer period without DS4Windows app to see if the issue popups even without DS4Windows app?
I am not sure DS4 will run without DS4 Windows, especially since most of my game config revolve around the controller and its touchpad. Would Steam work meanwhile?

> Is this issue only in certain USB port or in all ports?
I haven't moved any of my device's port since my PC is a part of my own entertainment center (a bit busy back there). I do have two USB controllers, according to device manager, and one controller surprisingly has nothing attached to it. I'll see if I can separate these inputs to each controller.

>Try to reset DS4 gamapad (there is a small hole on the back of the gamepad you can press with a paperclip or with a sharp pen).
What would this do, basically?

So the logfiles only write about read failure, that's a bummer :(

**Comment by mika-n** [comment]
> I am not sure DS4 will run without DS4 Windows, especially since most of my game config revolve around the controller and its touchpad. Would Steam work meanwhile?

Steam's built-in DS4 support should work at least when DS4 is connected over USB cable. BT connection needs DS4Windows app if those extra ds4 features (touchpad/lightbar/gyro) are needed in a game.


> > Try to reset DS4 gamapad (there is a small hole on the back of the gamepad you can press with a paperclip or with a sharp pen).
> What would this do, basically?

It resets the gamepad back to factory deaults and in practice this means that it forgets all BT pairing information and maybe something else. BT pairing is something you shouldn't worry about if using BT connection.

Anyway. Have you tried connecting the gamepad over bluetooth in case you are running out of usb ports and some of them have issues?

**Comment by Perseonn** [comment]
Thanks for the reply! For the moment I can separate the Mouse/Keyboard to another USB controller, now it's just waiting time till the issue pops.

> Anyway. Have you tried connecting the gamepad over bluetooth in case you are running out of usb ports and some of them have issues?

Unfortunately I currently don't have any Bluetooth dongle. Port-wise, this PC has a total of 8 USB ports, 1 for Mouse/Keyboard, 1 for the DS4, 1 for extra mouse (this one acts like a remote controller).
