### ISSUE TITLE
Unable to connect nacon compact wired controller illuminated on DS4Windows

### ISSUE THREAD

**Issue by JDA-GAMING** [Ryochan7/DS4Windows#1122]
Hello, I have a nacon wired illuminated compact controller and I cannot connect to Ds4 windows. Someone please have a solution. It is very important, I have been looking for and trying stuff for several months but nothing to do. I bought this controller especially for the touch pad to use it instead of the mouse on games (steam, emulator etc).
[controller DS4windowsDEBUG.txt](https://github.com/Ryochan7/DS4Windows/files/4230967/controller.DS4windowsDEBUG.txt)

**Comment by mika-n** [comment]
Based on the debug logfile you have a gamepad which is also known as "Nacon Wired Compact" gamepad and this gamepad has been investigated in the past. It is not fully DS4 compatible in PC.
 
However, there are few things you could try out with the debug version. Please try to use following debug options in DS4Windows.exe.config configuration file (edit with Notepad and see the end of the file).

Close DS4WindowsDebug.exe app when you modify the config file. Please re-run the debug app again with these debug options and post the result here. I guess the gamepad you have doesn't have DS4 staqndard features like gyro, touchpad and lightbar? And the gamepad is USB connected and not bluetooth BT connected?

```
Debug_SendRumbleLightbarData=false
Debug_GyroCalibration=false
Debug_ReadTouchpadData=false
Debug_ReadGyroData=false
Debug_ReadBatteryData=false
Debug_ForceConnectionType=1
```

**Comment by JDA-GAMING** [comment]
My controller has a touchpad that works on the PS4 but not on Windows 10.

**Comment by JDA-GAMING** [comment]
My controller works in xinput but I would like to use the touchpad which is integrated into the controller. Do you have a solution ?

**Comment by JDA-GAMING** [comment]
The controller is connected by USB

**Comment by mika-n** [comment]
How the debug log looks like after those Debug_xxx tweaks? Does it work with those options (sticks and buttons), but touchpad doesn't work? 

Is it so that the gamepad has rumble and touchpad? What happens if you set following debug options?

```
Debug_GyroCalibration=false
Debug_ReadTouchpadData=true
Debug_ReadGyroData=false
Debug_ReadBatteryData=false
Debug_SendRumbleLightbarData=true
Debug_SendRumbleLigthbarDataType=1
Debug_SendRumbleLigthbarDataAPI=1
```

Anyway. There is a possibility that the gamepad has a built-in firmware software which detects if it is connected to a PC or PS4 and this way goes automatically to xinput mode or in DS4 mode. In xinput mode touchpad doesn't work.

**Comment by JDA-GAMING** [comment]
First modification: (Debug_SendRumbleLightbarData=false
Debug_GyroCalibration=false
Debug_ReadTouchpadData=false
Debug_ReadGyroData=false
Debug_ReadBatteryData=false
Debug_ForceConnectionType=1)
My screen keeps blinking
[controller DS4windowsDEBUG2.txt](https://github.com/Ryochan7/DS4Windows/files/4233015/controller.DS4windowsDEBUG2.txt)

**Comment by JDA-GAMING** [comment]
But my controller is detected in DS4windowsDEBUG

**Comment by JDA-GAMING** [comment]
Second modif: Debug_GyroCalibration=false
Debug_ReadTouchpadData=true
Debug_ReadGyroData=false
Debug_ReadBatteryData=false
Debug_SendRumbleLightbarData=true
Debug_SendRumbleLightbarDataType=1
Debug_SendRumbleLightbarDataAPI=1)
The controller is not detected.
[controller DS4windowsDEBUG3.txt](https://github.com/Ryochan7/DS4Windows/files/4233053/controller.DS4windowsDEBUG3.txt)

**Comment by JDA-GAMING** [comment]
The controller is not detected

**Comment by JDA-GAMING** [comment]
Can you help me please?

**Comment by mika-n** [comment]
Based on the logfiles it looks like the gamepad you have forces itself to xinput mode in PC (either device driver or firmware in the gamepad does it). 

Official DS4 gamepad does similar thing when the official DS4 gamepad is connected over BT. At first it is in "PC-friendly mode", but after receiving certain configuration commands from PC the gamepad switces itself to native DS4 mode. DS4Windows app sends those configuration commands to DS4 gamepad over BT (ie. PC sends data to gamepad). If the official gamepad is connected over USB then the gamepad is automatically in native DS4 mode.

In theory it could be possible that the gamepad you have would switch over to DS4 mode after some configuration commands are sent over USB connection. Based on the logfiles the problem is that the gamepad has an input buffer size of zero bytes (ie. it doesn't seem to want to receive any data in xinput mode).

You could try changing option _Debug_ForceConnectionType=2_ and leaving other options as described in my previous post. However, I'm not very optimistic that this would solve the issue.

Sorry. It is too difficult to debug this issue without an actual hardware. And still it would be uncertain if the gamepad can be fooled to switch over to DS4 mode in PC connections.¨

Looks like the only hope would be to contact Nacon and ask them if they have any API/communication specs telling how the gamepad can be switched to DS4 mode in PC and ignoring the xinput mode. I doubt they would tell this but you can always ask them if you really really want to get the gamepad to work in DS4 mode in PC.

Easiest route would be to purchase some other DS4 gamepad which is not locked to xinput mode in PC (official Sony DS4 gamepad or numerous other Nacon/Razer/HORI fully compatible gamepad versions).

**Comment by JDA-GAMING** [comment]
Maybe the problem is with the device's functions?
<img width="298" alt="Annotation 2020-02-21 192352" src="https://user-images.githubusercontent.com/61274476/75060882-eb479a80-54df-11ea-9b68-64931c897829.png">

**Comment by mika-n** [comment]
Looks like the gamepad somehow forces itself to be recognized as xbox360 controller (xinput) in PC instead of DS4 dinput or native ds4 gamepad device. Don't know how to fool WinOS to ignore the xbox360 mode.

**Comment by JDA-GAMING** [comment]
I managed to delete the xinput! =)
Now the controller is HID type!!!! =)
<img width="875" alt="Annotation 2020-02-23 202830" src="https://user-images.githubusercontent.com/61274476/75118575-6beece00-567b-11ea-8096-c22ccf981576.png">

**Comment by mika-n** [comment]
How the gamepad behaves now in official (non-debug) DS4Windows app? 
Or maybe posting a debug log while connecting the gamepad now when you have removed xinput driver registration? 
Is touchpad now recognized by DS4Windows app? How about rumble?

If it works now then would you please post detailed instructions what you did because it would help other users using the same kind of Nacon Compact gamepad. I know few other people have asked about the same gamepad.

**Comment by JDA-GAMING** [comment]
DS4WindowsDEBUG-->Log:
[controlleur HID.txt](https://github.com/Ryochan7/DS4Windows/files/4242279/controlleur.HID.txt)

**Comment by JDA-GAMING** [comment]
I hope it will work

**Comment by mika-n** [comment]
hmm... The debug log doesn't show any gamepad devices, so did you connect the gamepad when the debuglog was generated?  At least based on that logfile DS4Windows won't use any gamepad because it doesn't find any devices with Usage=0x5 gamepad usage flag.

**Comment by JDA-GAMING** [comment]
<img width="1144" alt="a new controler xbox 360 virtual" src="https://user-images.githubusercontent.com/61274476/75119087-1e289480-5680-11ea-9b60-ee18bca51770.png">

**Comment by JDA-GAMING** [comment]
[log (modif DS4windowsDebug).txt](https://github.com/Ryochan7/DS4Windows/files/4242360/log.modif.DS4windowsDebug.txt)

**Comment by JDA-GAMING** [comment]
and now?

**Comment by Ryochan7** [comment]
My policy continues to be that I only support hardware that I have direct access to. In my case, that is the Sony branded DS4 v.1, DS4 v.2, and the Sony Wireless Adapter. Third party controller support is left up to other people in the community that have access to the hardware. Pull requests are welcome from people who have tested and gotten other hardware to work in DS4Windows.

The Nacon Compact supposedly presents itself to a PC as an XInput controller already so that takes care of the biggest DS4Windows use case. As for the touchpad use case you mentioned, my opinion is that the DS4 touchpad is not in a good position to use as a primary means of control. It might work out for some swipe controls or moving the mouse cursor on the Windows desktop but not for using in games. I find that accessing the touchpad to be a big stretch when holding the controller normally while gaming. There is no way that I would think that the DS4 touchpad would be a suitable replacement for the touchpads on a Steam Controller.

**Comment by mika-n** [comment]
The latest logfile looks promising, but does it actually work in DS4Windnows? Can you re-map normal button events? 

Touchpad and rumble probably still doesn't work because the gamepad reports "Raw InputReportLen=15  OutputReportLen=0".  OutputReportLen=0 means that the gamepad doesn't want to receive any commands (ie. rumble). InputReportLen=15 is a bit small buffer to contain all normal button events plus touchpad events. It could be that there is some hardware level "detected PC connection, so hard-wiring itself to xinput only mode".

**Comment by JDA-GAMING** [comment]
Ok i give up =(
