### ISSUE TITLE
How to turn off touchpad as virtual mouse / Issues with connecting

### ISSUE THREAD

**Issue by Kybine** [Ryochan7/DS4Windows#1123]
Hello, I had downloaded DS4Windows to help reduce the input delay on my controller, and it had done so successfully. However, I do not need any of the other futures, such as having touchpad as a virtual mouse. It has become a nuisance to my gameplay since I utilize the touchpad as a main function on my controller. Is there any remedy to this?
Also, another issue that I experienced yesterday night, was that my controller would be connected (through a wire) to the USB port, and DS4Windows would not read it. I reset exit out of DS4, disconnected and reconnected my controller, and it still did not show up. I unplugged the USB from its port and connected it to another second port, and it worked. However, today when I tried using DS4 again, I plugged in my controller and it was working fine for a couple of minutes, but no longer reads my controller. Is there anything I can do to solve this? I have already tried connecting to both USB ports, and nothing seems to work.

**Comment by MoHaX87** [comment]
If your game support native controller support , and if you dont use custom mapping for some buttons, you dont need DS4Windows App. Win10 Support DS4 controllers.
Connections problem - maybe bad cable or bad controller port.

**Comment by mika-n** [comment]
You can edit DS4Windows profiles and unmap all default mappings from touchpad and untick "use touchpad as mouse" option (or actually choosing "use touchpad as control" and then unmap all toouchpad gestures).
 
However, if you use USB connection and don't use any re-mappings of DS4Windows then I doubt that using DS4Windows has less lag than using the gamepad directly in a game without running DS4Windows app. If you use BT connection then DS4Windows app is required to utilize extra featues of ds4 gamepad (touchpad, lightbar, gyro, rumble).

**Comment by Kybine** [comment]
When I enable "Hide DS4 Controller" my game runs normally, but I don't get the input delay reduction benefit. Also, when I disconnect my controller with it enabled, and try to reconnect it, my controller is not registered to be connected on my computer at all; not in the game or on DS4. This has also been one of my other concerning issues. @mika-n

**Comment by mika-n** [comment]
Hmm.... HideDS4Controller should not cause re-connection issues but it is possible that "hiding" fails after re-connection if other apps acquired an access to the DS4 gamepad and this way prevented DS4Windows app to use exclusive lock on the physical controller. In some rare cases it may be possible that HideDS4Controller feature leaves the gamepad device in DeviceManager in disabled state. However, this might happend for example when DS4Windows app crashes and is not "cleanly" shutdown.  

If you have re-connection issues then check DeviceManager and make sure there are no HID or gamepad devices in disabled state.
 
>(Even if I exit out of DS4 windows, my controller does not turn off. I've tried restarting my PC but the same issue is there, and it is becoming very frustrating.)

Do you mean that even when the gamepad is connected over USB cable then the gamepad doesn't come alive (ie. lightbar on)? Hmm.... Are you sure the usb cable is in good shape because I don't see how DS4Windows might prevent usb connected gamepad to wakeup and set lightbar on?
