### ISSUE TITLE
All DS4 Analog Button Drifting

### ISSUE THREAD

**Issue by Animus120** [Ryochan7/DS4Windows#1124]
Hello, I recently found out about this updated fork of DS4Windows and immediately switch from Jay2K ones. But as soon as I replaced, all my DS4 (I have 2) are somehow detected as drifting to the top left. I thought it was my DS4 but as soon as I go back to Jay2K's DS4Windows, this problem doesn't exist. Can I get some help on this? Thank you very much. I'm on the latest version of Ryochan7's DS4Windows (2.0.1.0).

**Comment by mika-n** [comment]
See the deadzone setting in a profile editor. Jay2Kings version had a built-in minimum deadzone when the deadzone value in a profile was set to zero value (veeeery illogical). This newer Ryochan7 version allows to use true zero deadzone if the deadzone value in a profile is set to zero value. 
https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping

If you want (in practice analog sticks usually require certain deadzone because analog axies are never completely stable in a hardware level) to use deadzone then you have to set the value in a profile. There are some games which have game specific deadzone customization, so in those cases you may want to use a profile with zero deadzone value.

**Comment by Animus120** [comment]
Thank you for the clear explanation, I'll try checking the deadzone value and change it accordingly when I get back from work to see if that's the problem.

**Comment by Ryochan7** [comment]
I made the decision a long time ago to make 0.00 for a deadzone mean no deadzone. The older Jays2Kings build defaulted to around a 0.03 implicit deadzone for LS and RS when the profile used 0.00. There are times when it might be better just use the game's set deadzone for the sticks rather than enforcing an extra deadzone in the application. Also, even thought there is still an implicit deadzone for mouse controls, I can see the use case of having no deadzone set on a stick when mapping an analog stick to the mouse.

For newly created profiles, the current DS4Windows sets the deadzone for LS and RS as 0.08 in the profile with an anti-deadzone of 0.25. One problem with migrating old profiles is that the newer anti-deadzone setting will be written to the old profile so a stick will likely immediately jump past the set game deadzone and cause analog drift.

**Comment by Ryochan7** [comment]
I was only recently made aware that DS4Windows was still using the older Jays2Kings values for the first created (Default) profile. Version 2.0.12 fixes that problem so that my preferred settings are used for a fresh DS4Windows config.

**Comment by Animus120** [comment]
Thanks for the recent update, this fixed everything.
