### ISSUE TITLE
Forza horizon 4

### ISSUE THREAD

**Issue by GNS7** [Ryochan7/DS4Windows#1125]
The controls keep flinching on the screen. How can I fix it?

**Comment by GNS7** [comment]
[ds4windows_log - Copia.txt](https://github.com/Ryochan7/DS4Windows/files/4243284/ds4windows_log.-.Copia.txt)

**Comment by mika-n** [comment]
The logfile tells you the problem.

"2020-02-24 02:51:22.1099|WARN|Warning: Could not open DS4 DC:0C:2D:C0:7A:D0 exclusively. You must quit other applications like UWP apps (Netflix), Steam, Uplay, NVIDIA IN-GAME before activating the 'Hide DS4 Controller' option. For more info check https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues"

You are probably experiencing double input issue because of badly programmed game (blame Horizon programmers). As a workaround either try to workaround the exclusive access error or install HidGuardian tool if you really cannot find out which other app is "stealing" the physical controller and this way preventing exclusive access to do its magics.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by Ryochan7** [comment]
It is a problem with the game. This type of issue has been discussed a few times before including in the longer issue #463. Forza Horizon 4 does not seem to directly support DirectInput controllers but it will act weird if one is detected. You need to make sure DS4Windows has exclusive access to the DS4 controller or you are going to have a bad time.

**Comment by GNS7** [comment]
ok thanks
