### ISSUE TITLE
Audio stops working as soon as i open DS4Windows

### ISSUE THREAD

**Issue by KillerVan** [Ryochan7/DS4Windows#1130]
I'm using the nacon pro revolution unlimited controller and it's cool that it work well!
BUT when i open DS4Windows the audio of the headphones, that are connected through the jack of the controller, stops working!
The controller has some integrated buttons to change the volume of the sound; and when i rise up the volume through those buttons i can listen to the sound for like 1s and then it stops again.
IT IS REALLY STRANGE.
Please Help!

**Comment by Ryochan7** [comment]
Unfortunately, that can be a consequence of supporting rumble. The output report includes the headphone and mic volumes so if DS4Windows cannot detect the appropriate audio device then the volumes will be set to 0. Detection is done by looking at audio device names. Only the DS4 v.2 and Sony Wireless Adapter are directly supported; it looks like the Razer Raiju TE string identifier is included as well.

What is the name that appears in the Windows mixer for the Nacon Pro Revolution audio device?

**Comment by Robyer** [comment]
@Ryochan7 I have similar problem with audio with DS4Windows with my DS4 v2 and Sony Wireles Adapter. I comment here because I think the source of the problem is the same.

When I use DS4 without DS4Windows, I can hear the sound from the headphones attached to DS4 clearly and correctly. But as soon as I start DS4Windows, it somehow alters the sound and makes it play at lower volume. When I change volume in Windows (audio device called "Sluchátko u sluchátek s mikrofonem (7 - DUALSHOCK®4 USB Wireless Adaptor)") it now plays louder, but after one second it goes down with the volume again. The difference is maybe around 6 % when I play with the volume bar.

Then there is bigger issue that after some time of playing game (maybe 10 minutes, maybe 30...) it starts playing loud random noise instead of the original audio. I stopped using the audio output completely because of this issue, but I think restarting the DS4Windows and the controller fixes the issue..

Is there any way how to make DS4Windows don't touch that audio interface at all? Like ignore everything related to it and let Windows (and the USB Wireless Adaptor) handle that itself?

**Comment by Ryochan7** [comment]
I use the DS4 headphone jack pretty often and I have never encountered a problem with loud random noises popping up. The slightly lower volume is expected as the volume scale is not exactly the same that is used when using the native sound device outside of DS4Windows. It is just a close approximation and works well enough for me; mapping the normal displayed volume directly results in extremely loud and distorted audio based on my experience.

Unfortunately, there is no good way around this behavior. You would have to sacrifice rumble and lightbar functionality in order to have a chance to stop that behavior. The DS4 output report contains the headphone volume levels. DS4Windows attempts to find the native audio device for the DS4 and receive events whenever the volume level of that audio device changes.

**Comment by Ryochan7** [comment]
TODO: Make some sort of volume scale for the microphone level. I get a lot of popping in audio recordings unless the mic volume is down extremely low.
