### ISSUE TITLE
DS4Windows recognizes the controller and all but in games; nope.

### ISSUE THREAD

**Issue by Rogus** [Ryochan7/DS4Windows#1134]
Well, I've tried everything or at least tried to.
Hey @Ryochan7 can I get in touch with you, I have a serious problem with ds4v2 he was connecting just fine even though with those SCR or CSR I can't know for sure. But I bought one of these generic bluetooth dongles, but if I remember correctly it began with S not a C doesn't make any difference anymore, my pc almost got pretty destroyed by the heavy rains I live in the northeast part of Brazil so when it rains it rains pretty silently but this one was pretty heavy, it was a flood thank God and thank Jesus that my mother wake me up early I didn't even knew it was raining until she screamed to make long story short, my pc was wet down on water almost of it mainly in the usb entrances and in reset and power up and almost fricked out the whole thing out so I've tried to play with my micro usb cable from my phone I did stumbled by this image.
Captura de tela 2020-03-02 11 07 31
So sorry for the ramble it kinda got me scared of both losing the controller and the ability of playing with bluetooth wireless option and losing the way to play with micro usb cable btw the cable it is from a charger an original one btw from LG X POWER and in one part it says turbo for connecting at the charging entrance I did all those things like use dinput only installing xbox 360 drivers and vigem all again to repair to see if any kind of errors appear and my ds4 windows main windows shows shared mode and when I open steam it only recognizes the trackpad, that multitouch. Ah one more final question does ds4windows works for Denuvo protected games included with some kind of anticheat protection like EAC or BattlEye or any anticheat measure, so sorry again for the big post.
![Captura de tela 2020-03-02 11 07 31](https://user-images.githubusercontent.com/39033733/76010575-df050980-5ef1-11ea-9233-c2c862c4fa7d.png)

**Comment by mika-n** [comment]
See troubleshooting tips documentation page.

Also please provide the minimum required information to debug issues (version of DS4Windows app, content of the logfile or Logs tap page, what do you see in JOY.CPL controlPanel applet? does the controller work in htmlgamepad.com web site when ds4windows app is not running? and what about when DS4Windows app is running?)

https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

**Comment by Rogus** [comment]
Latest version ok, and in JOY.CPL it works but the calibrating part don't work too well but that testing it works okay all buttons recognized. It works and get recognized by the html5gamepad.com web site both without and with ds4 windows one thing to note  is that okay to have two wireless controllers? When in the case of ds4 windows gets open, and exclusive mode doesn't goes too well even though I am using the hide ds4 controller option marked. And here is the log file
[ds4windows_log_20200303.0.txt](https://github.com/Ryochan7/DS4Windows/files/4294929/ds4windows_log_20200303.0.txt)
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4294930/ds4windows_log.txt)
![Captura de tela 2020-03-05 16 58 52](https://user-images.githubusercontent.com/39033733/76020990-3790d280-5f03-11ea-99e8-80b0db1d26e0.png)
that last one proves that when ds4windows gets loaded and recognizes the controller and a v2 it gets another hash in the product page is it okay?
![Captura de tela 2020-03-05 17 03 35](https://user-images.githubusercontent.com/39033733/76021035-4d05fc80-5f03-11ea-93e1-d3bb050ad4a3.png)

**Comment by Rogus** [comment]
ops.
![Captura de tela 2020-03-05 17 06 10](https://user-images.githubusercontent.com/39033733/76021227-a5d59500-5f03-11ea-921c-bf9b6996cb7b.png)

**Comment by Rogus** [comment]
Like you saw it works. even without the program's open, but that steam it doesn't recognizes when I plug my micro cable usb.

**Comment by mika-n** [comment]
If exclusive mode (=Hide DS4 Controller option in ds4windows app) doesn't work then there will be two WirelessController devices. The first one is the physical original DS4 gamepad and the other one is the virtual output controller created by DS4Windows app and ViGem driver (or xbox360 controller if a ds4windows profile uses xbox360 output controller mode).

See following web pages for more info what to do if exclusive mode fails (as it does in your PC setup based on the logfile) and few tips about Steam stupidity with dualshock4 controllers.

https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#ds4windows-logs-tabpage-complains-that-exclusive-mode-failed-what-it-means-and-what-to-do-now
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

However, the content of the logfile is a bit strange in your setup because there seems to be duplicate entries of the same gamepad. Hopefully it is just a glitch in a logfile content and not in DS4Windows app. What do you see in "Controllers" tab page in DS4Windows? Only one controller?

```
2020-03-05 16:56:16.4283|INFO|Using Exclusive Mode
2020-03-05 16:56:19.3938|INFO|Found Controller: DC:0C:2D:D6:E1:94 (USB) (DS4 v.2)
2020-03-05 16:56:19.3938|INFO|Found Controller: DC:0C:2D:D6:E1:94 (USB) (DS4 v.2)
2020-03-05 16:56:19.4095|WARN|Warning: Could not open DS4 DC:0C:2D:D6:E1:94 exclusively. You must quit other applications like UWP apps (Netflix), Steam, Uplay, NVIDIA IN-GAME before activating the 'Hide DS4 Controller' option. For more info check https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
2020-03-05 16:56:19.4095|WARN|Warning: Could not open DS4 DC:0C:2D:D6:E1:94 exclusively. You must quit other applications like UWP apps (Netflix), Steam, Uplay, NVIDIA IN-GAME before activating the 'Hide DS4 Controller' option. For more info check https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

```

**Comment by Ryochan7** [comment]
One of the logs looks like Start routine is getting invoked twice so that is why the same input DS4 shows up twice. Besides that, I am not sure how much of the problem is actually an error with ViGEmBus.

I just recently had a problem where a virtual device unplug worked fine (to use KB+M profile) but a device plugin did nothing when reverting back to an Xbox 360 profile; there were several seconds in between profile changes so concurrency issues should not be an issue here. DS4Windows showed that the proper output device was requested. Restarting DS4Windows did nothing. Also, got a BSOD upon rebooting so I have to assume that something was wrong within the ViGEmBus driver.

**Comment by Rogus** [comment]
> One of the logs makes it look like the Start routine is getting invoked twice so that is why the same input DS4 shows up twice. Besides that, I am not sure how much of the problem is actually an error with ViGEmBus.
> 
> I just recently had a problem where a virtual device unplug worked fine (to use KB+M profile) but a device plugin did nothing when reverting back to an Xbox 360 profile; there were several seconds in between profile changes so concurrency issues should not be an issue here. DS4Windows showed that the proper output device was requested. Restarting DS4Windows did nothing. Also, got a BSOD upon rebooting so I have to assume that something was wrong within the ViGEmBus driver.

Thanks man, I did passed by that also hey can I help you donating via steam keys? I live in Brazil so you can test more games since my cc can't help because of the ELO banner.

**Comment by Rogus** [comment]
I have this new strange error appearing every time I start DS4Windows.
[String error don't know what this is in the newer version.txt](https://github.com/Ryochan7/DS4Windows/files/4495313/String.error.don.t.know.what.this.is.in.the.newer.version.txt)

[DS4Windows strange error.txt](https://github.com/Ryochan7/DS4Windows/files/4495310/DS4Windows.strange.error.txt)

**Comment by mika-n** [comment]
@Rogus Seems to be permission or shared process issue while DS4Windows app compares the existing version.txt versionstamp file with the one in this Github server. There should never be two DS4Windows processes running at the same time (well, server processes. Cmdline interface may launch the client process), so I wonder which other process is locking that file if the issue is not about permissions.

Meanwhile you could untick "Check updated version" config option to prevent DS4Windows to automatically check new versions.
