### ISSUE TITLE
My Razer Raiju won't connect

### ISSUE THREAD

**Issue by MrYourself** [Ryochan7/DS4Windows#1136]
So Ive been trying to connect y Raiju to DS4, but it won't connect. But in the Control Panel my Raiju is connected

These are the PID's I've found:

HID-compliant game controller:
HID\VID_046D&PID_1007&IG_00
HID\VID_046D&UP:0001_U:0005
HID_DEVICE_SYSTEM_GAME
HID_DEVICE_UP:0001_U:0005
HID_DEVICE

HID-compliant vendor-defined device:
HID\VID_1532&PID_1007&REV_0101&MI_03&Col02
HID\VID_1532&PID_1007&MI_03&Col02
HID\VID_1532&UP:FFF0_U:0040
HID_DEVICE_UP:FFF0_U:0040
HID_DEVICE_UPR:FF00-FFFF
HID_DEVICE

Razer Raiju Tournament:
HID\VID_1532&PID_1007&REV_0101&MI_03&Col01
HID\VID_1532&PID_1007&MI_03&Col01
HID\VID_1532&UP:0001_U:0005
HID_DEVICE_SYSTEM_GAME
HID_DEVICE_UP:0001_U:0005
HID_DEVICE

**Comment by mika-n** [comment]
VID/PID 1532/1007 is supported, so it should work.

If it doesn't work then download the debug version of DS4Windows app and run DS4WindowsDebug.exe app instead of the normal DS4Windows.exe app. The debug version generates loooots of messages about gamepad connection handshaking and it may tell us more clues why it doesn't work there.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by MrYourself** [comment]
[log.txt](https://github.com/Ryochan7/DS4Windows/files/4299746/log.txt)

And here is the log :)

**Comment by mika-n** [comment]
Are you using USB or BT connection? Try using USB at first because usually it is an easier way for WinOS and DS4Windows app. Some non-official DS4 gamepads work over USB but not over BT.

The logfile is a bit strange. By default DS4Windows app uses only devices registered as Usage=0x5 flag (0x5=gamepad hid device). The logfile does have hid entry with Usage=0x5 flag, but that device doesn't report itself as true DS4 gamepad (InputReportLen=15 and OutputReportLen=0). Those values are typical with xinput type of devices (gamepads pretending to be xbox360 gamepads). Do you have some Razer driver installed which forces the device to register itself as xinput device in PC?  DS4Windows app doesn't support xinput gamepads, because it was never the original intention of this app. The idea is to support dinput devices (DS4) and expose those as xinput devices for games which don't support dinput interface.

**Comment by MrYourself** [comment]
I think I installed the razer drivers, yes. But I tried to uninstall it now. And  here is the log: 
[log.txt](https://github.com/Ryochan7/DS4Windows/files/4301570/log.txt)

**Comment by MrYourself** [comment]
And im using USB

**Comment by InvictaNL** [comment]
Having the same issue with my Razer Raiju, tried everything but nothing seems to work.

**Comment by mika-n** [comment]
Still the logile shows `DEBUG: DS4Device. Raw InputReportLen=15  OutputReportLen=0`
These values are typical with some xinput devices, but not with DS4 dinput compatible device. Values may vary between different brands of DS4 gamepads and BT vs USB connected device, but for example InputReportLen=72 OutputReportLen=32 are used in some Razer DS4 compatible gamepads WHEN THOSE ARE in dinput mode.

See these posts for a background info about couple Razer gamepads (the first post talks about the same PID 0x1007 device you have). The gamepads in these posts work nowadays but the requirement is to setup those in a way that PC treats then as dinput device and not as xinput devices.. Don't know details how to do it with the gamepad you have (usually DS4 compatible gamepads don't trick PC to treat them as xinput devices, but i know some gamepads does it. That is very unfortunate decision by the gamepad vendor).
https://github.com/Ryochan7/DS4Windows/issues/580
https://github.com/Ryochan7/DS4Windows/issues/988

**Comment by mika-n** [comment]
> Having the same issue with my Razer Raiju, tried everything but nothing seems to work.

@InvictaNL  See couple posts above and download the debug version and generate a debug logfile.

**Comment by MrYourself** [comment]
I think I've got it.

This morning I just unistalled every driver that could be the Razer Raiju from the device manager. Rebooted my PC and now everything works like a charm

**Comment by mika-n** [comment]
@MrYourself That is great news. The debug logfile did show lots of Raiju related devices and I'm sure one of the uninstalled drivers forced the gamepad to act like xinput device. The debug version should support that gamepad also in BT mode, but the official version does not support BT Raiju TE, yet. One of the links I posted above talked about BT support. The code patch and github change request of BT Raiju TE support into the official code branch has been on my TO-DO list for a while 
already. The debug version already does it, so it is just a matter of time.

@InvictaNL Maybe you should try the same? Uninstall all Razer/Raiju drivers if the problem is that the gamepad forces itself to stupid xinput mode. Download the debug version and post the logfile for further inspection if you cannot get it to work.
