### ISSUE TITLE
DS4 Controller not recognized by DS4Windows 2.0.12 (tried a lot)

### ISSUE THREAD

**Issue by Thad007** [Ryochan7/DS4Windows#1139]
Hello, dear community.

My DS4 Controller is not recognized by DS4Windows 2.0.12. I'm using Windows 10 fully updated.

The Controller is working and I can use it just via the windows driver. The reason I downloaded DS4windows is, that the touchpad seems not to be supported by the windows driver.
So I installed DS4Windows, seemed fine. It also says "Connection to ViGEmBus 1.16.112.0 established."
But it says "No Controllers connected", though my controller is connected and can be tested just fine in windows devices.

I've tried at lot of things and I am now out of ideas:
Rebooted windows. Rebooted DS4Windows. Updated DS4Windows (it says it is the newest version).
Reinstalled DS4Windows.
Deactivated and reactivated windows game controller drivers.
(optionally Rebooted windows. Rebooted DS4Windows.)
Deinstalled and reinstalled windows game controller drivers.
(optionally Rebooted windows. Rebooted DS4Windows.)
Tried four different USB ports while DS4Windows is turned on or off, then turned it on. Every time, windows does recognize the controller, but DS4Windows does not. I realized that in the driver installation log of Windows (device could not be migrated) does always appear, followed by "Device configured" and "Device started". As I said, in windows it just works, and I'm a bit sceptical that is the reason for DS4Windows' troubles. Anyway, I tried a lot of USB ports, rebooting and reinstalls not changing the Windows behaviour on this.

Update: Steam does recognize my DS4 Controller only as a Playstation 3 Controller. Might be related to the problem.

Thanks for any help & Cheers, Thad

**Comment by mika-n** [comment]
See #1136 post. There is a post with a link to Troubleshootng page and a debug version of DS4Windows app (DS4WindowsDeviceDetect zip file). Please go through the troubleshooting tips. I still doesn't work then run the debug version and provide the logfile for further analyzing.

**Comment by Thad007** [comment]
Thank you very much already for the amazingly quick answer! I used the debug version and attached the log here.
[DebugLog.txt](https://github.com/Ryochan7/DS4Windows/files/4303227/DebugLog.txt)

**Comment by mika-n** [comment]
@Thad007   You seem to have NaconWiredCompact gamepad (VID=0x146B PID=0x0603 hardware model code).

There has been earlier attempts to support this gamepad, but unfortunately the NaconWiredCompact gamepad is really stubborn and it forces itself to xinput mode in PC and uses native DS4 dinput mode only with PS4 console.
 
The other post I linked above had a similar problem with Razor TournamentEdition gamepad, but user was able to fix the issue by uninstalling all Razor specific gamepad drivers and the gamepad started to act like "the first class dinput citizen" in PC also. In dinput mode the Razor gamepad works like DS4 gamepad in PC also.

The gamepad you have suffers from the same issue in PC, but so far no one has managed to get the gamepad act like dinput device in PC. It always reports itself as xinput device and DS4Windows was never intended to work with xinput devices because it is not a gamepad communication protocol used in "true native" DS4 gamepads.

If you can figure out how to force the gamepad to act like dinput device in PC then I'm sure the gamepad would work with DS4Windows app. Unfortunately I cannot do it because I don't have such gamepad to debug. All I can give as a tip is to try to remove NaconWiredCompact related drivers from PC or use some other driver for the gamepad and hopefully it no longer switch over to "limited" xinput mode in PC. You could try to connect the gamepad in Linux also and to verify if touchpad and rumble works there? If touchpad and rumble would work in Linux then I'm sure it would be possible to support the same in WinOS also, but someone should debug how the gamepad is initialized as dinput device and not as xinput device.

Or does touchpad and rumble work in Steam bigPicture mode in PC?

See these posts for more info. Unfortunately NaconWiredCompact gamepad is still unsupported in DS4Windows because of the "auto switch to xinput mode" issue in PC.
#1122 
#900

**Comment by Ryochan7** [comment]
Problems like this are why I suggest people to only attempt to use first party DS4 controllers on the PC. It makes sense for the general use case for a controller to force XInput mode when connected to a PC but that decision does severely limit how the controller can be used. Having access to the Gyro is very important to me as I use it in many of my DS4Windows profiles.

Even with a future mapper, supporting XInput compatible controllers will likely not happen. The exclusive mode problem is far worse when dealing with XInput controllers. Obtaining exclusive access to a physical Xbox 360 or Xbox One controller would pretty much be mandatory unless you use an additional software layer like x360ce and utilize passthrough mode; I haven't tested performance while attempting to utilize passthrough mode in x360ce in a long time.

**Comment by Thad007** [comment]
Thank you for your great and elaborate responses!
Actually I was totally not aware that the Nacon Gamepad would be not "true native", since Playstation4 Logos are printed prominently on the package and it was placed next to playstation4's in the store.
Actually the rumble feature works great, but the touchpad did never work on PC. In Steam it is recognized as a Playstation 3 controller, so without the touchpad :( So I'm probably going to give it back to the store and buy a better one. Thank you!

**Comment by tadejdanev** [comment]
same here. using usb cable can't get it to work :(

**Comment by tadejdanev** [comment]
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4314178/ds4windows_log.txt)

**Comment by mika-n** [comment]
@tadejdanev  Looks like the PC doesn't recognize the gamepad connection at all. What do you see in JOY.CPL controlPanel applet when you connect the gamepad over USB without DS4Windows app running? Run joy.cpl command to open the WinOS gamepad control panel. You should see there "Wireless Controller" entry.

Are you sure the usb cable is "fully connected cable"? I have several mobile phone usb cables here which can charge the DS4 gamepad but doesn't connect all required data lines, so those cables don't work as a data cables with DS4 gamepad. The same cable may work in PS4 console, but the situation is a bit different because PS4 console only pairs and charges the gamepad over usb cable but uses bluetooth as a "data line".

Try connecting the gamepad over BT in PC to see if WinOS recognizes it. At first you have to make WinOS to recognize the gamepad before DS4Windows has any chance to use it. JOY.CPL controlPanel applet should list "Wireless Controller" even when ds4windnows app is not running.

**Comment by tadejdanev** [comment]
yes on my windows 7 pc it's ok...while on windows 10 pc it's not....nothing in joy.cpl.....why?

**Comment by tadejdanev** [comment]
got it working.

**Comment by mika-n** [comment]
Great. One thing I'd like to remind you is the following warning in a logfile. Please go through the following documentation page for more info about exlusive mode (=Hide DS4 Controller option in ds4windows app). The warning in the logfile may not be a problem in games you use, but some games may behave weird if there are both the original physical controller device and a virtual output device (created by DS4Windows app and ViGem driver) visible at the same time.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
`
2020-03-11 17:10:31.5112|WARN|Warning: Could not open DS4 1C:96:5A:AC:B7:2B exclusively. You must quit other applications like UWP apps (Netflix), Steam, Uplay, NVIDIA IN-GAME before activating the 'Hide DS4 Controller' option. For more info check https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
`

**Comment by JauM-cmky** [comment]
Olá comunidade.

Queria uma ajuda, sou realmente muito leigo nessa área. Uso o Windows 10 e um Nacon Revollution Pro Controller v1, e uso a versão 2.0.15 do DS4Windows, quando conecto meu controle no PC automaticamente o DS4Windows reconhece, porém o controle não funciona nos jogos, testei pelo Big Picture e os jogos funcionam normalmente com o controle(Só que o jogo que eu preciso do controle é o Fortnite e não consigo usar pelo Big Picture). Já habilitei a função Hide DS4 Controller e mesmo assim não funciona, testei em outras portas USB e não funcionou.

**Comment by mika-n** [comment]
@JauM-cmky     ?

**Comment by Ryusennin** [comment]
And I thought Chinese was hard.
