### ISSUE TITLE
LSDeadZone & RSDeadZone have different values in GUI and XML profile

### ISSUE THREAD

**Issue by Ryusennin** [Ryochan7/DS4Windows#1150]
1. Since the move to the WPF architecture, I've noticed that the Left/Right Stick dead zone values in the GUI are automatically rounded down to inferior values. For example, inputting 0.10 will change to 0.09.

2. Likewise, if I manually change the values in the XML profile, the % will be different in the GUI. For example, LSDeadZone=15 will become 0.12 and  RSDeadZone=10 will give 0.08.

Which ones are the real values? Is this a GUI display bug or a conversion bug?

[Edit] Mmm, it occured to me that maybe the values for those two dead zones in the XML profile are not % but based on 0-128. The others seem to be based on 0-100.

**Comment by mika-n** [comment]
Good catch. This is clearly a bug.

**Comment by mika-n** [comment]
@Ryochan7  Ping. Is there a rounding bug in LS/RS deadzone values in a profile editor? When for example value 0.10 is entered in LS/RS deadzone edit field then it becomes 0.09. The same rounding issue isn't seen in L2/R2/SA deadzone values.

**Comment by Ryochan7** [comment]
The different representations in the GUI and XML is a side effect of the specs for old profiles from at least the Jays2Kings versions if not before with DS4Tool. The GUI represents the dead zone as a percentage. The XML file represents the dead zone in terms of axis units and only taking 127 units into account (negative is actually 128 units on the stick). Most newer settings are represented in the XML as a percentage.

As for the rounding behavior, that was actually a deliberate design choice on my part. The old GUI used to perform rounding to calculate the final value but the newer WPF GUI performs a floor and cuts off the remainder. The same floor operation is perform for L2 and R2 as well but the value range is higher (max is 255) so it is just a lucky coincidence that the behavior is different. SA dead zones are represented as doubles in the backend so no conversion has to be performed.

I like the more definite behavior of performing a floor operation rather than rounding the final number. In that case, the dead zone would need to be set to 0.11 in order for the value to stick and get the value you would want.

**Comment by Ryusennin** [comment]
Thanks for the detailed explanation.

The problem remains that, from the point of view of the average user, it's completely unintuitive.

**Comment by gambl3rkk** [comment]
@mika-n @Ryochan7 , sorry for the instrusion but I am a little bit confused right now. I play fortnite using LSDeadzone= 0,10 and RSDeadzone: 0,08 in the game. My question is: should I turn my deadzones to zero in ds4? or should I leave the ds4 default ones?

**Comment by mika-n** [comment]
If the game has its own customizable deadzone and the range and steps there work for you then you can set DS4Windows to zero deadzone.  However, if the game doesn't have enough range or the precision is too sketchy then you can set zero deadzone in the game and use just DS4Windows to fine tune deadzone.

I don't see much point to use both game and DS4Windows deadzone values at the same time.

Some games have a built-in fixed deadzone and the game doesn't allow to change it. In those cases DS4Windows anti-deadzone becomes handy because it allows to workaround the built-in fixed deadzone.

**Comment by gambl3rkk** [comment]
![ds4](https://user-images.githubusercontent.com/61009745/78290874-b558f580-7524-11ea-96e4-a674b03f7e33.png)
@mika-n Sensitivities and deadzones are well done in fortnite. I am going to try it to zero then, the same goes for the other LS and RS settings?

**Comment by mika-n** [comment]
In that case you can set both deadzone and anti-deadzone to zero value. And leave other settings to default 1.00 value (100% = 1:1 mapping with the physical input value). And leave  output curve to linear and curve input and rotation to zero. This way the "physical raw gamepad LS/RS/R2/L2 event" is sent to the game without any tweaks.

**Comment by gambl3rkk** [comment]
@mika-n Thank you so much, I have been using ds4 in the wrong way until today :)

**Comment by Ryusennin** [comment]
Version 2.0.16 looks legit. Thanks Ryochan!
