### ISSUE TITLE
Profile not working

### ISSUE THREAD

**Issue by FregrinZ** [Ryochan7/DS4Windows#1155]
Hello,

not sure if using this right but cant seem get profile to work in game. binded touch for options but doesnt work

**Comment by mika-n** [comment]
Please share the profile file here as a zip attachment or show a screenshot of the relevant part of the profile setup screen. I didn't quite get it what and how you had re-mapped touchpad.

**Comment by FregrinZ** [comment]
i will post a screenshot later but for example will say swipe left for options button. Any game i try profile doesn't seem do anything,I also loaded a game that doesn't use ds4 just xbox controller and controller wouldnt work at all.

**Comment by mika-n** [comment]
Mapping "swipe left" as "Options" button works just fine here both in xbox and dualshock4 output modes. Check the general option "Swype touchpad to switch profiles" option in DS4Windows settings (not a profile specific but common option for all profiles). Untick this option to make sure that DS4Windows won't try to change a profile when swipe touchpad.

I find "swype to change profiles" functionality very clumsy. IMHO the better option to change profiles on the fly is to use a special action and bind a certain key to do it. Or use "auto-profiles" feature to let DS4Windows to do it automagically.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#how-to-change-a-profile-on-the-fly-via-a-certain-gamepad-button-using-a-special-action
https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules


Also. Are you using "Hide DS4 Controller" option or HidGuardian tool to hide the original physical controller from games? If not then maybe the game is confused because button events are coming from two devices at the same time?
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by FregrinZ** [comment]
[default.zip](https://github.com/Ryochan7/DS4Windows/files/4348561/default.zip)

**Comment by mika-n** [comment]
You have set "Use DInput only" option in the profile. If you use this option then only mouse+keyboard re-mapping and macros work, but gamepad button re-mapping doesn't work because the original dinput device is exposed as "raw device" without any custom remapping. So, untick this "UseDInputOnly" option.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#games-dont-see-any-controller-not-the-virtual-gamepad-controller-or-physical-controller

Also. The "Flush HID" option is probably not needed. It is an old option and not recommended to use these days.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#gamepad-inputs-seem-to-be-sometimes-lost-especially-when-i-press-several-buttons-at-the-same-time

**Comment by FregrinZ** [comment]
maybe its not installed correctly or am doing something wrong, my games dont even see controller at all if use ds4windows.

**Comment by mika-n** [comment]
Jep. See the previous comment. You have set "Use DInput only" option and it it causing this problem. And you still may wanna check the "Swipe to change profiles" general option also (untick it).

**Comment by FregrinZ** [comment]
sorry i adjusted that before posting. I installed windows 7 xbox 360 drivers and gamepad works now. Weird because am on windows 10. if can set touchpad to bindings on left and right side now which works but i cant simply touch?

**Comment by mika-n** [comment]
There is touchpad "click" event also when you press the touchpanel, but it is true that there is no simple "touch" (without clicking or swiping) re-map rule.

**Comment by FregrinZ** [comment]
well all seemed good then tried fallout 76 and opened map and cursor moves all over place

**Comment by mika-n** [comment]
Check deadzone in LS/RS sticks.  
https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping

And check exclusiveMode functionality to make sure the game is not confused of double inputs. https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by Ryochan7** [comment]
> well all seemed good then tried fallout 76 and opened map and cursor moves all over place

It just works.

Tell me lies. Tell me sweet little lies.

https://www.youtube.com/watch?v=hFcLyDb6niA
