### ISSUE TITLE
Calibration issue (Steering wheel emulation)

### ISSUE THREAD

**Issue by Torxed** [Ryochan7/DS4Windows#1157]
After hitting calibrate:

![image](https://user-images.githubusercontent.com/861439/77062125-96624b80-69db-11ea-8aa5-2dfd3ae73ea1.png)

I'm prompted with:

![image](https://user-images.githubusercontent.com/861439/77062159-a11ce080-69db-11ea-8206-0effc4ad6d78.png)

Which seemingly doesn't do anything?
Pressing <kbd>X</kbd> doesn't appear to be doing anything.

Currently in for instance F1, the steering wheel will twitch and not go all the way but max out around 85%.

Edit: On another machine, the light bar turns green some times, and some times it doesn't. Input progress or visuatilization would probably be handy here.

**Comment by mika-n** [comment]
The calibration GUI is a bit difficult to understand because there is no graphical animation to explain how to do it. At some point I will probably add such a visualization there. Anyway, I'll try to explain here how it goes

- Choose an output axis for a gyro "steering wheel" in "Steering wheel axis" dropdow list. Usually Left-X axis if some racing game is used. Some apps support multiple controllers (for example both gamepad and joystick) then you can choose V-Joy virtual joystick axis also. VJoy option requires an installation of vjoy driver and app (not part of DS4Windows app).
- Choose steering wheel "lock to lock" range. By default 360 degrees.
- Press "Calibrate" button
- Orient the gamepad in "center position" as if wheels should be straight ahead. Keep the gamepad steady (don't shake it) and press "X" button. The gamepad color should turn to yellow to indicate that the first calibration point it set.
- Turn the gamepad 90 degree left. Keep the gamepad steady and press "X" button. The lightbar should turn to blue.
- Turn the gamepad to 90 degree left position. Keep the gamepad steady and press "X" button. Now when all three calibration points are set the lightbar should turn to green.
- At this point you can test the "steering wheel" by turning it. The green lightbar starts to blink when the gamepad is oriented in one of the calibration points. You can verify that, for example, center position is where you want it to be.
- If you are happy with the calibration then press "OK" to accept those values.
- There is no need to do this calibration twice for the same gamepad because calibration values are stored in profile folder.

Here are few more words about this steering wheel emulation.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#steering-wheel

Please note that the steering wheel emulation works best if the gamepad stays within the same 3D-orientation as it was during the calibration. It makes the accuracy much better. In practice it may need a "do-it-yourself" rig to make the gamepad physically "to behave" like a steering wheel. If you try to do all this "in free hands in the middle of the air" then it is veeery difficult to keep turning the gamepad along the calibration way. Not the mention that gaming immersion is much better when the gamepad is attached to a "steering wheel rig".
https://github.com/Ryochan7/DS4Windows/pull/491#issuecomment-439821245
 
I use this rig and steering wheel emulation mode in EuroTruckSimulator. Works wonderfully. It works also in more faster racing games, but some racing games with a console gamepad support has very big deadzone (because LS stick is not very accurate). In those games you have to adjust the sixaxis X anti-deadzone in axis config setting screen. This is explained in the Settings link I linked above.

Alternative way to use gyro as steering wheel (mapped as LS x axis) is to use "steering wheel mode 1" as explained in the settings screen. In that option you can map the raw gyro X (or was it Z?) axis to LS x axis. However, it has veeeery limited turning range (only 45 degrees) and it doesn't lock the gyro axis to max range, so if you turn the gamepad too much then the axis wraps around.

**Comment by Torxed** [comment]
That seams to do the trick, altho it's not always the controller turns yellow at the start.
But changing computer made it work, so might be something with my installation or setup on the other machine.

Appreciate the well written info/feedback!
And I'm looking forward to follow the improvements! Great work on keeping this project alive! :)

**Comment by Torxed** [comment]
For reference in case of the calibration issue, this is what it looks like: https://youtu.be/0ZPPMX7Muro
The LED is constant red. I know it's hard to see, but I'm holding it steady in dead center, hitting <kbd>X</kbd> and then turn left, hitting the <kbd>X</kbd> again and then same for right.

If I turn the controller up-side-down, the bar becomes yellow :)

**Comment by mika-n** [comment]
Hmm.... The calibration and "X" button press has a validation routine which checks that the gamepad is "stable enough" before the calibration point is accepted. If the gamepad shakes too much (ie gyro sensors) while triggering the X button then calibration waits few seconds to see if the gamepad stabilizes.

Also, if you calibrate it without a rig (ie. the gamepad is hold freely) then you still have to try to make sure that you turn the gamepad around (center, 90 left, 90 right) an imaginary center "steering wheel shaft". If the gamepad shakes too much and values are not consistent enough then the calibration may fail. This is why I use the "steering wheel mode 2" only with a do-it-yourself rig.

If you don't use a rig then the "steering wheel mode 1" may work better (ie. raw sixaxis X or Z sensor value is directly mapped as LS X-axis). Unfortunately this has very limited 0..128 "turn range" and turning is not "locked" when the gamepad is turned to max position left or right (ie. axis values wrap around, which is very annoying when used as a "steering wheel").

**Comment by Torxed** [comment]
> turning is not "locked" when the game pad is turned to max position left or right (ie. axis values wrap around, which is very annoying when used as a "steering wheel").

Ah, haha. Yea I was wondering why that happened *(that was my first setting and it was freakishly annoying). I actually managed to get the calibration working by free-handing it, the calibration values on the bottom left corner of the window while calibrating really helped to hold it stabilized.
