### ISSUE TITLE
On-screen keyboard and Civilization won’t work

### ISSUE THREAD

**Issue by acorneye** [Ryochan7/DS4Windows#1159]
I can’t use the controller as a mouse in the on screen keyboard or in Civ 6. In Civ 6 the mouse won’t even move. In the onscreen keyboard I can move the mouse but can’t press the buttons.

**Comment by mika-n** [comment]
DS4Windows posts mouse movement events programmatically to a mouse message queue in WinOS. Could be a game specific issue. For some reason the game won't react to these programmatically generated mouse messages. Sorry, I don't have CIV6 so I can't help more.

**Comment by Ryochan7** [comment]
Not sure about Civ 6. I have Civ 4 and Civ 5 though and virtual mouse events work in those games. I would assume that it likely a UAC permission problem. You might need to launch DS4Windows as the admin in order to have Civ 6 see the mouse events in game.

I would think that mouse clicks would work with the on-screen keyboard even when DS4Windows is launched as a normal user. It could just be a mapping problem. I would need a copy of the profile you are using to confirm that one.
