### ISSUE TITLE
BT Poll Rate

### ISSUE THREAD

**Issue by KMixa** [Ryochan7/DS4Windows#1161]
First of all, I would like to thank Ryochan7 and all the people helping him make a this fantastic tool.

Also, I must say that this is not an issue, everything works perfectly since I installed the tool, just wanted to check and see if I am doing everything right with BT Poll Rate option.

So, I bought a USB Bluetooth v.4.0 dongle with Frequency band: 2.402 - 2.48 and up to 24 Mbps speed. When I firstly connected my DS4, I had input of 3-4ms, but then, I switched BT Poll Rate from Default value (I think it was 250Hz) to max, and now input delay is locked at 0. So I wanted to know is this ok thing to do, it want ruin my Bluetooth or most importantly, my new DS4, and if it really makes input lag go from 3-4ms to 0?

Once again, fantastic work from you guys. Much love and support from me!

**Comment by KMixa** [comment]
@Ryochan7 can you reply on this when you have time? Is it ok to use BT Poll Rate on Max Level, and that it will not result in a battery problems in the future, or in any way have an impact on battery?

**Comment by Ryochan7** [comment]
Battery life should be lower when using the Max possible poll rate. I have never ran any real tests to find out by how much. One other factor is if you connect multiple controllers to your BT adapter. You might not be able to use Max setting for multiple controllers if the traffic is too much for your dongle to handle. At that point, you will have to play with the poll rate setting to find out when the connection gets stable again. Only had that type of experience with an older BT 2.1+ adapter.

Also, the min interval should be around 1.25 ms. I have already incorporated a change so that the displayed value will be seen as a double. Luckily it was no problem this time around and I was using string.Format in this version already.

**Comment by KMixa** [comment]
@Ryochan7 , thank you for your reply. Then, I don't think it is worth it to use max possible poll rate to lover 4ms input lag to 1ms. In my case, it would be better than to use default value of 250Hz to prolong DS4 battery life.

Apart from that, I don't see how can I lover my input lag even more? Maybe disable mouse option, because I don't use it in my games? That can help with battery life also.

**Comment by mika-n** [comment]
the latest version has "Enable Output data to DS4" option. If you untick this DS4Windows app won't use rumble and lighbar (ie. PC won't write out data to DS4 gamepad every few millisecond). Unticking this option probably saves some precious juice in DS4 pad.
