### ISSUE TITLE
What does the number value 0-5 do on square stick?

### ISSUE THREAD

**Issue by tzx613** [Ryochan7/DS4Windows#1168]
This isnt really an issue, but I'm currently using DS4Windows to square the deadzone like a DS3 controller. And I was wondering what exactly the square stick value changes? This:

https://i.imgur.com/LIXN0VC.jpg

Does it change the aggressiveness of the square? Meaning THIS would be **Cross Deadzone**:

https://i.imgur.com/bRYpJNq.png

This would be **Square Deadzone (5)**:

https://i.imgur.com/kl7HEJB.png

And I'm guessing the lower values (0,1,2,3,4) would be slightly less squared?

**Comment by mika-n** [comment]
These posts probably explain it in a bit more detail. The wiki documentation page on this site is a bit incomplete to explain all options (well, most options are a bit incomplete in wiki doc page). 
https://github.com/Ryochan7/DS4Windows/pull/740
https://github.com/Ryochan7/DS4Windows/issues/738

**Comment by Ryochan7** [comment]
> And I'm guessing the lower values (0,1,2,3,4) would be slightly less squared?

The lower values would make the output more squared. The algorithm is meant to keep the lower portion of the output more circular while still allowing the high end output to reach the corners of a square. Choosing 0 would result in a pure square output range. I personally prefer the low end of the output to be more circular so that is why the default value is set to 5.

Inner Roundness = 0:
![Roundness 0](http://theinstructionlimit.com/wp-content/uploads/2009/11/square-small.png)

Inner Roundness = 1:
![Roundness 1](http://theinstructionlimit.com/wp-content/uploads/2009/11/round-small.png)

Inner Roundness = 5
![Roundness 5](http://theinstructionlimit.com/wp-content/uploads/2009/11/rounder-small.png)

http://theinstructionlimit.com/squaring-the-thumbsticks

**Comment by tzx613** [comment]
Ok so just to be clear, in those pictures you posted, the left side is default cross/circle deadzone, and when using square stick, it isn't a turned square / diamond shape like this?

![kl7HEJB](https://user-images.githubusercontent.com/44180859/77718874-580bf400-6fba-11ea-8487-aad28116d61e.png)

**Comment by Ryochan7** [comment]
The images are graphed input vs output. Left image is input and right image is mapped output. As the Roundness setting is increased, the lower portion of the output becomes more circular.

The value of 5 is used as the default as that was what I liked best when I played Star Wars: Shadows of the Empire. The setting has come in handy while playing some older games that only support DirectInput.

**Comment by tzx613** [comment]
Alright if I'm being honest I've never felt more stupid. What is the difference between input and output? What are they? When I touch something on a controller isn't this input? Where is the output coming from?...

**Comment by mika-n** [comment]
Maybe the following post explains what is input for DS4Windows and what it output from DS4Windows app. Games will eventually see the "output pipe" of DS4Windows.
https://github.com/Ryochan7/DS4Windows/issues/1175#issuecomment-604864835

Remember. DS4Windows profiles can do all sort of remapping and re-adjusting with the physical button, stick, gyro and touchpad events before the result is outputted to games via a virtual gamepad device created by DS4Windows app and ViGem driver.

https://github.com/Ryochan7/DS4Windows/wiki/Settings
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by tzx613** [comment]
Ah, I dont think I'll ever fully understand
I'm using square stick to play rocket league, trying to find that sweet spot of speed but also control
