### ISSUE TITLE
nothing opens

### ISSUE THREAD

**Issue by Kendallplays** [Ryochan7/DS4Windows#1173]
using the latest version, nothing happens when i open it.

**Comment by mika-n** [comment]
If you rollback to the previous DS4Windows version then does it work? Which version you had previously?

**Comment by Kendallplays** [comment]
ii will try

**Comment by Deyvit-T** [comment]
I deleted the entire folder % APPDATA% \ DS4Windows and the app worked again.

**Comment by mika-n** [comment]
There has been cases where some config entries from an old version have caused an app crash. Or if the GUI is not shown then it is opened beyond the visible screen area (#1162 ).

Anyway. Good thing the issue is solved even when it is still a mystery which config entry caused the issue (crash or GUI not shown?)
