### ISSUE TITLE
Why vigem bus driver and "competition" ds4

### ISSUE THREAD

**Issue by gabri25ele** [Ryochan7/DS4Windows#1175]
Why need to install the vigem bus driver?
What is this bus?
and why there is an also DS4 (https://github.com/Jays2Kings/DS4Windows/releases) who does not need this vigem.

**Comment by Ryochan7** [comment]
Read the README first

https://github.com/Ryochan7/DS4Windows/blob/jay/README.md

**Comment by mika-n** [comment]
> and why there is an also DS4 (https://github.com/Jays2Kings/DS4Windows/releases) who does not need this vigem.

The old Jays2Kings (not supported anymore, I guess) version used ScpVBus driver which does similar things than ViGem driver. So, the question should be "why newer version of Ryochan7 DS4Windows uses ViGem driver instead of the ancient ScpVBus driver to expose the virtual output controller".

ScpvBus driver haven't been supported for years anymore (by the original author) and the ScvBus driver did some dirty hacks not supported officially in Windows device driver API. It caused problems with BT devices.

ViGem driver in Ryochan7 V2.x DS4Windows basically does the same as ScpVBus driver in Jay2Kings 1.4.x version of DS4Windows. But, the author of those drivers (Nefarius) no longer recommend people to use ScpVBus driver. He has created the ViGem driver to do the same, but it is the first class citizen of Win device driver API.

> What is this bus?

https://github.com/Ryochan7/DS4Windows/wiki/Settings

It creates a virtual output gamepad driver. In a high level the process goes as this:
- DS4Windows app reads gamepad events from the physical gamepad.
- DS4Windows app processes those incoming physical gamepad events through re-map rules defined in DS4Windows profiles (button remaps, stick curve output adjusting, macros, etc etc).
- DS4Windows app outputs re-mapped gamepad events to the virtual output gamepad device created by ViGem device driver (or ScpVBus driver in old V1.4.x version). The virtual output gamepad is exposed to WinOS and games as xbox360 or dualshock4 gamepad type.
- Games read gamepad events from the virtual gamepad device and not from the physical gamepad (because the physical gamepad doesn't show re-mapped button events because it shows only the raw physical button events).

**Comment by Ryochan7** [comment]
Personally I didn't think that the post deserved a real response. Not even acknowledging the ScpVBus driver used by the Jays2Kings build and then acting like using the updated ViGEmBus driver is superfluous. Asking why one driver is used over the other would have been a legitimate question that I would have answered.

**Comment by gabri25ele** [comment]
maybe it would be better to ask why the bus is always loaded in memory? while the other doesn't?

**Comment by mika-n** [comment]
What bus? ViGem is a kernel device driver and those live their own life and WinOS handles those entities based on connected devices and services. Device drivers don't behave like a traditional application.

Or do you mean the old ScpToolkit+ScpvBus and why it behaves differently than the newer ViGem+DS4Windows? You should probably ask the question in ViGem and ScpToolkit forums (well, ScpToolkit doesn't have an "official" forum anymore because the original developer is no longer endorsing and supporting it).
https://forums.vigem.org/topic/256/leaving-scptoolkit-behind-probably-a-stupid-question

**Comment by gabri25ele** [comment]
yes, probably is a "problem" of ViGem

**Comment by mika-n** [comment]
Feature. Not a problem. Although, I still don't see where you see a problem. But, the good news is that if the old Jay2Kings V1.4x version of DS4Windows+ScpVBus does what you need then feel free to use it. But it won't receive any new features or bug fixes and prepare for problems if you use bluetooth with Scptoolkit/ScpVBus (ie. other BT devices may behave strangely after ScpToolkit hijacks the BT driver stack).

**Comment by gabri25ele** [comment]
Feature. Problem.
point of view.
personally I prefer to have as few things as possible loaded in memory and only when necessary.

**Comment by Ryochan7** [comment]
This is pointless.
