### ISSUE TITLE
DS4Windows spamming random buttons

### ISSUE THREAD

**Issue by caden3ds** [Ryochan7/DS4Windows#1186]
I assigned the controller to different keyboard keys for a emulator, but it's randomly spamming them.

**Comment by Ryusennin** [comment]
Make sure you set some minimum dead zone (like 0.05) for your analog controls, especially the sticks.

**Comment by AlexByte** [comment]
why is it not necessary to do this in the old version?

**Comment by mika-n** [comment]
The old Jays2King V1.4.x version had a built-in deadzone even when a profile had set 0.0 deadzone value. That's why. This new V2.x Ryochan7 version allows to use true "zero" deadzone in LS/RS sticks because in some scenarios it is useful. However, if you map LS/RS stick to keyboard then you definetly need to set some deadzone because LS/RS stick is never completely stable in a hardware level (springs wear out, dust, etc).
