### ISSUE TITLE
Controller Readings Greyed Out

### ISSUE THREAD

**Issue by iaind5150** [Ryochan7/DS4Windows#1187]
Hello, I'm trying to lower the input delay to as little as possible and, on a previous version I could access the controller readings.. Now I cannot for some reason, both with a wired connection and BT. For what it's worth I'm using the motherboard BT (Asus X570-E Gaming)

I have my bluetooth polling rate set to max (1ms) and I can't confirm this with controller readings anymore. I'm using DS4 Windows Version 2.0.14. Any ideas?

**Comment by Ryochan7** [comment]
That is intentional when you open the Profile Editor from the Profiles tab. People had reported issues with the readings in the Controller Readings tab thinking they were errors. It has to be said that it was a case of people not using the program the way I do. When opened from the Profiles tab, the output readings would not match the values associated with the profile being edited. Instead, the tab would reflect the output from the actual active profile associated with a controller slot.

It was just easier for now to disable that use rather than try to hack something together quickly. If you want to use the Controller Readings tab for now, make sure to use the Edit or New Profile options from the list in the Controllers tab.

**Comment by Ryochan7** [comment]
I have an updated patch that restores the tab and more accurately portrays the proper profile settings in that circumstance. Not sure if I would want to commit it though. People would probably complain when using KB+M profiles that the settings are not honored despite choosing to use the temp slot.
