### ISSUE TITLE
Randomly restarting

### ISSUE THREAD

**Issue by AlbertZoto** [Ryochan7/DS4Windows#1192]
Hello friends, first of all thanks Ryochan7 for the hardwork.

I want to ask the community if someone is having the same issue that I am.

My controller restarts unexpectedly after some time with apparently no reason, I'm attaching the log file so maybe you can help me with this. My controller is connected via bluetooth

Thank you guys. 

[log.txt](https://github.com/Ryochan7/DS4Windows/files/4407475/log.txt)
 restarts randomly occasionally

**Comment by mika-n** [comment]
BT connectivity issue? At some point write-data over BT to the gamepad fails, so DS4Windows thinks that the gamepad was disconnected?

You could run a debug version because it will generate more detailed logfile and it should reveal if this is the case.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by AlbertZoto** [comment]
Hey guys, I'm back after a long time.

Today I finally was able to play some videogames and I got the same error I've had before. 

The controller worked fine for a couple of hours but suddenly it started to disconnect randomly again. 

I followed @mika-n advice and saved my log so you can help me find out what's going on.

PD. Malfunction started nearly at the end of the log file

Many thanks fellas.
[debuglog160620.txt](https://github.com/Ryochan7/DS4Windows/files/4789632/debuglog160620.txt)

**Comment by mika-n** [comment]
duplicate with #1353  
Please don't open multiple threads from the same issue.
