### ISSUE TITLE
Wireless Problem no input

### ISSUE THREAD

**Issue by qidds1** [Ryochan7/DS4Windows#1193]
![image](https://user-images.githubusercontent.com/45920243/78020957-edc1cd80-7384-11ea-96f5-a313b154ad21.png)
![image](https://user-images.githubusercontent.com/45920243/78021188-6032ad80-7385-11ea-93e4-28ad086a36d2.png)
The battery shows 0% but I think it is just a bug since Wired also it displays as 0%, my controller still lights up.
It is connected and but have no input. It is connected by Bluetooth.

If I untick Hide DS4 Controller, one will be Wireless Controller but receive input, the other will be XBOX360 but receive no input.

**Comment by mika-n** [comment]
How about USB connection?

Take a look at the following post. Try running the DeviceDetect debug version and see if the logfile there tells more clues.
https://github.com/Ryochan7/DS4Windows/issues/1192#issuecomment-606533097

**Comment by qidds1** [comment]
Okay funny, the debug version works perfectly.
[Bluetooth.txt](https://github.com/Ryochan7/DS4Windows/files/4409160/Bluetooth.txt)
[USB.txt](https://github.com/Ryochan7/DS4Windows/files/4409162/USB.txt)

The debug DS4 works perfectly with what I intended. The controller has input and can Hide DS4 Controller so no duplicate input. I just want it to detect as X360 so I do not need to add x360ce to every game wirelessly/wired.

**Comment by mika-n** [comment]
Interesting results from the bluetooth.txt logfile. Are you sure you have a genuine DS4 (revision1) gamepad and not a wanna-be "fake" copy? Where did you purchase it? 

```
03/31/2020 20:58:43: DEBUG: findControllers. idx=0 Opening device VID=0x054C  PID=0x05C4  isExclusiveMode=False
03/31/2020 20:58:43: DEBUG: DS4Device. DS4 v.1 conType=BT  MAC=D0:27:96:C0:45:2F
03/31/2020 20:58:43: DEBUG: RefreshCalibration. ERROR. readFeatureData failed. conType=BT dataType=5 LastErrorCode=0
03/31/2020 20:58:43: DEBUG: performDs4Input. WARNING. D0:27:96:C0:45:2F unexpected BT packet type. Continuing to accept PC-friendly packets from BT connection. btInputReport type0=1  type2=128
```
The BT connected gamepad is detected as VID/PID 054c/05c4 hardware and only Sony is supposed to use that identifier. And because of this identifier the gamepad is listed as "DS4 v1".
But the calibration of gyro sensors fail. Usually fake DS4 gamepads fail with this because those don't have "the perfect" Sony sixaxis sensor support. However, this error is not fatal.
The next warning is fatal in the official version, but debug version tries to recover it automagically. The gamepad fails in CRC32 check of BT data data packets and the incoming BT data packet is not in expected format (in "official" Sony ds4 format). This is also usually sign of fake copies.

The debug version tries to ignore this last warning and use the gamepad anyway, so this is why the gamepad works with the debug version  but not with the official version. 

Can you test if lightbar, rumble, gyro and touchpad works with the debug version?

If those work then there are two type of DS4 (v1?) gamepads on the martket. The official one which send BT data packets in "Sony DS4 native" format and gamepads which send the BT data packet in so called "PC-friendly format".

**Comment by qidds1** [comment]
I don't think I have the original one. 

Using Bluetooth the touchpad does not work but I don't mind because I am not using it much and the light also does not change according to the profile.

I hope this issue can be brought into the official one since the debug version work very perfectly just as if I was using the USB one.

**Comment by mika-n** [comment]
If you set "Debug_ForceConnectionType=1" debug option (ie. force DS4Windows to handle data communication line over BT as it was USB connection). Does touchpad and lightbar and rumble work then over BT?

Or leaving the connection type option in default value and setting these options:
Debug_GyroCalibrationType=1
Debug_SendRumbleLightbarDataType=1
Debug_SendRumbleLightbarDataAPI=1 or 2

**Comment by qidds1** [comment]
This is the log for
`Debug_ForceConnectionType=1`
[ForceUSB.txt](https://github.com/Ryochan7/DS4Windows/files/4415535/ForceUSB.txt)

This is the log for
`Debug_GyroCalibrationType=1`
`Debug_SendRumbleLightbarDataType=1`
`Debug_SendRumbleLightbarDataAPI=2`
[ForceOtherSettings.txt](https://github.com/Ryochan7/DS4Windows/files/4415537/ForceOtherSettings.txt)

For
`Debug_SendRumbleLightbarDataAPI=1`
it just crashes the DS4Windows

**Comment by mika-n** [comment]
Okey. The gamepad doesn't seem to have fully compatible "DS4 mode" in BT connections. At this point you can use the debug version because it is exactly the same as official version, except that in the beginning it dumps out loooots of detailed messages and it does this "fallback to accept PC-friendly BT data packets if BT doen't send true native DS4 data packets" mode. 

I have to try to find time to post a code change to make these "PC-friendly only" BT ds4 gamepads compatible with DS4Windows app. I know some Nacon/Hori users are also waiting for this change because owners of those certain gamepads are also stuck with the debug version at the moment.
