### ISSUE TITLE
DS4 light flashing

### ISSUE THREAD

**Issue by Comitant** [Ryochan7/DS4Windows#1198]
On bluetooth battery always shows 0% and my controller LED is flashing, yet when I plug it in both these issues go away. *The issue seems to have went away after a while, I'm not sure what happened though as the battery level was normal to start with. **Issue just came up again, is there any way to turn off the flashing?

**Comment by mika-n** [comment]
There must be some problems while DS4Windows app reads the battery level status in BT mode. Or the gamepad doesn't send this data and it is always reported as 0%. 

Take a look at the Logs tabpage. Is the flashing because of battery or high latency?

You can disable "high latency led flash" by unticking "Flash lightbat at high latency" option (general Settings, not a profile specific setting).

To disable low battery flashing set the Lightbar/FlashAt value to -10 (=disable low battery warning).

Are you using a genuine DS4 gamepad or some compatible model? Or is it a fake DS4 wanne-be chinese copy? There are fake DS4 gamepads which look exactly like Sony DS4 gamepad, but are not exactly the same. Usually those work just fine over USB, but BT mode may have some incompatibility issues with touchpad/gyro/lightbar/rumble.
