### ISSUE TITLE
Steam and DS4

### ISSUE THREAD

**Issue by Jassemm** [Ryochan7/DS4Windows#1199]
Hello there, 

I tried all the troubleshooting solution but didn't seem to work. the issue is whenever I connect ps4 controller without disguising it as PS4 in DS4 options, it works flawlessly in steam, however if I disguise it as a PS4 it just disappear from steam and doesn't work. weirdly, yesterday it was fine and for the last couple of months it worked without an issue. today just happened, nothing changed in the settings but I have auto update on, so maybe new version released and update effected it. 

I also wanna mention, I tried installing HID after the issue and it didn't help, steam cant recognise it now even if I close DS4, it can only be recognised when I start DS4 and set it as x360 controller. 

could you please guide me, where is the issue and what im missing here to get it to work.

DS4 V2, windows 10.

thank you for your hard work.

**Comment by mika-n** [comment]
Maybe something like this?
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

Try renaming the DS4Windows.exe and xxx.config file to DS4WApp.exe and DS4WApp.exe.config names. This behaviour is a problem in Steam client (ie. it does what was described in the troubleshooting doc without telling anything about it to user or letting user to choose an option how it behaves). DS4Windows app is not the only DS4Windows gamepad app Steam client "breaks".

**Comment by Jassemm** [comment]
as stated above, I did try the solutions provided in the troubleshooting including changing the name. option to make it look like PS4 controller just makes it disappear in steam, even when exclusive mode is on.

**Comment by mika-n** [comment]
Are you using HidGuardian tool to hide the physical controller or "Hide DS4 Controller" option in DS4Windows app?  If you use HidG driver to avoid double input issues then do you have DS4v1 or DS4v2 gamepad? 
https://github.com/Ryochan7/DS4Windows/issues/1099#issuecomment-583879881

What do you see in JOY.CPL controlPanel applet when DS4Windows uses dualshock4 profile?

I haven't tested Steam ds4 support recently, so in theory it could be that new Steam client may do some additional nasty logic with DS4 gamepad type.

**Comment by Jassemm** [comment]
supposedly, to hide physical to avoid the double input. but after restarting both disappeared.
while on JOY.CPL as ps4 profile I don't see any controller, where on xbox profile I can see its recognised.

**Comment by mika-n** [comment]
HidGuardian tool is an alternative and optional solution to hide the physical DS4 device from games. It is not the same as "Hide DS4 Controller" option in DS4Windows app, but the purpose is the same in both of these options. However, don't use both HidG driver and "Hide DS4 Controller" option at the same time. This "Hide DS4 Controller" option is sometimes called as "exclusive mode".
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Also, don't use "Use DInput only" profile option and "Hide DS4 Controller/HidGuardian" at the same time. This would lead to a situation where the physical gamepad is hidden, but the virtual output controller is not created either. So the end result would be "no gamepad" devices situation.
 
HidGuardian tool is NOT supplied with DS4Windows and not part of the app. It is just something DS4Windows app supports if user has installed it. If the "Hide DS4 Controller" (=exclusive mode) works then there is no need to install HidGuardian tool.

Anyway. If you have HidGuardian then it is possible that it hides both the physical gamepad (as it should do), but accidentally hides also the virtual D4 gamepad. The net result is "no gamepads".  The solution to this is explained in the previous comments I listed. Because you have DS4v2 gamepad then you can tweak the AffectedDevices sysreg entry of HidGuardian tool to hide only the DS4v2 gamepad and leaving DS4v1 gamepad type visible. The virtual output gamepad has always DS4v1 hardware identiier.

Anyway. If you don't have HidGuardian installed then you don't have to worry about this, because this "AffectedDevices" sysreg entry is something not related to "HideDS4Controller/exclusive mode" option.

Please attach the logfile and profile file here as an attachment (drag-and-drop those files to a comment box).

**Comment by Jassemm** [comment]
exclusive mode doesn't work for me that's why I installed HID, I tried turning off hide ps4, and im not using Dlnput only. 

after editing reg as follow:
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HidGuardian\Parameters\AffectedDevices:
HID\VID_054C&PID_09CC&REV_0100&MI_03
HID\VID_054C&PID_0BA0&MI_03
HID{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&05c4
HID{00001124-000

0-1000-8000-
[profile ps4.xml.txt](https://github.com/Ryochan7/DS4Windows/files/4422066/profile.ps4.xml.txt)
00805f9b34fb}_VID&0002054c_PID&09cc

now I can see it in st
[log.txt](https://github.com/Ryochan7/DS4Windows/files/4422060/log.txt)
eam but with double input.

**Comment by mika-n** [comment]
Try removing "HID{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&05c4" line from AffectedDevices sysreg entry (VID/PID 054C/05C4 is DS4v1 hardware vendor+product ID). The virtual dualshock4 VigEm gamepad happens to use this VID/PID code also, so that's what this needs to be removed from HidG sysreg entry. 

However, now when you see both physical and virtual gamepad in JOY.CPL gamepad configurator, it means that HidG is not hiding the physical gamepad. Did you disconnected and re-connected the gamepad when you modified AffectedDevices sysreg entry and re-launched DS4Windows app?

Those hardware identifiers in AffectedDevices should match the VID/PID of your gamepad. Hmm.... Based on the logfile you have DS4v2 gamepad, so it is should be VID_05C4/PID_09CC (usb) or HID[xxxx}_VID&002054c_PID&09cc. But maybe you have slightly different revision tag.

The "normal" version of DS4Windows app doesn't print out this VID/PID code, but the debug version prints out looots of details (include the VID/PID identifier). Download the debug zip, extract it to the same folder where you have DS4Windows and run the DS4WindowsDebug.exe app version. And the take a look at the logfile or post it here.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

Anyway. The idea is to list only the identifier of your DS4 physical gamepad in AffectedDevices and to remove all references to 054C/05C4 DS4v1 vidpid value. This way HidG won't hide the virtual DS4v1 gamepad while it hides the physical DS4v2 gamepad.

**Comment by Jassemm** [comment]
I did relaunch and, reconnected the controller. as well as deleting  "HID{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&05c4" from reg. still having both controllers there.

this is the debugged log file.
[log.txt](https://github.com/Ryochan7/DS4Windows/files/4423093/log.txt)

**Comment by mika-n** [comment]
Hmm... Everything seems to be OK.

Try removing the "&REV_0100&MI_03" tag from the first sysreg line. HidG does a simple "string comparison" with the gamepad identifier, so making sure that the beginning of the string matches is the crucial part. Or you could take a look at DeviceManager and see what it shows in properties.

How about if you test to connect the game over usb cable? Does it work? If it works then it would tell you that HidG is properly installed. In theory it is possible that some major WinOS update breaks HidG settings and it no longer hide gamepads. The easiest way to resolve this is to re-install HidG and let its installer to setup it again.

And when you launch DS4Windows app then check that Whitelisted sysreg entry (below HidGuardian settings). It should list the process ID of the DS4Windows executable (compare the Whitelisted  value with the TaskManager shown process ID).

**Comment by Jassemm** [comment]
ok, using cable did work, I can only see the virtual whether its xbox or ps4. 
however, wiressly, also after removing the "&REV_0100&MI_03". I still see both.
honestly, didn't know exactly where to look in device manager, but in HID I can see 2 game controller there.

**Comment by mika-n** [comment]
Hmm.. Maybe there is typo-error in "HID{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&09cc" line. Try using "HID\{00001124-etc....." value (note the backslash after HID keyword).

![DS4Win_DeviceManager](https://user-images.githubusercontent.com/35538525/78294712-80a06a80-7533-11ea-980a-c7625ee66173.png)

**Comment by Jassemm** [comment]
thank you, it did fix it I just copied it from there and vola no more double input. thank you !!
the string from device manager  was "HID\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&09cc"

thank you again!!

**Comment by mika-n** [comment]
Aah right. By default Github comment field drops the backslash char if it is in the front of bracket chars. The string needs to be set as "code" tag in the comment field to show it unaltered. Anyway. Great it works now.
