### ISSUE TITLE
fortnite sens issue

### ISSUE THREAD

**Issue by gambl3rkk** [Ryochan7/DS4Windows#1200]
hi, I use ds4 to map a keyboard bind on my controller when playing fortnite, but I have the feeling that when on, ds4 changes my sensitivities, and it's less smooth. I can't turn exclusive access on because it keeps give me an error, but the game is ok, I don't have double inputs. I have posted a photo of the default LS and RS settings of ds4 when creating a new profile, I am currently using them, should I turn all to zero?

![ds4](https://user-images.githubusercontent.com/61009745/78275095-753c4780-7511-11ea-829e-66670dc885ba.png)

**Comment by DoganM95** [comment]
I would try this:
Backup your current configuration (in the ds4windows installation folder, an .ini file perhaps), delete the one in the folder and start ds4windows again using factory settings, to see if it caused by your settings.

**Comment by gambl3rkk** [comment]
The ones that I posted are the default settings when creating a new profile. I did not modify anything, just the bind that I wanted to change. Should I still do that?
Could it be caused by the exclusive access? I use to play with hide ds4 off

**Comment by DoganM95** [comment]
Sure, give it a try and see if it fixes your problem

**Comment by gambl3rkk** [comment]
@DoganM95 I have checked and I did not find the file you told me, how can I do a removal and then a clean installation of ds4? I can't find it in the programs of my pc

**Comment by DoganM95** [comment]
The config file seems to be Profiles.xml

But just download the ds4windows installer and let it install into a folder on e.g. your desktop. Then exit any running ds4w instance (right click on the little icon and exit) and start the ds4windows.exe in your newly installed folder (on desktop).

This should give you a clean ds4w with stock settings and no profiles (temporarily, until you run your old ds4w again)

**Comment by mika-n** [comment]
You have zero deadzone. Anti-deadzone is set to "0.20".. Are you sure you need anti-deadzone? And you know the difference between deadzone and anti-deadzone values?
https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping

Deadzone is used to workaround "wobbling" LS/RS stick. It is hardly ever completely stable in hardware level or when you release the stick then it doesn't always return to the same absolute center position (LS/RS springs wear out, dust, etc...). Deadzone is used to avoid this unwanted LS/RS drifting when you have released the stick. 

Anti-deadzone is opposite thing. Some games have a built-in deadzone you cannot tweak (especially arcade racing games designed to be "steered" with a gamepad instead of with a steering wheel). Anti-deadzone can be used to eliminate that game specific built-in deadzone and this way making controls more sensitive. However, if the game doesn't have buit-in deadzone or you can tweak deadzone in a game to zero then you don't need anti-deadzone in DS4Windows profile.

If the game has custom settings to tweak deadzone and you want to use it then set DS4Windows deadzone to zero (not good idea to have deadzone tweaks both in game and in DS4Windows profile). However, many "console PC games" don't have any controller tweaks, so with those games DS4Windows comes to rescue.

On the other hand if you want to utilize DS4Windows deadzone/curve output/max range/etc tweaks then set all deadzone/curve settings to zero in game settings.
