### ISSUE TITLE
My controller keeps blinking in colors

### ISSUE THREAD

**Issue by keem85** [Ryochan7/DS4Windows#1202]
Strange thing is that the controller is working fine, but it's not solid color. It's blinking, and I find no way of turning the blinking off.. Also there are two controllers connected in DS4Windows, why is that? I only have one DS4 connected. Don't know where that other orphan one comes from?

**Comment by mika-n** [comment]
#1196 

And please provide more details as explained in the "Troubleshootin" guide. Logile content would show us the app version and gamepad type and potential warnings about input latency.

**Comment by keem85** [comment]
Windows 10 Pro 10.0.18362

Here's the log:
04/03/2020 15:01:00: DS4Windows version 2.0.14
04/03/2020 15:01:00: Starting...
04/03/2020 15:01:00: Connection to ViGEmBus 1.16.112.0 established
04/03/2020 15:01:00: Searching for controllers...
04/03/2020 15:01:00: Using Shared Mode
04/03/2020 15:01:00: Found Controller: 1C:66:6D:6B:9B:88 (BT) (DS4 v.2)
04/03/2020 15:01:00: Plugging in X360 Controller for input #1
04/03/2020 15:01:00: Controller 1 is using Profile "Default"
04/03/2020 15:01:00: Found Controller: 55:55:AA:D8:17:E4 (USB) (DS4 v.1)
04/03/2020 15:01:00: Plugging in X360 Controller for input #2
04/03/2020 15:01:00: Controller 2 is not using a profile
04/03/2020 15:01:00: UDP server listening on address 127.0.0.1 port 26760

**Comment by mika-n** [comment]
Hmm.... There seems to be one gamepad with DS4v2 (the model released with SlimPS4) over bluetooth (BT) and other one as DS4v1 (the original revision 1) over usb connection. Strange.

Have you connected/paired the gamepad over BT and at the same time you are charging in over usb cable from the PC? How do you connect the gamepad? Is the lightbar already on when you plug in usb cable (ie. you have woken up the DS4 gamepad and it has been connected to PC over BT already)?

Try shutting down the gamepad (keep holding PS button for about 10 secs until the lightbar goes off). Then plug in the gamepad over usb cable without touching the PS button at all. Do you then get just one gamepad in the logfile?

Or if you use BT and the gamepad needs charging then try charging it from a wall plug and not from the same PC. Or try to charge it with phone usb cable because I have several phone cables here which don't carry over DS4 data signals but can charge the gamepad.
