### ISSUE TITLE
Constant jitters not present in J2K driver

### ISSUE THREAD

**Issue by humbas5** [Ryochan7/DS4Windows#1205]
Hey! I've just bought a new DS4v2 controller to it's probably not "worn out". When I install drivers and try doing everything, it seems to be hypersensitive resulting in constant jitters in games. It says I've got 2 controllers in control panel. One is probably installed by windows and one is driver from here. While the windows one works properly with only micro jitters (I think they're natural), the other one constantly jitters so far and seems to be unable to even hit the center. Here it is:
![obraz](https://user-images.githubusercontent.com/63243158/78563454-44af2300-781b-11ea-88a7-eb9392af4d55.png)

What should I do with it?

**Comment by humbas5** [comment]
> 
> 
> "New" DS4 v2 controllers are more and more unreliable. The analog sticks of my brand new Berry Blue model were busted in 3 weeks. That's Sony for you.
> 
> There are several things that you can check. You see two controllers because there's the physical one (the DS4) and the virtual one (the emulated X360). The point is to hide the physical one, which conflicts with the emulated one. Otherwise you'll get double inputs in many games/apps, which can explain the jittering. You must either activate the exclusive mode ("Hide DS4") or install HIDGuardian (search the wiki).
> 
> The other thing you can try is to set some minimum dead zone for your analog axes. By default DS4Windows use zero but that will most likely generate micro-drifting. Try 0.05 for a start.

Thanks for your advice. I hid DS4 controller and now the only one I've got is DS4Windows one. Though it seems to be the problem - the driver just act like crazy, here's the video. What could I do about it? Is it a common problem?
https://photos.app.goo.gl/vKbYmWfjAYBy4wey6

**Comment by mika-n** [comment]
Explanation of deadzone and anti-deadzone DS4Windows profile tweaks:
https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping
https://github.com/Ryochan7/DS4Windows/issues/1200#issuecomment-608386980

So, maybe the profile you have has an anti-deadzone defined even when you don't need it? Try setting zero to LS/RS anti-deadzone and then tweak LS/RS deadzone to eliminate micro drifting (caused by LS/RS hardware as explained in the above linked pages). Or if a game has its own deadzone tweaking then set DS4Windows deadzone to zero or vice-versa, but don't set deadzone both in game settings and in DS4Windows profile settings.
 
Explanation of "double input / double controller" issue.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by humbas5** [comment]
Needed to Hide DS4 controller and actually delete my profile (probably from J2K version) and make a new one. Thanks a lot! Works fine.
