### ISSUE TITLE
Can't connect one of my controller

### ISSUE THREAD

**Issue by nosfay** [Ryochan7/DS4Windows#1209]
My controller is paired with windows 10.
I can test it with joy.cpl.
I can test it with HTML test page from DS4Windows.

But when I start DS4windows, nothing happened.

No error in logs:

```
2020-04-08 18:21:58.2587|INFO|Starting...

2020-04-08 18:21:58.2587|INFO|Connection to ViGEmBus 1.16.112.0 established

2020-04-08 18:21:58.2587|INFO|Searching for controllers...

2020-04-08 18:21:58.2587|INFO|Using Exclusive Mode

2020-04-08 18:22:03.5295|INFO|UDP server listening on address 127.0.0.1 port 26760

```

I've closed Steam just in case.

I have 2 other bluetooth controllers without issue.

Edit : 
I've run debug version, here is the log:

```
2020-04-08 18:34:19.9408|INFO|Starting...

2020-04-08 18:34:19.9408|INFO|Connection to ViGEmBus 1.16.112.0 established

2020-04-08 18:34:19.9408|INFO|Searching for controllers...

2020-04-08 18:34:19.9408|INFO|Using Exclusive Mode

2020-04-08 18:34:19.9408|INFO|DEBUG: EnumerateDS4. HID#1 Path=\\?\hid#vid_0513&pid_0318&mi_01&col03#8&9cf7f75&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Contr?leur syst?me HID  VID=0x0513  PID=0x0318  Usage=0x80  Version=0x100

2020-04-08 18:34:19.9408|INFO|DEBUG: EnumerateDS4. HID#2 Path=\\?\hid#vid_0513&pid_0318&mi_00#8&1a07be4d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd  Description=P?riph?rique clavier PIH  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0

2020-04-08 18:34:19.9408|INFO|DEBUG: EnumerateDS4. HID#3 Path=\\?\hid#vid_0513&pid_0318&mi_01&col01#8&9cf7f75&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=Souris HID  VID=0x0000  PID=0x0000  Usage=0x0  Version=0x0

2020-04-08 18:34:19.9408|INFO|DEBUG: EnumerateDS4. HID#4 Path=\\?\hid#vid_0513&pid_0318&mi_01&col02#8&9cf7f75&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=P?riph?rique de contr?le consommateur conforme aux P?riph?riques d'interface utilisateur (HID)  VID=0x0513  PID=0x0318  Usage=0x1  Version=0x100

2020-04-08 18:34:19.9408|INFO|DEBUG: findControllers. Found 0 possible devices

2020-04-08 18:34:19.9408|INFO|UDP server listening on address 127.0.0.1 port 26760


```

Edit2:

Controller HID: (same as my other controllers)
```
HID\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&05c4
HID\{00001124-0000-1000-8000-00805f9b34fb}_LOCALMFG&000a
HID\VID_054C&UP:0001_U:0005
```
I've found some different things if it can helps :
- Path to the device instance
- Container ID
- Object name of the physical device
- Bus number

**Comment by nosfay** [comment]
[ds4windows BT ERROR.txt](https://github.com/Ryochan7/DS4Windows/files/4455249/ds4windows.BT.ERROR.txt)

So USB mode is working, and I've now some errors with BT, see the attached log.

UPDATE:

I can get it worked by setting in debug version `Debug_SendRumbleLightbarData` to `false` like said in this issue https://github.com/Ryochan7/DS4Windows/issues/1143

Can you merge issues by the way please ?

**Comment by mika-n** [comment]
Jep. The "Debug_SendRumbleLightbarData=false" debug option helps in scenarios where the gamepad refuses to receive rumble and lightbar messages (ie. PC sends data to the gamepad over usb or BT communication line).
`2020-04-09 11:13:50.6462|INFO|DEBUG: sendOutputReport. ERROR. writeOutput failed. Force quiting output thread. LastErrorCode=170
`
But why writeData fails? Are you sure you have a genuine Sony DS4 (revision1) gameapd? There has been cases where a fake copy doesn't work exactly like the original gamepad.  Or faulty usb cable may cause problems. 

Have you tried the same gamepad over bluetooth in PC?

The same gamepad may seem to work just fine in PS4 console over usb cable, but PS4 uses usb cable only for pairing and charging. PS4 console reads and writes data over BT even when you have connected the gamepad over usb. In PC all communication goes over USB if the cable is connected to PC.


> It works too if i put these settings:
> key="Debug_SendRumbleLightbarData" value="true"
> key="Debug_SendRumbleLightbarDataType" value="0"
> key="Debug_SendRumbleLightbarDataAPI" value="1"

Hmmmmm... That's weird because the above shown debug values would make exactly the same thing as default settings in USB mode.

**Comment by nosfay** [comment]
I've missed a lot of informations, sorry!

There is 2 separated log.

It's not a genuine controller.

[ds4windows USB OK.txt](https://github.com/Ryochan7/DS4Windows/files/4456149/ds4windows.USB.OK.txt)
[ds4windows BT NOK.txt](https://github.com/Ryochan7/DS4Windows/files/4456150/ds4windows.BT.NOK.txt)

**Comment by mika-n** [comment]
> But maybe you could handle this and disable lightbar and rumble when controller face this error ? So it's still usable.

Yes. It seems that there are more and more copies (legit or fake) of DS4 "compatible" gamepads where things work just fine over usb, but BT has problems in PC.
 
I think there could be a profile option (Others tab page) where user could enable/disable "write lightbar and rumble data" feature because sometimes it might also help to tackle with BT lag issues in cases where a game doesn't need lightbar and rumble features.

At the moment DS4Windows app uses the "write failed" status to detect when a BT connected gamepad is disconnected (the app assumes that the gamepad is gone if it no longer can receive data). Disabling writeData or ignoring write failure events need a bit of thought what implications it would have to "gamepad disconnected" detection.

**Comment by nosfay** [comment]
Hello, I've tried last version, and now the controller can connect but instantly disconnect because of low battery detected (but it's fully charged). I think you could disable too battery level like ligthbar and rumble. 
USB connection is fine.

**Comment by mika-n** [comment]
@nosfay  You might wanna try the debug version because it allows additional tweaks. For example the debug config file has an option to disable battery reading value and this way the app always reports "full battery".
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

Download the "DeviceDetect" zip file linked in the web page and extract it to the existing DS4Windows app folder. 

- Modify DS4WindowsDebug.exe.config file in Notepad and set "Debug_ReadBatteryData" option to false value.
- Run DS4WindowsDebug.exe app (it is the same as the "normal" DS4Windows but it has those additional tweaks and dumps lots of additional debug messages to logfile and Logs tab page in DS4Windows GUI).
- Test if this option helps to tackle the issue.
- Provide the latest debug logfile (rename "%APPDATA%\DS4Windows\Logs\ file with TXT extension and attach drag-and-drop to a comment field here).

 If it works then maybe there should be similar option in the official version also (there are lots of other optional tweaks in the debug config file).

**Comment by nosfay** [comment]
I'm not sure it's a battery issue. 
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4900094/ds4windows_log.txt)

**Comment by mika-n** [comment]
Doesn't seem to be battery reading issue, but general inputReport (ie. PC reads data packets coming from DS4 pad) issue.

`2020-07-10 02:12:46.9142|INFO|DEBUG: performDs4Input. WARNING. 20:19:09:19:E8:DE crc32 check of BT input packet failed. btInputReport type0=1  type2=128
`
This error tells us that the incoming data packet in BT is not in expected DS4 format. Some fake DS4 revision1 gamepads have this issue.

But, there is one more thing you could try with the debug version. You could try to force the debug version to process those "potentially invalid" data packets and see how it goes.

Set "Debug_SendRumbleLightbarDataType" option in DS4WindowsDebug.exe.config file to value "1". It if doesn't help the value "2".

And the same with "Debug_GyroCalibrationType" option. Try values 1 and 2.

Anyway. These symptoms in BT are classical examples of fake DS4 revision1 gamepad issues. It might be possible to get it working, but someone with such a fake gamepad should debug it in hardware level to see how it communicates in PC. It may be a bit too difficult to try to guess from here without seeing and debugging incoming and outgoing HID data packets in "live".
