### ISSUE TITLE
No Controllers Connected in ds4windows

### ISSUE THREAD

**Issue by ghost** [Ryochan7/DS4Windows#1218]
Hi, i'm from Argentina and I have a problem with my DS4Windows, it doesn't recognize my Noga Gamepad (here in my country it's the most popular brand).
I would like to know if there is any option/add to make it work, or if there's an alternative step (i tried everything included downloading Ds4WindowsDebug.
At the moment the gamepad is only detected in the control panel, but in the first tab it appears "No Controllers Connected (max 4).

Name of the gamepad: Noga NG-3093
https://noga.com.ar/index.php/drivers/joysticks/driver-joystick-ng-3093

I would really appretiate your help in these quarantine times because it's really difficult to get out home for the next months.

My apologies for my bad english, and thanks in advance!

**Comment by mika-n** [comment]
Please take a look at the pinned "Read this before posting a new issue ticket" instructions. There is a link to a special debug version which generates a lot more detailed logfile from a gamepad connection events. Run that app version and provide the logfile here as an attachment text.

Anyway. You said you download the debug version, so please attach the debug logfile here. 
When I googled for "Noga NG-3093" it said that it is PS2/PS3 gamepad, not a PS4 compatible. There were other Noga NG-4xxx series with PS4 compatibility. This app doesn't work with PS3 gamepads if those are not published as directInput gamepads on WinOS and use the same HID message protocol as DS4 gamepad.

**Comment by Mclaud14** [comment]
Thanks for your answer! The debug version didn't even open in my PC. Finally I could solve the problem installing x360ce alpha 4.1 (the only version that worked), and then HID guardian (adding my hardware ID on the HKEY registry). So now i'm playing games like Forza Horizon 4 with my PS3  Noga Controller. Maybe this method could be useful also with DS4 on PS3 controllers for further updates.

Sorry for my bad english and thanks again for answering!

**Comment by mika-n** [comment]
The current code branch of DS4Windows app probably won't see PS3 controller support because the background code derived all the way to Jay2Kings version doesn't make it easy to support multiple controller types (=non DS4 compatible). Maybe some future version supports PS3 controllers because at some point there will be need to support both PS4 and PS5 gamepads. Then the whole backend code needs a major overhaul anyway.

The debug version doesn't work on its own. It needs to be copied to the same folder with the latest official DS4Windows installation (V2.0.14). The debug version shared certain libraries with the official app version.
