### ISSUE TITLE
Taskbar right click menu error.

### ISSUE THREAD

**Issue by lechuck01** [Ryochan7/DS4Windows#122]
I've got 1.4.94 installed at the moment and what's happening is when I right click on the taskbar icon, where it shows start/stop, it shows stop when it should show start instead. Here's a picture so you know what I mean. Happens on 1.4.95 as well.
![menu error1](https://user-images.githubusercontent.com/30793466/31057603-37e6cf72-a6dd-11e7-8e14-6afaf11e14b7.jpg)

**Comment by Ryochan7** [comment]
The routine for stopping and starting the service has changed fairly recently. The context menu text was being updated before the actual routine was being run so the old text was being used for that context menu instead of the proper updated text. This issue has now been fixed. Thank you for bringing up this issue.
