### ISSUE TITLE
Dualshock 4 no funciona cuando se usa DS4Windows_2.0.16_x64 en GTA V 

### ISSUE THREAD

**Issue by juanillo9791** [Ryochan7/DS4Windows#1221]
hola muy buenas ,Intentare ser lo mas preciso posible . Solo me pasa con el GTA V el unico boton q funciona es el tactil , en el cual solo golpea .

HTML5 Gamepad Tester Funciona correctamente con y sin el programa DS4 

**captura antes de activar el DS4**

https://ibb.co/SNfPyCG

**captura despues de activar el DS4**

https://ibb.co/6Pc7NWx

**Varias capturas del DS4**

https://ibb.co/zx3pdF5
https://ibb.co/Xyqbj64
https://ibb.co/CtBXfLy
https://ibb.co/Gf6RcNX

ruego disculpen si es post no es sufiente informativo para poder ayudarme.

**Comment by juanillo9791** [comment]
me podrian ayudar please

**Comment by mika-n** [comment]
Any changes to post in English (or in Finnish or Swedish :)  because looks like Spanish speaking people are minority here.

**Comment by Ryochan7** [comment]
From what I can understand, it looks like DS4Windows not getting exclusive access to the DS4 would likely be a problem. GTA V can read the DS4 as a DirectInput controller so there would probably be input conflicts in game between the virtual Xbox 360 and real DS4 controller.

I guess I should actually buy GTA V next time it goes on sale. Enough people ask questions about it.

I took about 2 years of Spanish in high school but I have forgotten almost everything. My Japanese isn't much better. Never actively communicated in a different language so it is easy to forget.

**Comment by Ryochan7** [comment]
You might want to try HidGuardian to resolve the exclusive access problem.

https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer

**Comment by Ryochan7** [comment]
Also, I guess I probably have to mention it since money is a factor and people might bring it up. I am fairly sure I won't be getting a Corona-chan relief check. Have not been employed since late 2017.

**Comment by Ryusennin** [comment]
Last time I checked (a few weeks ago), HidGuardian still worked nicely with GTA 5.

**Comment by Ryochan7** [comment]
I didn't start actively using HidGuardian until I started my recent batch of Touchmote experiments; specifically playing Star Wars Episode 1 Racer with a Wiimote wheel shell. My use case depends on a custom built version though.

https://github.com/Ryochan7/HidGuardian/tree/gottagofast

**Comment by Yohoki** [comment]
He says that the controller doesn't work when in GTA5. The only button that works is the touchpad, which Punches/fires.

His issue isn't the HIDGuardian or anything. He hasn't set up a profile for GTA5. It's simple, but all the instructions (afaik) are in english. It's not a program fault, but user error. :P

@juanillo9791
Ingles:
Sorry, My spanish is pretty bad, since I don't speak it every day, so I'll write in English and Spanish. :P
You need to set DS4Win to know what the buttons should be. Try using default profile and it will make your Playstation controller act like an XBox controller. Go to the "Automatic Profiles" tab, Press "Add Profiles" and "Browse for Program". Select your game's EXE file and hit "Open". Then, with GTAV selected, go to "Controller 1" and select "Default" and hit save.

Espanol:
Lo sentos, mi espanol es terrible hoy en dia. Entonces, voy a hablar en ingles y espanol :P
Necessitas dice a DS4Win que perfile te queres. Para GTAV, creo que "Defualt" es la una que queres. Va a mira XBox botones, pero no se si Playstation botones esta en la programa. En la area "Perfiles Automaticos" toca "Anadir Programs" y "Navegar en Oltros Programas". Poner la EXE de GTAV. Antes, en la area "Perfiles Automaticos", toca GTAV y a la area "Mando 1", poner "Default" y  Guardar.

**Comment by Ryochan7** [comment]
Update: I want to be at least semi-transparent. I actually got some Corona-chan bucks today. I will buy GTA V and install it today. Now I will be able to test this out directly.

**Comment by Ryochan7** [comment]
Tested it a bit. Based on what I have seen so far, DS4Windows obtaining Exclusive access to the DS4 is mandatory to avoid issues. The game does not support support for the v.2 but it does support reading the v.1 controller wired. Even when the v.2 is connected and a virtual Xbox 360 controller is present, input conflicts will occur as it seems like the game tries to interpret DirectInput even when using non-supported controllers. Virtual DS4 output works in game but the game still shows Xbox 360 button prompts anyway. Not much of a point of emulating a DS4 in GTA 5.

My initial hypothesis was correct. Been wanting to try out GTA 5 for a long time anyway so buying it will likely be worth it. Based on the VRAM display in the settings, the game pretty much maxes out the 1 GB of VRAM that my GPU has. The settings are about as low as the game will allow except for maybe bumping down the resolution. Frame rate was very good through the two intro missions.

**Comment by Yohoki** [comment]
@juanillo9791
Ryochan dice que necessitas poner la optione "Exclusive Mode". En GTAV es posible para usar una controlador de Playstation (v1) o XBox, pero no puedes usar los controlador Playstation nuevos. Si tienes un controlador con una luz en el tactil, es una nuevo (V2). Con la opción "Exclusive Mode", puedes usar su controlador como un controlador de XBox. Sin "Exclusive Mode", GTAV nota una controlador de v1 y XBox, o nota v2 y XBox. 2 controladores = no bueno. :(

Para usar "Exclusive Mode" salir todos progamas que usar una controlador... Juegos, Nvidia Programas (como GeForce Ecperience). Antes, en el "Regitro" de DS4Windows, Vaciar. En la "Opciónes", marka la opción "Hide DS4 Controller". Otra ves en el "Regitro", si hay texto de color rojo, hay mas programas usando un controlador. Si no hay text de color rojo, estas listo para GTAV.

**Comment by mika-n** [comment]
Here is a link to describe the background of "Hide DS4 Controller or HidGuardian" options (alternative ways to do the same) and why some games need it.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
