### ISSUE TITLE
R1/L1 spam

### ISSUE THREAD

**Issue by susiman31** [Ryochan7/DS4Windows#1231]
When i press R1 or L1 once, it often presses twice. For example when i want to scroll in-game and press R1 on the first page, it scrolls to the 2nd page. Same porblem occurs when playing and using R1

**Comment by Ryochan7** [comment]
Not sure if exclusive mode problem or KB+M issue. Are you using an Xbox 360 profile?

**Comment by susiman31** [comment]
I'm using a DS4. Same thing happens when scrolling with the arrows

**Comment by susiman31** [comment]
I managed to fix it by recording macros one by one but ingame it shows that i have 2 controllers connected and it makes me use both of these

**Comment by mika-n** [comment]
Could be that the game programmers have been lazy and the game suffers from the "double input" issue if there are both virtual and physical gamepad controllers visible. See the following doc pages:
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#double-input-problem-in-games-game-does-all-sort-of-weird-things-when-i-press-a-button-second-player-drops-in-cannot-navigate-in-menus-because-focus-moves-two-lines-when-i-press-a-key-just-once-etc
https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping
