### ISSUE TITLE
Left Stick behaviour consistency issue

### ISSUE THREAD

**Issue by Eiion** [Ryochan7/DS4Windows#1238]
Some time ago an update seemed to have changed something in how the left stick gets read out. 
But before I go into detail, here's some background: I'm using the DS4 controller with DS4Windows to play Call of Duty Modern Warfare (2019) wireless. Up until said update (maby a week or two ago), everything worked perfectly fine. (Thanks!)

After the update I'm having issues running in a straight line forward. It's a very rapid (and naturally very annoying) stuttering mess between walking and running. It's even worse when using tactical sprint.
Because of that I've changed the game's "Automatic Sprint" settings to "Automatic Tactical Sprint". I've tried "Automatic Sprint" but the previously mentioned setting seems to work best out of the three options (with the first one being "Disabled" and none of them working as what's considered "good" anymore).

Now here's what I have to do to counter this: Over time during playing things seem to shift from where pushing the left stick straight forward to run works, then I have to move left forward (up to 45° to the left) or right forward (also up to 45° - to the right though) to still keep running in a straight line, all the while trying to avoid the stuttering (the rapid change between walking and running) from happening. It's really annoying.
I'd make a video showing what's going on but I don't know how I would go about that or where to upload it to. I hope my description is good enough though to understand what I'm saying although English only being a second language to me.

Interestingly, while using the controller in wired mode, this is not an issue which is why I came to the conclusion that it's an issue with DS4Windows and not my controller.

**Comment by Ryusennin** [comment]
I fail to understand why it would drift in Bluetooth and not in USB.

If you can, test on a PS4 first to check if the pad is actually suffering from analog drift. It's a common defect on DualShock 4 and happens even to new controllers.

**Comment by Eiion** [comment]
I guess you misunderstood. The stick is not drifting - I'm not moving in any direction without actually pushing the stick.

**Comment by deadair3210** [comment]
Sounds like a issue with the analog stick, would probably be easy to spot the issue if you can find the analog values, don't remember if DS4Windows shows them anywhere

**Comment by Eiion** [comment]
You mean the controller readings? It can be found in "profile" - "settings":
![Screenshot](https://user-images.githubusercontent.com/18130829/80018271-10538c00-84d6-11ea-8078-3c5444a5e18a.jpg)
That's what it looks like for me. While numbers aren't dead on point they vary only by 1. (e.g. RX(I) is flickering between 127 and 128). I ascribe that to read out rounding. So I highly doubt there's any issues with the controller itself.

**Comment by deadair3210** [comment]
Well if it's showing correctly in DS4Windows, it's likely a issue with either the game/windows/another program messing with the controller inputs

**Comment by Eiion** [comment]
Or it's how DS4Windows interprets the data. I don't see how it's more likely the game/windows/another program when it all started some time ago after an update.

I've checked the controller with html5gamepad and noticed that when moving the stick fully forward and then (still moved to its full way) to the left and the right, the pointer doesn't follow the line. Sure, I expect some deviation but not that much: The point jumps back and forth between 1 and 0.75 on axis 1. The right stick doesn't do that.
This might be actually enough to cause the game to go rapidly between walk/run/tactical run. Of course I can't tell what the tolerances are for the game.

My suggestion would be to implement some smoothing for the read out data.

**Comment by mika-n** [comment]
It is normal that there are slight wobbling when you move the stick to NW/NE/SE/SW "compass" directions while the stick is fully extended. But is "too much wobbling" because of hardware issue or DS4Windows app or profile settings? 

One way to find out would be if you would download older releases one by one and test if the "too much wobbling" really is fixed in certain older version. This would give more hints to developers to see if some change after that version might have something to do with the issue. You can download and unzip the old ZIP package to a new folder and run DS4Windows from there. It will re-use all existing config files.
https://github.com/Ryochan7/DS4Windows/releases

Anyway. You could use "Output Curve - Custom" setting to fine tune how certain axis is smoothed or to enable "Square Stick" option and try different 0..5 "roundess" values.
https://github.com/Ryochan7/DS4Windows/issues/1168

**Comment by Eiion** [comment]
I've wanted to try older versions but after getting a new Logitech mouse yesterday their "G Hub" software seems to have the effect that a controller connected via ds4windows isn't recognized in game anymore.
It appears that G Hub's game recognition ability (though even not using game profiles) prohibits the ds4windows from emulating a controller that's usable in game. I'll have to figure out what's going on with that first.

As for the other options in settings, unfortunately I have no idea what they do and how they are used. I'll take your link as a starting point to find out. Thanks!

**Comment by CaptainHalflife** [comment]
Hi, i got the same problem.it only occur with ds4 window by @Ryochan7 but not with the original ds4 window.When i walk forward and and stop sometimes it continue to move .

**Comment by mika-n** [comment]
@CaptainHalflife  This has been mentioned several times in the documentations and older tickets.  The original Jay2Kings/DS4Windows had a built-in default deadzone when a profile was set to use "zero deadzone" value. In other words it was not even possible to use zero deadzone in Jay2Kings version even when sometimes it is desired (=for example a racing game has its own deadzone tweaking settings, so having "double deadzone layer" would just cause loose of precision).

This Ryochan/DS4Windows doesn't have "hidden implicit" deadzone because sometimes you may actually want to use zero deadzone. So, if a profile has zero deadzone then it zero. If you need to have some deadzone then a profile needs to set it.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping

**Comment by CaptainHalflife** [comment]
Ok thanks for the answer and sorry for posting an useless comment .
Keep up with this awesome program.

**Comment by Eiion** [comment]
For those wondering, these are the settings that seemed to (mostly) solve my issues with Call of Duty Modern Warfare (the only game I'm currently using the controller via DS4Windows for - so I don't know about other games). Some settings I've changed, others I didn't touch:
![Screenshot](https://user-images.githubusercontent.com/18130829/82346439-c25b7680-99f6-11ea-8fec-5aea11955cc4.jpg)

**Comment by mika-n** [comment]
So left stick (LS) drift was solved by using zero deadzone, but 1.20 sensitivity and SquareStick 0.0 values?  That's weird.  I'm very surprised to hear that deadzone alone didn't solve the drift. 

Hmmm.... This make me wonder if there is a bug in DS4Windows with certain combination of options. What kind of options you used to have with LS?

**Comment by Eiion** [comment]
Again, that was not a drift issue - the signal was not drifting as what we know how drifting typicall works.
These settings are what turned out to work the best for me. Before that I've used standard settings without any adjustments.
