### ISSUE TITLE
Macro not saving properly and not saving Repeat While Held (2.0.16)

### ISSUE THREAD

**Issue by Perseonn** [Ryochan7/DS4Windows#1246]
Hello!

I have issues with macro on 2.0.16 (previously using 2.0.7, but updated it since I thought it was fixed):

**Macro not saving properly:**
1. Pick any button on Controls Tab, in my case L2
2. Program opens "Select action for L2" window
2. Click on Shift Modifier
3. Select Shift Trigger, in this case, L1
4. Click Record a Macro
5. Click Record
6. Press B key on keyboard twice as Macro
7. Click Stop
8. Click Save

The program closes the  "Select action for L2" window, but doesn't save both the shift config and macro for L2. This has a work around by selecting any key after picking a shift trigger, then redo the steps to record macro. Only then the macro is saved.

**Macro not saving Repeat While Held:**
1. Follow the above step to set up a macro by using the workaround
2. Select "Repeat While Held" after recording mac

ro.
3. Click Save.

The program closes the  "Select action for L2" window, but doesn't save "Repeat While Held" configuration. Odd thing is, I used to have a repeat while held options on L1+Circle (outputs repeat E on keyboard), but after opening the Macro option on Circle and clicking Cancel, it reverts to "Play Once" and cannot be set as "Repeat While Held" anymore.

Other info:
Using genuine PS4 Controller (one bundled with the console)
Exclusive mode is active.
Repeat result is tested on Notepad++.
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4525779/ds4windows_log.txt)

**Comment by fchud** [comment]
same issue.

just tested on every x64 version down to **1.7.28**.

in every version after 1.7.28 recording a macro for a button with Shift Modifier does not work.
after recording and saving nothing happens.
recording a macro without a Shift Modifier seems to work just fine.

one other thing.
so, i created a macro in 1.7.28 for a repeated X(cross) tapping while it is held with Shift Modifier R2.
copied the _ShiftControl_ xml section into the current version of my profile's xml and everything works fine.
if you do not touch it afterwards, that is. because when i tick Shift Modifier, open the macro and just Save it even without modifying - the "Repeat While Held" does not save. but instead - it goes to the "Regular" macro section. so if you open macro for a Regular option "Repeat While Held" will be selected.


although, i do remember creating and assigning macros on different buttons with different Shift Modifiers not that long ago - probably 2-3 moths ago. is it possible that some windows update messed something up?

win 10 ent ltsc x64, hidguardian, genuine ds4.

**Comment by mika-n** [comment]
Jep. Relating to the second #2 bug about "repeat while hold" status. There was a bug when repeatWhileHold and MacroType settings were saved for shiftModifier keys. The code accidentally saved the status of these attributes into regular keyType attribute instead of into shiftKeyType attribute. This is now fixed in the next upcoming release.
 
The first #1 issue (record a macro is not saved unless some keyboard key selected before closing the key binding screen) is still under investigation. But luckily there is the weird/intuitive workaround for that issue as you described. Thx for reporting the issue.
