### ISSUE TITLE
Win10 Creators Build - HID-compliant game controller disable

### ISSUE THREAD

**Issue by pralima87** [Ryochan7/DS4Windows#125]
Just a issue that might be related to the Win10 Creators update.
Sometimes after a restart the HID-compliant game controller drivers will be disable causing the controller to stop working.

The work around is to enable the drivers in the Device Manager

**Comment by Ryochan7** [comment]
DS4Windows has had those types of problems for a long time. The problem has mainly been due to multiple controller scans happening at once. Most of those problems have been fixed but one issue with DInput mode has recently been discovered.

The only way to truly avoid these problems is to not use exclusive mode. With the current approach being used to enable exclusive mode, I am not sure there is a way to completely get rid of this issue.
