### ISSUE TITLE
Quadratic function producing invalid output

### ISSUE THREAD

**Issue by Swoogan** [Ryochan7/DS4Windows#1251]
When the quadratic function is selected for output curve, it will output a Y of 0 for very low values of X > 128.

I have my RS set to Quadratic. If I press lightly to the right, RX input is 131 and RY input is 128. RX output is correctly transformed to 144, but RY is incorrectly transformed to 0.

I am able to work around this by putting in the bezier settings for quadratic (namely 0.55, 0.09, 0.68, 0.53).

**Comment by Ryochan7** [comment]
Enhanced Precision was the only curve that was not affected by this problem. Unfortunately for everyone else, that was the only output curve type that was tested; tested the initial change while playing Fallout: New Vegas. This problem is already fixed in the code but there has been no public release with the fix. Been a bit all over the place with recent tests. For the most part, version 2.1 is ready for release provided that I do not edit the Changelog JSON file schema in any way.

https://github.com/Ryochan7/DS4Windows/commit/31aa0a1aac5066061b3ed82e95d5b33b7bb3a4c0
