### ISSUE TITLE
Unexpected axis control output mapping

### ISSUE THREAD

**Issue by Swoogan** [Ryochan7/DS4Windows#1260]
There appears to be an issue with the equation that maps axis controls. Under some condition the output actually inverts compared to what is expected. Other times there is a minimum floor of the output that removes fine precision from the input.

For the first case, 

1. setup the right analog stick as a mouse movements
1. set the mouse sensitivity to 1 (48 pps)

Notice that when you move the stick the mouse cursor will move fast at first and slow down as you increase the input on the stick. The equation's output is inversely proportional to the input.

In most other cases there is a floor on the movement approximately equal to `MOUSESTICKOFFSET`. This means that it's basically impossible to move one pixel at a time, even at very low sensitivities. At higher sensitivities it becomes impossible to move less that 40 or more pixels at a time. It also means that when moving in a horizontal or vertical line, even the slightest input on the other axis will cause the cursor to sheer off at a steep angle.

The equation:

    value = ((speed * MOUSESPEEDFACTOR * (timeElapsed * 0.001)) - tempMouseOffsetX) * diff + tempMouseOffsetX;

[An example](https://github.com/Ryochan7/DS4Windows/blob/jay/DS4Windows/DS4Control/Mapping.cs#L2978)

The commented line below actually works:

    //value = diff * MOUSESPEEDFACTOR * (timeElapsed * 0.001) * speed;

I rewrote it as:

    var timeDelta = timeElapsed * 0.001;
    var mouseVelocty = speed * MOUSESPEEDFACTOR;
    value = mouseVelocty * timeDelta * diff;

I believe that these issues might be related

* https://github.com/Ryochan7/DS4Windows/issues/1238
* https://github.com/Ryochan7/DS4Windows/issues/1200

**Comment by Ryochan7** [comment]
Not sure why the output coordinate would get inverted. I will look to see if I am duplicate that on my end.

As for the speed floor, that is intentional as I find it is much easier to control the aim (even on the low end) with a higher initial mouse offset speed. I have thought about possibly making that a user configurable setting rather than a fixed constant. It has not happened mainly because of paranoia regarding performance concerns.

Also, you might want to lower the dead zone set on RS. When I bind RS to mouse, I go to the extreme and use around 0.03. There is small mouse drift that can be compensated but there is much greater control when using a lower dead zone. Using a setting around 0.04 - 0.06 for the RS dead zone would probably be doable with almost no chance of mouse drift.

**Comment by Ryochan7** [comment]
Playing with this now. One of those issue probably would have dealt with output curves other than Linear that was fixed in version 2.1.0. I have encountered the problem regarding the way the speed floor is implemented. Especially with using such a low setting of 1, the mouse speed floor is actually faster than the per poll speed of the mouse cursor. That would help explain both why the cursor accelerates faster at the low end and potential inversion of the output.

I am going to have to change the logic used for the mouse floor. The speed floor for the sticks should probably be set as the minimum speed that the cursor will move per second. Now I just need to find a value that I like before I commit anything.

**Comment by Ryochan7** [comment]
Will probably tweak this a bit more. For now, the offset is specified as a percentage of the full mouse speed. It can thought of as another anti-dead zone.

**Comment by Swoogan** [comment]
Please do not add the offset without a way to turn it off by the user. I honestly don't believe it should be included at all, but if you insist, it should default to zero. It's presence makes this program completely unusable for any situation where you need pixel level control. 

For your needs, I believe you could simply tune the output curve to have a higher initial output. For example, setting your curve to `0.00, 0.23, 0.00, 0.24` will have a similar effect without subjecting everyone else to the loss of precision.

In practice the offset moves the whole curve up and remaps all the lower input to a higher value. It's like you're taking a vehicle accelerator that goes from 0-100 in 100 increments and tuning it to 10-100 over 100 increments. There's now no way to smoothly decelerate; you will just come to a sudden stop when you drop below 10. Imagine trying to park with that, or match the speed of another vehicle that's traveling at 9. It is impossible without changing the sensitivity, but that simply lowers the entire range, which removes the top-end speed. (eg: 10-100 becomes 5-50, but now I can't go faster than 50).

You can see this in practice. For example, with the default settings it's impossible to select a single character of 12px font. It's also impossible to target a small object in any game with the sensitivity turned up. If you don't luck out and land exactly on the object, you will jump passed it when you try to correct. If you attempt to correct in the other direction, you will jump passed it going the other way. I simply cannot imagine a scenario where this makes it "easier to control the aim."

**Comment by Ryochan7** [comment]
Using the fixed routine, it would be more like using the range 1.28 - 100 rather than 0 - 100. Without the offset, you are pretty much fighting two dead zones. You have to overcompensate to aim and that would cause more missing of the target. The current mouse offset could probably be lowered but I had liked the looser aim that it provided for some games (Fallout: New Vegas). Touchpad mouse and Gyro mouse use a similar mouse offset but it is based on a relative per gamepad poll. Also, it is quite a bit lower than the one used for the sticks.

**Comment by Swoogan** [comment]
I don't understand what you mean "fighting two dead zones," or "overcompensate to aim." I'm doing immensely better without the offset than I was with the original one.

How does removing precision from the input increase the precision of the output?

**Comment by Swoogan** [comment]
I tried the new code and it is much, much better now. I still find it more twitchy than my own version, but it's hardly perceptible. I'm not certain I'd notice it if I wasn't looking for it.

Thank you for addressing this.

**Comment by Swoogan** [comment]
One other thing, what is the purpose of this code:

            int deadzoneL = 0;
            if (getLSDeadzone(device) == 0)
                deadzoneL = 3;

            int deadzoneR = 0;
            if (getRSDeadzone(device) == 0)
                deadzoneR = 3;

The deadzone is zero unless it's zero, then it's three? That doesn't make any sense to me. If it's three it's zero, but if it's zero it's three? Maybe it's meant to be `deadzoneR = Math.Max(getRSDeadzone(device), 3)`, so that it's never less than three?

**Comment by Ryochan7** [comment]
Old Jays2Kings implicit dead zones. It was the same way with Xbox 360 mapping for the longest time as well. I removed those implicit dead zones and set an explicit default dead zone for new profiles. That design choice has led to many reports people have posted as bugs. I think I had commented out that section for a couple of releases before I re-enabled it due to user complaints. At least with mouse controls, it would be very unlikely that someone would intentionally want no dead zone set.

**Comment by mika-n** [comment]
I find it a bit problematic to have a hard coded implicit deadzone because at some point I'm sure there are scenarios where deadzone should really be zero. It is much better to have a deadzone as a default value in a profile because then it is possible to eliminate it if needed. 

If people upgrading from an old Jay2Kings profile files is a problem then it is possible to identify that a profile file was created using the Jay2Kings version (certain xml tags missing and the header comment field). In this case DS4Windows could impliticly modify the "zero deadzone" value in a profile file to be 0.10 or something when the new version saves the upgraded XML file.

**Comment by Ryochan7** [comment]
I wanted to avoid doing any type of profile migrations. Especially with no version information in the older files, it would probably be more work than it is worth.

**Comment by Ryochan7** [comment]
Got around to doing some minor refactors that I hesitated trying beforehand. Mouse offset is now a user configurable setting and the default has been lowered to 0.500; the old default landed around 1.280 for my usual Mouse Sensitivity of 110. Using the example of 1 for Mouse Sensitivity, the default mouse offset would make the minimum mouse speed be ~0.24 pixels per second.
