### ISSUE TITLE
PS4 Controller  Showing empty battery with BT connection 

### ISSUE THREAD

**Issue by Talharizwan** [Ryochan7/DS4Windows#1267]
PS4 Controller disconnecting again and again showing empty battery 0% while the controller is fully charged and showing 90% while connected via wired connection , 

Error message on bottom left on DS4 windows is " controller 1 removed or lost connection charge the battery"

**Comment by mika-n** [comment]
Please try to run the debug version and tweak "DS4WindowsDebug.exe.config" file settings. There is an TRUE/FALSE option for "Debug_ReadBatteryData". Set this to FALSE to see if it makes a difference. Also, post the debug logfile from "%APPDATA%\DS4Windows" folder here (attach as TXT file in a comment field).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by Talharizwan** [comment]
[debug test.txt](https://github.com/Ryochan7/DS4Windows/files/4598086/debug.test.txt)
as per your instruction i have done it but nothing happened same result plz find the attach txt file for logs

**Comment by mika-n** [comment]
Okey. There seems to be a communication issues between the PC and DS4 when a connection method is BT.  Does it work when connected over USB cable?

Anyway. How about if you tweak the following DS4WindowsDebug.exe.config entry:
Debug_ForceConnectionType=2 
Or try even Debug_ForceConnectionType=1 even when the game is connected over BT.

And how about if you uncheck a profile settings "Enable Output data to DS4" option in Others tab page? By unchecking this option the PC won't try to send data to the gamepad. Some BT chipsets are incompatible with DS4 and have problems especially when data is read and written at the same time in a fast pace (the gamepad needs to use BT communication a lot faster than a typical, for example, sports watch need to update its data).

You seem to have DS4 revision 1 gamepad. Are you sure it is genuine DS4 gamepad because some fake non-official DS4 gamepads re-use the DS4v1 hardware ID and those often have problems over BT even when those work over USB. If this is a new gamepad then it is probably a fake because Sony haven't manufactured DS4v1 gamepads in years (since the PS4-Slim was released).
