### ISSUE TITLE
Headset Audio Over Bluetooth, calling all hackers/devs

### ISSUE THREAD

**Issue by haywirephoenix** [Ryochan7/DS4Windows#1268]
With the adapter being overpriced (extortion by design if you need bt audio), and it also now being out of stock everywhere; there really is no solution to bt audio on either ds4 or xbx1 without the adapter, this could prove to be a really interesting project.

I have an EkoBuy Bluetooth 4.0 usb transmitter/receiver with BLE, EDR A2DP/HFP/HSP/AVRCP. It's CSR but it works fine with generic microsoft drivers.

I've heard some say that when pairing, it briefly advertises the audio device. And some people in russia have actally been able to send bt audio packets in linux https://habr.com/en/post/302356/

Anyone willing to peek inside their ds4 wireless adapter and post some photos of the ics?

Maybe a Usb over bluetooth solution could be worth exploring.

Let's finish this puzzle and deliver some open source justice!

**Comment by mika-n** [comment]
See what Ryochan7 has hacked and achieved within the last few days:
#1248

**Comment by haywirephoenix** [comment]
> See what Ryochan7 has hacked and achieved within the last few days:
> #1248

Nice, thanks! So glad it's being worked on.

**Comment by Ryochan7** [comment]
I wish I had backed up my changes to dual-pod-shock. I want to try audio streaming out again and I cannot find my modified version anywhere. Some other changes allowed the stuttering to occur less frequently but the audio was never smooth.

**Comment by Ryochan7** [comment]
Okay. I found an older version of my changes on my laptop Xubuntu installation. It contains the CRC32 generation portion which was the biggest issue when dealing with getting audio support working at all the first time around. I will get some changes migrated over and then upload a custom branch to my copy of dual-pod-shock; there is a lot of testing fluff in the copy I found.

**Comment by Ryochan7** [comment]
Got the changes backed up to GitHub so they won't get lost.

**Comment by Ryochan7** [comment]
Bugged keyboard mechanics d00d. Got the changes backed up to GitHub so the changes won't get lost.

https://github.com/Ryochan7/dual-pod-shock/tree/ryochan-changes

**Comment by Ryochan7** [comment]
I give up again. The wait period is the big element keeping the stream from being solid. With tweaking the wait period and removing the array printing, the stream could be made mostly stable. The stream would become a bit less stable with extra system activity even when placing the routine in a different thread.

I also tried to get audio streaming somewhat working on Windows and I could not get the controller to use the stream.

**Comment by haywirephoenix** [comment]
Thanks for trying anyways! Digging through these changes now, very interesting stuff.

**Comment by mirh** [comment]
Comments in the original article mentions turning off nearby wifi, and a certain `is-live=true` parameter. 

Also, why is bitpool 25 when the HID reports had 19? 
And why are we still tricking with scripts, instead of the [hard and fast C](https://github.com/mumumusuc/pi-ds4-dongle)? Perhaps that could allow a finer control of [buffering](https://github.com/chrippa/ds4drv/pull/80#issuecomment-253677945).

**Comment by Ryochan7** [comment]
Might as well post the update here as well. I got audio streaming to work, to some extent, on Windows. The program will use the first Sony DS4 device that it can find. The location of the playable SBC file has to be given as a cmd argument.

DS4 BT Audio Test (Windows)
https://www.youtube.com/watch?v=H2bjd7Oc2l0

Project Source
https://gitlab.com/ryochan7/ds4-audio-test-windows

**Comment by haywirephoenix** [comment]
Legend 👏 how did you overcome the stuttering?

**Comment by Keltere** [comment]
Is just jack or can it works with the integrated speaker?

**Comment by Hexality** [comment]
I'm just imagine but, if this works and Dualsense has some similarity to how dualshock audio works, we may be close enough to a possible haptic feedback/headphone jack over bluetooth?

**Comment by julianxhokaxhiu** [comment]
May I ask why this was closed? Seems a bit misleading to me.

If this needs to be worked on, it's better to keep it open in order to favor also contribution instead of thinking it was closed because either you ( as author ) gave up or perhaps it was fixed/triaged in any other issue/PR.

I suggest re-opening it, maybe updating the title to something fitting ( like `[CTA]` or `[WIP]` ) and dump as much detail as possible to foster the collaboration. I'd be happy to contribute but I'd need some kind of "kickstarter" to know how to start approaching this topic.

Thank you in advance.

**Comment by mirh** [comment]
Because noobs can't behave and keep nagging/spamming the threads over and over again (like, fuck, they don't even have the courtesy of checking what the previous messages said). 
Ryochan already got the thing "somewhat working" as you can see in #2089 - but there's still something he/we cannot quite put the finger on, with stability far inferior to the one you get on PS4. 

Nothing impossible, nothing crazy.. it will come one day, it's just a matter of sniffing/understanding the official bt connection better (some linux dev may have already succeeded in this, but I'm not sure)
For the moment there are far better (and probably *funnier*) [priorities](https://github.com/Ryochan7/DS4Windows/blob/jay/TODO.md) here.

**Comment by mbc07** [comment]
Things might get better in the future. AFAICT audio over BT is also needed to use the DualSense voice actuators wirelessly and that's something that probably will drive more people trying to figure this out...

**Comment by julianxhokaxhiu** [comment]
Thanks @mirh I've figured out all of that already but i was more wondering if there was a proper documented ticket where we could all jump in, get a quick kickstart and find out way out in hacking the project and therefore contributing. At the moment it looks like the information is quite sparse and it makes it very difficult to grasp.

@mbc07 maybe...or maybe not. As the functionality is currently present via USB, some people might just buy a super long cable and problem solved. Would be cool though to have it via BT too.

**Comment by Ryochan7** [comment]
The main point is that there is **no** collaboration. People are just complaining about me not finding a way to get it done.

![hey-peter-whats-happening](https://user-images.githubusercontent.com/581968/125205621-c543a700-e248-11eb-93d9-00d96f319786.jpg)
