### ISSUE TITLE
CSR 4.0 does not connect to DS4 V2

### ISSUE THREAD

**Issue by DerpHitman** [Ryochan7/DS4Windows#1270]
Hi there,

I've read on the issues here that CSR with default windows stack should work with the DS4, but mine does not connect. It shows up when I start the pair mode but does not connect no matter what. 

From what I could gather searching on the internet and tutorials is that only the DS4 V1 works with it, can anyone tell me if they have a V2 controller that works with a CSR dongle?

My dongle is a CSR8510 btw. 

Best Regards

**Comment by reyaz006** [comment]
I have CSR 4.0 and my DS4v2 works.
OS is Windows 8.1. Default BT stack is used, because I didn't like the driver supplied with the device.
In Device Manager it's named **Generic Bluetooth Radio**.
Hardware ID is **USB\VID_0A12&PID_0001&REV_8891**.
Reported description is **CSR8510 A10**.

My advice is to verify that your DS4 is original. Be sure to use the default Bluetooth pairing window. Read the pairing instructions in DS4W's Controller/Driver setup window.

**Comment by Ryochan7** [comment]
I use a similar adapter and all the listed info is the same. As long as the generic Microsoft driver and tools are being used then I would expect it to work fine.

Connect DS4 via Bluetooth Demo:
https://www.youtube.com/watch?v=5SUYCL5-vtw

Doing a quote here since the info is the same with my BT adapter as well.

> In Device Manager it's named Generic Bluetooth Radio.
> Hardware ID is USB\VID_0A12&PID_0001&REV_8891.
> Reported description is CSR8510 A10.

**Comment by DerpHitman** [comment]
I see. I'm pretty confident my DS4 is original, everything works perfectly with it except from connecting to the PC via this dongle. 

I checked the device manager and the same name and Hardware ID shows up, but where can I find the reported description? @reyaz006 My windows is in Portuguese so I'm not sure exactly where that is. As far as I know mine is a CSR8510 A10, but maybe it could be something else.

**Comment by DerpHitman** [comment]
In devices and printers my dongle simply shows up as "dongle", with a headset icon. In properties it says the manufactures is "KOGA". Could it be my dongle then?

**Comment by DerpHitman** [comment]
@reyaz006 @Ryochan7 I figured it out. Apparently I needed more pairing time for the controller to connect, so just starting pairing mode once again right after it ended was enough time for it to connect. Very odd. But everything is working now.

Thank you very much! Your comments made me try it again and it worked this time.

**Comment by reyaz006** [comment]
>but where can I find the reported description?

Somewhere in this list, in Device properties / Details tab. https://thegeekpage.com/wp-content/uploads/2017/07/hardware-id-min.jpg
