### ISSUE TITLE
Not working at all in Server 2019

### ISSUE THREAD

**Issue by rfulton04** [Ryochan7/DS4Windows#1271]
This is using a Dualshock 4 PS$ controller on Server 2019 Datacenter edition. 

This 100% worked on exact same hardware using Windows 10.

Using both Wired and Bluetooth.

![image](https://user-images.githubusercontent.com/12041000/81362863-e1314300-90af-11ea-8218-8a95d29de21b.png)

![image](https://user-images.githubusercontent.com/12041000/81362895-f1492280-90af-11ea-8013-166686fba571.png)

![image](https://user-images.githubusercontent.com/12041000/81362917-fe661180-90af-11ea-96aa-69975a52ffde.png)

**Comment by rfulton04** [comment]
![image](https://user-images.githubusercontent.com/12041000/81362982-23f31b00-90b0-11ea-8f94-22ce25d6e4c1.png)

**Comment by Ryusennin** [comment]
You need to provide more information.

#1196

**Comment by rfulton04** [comment]
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4599097/ds4windows_log.txt)

**Comment by rfulton04** [comment]
This is using the debug version. 

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4599112/ds4windows_log.txt)

**Comment by rfulton04** [comment]
BTHENUM\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&09cc
BTHENUM\{00001124-0000-1000-8000-00805f9b34fb}_LOCALMFG&0002

**Comment by rfulton04** [comment]
DS4 Model CUH-2CT2U

**Comment by rfulton04** [comment]
I now see that it enumerates "Human Interface Devices" under Device manager. However, Server 2019 is not recognizing it as such, it's detecting it as an "other device - Wireless controller"

![image](https://user-images.githubusercontent.com/12041000/81410650-14ef8580-910f-11ea-8e96-bf0354dc66e0.png)

**Comment by rfulton04** [comment]
Attempting to manually assign "HID-Compliant Game Controller" Reveals that it's not even an option under microsoft.

![image](https://user-images.githubusercontent.com/12041000/81411326-3735d300-9110-11ea-9a14-b239e0b936cb.png)

**Comment by mika-n** [comment]
Some WinOS and DS4 driver incompability or DS4 driver not installed at all. Few times I have heard about similar scenarios, but those were not WinServer2019 installations. Anyway, one way to solve the missing DS4 driver issue is to try to install "Sony PS4 RemotePlay for Windows" app because it tries to see if the PC is compatible with DS4 drivers.

Anyway. At first you need to get the WinOS to recognize the DS4 HID device. I think very few people here use WinServer OS versions, so you are on your own with that OS.

**Comment by rfulton04** [comment]
No luck on PS4 remote play. seemed to install fine. nothing will detect the controller. rip in peace.

**Comment by Ryochan7** [comment]
Not sure why you would be using Windows Server on a gaming rig. It would be a bit weird if the Server edition does not bundle the driver for HID game controllers. If you can find a way to make the DS4 work then great. I will not be able to provide support for Windows Server and I would recommend against using it for this purpose.

**Comment by rfulton04** [comment]
I have VMs that require hyper-v replication on it. Gaming rigs make great servers :).

I find it weird that it's outright missing the HID-Complaint game controller, and i'm probably the only person on the planet using a DS4 controller on server 2019 datacenter.

**Comment by zeruth** [comment]
This is still an issue, and maybe not a lot of us use Server 2019, but some of us do, and it's a huge heartbreak to see this not work at all either wired or wireless... I use it for my media center.

**Comment by mika-n** [comment]
Try installing Sony PS Remote Play app. Is the ds4/Ds5 gamepad recognized by WinOS (over usb or BT) after installing this app?

**Comment by zeruth** [comment]
yeah I tried that, doesn't do anything. ds4windows hangs here:
![image](https://user-images.githubusercontent.com/2943260/103409294-00874f80-4b1b-11eb-8791-a39227ada6d3.png)

I noticed it even sets the lightbar color before freezing.

**Comment by mika-n** [comment]
How about if you try the latest debug version and logfile? The latest debug version is based on 2.2.1 version.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

If the gamepad is shown in DS4Windows app and the lightbar flashes then there must be some activity. 
And do you have DS4 gamepad? Does it work better than DS5`in WinServer?

**Comment by zeruth** [comment]
Okay I got it figured out for wired at least!
Server 2019 doesn't apply the drivers automatically for some reason, however they DO exist!
![image](https://user-images.githubusercontent.com/2943260/103409899-be134200-4b1d-11eb-806c-f8e769f69226.png)
![image](https://user-images.githubusercontent.com/2943260/103409912-cbc8c780-4b1d-11eb-8cdd-c66f9df07aee.png)

Then you have to be sure to install the Win7 360 controller driver in the panel because Server 2019 doesn't come with the driver naturally.  

I'm now using my DualSense comfortably touchpad and all, trying to work out wireless still but i'll take this for sure
