### ISSUE TITLE
ds4 wired crazy movement on fifa20

### ISSUE THREAD

**Issue by pipes80-collab** [Ryochan7/DS4Windows#1279]
I have a problem when I connect ds4 with cable, I start FIFA 20 and there are strange and repeated movement without touch nothing, no problem with bluetooth

**Comment by mika-n** [comment]
Take a look at the pinned "Read this before posting a new ticket" post. FIFA is known to have problems with double-inputs. The solution is hide the original physical controller.
https://github.com/Ryochan7/DS4Windows/issues/989
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#double-input-problem-in-games-game-does-all-sort-of-weird-things-when-i-press-a-button-second-player-drops-in-cannot-navigate-in-menus-because-focus-moves-two-lines-when-i-press-a-key-just-once-etc

When you use BT then the original DS4 bt device is in "dead state", so that's why it works there.

**Comment by pipes80-collab** [comment]
with the active option to hide the ds4, the problem is not solved

**Comment by pipes80-collab** [comment]
this is the register after connecting the ds4 via usb, but no uwp app started, FIFA 20 use oriogin, maybe is that the problem?
![Annotazione 2020-05-11 213537](https://user-images.githubusercontent.com/56699284/81603972-7e9db700-93cf-11ea-8e14-54482b35a377.png)

**Comment by mika-n** [comment]
The logfile shows an error about exclusive mode (=Hide DS4 Controller option). That's why you are still seeing the FIFA bug (lazy EA programmers). 

Just read through one more tine the Wiki doc page and try to isolate which application has hijacked the physical gamepad device (and this way preventing DS4Windows to do exclusive trick). This really is PC environment specific thing, so there is no way we can tell you exactly which process has hijacked the DS4 gamepad. 
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

If you cannot get the exlusive mode to work and make sure that DS4Windnows app is the first app opening a connection to DS4 gamepad then you have to consider using the alternative solution to hide the physical DS4 gamepad. Install the HidGuardian tool to do the same as HideDS4Controller option in DS4Window (ie. those are alternative techniques, no need to use both at the same time).

**Comment by pipes80-collab** [comment]
maybe I have solved, only start windows with the controller wired

**Comment by Ryochan7** [comment]
Exclusive access to the DS4 is required to not run into problems with the FIFA games. You might be forced to install and utilize HidGuardian to work around the problem.

https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide
