### ISSUE TITLE
update for ds4windows 

### ISSUE THREAD

**Issue by elcorsico** [Ryochan7/DS4Windows#128]
please update with new version DS4Windows v1.4.96
thanks devs ;-)

**Comment by Ryochan7** [comment]
?

On Oct 7, 2017 7:40 AM, "elcorsico" <notifications@github.com> wrote:

please update with new version DS4Windows v1.4.96
thanks devs ;-)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ryochan7/DS4Windows/issues/128>, or mute the thread

**Comment by elcorsico** [comment]
sorry , update for cemu control possible or not ??
thanks devs

**Comment by Ryochan7** [comment]
I do not work on that version of the program. You would have to get in touch with @rajkosto about updating that fork.

https://github.com/rajkosto/DS4Windows
