### ISSUE TITLE
Suggestion regarding Update notifications

### ISSUE THREAD

**Issue by Eiion** [Ryochan7/DS4Windows#1290]
Whenever there's an update we get a notification pop-up. That's good! But that pop-up only should show up once until there's a newer update.

Opposed to that I've declined to update after I got that information - still, with every system start (DS4Windwos is in autostart) I'm getting the notification again for the same update that I've been informed about multiple times previously and which I also have declined multiple times. In my opinion it shouldn't be like that.

**Comment by Eiion** [comment]
So since aparently nobody is currently working on the project staying updated on the issues posted, here's an update of mine:
I've changed the time period after wich the DS4Windows should check for an update to once every 30 days. Still, with every start (it starts with the system) I'm getting a message that there's a new update available asking if I want to update or not. Please turn this off!

**Comment by Ryochan7** [comment]
My online activity is out there both on GitHub and GitLab. You should be able to see that I have been busy working on various tasks for several projects. Some of you people are completely unreasonable. If you want this changed right now, send a pull request. Otherwise, you have to wait until I get around to it.

**Comment by Ryochan7** [comment]
Here you go Lord. Good thing to know I'm nothing more than a serf to you.

https://github.com/Ryochan7/DS4Windows/commit/e0655fbc360a0a9cb94bf153f3fcfcac95cb6d7d

The initial idea was only proposed two weeks ago in a different thread.

https://github.com/Ryochan7/DS4Windows/issues/1311#issuecomment-637548257

**Comment by Eiion** [comment]
If after about a month there's not even a one sentence reply to a suggestion than assuming non-interest isn't too far fetched. So much for being unreasonable. 
Talking off being unreasonable: Apparently I touched a sore spot of yours and I'm sorry if that made you feel attacked. But my wording wasn't offensive nor was I making any demands. I just added to my original suggestion trying to circumvent the issue at hand (and failing with this step, since only completely deactivating the feature fixed it). That's no reason to become all defensive and going off like you just did on a platform about software development. Bye.

**Comment by deadair3210** [comment]
I mean, yeah it was offensive, you were basically demanding that they stop what they were doing and fix your issue immediately. Nobody gets paid to do this, they do it whenever they want. 

It's not abnormal for projects to go months without issues being answered. Don't assume that just because nobody has responded that it's not being worked on
