### ISSUE TITLE
Error on windows shutdown

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#1295]
![20200522_180549_HDR](https://user-images.githubusercontent.com/3978291/82717990-c6dd9480-9c6d-11ea-88bf-f46a63455bc5.jpg)

**Comment by mika-n** [comment]
CiceroUIWndFrame? That's not DS4Windows wnd class. Google tells that it is part of MS/Office and is "Speech and Handwriting Recognition feature" and seems to be known bug there. 
https://answers.microsoft.com/en-us/msoffice/forum/all/cicerouiwndframe-removal-procedure-fails/d716cf9d-2058-44b7-b3b6-dc554c2cdc3c

**Comment by shinra358** [comment]
I have office but haven't used it in years and ive not had this error before. just randomly does it on shut down sometimes recently. And if it is not a part of the program, why does it show the program name beside it and in the error box?

**Comment by mika-n** [comment]
> And if it is not a part of the program, why does it show the program name beside it and in the error box?

Because the MS "Speech and Handwriting" gadget attaches itself to an application window and message queue to do those addon speech/handwriting things. Just follow the instructions described in the MS bug report page (or numerous other similar pages Ms Google can find). Update Office version or uninstall/disable SpeechHandwriting gadget if you don't use it.

**Comment by Norbi095** [comment]
Hello, shinra358, I am dealing with the same issue for over a month now, and couldn't find a way to figure out what causes it.
I've been trough multiple Windows reinstalls as well, on both my two PC's, and none of which helped sorting out this issue whatsoever..

I've created a thread on the issue, the main error message pops up on Reboot/Shutdown saying 'CiceroUiWndFrame Application Error/Exception', and the other's are connected to .Net Framework errors.
The CiceroUiWndFrame exception is the most common error on restart, though.

Since I saw that you've closed this tread, have you managed to find a solution for the issue since?
mika-n said that it could be connected to Office, yes, but the Speech/Handwriting Option was present in the old, 2003 version of MS Office, but both my PC's have the newest 2019 (Office 365) installed on them, which none of has these options in them anymore, so something else is the cause of this issue.

Strangely enough, the original Release Build of DS4Windows (Jays2kings build) has no errors/exception neither on reboot/shutdown. I tested this multiple times, to make sure. Only the ryochan build has this issue.. weird.

**Comment by shinra358** [comment]
It doesnt seem to happen anymore since i posted this. I think when it
happened, nvidia drivers had stopped responding and recovered (probably
bcuz i needed to repaste... I c diamond thermal pads suck). So it was
probably because of that for me. It makes no sense why an untouched program
like microsoft office would magically be a problem out of nowhere 😂

**Comment by Norbi095** [comment]
Thats exactly what I was thinking.
Strange problem on my end though is that the two PC build I have are very different, the desktop PC is an Intel/NVIDIA Combo, and the second is actually a Lenovo Ultrabook with AMD CPU/GPU in it.
Both of them has a fresh copy of Windows 10 Pro, with the latest official Office 2019 on them as well.

Anndd.... both of my setups have the same exact issue on reboot/shutdown, and is also very random, sometimes it pops up, sometimes it doesn't, Event Viewer contains nothing usable, all it says it is conencted to SafeShutdown error in connection with the DS4Windows.exe, and other .Net errors...

Very strange, but yeah, it has to be something on a software side on either with the DS4 app itself, or something else..
If only I would know what though : (
And as I've said, the Jays2Kings Build which was forked to this new version works just fine without an issue, but, of course its missing features that this new fork has, so that's not an actual solution... : /
