### ISSUE TITLE
[Question] Custom Steam Option

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#1298]
Hello, what is the custom steam directory option used for?

**Comment by mika-n** [comment]
DS4Windows can look for Steam installed games in Auto-Profile/AddPrograms button. Well, at least DS4Windows used to do this, but now when I look at this Auto-Profile/AddPrograms button there is no longer "Add Steam games" option like there used to be in older versions.  So, it seems that at the moment DS4Windows doesn't use that option for anything :-)

The missing "Add Steam games" is not crucial issue because you can always use the existing "Add folder" or "Add program" buttons to add Steam games one by one to auto-profile list (if you use auto-profile feature at all).

**Comment by shinra358** [comment]
And there is also the button combo to launch a program and a separate run
program with profile so i was confused as to why we needed a 3rd option to
run a program.
