### ISSUE TITLE
Possible Future Issue with Steam and Exclusive Mode

### ISSUE THREAD

**Issue by Miltrivd** [Ryochan7/DS4Windows#1299]
On the latest Steam client beta some changes were made to their controller configuration and it seems to be trying to "take over" the controller constantly.

Even if you launch DS4Windows before Steam and hide the DS4, as soon as you turn it off it'll block Exclusive Mode the next time you turn the controller on, which means that you have to restart Steam every time you turn on the controller. This doesn't happen on the current stable client, you just open DS4Windows first and enable Exclusive Mode once when you turn on the PC.

Not a request or anything, just a heads up.

**Comment by mika-n** [comment]
Okey. Good to know. This just confirms that HidGuardian is becoming more and more required to do the "hide the physical controller" trick because Steam client shouldn't be able to dance around HidG (=kernel mode driver).

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer

**Comment by Ryochan7** [comment]
We are pretty much at a point where the old "Hide DS4 Controller" workaround is useless. At least it got an extra 3 year life span.
