### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by adestrador** [Ryochan7/DS4Windows#1304]
Every time I connect my DS4 in usb port to charge and play my games, after charged, when I try to connect via bluetooth, it doesn't work. I have to delete "Wireless Controler" in Windows 10 Bluetooth settings and pair again.

In Witcher 3, via usb connected, gamepad has problems. For example, for Geralt to get off his horse, the "circle" button must be pressed, but when I do that nothing happens, so I have to use the keyboard to do this.

**Comment by Ryusennin** [comment]
I'm playing Witcher 3 via USB and have no issues (GOG version). Is this a genuine DS4?

**Comment by adestrador** [comment]
> 
> 
> I'm playing Witcher 3 via USB and have no issues (GOG version). Is this a genuine DS4?

Yes

**Comment by adestrador** [comment]
> 
> 
> I'm playing Witcher 3 via USB and have no issues (GOG version). Is this a genuine DS4?

Yes, geniune

**Comment by raff-run** [comment]
I'm playing Witcher 3 right now through Steam with my controller on bluetooth. I had some problems initially -- the game didn't recognize any inputs, but that was actually because of windows 10's fastboot option (https://github.com/Ryochan7/DS4Windows/issues/1293) which made DS4Windows leave a "ghost" controller that gives no inputs and Witcher 3 listened to it, but the latest update (really recent) fixed this problem.

Try updating to see if it works. This update specifically might actually solve your problem with swapping the controller from USB to Bluetooth since you can specify a permanent virtual controller slot, so your game never notices a controller got disconnected in the first place.

Oh, and a tip: try charging the controller with a phone charger -- it'll charge WAY quicker than through USB connected to your computer. Just make absolutely sure the charger outputs exactly 5V because higher voltages may damage the controller and at least 800mAh (as it's written on the back of your controller, higher mAh values are safe, while lower values means it'll charge slower).

**Comment by Ryochan7** [comment]
The thing don't work

**Comment by adestrador** [comment]
> 
> 
> The thing don't work

Why? Your English is horrible

**Comment by Ryochan7** [comment]
> > The thing don't work
> 
> Why? Your English is horrible

I was poking fun at your vague title and post. You do realize that I'm the DS4Windows head developer right? Go bother somebody else.
