### ISSUE TITLE
Auto movement on CODMW

### ISSUE THREAD

**Issue by Heroiik** [Ryochan7/DS4Windows#1305]
Good morning all,

I have a problem for a few weeks with DS4, when I play call of duty I have the right joystick which moves slightly on its own, in bluetooh or wired

Only for Right stick and when i go to the left, maybe the dead zone but i tryed settings but not work...

I tried with the hide controller option and the HIDGUARDIAN software but now the game no longer recognizes the controller

Thanks ;)

**Comment by Heroiik** [comment]
Only for Right stick and when i go to the left, maybe the dead zone but i tryed settings but not work...

**Comment by mika-n** [comment]
Please provide details of the installation, versions and logfile as described here.
https://github.com/Ryochan7/DS4Windows/issues/1196

**Comment by Heroiik** [comment]
![capture1](https://user-images.githubusercontent.com/9657425/83390945-071ddf00-a3f3-11ea-83f5-a702efc4055f.PNG)
![capture2](https://user-images.githubusercontent.com/9657425/83390952-09803900-a3f3-11ea-9ddd-0b8f29162967.png)

on the second picture you see the position of Rx when i  shift very slightly to the left

**Comment by mika-n** [comment]
Hmmm... To me this looks like a hardware issue because the RX(I) = 64 and RX(O)=65.
I=the raw input from the physical DS4 gamepad.
O=output value after DS4Windows app has done all sort of optional rescaling/remapping/output curve manipulation as set in a profile. In that case you don't have any tweaks in RX because the I and O are the same value.

https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping

**Comment by Heroiik** [comment]
No Rx has arround 128, but when I push slightly to the right it appears, would you like a video?

**Comment by mika-n** [comment]
How RS looks like in https://html5gamepad.com/ web site when you run it with and without DS4Windows app?

If things work fine without DS4Windows app then try creating a new default profile in DS4Windows in case there is some problematic re-mapping/profile tweak in use.

If you use HidGuardian tool then you may have to temporarly disable it when you test the gamepad without DS4Windows app. One way to disable HidGuardian magic is to comment out HID device identifiers in AffectedDevices sysreg entry of HidG tool. There is a small utility to do it or you can use WinOS regedit tool to do it. After doing this the gamepad needs to be disconnected and re-connected because these settings take effect at gamepad connection time.
https://github.com/Ryochan7/DS4Windows/issues/1219

**Comment by Heroiik** [comment]
I tested everything but nothing works

**Comment by mika-n** [comment]
If HTML5Gamepad.com website shows the same weird result even when DS4Windows is not running then I would say that this is a hardware issue (or BT connectivity issue). But it does sound a bit weird issue and I have never heard before that RS stick would behave like that over BT, but just fine over USB.

There has been cases where cheap "wanna-be chinese fake copies" of DS4 gamepad have worked just fine over USB, but fails to work at all over BT.

Don't know if it would help to reset the gamepad. There is a small hole on the back of the gamepad you can press with a paper clip. At least it would not hurt anything (you have to re-pair the gamepad after reseting it). And if you have PS4 console or another PC then try how it works there to see if this is gamepad or PC issue.

**Comment by phammanhhiep** [comment]
Got the same problem with game "Control". The left stick seems to be automatically triggered even if I don't touch it. The only I found is use the ds3windows of Jays2kings .

**Comment by mika-n** [comment]
@phammanhhiep  Take a look at the deadzone setting. The old Jays2Kings version had a built-in deadzone even when a setting in profile would have zero deadzone value. This Ryochan7/DS4Windows version allows to use true "zero" deadzone if the value really is zero. In some scenarios it is useful. If you need to use deadzone then simply set the value in a profile.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping
