### ISSUE TITLE
feature request: Easier Defaulting

### ISSUE THREAD

**Issue by nr1995** [Ryochan7/DS4Windows#1306]
I would really appreciate an easier way
to get the numbers on each page/tab back to their defaults.
I think it would help encourage experimenting with tweaking the settings.
Could you add a “Defaults” button in _Controls_, _Axis_ _Config_, _Gyro_, and _Other_ ?
Thanks!

**Comment by mika-n** [comment]
Just take a copy of the existing profile as a backup before experimenting something and there you go.

**Comment by nr1995** [comment]
> Just take a copy of the existing profile as a backup before experimenting something and there you go.

Diving into the file manager to make backups is about 100x more hassle than a single click.
You don't feel like it's worth adding?

**Comment by mika-n** [comment]
Ööööh? Isn't there the Duplicate button on Profiles tab page?

**Comment by nr1995** [comment]
> Ööööh? Isn't there the Duplicate button on Profiles tab page?

Yeah, that's true I guess.
Still though, I stand by the request.

**Comment by mika-n** [comment]
I doubt there will be "tab page" specific "back to default" option because behind the scene the internal profile object doesn't know in which tab page each of the attributes are displayed. Only the GUI layer knows how attributes and the display layer is linked and categorized. Someday the display layer may be changed and options moves to different tabs, so too much hassle to keep all that in sync in "tab specific default button". The duplicate button works reasonable good as a backup/testing playground with new tweaks.
