### ISSUE TITLE
Controller readings greyed out?

### ISSUE THREAD

**Issue by ItsKlods** [Ryochan7/DS4Windows#1308]
![Capture](https://user-images.githubusercontent.com/66250305/83398933-384cde00-a3f8-11ea-8d46-4a1bf7972c5a.JPG)

Any ideas?

**Comment by bslenul** [comment]
Yup same issue for me, if I edit profiles from "Profile" tab, it's greyed out for some reason.

However, it works absolutely fine by clicking "Edit" directly from the "Controllers" tab.

**Comment by ItsKlods** [comment]
> Yup same issue for me, if I edit profiles from "Profile" tab, it's greyed out for some reason.
> 
> However, it works absolutely fine by clicking "Edit" directly from the "Controllers" tab.

Exactly this. Didn't know it worked through the controllers tab, thanks for that!

**Comment by mika-n** [comment]
That is by design. You have to edit the profile via "Controller" tab because this way DS4Windows  knows which gamepad to bind the profile editor. Editing profiles via profiles list is a bit problematic if you have more than one gamepad (which gamepad should show the Readings activity?).  Okey, granted that if you have only one gamepad connected at the moment then DS4Windows could automagically choose that even when profile is edited via profiles list.

**Comment by bslenul** [comment]
Ah yeah, I was confused because it was possible previously, but that makes sense!

**Comment by shinra358** [comment]
Ok, I'm trying to edit the profiles via the profiles tab and things are all still greyed out @.@

**Comment by Ryochan7** [comment]
Too bad I don't still have the old test patch I made. A patch was made to allow the mapping data in the Controller Readings tab to be independent of the UI but the changes were held back since the output from the currently active profile would obviously not reflect what is shown; that would lead to possible confusion. I guess I am going to end up re-enabling that tab for this path in the next DS4Windows release.

I hope I do not regret doing so. The feature was initially disabled as people incorrectly posted mapping discrepancies as DS4Windows bugs.
