### ISSUE TITLE
Touchpad not working

### ISSUE THREAD

**Issue by venkateshmoganti** [Ryochan7/DS4Windows#1310]
Playing Detroit became human on pc. Unable to use the swipe on touchpad and tapping not working in game. Please help

**Comment by mika-n** [comment]
DS4Windows app and the ViGem virtual gamepad driver doesn't support touchpad events in the current version. Touchpad is supported in DS4Windows app but it can be mapped as, for example, mouse control but not as a "true DS4 touchpad" through a virtual gamepad controller. Full touchpad support is under investigation by ViGem developers and when it is released then I'm sure DS4Windows app will support it.

**Comment by Ryusennin** [comment]
Detroit is xinput-compatible on PC, you don't need DS4 mode. Touchpad events are remapped to analog stick equivalents if you use X360 mode.

**Comment by Ryochan7** [comment]
Although I use DualShock 4 output support in some cases, too many of these issues keep getting posted. Makes me wonder whether offering the option is even a good idea.

**Comment by Ryusennin** [comment]
In the Profile/Other tab, I would simply suggest renaming the option "Controller: X360/DS4" to "Emulated Controller: X360/DS4". That would clear some things up.

Right now, the option seems to confuse some people into believing it's related to their physical controller. They just select DS4 because they have a DS4 and they think it's the normal thing to do.

**Comment by Ryochan7** [comment]
Personal I think the wording in context is pretty obvious.
