### ISSUE TITLE
Steering wheel calibration not persisting upon reconnection [log]

### ISSUE THREAD

**Issue by JuanRomani** [Ryochan7/DS4Windows#1314]
Hi! I'm having issues with the steering wheel calibration function. Had to reinstall version 2.1.1 some days ago becasue the calibration process was completely unresponsive (Created several profiles, changed run as from Task to Program and back, multiple reboots, you name it).
Now I'm on version 2.1.2 and it seems like the steering wheel calibration is not persisting when the controller is reconnected.

I experienced this issue on all scenarios... random disconections, "normal" ones or just automatic idle shutdowns.

Controller is a legit DS v2, running through a BT adapter less than 2ft away.

Log:
[DS4Windows Log 20 06 02.txt](https://github.com/Ryochan7/DS4Windows/files/4720800/DS4Windows.Log.20.06.02.txt)

Also, thanks a lot for all the work you put into this, it's insane. I'll look onto the code one of this days to see if I have the time or knowledge to help a little!

**Comment by mika-n** [comment]
Hmm... After the calibration what do you see in "%APPDATA%\DS4Windows\ControllerConfigs.xml" configuration file. It should have something like this (see how gamepad MAC identifier is used to link certain calibration with a gamepad):
```
  <Controller Mac="A1:13:9F:24:81:34">
    <wheelCenterPoint>8,-111</wheelCenterPoint>
    <wheel90DegPointLeft>-117,9</wheel90DegPointLeft>
    <wheel90DegPointRight>124,12</wheel90DegPointRight>
  </Controller>
```

**Comment by JuanRomani** [comment]
Hi! Here is my ControllersConfigs.xml (as .txt because github) [ControllerConfigs.txt](https://github.com/Ryochan7/DS4Windows/files/4726494/ControllerConfigs.txt), apparentlynothing in there... The procedure was logging in on Windows, turning controller on (via BT), do the calibration procedure, then manually disconnect the controller (Options + PS Button).

[DS4Windows Log 20 06 03.txt](https://github.com/Ryochan7/DS4Windows/files/4726497/DS4Windows.Log.20.06.03.txt)

**Comment by mika-n** [comment]
For some reason the ControllerConfigs xml file is not updated there. Permission issue? Special chars in path names? When you installed the app then DS4Windows asked where you want to save config files. Did you choose application profile folder instead of programFiles folder? Some PCs have additional security tweaks in c:\program files (with and without x86)\ folder. Try installing the app to for example c:\apps\DS4Windows\ folder and choose appprofile location as the configuration target.

Or if you remove the ControllerConfig.xml file then is is re-created? This should tell us if there are some permission issues.

Did you use the "Calibrate..." button and dialog or the "calibrate 360-steeringWheel" special action to do the calibration? Try using the "Calibrate..." button in Gyro tab page and remember to press "OK" button when all three calibration points are set.

If nothing else helps then try copying calibration values to the xml file manually (use the sample I posted as an example format).

**Comment by JuanRomani** [comment]
Hi! I have DS4Windows currently installed in C:\DS4Windows, tried running as Admin as well, with the same effect.

The re-creation of ControllerConfig.xml file seems to work fine every time I delete it and restart the program.

I have always used the "Calibrate" button on Gyro tab, at 180º, mapped to the Right Y-Axis

Didn't know about the special action, but tried it after reading your comment. Creating a mapping to that special action is doing nothing for me, no dialog even.
Also, when I tried to edit the Special Action it seems like is saving it as "Multi-Action Button", and if you try to edit it, the program crashes (tried multiple times).

No issues with editing the file manually, the problem is the values seems to vary when the controller loses connection and I will have to make an edit every time :/

Thanks for following up!

**Comment by mika-n** [comment]
Veeeeery strange. I have tested here the latest version with usb and bt gamepads with new and existing controllerConfiguration.xml files. No matter what I try the calibration AND saving and reading of those settings work just fine.

Calibration values should not vary between reboots with the same gamepad. However, please note that the "360 steering wheel emulation mode" is not really meant to be used as "swinging it around in mid air with free hand". It is more useful when the gamepad is installed in a "do-it-yourself" rig. This makes the gyro movement and calibration values more predictable and stable. This way for example EuroTruckSimulator/MudRunner/FarmSimulator type of games are veeery good (almost like playing with a real steering wheel with lots of buttons on a steering wheel).
https://github.com/Ryochan7/DS4Windows/pull/491#issuecomment-439821245

If you want to use gyro as "swinging it around in mid air" then may get better result with "steering wheel option 1" where gyro axis is re-mapped directly to LS/RS stick axis. However, this has very limited turn range (because of DS4 gyro sensor range) and the range "wraps around vice-versa" when you tilt the gamepad too much to left or right.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#steering-wheel

The "steering wheel option 2" you have tried to use is more like "DIY" steering wheel solution and work surprisingly well IF it is used with a rig (=tilting of the DS4 and gyro values are predictable and that's why calibration process makes it very accurate even when there are HW differences between DS4 gamepads).

Anyway. The linking between ControllerConfigs.xml file and a gamepad is looked up via MAC xx:xx:xx:xx value. Usually this should remain the same, but if for some reason this changes between DS4 re-connections then there will be problems.

Maybe the debug version would tell us more clues what is going on when the gamepad is connected and gyro calibrated.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by JuanRomani** [comment]
Will try the debug version as soon as I can. I'm currently using the gyro to play Assetto Corsa, although I haven't really affixed it to something and obviously there is more movement than it should (that DIY its awesome btw).

Will update soon, thanks!
