### ISSUE TITLE
[Feature] Special action - option to block usual inputs when the action gets activated

### ISSUE THREAD

**Issue by raff-run** [Ryochan7/DS4Windows#1316]
Special Actions are definitely one of the features I like the most in this program. I recently mapped a key combination, PS + R2, to a macro that toggles my microphone on/off in Discord and it works well! One problem arises though. When I use it, the R2 key will still become an input for the game I'm on. 

I have a similar problem on Witcher 3, where I map R2 + Circle to cast a spell. 
When I have enough mana to do it, it's fine, because Circle (the jump button) will get ignored as I will be already in the casting animation. When I don't have enough mana however, I jump, because both the keys for casting an spell and jumping were inputted at the same time.

So if I could mark a checkbox on the special action to block input from going to the game (while still activating other special actions, where applicable), that'd be great. I say "while still activating other special actions" because I have 2 actions bound to the same combination: one, a macro, and the other, a Press/Toggle key action:
![image](https://user-images.githubusercontent.com/44688128/83704804-8b39b780-a5e9-11ea-9f16-baab425c8876.png)

**Comment by artzox** [comment]
Just came into the same issue. My solution is to use R2+right thumb stick directions or R2+R3 to select and execute all 5 signs in W3. I have also unbound the R2, so no execution of the  previously selected sign by chance. Make sure to record the selection and exetution (for example 3+q) using the pauses,otherwise it doesn't work. This binding works nicely as you only move the right stick a milimiter and don't get false jumps or other actions if mana is depleted. The only downside is that to execute you lose some milliseconds in selecting the sign on each execution.

**Comment by raff-run** [comment]
I see. I don't like recording both selection and execution in one macro, though. That makes it so I can't use alternative modes. That's why they're separated: so pressing R2 + Triangle will execute the selection macro first(because it's on the top of the list), then use the toggle key bind separately and only release Q when I release R2/triangle.

But yeah, if you're not using alternative signs this is perfect

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by mika-n** [comment]
Yes. I can see how this kind of optional option in specAction/macro could be useful.

**Comment by artzox** [comment]
Since I haven't unlocked the alt signs (just started playing) can you test if the following works.
I set R2 to Q with a delay of 1200ms (could be less) before for the initial pressing. I then set R2 to work as shift modifier for the sq, circle ,x, triangle and R3 for selecting the signs (3-7). The result is that you can use the R2 albeit with a delay of 1,2 sec as a normal button, but if you want you can also select a sign and execute. What I have also set is that Q is repeated while held, hopefully working as a hold R2 for the alt sign, but not sure if this will work. Anyway I expect that some tinkering with this may achieve the end result. The idea is that you can select and execute the standard sign if you release the R2 trigger and the alt if you hold it.

@raff-run Could you test and let me know.
