### ISSUE TITLE
Crashing shortly after Starting after updating Windows 10 2004

### ISSUE THREAD

**Issue by ripps818** [Ryochan7/DS4Windows#1319]
After updating Windows 10 to 2004, DS4Windows crashes a few seconds after starting. I tried reinstalling .Net and VC++ runtimes and still doesn't start. I've tried starting several different ways (user/admin) and even a fresh install, and it still crashes.
Logs seem to indicate that "message Root element is missing".

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4734207/ds4windows_log.txt)

**Comment by ripps818** [comment]
Okay, I managed to get it start: 
1. Using a fresh install (renamed DS4Windows folder in AppData).
2. Turned off Bluetooth
3. Started DS4Windows and it wouldn't crash.
4. Turn Bluetooth back on.
5. Now it seems to work fine, and it grabs gamepads from both usb and bluetooth.

**Comment by mika-n** [comment]
Based on the logfile it seems something went wrong while reading XML configuration files (missing tags? missing file? invalid format?). But why something like this would happen after WinOS update? Weird.....  Anyway, by renaming the configuration folder DS4Windows re-created all config files and got rid of the problematic file. Could be that there is some hidden bug somewhere relating how very old XML files are upgraded to the latest DS4Windows version.

If you still have the old backup of config files then maybe you could zip it and attach here. If it crashes here then it would help to find out what is causing that issue. Could be that some other user run into the same problem is there really is a hidden bug in XML file handling.

**Comment by ripps818** [comment]
[DS4Windows.old.zip](https://github.com/Ryochan7/DS4Windows/files/4734837/DS4Windows.old.zip)

**Comment by ripps818** [comment]
The weird thing was that even after renaming the configs in AppData, it would still crash on startup until I tried starting with my bluetooth turned off.

**Comment by apoklyps3** [comment]
happened to me too.
turning off BT did nothing to fix it.
had to delete what I had and start froms scratch.
Same errors in log.

**Comment by s3rialthrill3r** [comment]
I think I have the same problem too. Running the executable brings up the DS4Windows window for a second then it disappears and the notification icon is gone as well.

**Comment by mika-n** [comment]
Do you mean that if DS4 gamepad over BT is already connected to PC when DS4Windows is started then the app crashes?
Would you please try to run the debug version and attach the logfile here because the debug version shows a lot more detailed messages about gamepad connection events.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

@ripps818  The "normal" (ie. not debug version) logfile you attached here has couple strange messages. The first thing is that you seem to have an ancient ViGemBus 1.14.x version installed. The latest version is VigEmBus 1.16.112.0 driver version. See the link list for a ViGem driver link. DS4Windows auto-updater functionality updates only the app itself, but not the WinOS kernel level VigEmBus driver.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

Another strange thing is that after the gamepad connection the gamepad seems to loose BT connection and this is why DS4Windows app thinks the gamepad is gone and tries to do "disconnect" things. Now there could be some race bug condition causing a crash, but the problem begins from the failing "write data" event (DS4Windows app not just read incoming events from the gamepad, but also write data to the gamepad. The communication link is a two-day highway, but now for some reason the writing lane fails).

DS4Windows profile has "Enable Output data to DS4" option. If you untick this one then does it work? Unticking this option disables data writing, but then lightbar and rumble doesn't work, but you might wanna try how it goes in this case.

```
2020-06-05 01:07:15.5144|INFO|Connection to ViGEmBus 1.14.3.0 established
2020-06-05 01:07:15.6204|INFO|Gamepad data write connection is lost. Disconnecting the gamepad. LastErrorCode=1167
```

**Comment by apoklyps3** [comment]
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4751531/ds4windows_log.txt)

**Comment by mika-n** [comment]
@apoklyps3  What do you have in "%APPDATA%\DS4Windows\OutputSlots.xml" file? It should contain something like this if there are no persistent gamepads assignments (ie. an empty default file content).

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Made with DS4Windows version 2.1.2 -->
<OutputSlots app_version="2.1.2" />
```

**Comment by apoklyps3** [comment]
the file you mentioned is not in appdata because I use ds4windows folder for all files for better backup.
it is in the local folder and it's this:
`<?xml version="1.0" encoding="utf-8"?>


<OutputSlots app_version="2.1.2" />`

**Comment by Ryochan7** [comment]
I just updated to Windows 10 2004 and I didn't run into a problem with DS4Windows. Looking at the code that writes the OutputSlots.xml file, the basic root element should still exist even if no permanent slots are assigned.

**Comment by apoklyps3** [comment]
it doesn't happen imediatelly.
give it a few days.
