### ISSUE TITLE
High latency

### ISSUE THREAD

**Issue by Miltrivd** [Ryochan7/DS4Windows#132]
Hello, just found this fork and went to test it immediately.

I'm getting 4 to 6 ms either wired or over BT. Normally this is 1.2 to 1.4ms over BT and 4 ms wired.

I'm using the same profiles I did with the old J2K version in case that matters. Made a new profile and repaired the controller but same issue. Under Windows 7 x64 with a second gen DS4, using DS4Windows 1.4.97 x64.

**Comment by Ryochan7** [comment]
With recent versions, the default BT poll rate is set to 4 ms. I find that output controls are slightly better when using a 4 ms poll rate rather than using the maximum rate around 1.25 ms. The input delay when using BT should not vary that much though. Also, the input delay when wired should be at an almost solid 4 ms.

There are a few tasks that you might want to try for testing. You might want to change your Power Management profile in Windows to use the High Performance profile if you are currently using the Balanced profile. In DS4Windows, try to disable any special actions that you have enabled. Also, I would recommend that you disable the Flush HID option in your profiles. That option was a bad workaround to reduce latency in the first place and better solutions are already in place.

**Comment by Miltrivd** [comment]
Thanks a lot, Power Management is custom from High Performance but removed Flush HID and changed the BT poll rate to 500Hz (missed the option on my first look) and it's extremely consistent at 2ms now, at 1000Hz it was showing a lot of variance and at 250Hz/4ms still showed enough variance that was constantly shooting to 5 ms and almost 6 ms.

Didn't want to go back to 4ms tho, since that's the reason I went from wired to wireless. It's perfect now, thanks again.

**Comment by Ryochan7** [comment]
That is weird that the connection is more stable at 2ms with your BT dongle. I have experienced varying performance differences with my two BT dongles but the main difference is one handles multiple controller connections better.
