### ISSUE TITLE
Controller is constantly disconnecting upon bluetooth connection

### ISSUE THREAD

**Issue by yuhaocooper** [Ryochan7/DS4Windows#1325]
![image](https://user-images.githubusercontent.com/22113815/83961036-fa512d80-a8c1-11ea-9d87-f3b017c17c52.png)

Is there a way to fix this?

**Comment by yuhaocooper** [comment]
[debug.wired.txt](https://github.com/Ryochan7/DS4Windows/files/4741472/debug.wired.txt)
[debug.bt.txt](https://github.com/Ryochan7/DS4Windows/files/4741473/debug.bt.txt)

I've attached the debug files of both the wired and bt connection of the controller.

**Comment by yuhaocooper** [comment]
I'm using a 3rd party controller here btw. And after reading more of the issues, I understand that the cause of this problem is that 'mode switch' that enables the other functions of a PS4 controller, in DS4Windows is failing.

I can help to rule out the possibility that the BT dongle or windows as the cause of the problem, as weirdly another same 3rd party controller that I bought is able to BT pair perfectly with my system. Thus, I can say that the most likely cause is this particular 3rd party controller itself. And so, my question is either.

1.whether I can edit the config files of DS4windows to ignore the 'mode-switch'. Normal button and stick activity is good enough for me.
2. Does anyone know of a way to update the drivers in the controller itself? or is it a hardware difference between the 2 controllers that I can't fix through software.

**Comment by mika-n** [comment]
The game presents itself as "genuine" Sony DS4 revision 1 (ie. the original first version of DS4 gamepad Sony haven't manufactured for years. Since PS4Slim was released Sony has manufactured only DS4 v2 gamepads). If you have purchased that gamepad withing the last 3-4 years then it is more than likely that the gamepad is a fake Chinese copy and not an official Sony DS4 v1 gamepad. Those fake copies often struggle with BT connections and don't behave like the real thing over BT in PC. However, at the same time USB may work just fine.

Unfortunately there is not much DS4Windows can do about this issue. Or someone who can debug the connection should investigate if the gamepad requires a bit different handshaking in BT than the real thing. Sorry, but it may be a bit too difficult to try to debug this without having an actual hardware. 

If you pair the gamepad in WinOS and try to use it WITHOUT DS4Windows then does the BT connection stay alive in that case? By default DS4 gamepad is in PC-friendly mode over BT, so ligthbar and touchpad probably don't work but other buttons should work. If the BT connection stays alive this way then "switch over to native DS4 mode in BT" is a problem and it is classical problem of fake copies.

There is one thing in the logfile you provide you should look at. The version of the installed ViGem client driver is ancient 1.14.3. The latest version of ViGem bus driver is 1.16.112.
`Connection to ViGEmBus 1.14.3.0 established`

See the link list and ViGem driver link (Note! The ViGem installer version is 1.16.116, but it will install 1.16.112 bus driver and that is the version tag seen in DS4Windows logfiles).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

**Comment by yuhaocooper** [comment]
Got it @mika-n . Thank you for the response! It is indeed one of the fake chinese copy, and I guess I'll just have to deal with it, such as getting a long micro-usb cable haha.

Just to share more information that may help in future cases: Yes, the BT connection does stay alive when it is not connected through DS4windows and when it does not try to apply the XBOX360 controller settings on it. However, because of the lack of controls mapping, it is also unusable and unrecognizable by a lot of the games.
