### ISSUE TITLE
Controller behaving differently on BT

### ISSUE THREAD

**Issue by MilosJ77** [Ryochan7/DS4Windows#1346]
Hi

I just picked up a Bluetooth USB adapter so I could go cordless.
Its working pretty fine except the touchpad is not functioning in the game I'm playing.
With cord it works fine but I switch to BT and the touchpad is still working as a mouse outside the game but not responding ingame, even though the game prompts me to use touchpad to open the map.

The lightbar also shines brighter on BT compared to cord. Its as if its using another profile, but I only have 1 profile.

The USB is 2.0 and using bluetooth v4.0.
Anyone know whats going on here?

**Comment by mika-n** [comment]
Touchpad works over USB? Hmm.... Are you sure the game is using the virtual DS4 gamepad created by DS4Windows app and ViGem driver? The fact is that the touchpad events are not supported in the current version of ViGem driver, so it doesn't work as a "native" touchpad in DS4Windows app. DS4Windows can read touchpad events, but ViGem output driver doesn't receive those events.

If you can use touchpad in a game over USB then it must be the device NOT going through DS4Windows app (ie. the native dinput DS4 device handle).

However, BT is a bit different story. WindowsOS doesn't support out of the box true DS4 mode (for example touchpad). DS4Windows switches the gamepad to true native mode, but it means that the gamepad works then only through the virtual output gamepad device. And because the ViGem virtual output gamepad doesn't support touchpad events then it is a dead end.

**Comment by MilosJ77** [comment]
Hi mika
Oh wow, yeah youre right. The controller still works without DS4. Huh, my bad.

So when you say that DS4W can read touchpad events, would that answer why I can use the touchpad (over BT) as a mouse outside of a game? Because I can move around and click stuff just fine with the touchpad.

**Comment by mika-n** [comment]
Yes

**Comment by MilosJ77** [comment]
Alright, tyvm.
