### ISSUE TITLE
Rumble not working and lightbar color settings not working

### ISSUE THREAD

**Issue by eltece** [Ryochan7/DS4Windows#1354]
I just installed DS4Windows, it's working but whenever I change the Lightbar color it won's changed (ex : Charging color set to Rainbow, but not working). I test the Rumble too and it's not working. I test by playing Forza Horizon 4 but the D-Pad not working. I already checked the "Hide DS4 Controller" option.

**Comment by eltece** [comment]
Here is the video : https://www.youtube.com/watch?v=zct7A2mVaJs

**Comment by mika-n** [comment]
Please read the pinned "Read this before posting a new issue ticket" for more what information to provide. Now your post lack all the basic information.

Also you might wanna try to run the debug version to generate more detailed logfile.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by eltece** [comment]
Here is the log file using debug version and profile I use https://mega.nz/file/cBEGVIRQ#Nn7d8xAhCanEdabB1-6GO19qVzo42fux5TIWXbvpbx8

**Comment by eltece** [comment]
I read the pinned, but the Issues I'm having is I can't use D-Pad while on game, I can't change the Lightbar color, and the Rumble doesn't work when I use Test Heavy nor Test Light. The controller it self is detected.
![image](https://user-images.githubusercontent.com/67061421/84981450-c77b2500-b15e-11ea-9e83-1c0216d2a213.png)

**Comment by mika-n** [comment]
How about usb cable connection? Is the same profile working just fine? DPad keys and rumble and lightbar?

When you test the gamepad over BT connection in JOY.CPL controlPanel WITHOUT ds4windows app running then does it register dpad key events? Do you mean that DPad keys work in every other app, but not in ForzaHorizon4?

Didn't see anything wrong in logfile or in the profile file. It works fine here.

You have DS4 revision1 gamepad. Is is 5+ years old gamepad or have you purchased it recently? Sony haven't manufactured DS4 v1 gamepads since PS4 Slim console was released. However, many stores sell cheap DS4 gamepads which pretend to be DS4 v1 gamepads (hardware ID and look-a-like), but are actually fake Chinese copies. Those often have problems in BT connection mode, but work better in USB mode. 

So, please test how the pad and the profile works over USB (lightbar,rumble). If it works then maybe you are suffering the infamous "buggy BT connection in fake copies" issue.

**Comment by eltece** [comment]
I use usb cable connection. Is the same profile and it's doesn't work from the beginning. Not only Forza but other games too. Yes the DS4 I have is copies, But all my friends using the exact same controller and they are find while using Cable and BT mode. The steam recognize it as PS4 controller but now it doesn't show as PS4 controller in game (F1 2019) anymore (it does show up as PS4 controller before). Maybe I should start from zero again by uninstalling the drivers, but I don't know what drivers it uses
![image](https://user-images.githubusercontent.com/67061421/84995898-c229d480-b176-11ea-8227-15c68c5c3d63.png) 
![image](https://user-images.githubusercontent.com/67061421/84995906-c48c2e80-b176-11ea-89ba-48e532ce78b0.png)
![image](https://user-images.githubusercontent.com/67061421/84996050-f69d9080-b176-11ea-8fa6-4824db382924.png)

**Comment by mika-n** [comment]
Aah, okey. Indeed the logfile tells that you are using USB connection. The debug logfile didn't tell there was anything wrong, so I wonder what is going on there.

What do you see in JOY.CPL controlPanel applet when DS4Windows is running? Is DPad key events recognized by JOY.CPL? Or in https://html5gamepad.com/ web page?

And do you see any L2/R2/LS/RS trigger and stick and gyro activity in ControllerReadings tab page in DS4Windows app (edit the profile via Controllers tab page and open ControllerReadings tab page in profile editor)?

**Comment by eltece** [comment]
Yup it show up and has a correct readings. What a weird issue I got. Can it caused by defect item? it's a copies controller tho, so it can be happened

**Comment by mika-n** [comment]
If all buttons and sticks and triggers are working and recognized in JOY.CPL and html5agmepad.com test app then the DS4 gamepad should be working. And DS4Windows app because the app doesn't see any differences in which app is using the virtual "xbox360 gamepad" controller device. 

Post a screenshot of JOY.CPL screen with a list of all detected gamepads when DS4Windows app is running and the gamepad connected. Do you see only the "xbox360 gamepad" device or is there also "Wireless Controller" device shown? If both of those are shown then there are problems with exclusive mode (=Hide DS4 Controller option) and this may cause weird bugs in games ("double input problem").
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by eltece** [comment]
![image](https://user-images.githubusercontent.com/67061421/85010001-84827700-b189-11ea-9939-e4f090d17eb4.png)
![image](https://user-images.githubusercontent.com/67061421/85010052-96641a00-b189-11ea-8ba4-78fd74f97978.png)

**Comment by eltece** [comment]
Oh I think I got that BT issue. My receiver just arrived. When I connect it, it constantly connecting and disconnecting.

**Comment by mika-n** [comment]
Looks like exclusive mode works just fine, so no "double input" problem. 
If the JOY.CPL controlPanel applet shows all key events (dpad and others) in Properties window then I'm turning to believe that this is a game specific issue. Or you have some special action or macro trigger defined in dpad keys and that's why those keys are not doing what you expect them to do.

However, don't know about the lightbar and rumble failure. Because the logfile doesn't show any "writeData" errors then some gamepad specific issue. Maybe. Does the rumble and lightbar work with PS4 console?

If some weird setting/profile confusion is causing these issues then try deleting everything below %APPDATA%\DS4Windows folder (files and folder below this root folder). Then the next time you start DS4Windows app it will create fresh default config files.

But, if this is a fake DS4 copy then it really could be a gamepad specific issue. Those are hit-or-miss lottery gamepads.
