### ISSUE TITLE
[Enhancement] Physical/Virtual Pad Toggle Special Action

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#1360]
Need to toggle these options without touching keyboard. Of course if user wanted to use virtual, they would have to do the special action before game start. Don't want to lose out on controller messages if games have proper controller support is why I would like to have this option.

**Comment by mika-n** [comment]
You could have different profiles and a spec action key to load a profile which has "Use DInput Only" option enabled. This option would ignore the virtual output controller and use the pad directly as a "native" dinput device.  Well, if you use HidGuardian then this won't help because HidGuardian can see changes in "hidden/visible" gamepads only at connection re-connection time.

**Comment by shinra358** [comment]
That would require keyboard usage. If i have to touch keyboard, i may as well just toggle it the normal way. I would also have to make 4 more profiles remap all buttons and lose controller rumble functionality.

Option would be called permanent physical/virtual toggle. Perm phys/virt togg for short. Pressing the special action would first turn off controllers like the special action for it does. Then it would properly toggle vpads on/off. Then user would have to turn controllers on again.

**Comment by shinra358** [comment]
And just found a game that doesnt work with the virtual pads. Turning controller on after the game is started while permanent vpads are active, beyond two souls doesn't see the controllers. But it has perfect normal controller support. Perfect reason for this feature right here.

**Comment by mika-n** [comment]
Closed because something like this can be done already using different profiles and a special action macro
- Two profiles, one with using a virtual output controller as usual (but UseDInputOnly is NOT checked). Other profile using UseDInputOnly option (checked)
- Special action macro key (bind to a gamepad button combination) to toggle between these profiles
- Or alternatively auto-profile rule to let DS4Windows to choose one of those profiles automatically based on the active foreground application.

https://github.com/Ryochan7/DS4Windows/wiki/Settings#how-to-change-a-profile-on-the-fly-via-a-certain-gamepad-button-using-a-special-action
https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules

Or if the logic is something veeery customized, but automated based on some rules then the command line interface makes it possible to change a profile or stop/start DS4Windows service from an external application or script
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options
