### ISSUE TITLE
Recommended Bluetooth Adapter on website is unlisted

### ISSUE THREAD

**Issue by Masamune3210** [Ryochan7/DS4Windows#1364]
Not a big issue, but the recommended bluetooth adapter on the website is unlisted and just leads to an error page. Is there another recommended adapter?

**Comment by mika-n** [comment]
Not really because there are zillions of brands and different adapters and the same chipset may be sold under different names on various parts of the Planet Earth. It is veeery difficult to maintain such a list (especially when people often don't even know what chipset their PC/laptop is using and don't tell that if it works or not).

**Comment by Masamune3210** [comment]
Ok, I kind of figured as such. Might want to remove the dead link from the website to remove future confusion though. What are the requirements for the DS4?

**Comment by mika-n** [comment]
The LinkList in Troubleshooting page pretty much sums it up what third party apps are required. DS4Windows installer prompts to install those if those are missing (Vigem driver, VC++ runtime libraries, MS .NET Framework etc).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

**Comment by mika-n** [comment]
it is pretty much up to the community to keep the list of working and non-working BT dongles up-to-date because developers have no way of knowing and testing all possible dongles. And people often don't tell or even know details of their BT chipset. Everyone are welcomed to update the Wiki page with their experiences with certain BT dongles.
