### ISSUE TITLE
It doesn't work anymore

### ISSUE THREAD

**Issue by Madatek** [Ryochan7/DS4Windows#1366]
So I don't know what happened but with the latest update it's broken, it keeps getting the dinput wireless controller inputs even though i disabled it from the settings.

Please someone warn me when this is fixed, uninstalling for now

**Comment by mika-n** [comment]
Log files?
Do you mean that exclusive mode is not working and a game is picking up the original "Wireless Controller" dinput device?
Or do you mean that "dualshock4" output controller type in DS4Windows app no longer work there?

Anyway. If you gave up and uninstalled the app then it is a bit difficult to help you because you are not ready to do your part (ie. testing, providing log files, screenshots, explaining more what exactly doesn't work anymore).
