### ISSUE TITLE
«Dark Souls II: SotFS» problem

### ISSUE THREAD

**Issue by nr1995** [Ryochan7/DS4Windows#1367]
So my controller doesn't work with **_Dark Souls II: Scholar of the First Sin_**.
_(yes I'm the same guy who posted the #1361 weirdness with Dark Souls Remastered,
but I've updated that to reflect new information)_
And I was reading online and people were saying that the main reason that happens with this game,
is because there are other controllers plugged in, and you have to unplug them.
There's no other controllers plugged in to my PC,
but my DS4 which is registered as a 360 pad (and has to be for this game)
is appearing in the system as “Wireless Controller”,
and simultaneously as “Controller (Xbox 360 for Windows)”.
If I run “joy.cpl” in the Run box to bring up the little Windows game controllers app,
it shows both of those, and the “wireless controller” can't be calibrated at all,
while the 360 one can be.
Is there any way to hide “Wireless Controller” from the system?
Such that there's no game that could possibly mistake your emulated controller as Player 2?

**Comment by mika-n** [comment]
Classical "double input" issue because of lazy game programmers. Take a look at this doc page for info about the topic and how to solve it (many EA games suffer from the double input issue also).
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Try "Hide DS4 Controller" option in DS4Windows and if it works in your PC setup then great. If it doesn't work (you will see a warning text in DS4Windows Logs tabpage and logfile if exclusive mode failed) then HidGuardian driver is alternative solution. It usually works even in PCs where exclusive mode (=Hide DS4 Controller option) doesn't work.

**Comment by nr1995** [comment]
Hey the “Hide DS4 Controller” option did it!
I guess I just never saw that option, because it's named exactly what I was looking for!  Thanks!
What's the benefit of having it _not_ hidden?  Why's it not default?

**Comment by mika-n** [comment]
It doesn't work in all PC environments (reasons beyond DS4Windows app itself). Also if someone would use HidGuardian then having it enabled at the same time is not necessary. Thirdly, use of that option requires administrative privileges, so DS4Windows app may show the Windows UAC prompt if admin permission is not enabled by default for the app.
