### ISSUE TITLE
Steam doesn't accept any dualshock controller if detects ds4windows.exe running

### ISSUE THREAD

**Issue by jpedro-f** [Ryochan7/DS4Windows#1373]
So in the latest update i found out that Steam doesn't accept any dualshock controller if detects ds4windows.exe running, which sucks because I cant play with my two controllers (DS4 and DS3(Shibari)) and still getting dualhock 4 prompts in compatible games. A work arround is to build DS4Windows with another name but I get double input beacause, "hide ds4 controller" doesn´t work well, a solution may be changing the name of this program, but it is just a matter of time until Steam patches it again, or create an option to spoof the name to a new name with a random character generator.

 I tried an AutoProfile on Steam which turn off ds4windows, so big picture mode only detect the directinput from bluetooth, but when I run any games and want to pop up de steam in-game overlay but the double input comesback (this with my different named build)

**Comment by Ryusennin** [comment]
I strongly suggest you disable Steam Input for all controllers (PS4, X360). Problem solved.

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

And if exclusive mode (=Hide DS4 Controller) option doesn't work in some PC environment then HidGuardian as an alternative solution should work.
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer

**Comment by reyaz006** [comment]
@mika-n can you take a look at my issue described in the latest comment here? https://github.com/Ryochan7/DS4Windows/issues/874#issuecomment-646865740
I'm not sure if I should install a new driver at all, and it doesn't seem like DS4W has any issues using exclusive mode.

**Comment by Ryochan7** [comment]
I have finally encountered this problem myself. Streets of Rage 4 absolutely refuses to detect DS4 controllers if it detects DS4Windows.exe running; the game will even refuse to read real DS4 controllers even while DS4Windows is stopped. It seems like the game **does not** use the SCAPI but implements the block on its own. The main way around the problem is to rename DS4Windows.exe to something else (whyme_DS4Windows.exe). The game will accept virtual and real DS4 devices after that while DS4Windows is running.

Especially now that it is confirmed that games are implementing the block on their own, this issue is relevant to me. I cannot just choose an alt file name and bundle it as game devs will likely just add that to the blacklist as well.

Sid Vicious Why Me?
https://www.youtube.com/watch?v=BN9fHMY76io

**Comment by Ryochan7** [comment]
I wonder if the game blocks InputMapper as well; the Steam mapper does enforce the block for that app. I don't have InputMapper 1.7 installed now. I will install it and test that out later.

**Comment by Ryochan7** [comment]
I just tested it and Streets of Rage 4 blocks InputMapper 1.7 as well. An executable rename for InputMapper is needed so the app can be usable with Streets of Rage 4.

**Comment by Ryochan7** [comment]
I don't know if I have to go completely nuts and assign a unique GUID to the filename but I think it would be best to remove the DS4Windows portion from the filename for an alt build. One fun way to randomize the filename would be to use something similar to the Words1000.TXT file used by Terry Davis' God's Word script.

https://glot.io/snippets/emkcfc01jp

Unfortunately, it would probably be better to store the alt filename in a separate file from Profiles.xml since the file will have to be read by both DS4Windows and DS4Updater.

**Comment by Ryochan7** [comment]
Finally got around to changing the Run as Task portion to allow this to work. DS4Windows will now write out the used task.bat file and link to the appropriate exe filename rather than having DS4Windows.exe hard coded. A minor consequence of this change is that a task.bat file will no longer be bundled in the DS4Windows archive files.

**Comment by Ryochan7** [comment]
Fixed an issue with the Updater failing to copy DS4Windows.exe to the custom destination. The changes for DS4Updater seem to be complete. It looks like this long standing issue will finally be stamped out in DS4Windows version 2.1.6. This workaround should not have been necessary to begin with but whatever.

For the record, Streets of Rage 2 > Streets of Rage 4.

**Comment by Ryochan7** [comment]
Version 2.1.6 now has a workaround to the main issue. DS4Updater version 1.4.3 and later will copy DS4Windows.exe and DS4Windows.exe.config to the specified destination if one has been made. There might be a reason for me to use this in the future but I hope not.
