### ISSUE TITLE
Right Joystick Constant Movement

### ISSUE THREAD

**Issue by NightsCreed** [Ryochan7/DS4Windows#1377]
Not really a coder or anything but decided to download this version of DS4Windows after my old version from Jay2Kings stopped connecting all together.  Already an improvement on connectivity, but I get into games such as rocket league where my right joystick controls camera movement and there's a constant shift where there wasn't one before.  Same controller as what I was using on the older versions so it shouldn't be a controller shift....any ideas?

**Comment by Ryochan7** [comment]
Pretty sure the problem is a lack of dead zone on LS and RS. Make sure to set it around 0.08 - 0.10.

**Comment by Softy590** [comment]
Bruh I almost destroyed my right & left sticks because I thought they were broken, I also have used the old version but very quickly changed to the new version because of connectivity issues. Haha! I was gonna open my controller tomorrow but luckily I found this GitHub issues page in time. Thanks man!
