### ISSUE TITLE
[Enhancement] Maybe add a command line option to get a controller's current profile

### ISSUE THREAD

**Issue by NiamiTV** [Ryochan7/DS4Windows#1390]
Possibly add a command line option to check a controllers current profile as we can already set a controller's profile.

**Comment by mika-n** [comment]
Yes, I can see how this could be useful in some scenarios where an external app or script is used to do some fancy profile things.
Out of curiosity what kind of use-case scenario you have needing this kind of logic?

This command may sound trivial to do at first, but it actually isn't. The question is how to provide the "answer" to the calling external app or script? 

- As a result of WinOS cmdline return code? It supports only numerical return values. The number should somehow correlate to a profile number and controller number. Controllers do have a number (slot#), but profiles don't have any numerical ID (unless those are named with a trailing number tag and the result would take that number).

- Or as a result of command output in a console? This supports strings, but the calling script should then parse the result from the console output. WinOS cmd/bat scripts can do that.

- Or as a result of temporary file where the result (controller# and profile name) is written to? Calling cmdline would provide the name of the temporary filename where this result is written to?

- Real API library interface for thirdparty apps? Not gonna happen anytime soon.

**Comment by NiamiTV** [comment]
Sorry for lack of any detail. I was thinking it could just return a string of the profile's exact name. My use-case for this would be: In my program I could get the controller's current profile and then duplicate it temporarily for use with my program so I could change settings, such as the lightbar, and then when the program is shutdown I could revert the profile to the original so it's 'seamless' in a way.

**Comment by mika-n** [comment]
I'll try to look into this at some point. The cmdline interface would print out the name of the existing profile and it would be up to the calling process to read and parse the output string.

**Comment by NiamiTV** [comment]
Alright, thanks.

**Comment by mika-n** [comment]
There is now new feature in DS4Windows command line interface. It supports querying various profile and app properties.

Here is the list of currently supported properties (I guess pretty self-explanatory property names):

```
Syntax: -command Query.device#.propertyName
- device# =1..4 slot number
- propertyName = one of the following identifiers

- DS4WindowsCmd.exe -command Query.1.ProfileName
- DS4WindowsCmd.exe -command Query.1.OutContType
- DS4WindowsCmd.exe -command Query.1.ActiveOutDevType
- DS4WindowsCmd.exe -command Query.1.UseDInputOnly
- DS4WindowsCmd.exe -command Query.1.DeviceVIDPID
- DS4WindowsCmd.exe -command Query.1.DevicePath
- DS4WindowsCmd.exe -command Query.1.MacAddress
- DS4WindowsCmd.exe -command Query.1.DisplayName
- DS4WindowsCmd.exe -command Query.1.ConnType
- DS4WindowsCmd.exe -command Query.1.ExclusiveStatus
- DS4WindowsCmd.exe -command Query.1.AppRunning
```

The result will be a string value or if boolean attribute then true/false string and the errorlevel of DS4WindowsCmd.exe is 0/1 as true/false value.

Note! DS4WindowsCmd.exe tool is additional optional command line interface tool. It can be downloaded from here: https://github.com/mika-n/DS4WindowsCmd

The cmd tool is not yet bundled with the official DS4Windows zip package. These same command line options do work with the original DS4Windows.exe also, but because it is a GUI app then it may be a bit trickier to integrate with Windows batch files. DS4WindowsCmd.exe tool is a console application, so it integrates better with Windows batch files. More info on the DS4WindowsCmd web page.

NOTE! This new Query cmdline option support is not yet published, but keep eye on the DS4Windows releases. The next official version should have the support.
