### ISSUE TITLE
Touchpad loses input when closing certain windows

### ISSUE THREAD

**Issue by Delmay441** [Ryochan7/DS4Windows#1391]
When wirelessly using the touchpad as a mouse, when I x-out of different program windows (Firefox, Discord, Steam, file explorer) my touchpad completely loses mouse control and I have to wiggle my actual mouse slightly to return it. I want to use the touchpad for couch gaming and it is very self defeating to constantly have to get up and manually move my mouse at my desktop. I can't seem to get it to consistently behave or act incorrectly either so I have no idea what could be causing the issue. I have tried completely removing the program and all associated programs several times with no luck.

**Comment by mika-n** [comment]
Hmmm.. DS4Windows app should not have such effect. Do you use auto-profile options in DS4Windows to choose profiles automatically based on foreground process and/or window? If you are then are you sure the profile is not changed? 

Anyway. DS4Windows app "simulates" mouse movement events and could be that even when the feature works then maybe those mouse movement messages end up to some invisible window and not to the forecground wnd? Well, this is just a wild guess because I have never heard such problem you described, so I'm not sure what theoretical theory could even cause something like that.

**Comment by Ryochan7** [comment]
I'm going to assume that it is a UAC security issue. That is the typical cause. The easiest way to address that problem is to run DS4Windows as the Administrator.
