### ISSUE TITLE
Any chance of simple turbo / autofire?

### ISSUE THREAD

**Issue by daninthemix** [Ryochan7/DS4Windows#1403]
We just need a simple checkbox on each input that is like Steam: 'hold to repeat'. That's all.

Macros don't cut it. This is simple, beneficial functionality.

**Comment by mika-n** [comment]
It is always a trade off between power-user vs casual-user functionality.  The compromise would be to provide a sample macro template with auto-fire settings. Then it would be just a matter of using "Load macro" feature (special actions/macro has a template feature already).

**Comment by mika-n** [comment]
Closed as "not going to be implemented in near future" because autofire/turbofire type of functionality is already available even when it is not "one click configuration". There are instructions how to do it via a macro.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#how-to-do-auto-fire-type-of-trigger-button-using-a-special-action
