### ISSUE TITLE
Crash when editing profile

### ISSUE THREAD

**Issue by frubo** [Ryochan7/DS4Windows#1405]
Yesterday DS4Windows started crashing whenever I try to create or edit a profile. Otherwise, it seems to still work fine. I'm on W10 2004 and using a genuine DS4v2.

I've tried a clean install of DS4Windows and using older releases; only the latest non-WPF version doesn't crash when creating/editing profiles. I also ran DISM and SFC.

Thanks.

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4941758/ds4windows_log.txt)

**Comment by mika-n** [comment]
Did you try to clean up existing config and profile files in %APPDATA%\DS4Windows\ folder?
I have seen cases where corrupted config files have caused something like this.

Please zip all config and profile files, delete all files and folders below DS4Windows folder and try to launch the DS4Windows. It will create new default config and profile files. Does it work in this case?

If it works then something strange in old config/profile files. Please attach the backup zip file here for closer inspection because DS4Window app should not crash even when some config/profile file has some weird values. It is difficult to debug this issue without having a test case.

**Comment by frubo** [comment]
> Did you try to clean up existing config and profile files in %APPDATA%\DS4Windows\ folder?
> [...] delete all files and folders below DS4Windows folder and try to launch the DS4Windows. It will create new default config and profile files. Does it work in this case?

First thing I tried was cleaning everything and doing a fresh install. It still crashes when I edit the default profile or try to create a new profile, always with a System.NullReferenceException.

I also tried creating a new user account and doing a fresh DS4W install, but it still crashes in the same way.

Since the non-WPF version works, could it be something with my system? I ran DISM and SFC but they found no problems.

Thank you for your support, mika-n.

**Comment by mika-n** [comment]
The exception is probably coming from this code line, but why?  I don't know because this is something which has been there "forever" and why it worked in your PC before but not anymore?  Maybe some permission issue. Have you installed DS4Windows app into c:\program files (or x86 version of it) folder? Try installing to c:\games\ or whatever custom folder because some WinOS setups have extra security tweaks in c:\program files\ folder if the app is not installed via "normal" Win installer app (and registered to a system).

```
ImageSourceConverter sourceConverter = new ImageSourceConverter();
ImageSource temp = sourceConverter. ConvertFromString("pack://application:,,,/DS4Windows;component/Resources/rainbowCCrop.png") as ImageSource;
```
https://docs.microsoft.com/en-us/dotnet/framework/wpf/app-development/pack-uris-in-wpf

The above shown code line tries to read the PNG file from DS4Windows executable file (embedded resource). But this is not new thing in DS4Windows app, so something in your PC/WinOS is now interfering. Virus scanner maybe blocking DS4Windows.exe app to access its own resources?

**Comment by frubo** [comment]
Closing this issue; I reinstalled Windows.
