### ISSUE TITLE
shared acess

### ISSUE THREAD

**Issue by andersonbruno02** [Ryochan7/DS4Windows#1406]
what is that? when i look at website it shows like a check mark
but mine shows like a X.
everything its working like a charm only wanna know what is that

**Comment by mika-n** [comment]
See the "exclusive mode" doc page. Shared Mode and Exclusive Mode are the opposite cases. The following page explains why many games require exclusive mode (ie. those games have "double input" problems if the physical ds4 gamepad device is used in shared mode both by DS4Windows app and directly by the game). Exclusive mode solves these problems because the physical gamepad is visible only for DS4Windows app (ie. the use of physical ds4 gamepad device is no longer shared).
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Exclusive mode (=Hide DS4 Controller -option in DS4Windows app) and HidGuardian driver tool are ALTERNATIVE ways to achieve the "exclusive use of phystical gamepad device" thing. In some PCs the HideDS4Controller option doesn't work because of reasons beyond DS4Windows app. In that case HidGuardian usually solves that because it should work in all PCs and software setups).

**Comment by andersonbruno02** [comment]
thank you! its good to know about that
