### ISSUE TITLE
Special Action - stick issues

### ISSUE THREAD

**Issue by Yohoki** [Ryochan7/DS4Windows#1408]
I've started making a profile for a game (Planet Zoo) and the camera is currently being a nightmare. The game devs only allow a button press+Mouse movement combo for rotating the camera. Normal macros don't seem to allow for mouse movement recording, so I've set up a special action.

It's currently set to any direction on the right stick will press the single quote key ( ' ) as a "Special Action" and the right stick is set as mouse controls in the normal mapping area. This works as expected, touching the right stick will move the mouse while holding the quote key. But, this brings up 2 issues.

Firstly, there's no mouse button options in the Special Actions menu that pops up to select which key to press. Not entirely important, but would be nice to have.

Secondly, and more importantly, the special action only seems to activate when the stick is fully tilted. If you slightly move the stick it just moves the mouse with out holding the quote key. It looks like the special action isn't activated until the stick is almost fully tilted.

**Comment by mika-n** [comment]
"Record a macro" screen in specActions does have mouse button support (mouse btn left/right/middle and a special btn keys to record 4th and 5th mouse btn events). To record left/right/middle mouse btn events you can simply press those mouse buttons while recording.

The second part of your question was about having both the "use stick as mouse" functionality at the same time with specAction event to send a kbd key event while the stick is moved. Yes, it is a bit "undefined" what will happen when two separate mapping rules are bind to the same stick or button. Or more exactly timing between these events is undefined or those events may override each other (so it seems that the other event was never fired).  With LS/RS sticks deadzone value plays a role here. Depending on how and what you do you may need to tweak LS/RS deadzone to avoid "double feeding" events. But in your case would want to do this "double feeding" to happen at the same time... Well, having two separate mapping rules in the same key or analog axis may be a bit difficult to get working because of timing issues those different rules are fired away (the order of events is not quranteed unless you use two specActions with "synchronized run" option).

![DS4Win_MacroRecorderMouseBtn](https://user-images.githubusercontent.com/35538525/87929881-d02d8680-ca8f-11ea-8bbb-e811635cb36f.png)

**Comment by Yohoki** [comment]
ah. I see. I'm talking about the "press/toggle key" option. If recording a macro had mouse movement, I would have used that, but it also does not, it seems. IIRC, Ryochan7 mentioned that the macro part of the program was leftover from Jays2Kings' version and would require gutting to improve on. So, I'm really not worried about that part too much. Would it be nice to see the macro a bit more powerful, sure. Do I think it's going to be a major focus anytime soon? No. I think he also mentioned he doesn't even use macros. XD
![image](https://user-images.githubusercontent.com/44595371/87970911-1bdd3180-ca8a-11ea-99ce-c72cb4ed3d17.png)
![image](https://user-images.githubusercontent.com/44595371/87970835-f2240a80-ca89-11ea-83a3-8bcad5ba1206.png)

The second part is more of what I'm having an issue with, though. You mentioned timings being an issue, but they seem to be timed fine. If I hold the stick fully tilted, they immediately cooperate together. I can fully tilt the stick around in circles and the screen responds normally as you'd expect. But, if I tilt the stick halfway in any direction, I am able to fully control the mouse indefinitly without the special action being triggered.

Deadzone doesn't seem to be an issue, as the mouse can be moved without it triggering. if it was ignoring deadzone, I'd expect the special action to be triggered as soon as the stick is tilted, and then mouse control is triggered whenever the stick is tilted past the deadzone line. There shouldn't be a case where ignoring deadzone would cause the special action to trigger after the normal action.

Although, now that I think about it, maybe deadzone isn't even accounted for. Could it be that the Special action only checks if tilt is at 255, instead of checking if tilt > Deadzone?

**Comment by Ryochan7** [comment]
The Special Action triggers have fixed dead zones for the analog axes. The values specified in the profile do not affect Special Actions. I don't remember but I would assume that values for stick directions would have to be at least 50% in order for the Special Action to actually fire.

My focus has mainly been improving the experience of basic XInput mapping. Some of the limitations of the mapping system make some games inaccessible; Torchlight 2 and Elder Scrolls 4 are two examples that affect me. As it is, there are other problems that I would rather tackle than to try to retrofit some major mapping changes to the DS4Windows code base.

I am wanting to think that I looked at changing the Press Key Special Action at some point to allow Mouse Buttons. There might have been a real reason for the limitation but I cannot remember what it would have been.

**Comment by Yohoki** [comment]
That all makes sense. I wouldn't want you to make major changes that break other things. I DS4Win daily so that'd be a big issue if everything broke. XD

I did some testing with notepad and special actions while looking at the controller readings. It looks like the Special Action activates at ~59 and ~195 (max is 0 on left and 255 on right). Those are roughly 50%, so that assumption looks right. I assume it's specifically set at these positions to activate whenever the stick is within a cone, allowing it to activate at a full tilt of the stick in any direction this is roughly in the right direction, including diagonally. It's quite a generous cone, though and even tilting it ~50-60 degrees off still activates it.

There's a bit of wiggle room there, I'm guessing, for people who want to do something like having an action assigned to each cardinal direction, as well as distinct actions that only happen at the diagonals such as requiring LS Up and LS Right at the same time... If that deadzone was changed, then the diagonals would take over the cone in those specific cases (or become more difficult to hit).... So, I guess it's a matter of balance, in this case.... can't really change anything here without affecting another part of it, because of the way it's currently coded.

That's a shame, but it's part of the issue with working with some one else's code, right? I'm starting to understand this on my own project. XD
