### ISSUE TITLE
Changing controller type causes crash on startup

### ISSUE THREAD

**Issue by ReadyP1ayerTwo** [Ryochan7/DS4Windows#1418]
If i change the controller type from Xbox 360 to DualShock 4, DS4 Windows crashes, And when i try to start it back up it won't respond and it will force close.

A Solution to this for now until it is fixed is to go to your saved profile, which should be located in C:\Users\yourusername\AppData\Roaming\DS4Windows\Profiles

 edit your profile with notepad, and go down and change this line from DS4 to X360

  OutputContDevice DS4 OutputContDevice

**Comment by Ryochan7** [comment]
Somewhat unfortunately, it works fine for me with version 2.1.4.

**Comment by mika-n** [comment]
Anything in the latest "%APPDATA%\ds4windows\log" logfile?

**Comment by ReadyP1ayerTwo** [comment]
[ds4windows_log_20200726.1.txt](https://github.com/Ryochan7/DS4Windows/files/4982021/ds4windows_log_20200726.1.txt)
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/4982022/ds4windows_log.txt)
[ds4windows_log_20200726.0.txt](https://github.com/Ryochan7/DS4Windows/files/4982023/ds4windows_log_20200726.0.txt)
All 3 of these say something about an xbox 360 controller, and these files were created around the time i was having the issue so i figured i should send all three

**Comment by mika-n** [comment]
I guess you were using V2.0.4 version at first because the oldest logfile (2020-07-26) shows this version tag. Other two are V2.1.4.

The gamepad connection seems to be USB, but still DS4Windows app complains about latency issues. I have hardly ever heard that USB connection would have latency issues (BT connection may have those depending on the "BT radio" quality). Try using different USB ports or cable or don't use un-powered USB hub (if you happen to use one). Anyway, to me this looks like USB connection issue.

**Comment by ReadyP1ayerTwo** [comment]
This crash happened on the latest version. Also as far as latency, i can't really tell a difference. I have had latency problems with my controller in the past and i've fixed it quite some time ago, so i know what it feels like. sometimes i think it just false positives as there being some sort of latency, maybe it's just not high enough latency to actually make a difference, but i will definitely try plugging my controller into another port and see if that fixes the latency problem!

**Comment by mika-n** [comment]
closed as "hopefully the crash at startup issue is gone now after other fixes in DS4windows"
