### ISSUE TITLE
Alignment Issues Return

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#142]
![ali](https://user-images.githubusercontent.com/3978291/32406419-81282470-c14e-11e7-8d05-b7452981df57.png)

**Comment by TristanYoung** [comment]
Enhance:  Save position and size of window.

Currently DS4Windows won't open to the size I prefer, which is the same size as the profile editing tab requires.  Every time I restart my system and decide to open DS4Windows, I have to resize the window.

**Comment by shinra358** [comment]
This was a thing that was fixed a long time ago but something must have gotten messed up in a few of the last past updates because I didn't have this problem before a few updates back.

**Comment by Ryochan7** [comment]
The latest window size problem is probably due to the extra column added for Link Profile. I have changed the sizing properties of the columns and changed the minimum window size allowed. It seems to be rendering fine. If nothing else, the window should not get to the point where labels get squished like that again.

As for saving the window size, DS4Windows already does that but I have seen it not work at times. Every once in a while, the window will be at the display size without being marked as maximized. I cannot remember when I encountered that last time but it hasn't been that long. Saving the last window position is not something that I would worry about.

**Comment by Ryochan7** [comment]
I guess saving the last window position would be helpful. I will look into implementing that.

**Comment by TristanYoung** [comment]
Thank you for addressing/considering the last window positioning/sizing issue.

**Comment by shinra358** [comment]
DS4Windows_1.4.91_x64 doesn't have this problem

**Comment by Ryochan7** [comment]
Hopefully the latest release fixes this problem for everyone.
