### ISSUE TITLE
[Feature Request] Specifically intercept original input for buttons used in Special Actions

### ISSUE THREAD

**Issue by bigorados** [Ryochan7/DS4Windows#1430]
So, i don't know how hard this could be to implement but, when you create special actions and press the buttons for them, the original button function still applies, so let's say i have a game where X is jump and i map a special action to a quick consumable shortcut that can be accessed on keyboard to L1+X, what happens now is that if you press L1+X your character would still jump, of course it could be said most of this stuff is supposed to be made within game logic, with the game inputs, but it would be awesome to have control over that outside of the game. and i'll add that only the buttons at work should be intercepted, cuz let's you are moving with your analog stick and doing a quick action, if all the inputs got intercepted when doing special actions you would stop moving.
I really love the program, Keep up the good work

**Comment by Ryochan7** [comment]
This might break some people's usage of Special Actions in DS4Windows. The two have always been set up as independent systems and conflicts like that would have to be resolved at the profile mapping layer. In theory, resetting inputs after executing a Special Action would probably be fairly easy to pull off.

**Comment by bigorados** [comment]
OMG, I just noticed there is this functionality in the normal input binding window,I'm sorry for not noticing it earlier, but still there is one thing I noticed that it doesn't support, the "Shift Modifier" box does do this the way i imagined it ideal, you get a orignal button input and when you go to the shift modifier option you get another functionality that indeed intercepts the original binding, but there is only 1 "Shift Modifier" So i can't get X to be thing1, L1+X to be thing2, and R1+X to be thing3 for example, of course all of those behaving separate from each other (this part seem to be done though).
I would say for there to be more Shift Modifier layers if possible

**Comment by DoganM95** [comment]
I am currently wondering too, how to cancel the function of a button used in a macro and just execute the specified comibation.

I recorded a macro (R2 down, R2 up, wait 10ms), assigned it to R1 but it doesn't work. Tried assigning it to (L2 + R1), still nothing. 

Maybe a checkbox with an option to cancel the original function of a button for the specified macro would solve this issue.

**Comment by bigorados** [comment]
I just stumbled across the "Load a profile" special action, and that seems to do the trick, it does intercept the original button binding, so you can set PS button to be an load a profile while held and have a whole new layer of face buttons, but it still doesn't tackle one minor gripe that i have, which is being able to have a button do thing1 while quicly tapping it and do the profile change while holding it, i tried the "Multi action button" special action and it just allows the results to be macros, if one of the results could be "Load a profile" we would be set

**Comment by Corgano** [comment]
The issue in the OP is one I share. In it's current implementation, the fact that special action buttons completely breaks the flexibility of using key combos to perform any special action. 

For instance, if I want to press {square} + {cross} to make the output 360 rapidfire [A], the only possible output i can get out of ds4windows is the xbox 360 controller pressing [A] WHILE also holding [x] on the output. 
This issue is twice compounded - a macro that presses and releases [A] ALSO has to contend with {cross} being held, giving VERY inconsistent results. 
Setting such a {square}+{cross} combo to a macro of "[A] button released" on loop is more consistent but EXTREMELY unintuitive - The macro triggered by any other means (ex holding triangle) would do basically nothing as expected, but only works at all because of the currently broken behavior.
Finally if someone INTENDED to get this effect, they could still 100% get it intentionally if given the chance. {square}+{cross} -> macro([X] button down, [A] button down, [A] button up, repeat on).

The current behavior severely limits the usefulness of the macros / special actions. Either A. not passing through special action trigger keys, or B. giving us a toggle whether to pass them through or not, **are both far easier to workaround to get the current (old) behavior than trying to work around the current behavior** to simulate not passing through the special action keys. Changing the behavior, although it might break some workflows, will open a LOT of new and much easier options going forward.
