### ISSUE TITLE
DS4W has to be re-added to HidNinja whitelist after every restart

### ISSUE THREAD

**Issue by rcostanza** [Ryochan7/DS4Windows#1437]
I don't know at what point it started, but for a while now I have to manually add DS4W to HidNinja's whitelist after every app restart, otherwise it'll block it from accessing the whitelisted devices. The apps' PIDs are persisted to the registry, but removed after a restart & refresh.

The device whitelist still works normally.

(sorry to post this here, not sure if the HidNinja repository at gitlab is the right one or if you're watching issues there)

**Comment by mika-n** [comment]
DS4Windows.exe app uses the HidGuardHelper.exe app to add the current runtime process ID (PID) to the HidGuardian sysreg whitelist. Do you have HidGuardHelper.exe app in the same folder with DS4Windows.exe app?

What happens when you run the HidGuardHelper.exe app manually from a cmd shell (cmd.exe shell)? Does it dump out any .NET error messages (it may prompt for UAC Windows permission dialog because HidG sysreg editing is allowed only from processes with elevated privileges)? By default it should not show any messages. Internally DS4Windows.exe calls this HidGuardHelper.exe app with a command line parameter (=the current PID process ID number of DS4Windows app).

HidGuardHelper.exe app takes care of removing the DS4Windows PID from the whitelist list when DS4Windows.exe app is shutdown because PID values are different each time DS4Windows.exe app is launched. It should not be left behind because the next time time PID may belong to a completely different app.

**Comment by rcostanza** [comment]
> Do you have HidGuardHelper.exe app in the same folder with DS4Windows.exe app?
> What happens when you run the HidGuardHelper.exe app manually from a cmd shell (cmd.exe shell)?

Yes. No error messages, neither on console or the event log (at least system/application ones). Running it while passing the current PID works like you said.

Not sure if it's a clue, but I have DS4Windows set to run as admin so I get the UAC prompt when it starts so that covers the elevation needed for the helper. But if I set it to run normally (non-admin), I'm never prompted until I try to open the helper through the link in the Settings panel. So I guess it's not being called to register the PID at the start?

[Logs](https://pastebin.com/GYBMGLMm) from just opening the app without any interaction, just in case. Doesn't seem to have anything special.

**Comment by mika-n** [comment]
`2020-08-14 11:19:51.2517|INFO|Using Exclusive Mode`
The logfile shows "Using Exclusive Mode" text. I guess you have enabled the "Hide DS4 Controller" option in DS4Windows settings?  Usually it is not needed to enable both "Hide DS4 Controller" option and to use HidGuardian tool to hide the original gamepad device. But it shouldn't hurt anything to have both HideDS4Controller option enabled and using HidG driver.

Anyway, the most striking thing is not what is in the logfile but what is missing in the file.  DS4Windows should show a  "HidGuardian in use. Launching HidGuardHelper" message when the app detects HidG driver and calls the HidGuardHelper tool to whitelist the process PID in HidG settings. 

Hmm... Do you see the "HidGuardian in use" message if you untick the "Hide DS4 Controller" option (=built-in exclusive mode)? 
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

DS4Windows app queries WinOS device driver repository to find out if HidGuardian is installed and AffectedDevices hidg sysreg entry lists the game device identifier. If this "HidGuardian in use" msg is missing then either option1 AffectedDevices hidg sysreg entry doesn't list your gamepad device identifier or option2 hidg driver itself is broken.

Option1: What is the device path of your gamepad? Is it listed in AffectedDevices hidg sysreg list? HidNinja tool is the easiest way to check this. If DS4Windows app is running in the background and the gamepad is detected by DS4Windows app then the following command line dumps out the device path into result.txt text file: _ds4windows.exe -command Query.1.DevicePath > result.txt_
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options

Option2: There has been cases in the past where HidGuardian driver stops working after major WinOS updates. Easiest way to solve this is to re-install HidGuardian driver to re-setup its internal driver registrations.

**Comment by rcostanza** [comment]
Reinstalling HidGuardian through the test installer fixed it. I didn't think of doing it since it was still working and blocking device access from apps outside the whitelist.

(As an aside, unrelated to this issue, the command line to query the device didn't work. I tried multiple properties, all returned empty results. Other commands, like start/stop and changing profiles, did work.)

**Comment by mika-n** [comment]
Good that things work again. 
Here the cmd `DS4Windows.exe -command Query.1.DevicePath > result.txt` does seem to work (just tested it). The first argument -command needs to be in lowercase letters. Well, if you don't need these cmdlines then not a major issue, but it is a bit strange why it works here but not there.

**Comment by rcostanza** [comment]
Yeah, I copied verbatim from your comment and then again from the wiki page, no dice.

```C:\DS4Windows>DS4Windows.exe -command Query.1.DevicePath
C:\DS4Windows>```

Dumping the output to a file, it would be empty as well. The controller is connected and working, I can even switch its profile with `LoadProfile.1.<profile>`.

**Comment by mika-n** [comment]
I'm lost why the cmdline Query doesn't work there.  
However, it is a fact that the standard "DS4Windows.exe" requires the "> result.txt" redirection as shown in my earlier posts because ds4windows.exe is a WinOS GUI app and those don't have console output at all. The output result should be therefore re-directed into a text file. The command line Wiki doc page explained this issue and listed an optional solution if console output is needed in WinOS batch files (ie. optional DS4WindowsCmd.exe additional tool).
