### ISSUE TITLE
[Feature Request] Vertical scale modifier for the analog sticks.

### ISSUE THREAD

**Issue by SwizzBiz** [Ryochan7/DS4Windows#1445]
Similar to how the vertical scale works for the gyro mouse option. should be helpful to keep stick output roundness when you don't want to mess with FOV ingame.

**Comment by Ryochan7** [comment]
This does not sound like a good idea. Maybe the closest that something like this would be implemented would be when cross dead zone becomes a thing and dead zone (and possibly other properties) can be set per axis.

**Comment by Ryochan7** [comment]
Cross dead zone is now a thing but it probably would not solve the original problem here. Again, I am just failing to see a direct use case for this when dealing with analog stick output. It might make sense when using RS to emulate the mouse. I am not sure I would use it so that would likely still keep me from implementing it.

**Comment by Ryochan7** [comment]
The feature was easy to implement. The question still remains about whether it was worth adding.

**Comment by Ryochan7** [comment]
The feature is available in version 2.2.14.

https://github.com/Ryochan7/DS4Windows/releases/tag/v2.2.14
