### ISSUE TITLE
Request: add option to disable windows notifications

### ISSUE THREAD

**Issue by RobertoBiundo** [Ryochan7/DS4Windows#1446]
Request 

Can we have an option to disable the windows notifications ("ds4 windows controller disconnected") and others

They don't show while playing full screen games anyway since windows auto enables the do not disturb. And since I have an auto turn off controller en 5 min they can be anoying g when the controller disconnects after I finished playing and started doing something else.

Maybe keep error messages but disable the informational ones?

**Comment by mika-n** [comment]
You can disable toolbar notifications in Win10 settings ( Settings / Notifications and disable DS4Windows process capability to show those bottom right corner popup notifications).

**Comment by RobertoBiundo** [comment]
Yes but do you have error notifications? Since this would also be
suppressed right?

**Comment by mika-n** [comment]
Yes. That Win10 setting would disable all notifications, but in practice there are only couple error notification scenarios and when things have been setup correctly then you probably never see those messages (ie. gamepad connection is compatible with PC and DS4Windows app, VigEm driver is working OK and exclusiveMode/HidGuardian setup OK).  I would not worry about not seeing those error messages because in the end you would see the result by having a non-functioning gamepad anyway. I tells you anyway that something is wrong and then you can take a look at the logfile for more details.

**Comment by RobertoBiundo** [comment]
Ok then...then no need for the option. I'll disable it through windows :)

**Comment by Ryochan7** [comment]
You can just change the **Show Notifications** setting in DS4Windows to **Warnings only**. That will suppress many possible notification messages including the Idle Disconnect message that you do not want to appear.

**Comment by RobertoBiundo** [comment]
Ah...nice....great job !. Works like a charm
