### ISSUE TITLE
Request: show battery level in connection notification

### ISSUE THREAD

**Issue by teeedubb** [Ryochan7/DS4Windows#1451]
Hi,

A feature request which I think would add value to DS4windows - showing the battery level in the windows notification that pops up in the bottom right corner of the screen when a controller is connected.

Thanks.

**Comment by mika-n** [comment]
Simple, but excellent idea. But the implementation is not that simple because the part of the code which shows this "Controller 1 using Default profile" connection message is shown BEFORE DS4Windows app has actually read the battery level (and other events) from the DS4 gamepad. So, this seemingly simple change does require a little bit of more work but the extra work may be worth it because I'm sure lot of users might find if useful. 

Meanwhile you could define a specialAction "check battery level" and bind it to some key combination. By pressing this trigger key DS4Windows will check the battery level and show it as a popup notification message.

**Comment by teeedubb** [comment]
Thanks for the special action info. I have the lightbar setup for flash at 20% battery, so it's no big deal, but I thought it would be handy to have that info when first connected so I thought I'd share it here 🙂

Also thanks for your continued work on DS4windows 👍

**Comment by teeedubb** [comment]
Wow thank you very much!

**Comment by teeedubb** [comment]
New notification looks very good - thanks!
