### ISSUE TITLE
When I connect the controller the mouse click moves crazy in folders 

### ISSUE THREAD

**Issue by IceChevalier** [Ryochan7/DS4Windows#1453]
I dont know why, but when I plug the Ds4 the mouse go to the top alone and moves like crazy. 

Thanks

**Comment by IceChevalier** [comment]
Fixed. Have to Delete de profile folder in your Windows AppData Location. Lovely.

**Comment by Ryochan7** [comment]
Pretty sure this issue has been fixed in the code. I stumbled across it myself while adding the 1 Euro filter options. The root problem is when the virtual mouse routines (Gyro and possible Touchpad) are run when there is a 0 for elapsed duration. One Not a Number instance can ruin some buffers (smoothing or trackball) and screw up the virtual mouse until the controller is unplugged.

https://github.com/Ryochan7/DS4Windows/commit/dbe6ca63cc0dadf01ecf3b49c27b4b2e3abe1d94

**Comment by IceChevalier** [comment]
First at all, Congratulations and thanks for the driver man, makes my day. I see... I gonna check in the filter options, anyway, I don't lose anything deleting the profile folder in the AppData direction beacause I only have 2 profiles and, with your improves, I don't needed it :) I'm using the default tab with the old Blood Omen and The Witcher 2 and works wonderful. Thanks again man.
