### ISSUE TITLE
Minor bug/weirdness when using dot and underscore in profile names

### ISSUE THREAD

**Issue by frubo** [Ryochan7/DS4Windows#1457]
When a profile name uses underscores, the profile window won't show the first underscore: 

`xbox_mouse` shows as `xboxmouse`
`xbox__mouse` shows as `xbox_mouse`

The profiles are written to disk with the correct name.

When using a dot, DS4W will ignore the dot and everything after it and write to disk the profile with the wrong name even though the profile window will show the correct profile name:

`xbox.mouse` shows as `xbox.mouse` but is written to disk as `xbox.xml`
`.mouse` shows as `.mouse` but is written to disk as `.xml`

**Comment by Ryochan7** [comment]
Underscore characters in profile names work fine for me. The profile is written to disk with the proper filename with the underscore characters in tact.

Not even sure why you want to add a dot in the filename but that is confirmed to not work. Looking at the routines now, the BackingStore.SaveProfile method is the culprit behind why dots are not allowed. Anything past the dot will be seen as the file extension and be stripped. That issue probably won't be too difficult to fix.

**Comment by frubo** [comment]
> Underscore characters in profile names work fine for me. The profile is written to disk with the proper filename with the underscore characters intact.

The profile _is_ written with the proper filename, its just that in the profile tab it always skips the first underscore:

![profile_tab_underscore_bug](https://user-images.githubusercontent.com/68470449/91252505-a255f480-e755-11ea-9354-197e4d025f4f.png)

> Not even sure why you want to add a dot in the filename[...]

I don't. I just pressed '.' instead of '_' (next to each other in my layout) and reported it since it results in missing profiles upon DS4W restart.


Thank you for your work on DS4W.

**Comment by Ryochan7** [comment]
The underscore problem was due to the Controls themselves. It seems that labels can use key accelerators (called Access Keys in WPF) which are denoted by an underscore followed by an alpha character. That is why the first underscore was treated differently. This is the first time I felt it was easier to make a custom converter than trying to find a different workaround. Now, all single underscores are escaped in the name before they are displayed.

https://www.wpf-tutorial.com/control-concepts/access-keys/
