### ISSUE TITLE
Controller Suddenly Breaks- Windows tries to install xinput drivers

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#1461]
[ds4windows_log_20200823.0.txt](https://github.com/Ryochan7/DS4Windows/files/5114510/ds4windows_log_20200823.0.txt)

Gamepads were working fine. Playing with daughter on Ultra SF4. Mid match after a couple of matches, controllers stop functioning properly. Go back to windows and the xinput drivers are being searched for for download. I already had them installed properly.

Also, DS4windows always starts with controllers showing in the cpl when no controller is turned on. I have to stop and restat ds4windows. Why does it do this and how do i disable virtual pads? I thought they were off but seems like they are malfunctioning the program.

**Comment by Masamune3210** [comment]
it doesn't look like a issue with the virtual controllers from a quick glance at the log. it seems to be a issue with a bad connection to the controller, as the log is almost completely spammed with errors about latency being well over 10ms. possibly Bluetooth adapter going out?

**Comment by shinra358** [comment]
It's always been like that for me with the spam. Controller always worked
fine while playing.

Now i have to reinstall the xbox drivers

**Comment by mika-n** [comment]
If the BT chipset/PC setup there is not up to the task to read and write DS4 gamepad fast enough then you may wanna pump up the "Flash ligthbar at high latency" value in Settings tab page (by default 10ms, but set it to something like 30ms if 20ms level is "normal" in your setup). This way the logfile is not spammed too often.

If you disable "Enable output data to DS4" option within a profile settings then do you still see disconnection and lag issues? Ligthbar and rumble doesn't work when this option is disabled, but makes it easier for BT chipset because DS4Windows no longer read and write data at the sametime over BT. By disabling the option DS4Windows app only reads gamepad key events.

Another source of weird problems is Windows "fast startup" option. It is some MS crap created when people were still using slow HDD disks. If WinOS has fastStartup enabled then WinOS restart is not really a cold reboot, but warm reboot where WinOS remembers some system settings between reboots. There has been cases where this has caused weird gamepad issues (WinOS remembers virtual output driver state between restarts). Anyway, fastStartup is useless option theseday when people use SSD disks, so try disabling this winos setting.
https://www.asus.com/us/support/FAQ/1031533/

NOTE! This WinOS fastStartup is not the same thing as BIOS FastBoot/QuickBoot option.

**Comment by shinra358** [comment]
Again, Win7 doesn't have that
![jo](https://user-images.githubusercontent.com/3978291/91060971-98b77a00-e5f9-11ea-9f72-10990534fee8.jpg)

**Comment by Masamune3210** [comment]
It was added in 8, you are on 7, of course it's not there. The rest of the message still applies though

**Comment by shinra358** [comment]
To answer the other thing, this happened with enable output data to ds4 off on one controller but it was on, on the 2nd controller.

What about the question at the bottom of my pic?

**Comment by shinra358** [comment]
also, what's the best way to reconnect the drivers back to the controllers without uninstalling and reinstalling the xbox drivers? Should ds4w be off when this is going on? just controller be wired or wireless during this process?

**Comment by mika-n** [comment]
No need to check the "flash lightbar on high latency" option.

"what's the best way to reconnect the drivers back to the controllers"  What do you mean by that? Back to the controller? PC doesn't install any drivers into the DS4 gamepad. But, if you suspect something is wrong in gamepad then there is a full reset button on the back of the gamepad (small hole you can press with a paper clip).

If you suspect that WinOS has incomplete/corrupted DS4 drivers then one way to make sure all required drivers are setup is to install Sony RemotePlay for Windows app. But, I'm not sure if the app is available for Win7.
https://remoteplay.dl.playstation.net/remoteplay/lang/en/index.html

None of the developers (and very few users) use Win7 anymore, so you are pretty much on your own there.

**Comment by shinra358** [comment]
Bcuz it seemed that ds4w made windows forget where the drivers are hence
windows tries to search for them again so that the controller can work.

And what of the driver question? Should the controller be plugged w cord or
is having it on bt fine when reinstalling the xinput drivers? And should
ds4w program be off on on during the process?

**Comment by mika-n** [comment]
During driver installation (into WinOS) it is best to disconnect all gamepads.
