### ISSUE TITLE
DS4Windows instantly crashes

### ISSUE THREAD

**Issue by Atticus33** [Ryochan7/DS4Windows#1464]
I've tried multiple versions, but when opening from the exe or shortcut, it instantly crashes. I've changed driver signing, reinstalled vigem, hid and ds4 drivers. no gui pops up at all
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5138824/ds4windows_log.txt)

**Comment by mika-n** [comment]
`2020-08-27 17:11:48.6762|ERROR|System.Management.ManagementException: Not found `

The error msg shown in the logfile is known and it because your PC either has corrupted WMI repository or you have disabled WindowsManagementInterface (WMI) service. See the following post: https://github.com/Ryochan7/DS4Windows/issues/723

https://docs.microsoft.com/fi-fi/windows/win32/wmisdk/wmi-start-page?redirectedfrom=MSDN

**Comment by Ryochan7** [comment]
Here is another link that might be relevant. Maybe you will be able to fix the issue from the WMI Control app.

https://answers.microsoft.com/en-us/windows/forum/all/systemmanagementmanagementexception-invalid/74ac22c7-509d-42a5-9f7f-2686dc87b7b2

**Comment by mika-n** [comment]
closed as "inactive ticket and most likely WinOS setup issue with WMI services".
