### ISSUE TITLE
Windows Security Identifies as Threat

### ISSUE THREAD

**Issue by DDoop** [Ryochan7/DS4Windows#1477]
**Describe the bug**
I woke my computer up from sleep (after inactivity timeout) and Windows Security quarantined DS4Windows.exe, after identifying it as a threat. Classified as "Behavior:Win32/Execution.HF!ml." Details: "This program is dangerous and executes commands from an attacker." No idea what the HF means, I tried looking around online and I couldn't find anything useful.
I was running the most up to date version, recently updated.

**To Reproduce**
1. Let computer time out to sleep mode (I tried manually putting the computer to sleep and then waking it, that did not seem to do it, **I also didn't try letting it time out to see if that would reproduce it reliably**).
2. Windows Security notified me after I woke the computer up.

**Screenshot**
![threat report](https://user-images.githubusercontent.com/59840876/92066965-fd8c7600-ed57-11ea-9419-2dbe9c87b9b0.png)

**Expected behavior**
Program is closed and DS4Windows.exe is deleted.

**Desktop (please complete the following information):**
 - Controller Make and Model: CUH-ZCT1U
 - OS: Windows 10 Pro v. 2004 64bit
 - DS4Windows Version: 2.1.9

**Additional context**
I didn't have any apps open that should have been listening to the controller for input, who knows what NVidia was doing in the background, though. I usually have to force close one of their services to get exclusive mode to work, but that's another issue entirely.
EDIT: The "Learn more" link in the image goes [here](https://www.microsoft.com/en-us/wdsi/threats/threat-search?query=Behavior:Win32/Execution.HF!ml) (and I could not actually find that threat code in the list of 500 pages, of course).

**Comment by Masamune3210** [comment]
If you are sure you got it from this GitHub repo, its just defender being over-zealous as usual. Likely doesn't like the updater or something, seems to be a issue with other projects as well. Modern anti-viruses work on a reputation database, and if a file isn't seen a lot yet due to being either seldom used or being a new build of a program, they tend to assume malcontent first, and ask questions later. It has flagged programs that I have wrote and built on the same computer that thought it was a virus, so its a bit braindumb most of the time to say the least lol

**Comment by DDoop** [comment]
Going to close the issue since I haven't been able to reproduce it, and I did get it from this repo.
