### ISSUE TITLE
DS4windows no longer reliably entering exclusive mode

### ISSUE THREAD

**Issue by KBD20** [Ryochan7/DS4Windows#1480]
**Describe the bug**
A few updates ago whenever I start DS4Windows exclusive mode fails even though I leave it on - the only other change I made was installing IFI HD USB Audio Control Panel, disabling it at startup did not work.

**To Reproduce**
1. Possibly install the IFI USB program
2. Restart Windows
3. Open DS4Window in admin mode before game clients (steam etc) start
4. See Exclusive mode is disabled.

**Expected behavior**
For exclusive mode to function.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.1
 - OS: Windows 10 Home 1909
 - DS4Windows Version: 2.1.9

**Additional context**
Any physical workarounds I need assistance for.

In this case the controller is plugged in via usb, no issue in bt mode
Sometimes I can 'trick' it into working - by switching off exclusive mode, toggling stop then start an enabling exclusive mode working (not reliable).
Unplugging and replugging the controller reliably fixes the issue.
Also I just found out windows re-enabled game mode which I turned off - I will find out by tomorrow at the latest since I don't want to risk me breaking it again (personal issue/reasons)

**Comment by mika-n** [comment]
See the post #1472 

DS4Windows app cannot do much about the issue because it is beyond the control of the app. You just have to try to find which process/app is stealing the gamepad and this way preventing DS4Windows app to open it in exclusive mode. For example Edge browser in recent WinOS updates uses a background app even when you are not using the Edge browser in foreground and the background process may steal the gamepad. Or thousands of other potential apps beyond the control of DS4Windows app.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

If you cannot find the app stealing the gamepad then alternative solution is to use HidGuardian device driver tool. See the page linked above.

**Comment by KBD20** [comment]
Yeah, I followed the guide (after successfully getting exclusive - so I tracked the virtual xbox pad) - turns out it was oculus rift software that never used to start by itself, uninstalling should fix it (had it for a friends vr).

**Comment by mika-n** [comment]
closed and added a comment about Oculus apps to a wiki doc page.
