### ISSUE TITLE
Weird DS4Windows behavior

### ISSUE THREAD

**Issue by pleasejustgo** [Ryochan7/DS4Windows#1482]
Not sure if it's a bug per se... but the first time I setup ds4windows, I ran it, installed the V whatever in step 1. Pressed and held share/PS button for 3 seconds, added device in control panel > devices and printers and windows bluetooth paired the device, didn't ask me for a pairing code or anything. In Project64, I was able to set the controls by pressing buttons on the DS4 controller. In the controller control panel or whatever, that you access from DS4Window settings tab, it showed just the wireless controller and it worked when I tested it, all the buttons lit up, all joystick axis worked. I think what happened was that I deleted the DS4Windows folder from the desktop last night, I thought I didn't need it, it had the exe in it and a bunch of other files... when I upzipped it again the next day and placed it in a proper folder and set it up to run at login and all that... then when I added a device after holding share/ps button, it added wireless controller and HID compliant controller and in the DS4Window control panel it shows wireless controller and xbox 360 controller, I guess it's emulated.. but when you click on configure it shows that the L2 and R2 triggers are in a single bar, like when you press L2 it moves to the left and when you press R2 is moves to the right. The configuration of the "wireless controller" does nothing. And in Project64, I can't simply change controls by pressing a button on the controller, I have to click on the box to use xinput, then assign a button manually. wtf, this is why I don't use windows. So stupid it's beyond belief. I'm not on windows at the moment so I don't remember the exact names of the tabs/menus or whatever. Sorry, if any of this makes sense, please help. I'd like to be able to just press a button like before to reconfigure my controls in project64 without xinput. Thanks.

**Comment by mika-n** [comment]
Please take a look at the pinned "Read this before posting a new issue ticket". As a minimum you should provide a logfile as text file ATTACHMENT in post (not just copy-pasted as 1000 lines text comment).

Anyway, I guess you are connecting over bluetooth and not over USB? 
If you see both "Wireless Controller" and the virtual "xbox360 controller" output controller then take a look at the following doc page. It explains why there are two gamepads even when you have just one phystical gamepad (=Wireless Controller = DS4 gamepad). In you case the xbox360 gamepad is a virtual output controller created by DS4Windows/VigEm apps.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

You can hide the original gamepad from games by enabling exclusive mode in DS4Windows (=Hide DS4 Controller option) or by using 3rd party additional HidGuardian tool. In fact some games require that the original gamepad is hidden because in some cases game programmers have been lazy and those games are confused when two gamepads send button inputs at the same time (=the physical pad and the virtual pad).

And the thing about L2/R2 axis. That is how xinput xbox360 axis works (it is splitted in half), but there is nothing to worry about it  because all games using xbox360 xinput gamepad should understand it and know how to deal with it.

DS4 dinput gamepad (=Wireless Controller named device) uses separate axis with L2 and R2.

If you use USB connection then most games/apps nowadays supports natively DS4 gamepad, so no need to use DS4Windows app. 

If you use BT connection then Windows supports DS4 gamepad natively, but only as in "PC-friendly mode" and not in "native DS4 mode" (=touchpad/gyro etc special DS4 features enabled). If you want to utilize touchpad/gyro in BT mode then DS4Windows app is required because this app knows how to switch the BT connected DS4 gamepad to native mode (WinOS doesn't know how to do it).

So, I recommend you to test this:
- Enable "Hide DS4 Controller" option to get rid of two gamepads in gamepad list (but read carefully the above linked web page how you HAVE TO make sure ds4windows app is the first app using the physical ds4 gamepad or exclusive mode fails).
- Modify DS4Windows profile to use either xbox360 or dualshock4 output mode depeding on whether you want apps to see xinput or dinput output device.

**Comment by Ryochan7** [comment]
A little manually configuration in Project64 is enough to throw in the towel. :laughing:
