### ISSUE TITLE
Proper way to convert joystick to 4 way dpad?

### ISSUE THREAD

**Issue by alpharou** [Ryochan7/DS4Windows#1484]
I need to emulate an exclusive 4 way input, and this is the best I could manage tinkering with the stick settings:

DeadZone: 0.95
maxzone 1.0
AntiDeadZone 0.0
MaxOutput 1.0
Sensitivity 0.5
Output curve Linear
Square Stick Off
CurveInput 100%

It somewhat works, but sometimes it jitters, triggers many times a second, and trigger two directions.
Any suggestions?

**Comment by mika-n** [comment]
There are several ways to do analog LS/RS -> digital Dpad mapping. Here is one way I have found to work pretty well.
The idea is 
- Set "big enough, but NOT TOO BIG" deadzone to avoid accidental digital triggerin (because LS/RS is never completely stable in hardware level), but leaving enough room in the "upper boundary" to avoid accidenal de-activations.
- Custom output curve to manipulate the output curve to "take it easy" in the beginning of the curve, but then rapidly pumping up to the max zone area (the custom curve shown in the pic is not possible by moving those red dots with a mouse in the graphical editor behind "..." button, but you can enter these values there manually and the graph does visualize it. And it works in DS4Windows because out-of-boundary curve is capped to max output value). The idea is to pump up the stick output as rapidly as possible to the max value.
- Square stick makes those diagonal directions "more square", so the output curve goes more reliably beyond the digital threshold even in NW/NE/SE/SW directions (by default if you move LS/RS to a diagonal position then the LS curve is circular).

![DS4Win_DPadLSMapping](https://user-images.githubusercontent.com/35538525/92572653-62325e00-f28d-11ea-8934-e6498dead5e8.png)

**Comment by alpharou** [comment]
> There are several ways to do analog LS/RS -> digital Dpad mapping. Here is one way I have found to work pretty well.
> The idea is
> 
> * Set "big enough, but NOT TOO BIG" deadzone to avoid accidental digital triggerin (because LS/RS is never completely stable in hardware level), but leaving...

I appreciate the reply, but this approach will create an 8 way dpad, and I'm looking to completely remove the diagonals.

That said, I think the custom output curve could come in very handy, thanks.

**Comment by mika-n** [comment]
Aaah. Missed that part of the requirement (ie. to not send out diagonal btn directions at all). Maybe insanely big square stick option makes the diagonal direction a bit more "difficult" to do. But it might be very difficult to eliminate diagonal directions of LS/RS completely with the current mapping routines in DS4Windows.

**Comment by Ryochan7** [comment]
There is no way to use a joystick as a 4 way dpad in the mapping routine. That has not been a strict requirement and I have had no use for such a feature. Such a feature would be easier to pull off with the current code than implementing an 8 way control dpad mode for use in Rougelike games. If nothing else, some type of overlap setting could be applied that would change the designated angles for each direction button.

**Comment by alpharou** [comment]
Ok, I understand.

That said, the configuration I posted initially seems to work, at least for my case.
