### ISSUE TITLE
Vibration on Emulate as dualshock (wireless)

### ISSUE THREAD

**Issue by IceLancerSR** [Ryochan7/DS4Windows#1487]
Hello!
I am playing Shadow of Tomb Raider. And game has native support (for playstation button icons) for both wireless and wired DS4 controllers , but once u put controller on wireless ,rumble (vibration) does not work any more. So i thought i might fix it with this tool.
But no success. i emulate as dualshock, click rumble test (in tool ,all good). But once in game rumble still wont work.
Is there a way to fix that?

**Comment by mika-n** [comment]
Maybe the game is accidentally using the original (physical) DS4 gamepad device where rumble doesn't work over BT? See the "double controller" issue described below.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

What do you see in JOY.CPL controlPanel applet when DS4Windows app is running and the gamepad is connected (run JOY.CPL cmd or click the "Control Panel" link in DS4Windows Settings tab page)? Do you see one or two "Wireless Controller" devices?

Try enabling "Hide DS4 Controller" option in DS4Windows to hide the original physical DS4 gamepad device handle and leaving just the virtual output controller created by DS4Windows/ViGem apps visible.  However, please read the page carefully because in some PC setups the exclusive mode doesn't work without tweaking the start order of other apps.

Alternative way to hide the original controller is to use HidGuardian driver solution and it usually works even in PCs where the "Hide DS4 Controller" (=exclusive mode) option doesn't work.

And check the active profile in DS4Windows. There is an option with xbox360 and dualshock4 output modes.

**Comment by IceLancerSR** [comment]
I see. Ok i will try with exclusive mod. I don't really bother my self with that because it involves stopping NvContainerLocalSystem to get exclusivity and if gamepad on idle disconnects later, exclusivity is gone
ok tested with exclusive mod , same thing , no vibration on wireless. In joy.cpl there is only one gamepad
and in device and printers there is one hid-compliant game controller and wireless controller

**Comment by mika-n** [comment]
If JOY.CPL shows just one WirelessController device then exclusive mode or hidGuardian is doing its magic. Good.
But, if the rumble still doesn't work and the profile doesn't have 0% rumble amplifier value then could be a game specific issue. I don't have "Shadow of Tomb Raider", but the previous version "Raise of the Tomb Raider". I'll try to test it at some point with DS4 gamepad (although don't know if it uses rumbling effects at all).

**Comment by IceLancerSR** [comment]
> 
> 
> If JOY.CPL shows just one WirelessController device then exclusive mode or hidGuardian is doing its magic. Good.
> But, if the rumble still doesn't work and the profile doesn't have 0% rumble amplifier value then could be a game specific issue. I don't have "Shadow of Tomb Raider", but the previous version "Raise of the Tomb Raider". I'll try to test it at some point with DS4 gamepad (although don't know if it uses rumbling effects at all).

Actually yeah! Rotr also doesnt have vibration in wireless mod. Gamepad dualshock icons are there but no rumble/vib

**Comment by mika-n** [comment]
Good and bad news. 
The good news is that the rumble does work even with BT connected DS4 gamepad (tested in RoTR and html5gamepad tester) via DS4Windows app, but the bad news is that it requires slight code changes, so it doesn't work there yet. Some time ago there were some weird issues with rumble and lightbar color, so the rumble feature was temporarily disabled when output controller is dualshock4. The code is still there which disabled the rumble. 

There probably should be a profile option to let user to decide if rumble/lightbar feedback event handlers are enabled or disabled.

**Comment by IceLancerSR** [comment]
> 
> 
> Good and bad news.
> The good news is that the rumble does work even with BT connected DS4 gamepad (tested in RoTR and html5gamepad tester) via DS4Windows app and dualshock4 profiles, but the bad news is that it requires slight code changes, so it doesn't work there yet. Some time ago there were some weird issues with rumble and lightbar color, so the rumble feature was temporarily disabled when output controller is dualshock4. The code is still there to disable the rumble in ds4 output mode.
> 
> There probably should be a profile option to let user to decide if rumble/lightbar feedback event handlers are enabled or disabled.

I could help you test defect and possible issues if u want. I used to assist you with debugging latency issue when u created debugger-off ds4mode (since then i solved issue by buying USB extension for bluetooth and stuck it under the monitor 2m away instead of keeping it behind metal casing of PC box. That totally solved latency issues)

**Comment by mika-n** [comment]
@IceLancerSR  There is now a new debug version available (synced with the latest 2.1.10 official release AND additional tweaks how rumble and lightbar colors are handled in DS4 output controller mode. The debug version has re-enabled rumble with small tweaks how the "watchdog timer" works in case rumble gets stuck on. Also, lightbar color set by a game works only if lightbar mode is set to Passthru (in normal mode lightbar is controlled by DS4Windows app only).

Ticket #1389 talks more about why the rumble/lightbar color logic was disabled in DS4 output controller mode. Some games got stuck in infinite rumbling (the watchdog rumble timer in DS4Windows didn't work properly with some games because the game sent some weird rumble/lightbar commands) or lightbar was flashing because the game kept changing the color (or it conflicted with the color set by DS4Windows app).

Now the debug version works like this:
- Lightbar: Games can set the lightbar color only if lightbar mode is Passthru in DS4Windows profile settings. If the mode is Normal (=default mode) then DS4Windows app ignores lightbar color commands sent by a game. Now it is up to the user to decide how she wants to handle the lightbar and "both ways" are now possible (different profiles can have different mode).

- Rumble: DS4 output re-enables rumble support. DS4Windows app has a rumble watchdog timer (next to Rumble %-amplifier value in profile editor) and now this timer is reset only if the new rumble value sent by a game is different than the previous rumble value. This way if the watchdog timer is enabled and a game re-sends the same rumble value alongside a lightbar color command then the watchdog timer has a chance to stop potentially stuck rumble motor. By default the rumble watchdog timer is disabled (=0 value in a profile), but feel free to set it to X secs in case some games keep getting stuck with rumbling.
- If you want to disable rumbling completely then set the %-amplifier value to zero and DS4Windows never enables rumble motors.

I tested this in Rise of the Tomb Raider and now rumbling seemed to work just fine even in BT mode and the rumbling never got stuck in infinite rumbling (well, RoTR was never identified as one of those problematic games. Street of Rage4 and Witcher3 seemed to have some issues, but the changes in the debug version might help with those games also).

**Comment by garikul** [comment]
Hello!
I have the same problem. I noticed that rumble in all games stopped working since ver. 2.1.5.
So, if you downgrade the DS4 to ver. 2.1.4, vibration will work fine...
Tested in the ROTTR/SOTTR/Horizon e.t.c.

P.S. Latest update 2.1.10 also don't solve the issue...

**Comment by mika-n** [comment]
@garikul  See the link to debug version in my previous post here. Download the debug V2.1.10 version and give it a test run in ROTTR/SOTTR. At least ROTTR worked now fine with DS4 output mode and BT connection (rumbling and lightbar didn't go crazy).

**Comment by IceLancerSR** [comment]
> 
> 
> @garikul See the link to debug version in my previous post here. Download the debug V2.1.10 version and give it a test run in ROTTR/SOTTR. At least ROTTR worked now fine with DS4 output mode and BT connection (rumbling and lightbar didn't go crazy).

I tested debug 2.1.9.0 in your link , couldnt get vibration to work in neither of two games? rumble settings is 100
i went back to some old version i had on hdd 1.7.22.0 and vibration works

**Comment by garikul** [comment]
> @garikul See the link to debug version in my previous post here. Download the debug V2.1.10 version and give it a test run in ROTTR/SOTTR. At least ROTTR worked now fine with DS4 output mode and BT connection (rumbling and lightbar didn't go crazy).

@mika-n, tested the debug version, but nothing changed... Tried via BT and USB - rumble doesn't work. Here are the logs:
[logBT.txt](https://github.com/Ryochan7/DS4Windows/files/5214011/logBT.txt)
[logUSB.txt](https://github.com/Ryochan7/DS4Windows/files/5214012/logUSB.txt)

**Comment by mika-n** [comment]
@IceLancerSR @garikul   Ooops. My major bad. I had commited the code changes in the debug version, but forgot to publish those changes. So, the debug version you downloaded was actually V2.1.9 and not V2.1.10. Please try again and download the debug version. The logfile generated by the debug ver should now show 2.1.10 and rumble should work in DS4 output mode.

**Comment by IceLancerSR** [comment]
> 
> 
> @IceLancerSR @garikul Ooops. My major bad. I had commited the code changes in the debug version, but forgot to publish those changes. So, the debug version you downloaded was actually V2.1.9 and not V2.1.10. Please try again and download the debug version. The logfile generated by the debug ver should now show 2.1.10 and rumble should work in DS4 output mode. Sorry for the confusion.

Tested in both games. ROTTR SOTTR Vibration now works! BT mode
I just recently deleted Witcher 3 from pc (hdd space issue) so cannot test that

**Comment by garikul** [comment]
@mika-n , yeah, it works in rottr, sottr and horizon via BT, thank you!
Should we using debug version for now?

**Comment by mika-n** [comment]
yes. you should use the debug version until the official version has those changes (or if something like that in case something still need to be tweaked before the change is released).

**Comment by IceLancerSR** [comment]
> 
> 
> yes. you should use the debug version until the official version has those changes (or if something like that in case something still need to be tweaked before the change is released). The debug version is identical with the official V2.1.10 version, There are just few extra debug messages when a new gamepad is connected and how previously unknown gamepads are handled.

Did extensive gameplay in SOTR , vibration works perfect. No weird side-effects. I did however notice that left thumbstick is slightly more sensitive then in older version of DS4. I have almost brand new gamepad so thumbsticks are very tight , but even slight touch on thumb would cause movement in Tomb Raider. hence had to increase dead zone from 0.08 to 0.09
It wasn't that sensitive in older versions

**Comment by ramaduc** [comment]
https://github.com/Ryochan7/DS4Windows/issues/1389#issuecomment-691658037

In response to Mika-n. I would like to thank you for your work and dedication.
I use the debug 2.1.13 version and it works flawlessly in Heave Ho, Streets of Rage 4, Shadow of tomb raider and the witcher 3.
For Witcher 3 i had to make some tricks in order to get it work. 

First I couldn't make my ds4 to work wirelessly and then when I plug it to my computer and unplug it, then the ds4 needs it to be paired again (as described in this thread). My Witcher 3 version is a GoG version.

I manage to made it work by using Steam. In fact you can add a non steam game so it made the trick. It works fine that way (tested wirelessly and pluged via usb). I pluged and unpluged the ds4...works like a charm.

The only thing a little annoying is the xbox buttons instead of the playstation ones. I don't know if there is a fix for that.

Thanks again.

**Comment by IceLancerSR** [comment]
> 
> 
> [#1389 (comment)](https://github.com/Ryochan7/DS4Windows/issues/1389#issuecomment-691658037)
> 
> In response to Mika-n. I would like to thank you for your work and dedication.
> I use the debug 2.1.13 version and it works flawlessly in Heave Ho, Streets of Rage 4, Shadow of tomb raider and the witcher 3.
> For Witcher 3 i had to make some tricks in order to get it work.
> 
> First I couldn't make my ds4 to work wirelessly and then when I plug it to my computer and unplug it, then the ds4 needs it to be paired again (as described in this thread). My Witcher 3 version is a GoG version.
> 
> I manage to made it work by using Steam. In fact you can add a non steam game so it made the trick. It works fine that way (tested wirelessly and pluged via usb). I pluged and unpluged the ds4...works like a charm.
> 
> The only thing a little annoying is the xbox buttons instead of the playstation ones. I don't know if there is a fix for that.
> 
> Thanks again.

as far as i know witcher 3 doesnt have dualshock button icons in wireless mod. Only wired. Get dualshock button icons mod from nexus to fix the problem

**Comment by ramaduc** [comment]
> > [#1389 (comment)](https://github.com/Ryochan7/DS4Windows/issues/1389#issuecomment-691658037)
> > In response to Mika-n. I would like to thank you for your work and dedication.
> > I use the debug 2.1.13 version and it works flawlessly in Heave Ho, Streets of Rage 4, Shadow of tomb raider and the witcher 3.
> > For Witcher 3 i had to make some tricks in order to get it work.
> > First I couldn't make my ds4 to work wirelessly and then when I plug it to my computer and unplug it, then the ds4 needs it to be paired again (as described in this thread). My Witcher 3 version is a GoG version.
> > I manage to made it work by using Steam. In fact you can add a non steam game so it made the trick. It works fine that way (tested wirelessly and pluged via usb). I pluged and unpluged the ds4...works like a charm.
> > The only thing a little annoying is the xbox buttons instead of the playstation ones. I don't know if there is a fix for that.
> > Thanks again.
> 
> as far as i know witcher 3 doesnt have dualshock button icons in wireless mod. Only wired. Get dualshock button icons mod from nexus to fix the problem

Thanks for the tips. I didn't know nexus mod. I managed to get the DS4 icons in Witcher 3. Don't need to plug the controller. It works wirelessly too (as long as you launch the game from steam).
