### ISSUE TITLE
Vibration disappears when lightbar is on by another button press

### ISSUE THREAD

**Issue by Pankeko** [Ryochan7/DS4Windows#1497]
Bug: if you assign a button press to light up the light bar, while holding that button vibration seems to be weird in games.

to reproduce: 
just add a color to a button press, so lets say when you press square it lights up pink, while holding it, vibration will be non existent or very weak, this does not occur when light is on all the times

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro Build 19041.508 2004
 - DS4Windows Version 2.1.13

**Additional context**
Id also wanna request the touchpad click (the one where you press on the curved edge) to enable gyro thanks love your program <3

**Comment by Ryochan7** [comment]
I don't mess around with those extras settings but it seems like there is no explicit ignore option for the rumble. I don't know if it would be a good idea to establish (0,0) as the ignore value since maybe someone would want to disable rumble in some case.

Also, I am not sure that allowing Touchpad Click for a gyro trigger is a good idea. I find the top region of the Touchpad area to be fairly stiff and requires too much force to activate. Since that region is not tracked and is considered outside of the range of the touchpad, there is no way to just utilize a touch option for that region. I guess maybe allowing for a Touchpad Click trigger option in general might be beneficial though.

**Comment by Pankeko** [comment]
For me my index finger usually just rests on that curve of the touchpad, feels kinda natural to click down on it, taking my thumb off the left analog or face buttons to click the touch is kinda difficult for me.
Thank you c:

**Comment by Ryochan7** [comment]
The vibration being reset occurred on the button release. (0, 0) does count as an ignore option but the release routine would set the device rumble to (0, 0) regardless if a temporary rumble value was set or not.

**Comment by mika-n** [comment]
SpecialAction macro can also set a lightbar color and I believe it doesn't reset the rumble back to zero value if the macro didn't do any rumble events. And if you enable "keep key state" option in a macro then specAction macro leaves the custom color on even when you release the button (and press another button to change the color to something else).
