### ISSUE TITLE
I request help getting DS4Windows setup

### ISSUE THREAD

**Issue by bluecloud98** [Ryochan7/DS4Windows#1498]
I just downloaded the latest files that is instructed to download if you want to get DS4Windows installed and setup and I have no idea how to get this going. I find the setup guide confusing.

**Comment by mika-n** [comment]
- Check requirements (Install the latest Microsoft .NET Framework libraries and VisualC++ runtime libraries)
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

- Unzip "DS4Windnows<versionTagHere>.zip" file to "C:\apps\DS4Windows\" folder
- Run DS4Windows.exe app from c:\Apps\DS4Windows folder and it will guide you through to install everything else if some required component is missing (mainly ViGem driver app. Optionally you can manually install the ViGem package, but the DS4Widnows app will do it when you launch the app for the first time).

- Plugin DS4 gamepad via USB or BT and there you go. After this you can do all sort of button/stick/touchpad remaps rules in DS4Windows if you want to customize how the gamepad works.

Instructions talk about "exclusive mode" and "HidGuardian driver tool" also. This is not required by DS4Windows app itself, but some games do require it to avoid "double controller input" issues.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by bluecloud98** [comment]
I'm still confused, I'm just trying to play Roblox with my DS4

**Comment by mika-n** [comment]
If you don't need the special features provided by DS4Windows app then why don't you just plug-in the gamepad via USB cable and play the game? Win10 supports DS4 gamepad natively over USB.

DS4Windows app is required if you want to re-map gamepad buttons (fex X button would be seen my games as DPadDown key or something else) or running macros from buttons (fex. X buttons sends out series of button events or even keyboard or mouse events).  Also, if you want to utilize gyro/touchpad features of DS4 gamepad over BT then you need DS4Windows app because Win10 can use those features only over USB connection.

**Comment by bluecloud98** [comment]
It's not working when I plug my controller in using a USB. I'm on a laptop in case that information helps. I also tried xpadder, I might buy xpadder, I'm just really trying to get this to work

**Comment by bluecloud98** [comment]
It's not working when I plug a USB in, I'm on a laptop in case that helps

**Comment by Masamune3210** [comment]
Then either your windows install is messed up, or the controller, cord, or port are having issues

**Comment by mika-n** [comment]
Read the pinned "Read this before posting a new issue ticket". You should attach the latest logfile as an attachment here (rename the logfile as .TXT file). We have no way of knowing what is going on there without more details. Error report "it doesn't work" is not very useful.

**Comment by mika-n** [comment]
closed as "inactive"
