### ISSUE TITLE
Trouble Pairing

### ISSUE THREAD

**Issue by sammer2001** [Ryochan7/DS4Windows#1500]
I installed last night and have been having trouble getting my controller to pair via Bluetooth. I've tested and it picks up the controller when plugged in. Also, on a different note, it would be great if I could actually install the app. I noticed that JoyComs are supported but is the Switch Pro Controller supported?

**Comment by mika-n** [comment]
See the pinned "Read this before posting a new ticket".  Please provide the minimum information asked there (application version, WinOS version, logfile as TXT attachment).

Also, you may wanna run a debug version of DS4Windows app. It generates looooots of extra messages when a gamepad is connected. It may tell more clues why the BT connection doesn't work.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by sammer2001** [comment]
The log file seems to somehow have been cleared. 
![Screenshot 2020-09-26 132524](https://user-images.githubusercontent.com/20076209/94346611-c9753f80-fffb-11ea-8108-c1ad3f98ab83.png)

**Comment by mika-n** [comment]
Hmmm... Are you sure you are using the latest V2.1.13 version because the logfile screenshot you posted looks an old version? Please download the latest version from the following link. This latest version should store a logfile in "%APPDATA%\ds4windows\log" folder.
https://github.com/Ryochan7/DS4Windows/releases
