### ISSUE TITLE
Macros sending keystrokes but not sending button presses

### ISSUE THREAD

**Issue by Corgano** [Ryochan7/DS4Windows#1514]
Assigning macros to a button seems to only half work. A macro that sends keystrokes or mouse clicks seems to be fine, but sending button presses on the output 360 controller doesn't do anything.

[L1] -> macro( {x} ) = nothing
[L1] -> macro( {spacebar} ) = presses spacebar

Sony DS4 version JDM-040
DS4Windows 2.1.14

**Comment by mika-n** [comment]
You probably need a short delay between key down and key up events because some games are not "fast enough" to see the key press if key down and up events are fired too fast.

**Comment by Corgano** [comment]
Oh that's a good point. I'll try that later when I get home

I was wondering if there was an option somewhere for key delay / key down
delay? Would it be hard to add two inputs to the macro window and add
variables for them? That way you could define say 70ms let delay between
keys, and 40ms delay before releasing keys. This could be stored for the
specific macro.

The upshot is you wouldn't have to specify / change every single delay like
you would if you recorded delays. It would also make speeding up or
allowing down an existing macro much easier

**Comment by mika-n** [comment]
You can edit those macros via "Powered by Notepad" technology also. Record a new dummy macro with "record with delays options" and see how it stores key press, delay key up events. Delays is, if I recall everything above 300 codes (ie. code value 310 is 310-300=10ms delay. Everything below <300 are key/mouse/rumble/ligthbar event codes.

Or you can modify the existing macro and record new events with delays and then use "move item up/down" to re-order those events.

**Comment by Ryusennin** [comment]
You can edit the delays directly from the macro editor by double-clicking the delay value.

**Comment by Ryochan7** [comment]
I don't use the macro system so I have had little incentive to add on to it. Last time I checked, controller button presses from macros worked.

Like others have mentioned, you will probably have to add some sort of wait period between the button press and button release otherwise the macro might finish executing in less than one game frame and the game will miss the press. I thought about adding some way to insert wait periods into the list during the initial migration to WPF for DS4Windows 2.0. Clearly I decided it was not worth the hassle at that time.
