### ISSUE TITLE
[Feature Request] Global keyboard shortcuts to change controller profiles

### ISSUE THREAD

**Issue by JeffreyMercado** [Ryochan7/DS4Windows#1515]
It would be nice to be able to create global keyboard shortcuts to be able to change controller profiles either at an individual controller level or for sets of controllers.

Ideally I'd be able to bind my macro keys for my keyboard to change my ds4 profiles (among other things). So while I'm in game, I could change profiles on the fly, without necessarily having to create the special actions for it. (I can do that, but I'd like to utilize my other devices if I can.)

Even more ideally, we'd be able to create integrations for external apps/devices to provide this functionality. I might be inclined to assist with a G-Hub integration if this was to become a thing.

**Comment by mika-n** [comment]
If you need some custom logic to change a profile (ie. something else than is built-in DS4Windows special action macros and "swype to change profiles" / ds4 keybindings to change a profile) then I'm sure you could work out something via a command line interface. There are commands to change a profile from a 3rd party custom application. 
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options

AutoHotKey is one app where you can define your own keyboard key combinations and run a custom command.
https://www.autohotkey.com/

You could bind a hotkey to run something like this: DS4Windows.exe -command LoadProfile.1.SnakeGame

If you want to integrate the command line interface with a fancy batch file then you might wanna use an additional (optional) DS4WindowsCmd.exe command liner tool along side with the DS4Windows app engine. The standard DS4Window.exe app doesn't have a console because it is WinOS GUI app, so there are certain problems to integrate it with batch file outputs and inputs. DS4WindowsCmd.exe tool solves that problem. However, just to run a LoadProfile command works just fine with DS4Windows.exe you already have if you don't need to process outputs of these commands.
https://github.com/mika-n/DS4WindowsCmd

**Comment by JeffreyMercado** [comment]
Oh nice. I could work with this in the meantime. Looks flexible enough to be able to make "profile sets" for different controllers.
