### ISSUE TITLE
hid guardian .. mouse keyboard not working .. can't start windows 7

### ISSUE THREAD

**Issue by sunotis** [Ryochan7/DS4Windows#1525]
hi .. i have a serious problem after installing hid guardian.

i have no access to my windows 7 desktop anymore, so i can not say which version ist was.

no access, because my usb keyboard and mouse don't work anymore right after exiting bios.
i can not even start in safe mode .. because i can not select safe mode as the keyboard is not responding

so after a while the windows login screen is loading and i can not do anything

any idea how i can repair this?

**Comment by Masamune3210** [comment]
if your keyboard is being affected by hidguardian, you will still be able to or at least should be able to access safe mode as it only kicks in once windows is fully booted. if not, do you perhaps have another keyboard or mouse handy? it shouldn't be affected by the program if you do

**Comment by mika-n** [comment]
You must have somehow lost the hidGuardian.sys device driver file because if that file is removed before unregistering HidG uplink filter links then you end up without usb keyboard/mouse. PS2 kbd/mouse would work.
If you don't use a proper uninstallation app then manual steps are like this to unintalll hidGuardian:
https://github.com/ViGEm/HidGuardian/tree/master/sys#manual-removal

Anyway, if you end up with that situation then it is possible to fix the issue through WinOS "boot recovery / advanced" option (command line interface of safe boot):
- Reboot to Windows boot recovery screen or sometimes called advanced boot/startup menu (F8 or F5 key during reboot, but before WinOS is actually loading). If you can't get these boot keys to work then force reboot the PC three times when the WinOS loading screen is shown (after the 3rd time WinOS thinks something is really wrong and goes into boot recovery menu).
- Navigate to Advanced boot menu screen and choose Command prompt
- Open RegEdit (run regedit cmd)
- Select one of the top menu lines with xxx_USERS
- Select "Load Hive" from menu line
- Select C drive and /windows/system32/config folder  (make sure it is C drive and not the default user folder this dialog offers at first)
- Select SYSTEM file and give it some name (any name, doesn't matter what it is)
- Open the file you named above
- Select "CurrentControlSet001"
- Navigate to `Control\Class\{745a17a0-74d3-11d0-b6fe-00a0c90f57da}` registry section
- Choose "UpperFilter" registry entry line and delete it
- Re-select the file you named above and choose "Unload Hive" from menu commands and confirm the warning
- Close reg editor tool
- Run the command `wpeutil reboot`

After reboot you should be back in business because the filter driver setting is gone (which was pointing to non-existent or non-working HidGuardian installation).
 

(These instructions can be found from HidGuardian web site/discord/documentation). HidGuardian works great, but especially the uninstallation needs to be done properly in order to avoid the issue you described.

**Comment by sunotis** [comment]
thank you!

**Comment by mika-n** [comment]
HidGuardian version 1 works great when it works, but it is theoretically dangerous driver if something goes wrong with the driver setup (just like you had). Fortunately nothing is permanently broken if this happens. There has been rumors of HidGuardian version 3 and rumors tell it does a lot of things better. But, all we can do is to donate/send test reports/help with documentation the author and wait for until the author Nefarious thinks it is release ready. Trust me. It doesn't help to ask what is the landing ETA time for the next version of HidGuardian or ViGem driver :-)

**Comment by Ryochan7** [comment]
You have to be really careful when you install or uninstall HidGuardian. The biggest issue is adding the Class Filter without having the driver installed. That is a guaranteed way to lose access to all HID input devices including a USB keyboard and USB mouse. You would then be forced to go into recovery mode and fix the Windows registry from there.

I usually use my own utilities to install a custom HidGuardian rather than using the old command line method with devcon.exe.

**Comment by jamezsan** [comment]
Please help! 

Similar issue, using WIN10. Installed HIDGuardian, and now after a reboot I cant use my keyboard in windows applications (search bar, settings etc). Ran the uninstall file to remove HIDGuardian, and after reboot I am still unable to use the keyboard.

**Comment by brack-choko** [comment]
These instructions can all be done from the CMD interface? The renaming and selecting files? I don't know anything about command line so I'd like some tips.

**Comment by mika-n** [comment]
If you want to uninstall HidGuardian and replace it with more robust and reliable (and easier to use) HidHide tool then see the HidHide installation guide. It explains how to uninstall HidGuardian before trying to install HidHide
https://vigem.org/projects/HidHide/Simple-Setup-Guide/

**Comment by brack-choko** [comment]
I'm in the same boat as the poster. I deleted the same thing and now my peripherals won't work. I've never used CMD, nor regedit. I'm hoping for a little more guidance if at all possible.

**Comment by mika-n** [comment]
okey, then there is no better guides than those using CMD and registry editor tool. It is the only way to resolve the issue now when you have screwed up the uninstallation of a device driver. Device drivers operate in Windows kernel mode, so those are always potentially more "dangerous" than normal user mode applications.

If you have a PC motherboard supporting those old PS/2 kbd/mouse connections then you could use ps/2 kbd and mouse to access the PC and try to recover the things without going through Windows recovery mode.

Alternative way is to re-install Windows :-)

**Comment by brack-choko** [comment]
nice, thanks for the quick responses. also, trying to rename "system" in the config file seems impossible as it is already in use. That seems to be my only issue atm but if I can't figure it out I'll go ahead and re-install.

**Comment by Ryochan7** [comment]
Just needed this info after turning off Test Signing and not removing HidHide; need it off temporary to test Valorant. Realized my error when the keyboard and mouse didn't work upon rebooting Windows. I thought there was another issue somewhere with the guide on how to get into Windows Recovery mode and fix the registry but this is the only issue I could find. Pinning this issue for now.

**Comment by Kanuan** [comment]
Oh, right, I was working on an manual HidHide manual removal guide but was procrastinating on actually finishing it.

Will try finishing it and making it live today

**Comment by Kanuan** [comment]
And done: [Fixing an improper removal of HidHide](https://vigem.org/projects/HidHide/fixing-a-bricked-system/)

Guide may be overdetailed but I thought it was better to leave no room for error, specially considering some users might be scared of messing with the registry

**Comment by Trihy** [comment]
Just leave rdp or any other tool configured. It will make things a lot easier.
