### ISSUE TITLE
Live preview lightbar color

### ISSUE THREAD

**Issue by lifehome** [Ryochan7/DS4Windows#153]
In the Jays2Kings' version, clicking the color block at the top right corner of `Controllers` tab, selecting customer color and roam at the "Define Custom Color" color spectrum area, allows you to preview instantly on the DS itself. Hopefully this version can adds this feature too, as it would be cool to adjust the color instantly :D

**Comment by Ryochan7** [comment]
I just checked this in the latest stable version and it works for me. Clicking the lightbar portion of the controller image and expanding the color dialog allows the lightbar on the DS4 to update with the custom color that you currently have selected. It does not update if you select a basic pre-defined color in the initial dialog though.

Also, thanks for mentioning this since I had actually broken this in testing with the changes being made regarding generating output reports.
