### ISSUE TITLE
Raiju TE - "Hide DS4 Controller" does not hide Controller with BT Connection but with USB Connection

### ISSUE THREAD

**Issue by glockmane** [Ryochan7/DS4Windows#1532]
**Describe the bug**
- plug via USB, hiding works
- connect via Bluetooth, hiding not working

**To Reproduce**
-

**Expected behavior**
Second Instance of Controller hidden

**Screenshots**
![image](https://user-images.githubusercontent.com/2814025/96056391-b4ffc680-0e86-11eb-9f0d-22944b84df30.png)
![image](https://user-images.githubusercontent.com/2814025/96056435-d791df80-0e86-11eb-95bc-d4bf3cc300c9.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: Razer Raiju Tournament Edition 1.05
 - OS: Windows 10 Enterprise 20H2 19042.508
 - DS4Windows Version: 2.1.15

**Additional context**

**Comment by mika-n** [comment]
Difficult to say is a gamepad issue (Razer is not 100% identical as DS4 gamepad over BT) and this confuses DS4Windows or if exclusive mode is failing because in BT mode some other app opens a connection to the gamepad and this way prevents exclusive mode to work. Do you see a warning message about an error in exclusive mode in a logfile?
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Or if nothing else helps then HidGuardian would probably work, but you have to tweak its settings because Razer has a different hardware VID/PID identifier than 100%  compatible DS4 gamepads.

**Comment by glockmane** [comment]
There was an error at first while try to gain exclusive mode but after disabling the mentioned nVidia service the error was gone and also no warning in the protocol (or is there another log besides the the one on the screenshot I posted?).

Tried with HidGuardian and HidHideTest but didn't know what to click in the HidHideTest App (I think I have to uncomment the device and I think I uncommented the wrong device..).. Managed to get it hidden with HidGuardian and HidCerberus which is kind of easier to understand for a noob as you see the device with name and the hide button besides it..

![image](https://user-images.githubusercontent.com/2814025/96186628-03bb6800-0f3c-11eb-864c-7e1fb2056789.png)

**Comment by Ryochan7** [comment]
The old "Hide DS4 Controller" option will no longer exist for a few reasons. HidGuardian is going to be the main means of hiding a DS4 from the system going forward. I don't really like having to rely on a deprecated driver but it is the most reliable option.

With HidGuardian, you will likely need to add two rules for your controller depending on its connection: one for USB and one for BT. The more specific Hardware Ids for the controller will differ depending on the connection type.

HidCerberus is okay but I find that it bogs down my system and introduces input latency. It seems like other people have had issues with HidCerberus after running Windows updates in the past as well.
