### ISSUE TITLE
Hide DS4 works, but camera still often spins left side

### ISSUE THREAD

**Issue by 1guy2balls** [Ryochan7/DS4Windows#1533]
So I got my hide ds4 controller option finally working. But the problem seems to be in something else (controller works perfectly itself, it's kinda new). It happens randomly as I noticed, RS can center fine after pulling left, but other time it keeps pulling itself hardly to the left. Only thing can stop it is pulling to the right side with a finger. Having default settings in a controller profile.
Sorry for semi-russian text.
![settings](https://user-images.githubusercontent.com/20609833/96366299-8405e700-114f-11eb-9cf2-cdf5ce40b591.jpg)
 I'm out of knowledge how to fix this.

**Comment by 1guy2balls** [comment]
Forgot to say that I noticed strange thing. In a game when it shows xbox ABXY it superfast blinks with same buttons of PS, like A-X. Looks like 2 controllers trying to replace each other

**Comment by mika-n** [comment]
spinning camera is a classical example of when "Hide DS4 Controller" or HidGuardian is not setup correctly (double controller issue). What do you see in JOY.CPL controlPanel applet and in a logfile after starting DS4Windows app and before and after connecting a gamepad?
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Drifting is another classic and it is in 99.999% cases a deadzone issue (once you have solved the double controller issue).
https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping

Based on the screenshot looks like your SixAxis deadzone is wrong because it is "100% deadzoned" (=the red area). It could be a bug in localizated number/decimal format where dot and comma are interpreted vice-versa (decimal or thousand separator).

**Comment by 1guy2balls** [comment]
> 
> 
> spinning camera is a classical example of when "Hide DS4 Controller" or HidGuardian is not setup correctly (double controller issue). What do you see in JOY.CPL controlPanel applet and in a logfile after starting DS4Windows app and before and after connecting a gamepad?
> https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
> 
> Drifting is another classic and it is in 99.999% cases a deadzone issue (once you have solved the double controller issue).
> https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping
> 
> Based on the screenshot looks like your SixAxis deadzone is wrong because it is "100% deadzoned" (=the red area). It could be a bug in localizated number/decimal format where dot and comma are interpreted vice-versa (decimal or thousand separator).

I don't know what is JOY.CPL - pls guide me there. I guess log file pretty clean?
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5398027/ds4windows_log.txt)
Just set numbers from the second link. Also my default dead zone for SixAxis is 25.00.
![full_settings](https://user-images.githubusercontent.com/20609833/96377760-58efb780-1190-11eb-9d76-6ff8a3f75509.jpg)

Maybe I should try to erase all drivers I installed for my dualshock and try to reinstall purely the ds4win?

**Comment by 1guy2balls** [comment]
Also, is this okay having both black and grey squares there?
![squares](https://user-images.githubusercontent.com/20609833/96377791-99e7cc00-1190-11eb-9f75-f8350d943096.jpg)

**Comment by mika-n** [comment]
Just run JOY.CPL command in Windows StartMenu. It opens the WinOS gamepad config screen. Another way to open this screen is to click "Control panel" link in DS4Windows Settings tab page.

The logfile looks OK:

The gray and black dot visualizes how the axis output looks like when it comes from a physical gamepad and how it is translated when it goes through all those sensitivity/deadzone/antideadzone/curve settings in DS4Windows app (output). The red area shows the size of deadzone.

 The values below the controller reading images are (I) = input from physical gamepad and (O) = output when DS4Windows has done its magic. If you don't set any tweaks in DS4Windows then I and O are identical, but now you have deadzone and especially anti-deadzone set so those two vary slightly (it is expected behavior).

SixAxis deadzone 25.0 is wrong because the value should be 0.0 - 1.0 (0% - 100%). So 25.0 means the deadzone is more than 100% so that's why the SA reading box is all red (ie. sixaxis output is zero all the time). Set this to something like 0.10. But if you don't use sixaxis for anything then this doesn't matter.

**Comment by 1guy2balls** [comment]
There were 2 controllers xbox 360 and wireless controller, when I finally turned on Hide DS4 function - xbox controller disappeared.
Don't think I'm using sixaxis for anything, so let it be as is.

Have to mention that outside the game there is no such left pulling. Looks like it only happens ingame. But which number should I set for deadzone for RS so I can test it?

**Comment by mika-n** [comment]
Xbox controller disappeared? Weird because it is the probably the virtual output controller created by ViGem driver and DS4Windows app, so it should remain visible but Wireless controller should dissappear (=physical controller).

WirelessController is the name DS4 gamepad uses (even when you connect the gamepad over USB cable it is shown here with WirelessController name).

Try to tweak the RS deadzone value up +0.10 step at the time and see when it is big enough (=no drifing anymore).

**Comment by 1guy2balls** [comment]
I forgot to say that turn on DS4 appearance in Profiles>*profile*>other>emulated controller. That's probably why. Also 0.09 deadzone already made it better, just played an hour and only 1 easy left pull noticed, will set 0.10 👍
