### ISSUE TITLE
Ds4w Charging Issue

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#1539]
https://youtu.be/B2GRtvCRcnE

The program has trouble charging the controller to full on its own. It can be on 90+% for hours. Unplugging and replugging will then show a different charging result.

**Comment by mika-n** [comment]
Try playing with the "Quick Charge" option in DS4Windows. Anyway, DS4Windows app itself really doesn't have anything to do with how the pad is charged and what battery level it reports to a PC. DS4Windows app simply shows the data what is coming from the gamepad.

Some 3rd party copy-cats may report weird results especially over BT connection. Again, this is an issue with those copy-cats and not in DS4Windows app because some gamepads sends the battery level info in non-standard DS4 format. Yes, DS4Windows app could try to understand all these variations, but it would be never ending battle with hundreds of cheap chinese copies which are not 100% compatible.

**Comment by maximus105** [comment]
I have original DS4 v2. When connecting via BT, I see the lightbar blinking randomly for 1 second in red or yellow. Although I have all the RGB sliders set to 0. And all lightbar blinks when charging or discharging are also disabled. I noticed this back when there was a non-original DS4 v2, which was defined as v1. It also had these random blinks. Although the battery was 100% charged. I don't remember which version of DS4WINDOWS it started with. But in the latest version 2.1.15 this problem is still present. Does this refer to DS4Windows charging issue? Or does it make sense to highlight this problem separately?

**Comment by shinra358** [comment]
> Try playing with the "Quick Charge" option in DS4Windows. Anyway, DS4Windows app itself really doesn't have anything to do with how the pad is charged and what battery level it reports to a PC. DS4Windows app simply shows the data what is coming from the gamepad.
> 
> Some 3rd party copy-cats may report weird results especially over BT connection. Again, this is an issue with those copy-cats and not in DS4Windows app because some gamepads sends the battery level info in non-standard DS4 format. Yes, DS4Windows app could try to understand all these variations, but it would be never ending battle with hundreds of cheap chinese copies which are not 100% compatible.

I have genuine sony pads

**Comment by mika-n** [comment]
Do you have "Flash lightbar at high latency" option enabled (Settings tab page)? Or maybe the latency warning threshold is too low for your setup?
The logfile should show a warning message also if the lightbar is blinking because of high latency (over BT communication).

You can also disable the battery related ligthbar color functionality by setting the FlashAt (profile/Ligthbar tab page) value to -10.

**Comment by shinra358** [comment]
Flash lighbar is checked and says 30ms. I dnt see reason for looking at this since it's dealing with controller being wired.
Disabling features i want to use is not a solution 😂

**Comment by maximus105** [comment]
@mika-n Thanks. I disabled "Flash Lightbar at High Latency: 20 ms" and set "FlashAt: -10%". After that, the lightbar stopped flashing randomly for 1 second.
I sometimes have the following in my LOG file:
2020-10-24 18: 33: 30.3098 | WARN | Controller 1's latency over 10ms (28.95 ms)
2020-10-24 18: 33: 30.3603 | INFO | Controller 1's latency now under 10ms
2020-10-24 18: 33: 30.9524 | WARN | Controller 1's latency over 10ms (22.85 ms)
2020-10-24 18: 33: 31.0134 | INFO | Controller 1's latency now under 10ms
2020-10-24 18: 33: 38.6378 | WARN | Controller 1's latency over 10ms (34.55 ms)
2020-10-24 18: 33: 38.6705 | INFO | Controller 1's latency now under 10ms
2020-10-24 18: 33: 40.9887 | WARN | Controller 1's latency over 10ms (35.65 ms)
2020-10-24 18: 33: 41.3901 | INFO | Controller 1's latency now under 10ms
2020-10-24 18: 33: 41.4315 | WARN | Controller 1's latency over 10ms (20.05 ms)
This is normal? What is causing this high latency, and how can this be fixed?
I have BT Poll Rate: Max (1 ms) set.

**Comment by mika-n** [comment]
The latency warning msg means that for some reason the PC and BT channel are having a hard time trying to keep up with the update frequency. Sometimes messages are not travelling fast enough over BT when you see this msg. 

You can try to set the BT poll rate to something like 4ms or 8ms and see if it makes any difference.

But, often the latency is something DS4Windows cannot do much about it in a software side. Please go through these steps, but it nothing helps then BT dongle/chipset in the laptop or PC is not up to the task. 
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#gamepad-connection-over-bluetooth-bt

If you have a BT dongle then try attaching in at the end of USB extension cable and this way taking the dongle closer to gamepad and further away from the radio storm caused by PC/laptop (especially WIFI). And try different usb ports.

**Comment by shinra358** [comment]
Closed with no indication of whether or not initial post was fixed

**Comment by mika-n** [comment]
The battery level value shown in DS4Windows is just showing what the gamepad reports back to the PC. And there are slight differences in how the value is reported when the pad is in charging state or without a charger cable connected.

If charger is connected then it is expected that DS4 reports the battery level as ">=100" index value before the battery is reported being "fully charged". If the charger is not connected then DS4Windows shows ">=95" level as full (the battery level value sent by 95 is not exact value and it has slight fluctuation).

Now, if the battery level never reach "full" status when the charger is connected then there must be something wrong in the battery/ds4/charger because DS4 never reports the battery being "fully charged" (ie. the battery value of HID input report never reach >=100 value). 

Now when you disconnect the charging cable and if the status is then shown full then it means that DS4 pad reports some value >=95 and <100. In theory DS4Windows code could be changed to accept >=95 as being fully charged even in charging mode, but then someone would complain why the battery is shown full even when it is not yet 100% full.

Closed as "not a bug, but a definition of what is full or not full".

**Comment by shinra358** [comment]
Except xboxstat (that comes w xinput drivers) has no problem reporting
battery values accurately 😂

**Comment by mika-n** [comment]
different apps may use different value ranges to report "full, medium, low" values or to scale for example all >=95 values coming from DS4 as "100%".
