### ISSUE TITLE
I need help please.

### ISSUE THREAD

**Issue by jkyt09** [Ryochan7/DS4Windows#154]
I wasn't sure where to post this so sorry if this is the wrong place. I think I tried just about everything to make my nacon revolution pro controller to work on my pc. DS4Windows can't detect my controller even though its plugged in. If someone could help me with this that would greatly appreciated.

**Comment by Ryochan7** [comment]
I do not own a Nacon Revolution Pro controller. Does the log show that the
controller was detected at all? It would be easier to fix the problem if it
was just a matter of not having the proper VID and PID for the device.


On Nov 18, 2017 5:11 PM, "jkyt09" <notifications@github.com> wrote:

I think I tried just about everything to make my nacon revolution pro
controller to work on my pc. DS4Windows can't detect my controller even
though its plugged in. If someone could help me with this that would
greatly appreciated.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ryochan7/DS4Windows/issues/154>, or mute the thread

**Comment by jkyt09** [comment]
nope not at all. My PC does but not the program, my friend's actually works the program so I'm not too sure what the problem is.

**Comment by Ryochan7** [comment]
I would suggest that you try to use the controller while running HID Report Listener. Some of the information given in the program would be useful and it would help diagnose if the controller can be read in HID mode.

https://inputmapper.com/downloads/download/5-tools/75-hid-report-listener

**Comment by Yuki-nyan** [comment]
@jkyt09 I'd try checking in device manager to see if there are any disabled Human Interface Devices as I've had Windows disable the HID devices for both my original DS4s and my Nacon Revolution Pro on a few occasions seemingly for no reason, resulting in the usual sound when I plugged in the controller but it not being detected by DS4Windows.

If on the other hand you have the Nacon Revolution Pro 2 rather than the original (with the USB C connection) then it probably does have a different PID so support will need to be added - however, there should be a switch on the back of the controller to toggle it into PC mode which makes it fully XInput compatible, albeit without the ability to use the touchpad.

**Comment by UnholyScribe** [comment]
How do u check to see if there are any disabled Human Interface
