### ISSUE TITLE
Wrong context for selected profile button

### ISSUE THREAD

**Issue by lifehome** [Ryochan7/DS4Windows#155]
Step to reproduce:
1) Open DS4Windows
2) Plug in a DS controller, let it identified by the program
3) Observe the button between selected profile and the color box, it's wrong and I don't even know what it says. **Too small for a word?**

**Comment by Ryochan7** [comment]
I have seen that before but didn't look into fixing it. It seems to happen
when the button is not using the text Edit.

On Nov 19, 2017 6:13 AM, "lifehome" <notifications@github.com> wrote:

Step to reproduce:

   1. Open DS4Windows
   2. Plug in a DS controller, let it identified by the program
   3. Observe the button between selected profile and the color box, it's
   wrong and I don't even know what it says. *Too small for a word?*

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ryochan7/DS4Windows/issues/155>, or mute the thread

**Comment by Ryochan7** [comment]
That column has been switched to auto resize so that should work around the problem.
