### ISSUE TITLE
Sekiro Shadows Die Twice - Camera spins out if "Hide DS4 Controller" option is unchecked

### ISSUE THREAD

**Issue by gigabit942007** [Ryochan7/DS4Windows#1570]
**Describe the bug**
With Sekiro Shadows Die Twice, the camera spins out of control with the "Hide DS4 controller" option unchecked.

**To Reproduce**
1. Run the default profile
2. On the profile settings go to the Other tab and check as it follows:
- Emulated Controller: Xbox 360
- BT Poll Rate: Max
3. On the program Settings Tab:
- Uncheck Hide DS4 Controller
4. Controler works but the camera spins out.

**Expected behavior**
Camera should not spin.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 20H2
 - DS4Windows Version 2.1.16

**Additional context**
If i check the "Hide DS4 Controller" option in the main settings tab, then the camera works fine and i can play the game.

**Comment by mika-n** [comment]
Double controller issue explained several times here already.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#double-input-problem-in-games-game-does-all-sort-of-weird-things-when-i-press-a-button-second-player-drops-in-cannot-navigate-in-menus-because-focus-moves-two-lines-when-i-press-a-key-just-once-etc

**Comment by Ryochan7** [comment]
This has been a thing with FromSoftware games since at least the PC port of Dark Souls 1. Exclusive access has to be working or the game will attempt to read from the DS4 DirectInput device. The camera spinning is due to how the game reads the values from the DS4 triggers.
