### ISSUE TITLE
High contrast problems

### ISSUE THREAD

**Issue by jernejs** [Ryochan7/DS4Windows#158]
I'm running Windows in High Contrast mode, which causes most bitmaps in DS4Windows to become invisible - it looks like this is because BackgroundImage is being used, which is ignored in high contrast mode.

![Screenshot](https://eternallybored.org/misc/imgs/ds4windows/hc.png)

**Comment by Ryochan7** [comment]
It does look like using the BackgroundImage property for a panel does not work right when using High Contrast mode in Windows. I can't find any change in properties that will make it work. Using a PictureBox control and setting the Image property works just fine for the same images. The panel would still have to exist so that overlaying controls still works as intended.

There are also other parts of the program that don't look quite right when running Windows in High Contrast mode.

**Comment by Ryochan7** [comment]
The original idea of using a PictureBox control won't work. Controls will get overlaid fine but the buttons will use the assigned window background color rather than using the segment of the PictureBox that it is hovering over. I have found that hooking into the paint event for the panel can work for having a background image work properly in High Contrast mode and buttons hovered above will be transparent.

**Comment by Ryochan7** [comment]
Oddly enough, it looks like this change has reduced input lag. An instance of the Options form is loaded at all times. Window rendering seems to be quicker as well. The main disadvantage is that the BackgroundImage is still set initially for Designer mode only to be disabled at run time.

**Comment by jernejs** [comment]
Thanks for taking care of this!
