### ISSUE TITLE
[FEATURE REQUEST] Allow pairing of joycons

### ISSUE THREAD

**Issue by BSoDGamingYT** [Ryochan7/DS4Windows#1592]
If possible, the addition of the ability to pair two single joycons (left and right) would be invaluable to many emulators/programs. 

This would allow both to be uses as a single input device.

**Comment by Ryochan7** [comment]
I am not sure how I would go about trying to add that feature. Been trying to think it through a bit to maybe play Halo 4 using a split JoyCon config. That would only be possible currently with KB+M emulation. For the most part, I would use the Switch Pro controller when I would want to map to a single XInput device.

**Comment by BSoDGamingYT** [comment]
BetterJoy achieves this functionality, so perhaps that is somewhere to begin?
https://github.com/Davidobot/BetterJoy

**Comment by cherreline** [comment]
Would it be simpler to not restrict pairing to joycons? Personally, I can think of a few use cases for being able to pair any number of input devices together into a single virtual controller. 

- pairing joycons so you can use them the way they were meant to be used
- dual-wielding your playstation/xbox controllers like joycons to give your wrists a break from their usual position (or as a workaround for a broken button)
- adding co-op to single player games or turning couch co-op games into team games

Since L/R joycons seem to have very little in the way of input overlap (aside from maybe the gyroscope data?), they shouldn't need much more configuration than just assigning them to the same virtual controller, and all of the other use cases I can think of can be addressed by ensuring users can disable conflicting inputs on a per-device basis as needed.

**Comment by Ryochan7** [comment]
The biggest challenge is copying input state data from each JoyCon input thread and merging the state data into one DS4State instance. That needs to be done before hitting the mapping routine. Mapping from a DS4State instance to the output controller happens very late in the routine so that won't matter as much.

The need for a single DS4State instance would kill the idea of binding multiple arbitrary controllers to one output controller without an additional mapping routine. The assumption of default XInput controls in the main mapping routine when no output binding has been explicitly mapped adds another hurdle. That would not be so much a problem with the JoyCons since there is only input overlap for the Gyro data. Even then, the Tilt Controls mode uses no implicit output binding.

The initial idea for unified JoyCons was to add an additional device class that would handle the mapping of each device's state data to a unified DS4State instance. Each JoyCon input thread would be hooked to that class rather than the mapping routine. It would at least allow for two JoyCons to be mapped to one XInput controller but it might present problems for some Gyro output modes.

**Comment by Ryochan7** [comment]
This feature was introduced in version 2.2.10. However, UDP server support was not tested prior to that release; the main goal was just to get 2 JoyCons to map to 1 Xbox 360 controller. The last couple of commits (especially commit ce8161171b0b474fddd7e902548e2abef5009e42) fixes some issues with Joined JoyCon support when it comes to the UDP server. The joined device state was not being used for the UDP server routine and Gyro Roll on JoyCon R was inverted when it wasn't necessary.

Not sure if it will be that useful but at least this should work in version 2.2.11.

**Comment by Ryochan7** [comment]
Version 2.2.11 is now out. UDP server usage with Joined JoyCon controllers is now possible.

https://github.com/Ryochan7/DS4Windows/releases/tag/v2.2.11
