### ISSUE TITLE
my ps4 controller is not working although it`s detectable in DS4 Windows

### ISSUE THREAD

**Issue by omaar1997** [Ryochan7/DS4Windows#1598]
I don`t know what happened, I was playing for almost 2 weeks now with my ps4 controller using DS4 Windows and i had no problem and everything was fine, then one day everything went wrong i don`t know what happened, i connected my ps4 controller through Bluetooth  AS USUAL and opened DS4 Windows.exe AS USUAL but when i opened my game i noticed that the controller isn`t working !!!! it`s detectable by the pc and the DS4 Windows program but when i launch any game it simply can`t detect the controller, i keep pressing all the buttons in the controller while i`m in the game that tells me " press any button " but still nothing.....as if the controller isn`t working or isn`t detected by the game. 
BUT when i change the setting " Emulated Controller " in my profile settings from " DualShock 4 " to " Xbox360 " everything works fine !!!!!! and the game detects the controller and everything is fine now.
PLEASE GUYS HELP ME.

![Screenshot 2020-11-26 213454](https://user-images.githubusercontent.com/31675083/100386887-4b4f0c80-302f-11eb-8c3c-728081c2dcbd.png)

![Screenshot 2020-11-26 213511](https://user-images.githubusercontent.com/31675083/100386890-4d18d000-302f-11eb-9d19-dbe93c4018cc.png)

**Comment by Genosystem** [comment]
It's a Steam game? do you change the Steam Controller Mapping Support?

**Comment by omaar1997** [comment]
> It's a Steam game? do you change the Steam Controller Mapping Support?

no it`s not plus i don`t have steam installed on my pc

**Comment by Genosystem** [comment]
what's the problem with configure the controller as Xbox? The games are usually designed for Xbox controller.

**Comment by omaar1997** [comment]
> what's the problem with configure the controller as Xbox? The games are usually designed for Xbox controller.

i'm a ps4 gamer so i'm not used for xbox configuration such as Y and A and B and so on.

**Comment by Genosystem** [comment]
Ok, but the initial description of this program is: "DS4Windows is an extract anywhere program that allows you to get the best DualShock 4 experience on your PC. **By emulating a Xbox 360 controller**, many more games are accessible."
Many games don't work or show Playstation button because don't support it.

**Comment by Masamune3210** [comment]
Make your whole life easier, just get used to XInput. Most games have either severally limited or broken DInput, so it's usually just not worth the hassle. If you really want to stick with DInput, make sure all your settings in DS4Windows are correct and maybe even reset them to default if you want to make sure

**Comment by mika-n** [comment]
Have you gone through the troubleshooting tips?
- Try a new default "empty" profile (create a new profile in DS4Windows app, but don't change anything else but the output controller type from xbox to ds4 ode)
- What do you see in ControllerActivity tab page in DS4Windows? Any activity when you move LS/RS or gyro?
- What do you see in JOY.CPL controlPanel applet (run JOY.CPL command in Start menu/Run)? One or two gamepads and what is the name of those devices? Can you see activities there when you press buttons?
- What do you see in https://gamepad-tester.com/ web site?

https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

**Comment by Ryusennin** [comment]
Pro tip for Playstation users complaining about Xbox buttons:

Learn the Xbox layout (the hard way) by playing karaoke in any Yakuza game. You'll become fluent in a couple of minutes.

**Comment by omaar1997** [comment]
> Have you gone through the troubleshooting tips?
> 
> * Try a new default "empty" profile (create a new profile in DS4Windows app, but don't change anything else but the output controller type from xbox to ds4 ode)
> * What do you see in ControllerActivity tab page in DS4Windows? Any activity when you move LS/RS or gyro?
> * What do you see in JOY.CPL controlPanel applet (run JOY.CPL command in Start menu/Run)? One or two gamepads and what is the name of those devices? Can you see activities there when you press buttons?
> * What do you see in https://gamepad-tester.com/ web site?
> * The logfile content?
> 
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

i tried all of them but nothing worked :( .
thanks for your help anyway.

**Comment by mika-n** [comment]
Logfiles? See %APPDATA%\DS4Windows\Logs folder and post the latest logfile here (rename the file as .TXT and drag-n-drop to a comment field).

And you didn't reply what did you see, for example, in JOY.CPL. It would tell us a clue if there is problems with exclusive access or creation of virtual output controller and so on.

Do you use exclusive access ("Hide DS4 Controller" option or HidGuardian driver to hide the physical controller)? 
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

The logfile would tell all this, so that's why troubleshooting asks to provide that as the first thing. Don't keep things hidden because it just makes difficult to help because we have to guess what is going on under the hood.
