### ISSUE TITLE
[Feature reqeust] divide touchpad click in zones

### ISSUE THREAD

**Issue by TheMasterDingo** [Ryochan7/DS4Windows#1599]
There are some games ( Death stranding for example) that do different things if you press the touchpad on the right or on the left.
Would this be possible to make, i mean registering as ds4 touchpad click left or right not mouse click?

**Comment by Xurca86** [comment]
Isn't there a mapping option in the edit profile, under controls for this? I have mine set as back (left touch) and start (right touch). Have you tried customizing a profile for that game?

Or am I not understanding this question? Cause I think there's already a way to do this. If the game have native support for a ds4 controller, should it have a option to map buttons to it?

**Comment by mika-n** [comment]
There is already left, right, upper and multi-touch regions and you can re-map those to do anything.

**Comment by TheMasterDingo** [comment]
Yes you can remap them but the output is the same Touchpad click, some games recognise natively touchpad click left and touchpad click right( when for example connecting the ds4 in usb).
Not sure if i explained it right? If not tell
Me i will post some pics

**Comment by mika-n** [comment]
Aah okey. Now I got your point. DS4Windows can re-map those touchpad regions to any kbd, mouse or gamepad key or macro events, BUT touchpad click is just one "touchpad click" event. At the moment it is not possible to send touch regions through the virtual output controller because the current version of VigEm driver doesn't support virtual touchpad events. ViGem team is working on adding a support to virtual touchpad events (ie. the x/y coordinate of the touchpad swipe or click point) but the feature is not yet available.

**Comment by Ryochan7** [comment]
That is not possible due to limitations of the ViGEmBus driver when emulating a DS4. The current stable version has no support for mapping Touchpad coordinates. I believe that has been resolved in the current ViGEmBus code but no new driver has been released with that functionality yet.
