### ISSUE TITLE
Disconnect PS + OPTIONS doesn't work

### ISSUE THREAD

**Issue by shirodevo** [Ryochan7/DS4Windows#160]
Hey,
First thanks for your amazing work. I just have a question i can't make the disconnect option work. It does on Jays2King original DS4 but since i switched to yours which i find better i can't disconnect using the macro i tried modifying it to other buttons or combinations but still with no success.
Thanks

**Comment by TristanYoung** [comment]
I just tested it on mine, and it works.  This is how I did it:

1. Click on the PROFILES tab.
2. Click on the SPECIAL ACTIONS tab.
3. Click on NEW ACTION.
4. Give your special action a name, eg: Disconnect
5. Put a checkmark on both the PS and OPTIONS triggers.
6. Select an action: DISCONNECT FROM BLUETOOTH.
7. Select an appropriate HOLD FOR time.  eg: 0 seconds
8. Click SAVE.
9. Click SAVE PROFILE.

Test the new special action.

Let me know if that works for you.

**Comment by Ryochan7** [comment]
Tested this with version 1.4.100 and the latest Git code. The Disconnect BT special action works fine with both builds on my system.

**Comment by SeemsFishy** [comment]
On my side:

This feature does not work with official wireless adapter if you are not using an exclusive mode aka "Hide DS4 Controller".
However, as for a regular BT Dongle - this feature works  for both mods, exclusive and non-exclusive.

Ryochan7, can you check this plz?

**Comment by Ryochan7** [comment]
Using the Sony dongle would explain it. That is actually intentional behavior that stems from how the hardware behaves. Unfortunately, the Sony dongle is always presented to Windows as a controller no matter if a DS4 is paired with it or not. Because of that, the only things that happen in DS4Windows when you disconnect a DS4 from the dongle is that the controller ID changes to a blank serial and any virtual XInput controller associated with the dongle is unplugged.

Because this is not a bug, this issue can be closed.
