### ISSUE TITLE
High ping while connecting/disconnecting a controller

### ISSUE THREAD

**Issue by vismaramatteo** [Ryochan7/DS4Windows#1609]
When I connect/disconnect the controller, for 30 seconds my internet goes really slow (showing 5000 ping on discord or stopping videos/livestreams).
To connect to internet I use an USB Wifi Adapter, so I think the problem is some sort of conflict issue between USB devices.

**Comment by mika-n** [comment]
Conflict or out of bandwidth in the usb host. Maybe, but unfortunately DS4Windows app cannot do anything about it. Try connecting wifi adapter and ds4 gameapd to different usb ports in case your PC has two usb hosts both serving some of the usb ports.  Or try using BT connection with DS4 instead of usb.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

But, this doesn't sound like a DS4Windows app issue, so I'm closing this ticket.
