### ISSUE TITLE
DS4 Stopped Working

### ISSUE THREAD

**Issue by Ryzack** [Ryochan7/DS4Windows#161]
I've been using it without too many issues for a while, but now the lightbar flashes orange and nothing happens. I've tried restarting DS4windows, unplugging and replugging the controller in and making sure steam was closed while doing so

**Comment by Ryzack** [comment]
Re-Enabling HID Game Controller Driver in Device Manager fixed this, thank you!

**Comment by Ryochan7** [comment]
Although this problem happens less often than with the old versions, using the current exclusive mode workaround causes controllers to get permanently disabled at random times. I should have updated the README by now with a note about re-enabling devices. The only decent solution to the problem is to stop using that workaround and use HidGuardian instead. It is a safer and better method to force grabbing exclusive access to a device. The current stable version introduces input lag but the latest code fixes that problem. I have been using HidGuardian for the past few weeks and it works great.

**Comment by Ryochan7** [comment]
I double checked and I did let a change slip through before actually committing it to version control. Version 1.4.100 does write the HidGuardian whitelist registry key when DS4Windows is run as admin. You can actually use HidGuardian with DS4Windows (without needing WhiteKnight) although you have to write the affected devices registry entry yourself. The disable and re-enable method will be used if you do not have HidGuardian installed on your system.
