### ISSUE TITLE
Game exe not staying on HidHide Test

### ISSUE THREAD

**Issue by SurfingCats** [Ryochan7/DS4Windows#1615]
I'm using HidHide Test to whitelist exe I want my DS4 (v2) to work on. 1 game (Call of Duty Black Ops Cold War) will not stay in the right column to allow my DS4 to work with. Every time I launch the game I have to re add it to the white list column. I put random programs on the right to see if they would stay after I closed them and they stayed.

Is this normal? Do I have to add the exe to "Allow" every time I want to use a DS4 with it?
![21591b91bacd49ef0432c571b70b50b3](https://user-images.githubusercontent.com/75226028/100622683-609d9280-32de-11eb-98f7-b3ad0e5e6b5a.png)

**Comment by mika-n** [comment]
Works as expected. HidGuardian works on process ID numbers, not on process names. Notice how the process ID changes each time you launch the game. 

DS4Windows app handles this by calling HidGuardHelper.exe tool to add the DS4Windows.exe process ID to the allowed list in HidGuardian registry (=Whitelist registry setting). With COD you have to do it yourself because HidHide tool doesn't actively monitor COD or any other app.
![HidGuardian_WhitelistRegistry](https://user-images.githubusercontent.com/35538525/100636133-0af6d380-333a-11eb-8dc3-de82b182eaf6.png)

One way to automate this via DS4Windows would be something like this:
- Setup an auto-profile rule to active certain COD specific profile
- Set "Launch program with profile" option in this profile to run your own custom script
- The custom script can look up the current process ID of COD app and to call HidGuardHelper.exe tool using this COD process ID as a cmdline argument. HidGuardHelper then takes care of adding the COD process to Whitelist sysreg list and to remove it when COD process is closed.
