### ISSUE TITLE
A macro can't only "play once" when it's set on a touchpad "swipe" action

### ISSUE THREAD

**Issue by WSXephon** [Ryochan7/DS4Windows#162]
Hi Ryochan7. 
I set the touchpad as "use for controls" and then set macros to the four "swipe" actions with the "play once" option . But I found that the macro will play time after time when my finger is keep swiping on the touchpad or stop swipe and keep finger on the touchpad after swipe. 
Would you let the "play once / repeat while held" option become effective when use macro on the touchpad?
Thank you!

**Comment by Ryochan7** [comment]
That functionality works fine for me. Both "Play Once" and "Repeat While Held" work as expected when using Touchpad Swipe controls with version 1.4.101.

**Comment by WSXephon** [comment]
I tested the touchpad actions and found that when I only set a macro to one of the four "swipe actions", and keep other three "unassigned" or "unbound", the macro will work good. But when I set macros to two or more than two of them, the "play once" option will not effective.
The code in the profile is like this:
`<Control>`
`    <Macro>`
`      <SwipeUp>65/65</SwipeUp>`
`      <SwipeDown>66/66</SwipeDown>`
`    </Macro>`
`    <KeyType>`
`      <SwipeUp>Macro</SwipeUp>`
`      <SwipeDown>Macro</SwipeDown>`
`    </KeyType>`
`  </Control>`
All the other options of the application is by default. You can have a try. 

By the way, I have two more little issues(?) to tell you. 

The first is after I set a macro, There is high possibility that all the macro will not work, incloud the "Special Actions" like "Disconnect Controller". I need to close and re-run the application to let the macros work again. 
And the second is you have set the "Cycle Programs" macro in the present by default. I have see the macro and I guess when the "play once" option is selected, the "switch programs" action will only play one time. But in fact, when I set the present macro to a button, then push and hold the button, the "switch action" will play every second until I release  the button. I don't know how it work like this. 

Please give me your advice. Thank you!

**Comment by Ryochan7** [comment]
Thank you for the more detailed breakdown. I encountered the problem once I enabled macros for two swipe controls. It turns out that a flag was not being set for swipe controls properly so enabling multiple swipe controls would change a flag and cause a macro to get executed again. The limited use case that I tried now works properly.

I am not sure about the Cycle Programs macro. It operates the same no matter if "play once" or "repeat while held" is selected but that behavior seems intentional. If it is intentional then I am not sure that I want to try to change it.
