### ISSUE TITLE
Feature Request: add filtering to the the Auto Profiles List

### ISSUE THREAD

**Issue by TrevCan** [Ryochan7/DS4Windows#1631]
As said in the title, it would be awesome to be able to filter by name (a-z or z-a) and also adding a search bar.

**Comment by mika-n** [comment]
You mean filtering on the list of active running process names and then adding a new filter rule using the result of this filter search?
Or do you mean that to create an auto-profile rule using some search filter logic to find a match with a running process/window titles?

If you mean to create a filter rule to match an auto-profile rule then there is already a wildchar logic in process/window title keyword fields.
https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules

If you meant a GUI screen to list all processes while creating these new rule keyword definitions then yes it would be possible, but that feature is probably on veeery low priority because there is the "Show auto-profile debug messages" option which lists names of active processes when you alt-tab between processes. You can use that logfile content to verify the exact process and window title name you need with a certain app.

**Comment by TrevCan** [comment]
I mean the last one, creating a search bar and a filter when having too many programs added. For example, if I added all the windows Start Menu Programs it's quite a hassle trying to find the program since they're not even ordered alphabetically, so that's why I was requesting the feature.

**Comment by mika-n** [comment]
Yes, agree but that's why I don't even use the "add all steam" or "add all start menu programs" command :-) 

I simply use the browse button or enable the "Show debug msg" option and then use the logfile to see what is the actual process and/or window title of certain app when I open and run it.

The filtering/search feature would be useful, but because it is not a critical show-stopper feature then I think this is on low priority.
