### ISSUE TITLE
Macro Recording Automatic Button/Key Release - Bug or Feature?

### ISSUE THREAD

**Issue by mrtostados** [Ryochan7/DS4Windows#1641]
**Describe the bug**
Hi, it's me again. I've noticed that, when recording macros, if a button is pressed during the recording, but not released, and recording is stopped, a button release event for that button is automatically added to the end of the macro. I'm uncertain if this is intentional, or a bug. I see huge potential benefits for open-ended/non-terminating macros, if their implementation is possible. Feel free to get rid of this if, for instance, it's a totally unavoidable fault of the program itself or something that hasn't been implemented for a reason.

**To Reproduce**
1. Open profile editor
2. Navigate to "special actions" tab
3. Create a new special action
4. Choose "record macro" from the dropdown list and click the eponymous button to open the associated window
5. Begin recording
6. Press any button, key, etc. (I used cross, for example) &mdash; or any combination of buttons and keys &mdash; and keep it/them depressed
7. Stop the recording
8. Observe as a release event is automatically created for each button/key not released before the recording was stopped

**Expected behavior**
I guess I don't know what I expect. Leaving a macro open is basically the same thing as a toggle, but it's much cleaner and more convenient as far as I can tell to use one "record macro" in place of a number of "press/toggle key"s. Now, I may be totally wrong, and there's some sort of functional limitation that prevents an open-ended macro, or some compatibility concerns etc. 

**Desktop (please complete the following information):**
- Controller Make and Model: Sony DualSense (model CFI-ZCT1W)
- OS: Windows 10 Home v. 10.0.18363 build 18363
- DS4Windows Version 2.1.19

**Comment by mika-n** [comment]
Intentional feature, because if macro would by default leave all buttons to "down event state" then support channel here would be full of messages where people complain why the button is still held down even when I have released the macro button on a gamepad.

But there is the "Keep key state" option you can enable and then if a button is left in down state in the macro then the macro engine won't automagically reset it back to default state. It is up to the macro to leave buttons in correct state when the macro si completed.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#special-action-record-macro-run-a-macro-options
