### ISSUE TITLE
Problem with official DS4 dongle

### ISSUE THREAD

**Issue by porterballs** [Ryochan7/DS4Windows#165]
hello i have been having a few issues in regard to using ds4windows with the sony official ds4 dongle, usually this is what happens, i will switch on my PC and then turn on my DS4 controller, it will connect to my dongle but ds4windows wont pick it up and wrap it as a xbox controller, i have to go on hardware in control panel and the dongle is showing a yellow exclamation mark i then have to remove the device in control panel and reattach it to my pc for windows to install it again then it will work for a while. 

The problem will begin again usually when i start up my pc i switch my controller on and it doesnt connect to ds4windows and i have to go through the same process, the only thing that sometimes fixes it is unticking and ticking HIDEDS4CONTROLLER. But more often than not that will not work and it will be the same process of uninstalling the dongle.

 I don't know if i am doing something wrong i have been using DS4 for over a year and this issue has been happening the last 3-4 months or so. My only theory is its something to do with the  HIDEDS4CONTROLLER option, i have it set to start up with windows as a task, and occasionally ds4windows will pick up my controller but it wont turn it into a xbox controller, sorry if this sounds confusing i wanted to be as detailed as i can if you need to provide any screenshots of what i am talking about would be happy to do so thanks for all your hard work any suggestions would be great.

**Comment by Ryochan7** [comment]
I don't really use my Sony dongle except for testing. The primary
connection type that I use is Bluetooth. Problems like that would probably
be due to the current exclusive mode hack. I have tried to make issues
happen less often but issues still happen every once in a while for unknown
reasons. At some point, that exclusive mode hack needs to be replaced with
HidGuardian. I have been using a custom version of HidGuardian for a few
weeks and it has been working great.

**Comment by porterballs** [comment]
thanks for the reply and yea i think that's the main problem with whats happening on my end, sounds great will that be implemented into a official release at some point? other than i works great thanks for your work if you hadn't of taken up the program afterwards i wouldn't be using it anymore.

**Comment by Ryochan7** [comment]
For now, DS4Windows writes the needed whitelist registry key so that
HidGuardian will give access to hidden devices. That way, WhiteKnight is
not needed. Other utilities are needed to better use HidGuardian. The
changes that I made to HidGuardian have been committed upstream but no
official release with those changes has been published yet.

On Dec 3, 2017 1:29 PM, "porterballs" <notifications@github.com> wrote:

thanks for the reply and yea i think that's the main problem with whats
happening on my end, sounds great will that be implemented into a official
release at some point? other than i works great thanks for your work if you
hadn't of taken up the program afterwards i wouldn't be using it anymore.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Ryochan7/DS4Windows/issues/165#issuecomment-348807664>,
or mute the thread

**Comment by Ryochan7** [comment]
The most recent release (1.4.109) should fix the issue with devices getting permanently disabled. It wasn't until fairly recently that the issue could be replicated consistently. Lately, I have been using the old exclusive mode hack primarily rather than HidGuardian.
