### ISSUE TITLE
Option to press both controller input and macro at the same time

### ISSUE THREAD

**Issue by Shinoyami** [Ryochan7/DS4Windows#1654]
Give us an option to press both controller input and macro at the same time. On an early update it changed to not press both at the same time, give us an option if we want to press just the macro or both input and macro at the same time.

**Comment by mika-n** [comment]
Some earlier versions did this automatically (ie. sent the original btn event and run the macro attached to the trigger). This naturally was a problem in some scenarios because there was no way to prevent this. 

Now this current logic to ignore the original trigger event and just running the macro makes both options possible. You can simply run the original trigger key event as part of the macro if you want to fire away both events. You can even have two different macros attached to the same trigger key and DS4Windows will run these parallel at the same time. Other macro can do simple trigger key event and the other macro some more complex macro thing you want to execute.

**Comment by Shinoyami** [comment]
The problem is: even if you create the macro with the inputs plus the macro, that will not run the inputs. Maybe it's just a bug but macros are unable to execute the same set of inputs that it was pressed.
