### ISSUE TITLE
Get latest version from GitHub Releases API

### ISSUE THREAD

**Issue by GingerAdonis** [Ryochan7/DS4Windows#1657]
Hi! I've noticed the numerous `newest` file commits. Wouldn't it be better to get the latest version directly from GitHub Releases API? It's less prone to mistakes made by humans, and it doesn't pollute the commit history.

The API returns a JSON response which can be parsed relatively easy.
API url: https://api.github.com/repos/Ryochan7/DS4Windows/releases/latest

The API end-point includes various other useful meta data:
- Changelog (release description).
- Publish date.
- Download links for auto-updater.

Another benefit could be to make use of the pre-release function to enable auto-updating beta releases. A simple checkbox in the app or updater could select between stable and pre-release.

**Comment by Ryochan7** [comment]
Versions of DS4Windows before version 2.1 had no proper way to parse a JSON file. Version 2.1 was the first release that bundled the Newtonsoft Json.NET library. The older Jays2Kings hosted its newest.txt file on the server hosting ds4windows.com rather than pointing to a file stored in the Git repo.

I would rather stick with the current newest file approach. Also, the file is created during a build step so it should not be manually edited by anyone.
