### ISSUE TITLE
Support for Razer Raju Tournament is broken since version 2.1.20

### ISSUE THREAD

**Issue by FJRMaverick** [Ryochan7/DS4Windows#1659]
Beginning with version 2.1.20 my Razer Raju Tournament is no longer found by DS4-Windows. Until 2.1.19 everything worked fined. First screenshot is taken with version 2.1.22.

![image](https://user-images.githubusercontent.com/57774924/102132872-808f9300-3e54-11eb-9cf2-4fb4fe9e217b.png)
![image](https://user-images.githubusercontent.com/57774924/102133032-c51b2e80-3e54-11eb-9fa4-22c8d6e98bcc.png)

**Comment by mika-n** [comment]
Interesting. The first screenshot shows "index out of bounds". I wonder where it it coming from.
Have you tried to remove (or zip and backup) "%APPDATA%\DS4Windows" config and profiles files and to test it with new config/profile files with default values?

And maybe running the debug version and providing the latest logfile here as TXT file attachment? Rename the .log file as .txt and drag-n-drop the txt file here.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by mika-n** [comment]
@FJRMaverick Please download the debug version linked above because it already has the latest fix Ryochan7 linked above. Does it help with the issue? IF not then please provide the debug logfile.

**Comment by FJRMaverick** [comment]
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5695266/ds4windows_log.txt)

**Comment by mika-n** [comment]
The debug version seems to detect both the gamepad and a headset which it thinks is a gamepad (the headset device has type=0x5 flag). As a test try removing all other usb and BT devices, so those won't cause any confusion in DS4Windows app.

When you connect just the RajuTE BT device then do you see the "index out of bounds" error message in Logs tabpage in DS4Windows app?

And try to download a new version of the debug app because it now has few additional checks and debug messages while a new gamepad is connected. The logfile you provided did gave few clues why it may have failed (more like what was missing from the logfile game clues).

**Comment by FJRMaverick** [comment]
Sorry, I did not disconnect all other devices, since this is a hassle (and must work with all of them anyway and does it with 2.1.19 too). But I downloaded the new debug version and tested it with that. It still does not work, but the log looks quite different. I started without connected gamepad and connected it (via BT) after having started the debug version.

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5695872/ds4windows_log.txt)

**Comment by FJRMaverick** [comment]
After that I stopped DS4Windows (with the stop button) and then started it again with the gamepad still connected via BT.

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5695906/ds4windows_log.txt)

**Comment by FJRMaverick** [comment]
And finally another try after having disconnected the headset (USB). Then DS4Windows finds the gamepad and connects it.

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5695925/ds4windows_log.txt)

**Comment by mika-n** [comment]
So now the RazerTE over BT works with the debug version?

Please download yet-another debug version and give it a try even with the weird "headset faking to be a gamepad" device connected. Things should now work even with these unknown "gamepads" (in fact I added the headset to the list of ignored "gamepad" devices to avoid it being used by DS4Windows debug version and fixed few bugs how those unknown gamepads are handled).

And when you are testing different things and scenarios then please close the DS4Windows app and start it again because then the app generates a new "clean" logfile. Now when the same logfile contains messages from different experimental scenarios it is difficult see the whole forest because a single tree is blocking the view (as we say in Finland).

Anyway, Give a test run to the yet-another-debug-version.

**Comment by FJRMaverick** [comment]
BatteryReading does not work, and never did with the Razer gamepad since I've got it.
Same applies to Gyro (not even sure, whether the Razer Raiju TE has Gyros!?)

Otherwise everything else seems to work with the latest Debug-Version.
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5696739/ds4windows_log.txt)

**Comment by mika-n** [comment]
> BatteryReading does not work, and never did with the Razer gamepad since I've got it.
> Same applies to Gyro (not even sure, whether the Razer Raiju TE has Gyros!?)
> Otherwise everything else seems to work with the latest Debug-Version.
> _"difficult to see the whole forest because a single tree is blocking the view (as we say in Finland)."_
> We have a very similar metaphor in German, we call it "Cannot see the wood, because of all those trees" ;-)

I just had a flashback about the battery reading and remembered I might have stumbled on that when the RaijuTE special support was implemented ages ago. And when I looked at the code there was "NoBatteryReading" option set to RaijuTE, so the battery is always reported as 99% to avoid "low battery" warning messages. And there is "NoGyroCalibration" option also set, so could be that the gamepad doesn't even have a gyro (don't remember for sure).

You can continue to use the debug version until the next official version is released (the fix for RaijuTE is already there waiting for to be released).

And I'm not surprised if Finns borrowed the saying from Germany because traditionally Finland have had long and close relationship with Germany in the old times.

**Comment by FJRMaverick** [comment]
Thank you for your support. I will stay with 2.1.19 until the next version will arrive.
It's a shame that there is no battery support, one of the few things I miss with the Razer. Is it not possible with this pad?

**Comment by mika-n** [comment]
Possible YES, but because the pad doesn't speak 100% DS4 jargon someone with the hardware should debug which bit fields in the input HID data packet is a battery value. I'm sure it is somewhere there, but just not at the standard DS4 buffer location.

**Comment by FJRMaverick** [comment]
Can I help with that? Or is there no interest at all to implement that?

**Comment by mika-n** [comment]
The debug config file "DS4WindowsDebug.exe.config" has an option "Debug_PrintoutInputDataBuffer". This option dumps out the incoming data packets to "%APPDATA%\DS4Windows" folder. 
- Lay down the controller on the table (ie. don't press any buttons, don't move sticks, don't move gyro sensors)
- Set the debug option to true value and run DS4Windows app when then battery is fully charged (and don't touch the gamepad to make sure the output dump won't change any button bit flag fields. It will be easier to see where the battery reading is when most of the other bit fields remain the same).
- Close DS4Windows app and take a backup copy of the %APPDATA%\DSWindows\inputreportdata_bt.txt file (renamed like xxxx_100.txt to indicate that it is for a full battery dump).
- Now you can set the Debug_PrintoutputInputDataBuffer back to false and continue to use the gamepad business as usual (ie. to consume the battery juice).
- Wait till the battery seems to be half full (how you know this? do you have PS4 console which shows the battery reading for this gamepad?) or you just have to try to estimate how long you usually can use the pad without charging it.
- Lay down the gamepad and don't press those buttons!
- Set Debug_PrintoutInputDataBuffer=true
- Launch DS4Windows app
- Close DS4Windows app and take a yet-another backup copy of inputreportdata_bt.txt file and rename it like xxx_50.txt

Now to make things even better you could repeat all this until the battery is almost over to generate yet-another dump file and rename it like xxx_0.txt file.

Now you should have two or three dump files where all button events show the same bitflag values, but battery bit flags should somehow change. There are few values in the dump which for sure are different (sticks usually wobble a little bit, gyro is not completely stable, timestamp etc, but analyzing the dump against the DS4 data structure may give some clues where the battery value could be in that particular gamepad type).

**Comment by FJRMaverick** [comment]
Check, will do that, when I find the time for it.

**Comment by FJRMaverick** [comment]
Check, will do that, when I find the time for it.

Started today after having played yesterday with the pad, so it should be half (!?) drained. Will make another dump today, when batteries get low (yeah, they last quite a long time, much longer than those in the original DS4) and after that, when fully loaded again.

**Comment by FJRMaverick** [comment]
Can you please look at this dumps? I am not sure, whether I do everything correct (or whether the debug version does what it should). They both look pretty much the same and there is nearly no "relevant" data in it (at least this it how it seems to me).
[inputreportdata_usb_50%.txt](https://github.com/Ryochan7/DS4Windows/files/5725772/inputreportdata_usb_50.txt)

**Comment by mika-n** [comment]
Jep. Looks like the inputReport data doesn't have battery value at all or it is in some special input report not used by DS4Windows app at all. Based on this dump I would say it is too difficult to invest any time trying to debug this without having an actual hardware. If PS4 console can report the gamepad battery level then the value is somewhere, but where? Who knows...

**Comment by FJRMaverick** [comment]
Mhm, yeah the PS4 shows the battery level of the gamepad. 
But the Razer Raiju TE also has three different modes it can use, it has a hardware-switch for selecting PS4 (BT), USB or PC (BT) mode, which is nice because it can be paired with the PS4 and the PC at the same time. But that also means that it may act differently when connected with a PC (BT). Anyway, it was worth a try and would have been great if it would have been so "easy".

**Comment by Masamune3210** [comment]
Have you tried connecting to the pc in ps4 mode? maybe the battery report gets disabled on the pc setting?

**Comment by FJRMaverick** [comment]
I just got v2.1.22 ... it is still not working with my Razer Raiju TE:

![image](https://user-images.githubusercontent.com/57774924/103084110-78ff8500-45de-11eb-9407-a6221fff4cda.png)

**Comment by FJRMaverick** [comment]
I am not quite sure, whether it was 2.1.22 before too and the fix is to be expected in 2.1.23!?

**Comment by FJRMaverick** [comment]
Okay, my fault. It was 2.1.23 which just arrived and works as expected.
![image](https://user-images.githubusercontent.com/57774924/103140672-c6b4e400-46e9-11eb-9a27-0be2dffeeacd.png)
