### ISSUE TITLE
Vibration is not working properly

### ISSUE THREAD

**Issue by xuru-thor** [Ryochan7/DS4Windows#1663]
I'm currently using DS4Windows version 2.1.22, my OS is Windows 10 Pro version 20H2, and I'm using an official 2nd gen DS4, connected via USB.
This issue only started occurring a few days ago, maybe because of the latest update. The controller rumble is feels way too strong and doesn't stop when it should. For example, while shooting in Resident Evil 2, the controller will vibrate for ages when the shot has already been fired 4 seconds ago, and the gamepad will vibrate very strongly, when it was weaker before. I tested this with x360ce and it worked perfectly fine, so it's not the controller or the game's fault.
Must I put any more info?

**Comment by Macake** [comment]
I was having this same issue since yesterday, maybe.
I know this sounds weird but, I was messing with the settings just right now to see if I could fix it, and found out that the problem only occurs when the controller lightbar is set to full black (R=0, G=0, B=0), like wut.
Going to test some games to see if it's really it.

(Sorry if my english is a little off)

**Comment by Macake** [comment]
Yep. Seems to be it, at least for me. I was also having a problem with Rocket League recognizing my controller as player 2. Turned Lightbar on and it's all back to normal. No idea why this is happening though. It really just happens when all the color values are set to 0, if I set at least one of them to 1 or above, it fixes the problem.

**Comment by xuru-thor** [comment]
> I was having this same issue since yesterday, maybe.
> I know this sounds weird but, I was messing with the settings just right now to see if I could fix it, and found out that the problem only occurs when the controller lightbar is set to full black (R=0, G=0, B=0), like wut.
> Going to test some games to see if it's really it.
> 
> (Sorry if my english is a little off)

Oh my god, I have my lightbar set to black too. I'll test it out right now, but I think you're right.

**Comment by xuru-thor** [comment]
> > I was having this same issue since yesterday, maybe.
> > I know this sounds weird but, I was messing with the settings just right now to see if I could fix it, and found out that the problem only occurs when the controller lightbar is set to full black (R=0, G=0, B=0), like wut.
> > Going to test some games to see if it's really it.
> > (Sorry if my english is a little off)
> 
> Oh my god, I have my lightbar set to black too. I'll test it out right now, but I think you're right.

Yep, you're 100% right. Changed the lightbar color and now it works perfectly.

**Comment by mika-n** [comment]
There is a certain special logic in DS4Windows app how it treats RGB values (all zero VS non-zero), but it should not have such an effect that rumble is boosted and never stops. Anyway, RGB all-zero is treated as "lightbar off" state in DS4Windows app, but because lightbar and rumble data packets are part of the same HID output buffer then there may be some corner cases when RGB is all zero (=even when lightbar is "off" then the output buffer still have those bit fields when DS4Windows sends out a packet to DS4 gamepad to command the light and rumble motors).

But, good catch that having at least one non-zero RGB bit solves the issue.

**Comment by keatsandyeats** [comment]
I had this issue on v2.1.22, and it persists after updating to v2.1.23. The gamepad starts rumbling at the appropriate time, but only stops rumbling when it reaches the time limit set in the profile (i.e. if the time limit is 0, it will not stop rumbling). This affects both emulated DS4 and XB360 controllers. The rumble stops properly if the lightbar color is not 0,0,0.

Additionally, the lightbar takes about four seconds to turn from lit to off when editing profiles. The response to RGB values is otherwise instant. For example, start with RGB at 0,255,0, then slide green all the way to zero. The light will decrease smoothly until green is 1, then it will remain at RGB 0,1,0 for four seconds before shutting off. I don't actually know if this is a regression, since I've never used the lightbar, but since lightbar and rumble are related I thought it worth mentioning.

Dualshock4 v1 over USB, Windows 1909 x64, ViGEmBus 1.16.112.0, DS4Windows 2.1.22 and 2.1.23

**Comment by keatsandyeats** [comment]
The issue is gone on 2.2.1. 🤷
