### ISSUE TITLE
The Division 2

### ISSUE THREAD

**Issue by AmyrSamo** [Ryochan7/DS4Windows#1672]
When Playing The Division 2 from UPlay it bugs out and makes the controller switch from PS4 to XBOX set up, and ever time that I shoot the R2 and L2 stick in a sense (it continues to shoot when I let go of the trigger)

Which is weird because when I play Watch Dogs 3 there is not that problem.

**Comment by Ryusennin** [comment]
"the controller switch from PS4 to XBOX set up"

In DS4Windows or in Division 2?

Anyway, you probably have exclusive mode turned off. You will need to try the "Hide DS4" option or to install HidGuardian.

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#double-input-problem-in-games-game-does-all-sort-of-weird-things-when-i-press-a-button-second-player-drops-in-cannot-navigate-in-menus-because-focus-moves-two-lines-when-i-press-a-key-just-once-etc

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by AmyrSamo** [comment]
Yeah when I open DS4 windows to use for division 2 it won’t stay on one controller setting (Xbox - PlayStation) and I’ve tried to use “Hide DS4” and still doesn’t work. I’ll try the HidGuardian.

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
