### ISSUE TITLE
BT constantly disconnects and reconnects every few seconds. 

### ISSUE THREAD

**Issue by coffeemocca** [Ryochan7/DS4Windows#1675]
First of all i would like to give a little background and context - for years i used my official DS4 controller with DS4Windows and have had a flawless experience - fantastic. Unfortunately that controller is now broken, i feel sorry for posting this issue here as its about a fake DS4 controller -but bear with me- - i have hope that something can be salvaged here. 

If i run JOY.CPL - the controller is detected as a 'wireless controller' over BT and registers all the button inputs as well as the analog sticks. 

In DS4Windows it is also detected for around 5-7 seconds, then disconnects itself and continues indefinitely in that loop.
In DS4Windows via usb, everything works flawlessly as before. 
Also via x360ce it works over bluetooth, albeit without lightbar and rumble etc.

The reason i've not just bought another official DS4 controller is that in my part of the world (South East Asia) - they're so expensive, around a weeks wage for the average worker here. Thats why these clone / fake DS4 are so popular here.

I've attached  a debug log file and there seems to be some clear errors.  
 a debug log file and there seems to be some clear errors.  
[Debug.txt](https://github.com/Ryochan7/DS4Windows/files/5720486/Debug.txt)

**Comment by mika-n** [comment]
Unfortunately many of those fake Chinese copies struggle over BT when the gamepad is switched over to native DS4 mode in PC. By default DS4 gamepad is in so called "PC-friendly state" in PC when BT is the connection mode until a special DS4 cmd is sent to the gamepad (ie. PC sends certain config commands to DS4 gamepad). Only this native DS4 mode supports touchpad/lightbar/gyro and various other special DS4 features. In Pc-friendly mode only "normal" buttons and sticks work.

WinOS doesn't know to how to switch over to native DS4 mode, but DS4Windows app knows how to do it. This is why the gamepad may seem to work just fine over BT without DS4Windows app because the gamepad is still in PC-friendly mode. As soon DS4Windows app is used and it switches the gamepad to native DS4 mode in BT PC those copy-cats sometimes struggle.

Based on the logfile those problems begin right after this mode switch. This is classical sign of DS4 gamepad not being 100% compatible with genuine DS4 gamepad in BT mode.

If you untick the "Send output data to DS4" option in a profile then DS4Windows app won't do some of those magics but you loose rumble/lightbar/touchpad etc features.

Also, the debug version has DS4WindowsDebug.exe.config config file you can use to enable/disable certain tweaks to see if those help (disable gyro calibration, disable touchpad reading etc).

Or you can try "Debug_SendRumbleLightbarDataType" option with 1 and 2 values to see if those make a difference.

It might be possible to make those 98% compatible copy-cats to work over BT, but someone with such a hardware should debug how the gamepad expects to communicate over BT when the gamepad is switched over to native DS4 mode. DS4Windows does few special support tricks with for example Raizu TE BT gamepad in BT mode and could be that similar tricks may work with copy-cats also. But, it is difficult to debug this here without having an actual copy-cat hardaware (developers probably have only genuine DS4 and DS5 pads).

**Comment by coffeemocca** [comment]
Hi, I'd like to say thanks for taking the time to reply, especially as we're talking about none genuine controllers - that we as users really shouldn't expect to be supported. Its really appreciated.

I tried the tweaks and variables in the debug config that you recommended - none of them changed the debug logs in anyway and it always seemed to fail at the same errors.

However, I did notice something in the log though...it could be something, it could be nothing or i could be totally mistaken.

In the debut log, the controller identifies itself / is identified as `DEBUG: DS4Device. DS4 `v.1``

Yet this device is a clone of DS4 v2 (with the light on the touch pad) not the first version of the DS4. 
Actually, the controller itself makes no attempt to appear as anything but a genuine DS4 controller, even the packaging, the instructions are identical to the official product, and it only weighs 6 grams less.

But why is it identifying itself as a DS4 v1? when its actually a DS4 v2? Could it be that the shady place in China these come from haven't been able to reverse engineer the firmware or something of the DS4v2, so it identifies as an 'official' DS4v1 as its the only version they were able to reverse engineer?

Sorry if my hypothesis sounds like nonsense I'm just stabbing in the dark here, its all a little way over my head.

**Comment by mika-n** [comment]
Those shady fake Chinese copy-cats re-use the DS4 revision1 hardware ID because I guess that's the DS4 firmeware version they have managed to reverse engineer. DS4v2 firmware may be yet-to-be broken. Anyway, Sony itself haven't manufactured DS4v1 gamepads for 4-5 years, so if you have purchased the gamepad within few years and the hardware ID is DS4v1 then it is a clear sign of fake copy (this happens a lot with those fake copies). DS4Windows app just reports the firmware HW version of the DS4 gamepad sent by the gamepad.
