### ISSUE TITLE
CUH-ZCT2E Rapidly disconnects and reconnects

### ISSUE THREAD

**Issue by Kabir193** [Ryochan7/DS4Windows#1691]
**Describe the bug**
When trying to connect this controller to my pc, the controller connects for a split second then disconnects straight after and continues to do this untill i exit out of DS4 or I stop the app. I sometimes catch a glimse of the latency being something ridiculous like +1 million. I have changed cables, re-installed drivers, tried the old Jays2Kings version, using a differrent laptop all together. Nothing seems to work. 
When using an older CUH-ZCT1E controller, it works perfectly fine. 
Sometimes when i re-plug the controller in, the app freezes, and i have to end it with task manager.
In rare circumstances. the controller connects however when editing profile settings, Input Delay: N/A, and no controller readings are seen. The controller doesn't work.

**To Reproduce**
1. Open DS4Windows
2. Plug in controller
3. See error "Controller 1 was removed or lost connection" constantly repeating in the bottom left.

**Screenshots**
[ds4log.txt](https://github.com/Ryochan7/DS4Windows/files/5741904/ds4log.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Windows 10 Home, Version 1909, Build 18363.1256
 - DS4Windows Version [e.g. 2.1.5]

**Additional context**

https://user-images.githubusercontent.com/76587129/103134391-c9431980-46a8-11eb-80ba-ef670e2b6f7f.mp4

**Comment by mika-n** [comment]
Try running the debug version and attach the latest logfile here as .TXT file.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

Or if you suspect the gamepad is somehow faulty then try to reset it (there is a small hole on the back of the gamepad you can press with a paper clip). 

Try both USB and BT connection methods.

**Comment by Kabir193** [comment]
Ran the debug version and the logs are here:
**Bluetooth:**
[ds4windows_logBT.txt](https://github.com/Ryochan7/DS4Windows/files/5743005/ds4windows_logBT.txt)
**USB:**
[ds4windows_logUSB.txt](https://github.com/Ryochan7/DS4Windows/files/5743006/ds4windows_logUSB.txt)

Regarding the controller, this is the second replacement controller i have received after sending another one back, thinking it was a controller fault. This problem has continued with a new replacement controller, even after resetting it numerous times.

**Comment by mika-n** [comment]
Veeeeery strange that the USB logfile shows also disconnection issues. Usually random disconnection is an issue in BT mode because there are more variables trying to work together (BT host chipset in PC, BT radio storm causing interference, BT receiver in DS4 gamepad, etc).

Based on the logfile issues start right after trying to do certain special DS4 things (calibrating gyro etc).

If you try following tricks then does the gamepad stay connected (using the debug version of the app)?
- UNTICK "Output data to DS4 gamepad" option in a profile
- Set DS4WindowsDebug.exe.config options as follows (edit in Notepad).
- Debug_GyroCalibration=false
- Debug_ReadTouchpadData=false
- Debug_ReadGyroData=false
- Debug_ReadBatteryData=false
- Debug_SendRumbleLightbarData=false

Modify the DS4WindowsDebug.exe.config file while ds4win app is closed and re-start the app everytime you have tweaked these settings. If you use BT then use PS button (hold it for 10 secs) to shutdown the gamepad and ideally toggle Win10 "bluetooth on/off" when trying again (this ensures that BT stack is cleaned up and the gamepad is back to original state when you re-connect it to PC over BT). If you use USB then disconnect the cable from PC and then re-connect (if you don't do this then firmware in the gamepad may still remember old settings).

**Comment by Kabir193** [comment]
So changed the config file options one after the other untill all of the options stated were set as "false". Nothing changed and the controller still kept disconnecting.

This is the log file where at the end with all options set to false:
**USB:**
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5743083/ds4windows_log.txt)

Unticking "Output data to DS4 gamepad" still didn't change anything. 

On another note, since I dont know who else to ask. I have noticed that this new controller with these problems (CUH-ZCT2E) seems to come default with a Square Deadsone, instead of the normal circular one. When looking at the output data in windows setting the controller readings reach the corners of the box instead of cutting off at the circular 75% where the readings would max out. Is there any way to change this as this Square Deadzone is also present when using this controller on a PS4?
Thank you.

**Comment by mika-n** [comment]
Many copy-cats have square LS/RS stick movement even when DS4Windows app tweaks are not used. DS4Windows profile does have additional LS/RS output curve settings and square-stick options, but those only affect how the output virtual gamepad sees LS/RS movement. It has nothing to do how the physical gamepad sends LS/RS values to PC and DS4Windows app.

Don't understand why USB could stuggle, except that try different usb ports and cables (usb2/usb3/front/back panel ports). And maybe trying the gamepad and the latest DS4Windows app version in another PC to test if the issue is there also.

**Comment by Kabir193** [comment]
Okay, is there a way to revert the Square input data being sent from the controller to emulate it as Circular?
I'm very certain this controller is Genuine from Sony.

I have tried everything i possibly can, using different computers and cables, the same problem seems to happen on every computer with these controllers. 
Is there anything else i could try?

**Comment by mika-n** [comment]
There is no way to change how the physical gamepad sends the LS/RS values, but feel free to play with DS4Windows profile settings (square stick/rotation settings) if you can work out something you need.

**Comment by w1lddog2** [comment]
Is it an Original DS2 v2???  Because i have a fake one and it is 99% identical to a DS2 v2 that i got online from Sony Store.  Usually fake ones have random issues.

**Comment by Ryusennin** [comment]
There's no safest bet. Even Amazon sells cheap clones as original controllers, and brand new original controllers are plagued with analog drifting issues.

**Comment by w1lddog2** [comment]
> There's no safest bet. Even Amazon sells cheap clones as original controllers, and brand new original controllers are plagued with analog drifting issues.

I have to disagree to an extent.  Buying straight from Sony is a safe the same from some retailers.

BUT

It is true that Amazon somethings sells clones as original, in fact a friend of mine a few years ago got two from amazon one urban camo and one woodland camo, the urban was a fake but the  woodland wasn't

**Comment by Kabir193** [comment]
> Is it an Original DS2 v2??? Because i have a fake one and it is 99% identical to a DS2 v2 that i got online from Sony Store.
> Usually fake ones have random issues. Can you show us the tag in the back of the joystick???
> 
> Original CUH-ZCT2E have circular dead zone not square. Sadly the DS4 was cloned to death, it guess the same will happen to the DS5. When buying Playstation products the safest best is just buy from Sony Stores or authorized retailers, it maybe a tiny bit more expensive, but you know you are getting the real deal.

This is the back of the controller...
![20210101_233258](https://user-images.githubusercontent.com/76587129/103447979-9d1c2f80-4c8a-11eb-8f2f-8de6642d35d3.jpg)

I ordered two new controllers and was very certain that these were original. Curious, i went back to my amazon order and saw that these were dispatched by an Amazon Warehouse (making me think that these were legit, as a private seller was not the middle man). I also paid full price for them as i needed them quite quickly. Which retailers should i trust then? Since clearly amazon isn't trustworthy.

And about the Square deadzone, This was what triggered me off the most.. as it affected every game that i played, and completely threw off my playing style. There was literally no way to change it and i was hoping by some miracle that DS4 could Emulate a Circular one, only to take me into another roadblock.

Anyway, it was a lesson learned and a waste of $120.
Thanks for the help, as there is literally no one else on the internet that has understood me until now.

**Comment by w1lddog2** [comment]
It's a fake one. It should say "Sony Interactive Entertainment inc."  instead of "Sony Computer Entertainment inc."

With Sony products when possible, buy from Sony Store. I don't mind clone joystick, but when you charge a clone as real one that is a big deal. I got a fake one as well it work just fine but it has battery issues and BT is a laggy.

Once Sony release a black DS5 i will get one and if there is one thing i know is that i will get it from a Sony Store.

**Comment by mika-n** [comment]
And see how there is no space between the double colon ":" char and "Manufacturer" and "Sony" words. The legit one would be "Manufacturer: Sony Interactive Entertainment Inc."

DS3 gamepads had "Sony Computer Entertainment" as a manufacturer, but DS4 pads should have "Sony Interactive Entertainment".

You may also use "Controller Readings" tab page to observe if the LS/RS movement (physical input) is circular or square. Or download a free "Game Controller Tester" app from Win10 Store or use gamepad-tester.com web page to see the LS/RS movement (when DS4Windows app is not running and doing its magic).
