### ISSUE TITLE
After updating to 2.1.23 DS4Windows crashes shortly after opening

### ISSUE THREAD

**Issue by KBD20** [Ryochan7/DS4Windows#1694]
**Describe the bug**
After updating to Version 2.1.23 from Version 2.1.22, the program crashes 30 seconds or so after starting.

**To Reproduce**
Start DS4Windows Version 2.1.23 (may not be the case on a clean install).

**Expected behavior**
The program stays running.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.1
 - OS: Windows 10 Home Version 2004, Build 19041.685, Experience Pack 120.2212.551.0
 - DS4Windows Version 2.1.23

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5742596/ds4windows_log.txt)

**Comment by Ryochan7** [comment]
I need to know what Macro you tried to execute which caused the crash. Can you post the relevant profile here? I don't know if adding the DualSense Mute button as a mappable button might have caused the breakage.

**Comment by MK99MA** [comment]
Experiencing a similar behaviour.

After booting my PC I got the usual DS4Win update prompt and as usual installed it, however did not notice any problems since I wasn't going to use the gamepad for a while.

When I started a game I'm usually playing with the controller I noticed that DS4Windows wasn't running anymore (LED wasn't colored the way it should if its running).
After starting DS4Windows manually with the already turned on DS4 (v2) I got the usual "device found"-sound following by the "device disconnected"-sound.

After checking my taskbar, not only DS4Windows crashed, but Steam shutdown too. This would happen for a second test too.
After rebooting my PC Steam does not close itself anylonger when starting DS4Windows, but the program itself still crashes instantly.

I'm executing DS4Windows as an administrator, if thats of any relevance.

In the latest logfile referring to a crash I got this error:
`2020-12-26 17:29:32.1458|ERROR|System.IndexOutOfRangeException: Index was outside the bounds of the array.`
[ds4windows_log_20201226.9.txt](https://github.com/Ryochan7/DS4Windows/files/5743364/ds4windows_log_20201226.9.txt)

This should be the default profile thats being used whenever a controller is detected while I'm not ingame (added the '.txt' since github apparently doesn't allow '.xml' files in comments):

[DS4.xml.txt](https://github.com/Ryochan7/DS4Windows/files/5743366/DS4.xml.txt)

**Comment by prankfurter** [comment]
I am also having this issue. As soon as my Dualsense connects it crashes the app. I rolled back to previous version and working as expected.

I created a new blank template and it works with 2.1.23 without crashing.

I have two macros set up on my profile that crashes DS4windows so think it is tied to the profile. One is Win+G and one is ALT-F9

**Comment by Ryochan7** [comment]
Looks like the answer is a Yes. Any control starting from Mute for Macros is now incorrect. The index for SwipeDown is also now invalid and is causing the IndexOutOfRangeException error. The Macro system was not changed to accommodate the added input button binding. Needs to be fixed.

**Comment by KBD20** [comment]
The crash happened without any input - macros I have on the default profile are L3+R3 tied to swipe up/down, and shift modifiers for the face buttons in order to rapid press (modifier was finger on touchpad), the rest are standard x-box mappings and a duplicate L3 and R3 to swipe right and left.

**Comment by Ryochan7** [comment]
Need to double check macro support but hopefully this bug has been fixed with commit 784457ab6f1911b37ef303048854a3504d0f8b0e.

**Comment by MK99MA** [comment]
Just wanted to report, that after todays Updates my issue seems to be resolved.

I did not do any advanced testing yet, but turning on my controller while DS4Windows & Steam are running does not cause either to crash.

**Comment by Ryochan7** [comment]
I still have not gotten around to testing a couple of possible ways to make the backend a bit more dynamic. I don't expect to add any more input button bindings but it might be useful knowledge in the future.
