### ISSUE TITLE
2.1.23 Dual Sense battery level always at 0%

### ISSUE THREAD

**Issue by Haruno19** [Ryochan7/DS4Windows#1695]
**Describe the bug**
I've just installed version 2.1.23 and dualsense battery level doens't work anymore. It's always at 0%.

**To Reproduce**
1. Connect dualsense via BT
2. Battery level is detected as 0%

**Expected behavior**
In the previous version it worked fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/61376940/103150309-1d1a3500-4773-11eb-8550-e83632953004.png)

**Desktop:**
 - Controller Make and Model: Sony DualSense
 - OS: Windows 10 Pro Build 19042.685 20H2
 - DS4Windows Version 2.1.23

**Additional context**
previously the battery reading wasn't really precise but it worked fairly.

Thanks

**Comment by Ryochan7** [comment]
The level reading routine has not changed since version 2.1.20. Can you check the battery level reading in the Profile Editor under the Controller Readings tab? That number is updated every gamepad poll rather than when the value changes. That should help determine if the BatteryChanged event is not firing or if a bad value is calculated from the device reader class.

**Comment by Haruno19** [comment]
Oh I restared everything and now it seems to be working, my bad, I should have tried before. Sorry and thanks!!
