### ISSUE TITLE
'Check Every' Option Has Never Worked.

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#1696]
'Check Every' Option Has Never Worked. Check Now does and so does check at startup. I've never seen an update window come up any other time. My pc was left on overnight as always and was on all day. I only knew this update was released by a firefox plugin checking the page.

**Comment by Ryochan7** [comment]
Unless something is wrong in your config file (Profiles.xml) then DS4Windows should download the remote newest.txt file at program startup (if the set time period has elapsed since the previous check) and check the latest upstream version number. The relevant tags in Profiles.xml are **LastChecked** and **CheckWhen** which is the number of hours to wait before DS4Windows will check for an update.

The routine works on my end on my native Windows 10 install and my Windows 7 VM.

**Comment by Ryochan7** [comment]
For further clarification, the **Check every** option only sets the time period to hold off checking for an update. It is directly tied to the **Check for updates at DS4Windows startup** option and those controls are disabled if the option is unchecked. The routine is only meant to run when DS4Windows first launches. It is not meant to be a continuous background process.

**Comment by shinra358** [comment]
So if it downloads the newest file at program startup, and my pc stays on
all day every day (program is always on aka no more program startup), then
it will never check again correct?

Kinda misleading if the update box only shows at program startup on pc
startup. And come to think of it, if i dnt turn my internet on immediately
at pc startup, the update box will never show if there is a new update.
