### ISSUE TITLE
DS4 wireless vibration problem 

### ISSUE THREAD

**Issue by ibrahim4639** [Ryochan7/DS4Windows#1703]
after the update the DS4 can no longer vibrate in wireless mode, I tested it in heavy or light it still doesn't do anything, but if i use wired mode it work fine.
i tested the original DS4 and it works fine it vibrates as usual
Can you fix this?

**Comment by Ryochan7** [comment]
Are you using Windows 7? BT connection?

**Comment by ibrahim4639** [comment]
> Are you using Windows 7? BT connection?

yes, i am using bt connection in windows 10
i use steam playstation controller support and the vibration works fine
jays2king ds4windows works fine too
but when i use yours it won't vibrate unless i use wired mode

**Comment by ibrahim4639** [comment]
can you fix it?, i like yours more because it has more features
or is it problem on my side? can you tell me how to fix this?

**Comment by mika-n** [comment]
Do you have a genuine DS4 gamepad or a copy-cat?

Try running the debug version linked here and post the latest logfile generated by the debug version as .TXT file attachment (ie. rename the logfile as .TXT and drag-and-drop the file in a comment box). The logfile tells more details about the gamepad.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by ibrahim4639** [comment]
> Do you have a genuine DS4 gamepad or a copy-cat?
> 
> Try running the debug version linked here and post the latest logfile generated by the debug version as .TXT file attachment (ie. rename the logfile as .TXT and drag-and-drop the file in a comment box). The logfile tells more details about the gamepad.
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

[log.txt](https://github.com/Ryochan7/DS4Windows/files/5753790/log.txt)
here my log file
i know i use 3rd paty controller but i wonder why in original ds4 rumble work in bt but it didnt work here
can u tell me how do i fix this?

**Comment by ibrahim4639** [comment]
and if i use ds4windows 2.1.0 i can use rumble but i cant play any games

**Comment by mika-n** [comment]
V2.20.0 introduced "Now use Interrupt endpoint for DS4 BT output reports" typo of change and it for sure has issues in Win7, but could be in theory that there are issues in Win10 and copy-casts.

How about if you download V2.19.0 version and then V2.20.0 version? Does it work in 2.19.0 version, but breaks in V2.20.0 version? If it does then this change probably backfires the copy-cat.

**Comment by ibrahim4639** [comment]
> V2.20.0 introduced "Now use Interrupt endpoint for DS4 BT output reports" typo of change and it for sure has issues in Win7, but could be in theory that there are issues in Win10 and copy-cats.
> 
> How about if you download V2.19.0 version and then V2.20.0 version? Does it work in 2.19.0 version, but breaks in V2.20.0 version? If it does then this change probably backfires the copy-cat.
> 
> Also, make sure the lightbar color is not 0,0,0 (all zero). Use at least something like 0,0,1 rgb color.

ah i just test it bunch diffrent version and found out that it worked fine until version 2.1.0
after that vibration not working anymore but i can still use ds4 normally
t think Changed type of output report transmitted to DS4 in BT. Now use report type 0x15 (previously 0x11) broke it
do you know possible fix for this?

**Comment by mika-n** [comment]
Please try the latest debug version (re-download it from the link posted above) and tweak the following values in DS4WindowsDebug.exe.config file as shown here (ie replace default 0 value with 17 and 132 values):

```
<add key="Debug_ForceOutputReport00"  value="17" />
<add key="Debug_ForceOutputReport01"  value="132" /> 
```

The meaning of these debug "force" options is this:
```
  <!-- Force output report bit flag values at 00 and 01 report byte locations -->
  <!--   00: 0=default,  05=0x05 as used in USB mode,  17=0x11 as used in BT mode V2.1.0 and older versions,  21=0x15 as used in BT mode V2.1.1 and newer versions -->
  <!--   01: 0=default, 247=0xF7 as used in USB mode, 132=0x84 as used in BT mode V2.1.0 and older versions. 196=0xC4 as used in BT mode V2.1.1 and newer versions -->
```

I'm not quite sure which of these options breaks the rumble support in the copy-cat pad while connected over BT.  At first try both 17 and 132 values at the same time. Then try only one of these values at a time (set other one zero) and see how it goes. This should tell which one of these output report bit fields causes the issue or is it a combination of these two.

You should close and restart DS4WindowsDebug app while modifying the config file.

**Comment by Ryochan7** [comment]
I will leave this open for now but I am marking this issue as invalid. If you decide to try to use a third party DS4 controller, you better be ready to debug any issues and submit a pull request. I only support the use of first party Sony brand DS4 controllers as that is what I have on hand to test. Based on my experience, many third party controllers don't even work correctly on the hardware they were supposedly made for.

**Comment by EnyarIsMe** [comment]
> Please try the latest debug version (re-download it from the link posted above and unzip the zip file into a folder where you have the latest official DS4Window app version. The debug zip re-uses other files from the official release) and tweak the following values in DS4WindowsDebug.exe.config file as shown here (ie replace default 0 value with 17 and 132 values):
> 
> ```
> <add key="Debug_ForceOutputReport00"  value="17" />
> <add key="Debug_ForceOutputReport01"  value="132" /> 
> ```
> 
> The meaning of these debug "force" options is this:
> 
> ```
>   
>   
>   
> ```
> 
> I'm not quite sure which of these options breaks the rumble support in the copy-cat pad while connected over BT. At first try both 17 and 132 values at the same time. Then try only one of these values at a time (set other one zero) and see how it goes. This should tell which one of these output report bit fields causes the issue or is it a combination of these two.
> 
> You should close and restart DS4WindowsDebug app while modifying the config file.

seems that i have same problem with DS4 copy-cat not changing color and not vibrating, i tried to use debug mode and changing values one by obe and both at the same time, nothing changed for me, i'm open to help with anything else i can do to solve it

**Comment by mika-n** [comment]
@EnyarIsMe Impossible to say anything without actually having such a copy-cat and being able to debug it. If the copy-cat doesn't follow DS4 standard then unfortunately someone with the gamepad should debug it and investigate how the communication protocol is different than with 100% compatible DS4 pad. Especially over BT those copy-cats are problematic, may work better over USB.

**Comment by EnyarIsMe** [comment]
@mika-n it's a bit out of my power to do such things alone, well, older version is working, guess other ppl with same problem can solve it by using 2.1.0< for now

**Comment by firodj** [comment]
Hi there,I ve got similar issues there,but Is there a list of possible combination of windows OS version,bluetooth device type/brand/ID, copy-cat/original DS4, DS4win version, that makes DS4 over BT enables rumble and lightbar.

Maybe VigemBus no need to list since it it just interface communicates to/from the Games,not to the directly to the DS4. cmiiw, many thanks for your hard works.

**Comment by mika-n** [comment]
VigEmBus has absolutely nothing to do with how those physical gamepads are connected/NotConnected and how the physical data is written or read to/from the gamepad, so it is not its job to list anything.

It is a never ending story trying to list all combinations. The bottom line is that if you want to be on a safe side then you should purchase an official Sony DS4v2 gamepad or an officially licensed compatible model (Nacon? Razor? various other).

The best place to see "always" up-to-date list of currently supported gamepads in DS4Windows apps is the knownDevices table in the app.
https://github.com/Ryochan7/DS4Windows/blob/dafdf7125ba6deb1a9fca7eccaeb3de4bc39132c/DS4Windows/DS4Library/DS4Devices.cs#L121

But, there are no lists of BT chipsets or BT dongles because it is next to impossible to keep it up to date (too many variations and the same BT dongle brand and model may have several chipset variations and users often don't know anything about those details and they don't report it here or anywhere else.
https://github.com/Ryochan7/DS4Windows/wiki/Bluetooth-Compatibility-List

So, if you purchase those cheap Chinese copy-cats then there is high risk of getting a problematic BT connection. I guess none of the developers have those copy-cat gamepad devices, so it is difficult to debug and see how to make those work better (to see how the communication protocol differs from an official Sony gamepad firmware). I'm sure in many cases it would be possible, but someone with such a hardware should debug it.

There is "HidReportInspector" debug tool to inspect closer those incoming and outgoing messages. If those messages are compared with a known working Sony gamepad then it might tell something if the message structure is somehow different. If the message structure seem identical then copy-cat must have a buggy/different/problematic firmware.
https://github.com/Ryochan7/HidReportInspector

**Comment by firodj** [comment]
Hi @mika-n , I try to enable the lightbar and rumble on BT, and successfully do it with my controller with slight modified on DS4windows mater branch.

What i do is try to understand this
* http://eleccelerator.com/wiki/index.php?title=DualShock_4#HID_transaction_structure
* https://www.psdevwiki.com/ps4/DS4-BT#HID_INPUT_reports

What I'm figuring out is the setup sequences that PS4 console do to DS4 over BT. There is Set Feature report that I think DS4Windows didn't do properly.

**Comment by mika-n** [comment]
hmm..... Interesting. That specific output report byte has been 0xF7 for ages (probably since the days of the original Jay2Kings version). I just tested the output byte with 0xF3 value with a genuine DS4v2 gamepad and it did seem to work.

Or could be that those web pages with DS4 output report specs have been updated since the original version, but DS4Windows app was never modified to follow those new reverse engineering results.

Anyway, maybe the DS4 copy-cat firmware expect to see 0xF3 value there and simply go wooooow if the  byte is 0xF7. DS4 pad doesn't seem to care if this byte is F3 or F7 (could be that only the first two bits of the first half byte are used, so the firmware in genuine DS4 handles F3 and F7 the same way, but copy-cat firmware is a bit different.

This may need a change in DS4Windows base code. Thx for testing. Debug version makes it possible to change that byte via DS4WindowsDebug.exe.config file, so it is easy way to test this with the latest "official" DS4 version without re-compiling the app.

Another thing about hot plugging BT while the same pad was connected over USB also. If the gamepad doesn't have a real hardware MAC address then something like that could happen because the on-the-fly calculated serialKey is different in usb and bt mode. Genuine DS4 has a real MAC address and it is the same both in USB and BT mode, so DS4Windows app is able to identify when the hot usb->bt plugged pad is still the same pad. With copy-cats this may not be true because of different serialKey. So, if you want to change the pad then do it from a wall socket or use usb cable which provides only power, but not carry over DS4 data signals (I have several mobile phone cables which work like this with DS4 pad).

**Comment by firodj** [comment]
I've used Debug version, did you mean changing the value `Debug_ForceOutputReport00` and `Debug_ForceOutputReport01` ?

Maybe if it possible to do:

```
<add key="Debug_ForceOutputReport03"  value="243" />
```

but it doesnt works

**Comment by firodj** [comment]
Since Iv'e copy-cat, I dont know what is the behaviour of reset hole button,because it still able to paired to my PC after resetting without do PS+Share again. Is it expected or not? I just want to reset the controller and retest this patch again.

because yesterday this 0xF7 nor 0xF3 still didnt work. then I tried guessly to send Set Feature Report 0x3, then it works with 0xF3 until now without resending the set feature. The code is still on my forked repo.

**Comment by mika-n** [comment]
The latest debug version has "Debug_ForceOutputReportFx" option to tweak this option (the byte index is a bit different in USB and BT connection mode, but the "Fx" byte using this option works both in USB and BT connection modes.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by Ryochan7** [comment]
The value of that output report byte used to be 0xFF in Jays2Kings. In most versions of this fork, it has been 0xF7. From what I have checked, it has never been 0xF3. Stripping out the flag 0x04 would disable flash support for the DS4 lightbar. If rumble used to work in previous versions of DS4Windows for some third party controllers but it does not work now then I doubt that byte is the culprit.

The other hypothesis from the one pull request was more likely. Maybe that controller cannot handle output report type 0x15 but it can handle 0x11 just fine. Output report type 0x15 was first used in DS4Windows version 2.1.1. That output report worked better for my DS4 controllers and there is always the hope that BT audio support might get implemented someday. Output report 0x15 would be required for that purpose as it has space to handle the SBC audio frames.

**Comment by firodj** [comment]
My copy-cat DS4 support report 0x11 and 0x15 with that byte should be 0xF3 (try another value no luck). Next thing is to check for audio support when using 0x15.

**Comment by firodj** [comment]
hi @Ryochan7 @mika-n I managed to get the second DS4v2 Original (around USD 34.79), and it works perfectly out the box using DS4Windows 2.2.1.

The problematic way seems coming from the copy-cat DS4. If I may give suggestions:
* you might revise the Readme, to require **Original** Sony Dualshock 4 Controller.
* or, add checkbox/options to enable/disable custom format to support copy-cat.
* have new issues template, eg. DS4windows version, OS version, ViGemBus version, DS4 sony original/copy cat, etc.

Actually I'm lucky enough to get copy-cat (around USD 12.78) that works nearly fit with my expectation with USB and BT (exclude Audio): although:
+ vibtrate, that stops when not continously set in output report. Cannot stop one of motors if both already turning on.
+ lightbar, that is not white but turqoise. To get white set R,G full and B at very low value.
+ gyro which has a drifting.

I also have another copy-cat that is very very bad, it only works with USB, plus lightbar+rumble, cannot be set. and keep disconnecting when using BT, when DS4windows try to fallback into USB format but then failed to get errors.

That was my 2cent, hope this will be helpful.

**Comment by mika-n** [comment]
DS4Windows app works with multiple 3rd party controllers from Razer, Nacon and many other. The problem with those copy-cats is that often people don't even know if they have a copy-cat because those cheap Chinese fakes are exactly like that, fakes made to look like the real thing even when those are pure crap inside. But "normal user" may not know that, so it would not help much to have a readme doc saying "cheap chinese fake copies are not supported". And people often don't even read those docs :-)

Different copy-cats seem to have different problems. It is difficult to "officially" support all those cases without having such a hardware for debugging and testing, so it is up to users to figure out differences. And even then it is not 100% if those customizations will ever be added to the official release.

**Comment by firodj** [comment]
Update PR: https://github.com/Ryochan7/DS4Windows/pull/1839
Add check box to enable/disable when using copy-cat DS4
