### ISSUE TITLE
Fixing gamepass's permissions tampering

### ISSUE THREAD

**Issue by Jordan-Ch** [Ryochan7/DS4Windows#1705]
**Describe the bug**
DS4windows in unable to use autoprofile for gamepass games. Permissions issue. NOT A BUG, just a question. 

**To Reproduce**
Trying to set up DS4windows to use an autoprofile for the game "moonlighter", but DS4windows does not have permission to access the file because of the way gamepass messes with permissions. 

**Additional context**
What permissions object in windows does DS4windows use? Which object do I need to add the permissions to in order for this to function. I can not simply change the file to public, as windows gives an (thought to be irrelevant error code 0x80070057:parameter is incorrect) to do with HDD failures.

**Comment by Masamune3210** [comment]
the error code is not irrelevant, it's complaining about hdd issues because of how 90% of gamepass games work. they are actually mounted encrypted disk images. so if the security is messed with windows will refuse to decrypt them and it will fail to mount. would have better luck doing process name matching or something similar for gamepass

**Comment by Jordan-Ch** [comment]
Ohk. So I can have it auto-profile based on a process ID? I know the process ID, so how do I associate it lol?

**Comment by Jordan-Ch** [comment]
Fixed. 

Used playnite to launch DS4windows with the game, select a profile, then terminate DS4windows when the game closes.
