### ISSUE TITLE
Plex, Jellyfin/Emby and BankID hard-locks my PC if DS4Windows is running with a controller connected.

### ISSUE THREAD

**Issue by tordenflesk** [Ryochan7/DS4Windows#1708]
**Describe the bug**

I have for some time (1 year plus) experienced full ~5 second freezes when accessing local Plex-servers via app.plex.tv, plus when accessing BankID (Norwegian goverment 2FA) with a physical token (phone BankID has no issue). I experience a similar hard-lock when browsing away from the pages.
My workaround for Plex has been accessing it directly, but since Plex have updated the local version to something close to the web version I'm experiencing this bizarre freeze there as well.

Testing alternatives like Jellyfin / Emby exhibits the same behaviour.

**To Reproduce**
1. Browse to offending page (Plex, Jellyfin/Emby or any site using plain BankID)
2. experience full ~5-second hard-lock.

**Expected behavior**
Not hard-locking.
Closing DS4Windows and opening Plex with the controller turned on and connected via BT doesn't trigger the issue.
Running DS4Windows with the controller turned off seems to not trigger it.

Browsers tested: Waterfox Classic, Waterfox Current, Vivaldi & Chrome. Also the Plex Windows app.

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - Belkin Bluetooth 4.0 USB Adapter - USB\VID_050D&PID_065A&REV_0112
 - OS: Windows 7 x64 w/ESU updates
 - DS4Windows Version 2.1.23

**Comment by mika-n** [comment]
Are you using "Hide DS4 Controller" (=exclusive mode) to hide the phyiscal gamepad? It may cause something like this when app tries to access a gamepad device locked (=exclusive lock made by DS4Windows app).

This is to blame those "other apps" and lazy programmers doing shitty job with WinOS HID interfaces.

The solution is to use HidGuardian to hide the physical gamepad instead of using the built-in exclusive access.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by mika-n** [comment]
closed as inactive
