### ISSUE TITLE
Controllers Not Recognized After a Reboot

### ISSUE THREAD

**Issue by Malumen** [Ryochan7/DS4Windows#1709]
Controllers pair OK and work; then after a reboot and pressing the PS button, controllers will be seen in Windows for a few seconds (with "connecting wireless controller" message) and then turns off. 

must re-pair again to get it to work.

**To Reproduce**
1. Start PC
2. `DS4Windows` auto-starts (minimized)
3. Open Windows Bluetooth settings
4. Pair controller (DS5 and DS4)
5. Pairs OK
6. Play games
7. Shut down PC for the night
8. Next day boot up PC
9. `DS4Windows` auto-starts (minimized)
10. Press PS button on controller
11. Windows notification pops up as if pairing wireless controller (bypassing DS4Windows)
12. Message disappears after a few seconds
13. Controller powers off
(and subsequent efforts to power on the controller result in steps 10-13 again)

**Expected behavior**
Pair controller, game, turn off system, boot back up and PC/DS4Windows remembers controllers.

**Desktop and controllers:**
 - Controller Make and Model: Sony DS4 v.2 (`CUH-ZCT2U`) and DS5 (`CFI-ZCT1W`)
 - OS: Windows 10 Pro Build 20H2
 - DS4Windows Version is 2.1.23

**Additional context**

**Comment by mika-n** [comment]
Does those gamepad work after reboot when DS4Windows app is not started? Anyway, DS4Windows app itself has nothing to do with BT pairing, it is up to the WinOS and the BT drivers you have in the PC.

But one thing you could check would be to disable (untick) "Win10 Fast Startup" power setting. This WinOS fast startup feature is a thing from the past when people had ultra slow HDD disks, but nowadays when everyone have fast SSD disks the fast startup feature is obsolete. If this option is set then WinOS preserves certain states of the PC in a cache file on disk and the next WinOS restart re-uses that state instead of doing "a cold reboot" of WinOS. This startup cache may reload something causing weird bugs in WinOS.
https://www.asus.com/us/support/FAQ/1031533/

**Comment by mika-n** [comment]
closed as inactive
