### ISSUE TITLE
Quality of Life improvments

### ISSUE THREAD

**Issue by Anuskuss** [Ryochan7/DS4Windows#171]
Hey @Ryochan7
first of all thanks for your effort in keeping **DS4Windows** alive.
I'm trying to run a keyboard-less game station and for a complete seamingless experience, I'm suggesting these three ideas:
- **Automaticaly connect DS4 bluetooth via USB**
   - DS4 is connected with PS4
   - Connect DS4 with PC
   - Assign MAC address of bluetooth adapter to DS4
   - Disconnect DS4 & Remove DS4 from controllers tab
   - Press PS button and connect to bluetooth adapter
- **UI with controller support**
- **On-screen keyboard with controller support**
   - E.g. Steam Virtual Keyboard

Cheers

**Comment by Ryochan7** [comment]
As far as I know, there is no way to implement the first requested feature. That is a problem with the hardware itself and the Microsoft Bluetooth stack.

A UI with controller support will probably never happen. Although it could be considered helpful, too much extra work would have to be done to attempt to work around the limitations of Windows Forms to make it possible. The only partial workaround is to just use a KB+M mapping when DS4Windows is active and use an alternative mapping when in game.

An on-screen keyboard would be useful for some applications and there is actually a virtual keyboard class in the source code that is not being used anywhere in the project. The major problem is that there is no way that I know of to overlay windows on top of regular fullscreen games on Windows. You would have to run games either in regular windowed mode or borderless windowed mode (if a game supports it) in order to be able to render something over the game. Steam uses DLL injection when launching a game to have the ability to render the Steam Overlay when requested.

Although getting DS4Windows to offer functionality more in line with what Valve offers in the Steam client would be great, that is not a priority. The top priority will likely always be reducing input lag as much as possible to ensure that a game responds to a press of a button as quickly as possibly. I wish Valve would finally focus on improving input lag issues and overall output performance for the Steam controller mapper. Even when using the Steam Controller, the mapping software is by far the weakest link in the whole experience and it kills the usefulness of the controller. I use the Kozec SC-Controller software when I want to play games with the Steam Controller and that piece of software makes the controller useful even though mapping options are more limited. I bought my version 1 DS4 a little while after Valve included support for it in the Steam client; I bought it around December 2016. I used it for a few hours and gave up concluding that it was unusable. I still test out both controllers using the Steam client every once in a while and things have not changed much; none of the settings that people have recommended make that big of a difference. Despite the work Valve has put into the controller mapping options in Steam, third party applications are still useful.

https://github.com/kozec/sc-controller

**Comment by Anuskuss** [comment]
> As far as I know, there is no way to implement the first requested feature. That is a problem with the hardware itself and the Microsoft Bluetooth stack.

I remember back in the day you had to connect your DS3 controller that way (it was called SixaxisPair or something). Do you know by any chance know how they could accomplish this?

> ...too much extra work would have to be done to attempt to work around the limitations of Windows Forms to make it possible.

Let's hope for Microsoft to actually make a decent Windows before everyone switches to Linux.

> Steam uses DLL injection when launching a game to have the ability to render the Steam Overlay when requested.

There exists an app on the Steam store which also does this ([Controller Companion](http://store.steampowered.com/app/367670/Controller_Companion/)). Might be worth a look.

**Comment by czukowski** [comment]
>>  ...too much extra work would have to be done to attempt to work around the limitations of Windows Forms to make it possible.
>> 
> Let's hope for Microsoft to actually make a decent Windows before everyone switches to Linux

Actually this one isn't really a Microsoft's fault (surprisingly!). Windows Forms is an API for building user interfaces that goes from ages where a few people could even consider somebody will want to use controllers with PCs :)

While the feature is possible to do, it requires quite a lot of effort as Ryochan7 has mentioned, although optimizing UI controls would never hurt, especially if it improved accessibility when used with keyboard as a result.
