### ISSUE TITLE
Unable to use gyro controls

### ISSUE THREAD

**Issue by sukrabambang** [Ryochan7/DS4Windows#1712]
**Description**
Unable to use gyro to controls Left-X-Axis both on tilt mapping and 360 Steering Wheel.

**Expected behavior**
Able to controls Left-X-Axis using gyro controls setup on DS4Windows application.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.1 (CUH-ZCT1E)
 - OS: Windows 10 Home Single Language Version 20H2 Build 19042.685
 - DS4Windows Version 2.2.1 
 - Tested on game: Dirt Rally 2.0

**Additional context**
When using 360 Steering Wheel the Left-X-Axis doesn't work.
Tilt mapping setup is working on DS4Windows (Jay2Kings) [v1.4.52]

**Additional question**
Is there a way to test this feature within the DS4Windows application?

[Settings.zip](https://github.com/Ryochan7/DS4Windows/files/5756732/Settings.zip)

**Comment by mika-n** [comment]
The Steering.xml profile file has 25.00 in SixAxis X/Z deadzone, so the "whole" sixaxis movement is dead.
![DS4Windows_SixAxisDeadZoneBug](https://user-images.githubusercontent.com/35538525/103409194-46213800-4b6e-11eb-9615-18d527f84167.png)

The solution is to set SA X/Z deadzone value to 0.00 (this is good value if the game itself has customizable deadzone because then you can tweak the deadzone through game settings). 

This "25.00" as a default SA deadzone is a bug in DS4Windows app in certain localizations. The app fails to recognize the localized decimal separator, so the value "0,25" may end up as being integer "25".

**Comment by sukrabambang** [comment]
@mika-n - Awesome! That solved the issue. Thanks!
