### ISSUE TITLE
DualSense Support

### ISSUE THREAD

**Issue by LeonPro12** [Ryochan7/DS4Windows#1715]
Hi,
Are you planning to support the sensitive triggers from the PlayStation 5 Controller?

**Comment by Ryochan7** [comment]
Not sure. There was the fork that added experimental support for the DualSense adaptive triggers. It was a bit interesting to test the feature but I am not sure how practical it would be outside of any actual game context. Another issue is that there would have to be some way to start adding device specific features in the profiles.

https://github.com/Mxater/DS4Windows/

**Comment by tomatosoupcan** [comment]
IMO potential uses:

- Gamecube emulation
- Divide triggers into two buttons each with physical feedback (i.e. for keyboard controls you can scope on half press, fire on full press)
- Add physical feedback for games that already have scope on half press fire on full press
- Just make guns feel more like guns in shooters

**Comment by giuseppe3349** [comment]
true, that would be very nice

**Comment by Ryusennin** [comment]
Proper feedback needs an API, a protocol. XInput doesn't support adaptive triggers, and thus no game on Windows can support them. You can't magically implement trigger feedback in an FPS if the game doesn't have any info about it.

I've read recently that Microsoft could be interested in designing a new Xbox controller with adaptive triggers. If that ever happens, they would certainly have to update XInput accordingly and that would become viable. In the meantime, some people out there are designing third party APIs, but I don't imagine any publisher making use of them.

**Comment by MicaelJarniac** [comment]
> XInput doesn't support adaptive triggers, and thus no game on Windows can support them.

I don't think this bit is exactly true. Sure, xinput doesn't support adaptive triggers, but I don't believe that means that no game on Windows can support adaptive triggers. If the games are designed only for xinput, then yeah, that makes sense. But I've seen games on Windows using features of the DS4, like the colored light bar and motion sensors, and I don't think those features are part of xinput. So I do think games on Windows can perfectly support adaptive triggers, the enhanced haptic engine and all that, as long as they aim to support the DualSense controller, and not just simply xinput.

And even DS4Windows does have an option to, instead of emulating an X360 controller, emulating a DS4, and although I haven't tested it much, I did manage to get Death Stranding (from Epic Games) to control the colored lights on my DS5 by setting DS4Windows to emulate a DS4. And from what I've heard, Death Stranding from Steam does have some extra features for the DS5, but I haven't managed to test it because the Epic Games version doesn't seem to support it all that well.

Also, nowadays it's becoming more and more common for people to use PlayStation controllers on their computers, and Steam has a good deal of features to support such controllers. I do think it's not unlikely that more and more games will start adding actual support for PlayStation controllers along with xinput.

**Comment by mika-n** [comment]
Even Microsoft tried to convince that xinput is something "new and better" than dinput interface then it is not exactly like that. XInput interface is veeeeery limited to support anything else but "xbox gamepad" type of buttons and events and axis. But the dinput interface is still available on Windows and it is much more flexible and supports different kind of hardware (not just xbox gamepad type of hw). So, doing those custom DS4 and DS5 things is possible via dinput interfaces if just games would support it.

**Comment by Ryochan7** [comment]
Some minor support has been added in the latest code. The main reason to use it would be for the Two Stage trigger mode. Some resistance can be added towards the end of the trigger to fake a button click when engaging the virtual Full Pull button.
