### ISSUE TITLE
Nacon Asymmetric Wireless Controller Support

### ISSUE THREAD

**Issue by Deathscyther1** [Ryochan7/DS4Windows#1719]
Please add Nacon Asymmetric Wireless Controller Support. Right now it doesn't show up in DS4Windows. If it already exists, please tell me what I might be doing wrong.

Edit:
The Debug Version does detect it, but the touchpad doesn't work and it shows my battery as 0%, changing light color doesn't work etc.  In Output Slots it also shows X360 instead of DS4 and in Gamepad Tester it says Xbox 360 Controller (XInput STANDARD GAMEPAD). In the Control Panel it shows 'Controller (XBOX 360 for Windows)' and 'Controller (Wireless Controller for PS4)', under both it shows Status: OK even though I never had an Xbox 360 Controller and I only have my Nacon Asymmetric Wireless Controller Connected with the Bluetooth receiver. In Windows Bluetooth Settings it only Shows 'Wireless Controller for PS4'. Only the things that already work without DS4Windows work and everything in Xinput checker works as well.

Edit 2:
In the debug version it gets detected as a potential DS4 gamepad. I have it connected over a usb bluetooth adapter. The rumble tests also don't work, while Rumble does work without DS4Windows. 

Edit 3:
Jays2Kings' DS4Windows doesn't detect it either and in the Debug version of Ryochan7's DS4Windows the light and touchpad don't work. The touchpad doesn't do anything and the light just glows white, no matter what.

Log:
[Log.txt](https://github.com/Ryochan7/DS4Windows/files/5760204/Log.txt)

**Comment by mika-n** [comment]
You are not telling the truth, the whole truth, and nothing but the truth.

With the information you gave it is impossible to say this-or-that unless someone has the exact same hardware. Please see the pinned "Read this before posting a new issue ticket" post.

And then follow the instructions given there and the link posted there to run a debug version and to generate a detailed logfile.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by Deathscyther1** [comment]
> You are not telling the truth, the whole truth, and nothing but the truth.
> 
> With the information you gave it is impossible to say this-or-that unless someone has the exact same hardware. Please see the pinned "Read this before posting a new issue ticket" post.
> 
> And then follow the instructions given there and the link posted there to run a debug version and to generate a detailed logfile.
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

Is it ok now?

**Comment by mika-n** [comment]
Okey, looks like the NaconAsymmetricWireless is registered in PC as a limited xinput device instead of "fully compatible DS4 dinput" device.

Nacon support page also says this: "The Asymmetric Wireless Controller is compatible with all PC games that are X-Input compatible"  Note the word "x-input compatible", it means that the gamepad firmware or the gamepad driver makes it to look like xbox xinput device and not as DS4 dinput device in PC.

But, this has nothing to do how the virtual output controller looks like. You can set the output mode as xbox360 or dualshock4 in DS4Windows profile settings. This is why you see the  "Xbox360 gamepad" controller. That is perfectly normal (and you can change the virtual output controller type to be ds4), but it has nothing to do how the physical source controller looks like to PC as an input. See the following web pages for more info.

https://github.com/Ryochan7/DS4Windows/wiki/Settings

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

But, if you cannot force the gamepad or the gamepad driver to make the Nacon ASymmetric to talk to PC as standard DS4 dinput device then there is nothing DS4Windows app can do about it (some 3rd party gamepads make an idiotic decision in PC to use xinput mode even when the gamepad would support full ds4 operation mode with PS4 console).

**Comment by Deathscyther1** [comment]
> 
> 
> Okey, looks like the NaconAsymmetricWireless is registered in PC as a limited xinput device instead of "fully compatible DS4 dinput" device.
> 
> Nacon support page also says this: "The Asymmetric Wireless Controller is compatible with all PC games that are X-Input compatible" Note the word "x-input compatible", it means that the gamepad firmware or the gamepad driver makes it to look like xbox xinput device and not as DS4 dinput device in PC.
> 
> But, this has nothing to do how the virtual output controller looks like. You can set the output mode as xbox360 or dualshock4 in DS4Windows profile settings. This is why you see the "Xbox360 gamepad" controller. That is perfectly normal (and you can change the virtual output controller type to be ds4), but it has nothing to do how the physical source controller looks like to PC as an input. See the following web pages for more info.
> 
> https://github.com/Ryochan7/DS4Windows/wiki/Settings
> 
> https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
> 
> But, if you cannot force the gamepad or the gamepad driver to make the Nacon ASymmetric to talk to PC as standard DS4 dinput device then there is nothing DS4Windows app can do about it (some 3rd party gamepads make an idiotic decision in PC to use xinput mode even when the gamepad would support full ds4 operation mode with PS4 console. Some gamepads have an option in driver to choose if the gamepad is seen as xinput or dinput device in PC or a switch or you need to get rid of some of those Nacon ASymmetric device drivers which are responsible of doing this idiotic decision).

How do I remove these drivers?

**Comment by mika-n** [comment]
I have no idea how to tweak/remove/nuke those vendor specific drivers or settings there to make the gamepad register itself as dinput and not as xinput device in PC. It is a vendor specific thing, so you have to try to figure it out because not many people have that gamepad, I guess.

**Comment by Deathscyther1** [comment]
> 
> 
> I have no idea how to tweak/remove/nuke those vendor specific drivers or settings there to make the gamepad register itself as dinput and not as xinput device in PC. It is a vendor specific thing, so you have to try to figure it out because not many people have that gamepad, I guess.

It works exactly like the Nacon Revolution Unlimited Pro Controller, just that it switches automaticallyband there's no way to do it. manually.

**Comment by mika-n** [comment]
Some Nacon/Razor gamepads doing the same xinput mode in PC worked as DS4 dinput devices in PC once the Nacon/Razor specific device drivers were uninstalled from WinOS (uninstall certain device driver).  But I don't know more details about it because I don't have Nacon/Razor gamepad. I guess those device drivers sent "hey! lock yourself in xinput mode" command to the gamepad and when the driver was uninstalled the gamepad was ready to receive the "switch to ds4 mode" command sent by DS4Windows app (ie. DS4Windows app sends the same command PS4 console does).

But exact details with your gamepad model is something no one else but the one with that hardware can debug and dig out.

**Comment by Deathscyther1** [comment]
> 
> 
> Some Nacon/Razor gamepads doing the same xinput mode in PC worked as DS4 dinput devices in PC once the Nacon/Razor specific device drivers were uninstalled from WinOS (uninstall certain device driver). But I don't know more details about it because I don't have Nacon/Razor gamepad. I guess those device drivers sent "hey! lock yourself in xinput mode" command to the gamepad and when the driver was uninstalled the gamepad was ready to receive the "switch to ds4 mode" command sent by DS4Windows app (ie. DS4Windows app sends the same command PS4 console does).
> 
> But exact details with your gamepad model is something no one else but the one with that hardware can debug and dig out.

I tried to google it, but I couldn't find WinOS anywhere, what is that? Also could you  tell me how to uninstall these drivers?

**Comment by Masamune3210** [comment]
WinOS is just windows

**Comment by mika-n** [comment]
Hmmm.. If you don't know what WinOS means than I think you better leave those device drivers alone or you risk corrupting the whole WinOS installation. Easiest way is just to purchase a genuine DS4 gamepad :-)

**Comment by Deathscyther1** [comment]
> 
> 
> Hmmm.. If you don't know what WinOS means than I think you better leave those device drivers alone or you risk corrupting the whole WinOS installation. Easiest way is just to purchase a genuine DS4 gamepad :-)

I just didn't know you'd abreviate Windows was called WinOS as well.

**Comment by mika-n** [comment]
Device Manager tool in WinOS but which driver there? No idea because each vendor may use different driver name.

**Comment by Deathscyther1** [comment]
> 
> 
> Device Manager tool in WinOS but which driver there? No idea because each vendor may use different driver name.

When I plug it in, the 'Xbox 360 Peripherals' section appears and there's an 'Xbox 360 Controller for Windows' there.

**Comment by mika-n** [comment]
difficult to say anything without having the hardware and debugging/trial-and-error tests. You are on your own with this one.

**Comment by Deathscyther1** [comment]
> 
> 
> difficult to say anything without having the hardware and debugging/trial-and-error tests. You are on your own with this one.

Do you know, where the .inf files for the drivers are?

**Comment by mika-n** [comment]
Those files are device driver stuff and stored in Windows folders. You can try to modify/tweak those files to black list devices not to use certain driver or force the hardware to use certain driver version. But, now we are talking about WinOS device driver tweaks and not DS4Windows app tweaks. I will close this ticket and wish you good luck with tweaking those the gamepad and drivers. There are better sites to ask help with device driver stuff than this site. Google is your friend.
