### ISSUE TITLE
Exclusive mode not working properly with certain games (for example Broforce)

### ISSUE THREAD

**Issue by JarnoVgr** [Ryochan7/DS4Windows#172]
An overview of my setup:
- Clean Windows 10 install with latest DS4Windows.
- DS4Windows launches as a task on boot. 'Hide DS4 Controller' option is enabled.
- (PS4) Controller support is disabled in Steam.
- Using a standard Bluetooth dongle.

Exclusive mode works fine as long as the game (Broforce for example) is not running. However, when it does, DS4Windows cannot bind exclusive to the controller and the game crashes.

I can't recall this being a problem on my previous Win10 install, which was setup the same way.

Is it possible to have full controller exclusivity for DS4Windows, or is this a known bug?

Thanks in advance.

**Comment by JarnoVgr** [comment]
Probably a duplicate of #118

**Comment by Ryochan7** [comment]
I am guessing that the hotplug routine in the game probably runs more quickly than the period that DS4Windows waits before attempting to obtain exclusive access to the HID device again. The approach being used to obtain exclusive access to a device is a brittle hack that works more often than not. The only real way around this problem is to use HidGuardian to only allow access to the HID device for applications in the whitelist. I have been using HidGuardian on my system for a little over a month and there is minor support for HidGuardian in DS4Windows; the necessary whitelist key is made when DS4Windows is started if the application is running with admin privileges.

**Comment by JarnoVgr** [comment]
It would be great if you could make a simple tutorial how to setup HidGuardian. Because from what I've read in #118 the latest public version doesn't work. Do I need to compile HidGuardian myself?

**Comment by SeemsFishy** [comment]
HidGuardian linked in #118 works just fine. However it may add a few frames of additional delay, but still worth trying. It solves Exclusive mode issues completely.

**Comment by TristanYoung** [comment]
I would like to know the mechanics behind HIDGuardian.  Keep in mind, I have done programming years ago, but never Windows services.

Does it act like a proxy - accessing the controllers early-on before steam and other programs can take control, and then acts as a relay?  I'd like to know specifically why it would add a few few frames of additional delay.

Surely there's a way to solve this issue that doesn't involve adding any frame delay.

Couldn't a service be created that grabs the controllers early-on in the start-up, and cleanly hands them over to DS4Windows, or otherwise re-create DS4Windows as a service, with a separate configuration GUI?

**Comment by Ryochan7** [comment]
Although I have not tried it myself, HidGuardian version 1.14.0.0 should not have the latency problems that 1.13.8.0 had; I am still using my custom 1.13.8.1 build on my system.

https://downloads.vigem.org/stable/1.14.0.0/windows/x86_64/HidGuardian_signed_Win7-10_x86_x64_v1.14.0.0.zip

HidGuardian acts as an HID filter driver which utilizes a device list so it knows if it should act on a device when a new HID device is plugged into the system. When a program wants to use a device, HidGuardian will check if the program attempting to open the affected device is whitelisted and it will only return an HID device handle if the program is whitelisted. The HidGuardian README file explains how it works pretty well.

https://github.com/nefarius/ViGEm/blob/master/Sys/HidGuardian/README.md

**Comment by TristanYoung** [comment]
Ok, got it.  So it's basically a proxy, and I can understand how it might take up some frames by passing the data on from the controller to the application - one additional hop.

I wonder how much that would be detectable.  Summing all the work you've done on DS4Windows in terms of optimizing and reducing latency with the adding the latency of HID Guardian - would that result in reduced latency, or an increase in latency?

**Comment by Ryochan7** [comment]
Bought Broforce and tried this out. Exclusive mode was never able to work if Broforce was running before connecting the controller. I never had the game crash on me though.

**Comment by Ryochan7** [comment]
The experience with Broforce gave me an idea to try out. The disabling process was never able to complete and would always error out. I kept getting different errors returned from Windows after the SetupDiCallClassInstaller call but the most consistent one was ERROR_INVALID_HANDLE. Also, the problem would cause the DS4 to get permanently disabled once the controller was disconnected. For the minor testing that I have done so far, just attempting to re-enable the device anyway at least got rid of the problem with the controller getting permanently disabled.

**Comment by Ryochan7** [comment]
Testing other scenarios, such as uPlay, seem to indicate that this change can stick. Luckily, Broforce gave a consistent way to reproduce this type of problem that could not be nailed down before due to it happening very sporadically.

As for the original issue, it does not seem like there is a way to make the old exclusive mode hack work while Broforce is running. HidGuardian is needed to get exclusive access to the DS4 while Broforce is running.

**Comment by JarnoVgr** [comment]
Thank you very much for looking into this! I guess I'll give HidGuardian a shot to get rid of exclusivity issues for once and for all.
