### ISSUE TITLE
Two controllers in settings pane "Game Controllers" when using bluetooth

### ISSUE THREAD

**Issue by tom-mayer** [Ryochan7/DS4Windows#1726]
**Describe the bug**
When pairing the DS4 via bluetooth and running ds4windows, 2 controllers appear in "Game Controllers". Applications like retroarch are not able to map the buttons then. (Weird enough, the retroarch menu works fine but mapping doesn't, it does however recognize two controllers).

**To Reproduce**
1. Pair DS4 over bluetooth on windows
2. ("Wireless Controller" will appear in "Game Controllers" but doesn't get any input data when looking at "Properties")
3. Start ds4windows
4. (ds4windows recognizes controller and blue light turns on etc)
5. ("8bitdo" controller appears in "Game Controllers" and receives input from gamepad )

**Expected behavior**
Only one controller (8bitdo / xbox360) should be present in "Game Controllers"

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 
 - OS:Win 10 Build 18363
 - DS4Windows Version latest

**Additional context**
I used an 8BitDo stick before to use the controller wireless

PS: if it helps with debugging I can also setup a dev environment, will just take some time due to my internet connection being very slow and Visual Studio being very big xD

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by tom-mayer** [comment]
Hey, thanks for the answer. I tried the "hide" option already, it turned on after closing some stuff, but did not remove the "Wireless Controller". That was also the first thing I tried after lookigng through the docs.

**Comment by mika-n** [comment]
Make sure you don't see "warning. failed to acquire exclusive access" warning messages in logfile or in Logs tab page because if you see this msg then it means the "hide ds4 controller" failed. If you can't get rid of that msg then your only option to hide the physical "Wireless Controller" device may be HidGuardian alternative.

But there is catch about DS4 BT connections and PCs and it may explain why you may see a dead WirelessController device. By default DS4 gamepad is in so called "PC-friendly mode" when it is connected over BT. In this mode those special DS4 features dont work in PC (touchpad/lightbar/gyro etc). This pc-friendly-mode is a like "emulated xbox compatible" mode without DS4 goodies.

The DS4 firmware starts to act like "true DS4 pad" over BT only when the pad receives certain control commands from a peer (PS4 console or PC over BT). WinOS itself doesn't know how to send out these control commands to DS4 pad, but DS4Windows application knows how to do it, so this is why those DS4 goodies work in PC even over BT (but you need to have DS4Windows app running to use those goodies). The result of this "switch over" from PC-friendly-mode to a true native DS4 mode is that the original BT WirelessController device handle ends up being a dead device in WinOS. It is a bug/limitation of WinOS gamepad support and not a bug in DS4Windows app. DS4Windows knows to to use this "dead WirelessController" devices by a raw BT device and to feed out gamepad events (and DS4Windows app specific transformation and re-map rules) over a virtual output controller created by ViGem driver.

So, having a dead Wireless Controller when the pad is connected over BT is normal and nothing to worry about. In fact in this case it is not even required to use "Hide DS4 Controller" option because the duplicated double controller device handle is dead already and doesn't send duplicate events to games. If you want to hide the dead device handle then HidGuardian can do it.

**Comment by tom-mayer** [comment]
Hey thanks for the detailed answer. I made sure that the hide option worked, but from what you described the raw "Wireless Controller" is to be expected. On the windows property pane it also doesn't do events, but it doesn't no matter if ds4 is loaded or not. Interestingly enough the website for checking if the controller works which is linked inside the ds4 tool does show input on both gamepads, so that was what alerted me. 
From what you said I gather that without ds4windows it should be in some sort of compatibility mode where normal inputs should work but ps4 specific stuff like gyres etc don't. This is not the case from what I see. Pairing without using ds4windows just adds the dead controller, no inputs. 
As this dead controller seems to be expected it is probably an issue with retroarch rather than ds4windows and I gotta tackle it from that angle. I will definitely try getting rid of it with HidGuardian, thanks for that hint. Is it  intended that ds4windows adds the device as an 8Bitdo stick or is that some sideeffect of me using a 8Bitdo stick normally to have wireless on the ds4?

**Comment by mika-n** [comment]
I have no idea what "8Bitdo stick" means. Do you have a picture of JOY.CPL controlPanel screen? Or rename the latest debug logfile as .TXT file and attach it here in a comment box as an attachment (ie. don't copy-paste the content but drag-n-drop attach the .TXT file)

**Comment by Ryusennin** [comment]
From what I remember, it's a common bug in RetroArch which for some reason detects the X360 pad as an 8BitDo controller.
