### ISSUE TITLE
PICTEK HD-060: Gyro drifts down constantly (otherwise works perfectly wirelessly)

### ISSUE THREAD

**Issue by AdriandeLima** [Ryochan7/DS4Windows#1727]
## Describe the bug
I got a [PICTEK HD-060](https://www.amazon.co.uk/PICTEK-Wireless-Controller-Joystick-Vibration/dp/B081N2F9PV) for Christmas, and I've set it up with DS4Windows (and Vigem and HIDGuardian). It's a 3rd-party DS4 replacement with Xbox layout, but also includes the touchpad, gyro, lightbar and a turbo button.

Connected via Bluetooth, it shows up as a ```PC263 Controller``` in Windows, and a ```DS4 v.2 (D0:27:96:3D:14:B7)``` ID in DS4Windows. ```VID: 0x054C, PID: 0x09CC``` according to HIDNinja

### Working:
Buttons, Analogue Sticks, Triggers, Lightbar, Touchpad, Turbo function

### Bugs:
- The gyro half works. It shows up in the SixAxis box under Controller Readings, but when I try and map it to anything, it constantly drifts downwards (tested by mapping to mouse). The ```Accel Y axis``` field in Controller Readings shows the Y slider all the way over to the left for an idle resting controller (whereas X and Z acceleration hovers near the middle for idle). The constant drifting looks like it's due to this controller having a different offset for Y acceleration. Would it be possible to fix this?

- Doesn't work wired, Windows glitches out and spams "installing controller"; controller is advertised as working out-of-the-box with Windows, Android and PS4. Possibly when wired to Windows it tries to emulate an X360 or something by default? 

- Under Output Slots, the first 5 X360 slots are occupied as ```Active``` and ```Dynamic``` (not sure if this is normal; surely 1 should show up as used, not 5?) EDIT: Disconnecting the controller shows that it only uses the first slot. The other 4 slots stay occupied. No idea why, no other controllers are connected. Maybe due to the glitch when I plugged it in wired? Not sure how to clear the slots or if this will cause problems later on.

- When disconnecting, the Log occasionally says:
```
Gamepad data write connection is lost. Disconnecting the gamepad. LastErrorCode=997
Controller 1 was removed or lost connection
```
(might have been leftovers from when I tried it wired and it glitched out)

## Desktop:
 - Controller Make and Model: PICTEK HD-060 / PC263 (manufactured by Shenzhen Hong Jingda Electronics Co. Ltd.).
 - OS: Windows 10 Pro 1909 (desktop PC, using Windows Bluetooth via a dongle)
 - DS4Windows Version: 2.2.1, ViGem v1.16

**Comment by mika-n** [comment]
Try running the debug version (extract the debug version into the same folder where you have the official DS4Windows 2.2.1 version). The debug logfile (%APPDATA%\DS4Windows\Logs folder) might tell more, for example, about the gyro calibration.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

And you seem to have old ViGem driver version. I recommend to install the latest 1.17.333 version because Nefarious has fixed various bugs and improves few things in ViGem driver which may cause "ghost virtual controller" issues when a connection is unexpectedly lost.
https://github.com/ViGEm/ViGEmBus/releases

About the USB wired issue. Some 3rd party controllers wants to act like xinput devices in PC instead of as dinput devices. If the gamepad firmware or driver detects that the connection is made with PC and not with PS console then the gamepad may make an idiotic decision to act like xinput device. This usually means "good bye touchpad/lightbar/gyro" support in PC. Could be that the driver of that pad does this when it is connected over USB and not over BT in PC? 

Those "gamepad data write connection is lost. Disconnecting. LastErrorCode=xxx" messages when a gamepad is intentionally disconnected is a "false alarm". Nothing to worry about. But if you keep seeing this when you didn't intentionally disconnected the pad then it is an indication of connectivity problem.

**Comment by AdriandeLima** [comment]
Thank you so much for the reply and helping me!

Here's the Debug Log:
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5761988/ds4windows_log.txt)

I haven't updated to the latest version of Vigem because I'm worried about https://github.com/ViGEm/ViGEmBus/issues/65 and it's Win10 only so no backwards compatibility with my other PCs. I'll test it later, see if it fixes the ghost controllers.

I tested the controller on another PC, and I'm pretty sure you're right - it's doing some weird XInput thing when wired. Works rubbish; Rstick has extra-low sensitivity in that mode. Good thing it uses fragile microUSB, meaning it is unusable as a wired controller. I'll just use it over Bluetooth 😀

Checking the log now, it looks like the error code hasn't appeared since. So it was from when I plugged it in to my PC and it glitched out. Tested for a while in Death Stranding and it's working great! (except for gyro)

**Comment by AdriandeLima** [comment]
** Wired bug **

I tested it wired on my main PC (with DS4Windows closed) and it doesn't glitch out (doesn't show up, though, due to HIDGuardian). Having DS4Windows open at the same time glitches it out with it repeatedly connecting and disconnecting, and gradually fills up all available XInput slots.

If there is a compatibility patch made, could it please somehow blacklist this controller so that (worst case) DS4Windows doesn't keep trying to set it up? This would avoid the weird glitch.

Here's a debug log of when it was glitching: 
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5762019/ds4windows_log.txt)

**Comment by AdriandeLima** [comment]
Just a little update of something I noticed the other day when configuring the controller.
The y axis on the motion controlls seems to be rotated 90°, so that it's in a "0" state when the lightbar is pointed directly at the ceiling (up)

**Comment by mika-n** [comment]
There may be some gyro calibration differences between DS4 gamepads. And especially between pads manufactured by different brands. The genuine DS4 pad also make some weird things with gyro in certain positions, so that behavior is not that exceptional.

DS4Windows app itself doesn't have gyro calibration routine to fine tune these gamepad specific differences. You may be on your own with that copy-cat.

**Comment by Darthagnon** [comment]
I've tested one of these controllers before; gyro Y axis was always offset from the other axes by a bit, and it looked like it was just an offset that was wrong. Doesn't DS4Windows adjust offsets under ```Edit Profile``` >> ```Axis Config``` >> ```SixAxis``` @mika-n?

**Comment by mika-n** [comment]
DS4Windows doesn't do custom calibration for gyro. It uses the internal calibration found in genuine DS4 gamepads.
But, there is a pull request with a custom gyro calibration routine. 
https://github.com/Ryochan7/DS4Windows/pull/1776

**Comment by AdriandeLima** [comment]
Turns out it was just bad luck on my part with the controller, and there was actually a problem with the gyro. The seller sent a replacement, and the gyro doesn't drift at all, despite weird gyro Y axis readings.

The PICTEK HD-060 can be added to the list of unofficial controllers that working perfectly with DS4Windows if there is one.

**Comment by Darthagnon** [comment]
I can confirm that #1776 fixed the gyro drift problem with the PicTek controller I was helping my brother with. Run gyro calibration with it sitting flat, and it no longer drifts.

Drift reappeared when switching profiles or something, but a quick calibration fixed it again. Works very well! Thank you!
