### ISSUE TITLE
Ds4 keeps disappearing

### ISSUE THREAD

**Issue by shogunreaper** [Ryochan7/DS4Windows#1731]
Not sure why this is happening but my ds4 controller just keeps disappearing.

The only way i can get it to come back is to either restart my computer or toggle the "hide ds4 controller" option in settings.

Wireless controller still shows up in bluetooth and in hidninja but when it's disappeared the xbox controller doesn't show up in there anymore.

**Comment by shogunreaper** [comment]
heres a log:

01/03/2021 20:58:09: DS4Windows version 2.2.1
01/03/2021 20:58:09: DS4Windows Assembly Architecture: x64
01/03/2021 20:58:09: OS Version: Microsoft Windows NT 10.0.18363.0
01/03/2021 20:58:09: OS Product Name: Windows 10 Pro
01/03/2021 20:58:09: OS Release ID: 1909
01/03/2021 20:58:09: System Architecture: x64
01/03/2021 20:58:09: Running as User
01/03/2021 20:58:09: HidGuardian in use. Launching HidGuardHelper.
01/03/2021 20:58:10: Starting...
01/03/2021 20:58:10: Connection to ViGEmBus 1.16.112.0 established
01/03/2021 20:58:10: Searching for controllers...
01/03/2021 20:58:10: Using Shared Mode
01/03/2021 20:58:10: Found Controller: A4:53:85:15:46:05 (BT) (DS4 v.2)
01/03/2021 20:58:11: Plugging in virtual X360 Controller
01/03/2021 20:58:11: Associate X360 Controller for input DS4 #1
01/03/2021 20:58:11: Controller 1 is using Profile "Default". Battery level is 12%
01/03/2021 21:00:09: Controller 1 is using Profile "Default". Battery level is 54%
01/03/2021 21:40:19: A4:53:85:15:46:05 disconnecting due to idle disconnect
01/03/2021 21:40:19: Disassociate X360 Controller for input DS4 #1
01/03/2021 21:40:19: Unplugging virtual X360 Controller
01/03/2021 21:40:19: Controller 1 was removed or lost connection

----this was after toggling hide ds4 controller---

01/03/2021 22:08:38: Stopping Virtual Output Controllers
01/03/2021 22:08:38: Closing connection to ViGEmBus
01/03/2021 22:08:38: Stopping DS4 Input Controllers
01/03/2021 22:08:38: Stopped DS4Windows
01/03/2021 22:08:38: Starting...
01/03/2021 22:08:38: Connection to ViGEmBus 1.16.112.0 established
01/03/2021 22:08:38: Searching for controllers...
01/03/2021 22:08:38: Using Exclusive Mode
01/03/2021 22:08:39: Found Controller: A4:53:85:15:46:05 (BT) (DS4 v.2)
01/03/2021 22:08:39: Plugging in virtual X360 Controller
01/03/2021 22:08:39: Associate X360 Controller for input DS4 #1
01/03/2021 22:08:39: Controller 1 is using Profile "Default". Battery level is 37%

**Comment by mika-n** [comment]
Update the ViGem driver, You seem to have an old version.
https://github.com/ViGEm/ViGEmBus/releases

**Comment by shogunreaper** [comment]
well i updated it to 1.17.333 and i'm still having the same problem.

01/04/2021 06:13:54: DS4Windows version 2.2.1
01/04/2021 06:13:54: DS4Windows Assembly Architecture: x64
01/04/2021 06:13:54: OS Version: Microsoft Windows NT 10.0.18363.0
01/04/2021 06:13:54: OS Product Name: Windows 10 Pro
01/04/2021 06:13:54: OS Release ID: 1909
01/04/2021 06:13:54: System Architecture: x64
01/04/2021 06:13:54: Running as User
01/04/2021 06:13:54: HidGuardian in use. Launching HidGuardHelper.
01/04/2021 06:13:55: Starting...
01/04/2021 06:13:55: Connection to ViGEmBus 1.17.333.0 established
01/04/2021 06:13:55: Searching for controllers...
01/04/2021 06:13:55: Using Shared Mode
01/04/2021 06:14:12: Found Controller: A4:53:85:15:46:05 (BT) (DS4 v.2)
01/04/2021 06:14:12: Plugging in virtual X360 Controller
01/04/2021 06:14:12: Associate X360 Controller for input DS4 #1
01/04/2021 06:14:12: Controller 1 is using Profile "Default". Battery level is 100%
01/04/2021 06:15:12: A4:53:85:15:46:05 disconnecting due to idle disconnect
01/04/2021 06:15:12: Disassociate X360 Controller for input DS4 #1
01/04/2021 06:15:12: Unplugging virtual X360 Controller
01/04/2021 06:15:12: Controller 1 was removed or lost connection
01/04/2021 06:15:20: Found Controller: A4:53:85:15:46:05 (BT) (DS4 v.2)
01/04/2021 06:15:20: Plugging in virtual X360 Controller
01/04/2021 06:15:20: Associate X360 Controller for input DS4 #1
01/04/2021 06:15:20: Controller 1 is using Profile "Default". Battery level is 100%
01/04/2021 06:16:26: A4:53:85:15:46:05 disconnecting due to idle disconnect
01/04/2021 06:16:26: Disassociate X360 Controller for input DS4 #1
01/04/2021 06:16:26: Unplugging virtual X360 Controller
01/04/2021 06:16:26: Controller 1 was removed or lost connection
01/04/2021 06:25:34: Found Controller: A4:53:85:15:46:05 (BT) (DS4 v.2)
01/04/2021 06:25:34: Plugging in virtual X360 Controller
01/04/2021 06:25:34: Associate X360 Controller for input DS4 #1
01/04/2021 06:25:34: Controller 1 is using Profile "Default". Battery level is 100%
01/04/2021 06:26:47: A4:53:85:15:46:05 disconnecting due to idle disconnect
01/04/2021 06:26:47: Disassociate X360 Controller for input DS4 #1
01/04/2021 06:26:47: Unplugging virtual X360 Controller
01/04/2021 06:26:47: Controller 1 was removed or lost connection
01/04/2021 06:35:25: Found Controller: A4:53:85:15:46:05 (BT) (DS4 v.2)
01/04/2021 06:35:25: Plugging in virtual X360 Controller
01/04/2021 06:35:25: Associate X360 Controller for input DS4 #1
01/04/2021 06:35:25: Controller 1 is using Profile "Default". Battery level is 100%
01/04/2021 12:33:12: A4:53:85:15:46:05 disconnecting due to idle disconnect
01/04/2021 12:33:12: Disassociate X360 Controller for input DS4 #1
01/04/2021 12:33:12: Unplugging virtual X360 Controller
01/04/2021 12:33:12: Controller 1 was removed or lost connection

**Comment by mika-n** [comment]
Maybe the debug version would tell more because it generates loooots of more detailed log messages.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

And there is DS4WindowsDebug.exe.config file and tweak settings there to experiment all sort of different things.

Anyway, I guess you have gone through the BT connection tips?
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#gamepad-connection-over-bluetooth-bt

If there are issues with BT connectivity and you have BT usb dongle in the PC then seemingly simple "use usb extension cable to move the BT receiver further away from the radio storm caused by PC chassis" may solve the issue. Or try different USB ports for the BT dongle (back and front ports, usb2/usb3 etc).

And are you sure you have genuine DS4 revision2 gamepad? Many cheap chinese copy-cats struggle over BT connection and the LS/RS stick movement is square instead of circular as it is in the genuine DS4 pad. What do you see in the back of the gamepad? Take a picture of the label. Do you see "Sony Computer Entertainment Inc" or "Sony Interactive Entertainment Inc" company name?

Or not all BT dongles/internal chipsets are compatible with DS4 BT requirements. Those may work initially when the gamepad is still in PC-friendly mode but once DS4Windows app commands the gamepad to switch over to native DS4 mode some BT chipsets start to struggle (the native DS4 mode sends a lot more data back and forth between the DS4 and PC than the default PC-friendly mode).

**Comment by Avatarchik** [comment]
I have the same thing, sony computer entertaiment inc
cuh-zct1h

**Comment by shogunreaper** [comment]
is the debug version the same as the latest regular ds4windows?

I replaced it and so far i'm not having the same problem.

Also yes i'm sure its a genuine one, i've had it for about 5 years now bought the ds4/official bt adapter bundle back in 2016 i believe. (dont use the bt adapter anymore though as it broke)

**Comment by mika-n** [comment]
> I have the same thing, sony computer entertaiment inc
> cuh-zct1h

Take a look at the following discussion. If you have "Manufacturer:Sony COMPUTER Entertainmen" (and notice how there is no space between "Manuf;" and "Sony" words) then it may be a fake copy-cat. DS3 pads were labeled as SonyComputer but DS4 pads should be SonyInteractive. 
https://github.com/Ryochan7/DS4Windows/issues/1691#issuecomment-753405846

Another way to check if the gamepad is a fake copy-cat is to test how LS/RS stick behaves when you move it around as fully extended. The movement should be circular, but if the movement is more like square then it is a fake copy-cat. You can see this from ControllerReadings tab page in DS4Windows or by downloading "Game Controller Tester" app from Win10 Store or using gamepad-tester.com web page.

**Comment by mika-n** [comment]
> is the debug version the same as the latest regular ds4windows? I replaced it and so far i'm not having the same problem.

Yes and no. The debug version uses the same base code branch as the official release, but the debug version is actually a bit newer because it contains changes not yet officially released. But the next official release should have everything the debug version now may have as an "extra".

**Comment by Avatarchik** [comment]
debug log: https://pastebin.com/2RXCVp8Y

**Comment by mika-n** [comment]
@Avatarchik  Looks like the DS4v1 gamepad refuses to accept DS4 gyro calibration commands and this way doesn't switch over to native DS4 mode in BT connection. This is a classical problem of fake DS4v1 copy-cats. Many cheap chinese copy-cats use DS4v1 hardware ID even when the firmware in the copy-cat is not fully 100% compatible. Those may work just fine over USB in PC, but often struggle over BT.

See the DS4WindowsDebug.exe.config config file. You may wanna try to experiement with various options there (true/false to enable/disable certain features and various other protocol modifiers).

If you have purchased that DS4v1 gamepad within the last 4 years then it is probably a fake copy because Sony haven't released genuine DS4v1 gamepads in 5 years (these days they release only DS4v2 gamepads).

And is the LS/RS stick movement square or circle? If it is square then it is fake.

**Comment by shogunreaper** [comment]
Alright it happened again after a few days while using the debug version [here's the log.](https://pastebin.com/raw/V7gHbmjZ)

oddly at the end it says that it idle disconnected but all i did was unplug it and try to turn it on (i leave it plugged in via usb when not using it to keep it charged)

16:27:58 is when i hit hide ds4 controller and it came back.

**Comment by mika-n** [comment]
I don't know for sure why the gamepad there behaves like that. Sometimes BT is a bit mystery

**Comment by shogunreaper** [comment]
it's not just bt though, i can't use it with usb while its like that either.

it's like its been locked up or something.

**Comment by SergeyPismennyi** [comment]
I have the same issue using dualsence
