### ISSUE TITLE
ds4windows randomly choose player / controller between player 1 until 4 (it only connected one controller)

### ISSUE THREAD

**Issue by nfsmania** [Ryochan7/DS4Windows#1748]
please fix the ds4windows randomly choose player between 1 until player 4 (while it only use one controller not 4), i already try the newest driver but it still has that problem, while the newest driver not require restart to make the controller player 1 again, but it still annoying, 

and the problem is appear when i connect and reconnect the ds4 press start and stop on ds4windows or using ps button to turn off the controller while i already press stop on ds4windows, after press start on ds4windows and connect the controller again it become player / controller 2, 3 or 4 

and if it likes that (become other than player / controller one) on cemu or rpcs3 many games that only support 1 controller are not recognized the controller like yakuza, god eater 3, senran kagura, etc 

it still detect as controller 1 on ds4windows but on cemu or rpcs3 it detects as controller / player 2-4 

also sometimes it needs to restart windows to make the controller detect as player 1 or controller 1 again, please fix that problem

**Comment by Ryusennin** [comment]
In "output slots" tab, try making your current controller permanent instead of dynamic.

**Comment by mika-n** [comment]
Make sure you have the latest ViGem driver also (DS4Windows app updater doesn't update ViGem driver).
https://github.com/ViGEm/ViGEmBus/releases

And if you experience something weird then make sure "double controller issue" is not the reason:
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

And if nothing else helps and WinOS messes up with xinput controllers then consider using "permanent" slot option in DS4Windows (outputSlots tab page) as Ryusennin suggested. This is partly WinOS/xinput and ViGem driver issue and sometimes the issue is beyond the control of DS4Windows app.
