### ISSUE TITLE
Dark Souls Remastered DS not working

### ISSUE THREAD

**Issue by EdgieEaster** [Ryochan7/DS4Windows#1777]
Dark Souls Remastered Dualshock emulation not working.

Desktop
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version 2.2.1

**Additional context**
DS Remastered see ds4 buttons, but emulation not working.

**Comment by Ryochan7** [comment]
Very likely some form of Exclusive mode has to be active. I looked and confirmed that Dark Souls Remastered does indeed have DS4 controller support but it is likely using DirectInput. Not sure what would happen if the original input controller were detected as well as the emulated one. Also, if you are using Bluetooth, the game might pick up the dead DirectInput interface rather than an emulated DS4.

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by 316elvenmaidens** [comment]
It requires Exclusive Mode enabled before the game is launched and overlays like Geforce Experience disabled
