### ISSUE TITLE
Issues after updating for latest version

### ISSUE THREAD

**Issue by vpontin** [Ryochan7/DS4Windows#178]
After updating to 1.4.107 i begin to have problems with DS4Windows.

First of all, USB connection wont work anymore, nor any log line appear indicating errors.

Second, connecting via BT always require me to check Yes on a UAC promt (i have "Hid DS4 Controller" checked but i dont remember needing to pass UAC dialogs on connect before), if i fail to accept that the program become broken, it doesnt show anything even DS4 showing the profile color. Only after restarting the PC (I'm using Windows 10 b1709 x64) solves the problem.

And ultimately some times the XBOX controller emulation simply dont work, and in the logs it indicate only going to dinput, and since i checked "Hid DS4 Controller" the ds4 is hidden and i cant play anything.

Is there any thing i need to do to fix this or those are bugs introduced on latest version?

**Comment by Ryochan7** [comment]
The only way to work around the UAC prompt is to always launch DS4Windows as the administrator. That is what I do on my system anyway in order to help increase process priority as well as not having to deal with UAC prompts.

The DInput only issues seem to come up at random. The only pending solution is to stop using the Scp Virtual Bus Driver and switch to using ViGEm. That should help get rid of some problems that DS4Windows tries to work around.

As for USB connections not working, you might want to check the relevant HID game controller device in Device Manager. The current exclusive mode hack sometimes leaves devices disabled after closing a device. Instead of using the older exclusive mode hack, I would recommend that you disable the "Hide DS4 Controller" option and look into HidGuardian. DS4Windows can utilize HidGuardian currently but it has to be launched as the administrator since DS4Windows has to write a registry key. You will have to write the necessary AffectedDevices registry key manually though.

Download:
https://downloads.vigem.org/stable/1.14.0.0/windows/x86_64/HidGuardian_signed_Win7-10_x86_x64_v1.14.0.0.zip

Main repository listing and README:
https://github.com/nefarius/ViGEm/tree/master/Sys/HidGuardian

Extra community documentation:
https://inputmapper.com/forum/general-chit-chat/754-found-a-correct-way-to-fix-exclusive-mode-on-windows-10-fall-creators-for-ds4

**Comment by vpontin** [comment]
I've installed HIDGuardian here and added the registry keys with proper hardware IDs. Should i still use DS4Windows or not?

**Comment by Ryochan7** [comment]
The bug mentioned about the exclusive mode trick should be resolved in the latest version. There should hopefully be no situation when DS4Windows will leave a device permanently disabled anymore. To be fair, InputMapper 1.6 has the same kind of exclusive mode problem; I cannot test 1.7 beta because it does not work on my system despite purging old files and trying many times.

I don't have any way to replicate the DInput only issue so I cannot say whether any change has been made regarding that issue. A problem with device hotplugging was found fairly recently but I am not sure what impact that would have; the issue was found while incorporating ViGEm support in DS4Windows and the changes mattered when using the ViGEm implementation.

Using a DS4 controller this way has always been a bit iffy. Luckily issues keep getting squashed so the experience keeps getting better. The safest option for performing this type of controller mapping currently is to use Steam although Steam has its own issues and that is why I do not use it; I don't even use Steam's controller mapping functionality for the Steam Controller.

**Comment by vpontin** [comment]
Well, i have this issue fixed back then when i became pissed trying to make my DS4 to work with hidguardian only (i was mistaken, i think), so i uninstalled everything and reinstalled ds4windows, setting to open as administrator via compatibility tab (but i lost the autostart feature, no matter if i put Program or Task Ds4windows doesnt autostart, but its a minor problem). Since then i didnt have any issue of this kind.

I forgot to report this and close the issue, so sorry...
