### ISSUE TITLE
DualSense Rumble not deep like DS4

### ISSUE THREAD

**Issue by BillisC** [Ryochan7/DS4Windows#1781]
**Describe the bug**
Hi there, Dualsense rumble is not deep and is quite annoying when playing forza horizon 4. In today's update you reduced the power to a nice point but the rumble is not as powerful as my dualshock 4. Ds4 is able to shake my hands while ds5 has a more “high pitched„ vibration

**To Reproduce**
Connect normally until it gets detected and emulated as xbox controller and then open forza. 

**Expected behavior**
I expected it to be deeper

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS5 (CFI-ZCT1W)
 - OS: Windows 10 Pro Build 2004
 - DS4Windows 2.2.2

**Comment by Ryochan7** [comment]
Some of it might just be attributed to the different tech used. Other than that, there is an option to change the Rumble strength used for DualSense controllers. Most people wanted the default sensitivity to be lower so that was changed with version 2.2.2. Full strength is available if you select High for Rumble Strength.

![ds4windows_ds_rumble](https://user-images.githubusercontent.com/581968/105094029-42941900-5a69-11eb-90cc-d55f49b73b46.png)

**Comment by BillisC** [comment]
Oh I didn't notice that option thanks👍
