### ISSUE TITLE
DualSense Light bar Single white led near bottom middle of light bar.

### ISSUE THREAD

**Issue by Ceroes** [Ryochan7/DS4Windows#1785]
**Describe the bug**
My DualSense has a white led lit near the bottom of the lightbar.

**To Reproduce**
Unsure
**Expected behavior**
Standard lit bar

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense (CFI-1CT1W)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 2.2.2]
 
 Edition	Windows 10 Pro
Version	20H2
Installed on	‎8/‎22/‎2020
OS build	19042.746
Experience	Windows Feature Experience Pack 120.2212.551.0

**Additional context**

**Comment by maestrini** [comment]
This is part of the new update. It indicates the player number.
From the changelog: "Now use player LEDs on Switch Pro, JoyCon, and DualSense controllers. Used to display input device slot number"

IMPORTANT: We need a way to turn this off in the profile or the settings though!!

**Comment by Ceroes** [comment]
Wow that's a stupid feature if you cannot turn it off... Like 1. I obviously know which player I am. 2 I can differentiate the controller by the light bar color. 3. Wtf.

**Comment by Valek2000** [comment]
we need a option to turn off this, and personalizate to put led in the midle of light bar, like is on steam.

**Comment by Felix989** [comment]
I have the same problem, and i dislike it. Please make it optional!

**Comment by Ryochan7** [comment]
Again a case of I can't win. People complain either way.

**Comment by Ryochan7** [comment]
Had to double check and that is not quite the way it works in Steam Input. With Steam, the Player Slot LED setting specifies the mode to use. The default is **Only with multiple controllers** with the other choices being **On** and **Off**. The middle LED is lit for slot number 1. Not sure what the LED arrangement would be when other controllers are enabled. I don't have a PS5 so I wouldn't know the intended behavior when connected to the console. 

The backend DualSense code is set up to map to the full range available with 5 LED lights. Although only 2 lights will ever be lit due to the 8 controller limit in DS4Windows. If people would want the middle LED light for slot 1 then a new mapping will be needed.

**Comment by Ceroes** [comment]
Is this the person who coded this in?On Jan 20, 2021 1:46 PM, Travis Nickles <notifications@github.com> wrote:
Again a case of I can't win. People complain either way.

**Comment by Ceroes** [comment]
I value your work and understand your point here ryochan. That being said I don't think it's a very well known feature and for a good 30initea I couldn't figure out if it was an intended feature, my controller or the program messing up.

We definitely need the ability to disable though.

**Comment by Ceroes** [comment]
Ar least now I know I can use the update without fear it's not functioning correctly and could harm my controller.

I originally had no idea this was an intended effect and while I did read the update and see that log not being familiar with that since I don't use steam or have a ps5 I didn't even know it was a feature not prior implemented. So my initial reaction was more than it needed and I apologise again I appreciate what you do.

**Comment by Bo98** [comment]
> I don't have a PS5 so I wouldn't know the intended behavior when connected to the console.

The correct behaviour is centre aligned:

![](https://freegametips.com/wp-content/uploads/2020/10/1601873723_PS5-the-DualSense-will-use-lights-to-indicate-which-player-1200x675.jpg)

(I checked on a PS5.)

**Comment by George3011** [comment]
Hey, just want to preface by saying that I've been using this application for years and I love it.

Is there a way to disable this bright LED indicating controller number? I have the lightbar turned off as the light is very distracting, but now I have a permanently on bright white LED at all times. Can you please put in an option - or point me toward an existing option - to turn off this unnecessary LED indicator light?

Thank you

**Comment by Hamiltron636** [comment]
> 
> 
> Again a case of I can't win. People complain either way.

Came to report this issue. Realize now that I missed it in the changelog. It's intended, not an issue. Though I would prefer to disable it, I'm so appreciative of the work that you've done, @Ryochan7 , that I would not dare complain about decisions you've made regarding a program you've released absolutely free of charge.

Keep up the great work.

**Comment by mika-n** [comment]
There is already a code change proposal to add "Enable Player LED" profile option. Ryochan7 probably takes a look at it at some point and reviews if the change/feature is approved.
https://github.com/Ryochan7/DS4Windows/pull/1789

(i don't have DualSense gamepad, so I don't dare to review the change request because cannot test it live)

**Comment by mrclsu** [comment]
Yep, I thought it would make more sense as a device option. If you think it should be a per-profile option, I can take a look at implementing it as such.

**Comment by Nyn69** [comment]
> The correct behaviour is centre aligned:

Then that's strange because after the DS4W update I have the same white light but on the left corner.

**Comment by Ryusennin** [comment]
The correct behaviour _on a PlayStation 5_.

**Comment by Animus120** [comment]
So how are this feature are going to be implemented on the next update? Centered like the one on real PS5 hardware, or left-aligned like the one currently in place?

**Comment by Serfrost** [comment]
The correct lighting is shown in this comment. The current implementation is simply new and preliminary. Give it time.

https://github.com/Ryochan7/DS4Windows/issues/1785#issuecomment-764210275

**Comment by MicaelJarniac** [comment]
One idea I had, and that I think could be useful, was to, if using only one controller, using those player indicator LEDs to indicate battery charge instead.

We can currently use the colored lights to indicate battery charge, but that prevents us from using the colors for something else, and it can be hard to tell which color corresponds to which battery percentage.

Having the player LEDs indicating battery charge would free the colored lights to be used for something else, and would allow a more "precise" indication of battery charge, because we could then count how many player LEDs are lit, and tell roughly the percentage of the battery as a function of `lit LEDs / total LEDs`, similar to how old phones had a battery icon with discrete "bars" inside of it, and by checking how many "bars" were lit, one could tell the rough percentage of charge left.

I believe this would be pretty great, and it'd give the player LEDs a very nice utility for people that use a single controller.

**Comment by Serfrost** [comment]
The main issue with LEDs is constant battery drain for an aesthetic purpose (and they're a bit distracting, especially when asymmetrical).  However, using those LEDs to show the battery charge _while_ it's charging wouldn't be too bad, but it may still end up slowing how fast your controller charges.

I'm generally against wasted battery usage, especially with rechargable controllers.  It's worse that a DualSense is not going to be easy to replace a battery with, if even feasible on your own--lack of easy disassembly, which I wish manufacturers would stop.

**Comment by nagup** [comment]
It's still easy to disassemble the controller, LED's are very low power, you have nothing to be worried about. If anything you should worry about charging itself, trying not to go above 80%, do yourself a favour and read up on why that is.

I have a crude solution to removing the player LED on my profile but I introduced the mute button LED to light up when the controller is using a USB connection, this was for me to know if the controller is connected via USB or BT. If you decide to try mine and you still find that its a problem, let me know and I can make another release with no LED's at all under any circumstance. Note that my fork is the exact same as the regular DS4 but I just removed two lines of code.
