### ISSUE TITLE
DS4 2.2.2 

### ISSUE THREAD

**Issue by HGunner7** [Ryochan7/DS4Windows#1786]
i just updated my DS4 to 2.2.2 and now the touchbar is not working i tried fixing it by using the xbox 360 layout it worked but my right stick stopped working in games. and vice versa please please please help!!!

**Comment by isaakfawkes** [comment]
If you read in the notes,"Only output DS4 touchpad button click when in Passthru mode".

**Comment by casey** [comment]
Is this an intentional change? It would be nice to be able to map the touchpad button click while in controls mode, which doesn't seem to be currently possible.

**Comment by ceedveed** [comment]
I ended up downgrading to 2.2.1 due to the touchpad clicking only working in passthru mode.

I use DS4Windows with a PC connected to the TV in the living room. The touchpad working as a mouse allows me to start my games using the DS4 controller. As soon as the game stops, I turn off the mouse function with the Touchpad Toggle option (PS button + touchpad tap). This no longer works with 2.2.2 because a single profile only allows touchpad as mouse OR touchpad click in game, not both.

I think a way around this would be to create two profiles, identical with the only difference in the Touchpad output mode. You can use a Special Action to quickly switch between the two profiles.

For now, I will stick to 2.2.1.

**Comment by TheMasterDingo** [comment]
still it was better as it worked on 2.2.1, maybe put a toggle in the settings, i used it like that

**Comment by MakiseKurisu** [comment]
I second this. I like how in the old version I can have both mouse control AND working in game touchpad click.

**Comment by Ryochan7** [comment]
Output Passthru Touch click is now an option.
