### ISSUE TITLE
Possible Bug: Trackball Friction calculations

### ISSUE THREAD

**Issue by midget35** [Ryochan7/DS4Windows#1794]
I've been doing some preliminary work to send trackball + friction data from the DS4 trackpad to commandeer the output of left or right analog sticks.

(This is useful as it would allow each gamepad to act as a distinct trackball for multi-player MAME games). 

A nice side effect of doing this is I can see the rel-time effect of friction in the Analog stick UIs of the Profiles > Controller Readings.

This leads me to what I think is a pretty apparent bug in the way the running friction and velocity is calculated (every 4 millisconds or so).

Basically: we see a lot of outliers when we print out the x and y calulations during many passes through the friction + velocity calulation code in the method:

DS4Windows.Mouse.touchUnchanged()

... after digging around, I worked out that the outliers (unusually high or low x or y calculations) emerge when the DS4State.elapsedTime value is significantly different from the average Input Delay value.

So: DS4Windows tells me the average input delay is about 4ms (which is amazing, by the way). And this comes out as an average of about 0.004d each time the DS4State.elapsedTime is read and utilised in said method.

The problems (outliers) emerge when elapsed time is 3 or 4 times higher (or lower) than average: I can see the newly calculated x and y coordinates jump all over the place through the Analog Controller Readings UIs. The friction and velocity is far from smooth. 

THE SOLUTION:

If we use the AVERAGE input delay time in place of DS4State.elapsedTime we get a significantly smoother curve. So my propsed solution is to use the avergae global input delay variable (is there one?) instead of the elapsed time between each DS4State instance.
 
NOTES:

On Mouse behaviour:
I am not certain why we don't see these x and y spikes when the friction is applied to the Mouse, but I suspect the SendInput() method of user32.dll goes on to do its own smoothing operations on the x and y values passed from DS4Windows. That is to say: I think the calculation errors are still very much there, but masked ahead of low-level mouse position updates.

On Friction calculations elsewhere: 
Along with touchUnchanged(), the calculation code in touchesEnded() and some other methods in Mouse.cs would likely benefit from this proposed solution (using average global input delay), and so increase the accuracy of trackball friction physics even further.

**Comment by Ryochan7** [comment]
It really seems like the issue comes from the initial velocity calculation. Although it is technically correct, the poll rate used for a device can really skew the end speed of the touchpad even when travelling the same distance on the touchpad. Trackball mode with the DualSense connected via BT has always been too fast but I gave up trying to change the behavior. Also, using a lower poll rate results in behavior that is similar to setting a higher friction level.

While testing things out, the only way I found to make the final trackball speeds more uniform in behavior was to use a static base line poll rate for the initial touchpad move events (used 4 ms). Trackball decay and the current mouse displacement would then take the current device poll rate into account. Not sure if I would push that type of change to production but it felt fine during testing.
