### ISSUE TITLE
Color Pulse Algorithm Modify

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#18]
I would like to ask that the algorithm for the lightbar color pulsing to be modified to coincide with the speed of the original lightbar pulse speed (orange charging light when ds4 is plugged without ds4windows). As it stands now, the pulse speed is too fast and the off light has lesser time than the on light. Each should be equal time. Not that big of a deal but I'm a perfectionist : P

This is for the [Pulse At] option.

**Comment by Ryochan7** [comment]
It looks like that part of the code works based on number of gamepad polls instead of using a set time duration. Each direction of the pulse will take 100 polls to make a full transition; that behavior could be a big problem for people using a BT connection. This method will have to be changed to be time dependent instead.

**Comment by Ryochan7** [comment]
Regular pulse mode and pulse while charging works using set time intervals now. Regular pulse mode uses a 2 second interval per direction and pulse charging mode uses a 4 second interval per direction.

**Comment by shinra358** [comment]
Excellent. Thanks!
