### ISSUE TITLE
Superfluous try-catch block

### ISSUE THREAD

**Issue by Phrohdoh** [Ryochan7/DS4Windows#180]
https://github.com/Ryochan7/DS4Windows/blob/jay/DS4Windows/HidLibrary/HidDevice.cs?utf8=%E2%9C%93#L462-L465

The catch body just rethrows the just-caught exception.

**Comment by Ryochan7** [comment]
I have only made minimal changes to HidLibrary. Although the throw makes the try block a bit pointless, I don't think that changing this is necessary. At some point, I need to get around to attempting to grab a newer version of the HidLibrary and incorporate it into DS4Windows. Some changes will need to be made anyway because the way IO is being handled in DS4Windows deviates slightly from the standard behavior provided by HidLibrary.

**Comment by Ryochan7** [comment]
I tried adding the latest HidLibrary code to DS4Windows. It took a while to get it working but some other problems came up in the process; the GUI became less responsive and the controller readings section became extremely laggy for some reason. Input performance ended up being slightly worse anyway and I don't like the extra work being done for overlapped IO (a lot of extra array creations). A lot of editing of the HidLibrary code needed to be done in order to add some necessary routines not included in the vanilla code. Also, read and write performance was extremely slow by default thanks to IsConnected being checked constantly.

For now, the old version of HidLibrary will continue to be used. The try-catch block has been removed.
