### ISSUE TITLE
Ds4 windows sees v2 pad as v1

### ISSUE THREAD

**Issue by bartekjot** [Ryochan7/DS4Windows#1801]
I have 4 pads, 3 of them identify correctly as v2 and the newest one falsely as v1. When connected via Bluetooth light bar colours don't work, neither does rumble. 

While using wired connection pad works as expected despite being marked as v.1

Found Controller: B4:3E:9B:21:63:D4 (BT) (DS4 v.1)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: [e.g. Windows 10 home] 
 - ds4 v 2.2.2

**Comment by mika-n** [comment]
The pad reporting itself as DS4 v1 is probably a fake copy. Many of those copy-cats report itself as DS4 v1 and while those may work just fine over USB there are often weird issues over BT (lightbar, touchpad, rumble don't work or connection is very unstable etc). Those fake copies often has square LS/RS movement instead of circle as in the original DS4 (this can be seen in ControllerReadings tab page or in gamepad HTML test web app).

So, this is not an issue in DS4Windows app itself but HW issue.

**Comment by bartekjot** [comment]
Hi mika, thanks for getting back to me so quick. Pad seems genuine however pairing it with android shows very vague lsrs stick movements as you suggested.

Perfect knock off. Will report and return ASAP.
