### ISSUE TITLE
Possible to create DS5 firmware updater for PC?

### ISSUE THREAD

**Issue by Shiftside** [Ryochan7/DS4Windows#1810]
I know this may be out of the scope for DS4Windows, but I'm assuming several people here may own a DS5 without a PS5. I noticed Sony provides PS5 system updates as downloadable files. Is it possible to create a DS5 firmware updater using those files instead of relying on a PS5 to do it?

**Comment by mika-n** [comment]
Something like this probably never make its way into DS4Windows app itself, because once someone figures out and reverse engineers the DS5 firmware logic there is most certainly an external app doing it. And it is probably good enough and no need to be inside DS4Windows app.

As far I know DS5 firmware updater is not yet reverse engineered.
https://github.com/SKFU/ps5tools

For now you have to connect DS5 to a PS5 console over usb cable to update the DS5 firmware. Or maybe Sony updates "Playstation Now/Playstation RemotePlay" apps in PC with ds5 firmware updater. Who knows....

**Comment by Ryochan7** [comment]
From what I know, no one has cracked the firmware update process yet. I wouldn't be the one to do it for sure.

I don't plan on ever implementing some form of firmware update functionality in DS4Windows if someone can make the process work on PC. It would probably be better suited as a dedicated app.
