### ISSUE TITLE
HELP Nacon Pro Revolution v1

### ISSUE THREAD

**Issue by RevengeHisoka** [Ryochan7/DS4Windows#1813]
Hello, I still can't connect my nacon pro evolution controller v1, can you help me please, my pc recognizes the controller, Nacon Sofware application too but on DS4Windows it can't find it.

**Comment by mika-n** [comment]
Please provide the minimum required information as explained in the pinned post: https://github.com/Ryochan7/DS4Windows/issues/1196

- WinOS version
- DS4Windows application version
- The latest logfile (open %APPDATA%\DS4Windows\Logs folder and rename the latest logfile as .TXT file and drag-n-drop the txt file here into a comment field)

And you may want to run the debug version and provide the debug logfile versions:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by RevengeHisoka** [comment]
I am under Windows 10 (8:22 pm), I do not understand how the debugging version of the DS4Windows application works, I am in version 2.2.2 and I cannot find the logs folder in appdata and Ds4Windows

cordially thank you for your help

**Comment by mika-n** [comment]
Just download the debug zip file from the linked web address and unzip it into the same folder where you have the existing DS4Windows 2.x version. Then instead of running DS4Windows.exe you should run DS4WindowsDebug.exe app.

Another way to find the logfile is to open the Logs tabpage in DS4Windows application and there is Export-button to export it as a text file.

**Comment by RevengeHisoka** [comment]
Yes , no worries, I will try this now, thank you for taking time for me, best regards

**Comment by RevengeHisoka** [comment]
When I try to put the Debug, it shows me that ViGEmBus Drive is not installed and I cannot put it
