### ISSUE TITLE
DS4Windows doesn't recognize parallel controllers

### ISSUE THREAD

**Issue by tgobira** [Ryochan7/DS4Windows#1814]
I'm trying to connect a parallel PS4 controller (a Pictek PC263 model). That's the log presented by DS4.

![image](https://user-images.githubusercontent.com/23407525/106145594-81565d00-6154-11eb-920b-129b2e047627.png)

And that's how the controller are being presented as connected.

![image](https://user-images.githubusercontent.com/23407525/106145657-9206d300-6154-11eb-991f-d124a9ccce7e.png)

But when I'm connecting a original controller, that doesn't happen and DS4 recognize the controller.

PS.: on Jays2Kings the parallel controller connects with no problem, but some features aren't included as Ryochan's DS4.

Anyone had the same problem with parallel controllers?

**Comment by mika-n** [comment]
"Parallel controller"? Now I must admit I don't know what it means.

**Comment by tgobira** [comment]
> "Parallel controller"? Now I must admit I don't know what it means.

I mean a control that isn't an original PlayStation Dual Shock 4.

The parallel controller -> Pictek PC263.

![image](https://user-images.githubusercontent.com/23407525/106194121-2ee56280-618d-11eb-80c9-0c1ec1d2675a.png)

**Comment by tgobira** [comment]
Here it goes.

2 last log files generated with Debbug executable.

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/5890093/ds4windows_log.txt)
[ds4windows_log_20210128.0.txt](https://github.com/Ryochan7/DS4Windows/files/5890094/ds4windows_log_20210128.0.txt)

**Comment by mika-n** [comment]
```
2021-01-28 18:15:18.8626|INFO|DEBUG: performDs4Input. ERROR. USB ReadWithFilestream failed. ErrorCode=ReadError
2021-01-28 18:15:18.8626|INFO|DEBUG: performDs4Input. ERROR. USB ReadWithFilestream failed. WinError=1167
```

These error msgs are the problem here. For some reason DS4Windows app fails to read button/stick/tuochpad/etc data from the  gamepad and this is why it disconnects the pad. What you could try
- Try different usb cables and usb ports (usb2 vs usb3 vs front vs back ports)
- Try bluetooth connection also (now you are testing USB). Well, usually usb works more reliably than BT.
- If you don't run DS4Windows app then does the gamepad work in WindowsOS without disconnection issues? You can test this via JOY.CPL controlPanel applet (run JOY.CPL command)
- DS4WindowsDebug.exe.config file has various TRUE/FALSE options to tweak how the gamepad is used. Try toggling those options and see if those make any difference (restart ds4windows app each time you modify this file).

**Comment by tgobira** [comment]
Nice...

1- I've tried all the ports on my PC (back and front ports) and still had the same problem.
2- Don't have bluetooth PC Connector. So I can't teste this at the moment.
3- Without DS4Windows app the controller works fine (image below).
![image](https://user-images.githubusercontent.com/23407525/106286633-9ef2f780-6224-11eb-9058-280891d3ef0d.png)

Maybe this 3rd party controller has some different configuration that DS4 still doesn't recognize.

=/

**Comment by mika-n** [comment]
Have you tried to tweak various DS4WindowsDebug.exe.config config file options? Try disabling touchpad/calibration/gyro/battery/etc options there and see if it works after disabling some DS4 feature.

Anyway, the gamepad configuration screenshot you posted is not fully 100% DS4 compatible picture because one button is missing (touchpad click btn) and where are trigger axis?

Almost like the gamepad you have there is registered as xinput device and not as dinput device in PC. Some 3rd party compatible gamepads does that. DS4Windows app doesn't support xinput devices, because it has never been an intention of the app and true DS4 gamepads should be dinput devices in PC. Anyway, try to see if you can force the gamepad to work as dinput device in PC. Some 3rd party pads have a driver option or some even work as native DS4 dinput devices when a vendor specific xinput device driver is uninstalled.

**Comment by tgobira** [comment]
Sry for the wrong pic... Windows recognize the controller as **dinuput device** (print with triggers and touchpad click).

![image](https://user-images.githubusercontent.com/23407525/106366465-d2b04900-631a-11eb-965f-89f05dcd5255.png)

With Jays2Kings DS4 App, the controller work's fine. The App recognize all controller button functions, even gyro, but it doesn't have any implementation for using de gyro.

**Comment by Darthagnon** [comment]
I and my brother both own PicTek HD-060/PC263 controllers. We had gyro drift with one (solved with gyro calibration feature recently added). We also found that this model of 3rd party controller works perfectly wirelessly. However,

**It does not work wired** (which is what your very first screenshot looks like, @tgobira) - it will connect and disconnect rapidly, because this controller has some weird proprietary thing going on so that it "works with Windows out of the box" (which means weird shenanigans with it presenting as an Xbox remote when wired to a PC) - DS4Windows doesn't like that.

### Workaround:
Use wirelessly; it is tested as working perfectly with 2 of this exact model of controller my end.

If you want to read what we did, tgobira:
https://github.com/Ryochan7/DS4Windows/issues/1727
