### ISSUE TITLE
help me!

### ISSUE THREAD

**Issue by Ray4218** [Ryochan7/DS4Windows#1816]
Problem 1 : Every 1 hour or so, the ds4 was losing connection for a 1~2 sec. and it's connected right away.
Problem 2 : 'hide ds4' doesn't work every time I turn on the ds4, but 'hide ds4' is working normally for first few hours I turned ds4 on.
please help me :( what should I do?
*I'm using the latest version.

**Comment by mika-n** [comment]
Please read the pinned "Read this before posting a new issue ticket" post and provide the information explained there and go through the troubleshooting document linked there. 

And what about if every single post would be titled as "help me"? Not very informative is it? If you have different kind of problems then open different tickets because it is difficult to keep track of things if the same ticket is used to discuss all sort of things.

About the HideDS4Windows option. Please read the ReadThisBeforePosting ticket and follow a link explaining what is the HideDS4Windows option and why you need to tweak your PC in a certain way to let DS4Windows to use that feature,

**Comment by mika-n** [comment]
closed because of inactivity. And links mentioned in "Read this before posting a new issue ticket" post explains the thing with HideDS4Windows (=exclusive mode).
