### ISSUE TITLE
[Suggestion] Audio Output on DualSense

### ISSUE THREAD

**Issue by paradise999** [Ryochan7/DS4Windows#1820]
I didn't find about this nothing in internet, so I decided write about it here. I connected DualSense in new port in Pc, Windows start installing it like new device. Its change default Audio Output. I start changing windows audio settings and try to check output in Dualsense speaker AND IT WORKS. I know that headphones inserted in dualsense work, like in ds4, but speakers didn't work. BUT, very big but. Windows see Dualsense speakers as Quadro audio system and dualsense play audio from "Behind speakers". What do I mean by all this? It can be use, fot example, to output characters speech  or something else what you want, if you find how to use it.

**Comment by Ryochan7** [comment]
The "Behind speakers" are probably the audio haptics. Some people use Voiceemeter to passthru the default audio stream to the audio haptics of the DualSense to sort of fake rumble. I guess you can pump up the bass on the passthru version and it supposedly feels good to some people. I would rather use the Rumble emulation provided by the hardware.

At least when it comes to a USB connection, it might be possible to utilize the built-in speaker rather than use the headphone jack to output audio. Based on the docs, it should just be a matter of writing an output report with the proper flag set. I don't see a real need for it unless you just want to pump music through the speaker. Doubt the audio quality would be that good though.

**Comment by paradise999** [comment]
I check and yes, it's haptics. I need to admit: For haptics, not bad sound. You are right, rather use Rumble emulation

**Comment by ArStah** [comment]
Hey, @Ryochan7, it would be great, if it was possible to turn the sound from headphones to speakers. I would use it for speaking with my friends while playing, like it's done on PlayStation 5(at least in BF5, didn't check other): when you play with someone and don't use headphones - the sound from game goes to the TV and the voices of people you playing with - to the controller speaker. Can i request this feature?) Thanks in advance! It's great what you are doing!

**Comment by Ryochan7** [comment]
> The application DualSenseX can do this (use the controllers speaker, also it supports audio haptic feedback)

It does not. You do not know what you are talking about or you are just outright trolling.

The most DSX can do is use NAudio to expose the audio interface to Windows and pump Windows audio so you can feel the bass in an audio track; also, it only works with a USB connection. That is not true haptic feedback and it is even worse than the emulated rumble that the controller provides natively. DS4Windows allows the use of Voicemeeter for that purpose if you want to do it. From what I have seen, nobody has decoded how to actually use the audio interface properly.

Besides, DSX cannot even handle the simplest case of mapping Cross to Xbox A without massive lag. Been waiting for the app to give me more value than a soda pop and it still has not happened. Needs me to finish his homework I guess.
