### ISSUE TITLE
left stick drifts 

### ISSUE THREAD

**Issue by AliNej2323** [Ryochan7/DS4Windows#1822]
i use the newest version, and my left stick lags and drifts all the time. sometimes it doesnt even let me go left or right and i can even see it on the "controller readings" tab . this problem is only by left stick and the RS works fine.  its hard to say its because of my controller considering  i bought it 2 weeks ago. i use the controller with wire. 

**Desktop (please complete the following information):**
 - Controller Make and Model:sk p415 Wireless ps4 controller
 - OS:  Windows 10 Pro Build 2004
 - DS4Windows Version [2.2.2]

**Comment by mika-n** [comment]
See if deadZone setting can solve the issue.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#deadzone

However, if the drift and required deadZone is "too big" then the gamepad may be dead-on-arrival. For sure all LS/RS sticks have slight variation and small drift because of hardware implementation (springs wear out, dust, small differences even between gamepads with the same brand and model number). DS4Windows app cannot solve the hardware level issue, but by tweaking deadzone value you can minimize the effect. Usually a deadzone <0.10 should be enough, but if you need bigger deadzone to "stabilize" the stick then you may have broken stick in the gamepad.

**Comment by mika-n** [comment]
closed as inactive
