### ISSUE TITLE
How to do something like: UP="R" L1+UP="T" (not "RT") L2+UP="U" (not "RU")

### ISSUE THREAD

**Issue by Nerque** [Ryochan7/DS4Windows#183]
I'm trying to use special actions, but I do not know why, when I press L1 + UP, the controller sends "RT", however ... I'm waiting for an "R" alone. Why does this happen?

**Comment by arkhillneo** [comment]
Try this steps:
1.In controller profile setting window, Select UP.
2.Set regular to "R".
![2018-01-18_182750](https://user-images.githubusercontent.com/35409070/35093524-943b471c-fc7d-11e7-9f24-318e89b48b94.jpg)
3.Select "Shift Modifier", and then first, select "L1" under list box.
4.While still in "Shift Modifier" , Select key "T".
![2018-01-18_182757](https://user-images.githubusercontent.com/35409070/35093528-95de8692-fc7d-11e7-9d39-028bd1c5caec.jpg)
Close windows and Save profile and try again.

**Comment by arkhillneo** [comment]
But if you want to do a whole game pad button shift setting, I would suggest to use JoyToKey. It is a better way to manage the multi-shift-key configuration settings.

Unless you need to use rumble feature or base on the game is impossible to disable joystick. Since to use JoyToKey you need to disable in-game joystick/controller support function, or they will have conflict.

**Comment by Ryochan7** [comment]
DS4Windows does not have any kind of Action Set functionality so the kind of mapping situation that you described is probably not possible. The main focus of development has been just making a better direct mapping to an XInput controller. You might have to look into other software projects in order to get the mapping functionality that you would want. JoyToKey, Xpadder, and Steam are alternatives that can be used that can provide that kind of mapping in one way or another.
