### ISSUE TITLE
Trigger option for "Gyro - Controls" is gone

### ISSUE THREAD

**Issue by keem85** [Ryochan7/DS4Windows#1843]
I can't find the trigger option for "Controls" under "Gyro" anymore. It's only there with "Mouse" and "MouseJoystick", but not "Controls". Any reason it has been removed?

**Comment by Ryochan7** [comment]
What? A Triggers option has never existed in DS4Windows for Controls mode. Tilt Controls always operated on **Always On** implicitly. I have never had a reason to add the option to that Gyro mode.

**Comment by keem85** [comment]
Huh, really? I could have sworn I used it on the Resident Evil games half a year ago, because mouse wouldn't work properly on that game. Maybe I remember the exact setup wrongly.. I do remember I had a trigger option, and that I chose the control sticks instead of mouse. Can't remember how I got it to work, then.

**Comment by Ryochan7** [comment]
Not sure how that would have happened. I guess gyro trigger options can be added to that gyro mode if desired. I just have never had a use for it so that functionality has never been added in.

**Comment by keem85** [comment]
I think it would be a good addition to games that cannot use gamepad and mouse interchangably. Some games can't aim with the mouse at the same time as strafing with the other thumbstick.

**Comment by Ryochan7** [comment]
Didn't tag this issue but the functionality has been committed. Also found a major oversight with Gyro Controls mode in the process. Gyro Controls buttons could get unintentionally fired even while using a different Gyro mode. I don't think I use Gyro Controls mode in any of my profiles so I was fortunately avoiding the issue due to those output controls being unassigned.
