### ISSUE TITLE
Xbox controller support?

### ISSUE THREAD

**Issue by pedrovay2003** [Ryochan7/DS4Windows#1847]
I know this seems redundant, but I would love Xbox controller support in DS4Windows (since we're seeing so many different controllers supported now, which is wonderful). My Series X controller has joystick drift out of the box, and it would be great to have something that runs outside of Steam that I can use to modify the deadzones of the sticks.

**Comment by Ryochan7** [comment]
Long story short: it will never happen. The big problem is not reading the input Xbox 360 controller but hiding the original Xbox 360 controller from a game. Steam handles controller blocking using X360CE style DLL overrides when it launches a game. There is going to be no attempt to find a way to perform DLL injection on apps running on the system that aren't launched from DS4Windows itself.

**Comment by mika-n** [comment]
XInputPlus is alternative tool to do all sort of axis/button remaps with Xinput devices. I don't use it regularly, so don't know how good/bad it is but I know some people use it to tweak the output curve of xbox LS/RS sticks.
https://sites.google.com/site/0dd14lab/xinput-plus/aboutxinput
https://www.google.fi/search?q=xinputplus+screenshots&sxsrf=ALeKk037Ra5HjB3LaJcRBy7wgJKTddIIpQ:1612693169110&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjLtuebxtfuAhVM_SoKHWR2DE4Q_AUoAXoECA4QAw&biw=1536&bih=762

However, xInputPlus uses DLL injection technique so it has pros and cons of that technique. Some games don't like DLL injections (anti-cheat protection?)

**Comment by C3S4RM3W** [comment]
> Long story short: it will never happen. The big problem is not reading the input Xbox 360 controller but hiding the original Xbox 360 controller from a game. Steam handles controller hiding using X360CE style DLL overrides when it launches a game. There is going to be no attempt to find a way to perform DLL injection on apps running on the system that aren't launched from DS4Windows itself.

What if you just make it work for the xbox one / series controllers? They use a different identifier and driver, so you can take those as input, hide those HIDs, and then output them as the x360 that vigem uses.

**Comment by mika-n** [comment]
> What if you just make it work for the xbox one / series controllers? They use a different identifier and driver, so you can take those as input, hide those HIDs, and then output them as the x360 that vigem uses.

Technically it would be easy to read xbox (any xinput) gamepads, run those events through a DS4Windows profile translations and then feed the output into virtual dualshock4 or xbox360 gamepad created by ViGem driver.

But then there is still the issue of hiding the physical gamepad to avoid "double input" issues in games. 
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

HidGuardian struggles to hide xinput type of devices. Here is an explanation from the man himself who created the HidGuardian and ViGen driver (Nefarious). 
https://forums.vigem.org/topic/343/block-disable-xinput-devices-hidguardian/4

If this hiding part would be easy then it would have been done years ago (without using DLL injections like many xinput solutions do it at the moment). Nefarious has created a new version of HidGuardian and it works a bit differently than the current HidG version but the new version is not yet officially out. Hopefully it solves this issue (=hopefully because no one knows until the new version is released).

**Comment by pedrovay2003** [comment]
So, that Xinput Plus program is really nice. That's exactly the kind of thing I'm looking for, but on a system-wide scale (Xinput Plus is a per-program thing, which works, but it's cumbersome, to say the least). It's too bad the controllers work so differently that DS4Windows won't be able to handle them. I really wish Microsoft would use higher-quality parts.
