### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by PAPIKO8** [Ryochan7/DS4Windows#1856]
**Describe the bug**
Hi, I have a very weird problem with my controller. It connects seemlessly with bluetooth and with cable. It has been working like a charm using DS4 windows on my WIN10 PC. Two days ago I connected my controller started the game but buttons were not working. I tried reconnecting, restarting the game even pc  but nothing worked. So I went into edit profile in ds4 windows and usually it worked like this: I pressed button  and it showed on screen which button I pressed. Now it doesnt work at all no buttons work only x y sticks work. I opened XINPUT from tools folder in ds4windows to see if my controller isnt broken and as you can see in screenshot i pressed bunch of buttons and it works (also tried to connect to my phone it all works) 

The only problem is that it doesnt work in ds4 windows and in games in pc 

Can you please help me (it worked for like month now it suddenly stopped working and I even reinstalled my windows to see if it helps but nothing works)

**To Reproduce**

**Expected behavior**
To work like charm 

**Screenshots**
![xinput](https://user-images.githubusercontent.com/78857237/107512246-d6f42600-6ba6-11eb-9ca4-0f9446d03c3d.png)

**Comment by mika-n** [comment]
Log file? Rename the latest file in %APPDATA%\DS4Windows\Logs folder as .TXT file and drag-n-drop the text file here in the comment box.
Profile you use? Zip and attach the profile here as a zip file.
What do you see in "Controller Readings" tab page in DS4Windows app? Sticks and gyro and triggers working?
What do you see in JOY.CPL gamepad configuration screen? Run joy.cpl command.
What do you see in https://gamepad-tester.com/ web page?

**Comment by Angelblack35** [comment]
У меня тоже эта проблема!

**Comment by PAPIKO8** [comment]
I actually fixed it, because I had to reinstall windows again anyway. Now sometimes happens that I connect my controller to pc(both usb or bluetooth) and it doesnt show up on ds4 so I have to delete controller from "devices and printers" in control panel and connect it again and it works (there is a video about it on youtube too)

sorry for bothering but I fixed 


thanks anyway

**Comment by Angelblack35** [comment]
Сылку можно на видео

**Comment by PAPIKO8** [comment]
https://www.youtube.com/watch?v=ycM-dRk1moQ

**Comment by mika-n** [comment]
> Сылку можно на видео

???? 

In English (or in Finnish) maybe?

**Comment by PAPIKO8** [comment]
> > Сылку можно на видео
> 
> ????
> 
> In English (or in Finnish) maybe?

Im not sure if I understand you correctly, but the video I sent you is in English

**Comment by mika-n** [comment]
> > > Сылку можно на видео
> > ????
> > In English (or in Finnish) maybe?
> Im not sure if I understand you correctly, but the video I sent you is in English

I meant that can you please post the question in English or in Finnish (well, in English i'm sure more people could help you) because I could not understand those comments you made (was it in Russia or some other language using cyrillic alphabets).
And take a look at the pinned "Read this before posting a new issue ticket" because your post is missing all required information (version of WinOS? ds4windows app version? Vigem driver version? ds4windows logfile? profile file you use? controller type?)

**Comment by PAPIKO8** [comment]
> > > > Сылку можно на видео
> > > > ????
> > > > In English (or in Finnish) maybe?
> > > > Im not sure if I understand you correctly, but the video I sent you is in English
> 
> I meant that can you please post the question in English or in Finnish (well, in English i'm sure more people could help you) because I could not understand those comments you made (was it in Russia or some other language using cyrillic alphabets).
> And take a look at the pinned "Read this before posting a new issue ticket" because your post is missing all required information (version of WinOS? ds4windows app version? Vigem driver version? ds4windows logfile? profile file you use? controller type?)

Im sorry I didnt realize it wasnt the same person commenting but it was you "my bad" and yes it was in Russian, even though im nit from russia I can read the alphabet so I was reacting to his comments (first one said that he has the same problem and in the second comment he asked for the link of the video that helped me with my problem) 

therefore as you can see my answers to his comments

**Comment by Angelblack35** [comment]
Windows 10, DS4WINDOWS 2.2.6, DUALSHOCK 4, dual Sense. I cannot provide any other information I am not at home now. the problem is that the gamepad is displayed by Ds4windows but no buttons work and the touchpad does not work either

**Comment by mika-n** [comment]
@PAPIKO8 Right :-)  my bad I got confused about those comments and got mixed up who commented what.

@Angelblack35 Please dig out the latest logfile from %APPDATA%\DS4Windows\logs folder or export the logfile from Logs tab page of DS4Windows. If you have the same problem with DS4 and DS5 gamepads then do separate tests with these gamepads (ie. connect only one gamepad at a time and close and re-start DS4Windows app when testing those). It will be much easier to interpret logfiles when there is less irrelevant log entries and different logfiles per gamepad.  You can attach logfiles here in the comment field when you rename the xxx.log file as xxx.txt file and drag-and-drop it here.

You could even try the debug version because it generates a lot more detailed logfile.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by Ryochan7** [comment]
Going to assume this was a ViGEm issue rather than an actual mapping issue. I ran into a couple of similar problems while fixing the ViGEm library. The notification callback issue in x86 mode made the output Xbox 360 controller not work sometimes if not just have DS4Windows crash.
