### ISSUE TITLE
Profile Got Reset

### ISSUE THREAD

**Issue by Chrisnetika** [Ryochan7/DS4Windows#1877]
Right now i'm pretty pissed off so my report is not gonna be perfect to standards.
I was using my dualsense controller on bluetooth but my battery was low.I plugged in the wire to charge it and it didn't switch over (to be fair as of lately that has not worked either) .So to get it working I usually have to unplug the thing because usually I have to turn controller off before I plug it for it to switch to usb mode but unplugging it after works so I did that as usual then plugged it back in.Usually at this point everything works the gamepad in usb mode charging while I play.. the birds sing the bees bug and the world is wonderful but this time that was not so.I was trying play my game and the directional(left stick) was working but the buttons not so much.So I tried shut ds4windows programs, unplug the controller.. start back up ds4windows then plug it in, same issue.Upon further inspection to my utter fking surprise the profile got reset.The name I put it was fine but when I edit it all my settings for it.. back to default.To make matters worse I thought I had it all backed up in another folder but turns out I didn't because I must've deleted it trying fix latency issue(another ticket).This all was happening during a match in my game and I had to shut it off so I get a penalty zzz.Yea not a good night.
Wanna know what prompted the program to reset my profile to defaults?
version 2.2.1
windows 10x54

**Comment by Chrisnetika** [comment]
Also to note with DS$ controller I never had this issue, 1st time trying to transition a dualsense from bluetooth to usb

**Comment by mika-n** [comment]
Logfiles? Difficult to say what could cause something like that, but in theory if a profile reading fails then ds4windows continue to use default settings. If the profile is saved at this point then it could cause something like this. But, this is just a speculation (Didn't look at too detailed the code if this would be possible edge case scenario).

I have several mobile phone usb cables where DS4 data connection doesn't work, but charging does work. I use those cables to change the pad from the same PC hosting DS4Windows and this way the pad continues to use BT connection even while charged.

But, the hotplug-connection swap is a slight issue if the gamepad is recognized with a different MAC address in BT and USB mode. Then there is no way for DS4Windows app to know that the hotplugged controller is actually still the same device. Logfile should tell if the MAC changes between usb and bt connections.

And just in case you should update the 2.2.1 version to the latest version because there has been some hotplug fixes.

**Comment by Chrisnetika** [comment]
[ds4windows_log_20210216.0.txt](https://github.com/Ryochan7/DS4Windows/files/5999254/ds4windows_log_20210216.0.txt)
[ds4windows_log_20210216.1.txt](https://github.com/Ryochan7/DS4Windows/files/5999255/ds4windows_log_20210216.1.txt)
[ds4windows_log_20210216.2.txt](https://github.com/Ryochan7/DS4Windows/files/5999256/ds4windows_log_20210216.2.txt)

**Comment by Ryochan7** [comment]
I am just going to blame the .NET Runtime at this point unless someone isolates the problem and proves the code is at fault. It works much better on my system.

Terry A. Davis performs "Write in C"
https://www.youtube.com/watch?v=hwFblDrxsQk

> Wanna know what prompted the program to reset my profile to defaults?
> version 2.2.1

That problem hasn't existed since version 2.2.3 from commit 6c5cd50eca1bf981ab82030e7628fd7fa2f74ac5

**Comment by Chrisnetika** [comment]
Upgraded to 2.2.7 about a few days ago,I can say it is stable so far.I tried recreate the issue and have not been able to do so.Guess I can close this one.
