### ISSUE TITLE
[BUG] touchpad commands no longer work

### ISSUE THREAD

**Issue by Ghostlyboo** [Ryochan7/DS4Windows#190]
since the last update, touchpad swipes commands no longer work [(this window)](https://imgur.com/tq9nitB), i used to have swipe up and down assigned to volume control, but that no longer works, but if i choose "use as a mouse" it works as it normally would.
going back to version 1.4.107 fixed it, im currently on Version 1.4.108
theres also that the text is white which makes it really hard to read, this is an old issue though.

**Comment by Ryochan7** [comment]
Thank you for bringing up this issue. An optimization that I made messed up the swipe routine because the same object was being compared to itself. Now the first touch is being properly tracked again so swipe controls and 2 finger swiping to change profiles work. I also changed the foreground color of the labels used to display the current binding for a swipe control so that it will display again. I never changed those labels when I edited the form to work better for high contrast mode.

Commit that caused the problem: https://github.com/Ryochan7/DS4Windows/commit/09e5d20bb0dd82d5add55673e85b4134a09681ae
