### ISSUE TITLE
Virtual Dualshock 4 not working after accidentaly install HIDGuardian

### ISSUE THREAD

**Issue by pinospin** [Ryochan7/DS4Windows#1902]
After I install BetterJoy, I accidentaly click on HIDGuardian installation
I think HIDGuardian disable both physical and virtual DS4 controller
After that I uninstall HIDGuardian (not delete button, I click on uninstall button), the gamepad still not output the button data
![image](https://user-images.githubusercontent.com/71922495/108951808-41bf5a00-769b-11eb-842b-306fe5fb9009.png)

 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro
 - DS4Windows 2.2.7

**Comment by mika-n** [comment]
Logfiles? 
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by Ryusennin** [comment]
![](https://i.imgflip.com/4zab66.jpg)

**Comment by Ryochan7** [comment]
Never tried to install HidGuardian via the BetterJoy utils. Don't know what rules they have set up but I don't understand why it would be set up to block DS4 devices at all. If it does then very likely the DS4 v.1 would be affected which means a virtual DS4 created by ViGEmBus would be blocked as well. It has been an inherit problem with HidGuardian as it has no way to distinguish physical controllers from virtual controllers created with ViGEmBus.

I guess I will have to test the BetterJoy utils later and see how it sets up HidGuardian.

**Comment by Ryochan7** [comment]
Glad I looked at the batch scripts first. I will refuse to attempt to install HidGuardian from the BetterJoy script as it would install HidCerberus as well. It looks like no rules are set up on install. However, it looks like the Program.cs file attempts to add devices input devices as they are detected by the program.

That approach does not work by design as HidGuardian only takes affect on new device connections. Trying to add an entry to the Affected Devices list upon detecting a controller is too late and other programs will still pick up the controller anyway. It would be fine for the second time connecting the controller as HidCerberus would probably just ignore the add Hardware ID request or just return an error code that BetterJoy might display a message for before continuing.

It looks like HidCerberus is only called for supported controllers though. There should be no blocking of DS4 controllers happening in BetterJoy.

**Comment by pinospin** [comment]
> ![](https://camo.githubusercontent.com/a505dc31520fe0fcd9f813f3f95da64b1349673182e5c5e7ebc53971e86d25b7/68747470733a2f2f692e696d67666c69702e636f6d2f347a616236362e6a7067)
> 
> https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide

I did

**Comment by pinospin** [comment]
> Glad I looked at the batch scripts first. I refuse to attempt to install HidGuardian from the BetterJoy script as it would install HidCerberus as well. It looks like no rules are set up on install. However, it looks like the Program.cs file attempts to add input devices as they are detected by the program.
> 
> That approach does not work by design as HidGuardian only takes affect on new device connections. Trying to add an entry to the Affected Devices list upon detecting a controller is too late and other programs will still pick up the controller anyway. It would be fine for the second time connecting the controller as HidCerberus would probably just ignore the add Hardware ID request or just return an error code that BetterJoy might display a message for before continuing.
> 
> It looks like HidCerberus is only called for supported controllers though. There should be no blocking of DS4 controllers happening in BetterJoy.

So basically it isn't HIDGuardian's fault?
Since I use DS4Windows and never turn on hide ds4 or install HIDGuardian

**Comment by Ryochan7** [comment]
> One more interesting thing I found about DS4Windows is that if I connect the controller without DS4Windws running then it work like charm. But when I launch DS4Windows both physical and virtual gamepad freeze the button, they no longer output the buttons although both appear in Control Panel

Assuming you are using a BT connection. That's how the hardware works on Windows. The DirectInput interface goes dead once the mode switch changes for accessing the extra features of the controller (Touchpad, Gyro, Rumble, etc.). The same behavior happens when using Steam Input or InputMapper. The only way to get that interface working again is to disconnect and reconnect the controller.

**Comment by Ryochan7** [comment]
Looking at the screenshot you posted before. It looks like the virtual DS4 is working fine. The original DirectInput interface for the DS4 is not registering input. That is to be expected.

**Comment by pinospin** [comment]
Oddly enough, I managed to uninstall ViGemBus driver (I'm nt even reinstall yet, it's like 2 driver at once running)
And somehow it worked
I think the problem lies on the ViGemBus driver that came with BetterJoy

**Comment by pinospin** [comment]
> Looking at the screenshot you posted before. It looks like the virtual DS4 is working fine. The original DirectInput interface for the DS4 is not registering input. That is to be expected.

The one I holding the buttons is the physical one
Both do output vibration data

**Comment by Ryochan7** [comment]
BetterJoy includes an installer for ViGEmBus 1.16.112.0 since there has been no stable release of BetterJoy since ViGEmBus 1.17.333.0 was released. Not sure about whether both versions would be in the Driver Store but I would think that only one version of the driver would be loaded by Windows.

**Comment by nefarius** [comment]
> BetterJoy includes an installer for ViGEmBus 1.16.112.0 since there has been no stable release of BetterJoy since ViGEmBus 1.17.333.0 was released. Not sure about whether both versions would be in the Driver Store but I would think that only one version of the driver would be loaded by Windows.

Windows will prefer the higher version number, unless the user manually forced an older version and even that approach isn't rock solid since Windows (Update) can trigger a "search for better suited drivers" on certain events the user might not be aware of.
