### ISSUE TITLE
Dualsense "Full click" output trigger threshold too low

### ISSUE THREAD

**Issue by Corgano** [Ryochan7/DS4Windows#1909]
The trigger threshold for the output of "full pull button" trigger mode on a dualsense controller is too low. It works perfectly fine with a new ps4 controller, but I recently got a used controller that has more give in the right trigger than the left. This means the bump on the left trigger happens after you feel the bump, but on the right trigger it happens slightly before you feel the bump, resulting in early / false button presses. The trigger threshold for the "full click" button really should be adjustable

Running the latest ds4windows release on this repo, windows 10 64 bit

Edit: Tried downgrading to 2.2.6 to fix another issue, and the sensitivity is the same. The button seems to trigger at 98-100% of the trigger pull, so changing the button threshold is unlikely to change this. If we could instead set the force feedback "button" position that would help compensate for worn triggers.

**Comment by Ryochan7** [comment]
The issue is the fact that the DualSense triggers register full 255 output at probably a bit over half trigger pull (definitely feels like less than 75%). That is an inherent hardware issue that other people have reported as well. The current threshold is set up to try to allow the most range for the soft pull before encountering resistance for the full pull. It is not an adjustable value which would technically be a problem if someone changes the max zone of the trigger. The option is meant to be more device agnostic so it would be best to avoid making some device specific options for that setting.

I don't know how to go about tackling this.

**Comment by Corgano** [comment]
I'm in the boat of making it used configurable. The current seeing is same
in most contexts and is fine as a default. If someone messed it up, they
could reset the values to default to get sane values.

**Comment by emilois** [comment]
If the issue where DualSense registers 255 at 75% pull can't be fixed since it's a hardware issue, how about adjusting Full Click trigger effect instead? Something like making the Full Click soft stop take effect at 60% pull or make it user adjustable.
