### ISSUE TITLE
Language pack question

### ISSUE THREAD

**Issue by arkhillneo** [Ryochan7/DS4Windows#191]
Hi
Does DS4Windows support language pack? If so, can anyone help to point out what should I do?
I saw the Lang folder and I tried several steps and searching google but no success.

I also have tried old project version of Jays2Kings's but still no success.

The only document I can find is here:
http://ds4windows.com/lang.html
But as you can see(I try to use ja language):
https://i.imgur.com/YugcolD.jpg
It sill in English:
https://i.imgur.com/sH45zvy.jpg

I saw the Language switcher thread but I can not find any language UI box on latest version of DS4Windows.
https://github.com/Ryochan7/DS4Windows/issues/169
https://i.imgur.com/lhRJN9a.jpg

I am using 1.4.108 x64 on Windows 10 1709.

Thanks for reading my question.

**Comment by Ryochan7** [comment]
The program should work with the currently set system locale although I will admit that it has never been tested. The only way that localization has been tested is by explicitly setting the locale in code. DS4Windows is able to load a language assembly and use it for localizing the application when the locale is set explicitly.

The Lang folder is a secondary search path for language assemblies so having a language assembly folder installed in the main application directory should take priority over any assembly installed in the Lang folder. Also, any old language pack from Jays2King's DS4Windows will likely not work.

The language switcher pull request has been ignored a bit. I have been a bit busy working on other portions of the program. I need to get back to checking out the language switcher pull request.

**Comment by arkhillneo** [comment]
Hi
Thanks for reply.
So it should work with language assembly follow the locale system set. But it just not work on my case.

I use the language pack form latest release of ds4windows here.

I have tested ds4windows on Traditional Chinese and Japanese locale system, and ds4windows still runs in English on both system.(I tried it on clean Win10 in VM too, no success.)

Move the language folder to main directly of ds4windows also does not work(for example fr-FR) on my case. Tried to Runs as Administrator , it sill use English UI. For now I have no idea what to do.

The language switcher feature is a good idea, hope one day it can be come true.

**Comment by Ryochan7** [comment]
Tested this out and I missed a step. Switching locales worked fine in the main build output folder but not in the main releases. It turns out that I missed bundling a necessary file in older releases. The DS4Windows.exe.config file is needed for secondary language folder searching to work properly. Without that file, localization folders have to be located in the same folder as DS4Windows.exe; the ja example that you showed should have worked. Now, switching from Enlgish to Japanese or German (locales tested) works properly with the main release. I will have to make sure to bundle the DS4Windows.exe.config file in future releases. You can grab a copy of the most recent file from the following link.

https://drive.google.com/open?id=1VRRlfUKwK_mt8mdEf7UvDwCC4JB1CFCH

**Comment by arkhillneo** [comment]
Thanks, it is working!!

![2018-01-15_103405](https://user-images.githubusercontent.com/35409070/34924696-dea954ec-f9df-11e7-9aa1-afeb94021f98.jpg)
