### ISSUE TITLE
Dualshock 4 messes with wifi while using Bluetooth

### ISSUE THREAD

**Issue by Vandal101** [Ryochan7/DS4Windows#1919]
While using the controller with Bluetooth, the internet on my computer "stops" it doesn't even disconnect from the wifi it just stops receiving data, when I turn off the controller the data comes back as nothing has happened, I tried switching all wifi channels the problem persists
other devices seem unaffected by the controller being on.

**Steps to reproduce the behavior:**
1. Connect controller using Bluetooth 
2. Open any web page
3. Page doesn't load
4. Disconnect controller
5. Page loads

**Expected behavior**
The internet should load fine

**Desktop**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Home Build 1909
 - Bluetooth Driver: Qualcomm Atheros Bluetooth 4.0
 - Wifi Driver: Qualcomm Atheros AR956x Wireless Network Adapter
 - DS4Windows Version 2.2.8

**Comment by mika-n** [comment]
Hmmm.. Are you saying that this is a problem in DS4Windows application? That it causes BT interference with your WIFI? If there were such a problem in the app then I'm sure this site would be full of bug reports complaining how the app breaks WIFI.

The issue must be in your PC, BT chipset or BT/WIFI drivers. The BT may work there just fine with other BT devices which send a lot less data over BT (ie. you don't notice the problem), but the gamepad sends and receives hundreds of BT packets in a second so the problem in your rig may be more severe. But, there is nothing DS4Windows app can do about the BT and WIFI in your rig.

**Comment by Vandal101** [comment]
First, one thing I had forgotten to tell, sorry, before using DS4Windows I was using Steam Input and I had no issue like this only after I had started using DS4W that these issues started showing up

I have seen several other reports from users with similar issues and one of the similarities I found was that if Wifi shares hardware with Bluetooth interference could occur, lowering the polling rate to the lowest value helps a bit but not that much, and even why does it occur with DS4W and not Steam Input?

Reports:
https://github.com/Jays2Kings/DS4Windows/issues/223
https://www.reddit.com/r/DS4Windows/comments/g7yjyd/ds4_windows_broke_my_internet_somehow/
https://github.com/Jays2Kings/DS4Windows/issues/336
https://github.com/Ryochan7/DS4Windows/issues/820
https://github.com/Ryochan7/DS4Windows/issues/35

**Comment by mika-n** [comment]
DS4Windows app is not only reading data from the gamepad, but also writes data to the gamepad (two-way BT highway). And does this all in high frequency to avoid gamepad lag. Some other apps may just read data from the gamepad or using the gamepad in so called "PC-friendly mode" in BT instead of in native DS4 mode. By default DS4 gamepad is in PC-friendly mode when connected over BT (certain DS4 special features missing in this mode). For example Win10 doesn't know how to switch the gamepad over to native DS4 mode in BT, so even when normal ds4 buttons work in Win10 over BT then those special ds4 gamepad specific things don't work. However, DS4Windows app knows how to switch the gamepad into native DS4 mode even in BT mode and this causes the gamepad to send a lot more data to PC. And the gamepad is ready to receive data from PC.

This "PC-friendly mode" vs "native DS4 mode" in BT may have something to do with the fact that the gamepad and WIFI seem to work in other apps. Or those apps use slower update frequency. Who knows....

Anyway, the fact is that DS4Windows app itself has nothing to do how your BT chipset and WIFI chipset physically communicate. Those device drivers and HW takes care of that and if there are issues then those are beyond the control of DS4Windows app.

Try to set the WIFI (in the wifi router) to use different wifi channel and see if it helps.

Or if you have BT dongle then try to use usb extension cable to move the BT dongle further away from the radio storm caused by your PC chassis (and takes the BT dongle closer to the gamepad but further away from the WIFI card).

Or try different BT dongle.

**Comment by Ryochan7** [comment]
DS4Windows (since at least Jays2Kings DS4Windows 1.4.52) has always been greedy when it comes to data throughput with the DS4. This fork is less so and people have complained about it; a lot of ree-ing about not making the Max BT poll rate the profile default. It seems that Steam Input is more conservative when it comes to the poll rate and I can feel the difference big time. Even Jays2Kings DS4Windows was faster than Steam Input and that is why I used it before I forked the project.

Apart from that, this issue could honestly boil down to the use of .NET versus a native compiled app written in C++. The .NET Runtime is inherently bloated (less so than the Java JVM), has a lot of extra security checks enforced on running code, and it has a massive system load to begin with. I have done pretty much all that I can do trim the load and it works out better on my system.

Recent experiments have shown that .NET 5 is much better when it comes to system load than the currently targeted .NET Framework 4.8. It will be a while before .NET 5 will be used in a public release of DS4Windows. I had thought about making the move at the end of the year but I am considering doing it much earlier than that; the .NET 5 build will likely be the primary build I use going forward.

In the end, nobody should be using a combined WiFi + BT adapter to begin with. Using cheap hardware is not going to give you good results.
