### ISSUE TITLE
Got the latest update and now my DualShock4 has no vibration on MW

### ISSUE THREAD

**Issue by Aarxnn** [Ryochan7/DS4Windows#1935]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [e.g. Windows 10 Pro Build 2004]
 - DS4Windows Version [e.g. 2.1.5]

**Additional context**

**Comment by mika-n** [comment]
Yes, this is intentional in the latest release. Some games suffer an unfortunate "motors stuck on rumbling state" issue. This is why rumbling is now temporarly disabled if the virtual ViGem output mode is DS4 instead of xbox360 mode.

If you want to use the rumble in DS4 output mode then for now you could use the beta/debug version of DS4Windows app because there ds4 rumbling is still enabled. Download the linked zip file and extract it into the existing DS4Windows app folder (where you have the latest official release) and run DS4WindowsDebug.exe app instead of DS4Windows.exe app. 
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by TheMasterDingo** [comment]
> Yes, this is intentional in the latest release. Some games suffer an unfortunate "motors stuck on rumbling state" issue. This is why rumbling is now temporarly disabled if the virtual ViGem output mode is DS4 instead of xbox360 mode.
> 
> If you want to use the rumble in DS4 output mode then for now you could use the beta/debug version of DS4Windows app because there ds4 rumbling is still enabled. Download the linked zip file and extract it into the existing DS4Windows app folder (where you have the latest official release) and run DS4WindowsDebug.exe app instead of DS4Windows.exe app.
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems
> 
> And the latest official DS4Windows app version is behind this link. Make sure you have the latest official release:
> https://github.com/Ryochan7/DS4Windows/releases

Will it be re-enabled in future updates?

**Comment by Aarxnn** [comment]
I hope it does. I stopped playing because I feel so off without the rumble lol

**Comment by Ryochan7** [comment]
Did a rage quit due to a different issue posted here. Virtual DS4 feedback has been re-enabled in the code. Not sure when a new release will come out.

**Comment by Ryochan7** [comment]
Version 2.2.11 is now out

https://github.com/Ryochan7/DS4Windows/releases/tag/v2.2.11
