### ISSUE TITLE
Blue Screen of Death when connecting dualsense controller by Bluetooth

### ISSUE THREAD

**Issue by Pl4t0nVl4dp** [Ryochan7/DS4Windows#1940]
Blue screen of death when connectin dualsense controller by bluetooth. Only on 2.2.10 version i have this problem, all the others works well !

**Comment by mika-n** [comment]
Please fix this post and follow the instructions explained in "Please read this first before posting a new issue ticket" post. 
And please fix the subject line because what do you think would happen if everyone posts tickets with such a great title as "please fix it".
And third, please fix the latest version of .NET and ViGem libraries and drivers on your PC.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

**Comment by Syko7956** [comment]
Okay, I was wondering if I was the only one getting a blue screen of death! Thank god, I thought something fishy was happening outside DS4Windows

**Comment by Pl4t0nVl4dp** [comment]
> Please fix this post and follow the instructions explained in "Please read this first before posting a new issue ticket" post.
> And please fix the subject line because what do you think would happen if everyone posts tickets with such a great title as "please fix it".
> And third, please fix the latest version of .NET and ViGem libraries and drivers on your PC.
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list



> Please fix this post and follow the instructions explained in "Please read this first before posting a new issue ticket" post.
> And please fix the subject line because what do you think would happen if everyone posts tickets with such a great title as "please fix it".
> And third, please fix the latest version of .NET and ViGem libraries and drivers on your PC.
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

Thanks ! And I am sorry, i am new to github

**Comment by Pl4t0nVl4dp** [comment]
> Please fix this post and follow the instructions explained in "Please read this first before posting a new issue ticket" post.
> And please fix the subject line because what do you think would happen if everyone posts tickets with such a great title as "please fix it".
> And third, please fix the latest version of .NET and ViGem libraries and drivers on your PC.
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

Thanks ! And i am sorry, i am new to github.

**Comment by Ryunam** [comment]
I'm experiencing the same sudden appearance of a BSOD whenever connecting the Dualsense to Bluetooth using the latest release of DS4Windows (2.2.10). This is on Windows 10 x64, version 2004 with latest updates. 

USB connection does not cause any issue as far as I could see. With Bluetooth I can reproduce this consistently by simply pairing the Dualsense and then launching DS4Windows. The error message in the BSOD mentions IRQL NOT LESS OR EQUAL and an apparent conflict with steamxbox.sys, which leads me to believe it's interfering with Steam's own X-input drivers, but the issue shows up even without launching Steam at all.

**Comment by Pl4t0nVl4dp** [comment]
> I'm experiencing the same sudden appearance of a BSOD whenever connecting the Dualsense to Bluetooth using the latest release of DS4Windows (2.2.10). This is on Windows 10 x64, version 2004 with latest updates.
> 
> USB connection does not cause any issue as far as I could see. With Bluetooth I can reproduce this consistently by simply pairing the Dualsense and then launching DS4Windows. The error message in the BSOD mentions IRQL NOT LESS OR EQUAL and an apparent conflict with **steamxbox.sys**, which leads me to believe it's interfering with Steam's own X-input drivers, but the issue shows up even without launching Steam at all.

**Comment by Pl4t0nVl4dp** [comment]
> I'm experiencing the same sudden appearance of a BSOD whenever connecting the Dualsense to Bluetooth using the latest release of DS4Windows (2.2.10). This is on Windows 10 x64, version 2004 with latest updates.
> 
> USB connection does not cause any issue as far as I could see. With Bluetooth I can reproduce this consistently by simply pairing the Dualsense and then launching DS4Windows. The error message in the BSOD mentions IRQL NOT LESS OR EQUAL and an apparent conflict with **steamxbox.sys**, which leads me to believe it's interfering with Steam's own X-input drivers, but the issue shows up even without launching Steam at all.

Same problem as me. But can i fix this or i should just use an older version until a new one is released ?

**Comment by Masamune3210** [comment]
Steam's enhanced xinput driver is pure trash and causes this exact issue, even when steam isn't open as the driver is loaded at boot. the solution is to go into steams controller menu in big picture mode and turn off enhanced xinput

**Comment by Pl4t0nVl4dp** [comment]
> Steam's enhanced xinput driver is pure trash and causes this exact issue, even when steam isn't open as the driver is loaded at boot. the solution is to go into steams controller menu in big picture mode and turn off enhanced xinput

Do you mean that i should disable xbox extended feature support ?

**Comment by mika-n** [comment]
DS4Windows app cannot cause BSOD on Windows10 because the application runs in user mode (user mode apps don't have permissions to do anything which could crash the OS). Only hardware or apps running in kernel mode can cause BSOD on Windows10 and those apps are in 99% cases device drivers or Windows system libraries. DS4Windows uses services of ViGem driver to do the actual virtual gamepad communication, so maybe Steam conflicts with this?

**Comment by Masamune3210** [comment]
> > Steam's enhanced xinput driver is pure trash and causes this exact issue, even when steam isn't open as the driver is loaded at boot. the solution is to go into steams controller menu in big picture mode and turn off enhanced xinput
> 
> Do you mean that i should disable xbox extended feature support ?

Yes, it should tell you to reboot afterwards, do so and then you should be good

I'm 99% sure thats the case, something about steam's driver does NOT agree at all with ViGem and causes a blue screen when both are installed and ViGem is used for anything

**Comment by Pl4t0nVl4dp** [comment]
> > > Steam's enhanced xinput driver is pure trash and causes this exact issue, even when steam isn't open as the driver is loaded at boot. the solution is to go into steams controller menu in big picture mode and turn off enhanced xinput
> > 
> > 
> > Do you mean that i should disable xbox extended feature support ?
> 
> Yes, it should tell you to reboot afterwards, do so and then you should be good
> 
> I'm 99% sure thats the case, something about steam's driver does NOT agree at all with ViGem and causes a blue screen when both are installed and ViGem is used for anything

Ok i disable it, and i restarted. Now everything work fine! THANKS A LOT !

**Comment by Ryochan7** [comment]
From README:

> In order to use DS4Windows properly, you have to open Steam Big Picture Mode, navigate to Settings > Controller> Controller Settings and uncheck **Xbox Configuration Support** along with **PlayStation Configuration Support**.

https://github.com/Ryochan7/DS4Windows#disable-steam-controller-mapping-support

Can't inspect what the source of the problem is but I am betting the problem is more with Valve and its XInput extended driver rather than ViGEmBus. Either way, having both installed at the same time would likely cause conflicts when dealing with virtual or physical XInput controllers.

**Comment by Ryunam** [comment]
Can this be re-opened please? On my system, even after disabling all those options from Steam Big Picture Mode, connecting a Dualsense controller through Bluetooth and then running DS4Windows immediately triggers a BSOD.

Interestingly enough, in the info section of the BSOD there is now no mention of steamxbox.sys whatsoever. The error simply reports a "**WDF_VIOLATION**" message.

I understand it might have to do with a conflict that is outside of what DS4Windows itself is doing and is more related to how Steam handles things, but since it does not happen with USB and it keeps happening here even after deactivating all the controller support options I would appreciate some more guidance.

**Comment by Ryochan7** [comment]
> Can this be re-opened please? On my system, even after disabling all those options from Steam Big Picture Mode, connecting a Dualsense controller through Bluetooth and then running DS4Windows immediately triggers a BSOD.

Instructions in Steam BPM clearly state you need to reboot your PC after installing or uninstalling their XInput Extended driver. Your message doesn't seem to indicate that you rebooted so I am going to assume that caused the problem.

**Comment by Ryunam** [comment]
@Ryochan7, thank you for looking into this first of all. Unfortunately your assumption is not correct in this case: I did reboot my system multiple times after disabling the Steam controller support options and I am still experiencing the same exact issue. 

Just to be safe and sure that I was actually following the instructions properly, I redid all the steps from scratch as indicated in this thread:

1) I went into Steam Big Picture Mode and disabled:
- Xbox Configuration Support
- Xbox Extended Support
- Playstation Configuration Support

2) I rebooted my PC, then went into the Bluetooth settings, put my Dualsense in Pairing mode and paired the controller to Windows.

3) After making sure that the controller was properly paired, I launched DS4Windows. A UAC confirmation prompt came up and, right after clicking on OK, the whole system triggered a BSOD.

This time, there was yet another message in the BSOD itself, citing a KERNEL_MODE_HEAP_CORRUPTION error.

**Comment by Ryunam** [comment]
No, I believe it's very unlikely for it to be a bad Windows install or a failing RAM. 

I have literally never got a BSOD in any other circumstance, not even once, with my setup. The very first BSOD I've got in years is with this specific configuration and software - and mind you, only and specifically with DS4Windows after pairing the Dualsense controller through Bluetooth. USB works fine. The Dualsense with the Steam driver also works perfectly fine, all my other controllers work perfectly fine and I've never had an issue whatsoever. You will concede that the likelihood of it being due to a hardware anomaly on my end is particularly low.

A conflicting driver is more in line with what has been explained in this very thread. But then again, if it's just the Steam Extended Xbox support that is triggering the BSOD:

1) Why does the Dualsense work fine if you keep the Xbox Extended Support option active on Steam and connect the controller through USB?
2) Why doesn't disabling that specific option fix it for me even after a reboot?

See also here, a few people on Reddit have also reported getting BSOD errors with the latest updates of DS4Windows:

https://www.reddit.com/r/DS4Windows/comments/lzuc1d/bsod_with_ds4windows/
https://www.reddit.com/r/DS4Windows/comments/kv357u/bsod_when_using_ds4/
https://www.reddit.com/r/DS4Windows/comments/k0010e/dualsense_5_controller_bsod_and_freezing_up/

**Comment by Ryochan7** [comment]
No matter what, since this is most likely a driver issue, there is nothing that I can inherently do. I don't have a means to push any type of driver changes so I am stuck with what is already published; it has been a item of frustration in many issues posted here. DualSense BT support works for me just fine so that is all I have to work off of at this point. Although I don't want to and it goes against my own advice in my docs, I will attempt to use the Steam XInput Enhanced driver and see if I run into similar BSOD problems on my system.

**Comment by Ryochan7** [comment]
Funny enough, I didn't run into a problem when the Steam XInput Enhanced driver was installed and using DS4Windows 2.2.10. Got nothing to work with here.

**Comment by mika-n** [comment]
I didn't see you mentioned the version of ViGem device driver you have there? 
Please go through the link list and install just-in-case the latest version of .Net framwork, VisualC++ runtime and most of all ViGem device driver packs.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

**Comment by Ryochan7** [comment]
Just tried the same scenario with ViGEmBus 1.16.112.0 and still did not run into the problem. This issue is going to go nowhere so ending it here.
