### ISSUE TITLE
bypassing DS4 Output curve in order to use  MW in-game Dynamic Response Curve

### ISSUE THREAD

**Issue by rodisport** [Ryochan7/DS4Windows#1944]
**Describe the bug**
I cant Use my in-game response curve.  I just downloaded the latest version. 
all the settings feel very weird, from linear to quad and so forth.
is there a way to bypass the output curve? I don't want the game to use ds4 curves

thanks for your help

**Comment by Ryochan7** [comment]
Likely want to reset Dead zone (0.00), Anti-Dead zone (0.00), and Max zone (1.00). The Gamepad defaults are set up with Xbox 360 controller emulation in mind.

**Comment by rodisport** [comment]
thank you I will try that. is there a difference between leaving output curve on custom with no points and linear?

**Comment by mika-n** [comment]
If you don't define a custom curve value then it is better to set it as "linear curve" option to make it clear that the curve is 1:1 linear. But technically an empty custom curve is the same as linear, but certainly not as obvious.

**Comment by rodisport** [comment]
right, I thought that may be the case. another thing I noticed is that when I set the emulator to DualShock 4, any ds4 settings such as dead zone, anti DZ,  rs sens etc, don't work in-game. It's like ds4 is not there, the only difference is that I can use my ps4 controller touch pad as a mouse. once I switch it back to xb 360 deadzone settings work.  I'm fine with it emulating Xbox, i just gotta figure out a good custom curve. the dynamic in-game one is like in the middle of ease-out quad  and ease-out cubic. they are both way too fast.  I'll test out some custom ones I suppose.
thank you for the responses. I appreciate this program very much

**Comment by mika-n** [comment]
Hmmm... are you sure the deadzone value doesn't work in DS4 output mode? Seems to work here. You can see how the deadzone works from the "Controller Readings" tab page in the profile editor. The red circle indicates the size of deadzone and I=input and O=output values below LS/RS/L1/R1 blocks show actual numerical input-output values.

**Comment by rodisport** [comment]
dead zone values don't register in MW when I have the output set to ds4, I can see it changing in the program but not in-game. Only when I switch it to Xbox, I can those changes. I also have to restart when I do that which is expected I think.  My preset is gamepad hopefully that is correct as well.

**Comment by mika-n** [comment]
Do you have both the physical original gamepad and the virtual DS4 gamepad (exposed by ViGem driver) visible for MW? In that case maybe MW is picking up data from the physical gamepad interface and it naturally doesn't have those DS4Windows tweaks.
So the classical "double input" issue?
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#double-input-problem-in-games-game-does-all-sort-of-weird-things-when-i-press-a-button-second-player-drops-in-cannot-navigate-in-menus-because-focus-moves-two-lines-when-i-press-a-key-just-once-etc
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

What do you see in JOY.CPL controlPanel applet when a ds4windows profile uses DS4 output mode? One or two "Wireless Controller"?
