### ISSUE TITLE
Bind PgDn = Next

### ISSUE THREAD

**Issue by ScarBrotherHelpMe** [Ryochan7/DS4Windows#1945]
Old bug, when u try to bind any button or comand to emulate Page Down u get "Next" instead
Page Up works fine

**Comment by Ryochan7** [comment]
Not really a bug but it is inconsistent. The binding is correct as it uses the proper Windows virtual key for Page Down. The label used for that key from the KeyInterop class ends up being Next as both Next and PageDown have the same value. Next appears first in the Enum so that label gets used rather than PageDown.

This isn't a big enough concern to warrant any changes. Don't want to duplicate the work done in that class just to change the associated names of keys.
