### ISSUE TITLE
Latency Spikes on both Wired and Wireless Connection. Please help.

### ISSUE THREAD

**Issue by PaydayPerry** [Ryochan7/DS4Windows#1961]
Controller: DS4.V2
[latency log.txt](https://github.com/Ryochan7/DS4Windows/files/6151876/latency.log.txt)
[debug log.txt](https://github.com/Ryochan7/DS4Windows/files/6151878/debug.log.txt)

As the titles says i get latency spikes, flashbar flashes quite a bit about it, checking the log reveals that yes, latency is over 10ms and it varies quite a bit but i remember it even saying 500ms sometime, point being that it locks out input, and remains stuck on the last action i did for about a second, similar to what happens when a controller runs out of battery. If i was for example tilting Right stick to look right, character starts spinning when the latency spikes happen, as you can imagine this is very frustrating and often leads to me getting killed in the game i play. Its very inconstitent when it happens, I can go hours without issues or it can happen 5 times in a minute, but it does seem to happen more often after awhile.

I will add that i dont seem to be getting the same problem if i dont use DS4Windows, but i really dont wanna stop using it because of all the profiles i have and the fact that not a whole lot of games support DS4 controllers natively

I have yet to find any helpful advice about the situtation anywhere and i havent found much in terms of people having similar problems, the ones i have found is about wireless only and it being a bluetooth issue of some sort.

I have tried using the debug version but the controller wont actually connect properly, I will include both the log file from when i was using it earlier and when i tried opening the debug version

**Comment by PaydayPerry** [comment]
Nevermind, it still happens even if i dont use DS4Windows

**Comment by mika-n** [comment]
faulty controller? can you borrow another gamepad to test that theory?

**Comment by PaydayPerry** [comment]
Okay, I do have an older DS4 Controller that i used previously so i will try with that, but i know that at the very least the wireless latency still happened with the old controller.

**Comment by PaydayPerry** [comment]
Okay, so i've tested with the old controller, sure enough the latency issues are still there on wireless, but wired is fine suprisingly.
Im not sure what's with the newer controller though. The newer controller with wired issues is about 3 months old and the older one is about 1 year old. The issues with wired only started happening recently while the wireless latency stuff started happening about 6 months ago. I dunno if it is actually something with the controller or my PC's settings when detecting the controller that is the problem.

Still wondering about why the debug version doesn't work either. Perhaps its something to do with programming language not matching up to my Swedish PC?

**Comment by mika-n** [comment]
Nej, I have a Finnish Win10 PC, so Swedish should be OK also because of the same charset and the same "weird" letters.
The debug logfile does detect the gamepad, but then it throws an error message "Sequence contains no matching element". This is weird especially when the exception doesn't tell any more clues at which point of the code it threw this error msg.

The debug version is the same code as the official one, but may contain some non-released new experiments. Maybe some of those things is now giving problems there in the debug build. But with this information it is very difficult to say which code point throws that error msg.

If you have a USB BT dongle then try attaching the BT dongle at the end of usb extension cable and this way taking the BT dongle further away from the radio storm caused by the PC chassis and closer to the gamepad.

**Comment by PaydayPerry** [comment]
The BT is built in to the PC so i unfortunately can't use this to help. Is there any other older debug versions that i can try, to see if they will work?
