### ISSUE TITLE
Detecting 2 controllers

### ISSUE THREAD

**Issue by MeHigh1101** [Ryochan7/DS4Windows#1965]
I'm using dualsense via bt and ds4w is detecting 2 wireless controllers...Some games work and some don't...In game controllers panel one controller is responding to input and the other one isn't...btw i have one controller..any help pls?

**Comment by mika-n** [comment]
Double input problem? Please read the toubleshooting guide.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#double-input-problem-in-games-game-does-all-sort-of-weird-things-when-i-press-a-button-second-player-drops-in-cannot-navigate-in-menus-because-focus-moves-two-lines-when-i-press-a-key-just-once-etc

**Comment by Atyne** [comment]
If you connect the controller via bt and wire at the same time, you will see wireless controller 2 times (unless you use a cable that transfers only power and not data). If you use ds4 emulation, then bt will freeze in the control panel. If you want to hide wireless controllers and see only emulated x360 controller, then use the guide above.

Guide transcript: Hide DS4 in the settings, if it doesn't work turn of whatever may interfere - most common is Nvidia shadowplay (open geforce experience>settings>disable in-game overlay). After the physical controller is hidden you can enable it back.

If you can't make it work you can alternatively install hidguardian and then you can hide/unhide it through hidninja in ds4 settings - select wireless controller in hid devices>check which address is in affected list>remove it>reconnect the controller - you have to do it for both wireless and wired if you use both (because of different hid address), also remember which address it was if you'll want to hide it again).
