### ISSUE TITLE
DS4Windows freezes sometimes when connecting a controller

### ISSUE THREAD

**Issue by Geroyuni** [Ryochan7/DS4Windows#1966]
I've been occasionally getting freezes from connecting my original DS4 v2. This does not always happen, but when it does, I must forcibly close DS4Windows from the task manager and start it again to take it back to normal, as the tray bar icon does not do much. This time I decided to check the log and I noticed there is a thrown exception from ViGEm in it.

Log: [ds4windows_log_20210316.2.txt](https://github.com/Ryochan7/DS4Windows/files/6152224/ds4windows_log_20210316.2.txt)

**Comment by mika-n** [comment]
you have veeeeery old ViGem version. Please update it because Nefearious has released newer version of it some time ago.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

DS4Windows auto-updater updates only DS4Windows app itself, but not ViGem device driver because installing automatically a new kernel model device driver without letting user to know about it might be a bit too dangerous.

**Comment by Geroyuni** [comment]
I thought I had the latest, but seems Parsec's installer reverted it to the old one. Welp, I'll check if I get it on latest, for now I'll close this
