### ISSUE TITLE
Improve Rainbow's power consumption

### ISSUE THREAD

**Issue by MakiseKurisu** [Ryochan7/DS4Windows#1967]
I was having issue with high idle power and audible fan noise (due to the extra power consumption) on my laptop. After investigating one major factor was due to I have AlwaysRainbow turned on. When I have everything closed but DS4Windows, turning AlwaysRainbow on resulted an increase of average CPU power consumption from 4W to 15W, enough to get the fan spinning. When I have my normal everything up, the same change results a jump from 35W to 40W. This is due to the implementation of Rainbow effect being a constant poll, which prevents CPU from entering low power state.

I think the current Rainbow implementation is done in DS4LightBar.updateLightBar(), which is called by ControlService.On_Report(). That means we are calling this method up to 1000 times a second. I don't believe this is necessary.

Ideally I think the lightbar code should be refactored so it is detached from the input loop. I'm not exactly sure about how lightbar works in DS4 but lightbar class should just provide a few methods to set the lightbar state from outside, and then the lightbar class itself maintains that state, either through a timer, or a looping thread. This way DS4Windows only needs to update the lightbar state when necessary, reducing the waste on CPU cycles, and also this make the code more maintainable.

**Comment by MakiseKurisu** [comment]
I understand that this is a low priority issue so here I add a warning on this feature if we don't want to work on this anytime soon:
https://github.com/MakiseKurisu/DS4Windows/tree/AddRainbowWarning

**Comment by Ryochan7** [comment]
That might be a consequence of how many output reports are sent to the controller especially when using a BT connection. Up until about version 2.1(?), DS4Windows was forced to use the Control endpoint to send data to a BT connected DS4. Using that method to send data forced a rate limiter of 8 ms. Since finding out how to take advantage of the Interrupt endpoint and using that method, now data can be placed in a buffer and sent as fast as the controller can receive it. That helps with more responsive rumble but it would cause a problem when output data is changing constantly.

Maybe a rate limiter needs to be in place for the Rainbow routine to hold a color for a brief period before changing to a new one. Other than that, you would be forced to use a slower BT poll rate to lower the number of possible changed output reports sent to the controller. I normally use the default of 4 ms.

**Comment by Ryochan7** [comment]
Never mind. Looks like there is already a 10 ms delay between each color change calculation for Rainbow mode
