### ISSUE TITLE
Request - 8Bitdo Adapter Support

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Ryochan7/DS4Windows#1970]
I have a 8bitdo but I notice that ds4 didn't seem to notice it. It is linked to a ps4 controller so I assumed it would see it. I need it to see the 8bitdo for the motion control support. If its possible could you implement it as soon as possible?

**Comment by P3rf3ctXZer0** [comment]
https://www.8bitdo.com/wireless-usb-adapter/

**Comment by Mircosfot** [comment]
i hope 8bitdo is only a name of this product because the dualsense read in 10bit

**Comment by P3rf3ctXZer0** [comment]
![DOyetFK 1](https://user-images.githubusercontent.com/10351221/111712271-4818a000-881b-11eb-8032-b2b3e4630c46.png)

**Comment by mika-n** [comment]
Try running the latest debug version and provide the logfile.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by P3rf3ctXZer0** [comment]
[Exported Debug.txt](https://github.com/Ryochan7/DS4Windows/files/6176550/Exported.Debug.txt)

**Comment by P3rf3ctXZer0** [comment]
Unplugged it and plugged it back in like 5 times :/

**Comment by mika-n** [comment]
The "problem" is this line. The device is seen by WinOS as xbox gamepad device (VID=0x045E  PID=0x028E). DS4Windows has never supported xinput devices because it was not the original intention of this app. The idea of DS4Windows was to do ds4 dinput -> xinput virtual conversion and now if the gamepad is already in xinput mode then no need to do xinput->xinput virtual conversion.
03/20/2021 18:12:35: DEBUG: EnumerateDS4. HID#5 Path=\\?\hid#vid_045e&pid_028e&ig_00#7&325c346&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant game controller  VID=0x045E  PID=0x028E  Usage=0x5  Version=0x0

But, it is true that DS4Windows has come a long way since the early days of Jay2Kings version. Now this app has a lot of fancy features (macros, remaps, autoprofiles etc) which might be useful with xinput gamepads also. There are other apps supporting xinput remapping and macros, so maybe you should look for those. As of now you cannot use DS4Windows app if the gamepad is seen as xinput (xbox) gamepad in Windows.

Maybe the USB dongle has some settings to expose the gamepad as DS4 dinput device instead of XBox xinput device?

**Comment by P3rf3ctXZer0** [comment]
All I really want is the ability to fix deadzones etc as well as motion controls support. I would just rather have it all through a single app.

**Comment by mika-n** [comment]
you have to see if the 8Bitdo has options to set it to expose gamepads as dinput devices instead of xinput devices. But for now there is no way to use xinput devices with DS4Windows app.
