### ISSUE TITLE
Curve (Input)? 

### ISSUE THREAD

**Issue by crunchycrouton** [Ryochan7/DS4Windows#1972]
Not sure if this is the right place to put this but I couldn't find anywhere else. I've looked all over the documentation and couldn't find an explanation for what Curve (Input) does. Just curious about what this setting does.

Thanks!

**Comment by Ryochan7** [comment]
It is a deprecated curve option that has been left in for backward compatibility with profiles made with Jays2Kings DS4Windows. The curve is applied before any dead zone calculations so that is why the Input qualifier is used there. I have always hated the option in both DS4Windows and in InputMapper as I find it extremely wonky no matter what value is used for that option.
