### ISSUE TITLE
Dualsense Lightbar Passthru 

### ISSUE THREAD

**Issue by PSerban93** [Ryochan7/DS4Windows#1975]
I want to know if there is an issue about lightbar passthru on Dualsense?
I tested an DS4 on Marvels Avangers and its work perfect but with Dualsense its just go black. 
Dualsense do not support the lightbar passthru or is an issue?
Thank you

**Comment by Ryochan7** [comment]
Making me regret adding the feature back already. Anyway, it works for me while playing The Witcher 3 with the DualSense.

**Comment by Ryochan7** [comment]
As stated in issue #1389, the error stems from workarounds due to incomplete data sent from ViGEmBus. Once I confirmed that the issue was with the ViGEmBus driver rather than DS4Windows, I wanted to avoid these type of issues constantly popping up and decided to remove the feature until a fix was added to ViGEmBus. I reluctantly added virtual DS4 feedback support back in after other issues posted here complaining that feedback support was gone. Now I am back on this type of issue getting posted constantly.

I can't win
