### ISSUE TITLE
Where to find non CSR bluetooth dongles?

### ISSUE THREAD

**Issue by Anofelah** [Ryochan7/DS4Windows#1989]
Not a bug, more a question.

On your GitHub page you mention as a reply to the question _What about CSR and Toshiba bluetooth adapters?_ > **"I can't say for certain about either, I've picked up a CSR adapater, and will attempt to make it work, but no guarantees."**

There seems to be an overabundance of specifically CSR adapters on the market, and I'm struggling to find one that isn't CSR. Am I missing something? In the UK I cannot find the one you recommend unfortunately.

Thanks

**Comment by TheMasterDingo** [comment]
I am and have used a CSR 4.0 of tp link, work very well, latency minimal and no disconnects at all.
Also you can check https://it.aliexpress.com/item/1005001273586697.html?spm=2114.13010708.0.0.75a54c4d9tZ2Tx which uses a realtek chip with bluetooth 5.1 ( it says 5.0 but lmp version suggests 5.1). I see no diference between the two and the csr is also more "flexible"because there are tools that allow you to clone/change its mac address as i did if you were to have multiple.

**Comment by Ryochan7** [comment]
A lot of the info on the website is very out of date. My version of the site is only slightly modified from the original; the biggest difference is the site uses Pelican SSG to generate the site files. Been thinking about changing the site but I cannot find a starting theme that I like.

I use a CSR based dongle as my primary BT dongle. I just use the built-in BT configuration tools in Windows 10 and connecting a DualSense to the dongle works fine. Past reports seem to indicate that using any custom tools included with CSR dongles are likely not going to work.

**Comment by Ryochan7** [comment]
Back to the tangent from the previous post, I updated the site. The FAQ section does not exist on the site anymore. Don't know if I will add it back later.
