### ISSUE TITLE
Bind SL, SR and Capture buttons for Joy Con

### ISSUE THREAD

**Issue by pinospin** [Ryochan7/DS4Windows#1998]
So the capture button behave just like home button when split, but i want it independent so i can make it behave like any button (e.g. Start button for the minus half)
Also I think it'd be nice to make SL/SR buttons bindable, so basically use them like shoulder buttons or paddle alternative

**Comment by Ryochan7** [comment]
I have opted to not worry about that as of yet. Mapping buttons beyond the extent of what is available on the DS4 or DualSense would create some big problems in the app; it should be easier now but there were quite a few issues just exposing the DualSense Mute button initially. Don't want the mapper to run through checks for non-existent buttons on each poll. Also, presenting options in the UI for those extra buttons is an issue. This would be nice but I have not thought of a way I would go about allowing those buttons to be mappable as of yet.

**Comment by pinospin** [comment]
How about let the user create the profile for specific type of input controller? (E.g: DS4 can use but not DS5). That way maybe could solve the UI problem.

**Comment by Ryochan7** [comment]
That is not doable due to the mapper restrictions especially with how Auto Profiles work. Especially with Auto Profiles, the profiles are loaded ahead of time so DS4Windows has no idea about what device will occupy an input slot. It is assumed that the input device will be a DS4.

Also, opening the Profile Editor from the Profiles tab pretty much has the same issue regarding not having any input device association. If I had my way, I would probably just remove that list as it causes more problems than its worth.

**Comment by Ryochan7** [comment]
Done in 3.0.11. Not sure how useful it will be.

**Comment by temoridao** [comment]
> Done in 3.0.11. Not sure how useful it will be.

Thank you for this! I think this is very useful functionality to be able to bind actions on the extra buttons on the joycon. 
But as far as I know, this is done for left joycon only? Is there any plans to add support of SR/SL for right joycon?
