### ISSUE TITLE
Slovenian translation

### ISSUE THREAD

**Issue by jernejs** [Ryochan7/DS4Windows#200]
The included Slovenian translation is awful (looks like it was automatically translated). I started my own translation here: https://github.com/jernejs/DS4Windows however in its current form it messes up the UI layout pretty badly, and I'm not sure how to fix this (but at least it's understandable, unlike the included translation).

**Comment by Ryochan7** [comment]
Unfortunately, editing translations in Windows Forms also entails having to edit locale specific versions of forms. I haven't bothered editing any forms for other locales other than English unless people have asked about it. There are a lot of outdated translations in the source code and that portion is not something that I can maintain by myself. My non-English language knowledge extends to a minor amount of Spanish that I can remember from high school and some elementary Japanese.

**Comment by jernejs** [comment]
OK, I think I fixed the form layouts (but I can't seem to be able to test the changes - can't get the language to load, it always uses English).

**Comment by arkhillneo** [comment]
Maybe there is a typo in the language menu?
![2018-01-27_090238](https://user-images.githubusercontent.com/35409070/35466707-47ba7cbc-0341-11e8-838b-f860c454c921.jpg)

Not for the language translation, but if only for the layout issue, I think you can just report it by uploading an image:
![2018-01-27_090022](https://user-images.githubusercontent.com/35409070/35466710-4c300c62-0341-11e8-9e82-7278ccfc0d67.jpg)

I have reported Chinese UI layout issue and it got fixed by Ryochan7.

**Comment by Ryochan7** [comment]
I checked out your fork. The updated Slovenian translation works fine on my machine when using your fork. The Options form layout is a bit off. Also, oddly, the new language pack combobox gets stretched a lot when the Slovenian language pack is being used. I have selected and loaded several other languages and only that translation causes a problem.

**Comment by jernejs** [comment]
Do I need to do anything special after compiling DS4Windows? I also noticed that the version I compile doesn't retain any settings (I tried compiling for Release/AnyCPU and Release/x64).

**Comment by arkhillneo** [comment]
@jernejs 
I only use Release/AnyCPU option to compile the project. I do not set any special setting.

After the compiler finished the job, I copy the file to the exist my DS4Windows folder(not the compiler folder) and follow the directory structure. So the language pack files have to move into "Lang" folder.

That's all and it works as normal.

**Comment by jernejs** [comment]
I tried this, too, but got the same results.

**Comment by Ryochan7** [comment]
I used Release/x86 for testing. Ever since the early stages of this fork, I avoid using the AnyCPU platform target. Some form editing in Designer mode can only be done using a 32 bit platform target so I usually switch the platform target to x86 while editing forms; the AdvancedColorDialog class is the reason that a 32 bit platform target has to be used while editing some forms. For most development, I use Release/x64.

Also, there is a post-build event that can be used to automate copying over language packs into the Lang folder. In the projects properties, under Build Events, just change the `GOTO END` line to `::GOTO END` and the routine will run. I use that only while bundling new releases.

**Comment by jernejs** [comment]
Looks like something is broken regarding AppData setting loading - the settings were saved fine, but not loaded; I temporarily removed them, and told DS4Windows to use .exe directory, so I can now test my changes.

**Comment by Ryochan7** [comment]
Okay. I always use the Program Folder option for storing the config files.
I will look into what is wrong with storing in AppData.

**Comment by jernejs** [comment]
AppData worked fine in the last release, so something must've changed since then.

Anyway, I think I got the layout in Slovenian translation fixed (at least it looks fine to me, both in regular and high-DPI), although I'm not completely sure how the layout changes affect the default locale (I did all layout edits in Slovenian locale, but in some cases the non-.sl.resx files were changed).

**Comment by Ryochan7** [comment]
The language switcher change altered when the Profiles.xml file was loaded. The Load method was being called before the file was found so the default Program Folder path was being used. The latest commit fixes the order so that the proper path to Profiles.xml is set before attempting to load the file. It has been tested and loading from AppData works again.

https://github.com/Ryochan7/DS4Windows/commit/15de9307c34f01c6b2feb5acc9d90f94baef65ce
