### ISSUE TITLE
Errors occurring, service won't start

### ISSUE THREAD

**Issue by Toadlover404Git** [Ryochan7/DS4Windows#2005]
The title says it all; every time I try to launch DS4Windows (latest version, 2.2.15) it gives me this error and doesn't start the service. I don't know what's wrong but this just keeps happening.
![image](https://user-images.githubusercontent.com/49255834/112774583-663e8700-8ff7-11eb-9799-c7a23d76c678.png)

**Comment by Toadlover404Git** [comment]
I tried downgrading to an older version and running it as administrator. Nothing changed.

**Comment by mika-n** [comment]
#1775 

You must have somehow messed up HidGuardian system registry settings.

**Comment by Toadlover404Git** [comment]
I used another fork of DS4Windows and it never did that. Only the official version from this repo is doing this.
Is there anything I can do?

**Comment by Ryochan7** [comment]
Again, DS4Windows does not even write to that registry value. People use other tools that mess up their config and then complain to me. Never even explained how you installed HidGuardian as there are probably at least 4 different ways to do it. If you didn't use my tools exclusively then the problem is on you and whatever tool used the wrong data type when writing that value.
