### ISSUE TITLE
PS5 controller wont work on FiveM

### ISSUE THREAD

**Issue by BTYlush** [Ryochan7/DS4Windows#2016]
I can get my PS5 controller to work on every other game I play on my PC with the assistance of DS4 windows that you produce but I cant get it to work at all on FiveM... im not a programmer just an avid gamer and was just wondering if other people have had this problem and if there is any solution for this problem or if there is nothing you can do about it then so be it... Love the program you put out and i will still continue to use it. Just wondering if im doing something wrong or if there is no fix to this problem.. I am using the newest version also..

This probably not the right format for the issue tab, but didnt know how else to raise the subject.

Thanks for your time.

**Comment by mika-n** [comment]
double controller issue?
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

However, wiki docs of DS4Windows talks about HidGuardian tool as an alternative solution (if the built-in exclusive mode doesn't work) but it may be best to wait a little longer because HidGuardian will be replaced with DsHidHide tool. Or feel free to try HidHidHide tool.
https://github.com/ViGEm/HidHide/releases/tag/v1.0.30.0

**Comment by mika-n** [comment]
closed as inactivity and not providing enough info
