### ISSUE TITLE
HidGuardianHelper is being launched multiple times

### ISSUE THREAD

**Issue by ferrazpedro** [Ryochan7/DS4Windows#2029]
**Describe the bug**
If I close and open DS4Windows again, a new HidGuardianHelper process is executed.

**To Reproduce**
Close and open DS4Windows multiple times.

**Expected behavior**
DS4Windows should close the HidGuardianHelper process while exiting or shoud reuse the process already running.

**Screenshots**
![image](https://user-images.githubusercontent.com/37643357/113519849-406c3180-9565-11eb-873b-223134f50cc7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro for Workstations 20H2 x64
 - DS4Windows Version 3.0.1

**Comment by Ryochan7** [comment]
These issues should have been fixed in the past couple of DS4Windows releases. Although, it might not matter for long anyway.

Now I am using HidHide, successor to HidGuardian, to hide controllers on my system. It works out better and it is more flexible than HidGuardian. The driver can whitelist specific programs without the need to manage PIDs and the installer includes a utility to set allowed programs. HidHide and its Configuration Utility would remove the need for HidGuardHelper as well as HidNinja.

**Comment by Ryochan7** [comment]
https://vigem.org/projects/HidHide/
