### ISSUE TITLE
Can't launch HidNinja

### ISSUE THREAD

**Issue by ferrazpedro** [Ryochan7/DS4Windows#2030]
**Describe the bug**
HidNinja can't being launched in version 3.0.1. I have already tried in the options menu, and launching directly the executable with no results.

**To Reproduce**
Try to launch HidNinja.

**Expected behavior**
HidNinja should be executed.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro for Workstations 20H2 x64
 - DS4Windows Version 3.0.1

**Comment by mika-n** [comment]
there may be some issues in HidNinja because DS4Windows was changed to use .Net Core in version 5.x instead of the old .Net Framework 4.x. Maybe you should download the latest DS4Windows 2.x version and unzip it to a separate folder and use HidNinja from there? The end result is the same because the HidNinja itself doesn't need to be in the same folder with the DS4Window 3.x version.

**Comment by Kanuan** [comment]
@mika-n I don't have HidGuardian anymore so I can't test to confirm, but I think there is a bug where HidGuardianHelper.exe will continue running in the background indefinitely (don't know if it's a chance or happens all the time). I remember I could open HIDNinja again after terminating it.

**Comment by mika-n** [comment]
yes, there were some bugs in HidGuardian when the host app DS4Windows moved over to use .NET5 but few of those bugs have been already fixed. Of course there may still be some corner cases, but that's why you are part of the testing and quality assurance department of DS4Windows Corporation :-)
