### ISSUE TITLE
DualSense (Charging with External Power Source while connected to Bluetooth)

### ISSUE THREAD

**Issue by Zachary211** [Ryochan7/DS4Windows#2042]
While using DualSense connected over Bluetooth, changes to charging state are not recognized correctly. Controller seems to charge yet no indication is given properly by DS4Windows. The lights will not pulse when configured to do so, and the player led on the bottom of the light bar seem to glitch out entirely sometimes having 3-5 lights randomly lit when controller is plugged in charging from external power source and connected over Bluetooth at the same time. 

1. Connect DualSense to Ds4 over Bluetooth. 
2. Set lightbar to pulse on charging, and player LEDs to signify battery level. 
3. Plug in DualSense to charge from external power source (Not the PC that is running DS4Windows), while connected over Bluetooth. 
4. Watch incorrect controller behavior and no charging indication for DualSense from DS4Windows.  

All charging indications seem to be working fine on a DS4 controller as always. Only having issues with DualSense. If you repeat the same with the DS4 then DS4Windows will say (%+) besides the battery level to indicate charging, and the light bar will begin to pulse correctly. 

![Not Charging](https://user-images.githubusercontent.com/35925223/113901323-bdcdb700-979c-11eb-82cb-1ebfc7669017.png)

![Charging](https://user-images.githubusercontent.com/35925223/113901419-d4740e00-979c-11eb-9eab-808632fbe7fe.png)

 - Controller Make and Model: Sony DualSense (CFI-ZCT1W)
 - OS: Windows 10 Pro 20H2 (KB5000842)
 - DS4Windows Version (3.0.1) 

Battery % that is reported when plugged and unplugged seems to also be sporadic with DualSense. It can be at 25% when unplugged, then report at 50% when plugged in then report at 12% when immediately unplugged again. Sometimes it goes down, sometimes it goes up. This could all be due to charging issues reported on the stock DualSense controller firmware. (unfortunately I cannot get my hands a PS5 to update the controller firmware and test).

Also just wanted to send thanks to everyone involved with keeping DS4 Windows working and up to date. Especially for just dealing with constant changes to Windows and pushing out that .NET5 port. 👍

**Comment by Ryochan7** [comment]
Confirmed with Hid Report Inspector. This looks to be hardware related more than anything else. When the DualSense is connected to my wall charger, the USB Charging flag does not get activated in the input reports. Although, it doesn't happen with the DS4 either but that case supposedly works on your end. Since that flag is not read in the input report, there is nothing for DS4Windows to report on so the (+) charging indicator will not appear.

**Comment by Birdulon** [comment]
I've observed sporadic charging for both DS4 and DualSense controllers with a USB power meter. DS4Windows seems to report charge state correctly, the controllers just have a habit of not always charging while plugged in, even when reporting lower battery levels like 50%. I've found replugging them on either end sometimes makes them go from drawing 0A to 0.8A.

It's likely the controller firmwares attempting to minimize battery wear, best to just assume DS4Windows is reporting correctly and that the controller is indeed not charging if you can't otherwise measure it, I've had a DS4 drop out while connected via USB.
