### ISSUE TITLE
Keeps asking for SaveWhere

### ISSUE THREAD

**Issue by schroef** [Ryochan7/DS4Windows#2053]
**Describe the bug**
Each restart it asks for SaveWhere

**To Reproduce**
1. Launch DSWindows
2. Dialog shows asking which folder to choose

**Expected behavior**
Ones chosen this setting should be stored in some config or settings file.

**Screenshots**
not needed

**Desktop (please complete the following information):**
 - Sony DS4 v.2 (00:1F:E2:D1:07:DE)
 - Windows 10 Microsoft Windows NT 10.0.19042.0
 - DS4W v3.0.1

**Additional context**
First installed as stated by [this page](https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide), it clearly states install in Program Files.
What i find weird is that in a couple issues reports here, i see its stated otherwise and should be installed in AppData?!

In the logfile i see it cant find config file, not sure what this file is named. All i see is ControllerConfigs.xml which has a broken XML tree same as for AutoProfles.xml, i guess they be filled properly if set.
```
2021-04-10 14:38:56.0550|INFO|DS4Windows version 3.0.1
2021-04-10 14:38:56.0550|INFO|DS4Windows exe file: DS4Windows.exe
2021-04-10 14:38:56.0550|INFO|DS4Windows Assembly Architecture: x64
2021-04-10 14:38:56.0550|INFO|OS Version: Microsoft Windows NT 10.0.19042.0
2021-04-10 14:38:56.0550|INFO|OS Product Name: Windows 10 Home
2021-04-10 14:38:56.0550|INFO|OS Release ID: 2009
2021-04-10 14:38:56.0550|INFO|System Architecture: x64
2021-04-10 14:38:56.0550|INFO|Logger created
2021-04-10 14:38:56.0724|INFO|No config found. Creating default config
2021-04-10 14:38:56.0979|INFO|Default config created
2021-04-10 14:38:56.7277|INFO|Running as User
2021-04-10 14:38:57.7564|INFO|Starting...
2021-04-10 14:38:57.7564|INFO|Connection to ViGEmBus 1.14.3.4 established
2021-04-10 14:38:57.7564|INFO|Searching for controllers...
2021-04-10 14:38:57.7564|INFO|Using Shared Mode
2021-04-10 14:38:57.7794|INFO|The gamepad DS4 v.2 (BT) uses custom feature set (MonitorAudio)
2021-04-10 14:38:57.7954|INFO|Found Controller: 00:1F:E2:D1:07:DE (BT) (DS4 v.2)
2021-04-10 14:38:57.8519|INFO|Plugging in virtual X360 Controller
2021-04-10 14:38:57.8519|INFO|Associate X360 Controller for input DS4 #1
2021-04-10 14:38:57.8739|INFO|Controller 1 is using Profile "Control-New". Battery level is 50%

```

[Auto Profiles.zip](https://github.com/Ryochan7/DS4Windows/files/6290548/Auto.Profiles.zip)

**Comment by schroef** [comment]
As i was reading this page > https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting
I see talk about a ds4windows.exe.config file i dont see such a file on my system. I only see DS4Windows.runtimeconfig.json

**Comment by Ryochan7** [comment]
Any page mentioning the use of the "Program Files" folder needs to be updated. That is extremely bad advice. Extracting the program to that folder will just lead to permission issues in many situations. I typically extract to the a sub-folder of the Downloads folder.

.NET 5 changed the application config file standard. DS4Windows.runtimeconfig.json is the new file and it uses JSON now rather than XML.

**Comment by schroef** [comment]
Thanks for the fast reply Ryochan7, i do see that file. I actually tried adding this *.exe.config file but that ds4 wont run so deleted it again. It seems the app is still looking for this file, [i did see ](https://github.com/Ryochan7/DS4Windows/blob/4c6a1d7012bc9730edbc3ba659d99c3e8e005e60/DS4Windows/DS4Forms/ViewModels/SettingsViewModel.cs)it in the code as well.

Ive been trying to find a solution for this "SaveWhere' dialog, but moving the app to appdata folder doesnt solve this. Is it normal behavior that it keeps asking this, i could not find that neither.

**Comment by schroef** [comment]
PS not sure this is really an issue, but if i check the actual log file vs the log tab in the app. Noticed that the line about the missing config file does not show in the app. See #line 8 > 10

![actual-log-vs-log-in-app](https://user-images.githubusercontent.com/6923008/114282592-c29ba080-9a12-11eb-89a1-9d19a98f573d.png)

**Comment by mika-n** [comment]
Is this still an issue in the latest version of DS4Windows?
And you should update the ViGem driver because the logfile screenshot shows you have an ancient 1.14.x version of ViGem

Make sure to use 64bit version of DS4Windows and ViGem:
https://github.com/Ryochan7/DS4Windows/releases
https://github.com/ViGEm/ViGEmBus/releases

Anyway, the app first checks the DS4Windows EXE folder if Auto Profiles.xml file is there. If not then it checks if the file is in %APPDATA%\DS4Windows path. You need to have read-write permission to one of these locations. The default recommendation is to use %APPPATH% as a profile location. Check that you don't have Auto Profiles.xml file in both of these locations.

**Comment by schroef** [comment]
@mika-n , yes still asks for where to save.

Does this logger come with ds4? Because i dont remember installer that.

I updated it couple times, when this issue occurred, uninstalled and did everything again as to the instructions. Still keeps asking it.

I first had indeed 2 locations with files, but according to the dev that is not good behavior. So uninstalled and installed everything in appdata folder. Still doesnt seem to matter.

I my comment earlier, i also noted that their own guides tell mixed things were to install, thats also why its perhaps confusing

**Comment by schroef** [comment]
Just updated 3.0.3 and installed ViGem, which prompts by installing this update. Did a reboot and still keeps asking.
Everything is in appdata where i as admin have full control over the folder.

**Comment by schroef** [comment]
If you see this comparison between in app logging and the actual log file. What is that config file, see line 9, it looks for? 

![log-comp-v3 0 3](https://user-images.githubusercontent.com/6923008/115592562-5dad3980-a2a1-11eb-8a19-7e05fb8f9940.png)

**Comment by schroef** [comment]
I see that "No config found" in this file, [App.xaml.cs](https://github.com/Ryochan7/DS4Windows/blob/4c6a1d7012bc9730edbc3ba659d99c3e8e005e60/DS4Windows/App.xaml.cs) , which check if this is the first run. Can that be related?

![first-run-check](https://user-images.githubusercontent.com/6923008/115593392-710cd480-a2a2-11eb-9043-1da3cd19fdde.png)

i see first run in another file where its declared different. I guess this is sort of deep linking? Not sure, dont know the language.

PS to be clear, my DS4windows is in ```c;/users/MYNAME/Appdata/Roaming/DS4Windows```

What i dont quite get, if this check, it check if autoprofiles is in the location of the exe and in appdata, thats probably for the 2 locations. But if i read it correct, if the file is there, then it states FirstRun as True. Shouldnt Firstrun than be False?

![firstrun-alwaystrue--withautoprofiles](https://user-images.githubusercontent.com/6923008/115594518-d614fa00-a2a3-11eb-96d3-81a6b82ad8c0.png)


I dont see any code which state FirstRun is set to false. Plus auto profiles is an option to use or not. When i did not had that file i also kept getting the window save where dialog. The last time i tried to solve it i created the file to see if it gets rid of that save where dialog.

**Comment by schroef** [comment]
I seem to have admin issues i guess. I tried changing something in the settings, toggle "quick save". But on restarting the app again, i dont see these changes have been saved. I tried running as admin still nothing.

The only thing i do see is that the folder DS4Windows has "read only" in the folder properties. Does that matter?
Ive have set my own admin account to have full control over everything. I never get why Windows still shows "read only".
Another thing, if we dont have writing permissions, shouldnt that popup in the log of ds4windows. That would make clear if that is issue.

![full-control-admin-user](https://user-images.githubusercontent.com/6923008/115595937-89322300-a2a5-11eb-91bc-feabadd80cda.png)
![read-only-issue](https://user-images.githubusercontent.com/6923008/115595940-89322300-a2a5-11eb-9748-08d4471f2dd4.png)

**Comment by mika-n** [comment]
>PS to be clear, my DS4windows is in c;/users/MYNAME/Appdata/Roaming/DS4Windows

Do you mean that the application executable is in Roaming folder? Maybe you should try to copy DS4Windows.exe (and other files in the same folder) to c:\apps\DS4Windows\ folder because c:\program files/program filesx86/desktop/windows profile folders and user's home folder have extra security tweaks in Win10.

**Comment by schroef** [comment]
Okay will try, but that is different vs what is stated in their howto guide.

Doesnt the user folder appdata/roaming/ds4windows have full rights? I mean i can write there files without prompts. I see it create those files in fly.

**Comment by mika-n** [comment]
>I see talk about a ds4windows.exe.config file i dont see such a file on my system. I only see DS4Windows.runtimeconfig.json

Now when DS4Windows v3.x jumped to .NET 5.x wagon the ds4windows.exe.config file is gone and it is replaced by DS4Windows.runtimeconfig.json file. The document haven't been updated, but thx for pointing out the old document.


>Does this logger come with ds4? Because i dont remember installer that.

Yes. DS4Windows app itself has all required components to write out logfiles. By default logfiles goes to %APPDATA%\DS4Windows\Logs folder. Those sames log entries are shown also in Logs tab page within the app (well, almost the same messages because couple messages goes only to the logfile and not to the Logs GUI).

>Doesnt the user folder appdata/roaming/ds4windows have full rights? I mean i can write there files without prompts. I see it create those files in fly.
>I put it in documents and it runs fine. 

You mean now the app works without always prompting about where to save profile/config files? If that is the case then I guess the roaming profile folder was the problem. After all it is a bit special kind of folder and for some reason the app doesn't wanted to be installed there. Sometimes these permissions are mysterious and some people run using admin account and others using user account. And some PC setups may have a network linked roaming profile folder and others local roaming profile. Or the profile folder is clean up each time the PC is rebooted etc etc etc...... Who knows what.....

**Comment by schroef** [comment]
Sorry for commenting while it was closed.

What I find strange is that I am the admin and have full rights on that folder and every folder traversed. You state the app doesn't like to be installed there, however it is notes a couple times here that that should be the better place? I'm getting confused about which folder is better or not.

It runs fine now inside user>documents folder

Ps my points about that looks g error I s that the code still looks for exe.config file 

I also think it shows startup dialog because the exe is in the same folder and according to the code it then shows startup save where dialog. Check the screen grabs I posted earlier. The if statement should be different I think

**Comment by Masamune3210** [comment]
Basic  rule of thumb is if you want to make sure something is going to work well, either make a folder and put it in your Downloads folder or another folder that you own without UAC protection, or put it on a drive other than your C: drive if avaliable

**Comment by schroef** [comment]
Yeah, but that is no solution, the issue is that i have full control as admin and it skips the proper checks
