### ISSUE TITLE
Windows XP

### ISSUE THREAD

**Issue by shiny-ribbon** [Ryochan7/DS4Windows#206]
May be out of luck here, but.... any way to get this working on Windows XP?

**Comment by JarnoVgr** [comment]
I took a quick look and the project depends on .NET Framework v4.5.2 which is not supported on Windows XP. I've tried setting it to .NET Framework 4.0, but the code uses some features from the newer version.

Maybe @Ryochan7 can provide a more in depth answer/solution.

**Comment by shiny-ribbon** [comment]
Yea I realized yesterday that was the issue. I really like XP hence this question. Fortunately I have Vista on this computer too for situations like this, and I-ve got it working on that.

Maybe I should make another topic about this but is there a way to turn off the latency lightbar pulse? it pulses red because I'm getting a latency of 10+ms

**Comment by JarnoVgr** [comment]
About the latter question: In the settings there's an "Flash Lightbar at High Latency" option.

**Comment by shiny-ribbon** [comment]
Thanks a ton! I don't know how I missed that

**Comment by Ryochan7** [comment]
Besides the .NET version requirement, I believe there are some Pinvoke calls being performed that require libraries included since Windows Vista. Also, it looks like ViGEm requires at least Windows 7 to be installed in order to work. The README should probably be updated to specify that DS4Windows only supports Windows 7 and newer.
