### ISSUE TITLE
[request/issue] improve checks regarding vendor-defined devices

### ISSUE THREAD

**Issue by Kanuan** [Ryochan7/DS4Windows#2060]
**Describe the bug**
From what I understood, the Horipad FPS Plus spawns two devices/has two parts. One is the gamepad itself and another some programming interface it has. Because this interface must be ignored to not cause issues, DS4Windows [has some checks in place to ignore vendor-defined devices](https://github.com/Ryochan7/DS4Windows/blob/jay/DS4Windows/DS4Library/DS4Devices.cs#L247).

The problem with this are 2:

- It only works when Windows current language is english. Since it gets the device description in the current language, having windows in another one will make the check always false
- When Windows is in english and the check works as it should, DS4Windows ignores every vendor-defined device even when they should be supported. This behavior was messing with some tests with the [custom DsHidMini DS4 Mode](https://github.com/ViGEm/DsHidMini/issues/59)

**How to reproduce**
You need a device that is both vendor-defined _and_ supported in DS4windows. I made this test with DS3 running a custom DsHidMini driver where the DS4 mode is Vendor Defined and the usage is 0x01. If the driver is installed with DS4 Mode as default (by editing the .inf file) the device ends up registered on windows as vendor defined. When using a custom DS4Windows build that has support for devices with usage 0x01, the DS3 is only picked if the set Windows language is not english.

**Expected behavior**
Besides the checking working regardless of the set Windows language, it should not ignore every single vendor-defined device., only the ones related to the affected devices.

**Desktop**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro 20H2 (OS Build 19042.906)
 - DS4Windows Version: Custom 3.0.1 that has support for devices with usage 0x01

**Aditional information**
I discussed the situation with Mika-n regarding this, but I wanted to avoid making changes that can affect devices I don't have and can't test.

I can throw another if/else in there to account for the new DsHidMini DS4 Mode, but I don't know how to properly implement a general fix for the issue as a whole that is both independent of the Windows' language and make only some specific vendor-defined devices ignored.

Though we can avoid the issue on dshidmini's side by just not making ds4 mode the default mode in installation, we want to avoid some situation where Windows could update the device's description back to vendor-defined and cause issues.

**Comment by mika-n** [comment]
yes, I can see the problem in the existing implementation (how it is a bit flawed in non-english WinOS setups and how it prevents some of the vendor-defined devices to work in DS4Windows). This "ignore vendor-defined devices" logic was added because of those very few 3rd party/copycat devices and not because all devices would have that kind of vendor-defined programming interface with usage=JOYSTICK or usage=GAMEPAD hid attributes. 

So, I guess the best way to solve this issue is to add a new "ignore vendor defined interface for this device" FeatureSet bitflag in DS4Devices.cs device list. This way we could easily tell DS4Windows that those certain devices may have this interface with usage=joystick/gamepad but it should be ignored. The end result would be that the DS3 VID/PID FeatureSet record would NOT have this featureSet flag set and this way the "vendor-defined" DS3 would be accepted (as is proven with the debug version of ds4windows that it works that way). Additional bonus would be that the DS3 "vendor specific" device would not need HidGuardian/DSHidMini/ExclusiveMode because games would not see it anyway, only DS4Windows would see the device because the "fake" VID/PID is set in FeatureSet array.

I'll look at this...
