### ISSUE TITLE
DS4Windows crashing

### ISSUE THREAD

**Issue by K54M** [Ryochan7/DS4Windows#2064]
So on DS4Windows 3.0 & over, whenever the program is minimized & I right click on the taskbar icon & press "Open program folder," the program crashes & I have to end the process manually then reopen the program. Not sure what the problem is. Im using V2.15 for now. Mainly just wanted to make people aware.

**Comment by K54M** [comment]
To clarify, im using V2.15 for now because V3.0 & over seem unstable for now, which is understandable since we switched to .Net 5

**Comment by K54M** [comment]
So after looking at the logs, it seems that then I press Open program folder, DS4W shows "Request app shutdown" & then closes, but doesnt end the DS4Windows,exe process

**Comment by K54M** [comment]
[ds4windows_log_20210413.1.txt](https://github.com/Ryochan7/DS4Windows/files/6306488/ds4windows_log_20210413.1.txt)

**Comment by K54M** [comment]
Seems like starting DS4Windows in admin mode fixes it. Not sure if I should always start DS4W in Admin mode

**Comment by Ryochan7** [comment]
Not sure why the access denied exception would pop up there. Going to have to look at that one case otherwise. Not sure why Microsoft changed the ProcessStartInfo class to have UseShellExecute default to false for .NET 5; the default for .NET Framework was set to true. That one change has caused quite a few errors to pop up.
