### ISSUE TITLE
ViGEmBus Driver Unsupported on Windows 7

### ISSUE THREAD

**Issue by CharlieM1997** [Ryochan7/DS4Windows#2065]
Hi,

I'm using Windows 7 and cannot install the newest ViGEmBus Driver. When I load into DS4Windows, it always opens with the Welcome screen. The option to install the 360 Driver for Windows 7 is greyed out. I already have the 360 Driver installed, but after closing the Welcome screen, the Start button is completely unresponsive.

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6306480/ds4windows_log.txt)
![Capture](https://user-images.githubusercontent.com/38163981/114614945-09043000-9c9d-11eb-8e10-58c9d0ca1ca1.PNG)

**Comment by mika-n** [comment]
The latest V1.7.333 ViGem doesn't support Win7 anymore. And the latest DS4Windows is also dropping Win7 support, so unless you move on to upgrade to Win10 then you are stuck with DS4Windows 2.x version. But I say "time to upgrade"

**Comment by Ryochan7** [comment]
ViGEmBus 1.17.333.0 only works on Windows 10. People have posted so many issues regarding bugs in out of date ViGEmBus installs that I opted to now force a minimum ViGEmBus version for using DS4Windows. The big downside is that Windows 7 users are finally out in the cold. Windows 7 had an extra year past EOL.

The solution to this issue is to "upgrade?" to Windows 10.

**Comment by reyaz006** [comment]
I'm on Windows 8.1 and I find there is still a good amount of changes in 3.0.2 log. Any chance to make it optional? Like, I could enable an option that would let me still use the application but be reminded that my OS is not supported by you anymore? Or also, if most of the issues the 1.17.333.0 aims to resolve are about DualSense, maybe only enforce the newer version for it?

I'd hate to be forced to mod the application or rely on someone's fork in order to use it.

**Comment by Masamune3210** [comment]
Unfortunately the amount of pure garbage the devs have had to put up with from people is pretty much why this decision exists in the first place, so it's extremely unlikely to be reversed any time soon

**Comment by Ryochan7** [comment]
> I'm on Windows 8.1 and I find there is still a good amount of changes in 3.0.2 log. Any chance to make it optional? Like, I could enable an option that would let me still use the application but be reminded that my OS is not supported by you anymore? Or also, if most of the issues the 1.17.333.0 aims to resolve are about DualSense, maybe only enforce the newer version for it?
> 
> I'd hate to be forced to mod the application or rely on someone's fork in order to use it.

I have been conflicted about doing this for a long time. There have been several issues posted here that really seem to be problems with past versions of ViGEmBus. I didn't originally want to do anything heavy handed to attempt to not have DS4Windows interfere with other apps. As shown with Parsec today, some other apps don't share that same concern and will just blow away a previous config unprompted.

With a lot of issues not posting any real information and posts being the equivalent of **the thing don't work**, it makes trying to diagnose problems almost impossible. I really feel like I need to start narrowing support down closer to my preferred configuration to save myself some frustration. The whole Parsec drama today also seems to be an indicator that there are issues posted here that are not problems caused by DS4Windows.

On a somewhat related tangent, there is the likelyhood that DS4Windows will stop supporting the use of HidGuardian in the near future. HidHide would then be the preferred way to block devices and that driver only works on Windows 10. This whole fork has been a moving target since its inception. If it weren't for Microsoft's own driver support changes, I would be a bit more concern about continuing to support Windows 8.1. As it is, Microsoft effectively killed Windows 8.1 before its EOL date.

**Comment by reyaz006** [comment]
Well. Guess 3.0.1 will be my friend for a few more years then.

**Comment by mika-n** [comment]
The fact is that at some point the rope needs to be cut if it is dragging the whole ship. Especially when the ship has veeeery limited time resources. Someone else for sure can fork this and try to keep Win7 and Win8 support back ported, but it takes time and dedication. Ryochan7 is just one person, so he cannot do everything especially if he doesn't need Win7 and Win8 anymore and time is running out then something needs to be done in order to keep improving the Win10 version of DS4Windows. Or the end result may be burn out and then everyone looses.

**Comment by Ryochan7** [comment]
DS4Windows 3.0.3 has reduced the ViGEmBus restriction to allow driver version 1.16.112.0 to work again. Now Parsec's flawed ViGEmBus install works again and older versions of Windows are temporarily supported again.

I will keep stating this. **PLEASE DON'T MAKE ME REGRET THIS**.
