### ISSUE TITLE
Program stops after some time

### ISSUE THREAD

**Issue by SnowSquire** [Ryochan7/DS4Windows#2071]
**Describe the bug**
After some time the program stops and sends out the error "ViGEm Device Plugin Failed. Closing Connection. If the isssue persists reboot Windows"
I've rebooted 3 times and have installed both the 1.17.333 & the 1.16.116 versions of ViGEm.

**To Reproduce**
Launch DS4Windows
Connect a controller
Wait
The program stops

**Expected behavior**
Program doesn't stop

**Desktop (please complete the following information):**
Log is attached

**Additional context**
Happened after I updated to ViGEm 1.17 but reverting doesn't work
[ds4log.txt](https://github.com/Ryochan7/DS4Windows/files/6321217/ds4log.txt)

**Comment by Ryochan7** [comment]
So this is happening when plugging in a virtual DS4 rather than an Xbox 360 controller? Can you check the HID-compliant game controller list in the Device Manager? You might have to enable the **Show hidden devices** option under the View menu. Maybe the virtual device is counted as corrupt somehow. Here is a post of a similar issue I experienced but it was with a virtual Xbox 360 controller.

https://github.com/Ryochan7/DS4Windows/issues/1597#issuecomment-779407414

The issue has not happened to me again so I have not seen about what measure can be taken. My only idea at the moment is to delete the associated virtual device. You would have to check the Properties window and look at the Location value (Location # is likely a virtual controller created by ViGEmBus).

**Comment by SnowSquire** [comment]
I ended deleting all the controller related devices in device manager and the .infs in driverstore. it was happening with both a virtual x360 and ds4 controller

**Comment by Ryochan7** [comment]
Thank you for the update. Deleting the files in the driver store might have been a bit overkill but at least it worked out for you. My only idea for a possible workaround to this would be including some sort of utility script that would attempt to delete those virtual devices. Since I have not run into that issue since I wrote that other post around February, I have not had a way to test whether that would even help workaround any problems.
