### ISSUE TITLE
Exclusive mode not working, and keeps putting split screen in my game when I press start, was fine till I updated.

### ISSUE THREAD

**Issue by ZurqWRLD** [Ryochan7/DS4Windows#2073]
**Describe the bug**

**To Reproduce**
the controllers menu, and for some reason since I updated, exclusive access is now off, when playing cod it works fine, but if I play rocket league I have to press the hide ds4 and it works but when pressing start it puts split screen, idk what happened, but before i updated ds4windows it worked perfectly on every game, now I cant play and I am getting a headache, its 230am and i am in this situation. ahhh please help

 - Controller Make and Model: Sony PS5 Dualsense
 - OS: Windows 10 20H2
 - DS4Windows Version Latest

**Comment by ZurqWRLD** [comment]
sorry if i did that wrong, first time posting

**Comment by Kanuan** [comment]
The Hide ds4 function can fail for many different reasons. [Why it can fail is explained on the wiki](https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues), but the summary is: don't use it.

__If you are on Windows 10 64 bits__, you can solve this issue by using HidHide. There's no specific guide for Dualshock 4 / Dualsense / Nintendo's controllers as of now, but it's pretty simple, just follow all the steps:

- Install the latest version of [HidHide](https://github.com/ViGEm/HidHide/releases) and its prerequisites, then reboot your computer

After reboot, connect your Controller and make sure DS4Windows is __STOPPED__ so you don't get confused on the next steps. Then open HidHide's configuration utility and:

- On the `Devices` tab, mark the checkbox on your controller entry (If you are not sure which it is, disconnect the controller to see which entry disappears, then reconnect it). A Red Lock icon should appear when you mark it
- Still on the `Devices` tab, mark the `Enable device hiding" checkbox in the bottom
- If you play both wired and wireless, make sure to repeat this process with the controller connected the other method
- Now on the `Aplications` tab, click on the `+` icon and add your DS4Windows.exe inside your DS4Windows folder so it can is allowed to see the controller
- Disconnect then reconnect your controller so the changes are applied
- With the controller connected and DS4Windows still stopped, check on the [Gamepad tester website](https://gamepad-tester.com) if no controller shows up, indicating that the controller is indeed hidden
- START again DS4Windows, it should pick the controller if you've set HidHide configuration utility correctly
- Check on the gamepad website again if the emulated Xbox/DS4 controller appears and is the only one

I'm only writing this small guide because the previous solution, HidGuardian, is obsolete now with HidHide, its successor, but there isn't a guide for it for now. In the future DS4Windows _may_ be able to auto-hide controllers as long as HidHide is installed.

Another thing to keep in mind is that [a few users](https://github.com/Ryochan7/DS4Windows/issues/20260) have a increased input delay when using HidHide. On my personal tests I couldn't notice it, but whatever is happening is already known and will be probably fixed in the next HidHide version. So, just try it and if everything works ok for you then great.

Remember to close this issue if this solves your problem.

**Comment by Newtype14** [comment]
@Kanuan I didn't know about HidHide. I followed your great guide and managed to install it no problem! One question though: Is it normal that in DS4Windows it says that "Shared Mode" is being used? There's a cross in the "ex" column.

**Comment by mika-n** [comment]
> @Kanuan I didn't know about HidHide. I followed your great guide and managed to install it no problem! One question though: Is it normal that in DS4Windows it says that "Shared Mode" is being used? There's a cross in the "ex" column.

Yes, "shared mode" is normal when DsHidHide or HidGuardian tool is used to hide the original physical controller because in those cases DS4Windows app itself doesn't even know if DsHidHide/HidGuardian hides or not the gamepad. This is why the gamepad is still shown as "shared mode" in DS4Windows.

**Comment by Kanuan** [comment]
Just 2 things regarding mika-n's comment: 

- It's only HidHide, not DsHidHide
- Ds4Windows knows if a gamepad is hidden with HidGuardian. The controller will appear with a "key" icon in the `Ex` colum in the `Controllers` tab

**Comment by mika-n** [comment]
true, ds4windows finds the existence of HidGuardian driver and whitelists the DS4Windows process in HidGuardian registry settings, BUT DS4Windows still doesn't know for sure if HidGuardian.AffectedDevices sysreg entry really has an entry for the gamepad. If there isn't an entry for the gamepad then DS4Windows may think that HidGuardian hides the device even when the device is not actually hidden. DS4Windows doesn't actively modify or monitor AffectedDevices HidGuardian sysreg entry.

Anyway, all this HidGuardian stuff is soon in history because HidHide replaces HidGuardian tool and makes things easier to maintain.

**Comment by Ryochan7** [comment]
Special routines are implemented to try to determine if a controller is considered hidden by HidGuardian. When the hotplug routine is run, DS4Windows will grab the current AffectedDevices list from the registry and check the device's Hardware IDs against that list. If a match is found then DS4Windows will add the right flag and the lock icon will show up in the GUI.

HidHide is essentially brand new tech as the public release only happened recently. I am assuming that a similar list is probably used in HidHide for flagging devices but I have not looked into it yet. The change will happen eventually.

**Comment by Ryochan7** [comment]
Registry access is blocked due to security flags set during the install. It looks like all queries would have to be done through the driver control device.

**Comment by nefarius** [comment]
> Registry access is blocked due to security flags set during the install. It looks like all queries would have to be done through the driver control device.

Yes, that is done on purpose to keep authority over the state to the driver. [Configuration change must happen through the API only](https://vigem.org/projects/HidHide/API-Documentation/). 

Having HidGuardian "configured" through the registry by 3rd party applications has always been a poor design choice and comes from a time where the whole idea was more of a prototype than a thought-through solution.

**Comment by Ryochan7** [comment]
Initial HidHide integration has been added. The API is being utilized. So far, only the device hiding active state is grabbed as well as the current blacklist. Looking for the DS4Windows exe in the whitelist and adding it if it is not detected will probably be done soon.

https://github.com/Ryochan7/DS4Windows/commit/60d9c768b42a8ba389396d13cad4dc141038491e

https://vigem.org/projects/HidHide/API-Documentation/

**Comment by nefarius** [comment]
Damn, that was fast! Upcoming week I try to port the application whitelist API helper code from the C++ UI to C# utility classes as this has been proven quite tricky as well, dealing with nested mount points and translating executable paths to the WDM DOS volume path syntax the driver expects.

**Comment by nefarius** [comment]
Bloody hell, that was annoying [but it's done](https://gist.github.com/nefarius/639b582dd8149b0ca63c4f7ca68a9761). NTFS mount-point/junction-aware translation helper for "normal" file path to DIS device path the driver expects.

Reverse lookup in the works too, almost forgot that, oops.

Will update the [API docs](https://vigem.org/projects/HidHide/API-Documentation/) accordingly soon.
