### ISSUE TITLE
Updating DS4Windows via automatic updater does not launch custom named exe

### ISSUE THREAD

**Issue by Zero-Starlight** [Ryochan7/DS4Windows#2074]
**Describe the bug**
After updating DS4Windows, it launches the normal DS4Windows.exe, rather than the custom name .exe file that allows it to hide from Steam.

**To Reproduce**
1. Set a custom exe name for DS4Windows
2. Update DS4Windows using the automatic updater
3. Check task manager process list to determine that the custom named exe is not running

**Expected behavior**
Automatic updater updates DS4Windows and then launches the custom named exe. (If this isn't the intended behavior, please make it more clear)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense Wireless Controller (CFI-ZCT1W)
 - OS: Windows 10 Pro 64 Bit Version 10.0.19042 Build 19042
 - DS4Windows Version 3.0.3

**Comment by Ryochan7** [comment]
It is supposed to if you check for an update from DS4Windows. If you launch the updater from Explorer then it would launch normal DS4Windows.exe. That functionality has not been checked since around the time it was first implemented. The custom exe is passed as a cmd argument to the updater so I would not think that any .NET 5 change would cause issues. I'll look into it.

**Comment by Zero-Starlight** [comment]
I've been using Windows' native launch at startup option to run the custom exe at boot since running with the DS4Windows boot option seems to only ever launch the default exe.

**Comment by Ryochan7** [comment]
Just tested an update from version 2.2.15 to version 3.0.3. The new DS4Windows exe is copied and the custom exe is launched by DS4Updater when it is finished.

**Comment by Ryochan7** [comment]
Just realized a problem. The task problem seems to be related to a .NET 5 change. The code `Assembly.GetExecutingAssembly().Location` would actually return `DS4Windows.dll` since that is the assembly that gets loaded; the extension path is swapped to exe for the corresponding exe file. In .NET Framework, the exe has the assembly so the current executable file location would be returned. In .NET 5, the app loads the program assembly and both executables will load the same `DS4Windows.dll` assembly.

Going to need to change this so the task.bat file will link to the proper executable; this change would probably present other problems in the code for people using a custom exe as well.

**Comment by Ryochan7** [comment]
You will have to re-create the Task but the process should work now. The proper custom exe file will be used in the bat file rather than the default DS4Windows.exe.

At some point, I should probably just add a small helper executable to replace the current batch file. Would get rid of the short cmd window that pops up when launching the current Task.
