### ISSUE TITLE
ds4 controller defaults to no profile instead of default profile

### ISSUE THREAD

**Issue by powerpuffboysz** [Ryochan7/DS4Windows#2077]
using version 3.0.3 whenever i start ds4windows it says it defaults to the default 360 pad profile but windows tells me it defaults to no profile and no program actually sees the controller until i manually switch to another profile and then back to the default 360 profile

**Comment by mika-n** [comment]
Seen similar reports couple times. In those cases it turn out to be corrupted config files. Try cleaning up %APPDATA%\DS4Windows folder and try again.

**Comment by Ryochan7** [comment]
Only controller 1 defaults to the Default profile. Any other controller will default to the No Profile state when that slot is used for the first time. That is the way it has been since the Jays2Kings days. It would probably be easier to change that behavior now but I never felt the need to change it.

**Comment by Ryochan7** [comment]
I'll get this changed to default all controller slots to be assigned to the Default controller. It would probably be better that way as long as it does not break something else.
