### ISSUE TITLE
Random ghost input

### ISSUE THREAD

**Issue by unknowwiiplayer** [Ryochan7/DS4Windows#2081]
Whenever using DS4Windows to play taiko I get ghost inputs randomly. Not as if I had two inputs of the same button all the time.
Please watch this video to understand the issue. https://www.youtube.com/watch?v=t6iaKGPHR7w
It's very noticeable in the slow parts (0:36, 1:06, many more examples can be found in the video), I played two times using DS4Windows and two times using Steam, same songs.
Note that it happens on fast stream of notes and on slow single notes. It's seemingly random.
Also note that it seems to only happen on red notes, which are right and square. I have not noticed double inputs on blue notes.
At 1:40, there is a red, red-red-blue combination, red-red-red-red-blue is heard and on gamepad viewer you can see that the button presses were square, square-right-triancle (slow down the playback speed so you can see it).
At 5:10 I switch to Steam to play and there are no more ghost inputs.
I have no hypothesis on why this happens, but it also occurs on 250Hz bluetooth poll rate, just less frecuently. (BT poll rate in the video is 1000Hz)
It's independant on the connection method, and also is on the emulated controller wether it is a Dualshock 4 or an Xbox 360 controller.
osu! does support controller inputs for the notes, but I prefer to emulate a keyboard (sometimes I want to play with keyboard without changing settings), the keys are DFJK, left blue, left red, right red, right blue. I've tried using a macro with just that key press and the result is the same. Using button inputs in osu! doesn't do anything different tho.
My controller is a geniune dualshock 4 v1.
I run DS4Windows as a task, with admin privileges.

**Comment by Kanuan** [comment]
You need to test with "Keyboard inputs" or "Gamepad inputs" only. I don't know how the game works, but you need to isolate the problem. Having your controller "visible" while using it as a keyboard can lead to issues.

======== Testing with Keyboard Inputs only =============

- Follow [this comment](https://github.com/Ryochan7/DS4Windows/issues/2073#issuecomment-821201633) to hide your real controller by using HidHide (Windows 10 64 bits only for now) and letting only DS4Windows see it
- After the real controller is hidden, create a profile that has the `Use DInput only` checkbox marked in the `Other` tab. This will fully disable the emulated controller
- Since the emulated controller will be disabled and the real controller is hidden, it will be like you have no controller connected in your system. Confirm if this is the case by opening the [gamepad tester website](https://gamepad-tester.com/), pressing some buttons and making sure no controller pops up
- After you confirm no controller is detected, map this `Use Dinput Only` profile like you do now so the controller only works as a keyboard and test to see if the random ghost input issue happens.

======== Testing with Gamepad Inputs only =============

-- Follow [this comment](https://github.com/Ryochan7/DS4Windows/issues/2073#issuecomment-821201633) to hide your real controller by using HidHide (Windows 10 64 bits only for now) and letting only DS4Windows see it
- After the real controller is hidden, use a profile that emulates a default xbox or DS4 controller and play the game by ___NOT___ setting your controller buttons as keyboard keys 

Report your findings later

**Comment by unknowwiiplayer** [comment]
======== Testing with Keyboard Inputs only =============

I've followed the instructions, there is no controller showing up at gamepad tester nor gamepadviewer.
did the changes to the profile osu! ando also tried making a new one without macros (I've recorded the keypress in osu! so I can slide my finger from right to down and do a double red, advanced techniques that are used in console taiko that I cannot achieve in osu with normal keyboard emulation) https://www.youtube.com/watch?v=ftRQ-PcYMQM
The result was the exact same but this time I got greeted with a ghost blue note at 0:24, it doesn't only happen with red notes.
In the video I didn't select the new profile without macros properly, but I tested it later, the results were the same.

======== Testing with Gamepad Inputs only =============

Yet again the results were exactly the same. I'm starting to think it has to do with the leght of the button presses I do, to put it in an example, it seems to be something like if I press it for exactly 100ms, then a second button press is prompted, which lenght is so short it's not visible in the gamepad viewer.
https://www.youtube.com/watch?v=xStG-CADvKs
Note that due to the randomness of this, it happened few times in the first song, it seemed to be alright but at 1:21 the ghosting occured, and the second song was cursed, too much ghosting.
The BPM of the songs should influence the lenght of the button presses, hence there are songs with more ghosting, if my aforesaid theory is correct tho.

**Comment by Kanuan** [comment]
This is the type of issue that we don't know if is a issue with OSU! or with DS4Windows, requires more tests but I'm not sure how to properly test it. Just playing the game makes it difficult to isolate/reproduce the issue.

If you discover what exactly causes the issue let us know.

Oh, if you are keeping HidHide, remember that your controller is hidden now, so only DS4Windows can see it. If you want to use your DS4 as an actual DS4 then you need to do so by choosing DualShock 4 emulation in the profile settings

**Comment by unknowwiiplayer** [comment]
I'm pretty sure that it's not an issue with osu!, because it doesn't happen when using steam for the convertion.
It does also happen on other taiko simulators such as TJAPlayer3 when using DS4Windows to emulate keyboard or gamepad input, which doesn't happen when using steam.
You can reproduce the ghosting by mashing the buttons repeatedly on notepad. https://www.youtube.com/watch?v=qhIZ0h2c7WI

**Comment by mika-n** [comment]
Can you see those double "keyboard events" in Notepad?

**Comment by unknowwiiplayer** [comment]
You can see double key presses in notepad, if you alternate square and right you should get a jfjfjfjfjfjfjfjfj pattern, on my last video you can see that there are many instances of double j presses, in the taiko videos are double presses of other keys.

I have recorded a macro which goes like this for every key
↓F
Wait 29 ms
↑F

Ghosting occurs on profiles with normal key presses and with macros.

**Comment by mika-n** [comment]
if you have macros set to different gamepad keys and you keep pressing those buttons rapidly then macro sequence may end up being executed in parallel. You can solve this issue by setting "Syncronized run" option. It makes sure that the same macro in the same btn is not re-fired until the previous execution is completed.
https://github.com/Ryochan7/DS4Windows/wiki/Settings#macros-and-special-actions

**Comment by unknowwiiplayer** [comment]
I have tested setting a special action with the macro and the option "Syncronized run", no success.
https://www.youtube.com/watch?v=CsSWTysynHU

**Comment by mika-n** [comment]
how about if you try to set those macros like this:
- Key down
- Wait 20ms (or whatever delay, too short delay may cause Windows to miss the keyDown event completely)
- Key up
- Wait 20ms

The idea is to make sure that the last keyUp and the next macro sending keyDown doesn't happen too fast right after each other.

**Comment by unknowwiiplayer** [comment]
I added a 26 ms delay after the macros in all keys and the result is the same.

**Comment by unknowwiiplayer** [comment]
I tested a dualshock 4 v2, which I bought for my gf about a year ago, doesn't have as much use as mine, which was bought in late 2014.
I haven't experienced ghosting with her controller.

That lead me to think that my controller must be dirty inside and something among that way is causing the issue, so I took my controller apart and cleaned it. I made sure to clean all the rubbers, the contacts under them, the connection of the flexboard under the motherboard and all, using isoprophyl alcohol, q-tips and a toothbrush.

Sadly, the issue is still pressent in DS4Windows and absent when using steam.

**Comment by Kanuan** [comment]
I'll try reproducing the issue, though I only have a DS4v2 to test

**Comment by Ryochan7** [comment]
So this is sounding more like a flaw with the macro system more than anything else. Personally, I don't use macros in any of my profiles and I don't even recommend others to use the macro system. It is inherently flawed in several ways and is only left in the program for backward compatibility.

**Comment by Kanuan** [comment]
> Ghosting occurs on profiles with normal key presses and with macros.

In his case it also happens when directly mapping the buttons to keyboard keys, without macros.

**Comment by Kanuan** [comment]
I 100% can't reproduce it with a DS4v2. No macro, just direct keyboard buttons binding
https://user-images.githubusercontent.com/24910442/115276817-e4cfa580-a119-11eb-96fa-146936742bf3.mp4

The only repeated key I got was 100% my fault as my hand got tired.

If I recall correctly, DS4Windows makes no distinction between a DS4v1 and a DS4v2 (someone feel free to correct me) regarding how its data is read, the only difference is the controllers VID/PID. Since the issue doesn't happens with my v2 I'm inclined to believe its a hardware fault with your controller.

## Theory 

On BT, the default setting on DS4Windows instructs the controller to send a Input Report every 4ms, which means ~4 Input Reports every single frame (~16ms at 60hz).

In the middle of a frame, your controller is sending one Input Report with the button unpressed. DS4Windows registers it and deactivates the keyboard input, but the button release itself is not displayed on your gamepad viewer since it happens before the screen refreshes. When the screen actually refreshes the button is registered as pressed again.

On USB Input Reports arrive at a even faster rate.

Why it doesn't happen on steam _could_ be because they have some jitter compensation or Steam just updates the emulated controller/keyboard at a slower rate, missing the released button, instead of DS4Windows that updates it per button event. (this is more of a guess, don't take my word on it).

To test this, you would need to dump every single Input Report your controller sends. Use this software:
[SimpleHIDWrite3 (1).zip](https://github.com/Ryochan7/DS4Windows/files/6338015/SimpleHIDWrite3.1.zip)

- Test directly __WITHOUT USING MACROS__, just binding the buttons to keyboard keys
- Make sure your controller is not hidden with HidHide
- Make sure the emulated controller is disabled on DS4Windows
- Open SimpleHIDWrite
- Select Wireless Controller in the top list
- Quickly repeat the test you were doing with the notepad, record it too. Make sure to not press 2 different buttons at the same time so it's easy to identify what exactly you are intending to do later
- Once you identify the repeated input issue, go to SimpleHIDWrite, click on _save as_ and save the reports dump. Stop the screen recoding then.

## Why using MACROs is flawed to prevent button jitter

Do the following test: edit your macro so that the waiting time you are using is 1000ms.

What you are thinking happens if you press 5 times the button in the span of 1000ms:

- The macro is activated only 1 time, since it's reactivation is ignored while it's running

What actually happens:

- The macro is activated 5 times along 5 seconds.

**Comment by unknowwiiplayer** [comment]
SimpleHIDWrite gives me an error when I select my dualshock 4 and a lot of inputs are registered, I assume it's from the gyro

https://user-images.githubusercontent.com/53797610/115285710-2eb98b00-a11c-11eb-9a83-f1b973cd684a.mp4

**Comment by unknowwiiplayer** [comment]
Here it is https://www.youtube.com/watch?v=LkTNlPPbkxY
[ds4.txt](https://github.com/Ryochan7/DS4Windows/files/6338300/ds4.txt)

**Comment by Kanuan** [comment]
@unknowwiiplayer you know what is the funny thing? I checked the file you've sent and nothing indicates a button is being released and when it should not (unless the software I've sent you isn't reading every single HID Input Report).

[WhatAmIDoingWithMyLife.xlsx](https://github.com/Ryochan7/DS4Windows/files/6338732/WhatAmIDoingWithMyLife.xlsx)

**Comment by unknowwiiplayer** [comment]
@Kanuan I'm really impressed by your analysis. What you're saying is really interesting... if there was no actual input of release, then how did it even trigger a new button press? that's hella weird.

Unless that SimpleHIDWrite's poll rate looking for changes is slower than DS4Windows'. If that was the case, testing longer would have shown the release and press of the button in some presses.

Now that I saw how you read the data I could have added a third button just to act as a guide, but anyways, now that the issue is fixed I don't think there's a point in cleaning the graphite off to make the issue come back. If the issue comes back I'll order new rubbers, I don't want to reapply graphite periodically.
