### ISSUE TITLE
DS4 version 3.03 won't even open.

### ISSUE THREAD

**Issue by TheCrocc** [Ryochan7/DS4Windows#2083]
Hey guys hows it going,
I'm trying to install the DS4 in my windows 10 but it wont even open or appear in the manager, it pops a blank icon on the toolbar but disappears in seconds.

**Comment by TheCrocc** [comment]
I've deleted the files from appdata and reinstaled btw.

**Comment by TheCrocc** [comment]
And i've installed C++, Runtime, the BusDriver, restarted the windows several times...

**Comment by mika-n** [comment]
please see the pinned "Read this before posing an issue ticket" and provide
- Logfiles
- Windows Eventviewer log msg/error msg

**Comment by Ryochan7** [comment]
> And i've installed C++, Runtime, the BusDriver, restarted the windows several times...

Betting wrong architecture again. You need to install the Visual C++ Redistributable and .NET Runtime for the arch of the program archive you downloaded. Not sure why a lot of people just go for the x86 version just because it exists primarily for one person (Windows x86 tablet user). I am seriously considering just stopping releasing an x86 build entirely.

**Comment by TheCrocc** [comment]
You, my dear, is a freaking legend! Deleted all the x86 that came installed and instaled the x64 files, got it working perfectly! Thank you so much!!
