### ISSUE TITLE
DS4 Windows doesn't find latest vigem bus driver

### ISSUE THREAD

**Issue by Santos9PT** [Ryochan7/DS4Windows#2086]
So Since the previous update I have been getting issues such as the auto updater deleting ds4 windows.exe. I did download everything again but now it says this:

![image](https://user-images.githubusercontent.com/82978107/115635886-99c5b600-a304-11eb-82e8-9e34c70d5888.png)
 

I installed the newer one but the error stays the same, so I tried to install the 1.16 version and says this:

![image](https://user-images.githubusercontent.com/82978107/115635981-caa5eb00-a304-11eb-9350-e06a432b0e90.png)

I also tried unninstaling the driver from device manager as well but nothing changed. it still says that i have the 1.14 version

Anybody got any ideas?

Thanks in advance.

**Comment by Ryochan7** [comment]
Looking at some archived setup projects for ViGEm, it looks like the backend code for the installer returns a list of devices with the ViGEmBus GUID. I cannot find the code that checks the list contents but I am assuming that the installer looks through the list to find the latest version available and reports if a newer version of ViGEmBus was found. DS4Windows pulls the info for the first device that it finds. In an ideal setup, only one device with that specific GUID should exist.

Unfortunately, it really looks like other software, such as Parsec, just don't play nice. This problem seems to be coming up often enough that some other software has to be cramming in ViGEmBus 1.14.x on people's system even if a newer version of ViGEmBus is already installed. It would be nice to know the software project that is the culprit but I have not run into this specific problem myself.

I guess the next step would be to iterate over a list of possible devices like the ViGEm installer does and attempt to find a compatible device from the list. It looks like the ViGEm client library code would skip over any potential older versions of ViGEmBus.

**Comment by Kanuan** [comment]
@Ryochan7 I'm helping him on this right now. I'll try finding if he installed something before that forced the installation of the old vigemBUS.

On another note, in case you need, the [user friendly HidHide guide](https://vigem.org/projects/HidHide/Simple-Setup-Guide/) is live

**Comment by Ryochan7** [comment]
Never mind my original hypothesis. The VIGEM_COMMON_VERSION check does **not** seem to do the trick. The ViGEm client library is able to connect to ViGEmBus 1.14.1.0 just fine; I couldn't find a 1.14.3.0 archive anywhere. The new driver check will not do what I wanted after all. The older simpler driver check was more likely accurate in regards to which version of ViGEmBus the client library was actually connecting to.

**Comment by nefarius** [comment]
We have the good sir @Santos9PT on our Discord for diagnosis; it's the lovely fork HP made for their Omen notebooks ruining everything - yet again 🙂 

Once we know more I can help you with these version detection bollocks, so far we have Oculus and HP ruining the fun for all of us 😉

**Comment by nefarius** [comment]
Yep, we found it. Since the absolute brainlets over at HP didn't change any GUIDs when forking my work back in 2018 (driver development is hard, go figure...) the check in DS4Windows gets tricked and enumerates the forked version of the bus (which is horribly outdated and can even be even exploited but I digress) which is indeed stamped as version `1.14.3.3` and therefore on the incompatible list.

As much as I wish to throw the ball back into HPs support court where it belongs, I'm afraid it is yet again on us hard working folks who actually know what they're doing to come up with a solution/workaround 😉 (thanks again for wasting all our time, HP).

In the registry we drilled down to the key `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceClasses\{96e42b22-f5e9-42f8-b043-ed0f932f014f}` which is the device interface identifier used by the official bus and client lib and used for detection by DS4Windows. On HP Omen Laptop devices there is a 2nd entry present because HPs driver uses the same GUID (sorry for repeating myself, but, beginners mistakes *sigh*):

![image](https://user-images.githubusercontent.com/286631/115743882-5b76d800-a392-11eb-8248-7f3685865d0d.png)

**Delete the 2nd key** as a whole and DS4Windows will be happily detecting the latest version of the bus again 🥳 

This change will remain there until someone (or Windows Update) re-installs the HP driver but it seems like they don't update it anymore anyway so should be fine 😉

**Comment by Kanuan** [comment]
@ethanlefebv we are testing if having this enabled (see screenshot) makes the entry come back after a reboot. It's better to be safe and leave it disabled.
![image](https://user-images.githubusercontent.com/24910442/115753791-f3b09500-a371-11eb-9019-056a396fdd35.png)

It should be on the `System devices` section. To be certain that this is the correct one that must be disabled, you can double click on it and check if it's the `HP Omen Driver`

**Comment by nefarius** [comment]
If you use "View by connection" in device manager you can confirm that it is the correct one to disable by looking at the parent device, like: 

![image](https://user-images.githubusercontent.com/286631/115762417-bcf37280-a3a3-11eb-9bfa-5ddaa4651744.png)

**Comment by mika-n** [comment]
good finding. And just like you all I'm not surprised either that some global big brand company is not playing by the rules.

**Comment by Ryochan7** [comment]
Good artists copy. Great artists steal.

These findings are definitely interesting. Yet another case of a company taking from open source and screwing things up for everyone else. You think it would be much better to work with upstream and improve the mainline driver but they think they need their secret sauce. HP devs couldn't even give Nefarius a donation for the hard work put into ViGEmBus. Have to learn about their borked fork when things break.

As at least a temporary measure, I ended up having to change the ViGEmClient library code to attempt to enforce a minimum driver version number there. It uses mostly the same logic as the new ViGEmBus check in DS4Windows. The change seems to do the job although DS4Windows should probably display a better message when the bus version mismatch exception is thrown.  It is not a good workaround but it should hopefully guarantee that the library will always connect to the latest version of the bus.

https://github.com/Ryochan7/ViGEmClient/commit/843b1c83f8046b1ad4e7a59f758bbf8733922f1f

**Comment by Serfrost** [comment]
Wow, what a disaster. You'd think they would test their shoddy patchwork before shoving it onto the end user's devices.

HP, if you're reading this, this is the kind of ignorance that turns people away from a company. Word of mouth spreads fast.

**Comment by Masamune3210** [comment]
Unrelated, but believe me if they cared this stuff wouldn't be a thing. This is not the first nor will it be the last time HP has had issues with their crappy software causing issues for users

**Comment by Ryochan7** [comment]
DS4Windows 3.0.4 should hopefully be able to skip that ViGEmBus fork.
