### ISSUE TITLE
Controller # keeps changing after disconnect/reconnect

### ISSUE THREAD

**Issue by ayoits0913** [Ryochan7/DS4Windows#2090]
I'm using my DS4 wirelessly and I'm running into an annoying issue with my emulators. The controller # keeps changing after I reconnect the controller (when the 5 minute idle turn-off kicks in). So I have to go and change the number manually in Pokopom settings. How can I stop this from happening or assign a permanent slot for it?

**Comment by Ryusennin** [comment]
Have a look at the Output Slots tab.

Alternatively, use a USB cable. Every time your BT connection times out, something else in your OS locks the controller slot.

**Comment by Ryochan7** [comment]
Thanks to the discoveries documented in issue #2086, I am going to consider every ViGEmBus related issue invalid until the next version of DS4Windows. At least with the next version of DS4Windows, there should be more of a guarantee about which version of ViGEmBus that is actually being utilized. Potentially using a 3+ year old driver and suffering its problems cannot be worked around by DS4Windows.

**Comment by IceLancerSR** [comment]
Alright i will subscribe my self to this question until next release then. As i am not on hp laptop but since its also connected to vgem i guess. This is quite annoying issue. Some applications cant recognize gamepad any more once it changes controller #

**Comment by IceLancerSR** [comment]
> Thanks to the discoveries documented in issue #2086, I am going to consider every ViGEmBus related issue invalid until the next version of DS4Windows. At least with the next version of DS4Windows, there should be more of a guarantee about which version of ViGEmBus that is actually being utilized. Potentially using a 3+ year old driver and suffering its problems cannot be worked around by DS4Windows.

Ryochan7 
i found out what is causing this to happen. I am using ds4 V2 and in order to achieve working dualshock native with hidguardian i have to resort to : 
go on HIDNinja -> Remove the HID\VID_054C&PID_05C4 entry and reconnecting the controller, otherwise HIDGuardian will end-up hiding the emulated DS4v1
Once i do that, controller will start randomly to change ID on connect.

Can something be done in ds4 to prevent it from happening? and keep functionality of named above

**Comment by mika-n** [comment]
You should remove HidGuardian and switch over to HidHide tool (the same author, but HidHide is the next-gen hider device driver tool). The latest version of DS4Windows 3.x supports HidHide.

Anyway, if you really want to keep on using the old HidGuardian then you have to tweaks its settings by removing the 054C/05C4 from AffectedDevices (HidNinja tool can modify this setting) list IF YOU USE dualshock4 as an output gamepad type in a DS4Windows profile. The virtaul output DS4 device is seen as DSv1 device, so hidGuardian would hide it if you keep 054c/054c entry in HidGuardian settings. Leave just the DS4v2 HID identifier in AffectedDevices list. See this #720 about HidGuardian and DS4v1 conflict.

But, the recommended way these days is to uninstall HidGuardian (be careful to do it in a proper way or you may end up without keyboard and mouse and you have to fix that issue through recovery boot option) and to replace it with HidHide tool. See this: https://vigem.org/projects/HidHide/Simple-Setup-Guide/

**Comment by IceLancerSR** [comment]
> You should remove HidGuardian and switch over to HidHide tool (the same author, but HidHide is the next-gen hider device driver tool). The latest version of DS4Windows 3.x supports HidHide.
> 
> Anyway, if you really want to keep on using the old HidGuardian then you have to tweaks its settings by removing the 054C/05C4 from AffectedDevices (HidNinja tool can modify this setting) list IF YOU USE dualshock4 as an output gamepad type in a DS4Windows profile. The virtaul output DS4 device is seen as DSv1 device, so hidGuardian would hide it if you keep 054c/054c entry in HidGuardian settings. Leave just the DS4v2 HID identifier in AffectedDevices list. See this #720 about HidGuardian and DS4v1 conflict.
> 
> But, the recommended way these days is to uninstall HidGuardian (be careful to do it in a proper way or you may end up without keyboard and mouse and you have to fix that issue through recovery boot option) and to replace it with HidHide tool. See this: https://vigem.org/projects/HidHide/Simple-Setup-Guide/

I see. But from the looks of it. HidHide is a lot of manual work. I have entire library , massive one in my "arcade" for gaming using  front end, how am i suppose to hidhide every single one of them separately? Even if its default ON and i have to do it for games that accept DS4 natively its still a lot of work. And hidhide doesnt support recursive path only absolute from what i can see? That breaks my setup

**Comment by Kanuan** [comment]
It works exactly the same as HidGuardian. You are confusing things. You only have to:

- Hide the real controller
- Whitelist DS4Windows

Then, for all intentions and purposes, you will be left with only the virtual controller created/emulated by DS4Windows. If you want to use your DS4 as an actual DS4 with games that have native support you only have to create a profile in DS4Windows with DS4 emulation instead of Xbox.

**Comment by IceLancerSR** [comment]
> You are confusing things, it works exactly the same as HidGuardian. You only have to:
> 
> * Hide the real controller
> * Whitelist DS4Windows so it can: `see the real controller` -> `Create a virtual controller from it`
> 
> Then, for all intentions and purposes, you will be left with only the virtual controller created/emulated by DS4Windows. Besides that, you only have to create a profile in DS4Windows where the virtual controller is a DS4 if you want to use your controller as an actual DualShock 4 in games that have native support for it.
> 
> ## Edit 1
> I don't know about how absolute/relative paths work, so I can't comment.
> 
> I also remembered that the current version of DS4Windows whitelists itself when it detects HidHide is installed, so your only job is literally just marking your controller as hidden on HidHide's configuration client

Alright, that sounds ok. I was under the impression that i need to whitelist game exe's.
I'll try it now

**Comment by Kanuan** [comment]
You need to Add your controller to the hidden device list, DS4Windows doesn't do this automatically for you. Follow the guide to verify if your controller is correctly hidden

https://vigem.org/projects/HidHide/Simple-Setup-Guide/

**Comment by IceLancerSR** [comment]
> You need to Add your controller to the hidden device list, DS4Windows doesn't do this automatically for you. Follow the guide to verify if your controller is correctly hidden
> 
> https://vigem.org/projects/HidHide/Simple-Setup-Guide/

I didnt need to do anything. In log ds4windows said
 05/09/2021 17:08:14: DS4Windows not found in HidHide whitelist. Adding DS4Windows to list
and everything works fine. Now i just use auto profile to switch to dualshock

**Comment by Kanuan** [comment]
_Sigh_...
Yes, DS4Windows has added itself to the whitelist.
If you didn't manually add the controller to Hidhide's hidden device list then it is still visible.

You clearly don't understand how HidHide works nor how DS4Windows interacts with it. Everything is explained on the guide. I'll not comment further here.

If your problem is solved then I recommend you on closing this issue

**Comment by IceLancerSR** [comment]
> _Sigh_...
> Yes, DS4Windows has added itself to the whitelist.
> If you didn't manually add the controller to Hidhide's hidden device list then it is still visible.
> 
> You clearly don't understand how HidHide works nor how DS4Windows interacts with it. Everything is explained on the guide. I'll not comment further here.
> 
> If your problem is solved then I recommend you on closing this issue

Thats some anger there.
I understood perfectly how hidhide works. What u missed is that i am using Hide DS4 controler in ds4windows which works perfectly in sync with hidhide , making no need for any aditional steps.

**Comment by Kanuan** [comment]
> I did however left "hide DS4 controler" in ds4windows ON.

This option should not be used along with HidHide/HidGuardian. Not because it will _cause_ issues, but because it is redundant.
If HidHide is actually working, `Hide DS4 controllers` is not necessary

> I cannot close the issue. As it was not mine in the first place.

Oh, my bad. I got confused on this

**Comment by Kanuan** [comment]
> Redundant from your point of view?
> If i do not use Hide ds 4 controler it causes precisly the issue u described above, forcing me to do additional steps to ensure that controler is whitelisted.

As I said, you clearly don't understand how HidHide works nor how DS4Windows interacts with it

**Comment by IceLancerSR** [comment]
> > Redundant from your point of view?
> > If i do not use Hide ds 4 controler it causes precisly the issue u described above, forcing me to do additional steps to ensure that controler is whitelisted.
> 
> As I said, you clearly don't understand how HidHide works nor how DS4Windows interacts with it

And now u are just acting like ass. I am out.

**Comment by mika-n** [comment]
@IceLancerSR Please note that the "Hide DS4 Controller" option is considered as legacy option and at some point it was even under evaluation if the option should be removed from DS4Windows app. But it was left in because lots of people do use it and if and when it works then it is "one click" way to hide the physical gamepad from games.

But, this support forum is also full of posts from other people who complain that games see double inputs even when HideDS4Controller option is set or yesterday it worked, but not today. The fact is that HideDS4Controller option is veeeery fragile because of reasons beyond the control of DS4Windows app. See the following wiki page and especially _Applications known to cause problems with exclusive mode_ paragraph.
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

But, if the option works then great but be aware that even some Windows update may break it if some Windows app all in a sudden gets a gamepad support and the Win app is auto-launched on boot before DS4Windows app is launched.

Also, if "Hide DS4 Controller" option works then in most cases HidGuardian/HidHide is not required because HideDS4Controller option does the same. And the vice-versa if/when HidGuardian/HidHide is properly setup then there shouldn't be need to tick HideDS4Controller option because HidGuardian/HideHide does the same and those kernel level drivers are not that sensitive to other apps as HideDS4Controller built-in option is.

And whenever the documentation in DS4Windows wiki pages talk about HidGuardian then it is just an old doc and not updated. HidHide is recommended in place of HidGuardian.

Anyway, things started to work there because you uninstalled HidGuardian and it is no longer hiding the DS4v1 virtual output controller (when you use dualshock4 output mode in DS4Windows profile it is seen as DS4v1 gamepad). HidHide works a bit differently and it can hide gamepads per device instance (HidGuardian hides gamepads per device type, so it was all or nothing per device type).

**Comment by Kanuan** [comment]
@IceLancerSR  As mika-n said, the `Hide DS4 controllerd` options is a legacy option and can stop working for many reasons.

Since you have hidHide now, it's recommended that you disable the `Hide DS4 controllers` option and finish setting up HidHide according to the guide.

I think that the only step left for you to do is to open HidHide configuration client and mark your controller as hideen (represented by a red lock), then restart ds4windows
