### ISSUE TITLE
Mouse emulation jitter with Bluetooth

### ISSUE THREAD

**Issue by arcanechocolate** [Ryochan7/DS4Windows#2091]
When emulating mouse movement on any button on the Dualshock 4 while using bluetooth, the movement is jittered.
Tends to improve when using 125hz (but it's much less fluid as a consequence). Does not happen when using an exclusively wired connection.

It seems to happen with a certain cadence, related to poll rate. Higher sensitivity doesn't seem to make it happen more often. I've tried a variety of different settings and configurations. This issue has existed for years now and I only decided to post the issue now. I haven't tested J4K version, only this one.

Unfortunately it's extremely hard to see in the video below due to the skip happening for 1 frame only and not being captured in at 60fps.

https://user-images.githubusercontent.com/83123281/115959741-0069f000-a50e-11eb-947d-44d4de0022ca.mp4

This video is at 1/10th speed.

https://user-images.githubusercontent.com/83123281/115959985-4bd0ce00-a50f-11eb-8def-4437057684a2.mp4

[mouseBTjitter.txt](https://github.com/Ryochan7/DS4Windows/files/6369602/mouseBTjitter.txt)

**Comment by Mircosfot** [comment]
this is why i use steam for gyro aiming, it runs smooth. joystickmouse is also shaking like an earthquake with DS4W.

**Comment by arcanechocolate** [comment]
> 
> 
> this is why i use steam for gyro aiming, it runs smooth. joystickmouse is also shaking like an earthquake with DS4W.

This is not reddit nor your personal blog. If you're not going to add something related to the issue at hand, please refrain from posting. 

Much obliged.

**Comment by Ryochan7** [comment]
> this is why i use steam for gyro aiming, it runs smooth. joystickmouse is also shaking like an earthquake with DS4W.

Valve couldn't even get it right with their own Steam Controller. I have to use 3rd party software to actually use the Steam Controller to play games rather than have it act as a $50 paperweight. If Steam Input did what I wanted, this DS4Windows fork would not exist.

**Comment by Ryochan7** [comment]
@arcanechocolate Probably has more to do with isolated higher gamepad polls over BT than anything else. Poll rate is taken into account for the mouse routine so an outlier will make the mouse cursor move further than during other gamepad polls. Not sure if there is really much that can really be done about it. The issue seems fairly minor as I set the mouse speed high enough in profiles that the cursor spans the entire screen quickly. Like you, I don't get really any type of mouse jitter when using a USB connection either.

**Comment by Ryochan7** [comment]
Maybe more could be done if I wanted to take away all form of granularity like Mircosfot seems to like. Tested it again and Steam Input is still garbage. Very fixed ranges when it comes to analog stick to mouse translation. Also, it does **not** seem to take poll rate into account. The mouse cursor still hitches when using Steam Input but not as much. Don't expect aiming to be anything but garbage; can't even aim at desktop icons reliably.

**Comment by mateusmedeiros** [comment]
The same thing happens to me for a long time now. I've seen some few people having this problem here and there but it seems to be uncommon. One example of it is here https://github.com/Ryochan7/DS4Windows/issues/815 but I could swear I had seen another issue where the person said something about it not having the problem before and the problem appearing after update X.

But I'm not finding it anymore. Maybe it's a false memory. But anyway, I'm gonna try to install a plethora of older versions and see if I can make it work with some old version, and if I can, if I can pinpoint which version introduced that problem.

It drives me crazy whenever I'm playing anything more mouse-oriented, and in my case the jittery jumps are a little more pronunciated than in that gif, don't know why exactly, but it's definitely the exact same behavior.

**Comment by mateusmedeiros** [comment]
Ok, update on this. After testing lots of versions, here's what I found:

 1. I remember not having this problem on my previous PC some years and years ago
 2. I could still reproduce this going back all the way to version 1.4.100
 3. Jays' latest version, 1.4.52, has a SIMILAR problem probably with the same root cause but slightly different
 4. Maybe the aforementioned point 3 is why I remember not having the problem as mentioned in point 1. Because maybe I DID have the problem but didn't notice it before because with Jays' version I think it is slightly more subtle.

Basically, it goes like this, imagining that the cursor goes 1 coordinate point per 1/10 second to the right and every 2 seconds it stutters for 2/10 second. The behaviour with both versions will be something like this:


| time | coordinate on Ryo | coordinate on Jays |
|------|----------------------|----------------------|
|1/10s:|1|1|
|2/10s:|2|2|
|3/10s:|3|3|
|4/10s:|4|4|
|5/10s:|5|5|
|6/10s:|6|6|
|7/10s:|7|7|
|8/10s:|8|8|
|9/10s:|9|9|
|10/10s:|10|10|
|11/10s:|11|11|
|12/10s:|12|12|
|13/10s:|13|13|
|14/10s:|14|14|
|15/10s:|15|15|
|16/10s:|16|16|
|17/10s:|17|17|
|18/10s:|18|18|
|19/10s:|19|19|
|20/10s: (stutter happens here) |20|20|
|21/10s:|20|20|
|22/10s:|20|20|
|23/10s:|23|21|
|24/10s:|24|22|

So it seems the current version will still manage to track how much the analog stick was pressed, it only ceases to update the mouse movement from time to time. While Jays old version would truly stutter and after the stutter end go on exactly from where it was. I'm guessing that's what @Ryochan7 meant by `Poll rate is taken into account for the mouse routine so an outlier will make the mouse cursor move further than during other gamepad polls`.

Now, that may be why I didn't notice it with my old PC some years ago, but it may also be because there's something in the environment associated. Maybe a more powerful CPU will mask it better or something like that. Considering how rare it seem to be a problem for people even though it happens since very old versions, it may well be because of the environment. But maybe it's because most people don't use analog stick to mouse mapping on their profiles.

I'm willing to try my hands on the code if you can give me some insight on your hypothesis and if you have any slight attem[t on an idea of how it could be resolved, @Ryochan7, but if you really think there's basically nothing that can be done because of how devices are implemented on windows or something like that, then I'll just keep on living with that, I guess 😅.

**Comment by arcanechocolate** [comment]
@Ryochan7 Now that you're back on, maybe you'd like to look at this with a different perspective. 
As much as Steam Input has its flaws, it does execute mouse emulation with no hitches while on Bluetooth. It even does it while passing through DS4windows beforehand. But if I use DS4windows exclusively (BT), then it hitches when emulating mouse movement.
