### ISSUE TITLE
Wired DS4 light bar goes to sleep

### ISSUE THREAD

**Issue by ayoits0913** [Ryochan7/DS4Windows#2093]
This has only been happening for the past couple months but.. when I put my wired DS4 down and don't use it for a bit, DS4Windows seems to shut off the lightbar automatically. Idle disconnect is not active. I don't want it to go off, I want it on always. How can I fix this? I can't seem to find any option that correlates with this.

**Comment by Ryochan7** [comment]
The only way this would happen is if you use the Passthru mode for the lightbar in a profile. If that is the case, this is a non-issue as I cannot do anything about it. Not going to find the issue about it but ViGEmBus does not provide enough info in the DS4 feedback routines to accurately change the lightbar and rumble motors so DS4Windows has to perform some workarounds and guess. The routine does not always work depending on the game.

The next version of ViGEmBus will likely include a DS4 feedback mode that gives the entire DS4 output report rather than a subset of it like the current driver does. Not much do to until that happens.

**Comment by ayoits0913** [comment]
Sorry for not answering sooner, but It's not in passthru mode
