### ISSUE TITLE
Suggestion: Retire HidGuardian \ HidNinja \ Hide DS4 usage in favor of HidHide

### ISSUE THREAD

**Issue by Serfrost** [Ryochan7/DS4Windows#2096]
https://github.com/ViGEm/HidHide

Nefarius considers HidGuardian defunct, or at least discontinued. I'm also for that notion since it was rather tricky and beyond average end user experience levels to get it working efficiently, and also causing some rather serious problems if users tried removing it without first disabling what it was doing, which is something many may accidentally do.

HidHide is very easy to use in comparison, though it needs its future v1.1 update before I'd consider it a "click & done" setup.

The issue with the Hide DS4 option with DS4Windows is what we all know, many apps will take priority, even the Windows Store.  It may be better to just replace this with a button that opens HidHide to allow the user to then set the configuration that they want.

As Nefarius continues development on HidHide I feel this will be the better solution overall; of course, that's just my opinion.

**Comment by Ryochan7** [comment]
Already done in commit 60d9c768b42a8ba389396d13cad4dc141038491e. Just haven't put out a new release yet. HidGuardian will still be an option for a while but HidHide is the main supported driver going forward.

**Comment by Gianlucas94** [comment]
Hi,
I use the HidGuardian here. For using the HidHide i have to unninstal the HidGuardian drivers?

**Comment by Serfrost** [comment]
@Ryochan7 As always, yed're on te ball. Glad to have the confirmation. 

@Gianlucas94 I haven't used HidGuardian so I don't know the specifics, but you should definitely do a full uninstallation of it per HidGuardian's documentation before using HidHide.

**Comment by Serfrost** [comment]
@Gianlucas94 See: https://vigem.org/projects/HidHide/Simple-Setup-Guide/

**Comment by Serfrost** [comment]
@Ryochan7 I guess I should ask this now, but when you have a DS4Windows Release with HidHide in mind, will users need to do anything if they have HidHide already installed from Nefarius's repo?

**Comment by Gianlucas94** [comment]
> @Ryochan7 As always, you're on the ball. Glad to have the confirmation & thanks for your continued work. It's been invaluable for us over at Cemu with DS4 / DualSense / and Switch controllers being the most common choices for our end users.
> 
> @Gianlucas94 See: https://vigem.org/projects/HidHide/Simple-Setup-Guide/

Thanks, i'll wait the implementation of HidHide before unninstall

**Comment by Kanuan** [comment]
@Gianlucas94 If you want to use HidHide right now you just have to follow the guide that was linked to you.

R7's Windows native support just means it will do things automatically when it is implemented. Right now, HidHide has a simple user interface that will let you 1) Hide your controllers 2) Allow chosen apps to see hidden controllers (in this case, ds4windows.exe needs to be allow).

All is explained in the guide

**Comment by Gianlucas94** [comment]
@Kanuan, thanks i'll try it

**Comment by alidorani** [comment]
I did try using HidHide, but what I can't seem to get working is Steam recognising my DS4. Do I still need to rename the DS4Windows.exe for that to work? If so, I can't seem to find DS4Windows.exe.config to rename any longer.

**Comment by Kanuan** [comment]
> I did try using HidHide, but what I can't seem to get working is Steam recognising my DS4. Do I still need to rename the DS4Windows.exe for that to work? If so, I can't seem to find DS4Windows.exe.config to rename any longer.

You are mixing different issues.

Steam not recognizing DS4 controllers is not related to HidGuardian/HidHide/Whatever.

When Steam detects `DS4Windows.exe` is running it will ignore every DS4 controller in the system, real or virtual. You need to run DS4Windows with another `.exe` name to solve this one:
![image](https://user-images.githubusercontent.com/24910442/116822075-3d0f9a00-ab53-11eb-828f-34959ff9139a.png)

Also, Steam does not need to detect the DS4 controller for the games to detect it. How games detect controllers is unrelated to Steam (at least if `Steam Whatever controller support` is disable, at least). Steam not detecting DS4 controllers is only a real issue if the user wants to use Steam's big picture

**Comment by alidorani** [comment]
> > I did try using HidHide, but what I can't seem to get working is Steam recognising my DS4. Do I still need to rename the DS4Windows.exe for that to work? If so, I can't seem to find DS4Windows.exe.config to rename any longer.
> 
> You are mixing different issues.
> 
> Steam not recognizing DS4 controllers is not related to HidGuardian/HidHide/Whatever.
> 
> When Steam detects `DS4Windows.exe` is running it will ignore every DS4 controller in the system, real or virtual. You need to run DS4Windows with another `.exe` name to solve this one:
> ![image](https://user-images.githubusercontent.com/24910442/116822075-3d0f9a00-ab53-11eb-828f-34959ff9139a.png)
> 
> Also, Steam does not need to detect DS4 controllers for the games to detect it. How games detect controllers is unrelated to Steam (at least if `Steam Whatever controller support` is disable). Steam not detecting DS4 controllers is only a real issue if the user wants to use Steam's big picture

OK, I knew I was a bit confused but holy cow. I've been driving myself crazy trying to wrap my mind around all of this.

Thank you so much for clearing that up!

**Comment by mika-n** [comment]
Writing a troubleshooting documentation is highly overrated:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

**Comment by Ryochan7** [comment]
Clicking the `?` button to the right would have popped up a window that would mostly explain that problem.

**Comment by Ryochan7** [comment]
HidHide support in DS4Windows is now a thing with version 3.0.4

**Comment by alidorani** [comment]
> Writing a troubleshooting documentation is highly overrated:
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

I did read that though, but I was still confused. I knew what that box did, I just didn't know that the two issues weren't related at all and that the controller infact did work even though it didn't show up in Steam.

Furthermore, the below part is still something I can't find in my DS4Windows folder.
![image](https://user-images.githubusercontent.com/7832145/117167140-49039200-adc7-11eb-8d81-f02183068614.png)

**Comment by Gianlucas94** [comment]
Thanks, it's perfect!

•	Immediately issue unplug of all virtual controllers when pressing main Stop button - This mean that now will stop the problem with the controller getting slot 2 when disconnects on idle?

**Comment by Ryusennin** [comment]
@Alidorani That file doesn't exist anymore in DS4Windows 3. The wiki has not yet been updated.

**Comment by alidorani** [comment]
> @alidorani That file doesn't exist anymore in DS4Windows 3. The wiki has not yet been updated.

That makes sense :-)

**Comment by mika-n** [comment]
Jep. The DS4Windows.exe.config file was for .NET 4.x apps, but now when DS4Windows 3.x uses .NET 5.x version the similar file is DS4Windows.runtimeconfig.json

**Comment by Yohoki** [comment]
@Ryochan7 , did you remove the Ex-Mode toggle in 3.0.4? I haven't gotten an update prompt yet, so I'm still on 3.0.3 with HidHide running now and it MAY still be necessary to use hide ds4 even with hidhide configured. I'm gonna go ahead and update and see if this still happens on the newer version.

I've started noticing that some of the real DS4 inputs are being leaked out somehow in various Windows system apps (Control Panel, Bluetooth Window, Start Menu, ect.) . The Ex-Mode seems to have fixed this leaking, in combination with HidHide. But I also got a "Windows needs restarted" message when I turned on ex-mode, so that may be why it's stopped leaking, as well. I'll have to try a few things out and see what causes/fixes it.

The things I'm noticing is:
D-pad moves highlighted item (mapped to arrow keys in my profile, so may be working correctly...)
L-Stick moves highlighted item (Mapped to mouse control, menus should not see the L-stick)
X Button clicks highlighted item regardless of mouse location{hits enter key} (Mapped to L-click, causes some menus to do both option, if also clicking a menu item)

I'm also not entirely sure if this is HidHide leaking the input, or something to do with D4W's virtual gamepad. I wouldn't even know how to begin figuring that one out. Either way, at least with HidHide now, enabling ex-mode should be much easier.

**Comment by reyaz006** [comment]
I'm sorry for unrelated and stupid question. And it's again about Windows 8.1.

It was great to discover that at some point after the situation with ViGEmBus the decision to drop older version support was revised. Now, I'm confused about this HidGuardian situation.

I *think* I didn't have HidGuardian installed anyway. But somehow I assumed that it's required for the "Hide DS4 controller" feature. I've now installed 3.0.8 and it doesn't seem to have any issues. I know I need to keep this option enabled for convenience with most games. But now I'm not sure why it still works for me, even though I don't have HidGuardian or HidHide installed (both require Windows 10). Can someone explain what's wrong with my interpretation?

**Comment by Kanuan** [comment]
> I think I didn't have HidGuardian installed anyway. But somehow I assumed that it's required for the "Hide DS4 controller" feature.

There are 3 ways to "hide" a controller from the system in a way only DS4Windows has access to it:
- `Hide DS4 Controllers` option in the settings tab (can fail to actually work for many reasons and it's not recommended to be used)
- HidGuardian (Obsolete because of HidHide unless you are not on Win10 or are using a x86 system)
- HidHide (x64 Windows 10 only for now)

Of the 3 options, you must use only 1 at a time. If you have HidGuardian/HidHide, you don't need to use the `Hide DS4 Controllers` option since it's redundant (why do you want to hide the controller _again_  if it's already hidden?)

**Comment by reyaz006** [comment]
Alright thanks, I understand now. But why `Hide DS4 Controllers` can fail? I can imagine issues with privileges but I'm running DS4Windows under admin anyway.

**Comment by Kanuan** [comment]
> Alright thanks, I understand now. But why `Hide DS4 Controllers` can fail? I can imagine issues with privileges but I'm running DS4Windows under admin anyway.

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by Ryochan7** [comment]
I would have been fine leaving HidGuardian support the way it was for a while longer. It was mainly a recent thread that included the same misinformation that I have seen many times over that made me pull the plug. HidHide is a much better tool for the job and it is much simpler to use anyway.

In the case of compatibility, it is really sh*tty to try to work against Microsoft's bad business decisions. Microsoft has pretty much already killed Windows 8.1 before its EOL date due to driver signing policy changes. Windows 10 is really the only version of Windows that will likely receive any form of driver updates after this year. Anyone still using Windows 8 should probably have already updated to Windows 10. Windows 7 users would be the most affected by pulling the plug on HidGuardian support.

**Comment by Kanuan** [comment]
> I would have been fine leaving HidGuardian support the way it was for a while longer. It was mainly a recent thread that included the same misinformation that I have seen many times over that made me pull the plug. 

@Ryochan7 could you elaborate on what was the misinformation? Even though there is no more support for HidGuardian anymore, I'd like to know what was that, specially if it was my fault.

**Comment by Ryusennin** [comment]
Not sure who's responsible (doesn't really matter) but HidGuardian's removal has been the final nail in Win7's support. DS4W 3.0.6 is the last usable version for this OS. A notice should probably be posted to warn legacy users.

Incidentally, I think it doesn't make any sense to maintain support for ViGEm 1.16 in DS4W 3.0.7 and later, considering this version of ViGEm is only useful on Win7. No point in supporting it anymore on Win10.

**Comment by Yohoki** [comment]
> Of the 3 options, you must use only 1 at a time. If you have HidGuardian/HidHide, you don't need to use the `Hide DS4 Controllers` option since it's redundant (why do you want to hide the controller _again_ if it's already hidden?)

They aren't necessarily redundant. In fact, there are certain programs that HidHide DOESN'T block, like the start menu and control panel. Using Ex-mode WITH HidHide seems to work just fine for blocking these rogue apps from getting raw controller inputs instead of virtual, and HidHide (at least on my end) has kept the "Failed to gain exclusive access" error from popping up. The two options are playing nicely together so far, and don't actually affect eachother if HidHide is set up correctly.

**Comment by Ryochan7** [comment]
Things like this happen when you take the fun out of the project
