### ISSUE TITLE
Screen savers do not turn on and monitor(s) do not turn off when Output slots are marked as DS4 (Permanent)

### ISSUE THREAD

**Issue by Andre87811** [Ryochan7/DS4Windows#2098]
When ds4windows app is running, it won't let Windows turn off the monitors after the PC screensaver turns on. I tried changing various settings like hide ds4windows and that didn't help. Only when ds4windows is exited/stopped is when Windows will turn off the monitors when the machine is idle and the monitors are supposed to turn off.

**Comment by Andre87811** [comment]
Upon further examination it appears the issue is tied to the configuration under "Output Slots" tab. When a controller is marked Plugged and marked as Permanent then it doesn't let the monitors turn off during standby.

**Comment by Newtype14** [comment]
Don't know if this is going to help you with your issue, but I'll put this out there just in case.
I had a problem where my PC refused to sleep/hibernate. I eventually discovered a neat command that tells you which program(s) currently running are preventing your PC from powering down. Open a command prompt and type: powercfg /requests

I guess another possiblity is that when your controller is connected, it's somehow moving the mouse cursor just slightly? It's enough to prevent the monitors from sleeping.

**Comment by Andre87811** [comment]
Nope, I correctly identified the issue. It is exactly how I described it.

**Comment by mika-n** [comment]
What options you have in OutputSlots? Post a screenshot of it.
If an outputSlot type is "permanent" then the virtual output controller is kept alive even when the physical gamepad is disconnected (some games need this because some crappy games don't support hotplug controllers). Anyway, could be a windowsOS thing to think the system is active when a gamepad is in connected state.

**Comment by Andre87811** [comment]
In this scenario, they are all marked as dynamic however sine are marked as Plugged in. Please see attached for the screenshot. 

![image](https://user-images.githubusercontent.com/57190373/116904139-91ba2000-abfa-11eb-82fb-c7769fba9515.png)

**Comment by Andre87811** [comment]
Actually this issue prevents the screensaver from turning on. Is it possible for there to be a patch to fix this?

**Comment by mika-n** [comment]
in wonder if the first slot in the screenshot (the line with "Empty - DS4" column values)  has a persistent slot type because the row shows DS4 even when the physical gamepad for that slot is disconnected (empty).

**Comment by Andre87811** [comment]
Here are a couple of screenshots of each line

![image](https://user-images.githubusercontent.com/57190373/117510073-a4a95900-af48-11eb-89d3-24390041c485.png)
![image](https://user-images.githubusercontent.com/57190373/117510099-affc8480-af48-11eb-8a99-ff77a07befc4.png)

**Comment by mika-n** [comment]
the second slot seems to have "Permanent" option, it means that even when a physical gamepad is disconnected then the virtual output controller is left as "connected" because some games don't like hotplugged devices. This may have side effects with screensavers.

But why two rows with DS4 in the Current column? Do you have two controllers?
Logfiles?

**Comment by mika-n** [comment]
Try setting all slots in OutputSlots as "Dynamic" instead of "Permanent" if it solves the issue. However, then due to some crappy games some games may have problems if the BT connected gamepad dies (battery 0%) or it is idle disconnected in the middle of the game session. When you re-connect the gamepad those crappy games may not see the gamepad until you reboot PC.

This is partly due to some issues in WindowsOS level (nothing DS4Windows app can do about it). And sometimes ViGem virtual gamepad driver may assign gamepadID 2 instead of re-using the gamepadID 1. See old tickets about "ghost gamepads" #1163
