### ISSUE TITLE
DS4 v.2 makes clicking sounds when connected to bluetooth, and acts differently when connected via USB

### ISSUE THREAD

**Issue by joms5** [Ryochan7/DS4Windows#2100]
My controller works perfectly fine with DS4windows when plugged in via USB. 
However when I connect via Bluetooth and try to use DS4windows, my controller's speakers turn on and off about every second. 
if connected to my computer via BT and DS4windows isn't running or is stopped, the speakers don't make noise.
The lightbar does weird stuff only when connected to BT (won't go completely dark, flickers)

I've noticed I can make the speakers turn on and off if I edit the lightbar settings on DS4windows.

Also that when connected via BT DS4windows recognizes this controller as "DS4 v.2" but when plugged via USB it reads the same address but "DS4 v.1"

Here's a video of me messing with the lightbar settings and the resulting sounds made.
https://imgur.com/gallery/OvcfEsR

The controller is cheap, which I'm assuming might be the problem

[ds4_4_29.txt](https://github.com/Ryochan7/DS4Windows/files/6402507/ds4_4_29.txt)

**Comment by mika-n** [comment]
The logfile shows that DS4Windows fails to read data from the gamepad over BT.
`04/29/2021 21:20:13: 98:B6:E9:AB:81:3A disconnected due to read failure: 997`

Often these cheap chinese copy-cats are not fully 100% compatible in BT mode. Often those work just fine over USB, but BT is a completely different story. Sure it might be possible to support every kind of 3rd party copy-cat over BT but someone with an actual hardware should debug how the BT communication works with the copy-cat compared to genuine DS4 BT communication.

**Comment by Serfrost** [comment]
If you're not using the Speakers for anything yourself, which I would assume is probably the case... then you can try [disabling] the speaker component in Window's Sound settings (Win Key + Search: "Change system sounds" --> Playback tab); but this will only work if the device is shown as an output device.

If it that works, then it's probably your best solution, even if it isn't an ideal one.  Otherwise, the same as mika-n described.
