### ISSUE TITLE
I can't have two controllers connected at the same time via bluetooth

### ISSUE THREAD

**Issue by LeonSK1512** [Ryochan7/DS4Windows#2101]
I play with a dualsense controller always connected by bluetooth, but when I try to connect a second controller, in this case it is a dualshock 4 v1, it disconnects immediately, why does this happen?

Log:
04/29/2021 21:43:42: DS4Windows version 3.0.3
04/29/2021 21:43:42: DS4Windows Assembly Architecture: x64
04/29/2021 21:43:42: OS Version: Microsoft Windows NT 10.0.19042.0
04/29/2021 21:43:42: OS Product Name: Windows 10 Pro
04/29/2021 21:43:42: OS Release ID: 2009
04/29/2021 21:43:42: System Architecture: x64
04/29/2021 21:43:42: Running as Admin
04/29/2021 21:43:43: Starting...
04/29/2021 21:43:43: Connection to ViGEmBus 1.17.333.0 established
04/29/2021 21:43:43: Searching for controllers...
04/29/2021 21:43:43: Using Exclusive Mode
04/29/2021 21:43:57: Found Controller: 4C:B9:9B:51:5C:66 (BT) (DualSense)
04/29/2021 21:43:58: Plugging in virtual X360 Controller
04/29/2021 21:43:58: Associate X360 Controller for input DS4 #1
04/29/2021 21:43:58: Controller 1 is using Profile "DualSense". Battery level is 87%
04/29/2021 21:44:16: Found Controller: 84:17:66:89:51:63 (BT) (DS4 v.1)
04/29/2021 21:44:16: Plugging in virtual X360 Controller
04/29/2021 21:44:16: Associate X360 Controller for input DS4 #2
04/29/2021 21:44:16: Controller 2 is using Profile "Default". Battery level is 62%
04/29/2021 21:44:27: 84:17:66:89:51:63 disconnected due to read failure: 997    (This is when the control disconnects, every time I try to connect it)
04/29/2021 21:44:27: Gamepad data write connection is lost. Disconnecting the gamepad. LastErrorCode=0
04/29/2021 21:44:27: Disassociate X360 Controller for input DS4 #2
04/29/2021 21:44:27: Unplugging virtual X360 Controller
04/29/2021 21:44:27: Controller 2 was removed or lost connection

I really want to be able to play with both controllers connected by bluetooth, it is difficult for me to have them connected by usb, please help

**Comment by Masamune3210** [comment]
You might be overloading your bluetooth adapter, are you using a USB adapter or one built into your computer

**Comment by LeonSK1512** [comment]
> You might be overloading your bluetooth adapter, are you using a USB adapter or one built into your computer

I use bluetooth integrated in a motherboard MSI MPG Z490 GAMING CARBON WIFI

**Comment by SeRoM** [comment]
Hello, 

I have described a similar problem [here](https://github.com/Ryochan7/DS4Windows/issues/2095), but with a headset as a second device.
I also use bluetooth integrated in a motherboard.
My old DS4 has never overloading my bluetooth adapter. 
it happened since i use a DualSense ...

**Comment by three36ixx** [comment]
I am having the same issue. Both controllers have different bluetooth identification numbers! I can sync them up in windows just fine. Both display a white bar simultaneously. If both of them are turned on and I open ds4windows, one of them immediately turns off and the other connects to ds4windows. Trying to turn on the second controller results in an endless blinking white led until it stops from not being able to connect.
I did not have this issue prior to upgrading my motherboard, processor, and ram. My current motherboard is the Asus TUF Gaming X570 Plus WiFi. I am using the built in bluetooth, just like I was on my other motherboard Asus Z87 Pro. PLEASE HELP XOXO :)

**Comment by three36ixx** [comment]
Before I wrote that. I did a few things...Delete the game controllers from device manager\Human Interface Devices. Removed them and resynced in Windows 10 Bluetooth Settings. Then I downloaded jayz2kings ds4windows, installed their driver, but only one would connect at a time! Closed that program.. Opened up ryochan's version. And kept trying to connect via bluetooth. I have not plugged them in via usb once!
But, now they are both connecting to ds4windows! I don't know what I did explained above that would have fixed it. Must be magic!

**Comment by three36ixx** [comment]
![image](https://user-images.githubusercontent.com/74925665/116751069-7b7d4b80-a9d1-11eb-99fd-119be762d33e.png)

**Comment by Masamune3210** [comment]
I'm not sure that running the old version did anything at all if at least nothing good. It uses an entirely different driver to talk to controllers. You probably just had a wacked up entry for your controller and removing the controllers let windows regenerate them

**Comment by three36ixx** [comment]
well if jayz2kingz version did the same thing, it was obviously a windows issue that is no longer effecting me. regardless, it works now. i am happy. thanks for your input @Masamune3210

**Comment by LeonSK1512** [comment]
I still have the same problem, but apparently it has a lot to do with the bluetooth integrated in the motherboards, I used an ASUS bluethooth 4.0 dongle and I managed to connect both controllers at the same time but they have high latency.
I will keep waiting for a definitive solution to the problem with the integrated bluetooth.

**Comment by three36ixx** [comment]
Well after reinstalling ryochan's drivers, I am back to square one! Noticed the latency was 4-5ms when set to 1ms with 1 or 2 controllers turned on. That seemed odd because I was getting 1ms before with a single controller before I attempted to fix this. There's no reason for this to be happening. My old board was using integrated bluetooth and I was getting updates for ryochan's revisions as time went on. I upgraded my hardware in November, 2020. I repeat, both motherboards are Asus. Both boards were/are using integrated bluetooth.

**Comment by three36ixx** [comment]
I must add that my old 4th gen i7 motherboard would have both controllers operating at 1ms - 2ms simultaneously.

**Comment by Masamune3210** [comment]
Thats weird, im officially out of my scope here, might have to wait for someone more official to help you sorry

**Comment by Kanuan** [comment]
There are some misconceptions around here:

- There are no "drivers" used for controller communication. Ryochan7 and Jays2kings versions of DS4Windows communicate with the controller directly through the standard Windows Bluetooth stack, no random drivers necessary
- The drivers you are actually talking about are the ones used to create virtual Xbox 360/DualShock 4 controllers. Jays2Kings use the obsolete `ScpVBus` and Ryochan7's use `Nefarius Virtual Gamepad Emulation Bus` (or just `Nefarius ViGEmBus`). They are not directly related to how DS4Windows communicate with the controllers. The communication flow is more or less:

`Bluetooth Controller` <=> `Default Windows BT stack` <=> `DS4Windows` <=> `ViGEmBus`

Though DS4Windows does send from the Virtual Controllers created by ViGEmBus back to the controller (Rumble commands, lightbar info if `lightbar passthrough` is activated), ViGEmBus cannot influence controller latency.

What can actually influence the latency is:

- __Bluetooth/Wifi interference: they both use the same frequency:__ Though they should auto adjust to prevent interference, sometimes it just happens. Check if your area isn't overloaded with different 2.4Ghz WiFi networks and bluetooth devices
- __Integrated Bluetooth in laptops/Cheap BT dongles:__ it's quite common for laptops to have shitty BT adapters, mostly because they are inside the laptop's shell, the same card doubling as both Wifi/BT or they just being overrall. They generally have short range and can't maintain the minimum data rate necessary when connecting more than 1 controller
- __DS4Windows/ViGEm spamming commands back to the controller:__ DS4Windows by itself, or when instructed by ViGEmBus, will send data back to the controller. There's a data rate limit your BT adapter can send to the connected devices, if DS4Windows were to send too much data at short periods of time to the controller this can cause the latency to spike. In my tests with 4 connected controllers and a cheap $5, 4.0 BT Dongle from AliExpress the latency never went over 10ms on normal playthroughs. Consider this a edge case and not a common occurrence.

If before, when using your integrated BT adapter, you never had latency issues and now you have, then:

- You may be having more interference in your BT connection. Try doing tests with your laptop's Wifi __FULLY__ disabled
- Some DS4Windows update caused it to increase the rate of commands it sends back to the controller and now your adapter can't keep up with the pace (unlikely)
- If making tests with a USB BT dongle, remember to disable the laptop's Wifi __and__ integrated BT dongle before connecting the new one. Windows can only use 1 BT adapter at a time and will default to the previous activated one

**Comment by Ryochan7** [comment]
I am going to assume it is a BT dongle problem. I can have 4 Bluetooth controllers connected to DS4Windows with no problems. I had an older BT 2.1+ adapter that only worked full speed with 1 controller connected. My current BT 4.0 dongle does not have that problem.
