### ISSUE TITLE
Controller connects to windows but not DS4 program

### ISSUE THREAD

**Issue by buner7** [Ryochan7/DS4Windows#211]
Just got a DS4 controller for use with PC but i'm having trouble connecting it with DS4Windows. It connects with a usb connection and works fine but i can't get it to work with bluetooth. I pair the controller with the PC but it never shows up in DS4Windows. I have tried everything I can find but with no luck. Also it does not ask for a pairing code but it seems to be paired with windows.
I am running windows 7 64bit. have an official SONY controller and am running the most recent version of the software from here. 1.4.109 i think? please help with any suggestions on what i can try

Edit1: I have now read that some people had trouble with motioninjoy DS3toolkit interfering with the DS4 controller. I had previously used a ds3 controller on this PC so i uninstalled that toolkit but as far as I can tell but it did not seem to help. Thought i would just add that info here in case that is helpful.

**Comment by kmcgurty** [comment]
I have had success installing [InputMapper HidGuardian](https://inputmapper.com/downloads/download/5-tools/76-inputmapper-hidguardian) and running DS4 as admin. I'm able to press the PS button, the remote flashes, connects to windows and then connects to DS4 (the light bar changes from a light blue to the one I have set). Version 1.4.110 seems to add something about HidGuardian, but I'm not sure if that's a fix or not.

**Comment by Ryochan7** [comment]
I am not familiar with how motioninjoy works exactly but I would recommend that you use either ScpToolkit (deprecated) or Fireshock for using a DS3 on Windows. With either one, there might be a conflict when trying to use a DS4 though. You would probably have to disable or remove the utilities in order to use a DS4 on DS4Windows; I had played with ScpToolkit a little bit but I cannot remember how everything was set up.

Another thing that you can check is the Device Manager. Make sure that the HID game controller is visible and has not been disabled. That would be one reason why the DS4 works when connected via USB but not via Bluetooth. Also, check if the controller is visible in the Game Controller Settings window from Devices and Printers in the Control Panel.

There were no fixes in version 1.4.110 regarding HidGuardian. There are just a few extra links in the Settings tab that can help with managing HidGuardian. They are fairly simple. A base template AffectedDevices file can be written to the registry, any possible stale whitelist registry entries can get deleted (I need this especially while debugging and have to kill DS4Windows), and a shortcut to open the HidGuardian registry keys in Regedit.

**Comment by buner7** [comment]
Been still trying to get it to work and i have gotten to the point where ds4windows recognizes it for only a moment then the controller disconnects from bluetooth completely. I have tried charging it, restarting the computer, resetting the bluetooth and using different ports for the usb adaptor. This is what the log shows when this happens. It appears that the controller itself even turns off when this happens. Any ideas on things I could try?
![ds4 pics1](https://user-images.githubusercontent.com/36172108/35995896-c9dab32e-0ce2-11e8-833c-58c899f7675d.PNG)

**Comment by buner7** [comment]
Also when plugged in, now it only works as a touchpad/mouse the buttons don't seem to register

**Comment by buner7** [comment]
I have absolutely no idea why this worked but this youtube fix helped and i have it working with BT right now. thanks for helping I'll let you know if it keeps working haha

https://www.youtube.com/watch?v=N7DUV4T8744

**Comment by Ryochan7** [comment]
That is very strange. Thanks for posting the link to that video.
