### ISSUE TITLE
DualShock 4 emulation not working over bluetooth

### ISSUE THREAD

**Issue by Lombra** [Ryochan7/DS4Windows#2123]
**Describe the bug**
Applications receive no input when DualShock 4 emulation is used together with bluetooth.

**To Reproduce**
1. Use DualShock 4 emulation.
2. Connect using bluetooth.

**Screenshots and Logs**
[ds4windows_log_20210509.12.txt](https://github.com/Ryochan7/DS4Windows/files/6447742/ds4windows_log_20210509.12.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualShock 4 v2
 - OS: Windows 7 Ultimate 64 bit
 - DS4Windows Version: 3.0.4 (updated from 2.1.19 in an attempt to solve)

**Additional context**
I have been testing with ManiaPlanet (Trackmania 2) not on Steam. Steam not running. **Input works as intended when using either wired connection or Xbox emulation.**

DS4Windows seems to recognise the controller. Lightbar color changes according to profile, and controller readings work. Touchpad mouse control works. Output slot 1 is active.

HidGuardian is enabled, and using custom executable name.

Does seem to work in Steam big picture, and even when DS4Windows isn't running, which I thought shouldn't work given HidGuardian. Something gone wrong there?

I've had this working before on this same system. Not sure what I've done this time.

![bild](https://user-images.githubusercontent.com/8340020/117577032-68acfa00-b0e8-11eb-9aa3-76fb1ea7be6b.png)
![bild](https://user-images.githubusercontent.com/8340020/117576875-c260f480-b0e7-11eb-859d-8b718f70ac8c.png)

**Comment by Kanuan** [comment]
The issue is that, the way your HidGuardian is configured, it is hiding USB DS4v1 controllers. When DS4Windows emulates DS4 controllers, they are virtual USB DS4v1.

I would suggest you to use HidHide (HidGuardian's successor), since it does not have this issue and is waaay easier to use. But it is only for `64 bits Windows 10` for now.

To fix this on your current setup, remove every entry that has __exactly__  `VID_054C&PID_05C4` somewhere on it, then it will work again.
The major problem with this is that, if you have a real DS4v1, when connecting it via USB it will not be hidden anymore.

I strongly recommend you on updating to 64bits Windows 10 so you can:

- use the latest version of Vigem
- Replace HidGuardian with HidHide

**Comment by Lombra** [comment]
Ahh, that was it. Thank you!

I probably had HidGuardian configured correctly at first, but at some point I tried reapplying the default values to see if that fixed anything. So maybe something else was the issue originally...

I now only have this identifier Hid guarded: (added it after submitting this issue)
`HID\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&09cc`

I do intend to install Windows 10 on my new PC, as soon as components are available to build one. :)
