### ISSUE TITLE
Gyro/ Mouse joystick shacks like an earthquake

### ISSUE THREAD

**Issue by Mircosfot** [Ryochan7/DS4Windows#2130]
When i set my Gyro to Mouse joystick, every movement goes shaki. testet with bluetooth

**To Reproduce**
1. Go to Gyro
2. Click on output mode
3. Scroll down to mouse joystick

even tried the filters without succsess.  

steaminput  works very well.

**Screenshots and Logs**
this problem is not an error, it is a bug

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 and Dualsense
 - OS: [e.g. Windows 10 Pro Build 20H2]
 - DS4Windows Version [e.g. 3.0.4] latest

**Comment by Ryochan7** [comment]
> steaminput works very well

Need a Maury Povich gif here. The lie detector determined that was a lie.

Mouse-like Joystick does not even work for the most part in Steam Input. Even RambleTan videos show that and he has gone through some of its major limitations. It does not help that Steam Input still does not scale axes properly after all these years. It uses a range of [-32767, 32767] rather than the full range of [-32768, 32767]; that one extra unit in the neg direction really matters in some games.

Other than increasing the dead zone, it is likely just a matter of decreasing the set anti-dead zones for each axis. Unless a game absolutely refuses to work with mixed input, I wouldn't even use Mouse Joystick. The Halo Master Chief Collection was the main game that I had to use Mouse Joystick .

**Comment by Mircosfot** [comment]
Edit: after 10 times plug/unplug my BT Dungle it works now without any problems. was my fail, sry
