### ISSUE TITLE
Norton Security reports a Trojan while updating

### ISSUE THREAD

**Issue by internetvertipper** [Ryochan7/DS4Windows#2134]
**Describe the bug**
As I was clicking on the update button Norton showed up and reported, that the program wanted to install trojan2.exe and removed the data, but installed anyway

Desktop:
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [Windows 10 Pro Build 20H2]
 - DS4Windows Version [ 3.0.3/3.0.4]

**Comment by Ryochan7** [comment]
Going to assume it is a false positive until proven otherwise. With VirusTotal, the worst I have seen from some anti-virus engines is suspected ad-ware and that has been a noted false positive on StackOverflow; can't recall the Gen title given for it. More of this seems to have popped up since the move to .NET 5 and specifically for x86.

Kaspersky, ClamAV and Windows Defender cannot find anything on my end. Running ClamAV on Linux doesn't find anything either. Need to get more RAM in my PC so I can actually run a Windows 10 VM.

I cannot look into this further right now. I will not be back home to use my Windows PC until probably late Sunday.

**Comment by re11ding** [comment]
Same happens with Malwarebytes. Being opensource, it's obviously not malicious, but at least pointing out the false positives is important.

**Comment by mika-n** [comment]
there is not much DS4Windows app can do about those false positives

**Comment by Ryochan7** [comment]
I'll look into this when I get home in a few days. One test is going to be compiling the last DS4Windows 2.x code and see if the result is differ with .NET Framework 4.8.

**Comment by Ryochan7** [comment]
Looked into this some. VirusTotal does not complain about an x86 build when compiling the old `netframework` branch code under .NET Framework 4.8. As far as the latest code is concerned, I have narrowed down that VirusTotal mainly complains about the bundled **api-ms-win-crt-runtime-l1-1-0.dll** file included in the main program. That file is a part of the Visual C++ Redistributable x86 package. It looks like pretty much any .NET 5 (or even older .NET Core) app is going to bundle that file.

Based on some reports, it looks like other programs bundle the same version of the file. At least DS4Windows is not alone in this issue. I uninstalled Visual C++ Redistributable x86 and reinstalled. I ended up breaking .NET desktop application project support in Visual Studio and having to fix that. It didn't matter.

https://www.virustotal.com/gui/file/4adff24cfea9d01a4b0feb1616b601123aae66f937189191a3ea85b964797b91/detection

https://strontic.github.io/xcyclopedia/library/api-ms-win-crt-runtime-l1-1-0.dll-AA4ECF393C106E9687B7BB8AB91BB431.html
