### ISSUE TITLE
Ds4 Doesn't Have audio Output

### ISSUE THREAD

**Issue by Zi-zo** [Ryochan7/DS4Windows#2141]
Hey everyone.
here we go shortly.
So Today I read about this titles (DS4windows has no audio , ...)
I saw 2 or 3 issues like this in git but even if they had (?!) solution ,it didn't work for me.

My problem is I don't have the (Wireless pad) Option in the (Select device output).
I tried use Both Ryochan and Jays2King versions of DS4.

I think there is some thing wrong with the Realtek HD Audio manager , I don't know maybe not

Did anyone have this issue solved or can anybody help me ?

**Comment by Kanuan** [comment]
You need an official sony's DualShock 4 version 2 (the one where you can also see the lightbar through the touchpad) and it needs to be connected over USB. It's a default function of the controller, switching between ryochan7's and jays2kings is unrelated to it

**Comment by Zi-zo** [comment]
In 2017 I connected a Dualshock (ps4) through (Bluetooth)??!! and i had
sound from it's jack

Believe me I am not using ps1's pad

Anyway thanks for attention(xd)

**Comment by Ryochan7** [comment]
Apart from the needless berating, this issue is mostly just blatant misinformation.

At least based on my experience, Windows used to detect a Wireless Bluetooth audio interface along with the Wireless Controller interface when trying to pair a DS4 sometimes; later Windows 10 updates made it so it would only show the Wireless Controller interface while attempting to pair a DS4. Windows 10 would never connect to the audio interface though. Even if Windows were able to connect to it at some point, you would likely have to choose between Bluetooth audio or the controller; both would likely not work at the same time when connected to one Bluetooth adapter.
