### ISSUE TITLE
DS4 v.2 connects only via first setup in Settings app

### ISSUE THREAD

**Issue by iArti** [Ryochan7/DS4Windows#2142]
I'm using latest Ryochan7's DS4Windows (3.0.5) on latest Windows 10 build (19042) on my Acer Laptop with in-built Bluetooth.
I have a problem - DS4Windows detects DS4 only when it was first setup via Settings app (Bluetooth -> Add device). If Dualshock gets disconnected, I press (PS) guide button, DS4 connects, but DS4Windows can't detect it and gamepad shuts down in several seconds. However, if I delete gamepad from settings and setup it again (PS+Share -> Add device), everything is working again. Also, I'm using "Hide DS4 Controller".
Is it bug or how things work?
I've attached logs, but it shows nothing usefull, because DS4Windows can't even detect Dualshock 4. 
[ds4windows_log_20210515.0.txt](https://github.com/Ryochan7/DS4Windows/files/6484849/ds4windows_log_20210515.0.txt)
Disabling "Hide DS4 Controller" gives nothing. As I connect DS4 second/third/fourth... time it doesn't show up even in Contol Panel. Just "Connected" status in Settings app for a few seconds and it disconnects.

**Comment by mika-n** [comment]
First things first.

`Connection to ViGEmBus 1.16.112.0 established`
You have an old version of ViGem bus which may cause even BSOD Windows crashes with Win10 and DS4Windows 3.x versions. You should install the latest ViGemBus 1.17.x version from the following web page (**remember to download x64 64bit version** and NOT the 32bit x86 version if you have 64bit Windows, 99.999999% cases on Win10 are 64bit versions nowadays).
https://github.com/ViGEm/ViGEmBus/releases


`HidGuardian in use. Launching HidGuardHelper
Using Exclusive Mode`
You seem to have both HidGuardian driver installed AND you have ticked the "Hide DS4 Controller" option in DS4Windows app. Usually only one of these is used at the same time because both do the same thing. Anyway, HidGuardian is an old driver and it has been replaced by HidHide driver (the same author as with HidGuardian). You should uninstall HidGuardian and install HidHide driver to hide the physical gamepad from games (to avoid double controller issues).
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

HidHide installation instructions (and HidGuardian uninstall instructions):
https://vigem.org/projects/HidHide/Simple-Setup-Guide/

But, these issues shouldn't have anything to do how Windows BT stack/driver recognized the physical DS4 gamepad (well, if you have somehow screwed up HidGuardian installation and setup it may prevent DS4Windows to see the gamepad). To diagnose the issue I would rule out the HidGuardian mis-configuration theory at first by uninstalling HidGuardian as instructed on HidHide setup guide page and then try the connect/disconnect thing before installing HidHide.

**Comment by Kanuan** [comment]
Don't know if related, but I had an issue where my USB Bluetooth dongle would not remember my controller after a Windows' sleep-wake cycle or reboot.

The issue was (somehow) because it was connected to a 3.0 USB port, while the dongle was made for 2.0 ones. Though 3.0 should be retro compatible with 2.0, there was some compatibility issue with mine.

Plugging in an actual 2.0 port fixed the issue for me. If you are using a USB dongle try different USB ports in your computer

**Comment by iArti** [comment]
> But, these issues shouldn't have anything to do how Windows BT stack/driver recognized the physical DS4 gamepad (well, if you have somehow screwed up HidGuardian installation and setup it may prevent DS4Windows to see the gamepad). To diagnose the issue I would rule out the HidGuardian mis-configuration theory at first by uninstalling HidGuardian as instructed on HidHide setup guide page and then try the connect/disconnect thing before installing HidHide.
Yeah, that's the drill. I've updated VIGem driver and uninstalled HidGuardian, however, issue still persist. At this point, I don't care about hiding gamepad, I just want it to work without so much hustle.
So, again, my steps (from the very beginning):
1. DS4Windows launches with Windows as a task.
2. I open Bluetooth settings on my laptop and connect DS4 (PS+Share -> Add device)
3. DS4Windows detects gamepad and everything is fine
4. I disconnect DS4
5. I press PS (Guide) button to connect
6. Lightbar glows white (instead of battery level), DS4Windows shows nothing
7. After several seconds, DS4 disconnects
To make things work again I have to re-run setup process (delete device and pair it again).
I have generic built-in Intel Bluetooth.

**Comment by Kanuan** [comment]
> send a screenshot from your device manager with the Bluetooth section expanded

**Comment by iArti** [comment]
> > send a screenshot from your device manager with the Bluetooth section expanded

![image](https://user-images.githubusercontent.com/23010139/118360578-19a41080-b591-11eb-8af3-a18ffc870281.png)
There is couple of items in Russian, they mean Bluetooth LE enumeator and Device Identification Service

**Comment by iArti** [comment]
Updating Intel Bluetooth Driver solved problem. Thank you for trying to help!
