### ISSUE TITLE
Can't emulate dualshock 4 on a dualsense

### ISSUE THREAD

**Issue by tweash** [Ryochan7/DS4Windows#2146]
My emulated controller is set to dualshock 4 and i have use dinput only selected but steam is still acting like im using an xbox 360 controller. Im on the latest version and im using bluetooth.

**Comment by Kanuan** [comment]
Are you using HidGuardian?

If yes, go to the  `settings` tab -> open `HidNinja` -> Remove entry `HID\VID_054C&PID_05C4`

Then reconnect your controller

**Comment by tweash** [comment]
> Are you using HidGuardian?
> 
> If yes, go to the `settings` tab -> open `HidNinja` -> Remove entry `HID\VID_054C&PID_05C4`
> 
> Then reconnect your controller

huh you know i saw that option earlier but then i updated ds4 windows and now its gone. Any other way to get rid of it? And what even is it?

**Comment by Kanuan** [comment]
Sorry, I was not clear. I'm not saying for you to use it, I'm saying that if you were using it hidguardian has this common issue where it can end-up hiding the virtual ds4 controller if it is misconfigured

**Comment by tweash** [comment]
[log.txt](https://github.com/Ryochan7/DS4Windows/files/6489659/log.txt)
Yeah there was no misunderstanding just wondering why it disappeared when i updated

**Comment by Kanuan** [comment]
I should properly finish waking up before reading my emails.

> i have use dinput only selected

- This option actually means DS4Windows will _NOT_ spawn virtual controllers, regardless to what you set. This needs to be disabled so DS4Windows creates a virtual controller accordingly to your profile.

> but steam is still acting like im using an xbox 360 controller

Need more info on what is happening here. A few things to consider:


__Regarding Steam:__
- It's recommended that Steam's `Playstation/Xbox configuration support` is disabled when using DS4Windows. Steam doesn't need this enabled for the controllers to be picked by its games. This option should only be used if you want to use Steam as a remapping tool, which is not necessary since DS4Windows has the same functions
- If Steam detects DS4Windows is running, it will ignore every DS4 controller in the system (real or emulated). This means you won't be able to control Steam's big picture with the emulated DS4 created by DS4Windows, though it should work as normal in games anyway
- If you want Steam to stop ignoring the Emulated DS4 for Big Picture usage then you need to go into the `settings` tab and set a custom .exe name for your DS4 windows, then restart DS4Windows by using the new .exe file created in its folder

__Regarding using DualSense + Emulated DS4__ (this is more or less unrelated to your problem, but I think it might be useful):
- When emulating a DS4/Xbox 360 controller with DS4Windows, there is a good chance games will detect 2 controllers instead of one: the "generic" real controller (DualSense) and the emulated controller, which leads to the famous __double input issue__
- The `Hide DS4 controllers` in the settings tab aimed to solve the double-input issue, but it can fail for any number of reasons and it's recommended to just leave it disable, as there are better solutions for that
- The recommended solution is for you to hide the DualSense controller using __HidHide__ (HidGuardian's successor) so games stop detecting it, preventing the double-input issue from happening since the games will only see the emulated controller. [Here's HidHide setup guide](https://vigem.org/projects/HidHide/Simple-Setup-Guide/)
- There is a issue with HidHide right now where some games end-up having really high input latency when using a emulated DS4 controller. It has already been solved in its source code but there has not been a new release of HidHide with the fix yet. From what I know, emulated xbox controllers are free from this problem and the issue happens in only a small number of games, so you can just use HidHide as normal and if you suffer from high latency with emulated DS4 controllers you can switch to Xbox emulation until the new version is released

**Comment by tweash** [comment]
Thanks for your response, unfortunately I can seem to solve this. I turned off the dinput only setting and it doesnt seem any different. I never really had much of a problem with steam detecting multiple controller besides a few times when ds4windows and steam opened at the same time. I also dont really use big picture mode but I heavily use steam controller configurator and dont really wanna figure out how to use the equivalent in ds4windows as it doesnt seem nearly as robust. It seems to me that the option to emulate a dualshock 4 is just busted for me, dunno why it would be emulating a 360 controller when I specifically have that option enabled.

**Comment by Kanuan** [comment]
with the dinput setting off, send the new log

**Comment by tweash** [comment]
[log.txt](https://github.com/Ryochan7/DS4Windows/files/6490102/log.txt)

**Comment by Kanuan** [comment]
accordingly to the log, it is actually creating the virtual DS4.

- Select your `ds4` profile
- type `Win + R` on the keyboard, then on the appearing windows type `joy.cpl` and hit OK
- Send a screenshot of the windows' controller window

![image](https://user-images.githubusercontent.com/24910442/118414078-ff456200-b678-11eb-9f30-fef96a01795c.png)

**Comment by tweash** [comment]
![rundll32_2021-05-16_18-10-42](https://user-images.githubusercontent.com/55579525/118414360-09179700-b672-11eb-8788-430a3d2eaaf7.png)

**Comment by Kanuan** [comment]
Wireless controller means DualSense or DualShock 4.

Send a screenshot of DS4W's `Output Slots` tab

**Comment by tweash** [comment]
![Uploading DS4Windows_2021-05-16_18-14-00.png…]()

**Comment by Kanuan** [comment]
Broken image link. Edit your post to re-upload it

**Comment by Kanuan** [comment]
You've set a permanent virtual Xbox 360 controller on the first slot. Click on it -> change from `permanent` to `dynamic` then on the `accept` button. After that, click on the `unplug` button.

All slots should set to dynamic unless you have some specific usecase.

the second slot is the virtual DS4 as it should be. DS4Windows is working as it should.

Accordingly to your `joy.cpl` screenshot, there are 4 controllers connected:
- Xbox 360 (should vanish after changing the first slot from permanent to dynamic and unplugging it
- Wireless controller 1 (DualSense?)
- Wireless controller 2 (Virtual DS4?)
- Wireless controller 3 (no idea. Try stopping-starting DS4Windows)

**Comment by tweash** [comment]
Huh well now I think its working? It's not working in Steam though and now only one controller shows up in joy.cpl and it doesnt detect any inputs however the controller readings tab in ds4windows is detecting inputs. If I plug in the controller rather than using bluetooth another controller will show up in joy.cpl that detects inputs however still nothing shows up in Steam.

**Comment by tweash** [comment]
Wait forget about the part about me plugging it in I guess, accidently enabled dinput only somehow and now another controller shows up in joy.cpl that detects inputs while in bluetooth but nothing in Steam.

**Comment by Kanuan** [comment]
> - If Steam detects DS4Windows is running, it will ignore every DS4 controller in the system (real or emulated). This means you won't be able to control Steam's big picture with the emulated DS4 created by DS4Windows, though it should work as normal in games anyway
> - If you want Steam to stop ignoring the Emulated DS4 for Big Picture usage then you need to go into DS4W's settings tab and set a custom .exe name for your DS4Windows, then close and re-open it by using the new .exe file created in its folder

To properly check if DS4Windows is running under a custom name, press `Ctrl + Shift + Esc` to open Windows' task manager -> go into `Details` tab -> check how DS4Windows appears there. If its name is exactly DS4Windows then Steam will ignore every DS4 controller in the system, virtual or not. 

Besides that, doesn't Steam properly detect the DualSense controller if DS4Windows is just fully closed? I'm not sure about connecting via bluetooth, but Steam does has direct support for DualSense controllers without using DS4Windows (on cable at least).

**Comment by tweash** [comment]
Okay now it detects it but now the dualsense and the dualshock 4 show up. How do I disable it detecting the dualsense?

**Comment by Kanuan** [comment]
Or you hide the DualSense with HidHide as I mentioned in another post above, or you just... don't use DS4Windows at all. Fully closing DS4Windows (as in, it does not appear on the task manager at all) and then restarting Steam will make Steam pick the DualSense directly. 

Do you have any need of DS4Windows if your intention is using Steam's controller support?

**Comment by tweash** [comment]
Yeah some games seem to not work correctly with steam's dualsense support. Some games vibration would not work or the controller just wont work at all on games where my dualshock 4 worked just fine. Also I just want to simply switch a profile for games that I want to emulate a dualshock 4 in, instead of closing ds4 windows or whatever. I'll follow the guide you posted before. You've been a great help, thanks.

**Comment by Kanuan** [comment]
I am glad to help (when I can). Be sure to mark this issue as closed!

Remember that issue with high input delay with HidHide I mentioned on some post above (should affect a small number of games. Will be fixed on the next release of HidHide)
