### ISSUE TITLE
Mouse input does not work with right analog stick

### ISSUE THREAD

**Issue by PatriotZest** [Ryochan7/DS4Windows#2150]
So I wanted to use my right analog stick to perform mouse functions, I have mapped the controls currently but it does not work any fix?

**Comment by mika-n** [comment]
maybe you should read the pinned "Read this before posting a new issue ticket" post?
And then provide more details AND the profile file you are using.

**Comment by Ryochan7** [comment]
Learn about Windows UAC security measures and run DS4Windows as the Admin. There are many issues posted here regarding this same issue. In short, it is legitimately Microsoft's fault.

On the plus side, there is a likely chance that I will get a virtual KB+M driver released sometime this week. It would likely work similar to the driver used in reWASD but it would be open source with a more documented API. The driver would be faster than using SendInput API, it would not be affected by Windows UAC security measures, and it would not be stopped by UAC pop-ups like SendInput is even when running DS4Windows as Admin. This is something I have been wanting for years; I think since around 2015.

Related to issue #1629

**Comment by PatriotZest** [comment]
Ok so the mouse input works I gave ds4 admin and UAC virtualization allowed but now whenever I open my game VALORANT the mouse input stops working again I close the game then it starts working again. Any fix?

**Comment by Masamune3210** [comment]
Valorant ignores emulated inputs intentionally, thats actually one of the things the new driver will hopefully fix

**Comment by PatriotZest** [comment]
reWASD also used to work but its stopped now, also it lacks a lot of features hopefully this new driver will fix our issues. The Anti-Cheat thing in valorant blocks emulated input
