### ISSUE TITLE
Inverting Trigger Axis (L2/R2) ?

### ISSUE THREAD

**Issue by FlintEastwood** [Ryochan7/DS4Windows#2151]
How can I invert the trigger axis (L2/R2  In 0% = out 100% and In 100% = out 0%) for the DS4 controller?
I thought, I could do it with the curve-editor, but only bezier points can be moved.

I need this for Richard Burns Rally, where the throttle and brake are inverted, when using DS4 output.
With Xbox360 output, both triggers are combined to a single axis and that doesn't work for Rally left braking.

**Comment by Ryochan7** [comment]
That sounds like a bad scheme in game tbh. Never had a reason to add some sort of invert option for the triggers. I guess it wouldn't be too hard to add it as an extra modifier.

The triggers of the Xbox 360 controller in DInput mode are mostly useless since they are mapped to one axis.

**Comment by mika-n** [comment]
> How can I invert the trigger axis (L2/R2 In 0% = out 100% and In 100% = out 0%) for the DS4 controller?
> I need this for Richard Burns Rally, where the throttle and brake are inverted, when using DS4 output.
> With Xbox360 output, both triggers are combined to a single axis and that doesn't work for Rally left braking.

This is your lucky day. I also do mods for Richard Burns Rally :-)

The solution for RBR is to tell it the controller you use for brake/throttle are inverted and problem solved. If you have RallySimFans (RSF, www.rallysimfans.hu) rbr version then the latest version has RSF_Launcher app (see RSF_Launcher subfolder in RSF RBR installation folder) where you can tell RBR that throttle/brake are inverted.
![rsfLauncher](https://user-images.githubusercontent.com/35538525/118610863-e8138b00-b7c4-11eb-904b-879b8a71792c.png)

If you don't have RSF rbr version then the same can be tweaked through input.ini file (open it in Notepad) in RBR root folder.

Also, about the xbox gamepad issue in RBR and combined throttle/brake axis. I have modded a solution to that issue if you have xbox gamepad or use DS4 as xinput output device (well, with DS4 gamepad there is no need to use DS4Windows app and xinput mode because RBR works with DS4 gamepad out-of-the-box once you tell rbr the gamepad has inverted axis). Anyway, see this if you really want to use xbox/xinput gamepad in RBR.
https://github.com/mika-n/NGPCarMenu/issues/15

**Comment by FlintEastwood** [comment]
Hello Mika, 
Thanks for pointing me to the input.ini. I totally forgot about that.
When I come home from work today,  I will try this.

@Ryochan :
Thanks for your reply too. I will try it tonight with the game's INI setting.

And yes, RBR is still the best rally simulation.

**Comment by FlintEastwood** [comment]
Hello,
it really worked. Thank you Mika.
So I used the RBR "input.ini":
`InvertThrottleAxis = true`
`InvertBrakeAxis = true`

I think we can close this problem :)
