### ISSUE TITLE
High latency over bluetooth

### ISSUE THREAD

**Issue by jonalange** [Ryochan7/DS4Windows#2153]
I'm using the Dual Sense PS5 controller with your software. 
Via cable connection I got around max 5ms delay.

When I'm connected via bluetooth I've got a delay from min 10ms to max 300-500ms.

Thats pretty annoying. I use a bluetooth 4.0 dongle and just ordered a 5.0 to see if that solves the problem.

Are any settings wrong or what do I need to do to fix this?

**Comment by Masamune3210** [comment]
Try moving your dongle away from your case and closer to your computer if you are on desktop and are able to. Or plug it into your monitor if it has USB ports. Unfortunately, there isn't much way software-wise to make latency better as its a hardware issue. If your dongle is having trouble talking to the controller or if there is too much interference it causes latency issues

**Comment by jonalange** [comment]
Well, I try that. But with an xbox controller everything works fine. Maybe the ps5 controller transfers a lot more data than this useless xbox controller without any technology inside

**Comment by mika-n** [comment]
DS4 gamepad has two operating modes in BT connection mode.

(1) By default PC-friendly mode in BT which is a bit like how xbox gamepad sends button events (well, not as xinput, but dinput protocol in DS4 but in this mode DS4 gamepad doesn't support those special DS4 things touchpad/gyro/lightbar). This also means that a lot less data is sent to PC and a lot less data is written to the gamepad (it is two-way BT traffic between PC and DS4 gamepad). If you use DS4 gamepad in Windows10 without DS4Windows app then the BT connected DS4 remains in this PC-friendly mode. Often gamepads may work just fine in this mode even when BT coverage is not that great.

(2) Native DS4 mode over BT requires certain configuration commands to be sent to DS4 gamepad before the pad switches over to this native mode. DS4Windows app knows how to send this initialization commands to the gamepad. In this mode there will be a lot more traffic over the two-way BT highway. Some BT chipset/dongles/PCs struggle to keep up the data rate in this mode.

If you don't need lightbar and rumble then you could untick "Enable Output data to DS4" profile option in Others tab page. When this option is unticked then DS4Windows app won't send rumble and lightbar data to the DS4 gamepad, so there would be a lot less data moving over BT (writing out data). See if this helps.

Other tips are listed here. If you have BT dongle then the USB extension cable trick has worked in many cases. And try different USB ports (usb2/usb3/front/back panel/powered usb hub etc).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#gamepad-connection-over-bluetooth-bt

**Comment by jonalange** [comment]
Thank you very much. The latency seems fine after moving the dongle around. But the controller turns off like instantly when I try to connect it to the pc. Any idea why this could happen?

**Comment by jonalange** [comment]
Quick update: For some reason the controller had no battery. But yesterday it was plugged in for at least 3-4 hours and had a battery of around 70%.
Do I have to change something in the settings so the controller actually turn off?
The pc was off over the night.

**Comment by Masamune3210** [comment]
That seems to be a bug in the controller firmware itself from what I can gather, as that's the only thing I cant rule out, multiple people have reported that same issue

**Comment by Zero-Starlight** [comment]
I'm getting similar, if somewhat sporadic issues with Bluetooth latency as well. Report is below, and I'll attach one of my logs.

Desktop (please complete the following information):

Controller Make and Model: Sony DualSense Wireless Controller (CFI-ZCT1W)
OS: Windows 10 Pro 64 Bit Version 10.0.19042 Build 19042
DS4Windows Version 3.0.5

Using a MPOW Wireless USB Dongle (Model: BH456A), which I purchased due to issues with my motherboard's bluetooth hardware not being able to maintain connection with my Dualsense, unlike my DS4, I have issues with moments of high latency (around 50ms at max) resulting in sudden input lag spikes. I don't necessarily want to resort to disabling output data if I can avoid it, so I'll see if I can find a way to get the dongle further away.
[ds4windows_log_20210520.0.txt](https://github.com/Ryochan7/DS4Windows/files/6525418/ds4windows_log_20210520.0.txt)
