### ISSUE TITLE
Can't read battery level when connected via cable

### ISSUE THREAD

**Issue by jonalange** [Ryochan7/DS4Windows#2155]
When I'm connected via cable the battery says 0%+ 
But when connected via bluetooth it shows me the (I guess) correct value.

Using a DS5 btw

**Comment by mika-n** [comment]
please read the pinned "Read this before posting a new issue ticket". Provide versions, logfiles, screenshots.
But, the short answer is that DS4Windows simply reports what it receives from the gamepad. And with DS5 it is recommended to hook it up with PS5 console to get a firmware update because there has been few DS5 firmware updates fixing various bugs (battery issue is one of those).
