### ISSUE TITLE
Trojan in DS4Windows_3.0.5_x86.zip?

### ISSUE THREAD

**Issue by sadstan123456** [Ryochan7/DS4Windows#2161]
Said release file is blocked by browser when trying to download.

zip file: https://www.virustotal.com/gui/file/7532a60e5f37f63165238487fb95d8460f899cc408c4c37423024e83d4bfe224/detection/f-7532a60e5f37f63165238487fb95d8460f899cc408c4c37423024e83d4bfe224-1620727834
7z file: https://www.virustotal.com/gui/file/9105ba25723505be4568ad31f670b27c92be2a9ba5af80c0ae5180030917cc3d/detection

**Comment by Masamune3210** [comment]
PLEASE check existing issues before making your own, this has been asked literally 10's of times now. 

There is nothing malicious in the releases, its just anti-virus heuristics having a fit about .NET embedded runtime stuff

**Comment by kazhybride** [comment]
Guys I have a problem, I can't connect my controller with DS4Windows. Each time I click on Start, my controller is connected, but after few second, it's turn to disconnected by itself.

**Comment by Kanuan** [comment]
@kazhybride 
Please, do not hijack other issues, specially when they are completely unrelated to the problem you are having.

Create your own issue and, before that, read the [pinned issue](https://github.com/Ryochan7/DS4Windows/issues/1196) on how to properly troubleshoot your situation.

Also, make sure to read and correctly fill the given template when creating your own issue, giving the maximum amount of information and correctly organizing it. It's basically impossible to help when the person who needs help gives almost no useful information to work with.

**Comment by kazhybride** [comment]
@Kanuan oooh ok ok my bad :(
The problem is that I'm French and I can't give you clear information about my situation. Is there any French support ?

I gonna delete my message after this.

**Comment by Ryochan7** [comment]
Related to issue #2134 

As far as I am concerned, this seems more like a false positive than anything else. I have not had a chance to look back into this since my last post in that issue; the main focus lately has been on driver work. Probably going to end up re-installing Windows 10 before the next release of DS4Windows.  It probably won't make a difference though. According to VirusTotal, other projects are supposedly using the same suspected compromised x86 libraries from the Visual C++ Redistributable package.

As far as I am concerned, unless you are still using a 32-bit system for some odd reason (older Windows tablet), there is no reason to download the x86 build of DS4Windows. You would likely get better performance by using the x64 build instead. Also, it does not seem to suffer from this problem since those Visual C++ Redistributable files are not flagged by those virus engines.

**Comment by Ryochan7** [comment]
Got a Windows 10 VM running. Installed the minimum required to get Visual Studio 2019 to compile .NET 5 projects. I tried to just compile the Console app template and upload the results to VirusTotal. **Same thing**. Sigh. Maybe I should just blame Microsoft for this one.

x86 support might end up going away after all.

**Comment by Ryochan7** [comment]
Publish arguments matter.

https://www.reddit.com/r/csharp/comments/k9pnn0/net_5_single_file_trim_self_contained_detected_as/gf5my1c

> Framework Dependent / Single File throws no Virus Warning

Holds true on my end. WTF

**Comment by Ryochan7** [comment]
Did another test. DS4Updater.exe (x86) has been a thorn in my side through this. Unsigned DS4Windows.exe produces a lot of warnings from anti-virus engines when uploaded to VirusTotal. Used new certificate to sign that same DS4Updater.exe and then uploaded: NO WARNINGS. WTF

Maybe the somewhat crazy extortion angle was not far off

**Comment by Ryochan7** [comment]
Here is an example. DS4Updater.exe from DS4Windows_3.0.5_x86.zip. One copy unsigned and the other signed. 19 errors for the unsigned version and 0 errors for the signed exe.

DS4Updater.exe (unsigned)
https://www.virustotal.com/gui/file/bec20aacb44db8fcd647b01b3dbf57679bf73cec2393c045cf012995bd01d9ba/detection

DS4Updater.exe (signed)
https://www.virustotal.com/gui/file/f14b738b613f58a116dc6113ad1a4bbb5244f9bc88f7df45a845c77121621f04/detection

Obviously I was going to sign future releases of DS4Windows since I have the means to do so now. I did not want to think that it would be absolutely necessary for publication though.

**Comment by Ryochan7** [comment]
14 errors vs 2 errors for the archive. The report does not tell me which files the 2 anti-virus engines are complaining about. Much helpful

DS4Windows_3.0.5_x86.zip
https://www.virustotal.com/gui/file/7532a60e5f37f63165238487fb95d8460f899cc408c4c37423024e83d4bfe224/detection

DS4Windows_3.0.5_x86.zip (signed exe and DLL files)
https://www.virustotal.com/gui/file/ac2c14c32fc357d59e88751a98c63e958b35b018e68f482cf1011761eb7333e8/detection

**Comment by Ryochan7** [comment]
Cylance does not seem to like HidNinja for some reason. That brings it down to 1 error for the signed files archive.

**Comment by Ryochan7** [comment]
BitDefenderTheta is complaining about my custom Nefarius.ViGEm.Client.dll file. It is probably something to do with the new version checking routine that I added in; the errors shown on VirusTotal went to +1 for the archive files previously once that change was added. Not sure if signing the bundled ViGEmClient.dll file, along with the exposed Nefarius.ViGEm.Client.dll file, would help. Going to have to try that soon. Now down to 0 errors.

**Comment by Ryochan7** [comment]
Tried out signing the internal ViGEmClient.dll file. Now VirusTotal does not complain about my custom Nefarius.ViGEm.Client.dll file.

**Comment by sadstan123456** [comment]
> PLEASE check existing issues before making your own, this has been asked literally 10's of times now.
> 
> There is nothing malicious in the releases, its just anti-virus heuristics having a fit about .NET embedded runtime stuff

I personally do believe to be a false positive. However, I do think there still is a real issue.

**Comment by sadstan123456** [comment]
> 14 errors vs 2 errors for the archive. The report does not tell me which files the 2 anti-virus engines are complaining about. Much helpful
> 
> DS4Windows_3.0.5_x86.zip
> https://www.virustotal.com/gui/file/7532a60e5f37f63165238487fb95d8460f899cc408c4c37423024e83d4bfe224/detection
> 
> DS4Windows_3.0.5_x86.zip (signed exe and DLL files)
> https://www.virustotal.com/gui/file/ac2c14c32fc357d59e88751a98c63e958b35b018e68f482cf1011761eb7333e8/detection

Based on my testing, the detection is was for DS4Updater.exe
So, would this mean that signing DS4Updater.exe resolves the issue?

**Comment by Ryochan7** [comment]
It does seems like just signing the file is enough to get those anti-virus engines to stop complaining. The Cylance error regarding the whole archive is the only reasonable warning (marked Unsafe) probably because HidNinja requires Admin privileges to run and it messes with the system registry. I guess I can understand why it would possibly complain. A warning like that should not cause red flags in Windows Defender that would block files from getting copied like what was posted in a different issue. At some point, HidNinja will be removed from distribution because HidGuardian is deprecated in favor of HidHide.

At least there seems to be a workaround for now. I would hate to think that digital signing would be an absolute requirement for distribution going forward. That would be an added cost around $90 USD per year to renew the certificate. Not a very open source friendly requirement to impose on hobby projects. I originally got the certificate for driver development as it is an absolute requirement for driver distribution.
