### ISSUE TITLE
Auto Profile with Hide DS4Windows Temporarily enabled is closing the whole application after about 20-30 seconds.

### ISSUE THREAD

**Issue by Pixxel123** [Ryochan7/DS4Windows#2170]
After selecting an application (Duckstation emulator) in which DS4Windows should be turned off for, DS4W closes itself out automatically.

This happens on Duckstation 0.1-4046-g96330e55.

**Comment by mika-n** [comment]
closed because the original bug report didn't provide enough information (versions and most of all the latest logfile of DS4Windows). Anyone posting a new issue ticket should read the pinned "Read this before posting a new issue ticket" post to make sure they know what information they should provide.
