### ISSUE TITLE
Windows Server 2019 - PS4 gamepad working on wired, but not on wireless

### ISSUE THREAD

**Issue by Dirkaios** [Ryochan7/DS4Windows#2171]
(As the titles says)

On Windows Server 2019, I can use the PS4 gamepad with DS4Windows only on wired, but not on wireless.
The issues seems to be related on how the PS4 gamepad is detected by Windows Server 2019 itself.
I can pair the device via bluetooth but it will never pick up as proper gamepad, (apparently due to lack of proper driver), therefore, DS4Windows will never work or find any game controller device to pick up and do its magic.

I can get DSHIDMINI + BTHPS3 + PS3 gamepad + DS4Windows working perfectly fine on Windows Server 2019, wired or wireless.
Is there any way get PS4 also working with these? Any hopes for PS4 gamepad to work wirelessly on Windows Server 2019?

**Comment by w1lddog2** [comment]
Why would you use Windows Server 2019  instead of Windows 10????   
Windows Server 2019 even 2016 sometimes has hard time detecting hardware on consumers pc, which leads to have to install them by hand.  For example on a B460MDS3H board  Windows Server 2019, failed to detect few components while  Windows 10 didn't.
In fact Windows Server will install some addon that for regular use are "bloatware".

**Comment by Dirkaios** [comment]
> 
> 
> Why would you use Windows Server 2019 instead of Windows 10????
> Windows Server 2019 even 2016 sometimes has hard time detecting hardware on consumers pc boards, which leads to have to install them by hand. For example on a B460MDS3H board Windows Server 2019, failed to detect few components while Windows 10 didn't.
> In fact Windows Server will install some addon that for regular use are "bloatware".

There are reasons.
I know Server 2019 is not meant for gaming and such, but the experience is good for those who seek optimization while gaming.
You won't get as much bloatware as recent Windows 10 and its broken updates. You can get a lot of bloatware if you activate several services and features, for sure, but they are not as imposed as many bloatware on Win10. In fact , you do get a very lean experience with server 2019 out of the box (maybe too much...).
You can check videos from Fr33thy, Chris Titus Tech and Linus on Youtube if you need to understand how and why.

If it failed to detect some hardware for that mobo, you might want to try Snappy Driver Installer.

There are a few cons for using Server 2019, but I haven't experienced many on AMD/Ryzen.
The PS4 gamepad on wireless was the only main issue that I can think of.

**Comment by w1lddog2** [comment]
This my main issue with "Tech Lords" on youtube, they give  adivces that are "uhmmm really".  On Windows 10 Pro you can disable auto updates, bloatware can be removed quite issue and you won't have any issue with consumer grade hardware.
First they were talking about LTSC,now they are recommending windows server for gaming LOL.
I work with different flavours of windows server on daily basis. I expend most of my day with "Windows Admin Center" managing them.

Anyway, on device manager under bluetooth what do you see???  It could be an issue with the Microsoft Bluetooth enumerator.

**Comment by mika-n** [comment]
this has been discussed before in those old tickets already. Use the search feature, but here is one ticket. #1271 
The problem is not in DS4Windows, but in WindowsServer2019 because it tries to limit the driver exposure surface area by leaving out several drivers and tools supplied with desktop Windows versions. One thing missing is gamepad drivers and probably many of the HID bluetooth drivers. You need to see if you can install those missing drivers.

**Comment by w1lddog2** [comment]
> this has been discussed before in those old tickets already. Use the search feature, but here is one ticket. #1271
> The problem is not in DS4Windows, but in WindowsServer2019 because it tries to limit the driver exposure surface area by leaving out several drivers and tools supplied with desktop Windows versions. One thing missing is gamepad drivers and probably many of the HID bluetooth drivers. You need to see if you can install those missing drivers.


I guess that he did read that ticket. Because jrickter88  was not even able to use the gamepad wired. For what i see they never solved the wireless issue.

Like you said on Windows server the driver exposure is limited. That is why i told him the case of the B460MDS3H board which is extremly common on the consumer market yet Windows Server won't detect nor install all the drivers, leaving you to do it 

I don't think that Microsfot use the sames repositories for  Windows 10 and for Windows Server.  His/her best beat is to compare every driver that is used by DS4 and compare it to the ones installed on a Windows 10 PC.

**Comment by Dirkaios** [comment]
> 
> 
> this has been discussed before in those old tickets already. Use the search feature, but here is one ticket. #1271
> The problem is not in DS4Windows, but in WindowsServer2019 because it tries to limit the driver exposure surface area by leaving out several drivers and tools supplied with desktop Windows versions. One thing missing is gamepad drivers and probably many of the HID bluetooth drivers. You need to see if you can install those missing drivers.

Thanks, I didn't see this topic when I used the search (possibly mistyped something). Seems to be the same drama in the end. That's why I poked with the possibility of using anything that Nefarious is doing (which is quite a lot now...so I'm a bit lost). For his tools, I'm not sure if there is or will be any support for DS4 since it already works on Win10, but it could be useful for this situation.

I use Win10 for my gaming, but also try other things on dual/triple booting and so on. That's why I'm experimenting with Server 2019. I remember doing something similar with Server 2003 in the past, but it was not as positive as it is right now where most of the stuff just works (except this one).

**Comment by w1lddog2** [comment]
If you are dual,etc booting, then just compare the drivers that are being used for the bluetooth on the Win10 install and the ones in the server.

**Comment by Ryochan7** [comment]
Never had a reason to use any Windows Server edition. Despite my problems with Linux lately, I still use Linux exclusively for server tasks. I am not sure why a PS4 controller would only work wired but not wireless if Windows is actually detecting the BT connection as a Wireless Controller. At least the base HID input driver is bundled with Windows Server.

In the end, this is a Windows problem and not a DS4Windows related issue.
