### ISSUE TITLE
Include self-contained variant of application

### ISSUE THREAD

**Issue by L0um15** [Ryochan7/DS4Windows#2172]
This is just a suggestion. DS4 windows uses .NET 5 Runtime in order to work properly which means it is framework-dependent, it would be nice to have self-contained variant of application for non-developers so they can use application without installing whole runtime just for one application.

Pros:
 - Already included with application, works out of the box
 - Removal of DS4 Windows will result in removal of NET 5
 - Bundled runtime is isolated, it will be only accessed by this specific application and it will not be suddenly updated.
 
Cons:
 - Much larger application size
 - First Launch takes some time
 - Files chaos

**Comment by Ryochan7** [comment]
Some Massive Cons:

* Much more likely chance for false positives to show up in VirusTotal due to bundled libraries
* Much more bloated zip archive (over 100 MB)

I am sure Microsoft will likely bundle a .NET 5.0 Runtime with future Windows updates at some point. Currently, it isn't a big deal to just download and install the current runtime packages linked from the DS4Windows README file or even from the initial failure window if you launch DS4Windows without having .NET 5 installed first. There should be no need to have the app contain an isolated instance of the runtime; people complain about the amount of extra DLL files that are currently bundled with DS4Windows.

**Comment by L0um15** [comment]
Ok, i understand. Thanks for your response.
