### ISSUE TITLE
Request: Tooltips

### ISSUE THREAD

**Issue by timothymowens** [Ryochan7/DS4Windows#2176]
Please add tooltips to all the checkboxes and such in settings and throughout the application that explains what the option actually does.  Some are blatantly obvious, but some aren't.  Like "Hide DS4 Controller" for example.  What does this actually do?  Does it hide the DS4 controller from the DS4Windows app?  Does it hide it from Windows?  Does it hide it from specific apps/games?

**Comment by Masamune3210** [comment]
It attempts to hide the physical controller from other apps on the computer

**Comment by Kanuan** [comment]
### Regarding the `Hide DS4 controllers` option

  DS4Windows does not "change" how the controller communicates to Windows, meaning it does not makes Windows see the controller as if it were, for example, an Xbox controller or a keyboard. What it actually does is that, assuming you are on default settings, it creates a __virtual__ Xbox controller in which the real controller is remapped into.

  This means that you end-up with 2 controllers: the real and the virtual one. Some games can end-up detecting both at the same time, leading to the famous "double-input issue". Some games may also start randomly 2 player mode (e.g.: rocket league) since it thinks there are 2 separate controllers connected.

  Want to check this? Press on your keyboard the keys `Win + R`, then type `joy.cpl` and select `OK`. This will show a list with the current connected controllers. If you are using a controller with DS4Windows, chances are that you will see 2 controllers in the list.

 The "Hide DS4 controllers" option attempts to hide the real controller from the system, leaving only the virtual controller you want to use. Doing this prevents the double-input issue in games.

 __If you are on a 64 bits Windows 10, this option should not be used__ because it can fail to actually hide the controller for different reasons. For hiding the real controller, the current recommendation is to use [HidHide](https://vigem.org/projects/HidHide/Simple-Setup-Guide).
 
 
 ### Regarding the tool-tips
 
  _Take what is written here with a grain of salt since I'm not a contributor to the project, I'm just trying to give some context_

  Only Ryochan7 and mika-n can confirm this, but the tooltips are probably just pretty low on the "to-do" list. I guess that there are more pressing issues to be fixed and features to be implemented, and there is only so much a 2 people team can do on their free time. It is a project that is open to contributions though, meaning anyway can easily contribute to it if they know the minimum on how to code.

  Besides that, there is only so much that can be explained on a tool-tip. For a noob user, what I've wrote on the previous section is the bare minimum to understand why there is a need to hide the real controller from the system. For most of the options that are missing tool-tips, if the user doesn't already know what they do it's not a tooltip that will save them.

  Most options that require detailed explanations probably already have one on [DS4Windows' Wiki](https://github.com/Ryochan7/DS4Windows/wiki). If the option and how it works is missing there, then again this project is open to contributions and anyway can add missing info to the wiki.

**Comment by timothymowens** [comment]
Thank you.  I am admittedly new to DS4Windows and wasn't aware of the wiki.

**Comment by mika-n** [comment]
yes, documentation on the web and in the app is never-ending-story. It should be improved, but devs don't have enough time and energy to do it.
