### ISSUE TITLE
[Feature Request] Option to track if process was shut down in auto-profile

### ISSUE THREAD

**Issue by ferrazpedro** [Ryochan7/DS4Windows#2190]
I don't know how feasible it would be, but the idea is to be able to turn off DS4Windows with the already avaiable option, but when the chosen process shuts down, DS4Windows would turn itself on again, even if it was in the background.

**Comment by Kanuan** [comment]
Can't you achieve more or less the same thing by creating a profile with `Profile settings` -> `Other tab` ->  `DInput only` checkbox enabled (so this profile do not spawn virtual controllers) then set this profile with auto-profile for the chosen process?

besides that, can you elaborate a bit on why you want DS4Windows disabled in specific games/process?

**Comment by ferrazpedro** [comment]
Well, I would like to disable it when steam is working. This way I could have the best of steam already made presets and ds4windows for everything else. But the thing is: Steam would not be the process in the foreground.

It already has the first part of this process working right. When I select this option:
![image](https://user-images.githubusercontent.com/37643357/120696072-7d2fa880-c482-11eb-9900-82d3ceeee46c.png)

It would be awesome if DS4Windows could revert this change whenever the Steam process was shut down.

**Comment by mika-n** [comment]
something similar has been discussed before, but there are couple things good to know
- Auto-profile feature relies on the current FOREGROUND process. DS4Windows app does not actively poll and scan all background processes because it would be looooots of wasted CPU cycles if done too often.
- If an app is launched, but it doesn't create a window or doesn't get a foreground focus then DS4Windows doesn't "see" the new process because the app doesn't scan all process launches.

Sure it would be technically possible to scan all background processes, but it hasn't been implemented because it is not a cheap operation (in cpu cycles) to do few times per each second. However, DS4Windows has a cmdline interface you can use to command DS4Windows to do various things and then there are 3rd party external apps you can use to run commands based on services and running processes.
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options
https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules

You can use Windows TaskScheduler to create tasks to launch automatically when a certain process is launched (fex steam client). Or use 3rd party apps to do the same and much more.

**Comment by Ryochan7** [comment]
It would technically be possible. Have the auto profile checker use foreground window checking until a particular window comes into focus and then switch to just monitoring a process until it dies. Trying to constantly poll for various processes all the time seems like a waste of CPU cycles. I wouldn't have an immediate use case for it and I would normally just stop the DS4Windows control service manually.

The GUI would likely have to be changed as it is not obvious which temp profile is actually active at the time and a change in profile switching logic would make things more confusing.

**Comment by ferrazpedro** [comment]
Thanks for all the responses! Well, since this would be kinda complicated to implement, I'm trying to make it work with autohotkey. But whenever I use "ControllerMapper.exe -command stop" (ControllerMapper is my alias to DS4Windows so Steam doesn't complain) nothing happens.

**Comment by ferrazpedro** [comment]
Since I could resolve this with autohotkey, I'm closing this issue.
