### ISSUE TITLE
[Feature Request] Stadia controller.

### ISSUE THREAD

**Issue by marcopaone** [Ryochan7/DS4Windows#2209]
Hi! I wanted to ask, is it possible to add support for the Stadia controller? 
Thanks in advance.

**Comment by mika-n** [comment]
#1617 

Possible yes, needs someone with the hardware to debug and develop the support. Don't know if any of the DS4Windows devs have Stadia controller (for sure I don't have).

If you just need to map Stadia Controller (usb wired) as xinput device then there is StadiaController app and it actually uses the same ViGem driver to expose the virtual xbox controller than DS4Windows app uses. But StadiaController app doesn't have all these fancy macro/re-map/outputCurve features found in DS4Windows app.
https://github.com/71/stadiacontroller/

Anyway, because the HID/dinput interface of StadiaController is known then it would be quite easy to add a support in DS4Windows, but some dev should have the hardware at first. Until then it is up to the community to add the support as a code pull request.

**Comment by Ryochan7** [comment]
It is probably possible but I wouldn't implement it on principle. I am massively anti-Stadia and mostly anti-Google in general nowadays. If someone would make a pull request for Stadia controller support, I would probably merge it in.

**Comment by thestift** [comment]
any updates now?

**Comment by Masamune3210** [comment]
Did you miss the part where he said that he wasn't working on it and that it would take someone else doing it to get it merged in?

**Comment by thestift** [comment]
Yeah sorry missed it
