### ISSUE TITLE
Disconnect Controller special action doesn't work with official adapter

### ISSUE THREAD

**Issue by FirionHope** [Ryochan7/DS4Windows#222]
At least I think thats the problem. I can't get it to work at all, so I  have to hold down the PS button for 10 seconds instead

**Comment by pedrovay2003** [comment]
I'm using the official adapter, and the special action works for me. The only time it doesn't work is when the controller isn't in Exclusive Mode, at which point I have to hold the PS button until it turns off. If Exclusive Mode is being used, the button combo will still work with the adapter to turn of the controller instantly.

**Comment by FirionHope** [comment]
Ah its an exclusive mode issue then. Like many other people I haven't been able to get that to work either.

**Comment by diogocalgaro** [comment]
For me, exclusive mode works well if DS4Windows is one of the first apps to start with Windows. It has to start before Steam, for example. So I put DS4Win on auto-start and Steam I start manually later.
I'm using the Sony adapter too.

**Comment by FirionHope** [comment]
Interesting, I'll have to try it. Do you start it as a task? For me the task icon is grayed out so I can only run it as a program.

**Comment by Ryusennin** [comment]
I think you can only access the Task option if you've started DS4Windows as admin.

**Comment by Ryochan7** [comment]
Enabling the Task option requires DS4Windows to be run as admin. I will take a look into whether the special action still works with the Sony adapter. I don't think I have changed anything that could break that functionality.

**Comment by Ryochan7** [comment]
The code explicitly looks if exclusive access has been obtained before attempting to disconnect the controller. I did not leave a comment about why that restriction is in place and I cannot remember why either. I am wanting to think it was due to a hardware problem regarding the adapter keeping the PS and Options buttons stuck after disconnecting the controller when using the button combination. I typically click the BT icon in the GUI to disconnect the controller to avoid that kind of problem.

**Comment by Ryochan7** [comment]
That is the reason. Having those stuck buttons can be a problem for some applications such as Steam. Unfortunately, this is an inherit problem with the Sony wireless adapter that I cannot do anything about. The only workaround that could be done is to add a delay before the Disconnect BT special action is actually initiated to give the user a chance to release those buttons before disconnecting the controller. That might cause some confusion though.

**Comment by Ryochan7** [comment]
I am going to keep the current behavior for now. In case anyone is curious, here is a small example patch that would add a delay before disconnecting a controller connected to the Sony dongle.

```
diff --git a/DS4Windows/DS4Control/Mapping.cs b/DS4Windows/DS4Control/Mapping.cs
index c63ee43..b69f776 100644
--- a/DS4Windows/DS4Control/Mapping.cs
+++ b/DS4Windows/DS4Control/Mapping.cs
@@ -1902,9 +1902,9 @@ namespace DS4Windows
                                     {
                                         d.DisconnectBT();
                                     }
-                                    else if (deviceConn == ConnectionType.SONYWA && exclusive)
+                                    else if (deviceConn == ConnectionType.SONYWA && !d.IsDisconnecting)
                                     {
-                                        d.DisconnectDongle();
+                                        ForeclosureOfADream(d);
                                     }
 
                                     //foreach (DS4Controls dc in action.trigger)
@@ -2216,6 +2216,19 @@ namespace DS4Windows
             }
         }
 
+        private static void ForeclosureOfADream(DS4Device d)
+        {
+            d.IsDisconnecting = true;
+
+            Task.Delay(2000).ContinueWith((t) =>
+            {
+                d.queueEvent(() =>
+                {
+                    d.DisconnectDongle();
+                });
+            });
+        }
+
         private static async void PlayMacro(int device, bool[] macrocontrol, string macro, DS4Controls control, DS4KeyType keyType)
         {
             if (macro.StartsWith("164/9/9/164") || macro.StartsWith("18/9/9/18"))
diff --git a/DS4Windows/DS4Library/DS4Device.cs b/DS4Windows/DS4Library/DS4Device.cs
index 17dc6e3..8a1d500 100644
--- a/DS4Windows/DS4Library/DS4Device.cs
+++ b/DS4Windows/DS4Library/DS4Device.cs
@@ -175,7 +175,7 @@ namespace DS4Windows
         public bool IsDisconnecting
         {
             get { return isDisconnecting; }
-            private set
+            set
             {
                 this.isDisconnecting = value;
             }
@@ -911,6 +911,7 @@ namespace DS4Windows
                     if (controllerSynced != synced)
                     {
                         synced = controllerSynced;
+                        this.isDisconnecting = false;
                         SyncChange?.Invoke(this, EventArgs.Empty);
                     }
                 }
```

**Comment by Robyer** [comment]
@Ryochan7 Could we have that delayed disconnection as option? I'm using sony dongle and I can't make exclusive mode to work properly, so I can't disconnect the DS4 easily with special action. 

Btw isn't it possible to wait for some "button up" event, so the disconnect action would be started only after all buttons are released?

**Comment by Ryochan7** [comment]
If you are having problems with exclusive mode not working with the Sony dongle, you can first try to disconnect and re-connect the dongle. I have experienced exclusive mode not working with the dongle on occasion even when it should and doing that cycle is sometimes necessary to allow DS4Windows to get exclusive access to the dongle.

It would be possible to code the Special Action to set a flag once the trigger is detected and wait until the trigger is released before executing the action. A delay would probably still be required as the input from the DirectInput controller would probably be a tad behind the input from the raw HID device due to buffering.

I had looked into implementing something like that before but I decided to not worry about it. Maybe I can look into that again.
