### ISSUE TITLE
DS4 isn't recognised anymore in Control (epic version)

### ISSUE THREAD

**Issue by ramaduc** [Ryochan7/DS4Windows#2223]
Hello. 

My dualshock 4 controller isn't recognised anymore in Control (remedy game).

This is only happening on epic game version. I have also the steam version and it works fine. I already finish the game on epic version and it worked fine. But since I bought the dlc, I relaunch the game and now the DS4 is not recognised.

My only solution for now is to add a non steam game in steam and to launch it from steam. 

Someone can help ? Thanks

**Desktop (please complete the following information):**
 - Controller : Sony DS4 v.2 CUH-ZCT2E
 - OS: Windows 10 Family Build 2004
 - DS4Windows Version 3.0.9

**Comment by MikeCZ23** [comment]
ds4windows works fine for me in Control Epic

**Comment by Kanuan** [comment]
With Steam fully closed:

- Connect your controller and have DS4Windows running
- Send a screenshot of DS4Windows `controllers` tab
- Send a screenshot of DS4Windows `Output Slots` tab
- Press on your keyboard `Win + R` -> Type `joy.cpl` and press OK -> __Send a screenshot of Window's `USB Game Controllers` Window__

**Comment by ramaduc** [comment]
> With Steam fully closed:
> 
> * Connect your controller and have DS4Windows running
> * Send a screenshot of DS4Windows `controllers` tab
> * Send a screenshot of DS4Windows `Output Slots` tab
> * Press on your keyboard `Win + R` -> Type `joy.cpl` and press OK -> **Send a screenshot of Window's `USB Game Controllers` Window**
> * Go to the DS4Windows `log` tab, export the log file and send it here
> 
> Send all screenshots and the log file in a single comment here to keep things organized

Hello Kanuan,

Here are what you want.

[Logs.txt](https://github.com/Ryochan7/DS4Windows/files/6658792/Logs.txt)
![controller](https://user-images.githubusercontent.com/67982109/122124491-a3b0f480-ce2f-11eb-96b2-2440657c36b0.png)
![Output](https://user-images.githubusercontent.com/67982109/122124493-a4498b00-ce2f-11eb-9dac-ea6f83400e69.png)
![USB Game Controllers](https://user-images.githubusercontent.com/67982109/122124494-a4e22180-ce2f-11eb-952b-cc7771ae0c04.png)

I have 3 controllers so that normal if you see 3 controllers. I tried with 2 different controllers. I reinstall the game once. Nothing changed. I just don't understand. The other games on Epic are functionnal with the same controllers and my steam version of Control is working like a charm with this controller too. 

The only thing I did to get it works is to add a non steam game and play the game through Steam. It worked before in Epic so I don't know what happened.

Thanks again for the time you will spare for this.

**Comment by Kanuan** [comment]
I don't have Control installed anymore so I can't test, but if I recall correctly it doesn't have DualShock 4 support.

Did you ever had PS button icons when playing Control or they were always Xbox buttons icons? If it's the later option, then you probably have that Steam option `Playstation Configuration Support`, which makes Steam translate your DS4 controller into a virtual Xbox controller.

This would explain why your controller is not working directly through Epic Games Launcher (Game detects your controller as an actual DS4) while it works when launching it from Steam with the non-steam game option (Steam translates the controller and it detects it as a Xbox controller)

Anyway, just create a new profile on DS4 windows that has Xbox 360 controller emulation instead of DS4 emulation.

Also, any specific reason for using 3 permanent Output Slots? Why not set all slots to dynamic, so the virtual controllers only exists when the real controller is plugged in?

**Comment by mika-n** [comment]
```
06/15/2021 22:57:37: Connection to ViGEmBus 1.16.112.0 established
06/15/2021 22:57:37: Using Exclusive Mode
```

And because you have Win10 64bit OS you should upgrade ViGem driver to the latest 1.17.xxx version. The old 1.16.x version is not guaranteed to work properly with the latest DS4Windows versions because the app expects to see 1.17.x version of ViGem.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

And because you use "exclusive mode" (=Hide DS4 Windows -option in ds4windows settings) then make sure you have read and understood how it works and if the exclusive mode fails to enable then how to fix it (track down other apps hijacking the gamepad or use an alternative solution HidHide driver from the same author as ViGem driver).

**Comment by ramaduc** [comment]
Hello Guys,

@mika-n I updated the ViGem driver but it doesn't resolve my problem although it is good to update it.

@Kanuan Thanks for the tips. I managed to get it work by changing the emulated controller to X360. 
The reason why I set the output slot to permanent DS4 is because I prefer to get the playstation's buttons on the screen (when it is available). I have X360 controller but I don't want to play with it as I prefer DS4 controller. I suppose I won't need DS4Windows if I used X360 controller. So no need for dynamic type for me unless I didn't understood the purpose of this feature.

I created a copy of DUC profile, change the emulated controller to X360 and set an auto profile to control so that when I launch the game, it will automaticaly select the DUC Xbox profile.

Thanks again for your time.

Regards.

**Comment by Kanuan** [comment]
> The reason why I set the output slot to permanent DS4 is because I prefer to get the playstation's buttons on the screen
> So no need for dynamic type for me unless I didn't understood the purpose of this feature.

__The Output Slots types are not related to the real controller you are using__.

You don't need a permanent DS4 output slot to use your DS4 _as_ an DS4 controller. If you set all slots to dynamic, then when you connect your real DS4 controller DS4Windows will spawn a virtual controle. If the virtual controller DS4Windows creates is a DS4 or Xbox 360 controller that only depends on the profile you've selected to your controller. When you disconnect your real controller DS4Windows will also disconnect the virtual controller.

In your case, you have 3 virtual DS4 controllers constantly plugged in, regardless if your real controllers are connected or not. When you use a real DS4 with a DS4-emulation profile, then DS4Windows just associated one of the "black" permanent virtual DS4 controllers to your real controllers. When you select a x360-emulation profile, because a permanent "blank" device does not exist already DS4Windows will temporarily spawn a virtual x360 controller, meaning you end-up with a total of 4 connected virtual controllers in your system (3 useless DS4 controllers and 1 x360 controller associated with your real controller)

Anyway, since your issue is fixed, please, mark this issue as __Closed__

**Comment by ramaduc** [comment]
@Kanuan Thanks for your explanations. It is very helpful and clear.

I remember I had problems regarding four controllers recognized while I had 3 in real, so it might comes from that.
So I change all the output slot for dynamic.

Thanks again.

Regards
