### ISSUE TITLE
unreal gold/ oldunreal 227i mod not detecting controller

### ISSUE THREAD

**Issue by powerpuffboysz** [Ryochan7/DS4Windows#2234]
im using the latest 3.0.9 and it not really that unreal isnt seeing the controller but the game refuses to acknowledge autoprofiles. i double checked most other programs on my pc and they all work with autoprofiles just fine. strange thing is if manually change to my custom profile it works but autoprofiles don't for some reason

**Comment by Ryochan7** [comment]
I can't get Unreal Gold to work on my current PC. :cry: It has been a long time since I played the game through (probably when working on antimicro).

Not sure if the problem would have been a permission issue. I wouldn't be surprised if the game has to run in an Elevated state. If that is the case, DS4Windows would not be able to get the window handle unless it is also running Elevated as Admin. You would likely run into input problems as well.

**Comment by powerpuffboysz** [comment]
yeah, im an idiot. i'm a bit ocd when it comes to folder names so i use dynamic linking to rename steam folders and still be playable. unreal gold was one i renamed and the second i dug up the true folder which i had hidden it autoprofiles worked
