### ISSUE TITLE
Fightstick not getting detected

### ISSUE THREAD

**Issue by bzlom** [Ryochan7/DS4Windows#2236]
**Describe the bug**
DS4Windows doesn't detect fightstick "HORI Fightstick Mini". 

**To Reproduce**
Doesn't matter what you do - it just doesn't detect it. I was using some version of DS4Windows 1-2 years before and it was working without any issues, tried an older build of DS4 - still doesn't detect it, recently reinstaled Windows - maybe it's some latest windows update that's affecting it - no idea. My official PS4 controller is detected without any issues - only the fightstick doesn't. The fightstick itself is in working state since I opened gamepad tester (https://gamepad-tester.com/) and it registers button presses.

**Expected behavior**
To detect the Fightstick

**Desktop (please complete the following information):**
 - Controller Make and Model: HORI Fightstick Mini PS4-043
 - OS: Windows 10 Home build 19043.1052
 - DS4Windows Version 3.0.9

**Comment by mika-n** [comment]
Log file? See the pinned "Read this before posting a new issue ticket" post.
Send a screenshot from gamepad-tester.com page where it shows the VID/PID vendor/product hardware identifier values (0xABCD / 0x1234 type of hex decimal values).

And when you say it used to work with an old version of DS4Windows app then what version was that?
Are you sure the gamepad is recognized by Windows as dinput device and not as xinput device? DS4Windows doesn't support xinput gamepads because the original idea of the app was to expose dinput DS gamepads as virtual xinput gamepads on PC, so doing xinput->xinput translation was originally useless scenario.

**Comment by bzlom** [comment]
Hi, haven't attached log files since they didn't contain IMO anything useful, attached them this time around - you can see 2 pair of logs from 2 different versions I've tried yesterday:
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6675444/ds4windows_log.txt)
[ds4windows_log_20210617.2.txt](https://github.com/Ryochan7/DS4Windows/files/6675445/ds4windows_log_20210617.2.txt)
Also have attached a requested screenshot with VID/PID:
<img width="669" alt="horiFighstickMini" src="https://user-images.githubusercontent.com/3832242/122525798-83d92680-d011-11eb-9490-e484a1f63587.PNG">

I don't know what older version of DS4Windows I was using before - so I'm not excluding the fact that I might have been using a different tool. 
Are you sure the gamepad is recognized by Windows as dinput device and not as xinput device? - how can I check that?

**Comment by mika-n** [comment]
DS4Windows app folder has Tools/XInputChecker/ tool. Try to run it while DS4Windows is NOT running and if you see the gamepad there then it is registered in WinOS as xinput gamepad. Then the short answer is that DS4Windows doesn't support it because originally there was no need to do xinput->xinput "conversion".  

If the gamepad is NOT shown in XInputChecker, but the gamepad is shown in JOY.CPL controlPanel applet (run this command in StartMenu) then the gamepad is probably registered as dinput device and there is hope. Trigger "shoulder buttons" (if the fightstick has equivalent buttons with those DS4 shoulder triggers) should also be shown in separate axis in JOY.CPL and not as combined within the same analog axis (xinput trigger keys are combined into single axis in JOY.CPL because it uses dinput interface. Yes, this xinput using combined trigger axis over dinput interface thing is a stupid thing by Microsoft).

If the xInputChecker tool can see the gamepad then you should see if you can force the gamepad to be recognized by WinOS as dinput (some custom gamepads have a switch for it or vendor specific device driver option).

**Comment by bzlom** [comment]
It's apparently working without the need for DS4 - either Killer Instinct devs patched something in or Microsoft updated their support for controllers. One way or another it's working without the tool now. Sorry for the trouble - I was getting the controller detected 1-2 years ago with DS4Windows or something else and it seems it's unnecessary any longer. Sorry for the confusion and thank you for your help.
