### ISSUE TITLE
'Passthrough' on left and right touchpad click for games with distinct left / right click DS4 actions (eg Death Stranding)?

### ISSUE THREAD

**Issue by PoliteTimesplitter** [Ryochan7/DS4Windows#2254]
Sorry if I'm overlooking something, but I've tried a few different options and can't get this to work.

Some games which feature PS4 controller support have distinct actions tied to clicking the touchpad on the left side and on the right side. One example is Death Stranding, where clicking on the left side calls out or gives Likes, and clicking on the right side would start photo mode. I can't get either of these to work when my PS4 controller is emulating a DS4 in DS4Windows. If I stop DS4W and plug my DS4 in via USB it works as intended. Is this a limitation of the DirectInput / Vigembus that it uses, or am I missing something?

I understand that inputs can only be assigned to a generic 'touchpad click' option manually, but in the Touchpad tab I've tried setting Output Mode to 'passthru' and 'Controls' with 'Passthru Click Action (DS4 Mode)' enabled, but to no avail in Death Stranding. If it means 'click' as in mouse click, I don't get the mouse click either (which would hold the backpack with the left or right hand respectively in DS). Nothing happens. 

I also went into Steam Big Picture and enabled 'Playstation configuration support' but that just stopped DS4Windows working when in a PS4-based profile entirely.

The only other DS4-supporting game I knowingly have and play is Yakuza 7, in which any touchpad click (no matter which side) brings up the map, and this works with the passthru - but seemingly _not_ games with side-specific click presses like DS.

Is this just something DS4W can't do or have I mucked something up along the way?

**Comment by Ryusennin** [comment]
I'm not sure about ViGEm, but it's possible that it doesn't differentiate left and right clicks via passthrough mode.

From memory, there aren't many games on PS4 that specifically implement left/right touchpad clicks. Death Stranding is one of the few ones. I often found this quite a shame and a waste of potential, since most games seem to only use the touchpad as a big glorified Select button. A handful of them will instead use swiping to offer alternate functions (like displaying the map in Witcher 3 or Days Gone).

**Comment by Ryochan7** [comment]
Maybe I should have left the issues section closed for good? Literally a user created problem for this project as a whole. I need muh old driver support but I want magical new feature for free.

Touchpad Passthru mode has been documented several times to only work as intended with ViGEmBus 1.17.333.0; searching is too much work. Only that version of the driver can transmit Touchpad and Gyro data like a real DS4 controller; using ViGEmBus 1.16.112.0 won't do it. That means you have to run Windows 10 in order to have access to Touchpad and Gyro Passthru modes. People will whine about Windows 7 support and then still expect features that require the newest ViGEmBus driver in order to work. Can't help but get toxic in cases like this.
