### ISSUE TITLE
can someone please tell me how to use hidguardian?(Edit: new bug found)

### ISSUE THREAD

**Issue by brothan323** [Ryochan7/DS4Windows#226]
I have no idea how to whitelist my ds4 device and google brings up nothing.

**Comment by TristanYoung** [comment]
I'll give it a shot.

1.  Download and install the Windows Driver Kit from the Microsoft website.  Since I run Windows 10 x64, I installed the version for Windows 10 x64 from here:
    https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

On the Microsoft WDK site, skip over step 1, then download and install the WDK in step 2.  This will install a crucial program called devcon.exe

2. Download the following file, and copy the contents to a folder of your choice:
    [HidGuardian Helper Files.zip](https://github.com/Ryochan7/DS4Windows/files/1753664/HidGuardian.Helper.Files.zip)

3.  Open the folder you created in step 2, then right-click on 'Install HIDGuardian' and select 'Run as administrator'.  This will install the HIDGuardian filter driver.

4.  You can either update the registry with the list of devices to guard manually, through a pre-compiled .reg file, or via DS4Windows.  See next steps 4a to 4c - pick one only.

    4a. Manual method - If you want to do it this way, you can get the necessary info out of the file mentioned in step 4b.  If you need help using regedit, you probably shouldn't be using regedit ;)  As I see it, there's no need to do it the hard way when others have made it easy for you :)  

    4b. Registry file import - double-click on the .reg file 'HID Guardian AffectedDevices' and merge this into your Windows registry.

    4c. If DS4Windows is running, terminate it.  Then run DS4Windows as administrator by opening the folder where DS4Windows is saved, right-click on DS4Windows and select 'Run as administrator'.  Then under the Settings tab, select 'Write HID Guardian Device List'.   Note, if DS4Windows is not running as administrator, it will not be able to write to the Windows registry.

You should be good to go.

Let me know if this works for you.

**Comment by TristanYoung** [comment]
I hope Ryochan7 doesn't mind, I posted the above (slightly modified) as a quick-start guide in the wiki section.  It will be easier to refer people to the wiki and keep it up-to-date with the latest install information.  

If anyone has any suggestions to make the guide better, please let me know.

I'm looking for someone who can help convert the batch file to a PowerShell script.  My first attempt failed while trying to call devcon.exe with arguments.

**Comment by TristanYoung** [comment]
Were you successful in getting HIDGuardian working?

**Comment by brothan323** [comment]
I sure was. Thanks a bunch for the help.

**Comment by TristanYoung** [comment]
That's great. Glad it helped.  Have fun!

**Comment by brothan323** [comment]
So, the doesn't work anymore. It decided to stop working after a few hours of idling. I went to sleep, came back a while later to play game vids, but the controller just will not be read by any steam game.

**Comment by brothan323** [comment]
nothing fixes this but restarting my pc.

**Comment by TristanYoung** [comment]
Here's a question:  Have you updated Windows 10 since you initially got it working?

It's worth looking to see if HIDGuardian is one of the drivers in the chain for your bluetooth controller after the controller stops working.

Is DS4Widnows still running when you notice the controllers stop working?  Make sure it hasn't frozen, crashed or terminated.  This behavior is weird, since it doesn't seem to make sense.

Q: How do you turn off your controllers when you're finished using them?

Incidentally, I would create a new ticket for this new problem, and title it appropriately, rather than re-purposing an old ticket.

**Comment by brothan323** [comment]
uhh I use Windows 7, not Windows 10.

>It's worth looking to see if HIDGuardian is one of the drivers in the
chain for your bluetooth controller after the controller stops working.

I have no idea how to do this.

>Is DS4Widnows still running when you notice the controllers stop working?
Make sure it hasn't frozen, crashed or terminated. This behavior is weird,
since it doesn't seem to make sense.

DS4 windows is fine, not frozen or anything.

Q: How do you turn off your controllers when you're finished using them?
I unplug it, if it's plugged in via mini usb. Or I press options+psbutton
to disconnect from the bluetooth(the ds4 controller could resync without
issue before the program screwed up again.

**Comment by czukowski** [comment]
@brothan323

Maybe it's not it, but I've had a very similar issue and it turned out it was because I was plugging the controller into the computer's USB port for recharge. I guess something can get really messed up in the system when the controller switches connections between Bluetooth and USB. My solution was to use a wall charger instead and the issue hasn't reoccurred since then :)

**Comment by TristanYoung** [comment]
@brothan323 Sorry, I'm not going to attempt to remember what OS version everyone said they use in other threads.  I have a hard enough time remembering what I ate for breakfast.  Probably means I didn't eat anything ;)

Like @czukowski said, maybe it has to do with plugging in to the USB port.  I have never plugged my controllers in to the USB ports on my computer.  I use a dual controller charger utilizing the feature connector at the bottom of the DS4 - between the palm grips, to the left of the headphone jack, powered by its own 5v power supply.  I don't like using the USB ports on the controllers.  It's worth asking.

Other than that, I'm not really sure what's going on with your setup.  Have you tried this on a different computer using the same bluetooth radio and controller?  Can you duplicate it on that other machine?  Is it also Windows 7?

**Comment by Ryusennin** [comment]
Could be USB related indead, although I'm also on Win7+HIDGuardian and I regularly switch between USB and BT without any conflict.

Brothan323, is Quick Charge activated in DS4Windows?

**Comment by Ryochan7** [comment]
Keeping DS4Windows running overnight and syncing a controller later works fine on my machine.

**Comment by brothan323** [comment]
@TristanYoung Sorry, this program has just been bugging the hell out of me for the past week and a bit lol.

I did figure it out though.  @czukowski was right, connecting the DS4 controller to my PC via USB messed with the driver. Having it connected to the bluetooth works fine, even when disconnecting and reconnecting after a while.

**Comment by Ryochan7** [comment]
You are in the same boat that I am with InputMapper. None of the 1.7 builds have detected any of my controllers and the abandoned 1.6 build only works with my controllers when connected via USB.

Unfortunately, I can only really make this project more useful for myself (scratch your own itch). I have fixed issues people have mentioned in the past but I can only diagnose a problem if I can re-produce it on my system.

**Comment by brothan323** [comment]
lol well the driver still bugs out after the DS4 is disconnected from the pc for a few hours. No idea why this is even an issue:\

**Comment by lewisohn** [comment]
After updating to the latest version of DS4Windows, exclusive mode stopped working for me. I have a second generation DualShock 4 controller and I use InputMapper HidGuardian. After a quick search I found [these instructions](https://inputmapper.com/forum/inputmapper-1-5-support/843-how-to-get-exclusive-mode-working-including-2nd-gen-controllers) on the InputMapper support forum, posted a few weeks ago.

I noticed that DS4Windows had written this to the registry:

```
HID\VID_054C&PID_05C4
HID\VID_054C&PID_09CC&MI_03
HID\VID_054C&PID_0BA0&MI_03
HID\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&05c4
HID\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&09cc
```

Whereas the instructions recommended this:

```
HID\VID_054C&PID_09CC&REV_0100&MI_03
HID\VID_054C&PID_09CC&MI_03
HID\VID_054C&UP:0001_U:0005
HID\{00001124-0000-1000-8000-00805F9B34FB}_VID&0002054C_PID&09CC
```

By switching over to the recommended whitelist I was able to get exclusive mode working again. Just sharing here in case it helps anyone else.

**Comment by xan105** [comment]
My 2nd gen DS4 & DS4Windows work flawlessly with hidguardian by using the registry modification from the link given by lewisohn.
Nvidia share is no longer a problem thanks to this :)

**Comment by Ryochan7** [comment]
The only difference that I see is that the BT string uses uppercase
characters for the InputMapper version but the DS4Windows version uses some
lowercase characters. The strings are the same otherwise. On my system,
Windows gives the Hardware ID with some lowercase characters so that is why
that version is used in DS4Windows. The version bundled with the
InputMapper HidGuardian installer is an older version (1.6.1.0). The
current version that is available is version 1.14.0.0. I would have to test
the older version of HidGuardian to see if the problem comes down to how
that version of HidGuardian handles Hardware ID strings.

Personally, I would not use that version of HidGuardian anyway since I
encountered some latency issues using older versions of HidGuardian. The
oldest version that I would recommend using is version 1.13.0.0.

On Tue, Mar 13, 2018 at 11:10 AM, Anthony Beaumont <notifications@github.com

**Comment by Ryochan7** [comment]
I tried this with the older version of HidGuardian. It works as expected on
my machine.

**Comment by Ryochan7** [comment]
More testing. Both versions of the string work on my system with the old version of HidGuardian. However, I am wondering if HidGuardian is actually matching by ID `HID\VID_054C&UP:0001_U:0005` instead when using the example list given. That is a more generic Hardware Id for that controller and it would be checked first since HidGuardian checks each ID in the list sequentially.

**Comment by dreamcat4** [comment]
Hello.
I had a previous version of HID Guardian installed that wasnt working properly. So I just downloaded the latest version from here:

https://downloads.vigem.org/stable/1.14.0.0/windows/x86_64/

Then unzipped it. Didn't need WDK for devcon.exe or anyhting like that. Just right clicked on the Cog, and selected 'Install' from the explorer context menu. It promped me to restart. Did that.

Opened DS4Windows in administrator mode, and selected the clear registry, then add registry options in settings (these options are not visible unless DS4Windows is running as admin).

What I discovered was that this all works now. The exclusive more. However it only finds controllers IF DS4Windows is being launched in admin mode (again). So not just for the initial installation, but also whenever you need to actually use / play there after. DS4Windows must always be launched as admin. Otherwise no controllers are detected.

Perhaps there is some way around this limitation so we don't need to be running constantly as Admin? Thats kindda problematic for normal everyday use, but especially if launching DS4Windows as a startup login item.

Also why can't DS4Windows always show those registry actions in settings (in normal mode), then ust elevate itself for those times when the user actually clicks the option? If the program is already capable of elevating itself for other types of actions, isn't there some internal hook already in there somewhere?
