### ISSUE TITLE
[Hide DS4 Controller] Please make this option back

### ISSUE THREAD

**Issue by Tyralith** [Ryochan7/DS4Windows#2262]
Hi, first i just wanna say i love your app since the beginning.
Back in the days when i used motioninjoy who caused some BSOD on my PC :D 

Anyway, i just saw in your lastlog v3.0.11 that you disable the option to "Hide DS4 controller" and said it's obsolete.
I don't understand why? I still use this option since the beginning and it's worked really well.

Especially in Soul's game from "From Software" who doesn't work without this option.

So is it possible to bring back this option or at least a way to bypass this problem ?

Thank you !

**Comment by jeek-midford** [comment]
Please install HidHide on your computer. It's better than "Hide DS4 controller".

**Comment by Tyralith** [comment]
Nice thank you, i just tried this and it works very well.
In case someone ask the same question as me, you just have to disable/enable the sony gamepad when you connect your controller with HidHide.
If you don't re-enable it before disconnect it, you won't be able to see your controller when you will connect it again.

Anyway it looks like what you should have done with the "hide DS4 controller" in DS4windows.

**Comment by Masamune3210** [comment]
The hide DS4 controller option was removed iirc because it doesn't work 70% of the time and is more trouble to deal with than it's worth. As to the other issue, are you saying that if you don't disable HidHide that the controller wont show in DS4Windows? Is the program on the whitelist?

**Comment by aburke20** [comment]
Wait, I'm confused, at least for me it worked 100% ! And how was it troublesome, it was a simple "on/off" option. 

Some games I literally can't play without activating it: (Lego builder, and Sekiro right now, but I have a few others that also require it).

The new solution is to install an entirely separate program ? _That's_ inconvenient.

Which was the latest version still using it, because I swear I can't play without it.

**Comment by isaac-weisberg** [comment]
Hide DS4 option has disappeared, Exclusive mode is unavailable, some titles (NFS 2015 in particular) break because of this...
And it did work, it did always work for me - sometimes it was a must to reconnect the controller for it to work especially if I left it plugged for the night.

**Comment by Masamune3210** [comment]
You can look through the issues and the different releases adding and removing it and see the tumultuous reputation it has. It cannot work 100% of the time and has its issues due to how it works, the new method is much more robust as it hides the controller from the entire system at a lower level and before anything can grab a handle to the controller. Any game that required that option can work with HidHide the same if not more successfully

**Comment by LanceLionroar** [comment]
This new "improved" way does not work for me whatsoever. Forza Horizon 4 is broken and all search results tell you to "Hide DS4 Controller" I have installed HidHide, followed what very little guidance was available online, and no matter how many times I tick on and off the "enable device hiding" option it does nothing. Yes I have added the program to the whitelist, and chosen the controller so that it's marked with a red lock. So this option requires an extra installation and does not even work. If anybody actually has a clue how to get Forza Horizon 4 to recognize the controller properly in this build, please advise how.

**Comment by Kanuan** [comment]
1) You need to reboot after installing HidHide, otherwise it will not work. Also, you need to REBOOT, not turn off then on again
2) [HidHide has a setup guide](https://vigem.org/projects/HidHide/Simple-Setup-Guide/) that has been working for basically everyone until now
3) You need to verify on Windows' `joy.cpl` (`USB Game Controllers` window) if HidHide is working properly. The image below shows how it is supposed to work, with the real controller hidden and the virtual controller DS4Windows creates visible as it should be
![image](https://user-images.githubusercontent.com/24910442/124403660-df8ff900-dd0d-11eb-8789-d13341c5673e.png)

**Comment by LanceLionroar** [comment]
I started from scratch and followed the instructions more carefully and it works now. Hasn't really been the most convenient way of doing things though.

**Comment by Yohoki** [comment]
I also have a branch I maintain that includes the exclusive mode option. If you REALLY need exclusive mode, you can download the branch from my github.

But, for 99% of users, HidHide is a better solution.

Since HidHide fixes almost all issues we had with HidGuardian and Exclusive mode, I don't see either being brought back at any point. It adds a few steps to get it working right, but once it's set up correctly, you never have to touch it again unless you add another controller.

**Comment by Yohoki** [comment]
@Ryochan7 Might be too early to REALLY tell, but I think the game "Breakwaters" also breaks if Ex-Mode is turned off. My controller died, and turning it back on broke ex-mode and suddenly the game was unplayable. Even closing out of the game and restarting still had the controls broken. I did have HidHide installed and working correctly, so it *should* have blocked physical inputs from the game.

I'll have to test it a bit better later tonight and see if that was exactly it to be sure and I'll let you know. It may have been some other fluke since this is still in Beta right now.
