### ISSUE TITLE
Warzone 

### ISSUE THREAD

**Issue by Blu3Dev21x** [Ryochan7/DS4Windows#2267]
> I will at times disconnect the controller to untangle the type c usb cable, and when i reconnect it the pc detects the controller, the ds4 does also but in game only the touch pad on the ps5 works not any of the buttons. I go through a process of restarting the game and pc over and over until it does. someone pease fix this.

**Comment by mika-n** [comment]
don't disconnect the gamepad in the middle of the gaming session. It really is up to the game how those behave when a gamepad is re-connected while the game is running. Some games don't like it at all, some are more tolerant.

But, DS4Windows does have "permanent slot type" in "OutputSlots" tab page. Set a gamepad slot to permanent instead of dynamic type and it may workaround disconnection-reconnection issues with those buggy games.

**Comment by Blu3Dev21x** [comment]
Ok thank you.
