### ISSUE TITLE
 Controller shows up as XBOX_360_DEVICE_00:01 after sleep

### ISSUE THREAD

**Issue by gootdude** [Ryochan7/DS4Windows#227]
Running Windows 10, after the creator's update, I've noticed that sometimes after my machine goes to sleep, the controller no longer works in games because it thinks it is another new USB controller. 

When everything is functioning properly, there is a USB Input Device that shows up as location: XBOX_360_DEVICE_00:00

When the bug happens, the USB Input Device 00:00 shows it is no longer connected, and instead a new USB Input Device is listed with location XBOX_360_DEVICE_00:01.

Removing all the USB Input Devices and restarting DS4Windows does not fix the issue, as the controller will keep showing up as XBOX_360_DEVICE_00:01.

Only removing the USB Input Devices and restarting fixes the problem for me.

The games I'm playing, they only recognize the controller if it is XBOX_360_DEVICE_00:00.

Any idea how to fix this issue would be great, since I have to constantly restart my computer now to make sure the controller is going to work.

**Comment by Ryochan7** [comment]
I cannot remember exactly but I think DS4Windows is set up to stop its service when entering sleep mode and re-starting it once the computer returns from sleep mode. That process would unplug all virtual controllers once the service is stopped and then replug them once returning from sleep mode. If exiting DS4Windows does not take care of the problem then it might be a driver issue with ScpVBus. This might have to be tested with ViGEm to see if the problem occurs with that driver.

As an aside, I usually stick with the Linux mindset that sleep mode does not exist. It has been rare that sleep mode has ever worked for me on a Linux system. Hibernate has worked fine in the past.

**Comment by Ryochan7** [comment]
There was a problem with the resume routine regarding Bluetooth connections. Despite the HID device for a controller being closed on suspend, Windows would see the old HID device upon resuming and DS4Windows would try to use it and immediately fail. The process would make it so that the associated slot in ScpVBus would not be usable until the ScpVBus driver was disabled and re-enabled.

To work around the problem, Bluetooth controllers are now completely disconnected upon suspend so no old device will be seen by Windows upon resuming. Since making this change, I have not run into any problems with assigning slots in ScpVBus.
