### ISSUE TITLE
Macro not recording all keys

### ISSUE THREAD

**Issue by Mister-Curious** [Ryochan7/DS4Windows#2274]
**Describe the bug**
Cant record Macro of holding down Win key and Z key

**To Reproduce**
1. Click on controller button (say PS button for example)
2. In the 'Select an Action' window that appears press 'Record a Macro' and then press 'Record'
3. While the app is recording the action, press the Win Key down, and then press the Z key down
4. You will see that only the Win key action was recorded. 

**Expected behavior**
Expected to see the keys I pressed logged on the side and recorded. 

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 10 Pro Build 20H2 OS build 19042.1052
 - DS4Windows Version 3.0.10

**Comment by Yohoki** [comment]
The Macro recorder lets you record multiple times. Some button combos just don't work well with the recording process. Try recording the inputs separately.

Try this:
Click Record
Press 'Win' key
Click Stop
Click the '^LWin' or '^RWin' line on the left. *Up, not down*
Click Record Before LWin
Press 'Z' key
Click Stop

You should now see the combo you were looking for. :)

A quick side note, some applications don't detect a combo when they're pressed this quickly together. So, if you need to add a delay in, add it in before the 2nd line, so that the Z press is delayed by 5ms or so. Makes certain games think it's a human input and not a robot/macro.
