### ISSUE TITLE
It doesn't rumble in game when I set emulated controller to DualShock4.

### ISSUE THREAD

**Issue by James20001120** [Ryochan7/DS4Windows#2275]
I use Razer Raiju Ultimate controller. It rumble in game when I set emulated controller to Xbox 360. But It doesn't rumble in game when I set emulated controller to DualShock4. Even if I select Peset to Output Controller DualShock4,it still doesn't rumble in game.

**Comment by mika-n** [comment]
3.0.11 release note "Disabled broken DS4 feedback support again. Can't have semi-nice things. Don't bring it up again until at least the next ViGEmBus driver update"

This means rumble support is disabled on purpose on DS4 mode because there are few bugs in it (beyond the control of DS4Windows app). Once those bugs are solved then ds4 doesn't have rumble support. The bug could cause the rumble to get stuck on in some games.
