### ISSUE TITLE
Saints Row IV not working with controller after update 3.0.13

### ISSUE THREAD

**Issue by Jagerlion** [Ryochan7/DS4Windows#2290]
Not sure what going on but specifically Saints Row IV is having problems not detecting the controller. Using a Dual Shock 4 controller.

Tried  reinstall, restart, ran Hide DS4 on and off. Also tried switching between X360 output and DS4 output. None worked, ran input checker and works just fine. Other games are working as well, tested Resident Evil 2 and Biomutant.

Rolled back to version 3.0.10 and this seems to be the temporary fix for now. Seems like the issue is with 3.0.13 or 3.0.12.

**Comment by mika-n** [comment]
Hmmm.... There shouldn't be nothing which "could" even theoretically cause issues like that. Are you sure the original gamepad was properly hidden because if not then many games have weird issues. HidHide tool is the recommended way to hide the physical gamepad (works more reliable than the "Hide ds4 controller" aka exclusiveMode option in DS4Windows app settings).
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues 

Logfiles from both versions? Rename .log files as .txt and then drag-n-drop the file here in the comment field.

**Comment by Jagerlion** [comment]
I ran the uninstall/install for it and did the Hide twice, pretty sure I ran it properly. Familiar with the process. Uh I'll try to get the log files a bit later, is there a specific log file I'm looking for or just the latest one?

**Comment by Ryochan7** [comment]
Not sure why things would be different. Never tried the Windows version of Saints Row 4 but Saints Row 3 requires exclusive mode to be working or the input would be really funky and unusable; Saints Row 4 has been a Linux only title for me as the Linux port has ran well when I have played it. I guess I will install the Windows version and see if I run into similar issues.

**Comment by Ryochan7** [comment]
It is installed. Saints Row 4 has direct Steam Input API support. The game will only recognize a virtual Xbox 360 controller when using an external mapper. For some reason, the game does not even seem to read the Steam Input actions when attempting to use PlayStation Configuration support in Steam.

**Comment by Ryochan7** [comment]
I think Left 4 Dead 2 is the only SIAPI compatible game that I have ever played that actually worked as intended. Every other game that has utilized SIAPI, including Portal 2, has mapping problems or just doesn't work with defined actions at all. The API is mostly worthless but it gets praise for pretty GUI mapper.

**Comment by mika-n** [comment]
closed as inactive, logs missing
