### ISSUE TITLE
Help switching profiles (or get rid of Unload Trigger)

### ISSUE THREAD

**Issue by 0-Khs-0** [Ryochan7/DS4Windows#231]
Hello,

first, I want to tell you that your program is really excellent and it work perfectly.

I'm trying to switch between 3 profiles with Left Stick, but I can't find the solution.
With specials actions I can switch from Profile01 to Profile02 (or Profile03) but if I wan't then to load Profile03 (or Profile02), I need to go back to Profile01 (Unload trigger) and then switch to the other one.

What I do is :
- Left Stick Left : Profile01
- Left Stick Down : Profile02
- Left Stick Right : Profile03

Not working (what I would like) :
- Profile01 -> Profile02 -> Profile03
- Profile01 -> Profile03 -> Profile02

Working (what bothers me) :
- **Profile01** -> Profile02 -> **Profile01** -> Profile03
- **Profile01** -> Profile03 -> **Profile01** -> Profile02

If I missed the solution, thank you in advance for your help.
Otherwise is it possible in "Special Actions/Load a profile" not to force the selection of an Unload Trigger or add an option like "No Unload Trigger" ? If not, maybe have the possibility to load a profile with a macro ?

I hope that my explanations are not too confuse and sorry for my bad/strange english :)

OS : Win7 x64
DS4Windows : Version 1.4.113

**Comment by Ryochan7** [comment]
Requiring an unload trigger is a problem. An unload trigger could be useful for some use cases though. This functionality is something that I would not want to touch at this point.

Besides the unload problem, this type of setup would be a problem due to diagonals on the stick. There could be a likely chance that two profiles would be loaded in one poll. Changing the regions used for controls so that two controls would not be active at the same time would be required.
