### ISSUE TITLE
GUI Issues

### ISSUE THREAD

**Issue by frozen-eye** [Ryochan7/DS4Windows#232]
Hi, there are lot's of GUI issues on HighDPI screens with a zoom other then 100%. Do you have plans to rewrite a GUI in e.g. WPF with scaling compatibility?

![image](https://user-images.githubusercontent.com/6815256/37140352-1088087a-22ba-11e8-967e-006b7eecc97b.png)

OS : Win10 x64 Pro
DS4Windows : Ryochan7 Build Version1.4.113
Display Resolution: 3200x1800, Scale: 175%

**Comment by Ryochan7** [comment]
I would like to do it sometime but it won't happen for a long time. It doubt it will even happen in 2018. For now, I have been experimenting with WPF trying to make an alternative to the current Welcome dialog that installs the Scp Virtual Bus Driver. Making decent layouts is still a problem for me but WPF seems pretty nice.

**Comment by Ryochan7** [comment]
This is an old issue but now this problem is being tackled. A WPF version of DS4Windows is nearing completion. The plan is to release the final build as DS4Windows 2.0. The WPF build should be a lot better regarding scaling since the app uses the layout containers that WPF provides. It also performs better even regarding the mapping routine so perceived input latency has improved. Here is a link to the current WPF beta build.

https://drive.google.com/file/d/1Jq0jMmvj4jHUw2sq4nq9rCpdw1ZfTJtl/view?usp=sharing

**Comment by Ryochan7** [comment]
Version 2.0.0 is now online. The project has been rewritten to utilize WPF and I have seen that windows now scale much better than with the old WinForms build. Close to two years later and this issue can finally be closed.
