### ISSUE TITLE
Sony wireless adapter - double button presses?

### ISSUE THREAD

**Issue by McNippleson** [Ryochan7/DS4Windows#233]
I bought the official Sony wireless dongle since my cheap BT stick died. I paired DS4 and PC but now all buttons are being pressed twice. In a menu pressing DPAD down moves the menu two positions down etc.

I am looking through DS4W settings but don't see anything to fix this, does anyone know what to do?

**Comment by Ryochan7** [comment]
Is "Hide DS4 Controller" enabled in the Settings? It sounds like whatever game you are running supports both DirectInput as well as XInput. Without enabling exclusive mode and hiding the DS4 controller, the game will see two controllers: the DS4 (dongle) and the emulated Xbox 360 controller. If exclusive mode is enabled and DS4Windows can successfully obtain exclusive access to the controller, the game will only detect input from the virtual Xbox 360 controller.

Since you are a new owner of the official Sony wireless dongle, I should mention something about the device. You should take note that Windows actually sees the dongle as a DS4 controller even when no controller is synced to the dongle. If exclusive mode fails, you might have to try unplugging the dongle from the USB port and plugging it back into the port to have DS4Windows attempt to obtain exclusive access to the device again. Just running the Disconnect BT action and syncing the controller again won't help.

**Comment by McNippleson** [comment]
Thanks, I've used it for a long time in exclusive mode but it turned itself off somehow (same happens with white icon option all the time for some reason). Works fine now. Thanks for taking over and maintaining DS4W 👍
