### ISSUE TITLE
Not working in game "Last Stop"

### ISSUE THREAD

**Issue by miku1958** [Ryochan7/DS4Windows#2346]
**Describe the bug**
I am using DualSense to simulate Xbox controller, and I try to play a game named "Last Stop" in Xbox:
![image](https://user-images.githubusercontent.com/24806909/126869193-d1ca9fbd-9d20-4ad5-9aeb-2e1856ccd8a0.png)

It can recognized the Xbox controller, but I pressed the button and nothing happened.
Please let me know what setting info you need to know and I will add the screenshot.

Other games is working great.

**To Reproduce**
1. Go to Xbox
2. Open Last Stop
3. Contorller not working

**Expected behavior**
Contorller isworking

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense  (CFI-ZCT1W)
 - OS: [e.g. Windows 10 Pro Build 21H1]
 - DS4Windows Version [e.g. 3.0.13]

**Additional context**

**Comment by h1nnak** [comment]
In dark souls 2 I have to start the game first, then start DS4Windows and connect the controller. Maybe this will help you?

**Comment by mika-n** [comment]
#1196

**Comment by mika-n** [comment]
closed as inactive

**Comment by miku1958** [comment]
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6878414/ds4windows_log.txt)

Sorry for busy these days there is the log file.

@h1nnak Hi I test your sulotion and it is not working.

**Comment by mika-n** [comment]
`ViGEmBus 1.16.112.0 `
You have an old ViGem driver version. Update it to the latest 64bit x64 version.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

Anyway, don't see anything obvious in the logfile (except one warning about disconnection, but it was probably because you really disconnected the BT device).

When a gamepad is connected and DS4Windows app is running then what do you see in JOY.CPL controlPanel applet? Run this command to open the joystick control panel in WinOS. Do you see one or two gamepad devices?

And make sure you read the following post and understand the concept of "hiding the physical original gamepad and leaving just the virtual output controller visible for games"
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by miku1958** [comment]
Here is what I saw in controlPanel: ![image](https://user-images.githubusercontent.com/24806909/127023272-046a8067-a653-43d6-9cd6-f685efe4ca27.png)

I tried hide the DS4 controller and it has no help, I still can play this game with gamepad. Let me try to update the ViGem.

**Comment by miku1958** [comment]
Updating the ViGem is not helping.

**Comment by miku1958** [comment]
I can play other games with gamepad and they work great.

**Comment by Kanuan** [comment]
From your screenshots, your dualsense is still visible on the controller list, meaning it is still visible to the game and may be why you are having issues.

The most common approach, explained on the link mika-n has sent you somewhere above, is to hide the physical controller and leave only the virtual device, the emulated vbox controller that DS4Window creates, visible to the game.

Re-read the link mika-n has sent on her comment and try the hidhide method

**Comment by miku1958** [comment]
@Kanuan Thanks, it work.
