### ISSUE TITLE
Ds4 won't run unless Net 5.0

### ISSUE THREAD

**Issue by jdwill25** [Ryochan7/DS4Windows#2355]
Ds4 won't run upon opening
It happened after plugging in USB to play while charging controller.
'Microsoft.WindowsDesktop.App' version '5.0.0' was not found.

**To Reproduce**
1. Go to 'ds4 windows'
2. Click on 'ds4 windows application'

**Expected behavior**
Regular Ds4 controller menu pops up.
I hit start and controller connects.
I play game like usual.

**Screenshots and Logs**
![Screenshot 2021-07-25 120510](https://user-images.githubusercontent.com/87943996/126907374-e8423ede-185d-40fa-92a6-310ebb238a95.png)

 Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony dualsense ps5 controller
 - OS: [e.g. Windows 10 MSI Steel series GE66 Raider]
 - DS4Windows Version [e.g. 3.0.3]

**Additional context**

**Comment by Masamune3210** [comment]
.....then do what it says and install .NET 64-bit?

**Comment by jdwill25** [comment]
On Sun, Jul 25, 2021 at 4:38 PM Masamune3210 ***@***.***>
wrote:

> .....then do what it says and install .NET 64-bit?
>
well I left that part out because it goes without saying that would have
been the first thing to try. But even though I have it downloaded it’s not
acting like it and I’m not that tech savvy. I’m wondering if maybe I have
to move .NET into a different folder or something? I found a wired
alternative solution but DS4 was nice for the time.

**Comment by Kanuan** [comment]
You (probably) need [this version](https://dotnet.microsoft.com/download/dotnet/5.0/runtime) of the .net runtime:
![image](https://user-images.githubusercontent.com/24910442/126915579-f4cf729e-a08a-41d4-952a-4a85796587a9.png)

**Comment by mika-n** [comment]
As Kanuan pointed out this problem is often because of users installing either 32bit x86 version of .NET runtime libaries or just the consoleApps or serverApps version of .NET 5.x libraries.
- Forget those 32bit x86 versions of DS4Windows app, ViGem driver and .NET libraries. Download and install 64bit X64 file versions (ie. the installation package has X64 tag).
- From .NET 5.x runtime libraries you need to download the "for DESKTOP apps" version and not console/serverApps version.

In 99.99999999% cases the error msg shown is because of those two mistakes.

**Comment by mika-n** [comment]
closed as inactive and the problem was probably user installing wrong version of .NET libraries
