### ISSUE TITLE
Program not starting automatically with windows

### ISSUE THREAD

**Issue by powerpuffboysz** [Ryochan7/DS4Windows#236]
as the title says the program will not open automatically when my pc restarts even though the box for it is ticked. I even tried adding a manual shortcut to the startup menu myself and still nothing. if it helps i'm using windows 10

**Comment by DerpStation** [comment]
So, I managed to get it boot at startup, and here's how to do it.

- In DS4Windows check "Run at Startup" and choose "Task" rather than "Program" (out of personal preference)
- Place a shortcut of DS4Windows.exe in "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\"
- Add a registry string for it in "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" with the name DS4Windows and the string being the location of DS4Windows.exe with the exe at the end e.g. "C:\Program Files\DS4Windows\DS4Windows.exe"
- Reboot

**Comment by TristanYoung** [comment]
@DerpStation You should only need to click the "Run at Startup".  Having DS4Windows set to start up 3 different ways potentially all at the same time is redundant.  Find one method that works, and stick to it.  As the good ol' adage says, "keep it simple".

I run Windows 10, and prefer to have control over the startup.  I tend to create my own TaskSheduler entries to have programs start up at login with highest privileges.  Works just fine, and never need to fiddle with it.

If you want to try this method, press the Windows key + R to open the Run box. Type taskschd.msc and press Enter.  Then create a new task, set it with highest privileges, with the action to run ds4windows.exe with the trigger at logon.  Make sure you disable Run st Startup in the DS4Windows interface, and remove all other autorun entries where-ever you may have created them.

**Comment by UnluckyForSome** [comment]
Just FYI, thought this may help others with the same issue who are looking for a solution. For me, I had “Always run this program as Administrator” ticked, which was stopping the program starting on boot. Unchecked this and it works fine!
