### ISSUE TITLE
high laatency spikes

### ISSUE THREAD

**Issue by GalaxyDylan** [Ryochan7/DS4Windows#2363]
**Describe the bug**
extremely high latency spikes

**To Reproduce**
Steps to reproduce the behavior:connect controller and watch the delay. tried on multiple different controllers

**Expected behavior**
normal latency
**Screenshots and Logs**
![image](https://user-images.githubusercontent.com/87963761/127073750-f80a3214-3e4a-4dbb-bd6a-b1aed8298265.png)
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/6881781/ds4windows_log.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 
 -  - OS: [Windows 10 ]
 - DS4Windows Version [e.g. 3.0.13]

**Additional context**

**Comment by Kanuan** [comment]
Not DS4Windows fault. A good number of people have opened ssues around here describing the same problem and it all boils down to:
1) having a shitty integrated Bluetooth dongle (common for notebooks)
2) Having a bad BT dongle 
3) Having a good dongle but located somewhere on your PC with high radio interferance, sometimes caused by USB 3.0 ports by themselves (solution: try moving the dongle to another port or connecting it with a USB extensor)

**Comment by GalaxyDylan** [comment]
> Not DS4Windows fault. A good number of people have opened issues around here describing the same problem and it all boils down to:
> 
> 1. having a shitty integrated Bluetooth dongle (common for notebooks)
> 2. Having a bad BT dongle
> 3. Having a good dongle but located somewhere on your PC with high radio interferance, sometimes caused by USB 3.0 ports by themselves (solution: try moving the dongle to another port or connecting it with a USB extensor)

its not any  of these as the problems just started coming randomly. it worked fine for 3 ish days

**Comment by GalaxyDylan** [comment]
And it wont be a shitty bluetooth dongle

**Comment by mika-n** [comment]
Those BT issues are usually because of interference (in radio waves) or the BT chipset/dongle is not up to the task with high frequency DS4 gamepad in native DS4 mode (ie. native DS4 mode transfers a bit more stuff over the BT than PC-friendly default mode. DS4Windows uses native DS4 mode because otherwise touchpad/lightbar/rumble would not work).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#gamepad-connection-over-bluetooth-bt

Try the simple trick using BT dongle at the end of usb extension cable (ie. takes the dongle further away from the radio storm caused by PC chassis and closer to the desk level where you have the gamepad).

Anyway, not much DS4Windows app can do about it. You can try to untick "Enable output data" option in a profile (disconnect/re-connect the gamepad after changing this option) and test if latency is less serious when PC just reads data from the gamepad and doesn't write out data into the gamepad.
