### ISSUE TITLE
sensative/non responsive d-pad

### ISSUE THREAD

**Issue by powerpuffboysz** [Ryochan7/DS4Windows#237]
in some programs the dpad is completely disabled like in steam bpm and a few games. in sonic mania the dpad does work but is so sensitive the slightest push on any of the direction buttons makes the menu freak out

**Comment by Aaron-Ritter-IDEXX** [comment]
That doesn't seem to line up with my experience at all. Is this when using specific settings?

**Comment by powerpuffboysz** [comment]
no. for the most part I use the default profile that comes with the program. the only settings I've change are the run at startup box is ticked(something else I've unfortunately been having trouble with)

**Comment by Ryochan7** [comment]
The menu problem in Sonic Mania makes it sounds like it could be an exclusive mode problem. If the game is detecting both the DS4 controller and the emulated Xbox 360 controller input at the same time then that could explain the crazy behavior with the menu.

The Steam BPM issue that you described could be due to the mode change that occurs when DS4Windows detects a Bluetooth DS4 if Steam is using the DS4. Under the default mode, gyro data and touchpad data are not available in the input report so the requested input report type has to be changed in order to have access to that data. That can render any application that does not already have a handle on the DirectInput device to not be usable with it even after DS4Windows is closed; oddly, Steam can still detect the press of the PS button for some reason. If you want to actually use the DirectInput device associated with the controller, you have to disconnect and re-connect the controller.

**Comment by powerpuffboysz** [comment]
Thank you. Its working now. It was GeForce experience of all things causing me issues.
