### ISSUE TITLE
There is missing some funcionality

### ISSUE THREAD

**Issue by GeraltV47** [Ryochan7/DS4Windows#2370]
I found in DS4Windows some missing feature, when selecting the emulation of virutal conroller "Dualshock 4" option, there should be an option to emulate direct input mode for old games, which, should let for assigning to the sticks/triggers any given actions like on this picture:
![1](https://user-images.githubusercontent.com/75566547/127311884-31932033-0532-4b7b-b2f7-f45f0bcfcbe4.jpg)
I've found an excellent old game, future flight sim Echelon: Wind Warriors and assiging axies to given funcs is not allowed in this game, the right y axis is by default responsible for yaw(rudder) axis, the only way to change axies assignment is the controller software, like Better DS3 that allow to emulate DirectInput and also allow to assing any axis like on this picture, from X Axies to through sliders to the dial. Please help cuz playing some old games on my beloved DS4 gamepad is impossible. :(

**Comment by Kanuan** [comment]
This is not an issue, it's a feature request. As such, it should be moved to a [Discussion](https://github.com/Ryochan7/DS4Windows/discussions) topic. Since you are the OP of the issue, there is a button here somewhere that can be used to move it there.

Also, some of what you need can't be done because it's impossible to change the __layout__ of the emulated DS4 controller, and in the DS4 layout there are no (IIRC, I'm not sure) Slider or Dial axes.

All in all, there are other solutions that can be used to achieve what you want, like vjoy + UCR

**Comment by GeraltV47** [comment]
I mean that it would be possible when there would be option to emulate DirectInput mode that has axies like slider or dial, read correctly, and for sure it is possible, when in Better DS3 it is it should be in DS4Windows aswell.

**Comment by Masamune3210** [comment]
Thats not how anything works lol, just because one program supports it doesn't mean that all others want to or are required to

**Comment by GeraltV47** [comment]
I know that i can use software like vjoy, but id like to have all profiles being set up in DS4Windows and why implementing it in DS4W is impossible? Can someone explain me that? Im noob :)

**Comment by Ryochan7** [comment]
![hey-peter-whats-happening](https://user-images.githubusercontent.com/581968/127534854-e016687b-f255-465f-9d85-f7efd8f2dcdd.jpg)
