### ISSUE TITLE
Lightbar doesn't change to profile color

### ISSUE THREAD

**Issue by pedrovay2003** [Ryochan7/DS4Windows#238]
With the newest update, 1.4.115, when I wirelessly connect my controller (using the Sony adapter), the Lightbar stays the default color, and it doesn't change to the color I set in the active profile until I switch to a different profile and back again. It doesn't do anything functionally different, it's purely aesthetic, but I thought I'd point it out.

**Comment by ceedveed** [comment]
Same here. I'm also using the official Sony adapter. It works when using Version 1.4.113 though. 

Starting with Version 1.4.114, the lightbar color will not match profile setting. However, if you open the profile setting and start changing the lightbar settings, it will then work.

I reverted to 1.4.113 and it matches the lightbar color setting now.

**Comment by Ryochan7** [comment]
Version 1.4.114 and 1.4.115 are identical except 1.4.115 has the latest
updater version specified so the program will now if the updater should be
updated.

I have encountered the issue and it is due to changing how output reports
are sent for USB and SONYWA connections. The process was only tested with
USB connections. The Sony adapter isn't tested against that much and I
hardly use it in general. The sync process has been updated on my local
copy to force an output report update so that the profile lightbar color
will be used when syncing a controller to the adapter. The change will be
pushed to the repository shortly.

**Comment by shogunreaper** [comment]
i seem to have a problem with the lightbar coming back on every time i turn my controller back on from idle disconnect.

i just updated today so it's something recent, though i'm not sure what i was on before.

**Comment by fehmi1907** [comment]
I have a bug report - DS4Windows crashes if I launch Cemu with my DS4 turned off. I don't have any issues if DS4 is already on when I launch Cemu.

Below are from the event log:

`Application: DS4Windows.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at DS4Windows.UdpServer.NewReportIncoming(DS4Windows.DualShockPadMeta ByRef, DS4Windows.DS4State)
   at DS4Windows.ControlService.On_Report(System.Object, System.EventArgs)
   at DS4Windows.DS4Device.performDs4Input()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()`

**Comment by pedrovay2003** [comment]
Thanks a ton for looking into this!

**Comment by Ryochan7** [comment]
The new releases fixes this issue.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.4.116/DS4Windows_1.4.116_x64.zip
