### ISSUE TITLE
Loss of control - analog sticks

### ISSUE THREAD

**Issue by TristanYoung** [Ryochan7/DS4Windows#24]
Hi, thank you for continuing on the project.

I discovered your updates, and thought I'd give it a try.  Unfortunately my analog sticks aren't working anymore with your updates.

The original DS4Windows I was using has no issues, and reverting to the original version corrects the behavior.

I notice that when I go in to DS4Windows (your latest version) and have it show me the controller's outputs, both analog sticks appear to be working correctly - the movements are detected.  I double-checked my mapping (should be default), and they seem fine.

Buttons seem to work - I can lob arrows into my enemies no prob, as long as they are directly in-front of me, and they're willing to seek me out :)

**Comment by Ryochan7** [comment]
Are you running version 1.4.64 that was just released? I tried remapping some analog stick directions and I haven't encountered a problem with it. Can you post the profile that you are using that is having problems?

**Comment by TristanYoung** [comment]
Sure thing, and thank you for responding.

Profile has been attached.

I should point out that I did try a previous version of yours perhaps 2 or 3 revisions ago, and my x-axis analog sticks operated backwards, so I had to move the stick to the left to get it to go right.  Again, reverting to the last Jays2Kings version restored proper functioning.  I wonder if this "alternate behavior" is related.

**Comment by shinra358** [comment]
Same here. Deals with the quick charge fix. Just tried a game after trying to get controller to work again. Plugged only because I can't get bluetooth xinput to work anymore, buttons seems to function but I can't move the character because analog sticks don't do anything.

**Comment by Ryochan7** [comment]
I found the reason that the axes were inverted before. An option was enabled for the wrong directions of LX so the mapped values were inverted. Other axes bindings worked for me. Since the bindings are not using any extras, as a workaround, you can either click the default button on the mapping window for those directions or reassign the mapping; with the last few versions, assigning a control to the default Xbox 360 mapping does the same behavior as clicking default. That removes any explicit action for that control which will save processing time.

**Comment by Ryochan7** [comment]
Looking back to previous versions, version 1.4.62 and 1.4.63 were affected by this problem. It was due to using the wrong object to check for active actions. The output state was being used and problems would happen when resetting a control to its default value for Xbox 360 mapping routines. Several control mappings were affected by the problem (Analog sticks, Cross, Circle, Dpad, extras execution). 1.4.64 only has a problem with LX values being inverted. This has all come about due to trying to optimize the mapping methods being used and failing in the process.

**Comment by Ryochan7** [comment]
Version 1.4.65 is now out and it should fix this problem completely. I have tested switching out the controls for the two analog sticks and controls worked as expected.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.4.65/DS4Windows_1.4.65_x64.zip

**Comment by shinra358** [comment]
Would love to test but all I'm getting now is this:

Application: DS4Windows.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   at DS4Windows.BackingStore.LoadProfile(Int32, Boolean, DS4Windows.ControlService, System.String)
   at DS4Windows.Global.LoadProfile(Int32, Boolean, DS4Windows.ControlService)
   at DS4Windows.DS4Form..ctor(System.String[])
   at DS4Windows.Program.Main(System.String[])


Is it something with my .net runtimes? Or is it something with the program?

**Comment by Ryochan7** [comment]
Can you post the profile being loaded at startup and all your special actions? The error seems to indicate that the program fails when a duplicate key is attempting to be inserted into a dictionary in the LoadProfile method. I am assuming that this has to do with the special actions that are assigned in the configuration.

**Comment by shinra358** [comment]
haven't touched these in ages: https://mega.nz/#!f49UgBiS!8v5E1AAhUTnK86_BuZ-Y32nw_Op9NydZ5DowGbBJEE8

**Comment by Ryochan7** [comment]
Looking at the issue, I don't know how your profiles worked as long as they did. These profile must have been from an older version before some safety checks were put in place. The same ProfileAction is listed twice in all your profiles. That would explain the error that you are encountering. You would have to fix the profiles by hand in a text editor.

Change

```<ProfileActions>Disconnect Controller/Disconnect Controller</ProfileActions>```

to

```<ProfileActions>Disconnect Controller</ProfileActions>```

One way to work around the issue in the code would be just to overwrite a duplicate action in the dictionary with the newer version.

**Comment by shinra358** [comment]
"These profile must have been from an older version before some safety checks were put in place"
Yep, from the very beginning. No one ever said to go in and change anything. Thought the program would have done all of that itself if need be. : P

Fixed that, now it keeps telling me 'specified argument out of range'. But before that, it was telling me that it couldnt find the scp drivers that I just installed.

**Comment by Ryochan7** [comment]
Profile Action names are supposed to be unique and some parts of the code did enforce that. One big problem is that the ListView being used to display the actions used to create duplicate entries in some cases. That issue was corrected but that doesn't help old profiles. The restriction is now enforced when loading profiles now and the unedited versions of the old profiles now load properly.

**Comment by TristanYoung** [comment]
Hi!  Sorry for my absence, been a very busy week.

Understood about all the changes and improvements.  I'll check out the new version.  Thank you for improving DS4Windows.

**Comment by TristanYoung** [comment]
Definitely fixed things.  Thank you.

**Comment by shinra358** [comment]
yeah, analog stick portion is fixed.

**Comment by Ryochan7** [comment]
@shinra358 Found the problem about 'specified argument out of range' and worked around it. IEnumerable does not work as documented after opening an HidDevice for some reason.

**Comment by shinra358** [comment]
bluetooth xinput isn't registering at all on any controller now. not even it a glitchy state. xinput on wired is now broken (breaks randomly). On any xinput port (we really gotta get rid of the port thing, it's making things way too complicated. I don't think input mapper has this.). Everything else seems fixed as the update set out to do.
v1.4.67

**Comment by Ryochan7** [comment]
There are a couple of tasks that could be tested. Here is a build with some minor changes and several extra log messages added. Please refer to the log tab and check the messages that are posted.

https://drive.google.com/open?id=0B6yGHDx0CFzDYXJGN3RwRXdmc0U

InputMapper does not have a configurable setting for the xinput port starting number but Device Manager shows that InputMapper starts the SCP Virtual Bus Driver using port 11.

**Comment by shinra358** [comment]
![clipboard02](https://cloud.githubusercontent.com/assets/3978291/25568050/c4b7888a-2dc8-11e7-8aa6-b3990d68ef4a.png)

Im on port 11 and usb seems to be working again but it's only reading as 1 xbox controller when 2 are plugged in. There is nothing out of the ordinary in the logs for plugged or unplugged even though bluetooth mode still doesn't work.

**Comment by Ryochan7** [comment]
A critical bug with Exclusive Mode was found last night. This problem affected older versions as well and was the leading cause for controllers becoming unintentionally disabled; it would also affect controller detection. The problem was due to the hotplug routine getting executed multiple times at the same time after launching a background process. This problem would not affect people who run DS4Windows as the administrator.

https://drive.google.com/open?id=0B6yGHDx0CFzDNWtvZkk1SW1mdVU

The touchpad portion should work per controller so there should be no reason that only one touchpad would work. There doesn't seem to be anything wrong with that portion of the code. I only have one DS4 controller so I can't test that problem out on my end.

**Comment by shinra358** [comment]
![joe](https://cloud.githubusercontent.com/assets/3978291/25601980/15fd0666-2ebe-11e7-8bd1-8f65cd5059cf.png)

Still a no go. each controller individualy show nothing in joy.cpl. wire nor bluetooth. Until I hook 2 controllers up and then only one xbox controller shows. port 11.

"This problem would not affect people who run DS4Windows as the administrator."
affected me regardless.

"The touchpad portion should work per controller "
never has for me. for any version. not even input mapper. only the very first paired controller seems to control the mouse.

**Comment by shinra358** [comment]
![bona](https://cloud.githubusercontent.com/assets/3978291/25602526/ab274766-2ec2-11e7-9e60-edc0db4ee585.png)

Also, ds4 always starts on the 2nd tab instead of the first when opened.

And is 'use controller [] for mapping and readout []' supposed to be shared through every profile? If you try to make the settings separate in each profile, you can't do it because the other profiles always get the changes.

**Comment by Ryochan7** [comment]
It looks like 'Use controller [] for mapping' is only really used in the Options form. It has no impact anywhere else in the program. The '...and readout []' portion is supposed to be an application setting rather than a profile setting. That option should not be in the Options form at all and it doesn't do anything.

**Comment by shinra358** [comment]
Topic seems fixed. I'll put the cursor problem in a new posting.

**Comment by Ryochan7** [comment]
I will make a new issue about the mapping problem since that still has to be reviewed. This issue can be closed since the core problem has been addressed.
