### ISSUE TITLE
Two Stage Mode does not use raw input for activation

### ISSUE THREAD

**Issue by ChocoChopin** [Ryochan7/DS4Windows#2419]
Two Stage Mode only registers a "full pull" state if DS4win's own output registers a full pull.

This means, for example, that if you lower your sensitivity or max output for that trigger, it becomes impossible to use the two stage mode feature, as it'll never register.

It seems to me like what _should_ happen is that a raw input state of 255 activates the full pull, regardless of what DS4win is presenting to other applications.

As an example of how this poses a problem, here's what I'm trying to do: in RDR2, the R2 trigger can register two distinct states, where a slight pull will ready the weapon at the hip, and a very slightly greater pull will fire it, all very near the top of the trigger's full range. It'd be nice if it were possible to ensure that only the very bottom of the pull actually fires, especially in tandem with the full click haptic trigger setting of the DualSense, which under the right circumstances creates a pretty realistic feeling of a trigger pull. This is difficult to attain with sensitivity and curve response settings alone, however, because different weapons have different analog sensitivities in the game, so if you set it just right for one weapon, it won't work properly for another. 

The simple solution to this would be to use the two stage mode setting to trigger a left mouse click at the bottom of the trigger pull, and make everything short of that a sort of half-pull that won't accidentally fire any of the in-game weapons, but it's impossible to use DS4win's two stage mode feature without actually sending a full pull to the application you're using. I have a hard time understanding why two stage mode isn't just using the controller's raw input.

**Comment by ChocoChopin** [comment]
Is there any particular reason that this was marked invalid?

**Comment by Ryochan7** [comment]
Then you end up with a problem once the trigger can no longer reach that 255 threshold; that is probably not as big of a problem with the DualSense since the controller hits 255 pretty early before the physical trigger limit is reached. As it is, Full Pull is busted if Max Output is not set at 100%.

Been trying to work on a different interpretation of Dual Stage Trigger output. Some of these situations would be a bit different as I am mapping against a Steam Controller and actually having a hard click output button exposed with the trigger requires different behavior. One change I will likely carry over here is to allow the Hip Fire Delay to be skipped if the Full Pull threshold is achieved early. Still working on changing how the Soft Pull range works but more Full Pull options would have to be added as well.
