### ISSUE TITLE
"Load profile" special action does not change profile in Controllers screen

### ISSUE THREAD

**Issue by reyaz006** [Ryochan7/DS4Windows#2420]
I'm seeing that the right profile is loaded fine when I trigger this special action, but it's not reflected in the GUI. Should it? I thought it should.

**Comment by mika-n** [comment]
SpecAction.LoadProfile doesn't change the default profile type because specAction loads a "temporary profile". The value of temporary profile is not set as a default profile the next time you startup DS4Windows app.  This is by design.

Command line interface does have both LoadProfile and LoadTempProfile options, so if you need to do something more fancy then you could run a batch script in specAction and use a cmdline interface to tweak DS4Windows runtime settings.
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options
