### ISSUE TITLE
ps4 Controller connects and disconnects right away in bluetooth

### ISSUE THREAD

**Issue by DaNiNeX** [Ryochan7/DS4Windows#2422]
I've deleted the entire program, drivers included, several times today and reinstalled lastest version.
I've re-paired the controller several times and i've also reset it.
I can pair my controller to windows but it disconnects right away.
(Works fine by cable, no issue whatsoever)

Worked fine yesterday, now it gives me a error.

log:
[a.txt](https://github.com/Ryochan7/DS4Windows/files/6951401/a.txt)

Im lost on what else to do..
Thanks in advance!

**Comment by mika-n** [comment]
Purchase a genuine DS4 gamepad and not a cheap copy-cat. In 99.999% cases like this the problem is with those fake copy-cats not following official ds4 firmware communication protocol especially in BT. Don't support those thiefs by purchasing a fake ds4 gamepad (=those may look like the genuine thing but the firmware and hardware inside is not 100% real thing). Or complain the dealer or manufacturer responsible of the gamepad.
