### ISSUE TITLE
Hide DS4Windows not working

### ISSUE THREAD

**Issue by JenomCMS** [Ryochan7/DS4Windows#2423]
I have been using a DS5 in ds4windows for a long time and i have never had problems. About a week my Hide DS4 Controller stopped working. Whenever i clicked on the button it would ask me if i gave permission (the windows administrator pop up) and i would here the sound as if i was connecting something to my computer.
Now, whenever i click the button the controller's light flashes and it doesn't work. I close Nvidia container every time before launching so i dont know what else it could be.
Any idea?

**Comment by Kanuan** [comment]
The hide ds4 controllers is not recommended, use hidhide.

Read the following link carefully, it has all the answers you need

https://kanuan.github.io/DS4WSite/guides/solving-double-input/

**Comment by mika-n** [comment]
And few more tips and explanations here: https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

But i'm closing this ticket because if the "Hide DS4 Controller" option (=exclusive mode to hide the original physical gamepad) doesn't work then is a just workstation issue and not DS4Windows app issue. Read those linked docs several times to make sure you understand why it is like that.
