### ISSUE TITLE
Losing Features On DualSense Controller When Wirelessly Emulating DualShock 4

### ISSUE THREAD

**Issue by coopermf** [Ryochan7/DS4Windows#2433]
I have been setting up auto profiles for games that automatically detect controllers so that I'll get PlayStation button prompts when using my DualSense controller, then I noticed that this killed the rumble feature in games like Hitman 3 and AC Valhalla. At first I thought that the games just didn't implement it properly on PC but with some more testing I found that when connected over USB it worked properly with vibration, and to my surprise even adaptive triggers seemed to be working in Valhalla. So this leads me to wonder would it be possible for DS4Windows to give DualSense controllers full features when connected wirelessly or is not something that DS4Windows would be capable of solving?

**Comment by mika-n** [comment]
#1196 

Depends on the version of DS4Windows app you have. Lightbar-passthru and rumble has been disabled on purpose in the latest version when a profile uses dualshock4 output mode. It is because of few problems with the current version of DS4Windows app and ViGem virtual gamepad driver. Until those issues have been solved the current version doesn't have rumble in ds4 output mode (rumble works only in xbox360 mode).

If there is a difference between how rumble works over BT and USB it means that the physical gamepad is not hidden. 
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by coopermf** [comment]
Thanks for info, I'm on the most recent version (3.0.16) and strangely enough I do have the hide DS4 controller option checked but I guess that doesn't effect the controller when connected via USB. I appreciate all the effort you guys are putting into working out the bugs with dualshock4 output mode. Do you guys have any plans in the future to implement DualSense features like adaptive triggers over BT?

**Comment by mika-n** [comment]
Use the search bar (on top left corner) to find old commetns about adaptive triggers.
https://github.com/Ryochan7/DS4Windows/search?q=adaptive&type=issues

Anyway, the problem is that DS4Windows+ViGem combination supports only xbox360 and dualshock4 as an OUTPUT virtual controller type and those controllers don't have adaptive triggers concept at all. Games will see the (virtual) gamepad as either xbox360 or dualshock4 even when the physical gamepad would be DualSense, so games probably won't try to tweak triggers because they think you are using xbox or ds4 gamepad.
