### ISSUE TITLE
Does not work when the Wise Auto Shutdown program window is open

### ISSUE THREAD

**Issue by Logonoff410** [Ryochan7/DS4Windows#2445]
Does not work when the Wise Auto Shutdown program window is open. When the program is minimized to the tray, everything is fine

**Comment by Ryochan7** [comment]
I would have no idea why.

**Comment by Yohoki** [comment]
I've had this happen with a few programs. Try running DS4Windows as administrator. I usually see this when DS4Windows is not run as admin, some programs that run as an admin will block inputs from the controller. I can't remember if this is what fixed it for me, because I haven't seen it happen in a while.... But I think this is what did it, because it was important things, like my virus scanner (running in admin mode) that would block inputs.

- Right click DS4Windows.exe
- Properties
- Compatibility
- Tick "Run as Administrator"
- Apply and restart DS4Windows

The checkbox should persist through updates, so you shouldn't have to fix it after every update.

**Comment by Logonoff410** [comment]
Yes! it works. Thank u!
