### ISSUE TITLE
Macro works only once

### ISSUE THREAD

**Issue by chance-an** [Ryochan7/DS4Windows#2448]
**Describe the bug**
Setting a macro to a button makes it to trigger only once.

**To Reproduce**
1. Click a button to map
2. Start `record a macro` , record a macro and save.
3. See that macro is not triggered
4. Restart DS4Windows
5. See that macro works once by pressing the button
6. The macro doesn't work for a second time. Restarting enables to work once again.
7. Restarting using administrator mode makes no difference

**Expected behavior**
The macro should trigger every time I press the button.

**Desktop (please complete the following information):**
 - Controller Make and Model: DualShock 5
 - OS: Windows 10 Pro Build 19044.1706
 - DS4Windows Version :3.0.18
**Additional context**

**Comment by Ryochan7** [comment]
Last I knew, macros still worked. Tbh, I have discouraged the use of macros almost since the start of this fork. It was only left in for backwards compatibility with the original Jays2Kings build (1.4.52).

I would assume macros still work as designed due to CoD players crying about macros being a cheaters dream and delegating DS4Windows as purely a cheating app; nevermind Steam Input and reWASD would be able to pull off similar tricks. I will check and make sure macros can still be fired multiple times.

**Comment by Ryochan7** [comment]
Sequential executions of macros is working on my end. Can you share the profile you are using so I can test it out?

**Comment by chance-an** [comment]
Of course. (please remove the `.txt` extension or GH would not allow me to upload)

[p1.xml.txt](https://github.com/Ryochan7/DS4Windows/files/9076593/p1.xml.txt)
