### ISSUE TITLE
Add button to re-launch ds4windows as admin

### ISSUE THREAD

**Issue by soredake** [Ryochan7/DS4Windows#2461]
**Describe the bug**
Right now ds4windows does not have a useful button to re-launch itself as admin (to be able to set "run as" settings to "task" )

**To Reproduce**
1. Launch ds4windows as non-admin
2. Go to settings
3. There is no button to relaunch ds4windows as admin

**Expected behavior**
Have a button to re-launch ds4windows as admin.

**Screenshots and Logs**
Another software, powertoys, for example have a button to do this.
![a-windows10-powertoys-v45](https://user-images.githubusercontent.com/5204968/178153483-09fb2cc3-ebd0-4e21-9850-ffac3b3d8de4.jpg)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 11 Pro
 - DS4Windows Version 3.1.0

**Additional context**
https://www.reddit.com/r/pcgaming/comments/ety52y/psa_disable_the_uac_popup_for_ds4windows/ffje111/

**Comment by Ryochan7** [comment]
I have been starting to remove some code complexities and workarounds mainly needed when DS4Windows was run as the Administrator. I would be more likely, at this point, to remove the Run As Task option entirely rather than add a feature like that into the code. For me, running as Administrator was mainly useful to work around SendInput issues with games that run as Admin; the main example I always think of is Mass Effect 1 Classic.

Using the FakerInput driver removes the need to do that and it also works around UAC prompts which running DS4Windows as Admin cannot handle. Haven't had a need to run DS4Windows or my test mapper as the Administrator since releasing that driver.

**Comment by soredake** [comment]
I've installed fakerinput, but after connecting gamepad i still get UAC prompt.

**Comment by soredake** [comment]
Can ds4windows installer install fakerinput by default?

**Comment by Ryochan7** [comment]
It is available under the same dialog window listed as Step 5. The driver is listed as Optional and it is probably better to not make it a set requirement since it cannot be actively maintained right now (no OV cert). Luckily it is a user-mode driver so there should be far fewer problems when it comes to Windows updates. Still working on fully utilizing the driver in its current state.

Been thinking about this and I think I will keep the current Run As Task option available; there would be minor benefits to removing the Task Scheduler package from the project. Not going to worry about adding an extra option to force Explorer to launch DS4Windows as the Admin though. That will continue to be left up to the user.

**Comment by Ryochan7** [comment]
https://github.com/microsoft/PowerToys/issues/3239

Complain about false positive VirusTotal results and then asks for potential features that will guarantee more false positives to show up. All while keeping me from getting a code signing certificate that would help such false positives go away all together.
