### ISSUE TITLE
Gioteck VX-4

### ISSUE THREAD

**Issue by jacho981** [Ryochan7/DS4Windows#2476]
**Describe the bug**
I just bought a Gioteck VX-4, because it was in your "compatible controllers" list. But apparently windows detects it as an XBOX controller, which would make it not compatible? DS4 is not detecting it so i guess, that's the case. 

It's wierd because it says literally "Gioteck VX-4 Premium Wireless Controller for PS4, PS4 SLIM, PS4 PRO and PC", so it sounds wierd to me that it gets detected as XBOX controller....

So i think you should update your list, unless you can tell me there's a workaround for this issue, Just wanted to inform, so it doesn't happen to anyone else. Also, if you could point me to a software that could enhance my input lag for an xbox controller i'd be so thankful, because i'm pretty new to controller world. 

**Desktop (please complete the following information):**
 - Controller Make and Model: Gioteck VX-4 Premium Wireless Controller for PS4, PS4 SLIM, PS4 PRO and PC
 - OS: Windows 10 PRO 21H2
 - DS4Windows Version 3.1.0

Thanks for your attention.

**Comment by Ryochan7** [comment]
Personally I disavowed almost all 3rd party controller support a while ago. It is up to the community in order to help provide support for hardware I do not own. Since people have not done so, I will just remove that entry in the table and the info in DS4Windows if it still exists. The only ways to help the situation would be to either debug DS4Windows on your machine or gift me a Gioteck VX-4 for my own use.
