### ISSUE TITLE
Controller Disconnects and Reconnects every time I switch application windows

### ISSUE THREAD

**Issue by PADBX** [Ryochan7/DS4Windows#2489]
When my controller is connected via Bluetooth, it disconnects and reconnects every time I switch application windows.

**Comment by Yohoki** [comment]
Is it disconnecting, or switching between DS4 and XBOX mode? That might just be normal behavior. Easy to fix if that's the case. But we'll need more info to find if that's the problem and to fix it. Log files would help here. Turn on Auto-profile debug logs and try making this disconnect happen a few times and send the logs, please.

### Turn on Auto-Profile Debug Logging
- Click "Auto-Profile" Tab
- On the Right side of the tab, scroll to the bottom and tick the "Show Auto-Profile Debug Messages" Box
![image](https://user-images.githubusercontent.com/44595371/181353276-7fa936d5-ec91-4a78-88ad-52aa8aa77199.png)

### Log Files
- Log files are located at "%AppData%/Ds4Windows/Logs" or "C:\Users\USERNAME\AppData\Roaming\DS4Windows\Logs" on windows.

**Comment by PADBX** [comment]
Will try to. Interestingly enough after fully charging the controller the problem went away. It also went away when I checked off "Hide DS4 Controller". Does it help to say that the controller is third party?

**Comment by Yohoki** [comment]
Hide DS4 (Exclusive mode) has some issues. Unless you need it on (And know WHY you need it on), it's usually best to keep that off. HIDHide is a much better tool to use. But I don't know of that causing issues that would disconnect a controller.

I'm not familiar with how 3rd party controllers work, If it's a supported controller, it should just work like a regular controller. But I have no idea how 3rd party controllers that aren't specifically supported work. I don't think that would cause them to disconnect on switching tabs, though. That sounds like the auto-profiler is affecting it.

If the battery was low, it might have turned off the controller, but I wouldn't expect it to auto-reconnect without you hitting the button.

So, the biggest flag that's sticking out to me is your auto-profile and profile settings. Turn on those debug messages, and next time it happens, send me those logs and I'll check them out for you. Happy gaming, until then! :)

**Comment by Ryochan7** [comment]
> Will try to. Interestingly enough after fully charging the controller the problem went away. It also went away when I checked off "Hide DS4 Controller". Does it help to say that the controller is third party?

I don't recommend using the old "Hide DS4 Controller" workaround anymore. People didn't like when I removed the workaround previously so that is why it still exists in the app. Some apps can actually still detect the controller (probably if not using the HID interface) and force attempt to open it. It can cause some games (Broforce) to hang for a while before startup.

Using HidHide is the recommended way to hide the input controller from other apps on your system. Install that driver and use the bundled configuration utility to hide the device. Make sure to disconnect and then re-connect the controller to ensure the changes take affect. DS4Windows should show a key icon in the main controllers listing if it can find a entry for the input device in HidHide.

https://github.com/ViGEm/HidHide

**Comment by PADBX** [comment]
So I have the log of it happening again after letting the controller die.
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/9296884/ds4windows_log.txt)
