### ISSUE TITLE
doesn't work on valorant anymore

### ISSUE THREAD

**Issue by NustyFrozen** [Ryochan7/DS4Windows#2524]
since last update the app doesn't work on valorant

**Comment by Masamune3210** [comment]
Make sure hidhide is enabled

**Comment by Ryochan7** [comment]
Haven't tried Valorant in a while and I don't have it installed currently. The last time I tried, they put an extra "security measure" to only allow one mouse pointer to be usable in the game. The game will use the first mouse device it detects events on from the launcher IIRC. If you use a normal mouse then the virtual mouse will not work. If the game uses the virtual mouse then you cannot switch to a real mouse device while in game.

Not sure if you are running into that or not. Would have to reinstall the game to confirm.

**Comment by NustyFrozen** [comment]
yea, the game detects on the last update only 1 input from mouse device

**Comment by Kanuan** [comment]
The instructions in the "Game doesn't respond to DS4W's KB/M commands -> Special cases" SECTION of the following page worked for me a while ago: [Keyboard & Mouse (KB+M) remapping issues](https://docs.ds4windows.app/troubleshooting/kb-mouse-issues/#special-cases-valorant-and-possibly-others)

**Comment by Ryochan7** [comment]
Finally got a chance to test this. The behavior in Valorant has not changed since I previously tested it. You have to use the virtual mouse exclusively upon launching the Riot Client. It limits input to the first device the client detects events from.

Also, it is not stated in the OP what event generator was used and no log was given so I should add a note. You must be using the FakerInput driver to have any hope that virtual mouse events will work in Valorant; SendInput will **NOT** work. That note is mentioned in the initial driver install screen.
