### ISSUE TITLE
HID-Compliant - This device is disable. (Code 22)

### ISSUE THREAD

**Issue by pralima87** [Ryochan7/DS4Windows#254]
Sorry to ask this if it was already answered.
For some reason the driver of "HID-compliant game controller" gets disable/paused.

When this happens the controller stops working and the lightbar shows a white color.
Is like the controller is connected but not properly detected.

To fix this the HID drivers require a manual disable/enable.
Sometimes a system restart.

Is this fixable?
Could it be related to HID guardian?

Here is a image of the issue:
[https://flic.kr/p/24C4LD4](https://flic.kr/p/24C4LD4)

**Comment by pralima87** [comment]
This issue is addressed in the main description.
Sorry for bothering.

**Comment by Ryochan7** [comment]
The problem happens with the old exclusive mode hack. Although attempts have been made to minimize the problem, it seems like an inherit problem with using that method as Windows can perform some bizarre behavior; the last issue that was addressed in the program was Windows sometimes disabling a device again once it was unplugged. Using HidGuardian is a way around this problem.

**Comment by pralima87** [comment]
Humm but is HIdGuardian its own app or is it integrated in the DS4Windows tool?
Should I un-stick the option "Hide DS4 Controller"

**Comment by Ryochan7** [comment]
HidGuardian is an HID filter driver that has to be installed. DS4Windows just writes the necessary registry entries that HidGuardian looks for when the HidGuardian routines are run. Because DS4Windows has to edit the system registry, DS4Windows has to be run as admin in order to be able to utilize HidGuardian.

The "Hide DS4 Controller" option can still be checked even while HidGuardian is being used. The old hack should not end up executing since DS4Windows should be able to get exclusive access to the device on the first attempt opening the device.
