### ISSUE TITLE
Intermittency when trying to connect in exclusive mode

### ISSUE THREAD

**Issue by gilgamar** [Ryochan7/DS4Windows#2541]
Since the last patch I've been noticing inconsistency when connecting my ds4 controller in exclusive mode. Most of the time it's falling back to shared mode and I can only manage to get exclusive mode to connect after toggling Bluetooth off/on, ds4windows stop/start as well as toggling "Hide DS4 Controller". It'll still fail to get exclusive mode after trying all of those but once in awhile I can get it to catch the controller in exclusive mode. This hadn't been an issue prior to the most recent update so I suspect it may be a new bug. Let me know what extra details you need to help identify the problem.

**Comment by Kanuan** [comment]
The `Hide DS4 Controllers` option is a legacy, non-recommended option that can fail to work for many reasons (Windows will deny the Exclusive Access request). Because of this, it should not be used anymore.

This option is used to prevent the "double input issue", but there is a better, more reliable way to solve it. If you are on a x64 (64 bits) system, the recommended approach is installing and configuring HidHide to hide, at all times, the __real__ controller being used from everything on the system except DS4Windows.

- Check the [_Preventing the double controller / double input issue in games_ guide](https://docs.ds4windows.app/guides/solving-double-input/)
    - After installing HidHide the user __must reboot__ the system

**Comment by gilgamar** [comment]
@Kanuan Thanks for the swift reply. It sure seems like something in Windows is trying to grab the controller before DS4Windows can. I found if I stop ds4windows, connect the controller and then start ds4windows it'll catch the controller in exclusive mode. This is a bit of a pain so I'll look at the HidHide option. Thanks again.
