### ISSUE TITLE
[Feature request] Connect without emulation

### ISSUE THREAD

**Issue by avi12** [Ryochan7/DS4Windows#2544]
I have a DualSense (PS5) and a DualShock (PS4) controllers
I'm often connecting the DualSense directly through Steam, which results in some games recognizing it as a PS controller accordingly
If I want to check the battery level, I do it via [DualSenseX](https://github.com/Paliverse/DualSenseX), as it has a feature that does not emulate the DualSense as an Xbox controller

What I like about DS4Windows is that I can connect both of my controllers to the app simultaneously, which does not seem possible via DualSenseX

Is it possible for DS4Windows not to emulate the controller as an Xbox controller?
If so, I can ditch DualSenseX in favor of DS4Windows

**Comment by Masamune3210** [comment]
There is a option to change the emulated controller, you have the option of a DualShock 4 or a Xbox controller

**Comment by Kanuan** [comment]
It's complicated because:

1. Steam starts ignoring every DS4/DualSense controller, real or emulated, when it detects DS4Windows is running
2. Even with no controller emulation DS4Windows still has some default settings related to mouse and profile switching that need to be disabled

All in all, it's possible to do what you want. Follow the "Disabling almost every DS4Windows functions (use real controller directly with Steam Input or other app without interference)" SUB-SECTION inside the "Other" SECTION in the following link: [Preventing conflicts between Steam and DS4Windows](https://docs.ds4windows.app/guides/prevent-steam-conflict/#other)

**Comment by SiTWulf** [comment]
@avi12 I have the same problem (But with Marvel Spiderman game)
For me the only solution is using AutoProfiles with the option "Turn Off DS4Windows Temporarily", when DS4Windows detect the Game Launched, disables emulation and let the DualSense (Using USB  Cable ONLY) to work like DualSense in the game.

@Masamune3210 These is not a correct solution, we need DUALSENSE (PS5) not DS4 (PS4), using the emulation DualSock4 only get the Gamepad Icons, but not Haptic Feedback or Adaptive Triggers.

@Kanuan Not really complicated.

**Comment by Ryochan7** [comment]
> DualSense directly through Steam, which results in some games recognizing it as a PS controller accordingly

Only for games with direct SIAPI support which is a very small list. For the most part, you are going to get Xbox controller emulation when using the Steam Input mapper. Even when playing games with direct SIAPI support, you are going to have a translation layer in place that handles in-game action mapping and displaying the appropriate button glyphs when possible. Besides, I have hardly ever had a native SIAPI game work as intended; not even flagship Valve titles like Portal 2 or Left 4 Dead 2 work as intended when using SIAPI support.

If you really just want just a battery level display, you need to use a profile with the **Disable virtual controller** option checked. That option will unplug any virtual controller associated with the input controller if one exists. You would be limited to mapping KB+M actions but you can disable those mappings if you want as well. Other than the **Custom Exe Name** option, there is nothing to do for games that natively support SIAPI that use Valve's DS4Windows (and InputMapper) block built into the Steam client. That is entirely on Valve.

**Comment by Ryochan7** [comment]
Also should point out that Xbox controller emulation does not even work as intended in the Steam Input mapper after all these years; I make sure to confirm it every once in a while. That mapper is still using the output range [-32767, 32767] for axis interpolation rather than [-32768, 32767]. That one extra unit in the negative direction does matter in some games if you want the camera to pan left at full speed.

**Comment by avi12** [comment]
> you need to use a profile with the Disable virtual controller option checked
@Ryochan7 After doing so, it does not seem like the PS button is working, i.e. I cannot launch into Big Picture mode
