### ISSUE TITLE
DS4Windows Static Constant Beep noise coming from Speaker on Copy/Fake PS4 Controller

### ISSUE THREAD

**Issue by dissidius** [Ryochan7/DS4Windows#2547]
Hello Legend!

Issues in issue number #2493 are still present even on latest version of DS4Windows 3.1.3!

Is there anything planned for solving it?

Cheers and Best regards

**Comment by Yohoki** [comment]
It looks like Ryochan's about to transition to a new version of ViGEmBus driver, and won't have to deal with the output reports not working as intended. So, fixing issues with the current driver are probably not a priority.

For now, be patient, and let's try not to open another issue for one that's already been created. When the next version that includes a ViGEmBus update comes out, if you still have the issue, that would be the time to bring it up.

**Comment by Ryochan7** [comment]
There is pretty much nothing to be done. There needs to be a way to distinguish between a fake and a real DS4 and I am getting no help on the matter. I am not going to ruin my own experience because you tried to buy a cheap knockoff that probably does not work 100% on a PS4 console either. Either you have to help debug DS4Windows on your machine or gift me a controller for my own use.

**Comment by dissidius** [comment]
I finally found what couses the issue!

It is just this line of code in DS4Windows-3.1.4\DS4Windows\DS4Library\DS4Device.cs:

outReportBuffer[2] = 0xA0;

Removed this and rebuild the app and no more noise and everything freaking works so 0x11 or 0x15 and had nothing  to do with it to begin with !!!!!!

Cheers and Thanks legend @Ryochan7
