### ISSUE TITLE
how to add Elden Ring 

### ISSUE THREAD

**Issue by PrestigeDevop** [Ryochan7/DS4Windows#2552]
it doesn't work on Elden ring ? 
Ive add the program and map a profile however it still doesn't recognize the input mapping  I've fixed this issue using other program (x360ce.exe) but its annoying to use and almost always break the profiles 

is there  a way to emulate xinput-directinupt  and how to fix this issue (Elden ring)

**Comment by Kanuan** [comment]
@Ryochan7 could you add me as colaborator and give me mod powers to close issues/convert then into discussions? I won't go messing with things left and right, just want to help keeping the issue tracker organized

---------------

@PrestigeDevop from what I remember of FromSoftware games, they have really bad controller support and will just:

1. Only tries to read the very first controller in Windows' controller list
1. Will only be able to actually work if this first controller is an XInput controller
    - In this case, your DS4Windows profile need to be configured to use virtual Xbox 360
    
The problem is that (usually) the 1st controller in the list is your real (physical) DS4 controller, and DS4Windows' virtual xbox 360 comes second.

To prevent issues with the game, you need to:

1. Hide your REAL controller so it can't be detect by games/apps besides DS4Windows
    - For instructions on how to do so properly: [Preventing the double controller / double input issue in games](https://docs.ds4windows.app/guides/solving-double-input/)
1. Use a profile in DS4Windows set for virtual xbox 360 controller
1. Make sure it is the only controller in [Windows Game Controller list (joy.cpl)](https://docs.ds4windows.app/troubleshooting/controllers-check/#windows-game-controllers-list-joycpl)

**Comment by PrestigeDevop** [comment]
> orks. Use a profile in DS4Windows set for virtual xbox 360 controller
it's already configured as xbox 360 , I wil try other solutions , 

Thanks for replays and clarifying instructions now I understand why this issue occur at the first place , and sorry if this issue [post]  didn't followed the submission guidelines .I think this repo should've some wiki and mention repetitive Q&A and  information like this .

**Comment by AudioDuplication** [comment]
It DOES have a wiki... https://github.com/Ryochan7/DS4Windows/wiki
And this is somewhat close to a FAQ: https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting
