### ISSUE TITLE
Trayicon fails to create under a junction

### ISSUE THREAD

**Issue by thegamerx1** [Ryochan7/DS4Windows#2569]
**Describe the bug**
DS4Windows doesn't create tray icon when running under a junctioned folder

**To Reproduce**
1. Install DS4Windows from scoop
2. Run DS4Windows from `~\scoop\apps\ds4windows\current` or use start menu shortcut.
3. No tray icon

**Screenshots and Logs**
Weird crash I got when running with controller.
[ds4windows_log_20220907.18.txt](https://github.com/Ryochan7/DS4Windows/files/9501506/ds4windows_log_20220907.18.txt)

No tray icon no error
[ds4windows_log_20220907.23.txt](https://github.com/Ryochan7/DS4Windows/files/9501516/ds4windows_log_20220907.23.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.
 - OS: Windows 10 21H2
 - DS4Windows Version: 3.1.4

**Additional context**
Running DS4Windows from `~\scoop\apps\ds4windows\3.1.4` works fine.
I downloaded latest ds4 from github and replaced it with scoop one same issue.

```
drwxr-xr-x 1  0 Sep  7 01:20 3.1.4/
lrwxrwxrwx 1 46 Sep  4 05:06 current -> /c/Users/TheGamerX/scoop/apps/ds4windows/3.1.4/
```

**Comment by Sp3ci3s8472** [comment]
Weird I got the same error when I don't have Explorer as a shell in Windows 10 (I use Kodi as a shell) and try to start minimized. So it seems like this might be a bug. My issue is here: https://github.com/Ryochan7/DS4Windows/issues/2577

**Comment by Ryochan7** [comment]
I am a year late to this. Currently working on Scoop related junction problems with issue #3145. Never used Scoop before looking into controller hiding issue. Now extra checking will be done to check if DS4Windows is installed under a junction directory and then attempt to grab the real install path.

My recommendation previously would have been to use the real install directory rather than the junction directory. Even running DS4Windows from the real install directory once would probably have been enough to resolve the tray icon issue; it was enough to work around that controller hiding issue. This issue should be resolved in the next version of DS4Windows.
