### ISSUE TITLE
Turbo mode/Rapid Fire

### ISSUE THREAD

**Issue by GuyNumber129** [Ryochan7/DS4Windows#257]
Hey I've been using this program for a while, since like beginning of 2016, but I've decided to use this daily for Fortnite (PvE mode, Save the World). The program works great but I can't seem to get my macros to work. I want my fire button (R1) to have a feature where I can hold the button to continuously fire the weapon. I managed to get the feature to work where the R1 button mimics the LMB but it has issues when building. Is this at all possible? Would it be possible to add a turbo button mode that repeats the button press by holding it?

Thanks in advance.

**Comment by Aaron-Ritter-IDEXX** [comment]
It's doable, by making a macro. Export the macro and edit the delays to be reasonable so that you get, oh, 10 button pushes per second... or whatever it is you want. In another day or two, I can share my exported macro.

What's not clear to me is whether it works well if you make the macro press the button just once and then repeat while held. It's not clear whether it repeats smoothly. My experience doing that is mixed; games don't seem to think it's being pressed quickly at all. I make my "turbo" macros press the button 4 times or so.

**Comment by GuyNumber129** [comment]
I'm not too experienced in making macros, so I'm not sure how to write a macro. That said, if you do upload your macro, that would be greatly appreciated. I'll have another go, and see if I can get it working.

**Comment by daninthemix** [comment]
This program is in desperate need of a simple 'repeat while held' toggle on each input assignment.

**Comment by Ryochan7** [comment]
Maybe at some point I will get around to making some form of refactor that would allow more mapping features. There are some features that DS4Windows could really use that would open up possibilities. As it is, I have had a fair amount of work just experimenting with what is available and improving the current experience.

**Comment by Ryochan7** [comment]
This type of feature will definitely not make it into DS4Windows. Hopefully I can make something new in the future that will have that kind of functionality. Funny enough, antimicro had that kind of functionality although I don't like how I ended up implementing it.
