### ISSUE TITLE
Where is the installer for DS4Windows Version 1.4.117 or initial release? Or do I use some TPP program to install?

### ISSUE THREAD

**Issue by StayGoId** [Ryochan7/DS4Windows#258]
Edit: When I move over the .zip files onto my PC, does that mean that the program is already installed? O.O I think it started working right when I plugged in the controller right now. Weird.. Still any response from anyone would help.

Edit 2: Instead of continuing to not know what tf I was doing, I downloaded InputMapper instead and during installation, I was prompted to install the X360 driver, and I think that is what allowed the controller to start working. Still, Ryochan7, you should include instructions on how to install DS4Windows for new users like me. If it were similar to how Jays2Kings, where there were two executables, one for updating the program and one for installing the program, that would make so much more sense than not including an installer within the .zip files.

**READ**
Edit 3 (4/13/2018): Thank you to those who commented below, especially tordenflesk. I was downloading from this page (https://github.com/Ryochan7/DS4Windows) and not the "releases" page, which gave me the .zip folder for the files that RyoChan7, the developer, uses, instead of the user ones. My bad. I got my PS4 controller working using InputMapper, so it's all good. **PROBLEM SOLVED.**

I looked in all the folders and did not see any .exe files anywhere. Please help me, as I am new to this.

Your readme.txt in both Version 1.4.117 (just uploaded 13 hours ago) and 1.4.156 (from 11/18/2014) have no instructions on how to install the program..

**Comment by tordenflesk** [comment]
https://github.com/Ryochan7/DS4Windows/releases

**Comment by jonaaa20** [comment]
Dude, I don't want to be rude but the installation of ds4windows is easy, just download on releases tab, then extract it to anywhere you want then open ds4windows.exe, is that hard? To connect via Bluetooth, hold button Share + PS Button then connect it with your windows...

**Comment by TristanYoung** [comment]
"I don't want to be rude"  - such pretense is rude all on its own. Without a clear and concise step-by-step guide, it's doubly-rude.

There will be people who are unfamiliar with manual installation.  Not every computer user knows the optimal place to copy a folder, maybe they've never copied folders before, and mixing in Administrative rights - whoa.  Let's be fair, some people just want to know how to turn the key and drive the car, they don't want to know how to use a wrench to install the battery.  Things should be created to perform as easily as flipping a light switch, while also offering the more difficult approach.

We're going to see beginners, those with lower computer skills or lower confidence and [console gamers that are used to or expect the plug-and-play approach] lured into joining the PCMR.  These people won't necessarily be able to use DS4Windows without a little bit of help, and if they can't, HidGuardian is even further out of their reach.

When we look at the various related projects - DS4Windows, HidGuardian, etc, it's basically something a fair percentage of advanced computer users can perform, but not everyone.  That's one of the reasons why I created a pair of batch files and DS4Windows + HIDGuardian installation help file to aid in installation, reinstallation and removal of HidGuardian into and out of the device chain.

I would love to see a proper installer created, so that those that aren't as computer-savvy as you or I can install this stuff easily, and enjoy PC gaming.  I'd love to learn how to create an installer script.  I can make a simple batch file to install DS4Windows with and without HIDGuardian, and am willing to give another attempt at writing a powershell script, but it wouldn't be a Windows Installer script, which would be preferable.  If anyone can point me to some good resources for building a custom installer for DS4Windows, I'd love to look into it.

Meanwhile, I'll update my installation help file to provide greater help.  I believe there's an omission in my help file anyways I'd like to get corrected.

**Comment by TristanYoung** [comment]
I have updated the WIKI on how to install DS4Windows and HIDGuardian.

The DS4Windows and HIDGuardian install guide can be found here:
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian---Install-and-Setup-Guide

This guide was not created by the original authors of DS4Windows, or Ryochan7.  It may contain errors.  Please let me know if you find any, and I'll update it accordingly.

**Comment by Ryusennin** [comment]
Nice tutorial. Remember that Ryochan has developed an experimental HIDGuardian installer (latest link below) which so far works very well and doesn't require the use of devcon. You can find more information about it in topic #147.

http://ryochan7.xyz/ds4windows/test/DriverInstaller_Test_20180402.zip

**Comment by TristanYoung** [comment]
Ryusennin: I wasn't aware he built an experimental HIDGuardian installer.  I'll have to check it out, and possibly integrate it into the guide.

Ultimately though, I'd like to see more of an all-in-one installer - one that installs DS4Windows, HIDGuardian, and sets the registry keys, so I can shorten my guide to one line:  Run the installer.

**Comment by jonaaa20** [comment]
Nice tutorial @TristanYoung !
