### ISSUE TITLE
run at startup in windows10,UI is english

### ISSUE THREAD

**Issue by redomCL** [Ryochan7/DS4Windows#2621]
**Describe the bug**
run at startup in windows10,UI is english.

**To Reproduce**
1. thanks for your DS4Windowss,when I config run at startup in windows10,UI is english，whatever I config lanuage, I must to reboot DS4Windows once

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: [Windows 10 Pro Build 21H2]
 - DS4Windows Version [3.1.6]

**Comment by Ryochan7** [comment]
The current routine does not add the appropriate working directory in the shortcut. That is required so the app can discover the language assemblies that are bundled. Otherwise, the app will default to the default language. Should be a simple fix. I never use that functionality so I would not have encountered this issue.

**Comment by Ryochan7** [comment]
Changed in commit c4dcc56df19f6aae1b0adf9206f75dcaf7e95ceb. I have confirmed that DS4Windows now adds the working directory of DS4Windows into the lnk file.

**Comment by EAPermanent** [comment]
can't select chinese（zh-cn&zh-tw） language package bug again in 3.1.7!
