### ISSUE TITLE
Crash when switching from Dualshock4 Emulated Controller too fast

### ISSUE THREAD

**Issue by AkiraJkr** [Ryochan7/DS4Windows#2625]
I don't have a great way of describing this, but I do have the logs of when the crash happened.

[ds4windows_log_20221007.0.txt](https://github.com/Ryochan7/DS4Windows/files/9737901/ds4windows_log_20221007.0.txt)

Not sure if it's of any help, but:
- I also switch Profiles using Special Actions.
- ~~The one profile where I disable my controller had a special action to load two profiles in one button, until now. It doesn't seem like a consistent crash, but maybe this is related?~~ I can confirm this is not related, for I crashed with only one Special Action enabled.(See image below)
![image](https://user-images.githubusercontent.com/27028529/194741415-67e51866-980a-455a-8d17-879110578db0.png)

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/9740870/ds4windows_log.txt)

After some more testing, I reached this conclusion: 

DS4Windows crashes if you switch FROM a DualShock4 profile to a XInput one.

**Comment by Ryochan7** [comment]
Not sure why you would switch output controllers twice in less than 1 second. The sleep time that the log is complaining about was needed because there was a high chance that ViGEmBus would not be ready for calling the AwaitRawOutputReport call for a controller without some delay after plugging in the device. Could have avoided that by just making sure the loop was started before trying to interrupt the thread.

This problem won't really matter anymore as I have thrown in the towel and disabled virtual DS4 feedback support again. It only works reliably for one controller and it looks like the problem is on the ViGEmBus side.

**Comment by AkiraJkr** [comment]
Gotcha. It only happens rarely and only because I end up switching to X360 immediately(which as a consequence, causes me to switch twice in less than a second), so I'll keep that in mind. Unless you're using the issue to track this issue, I guess I could close it?
