### ISSUE TITLE
[Suggestion] DualSense emulation

### ISSUE THREAD

**Issue by TheMasterDingo** [Ryochan7/DS4Windows#2652]
This days more games for PS5 are getting released for PC, also other games support the Haptic Feedback of DualSense (
A Plague Tale: Requiem for example has full support for the haptics) when connected via USB.
The problem is that when the DS is connected through BT the game does not recognise it.
I understand that for this feature it needs support from the Vigem driver.
Just wanted to leave this suggestion here.
DualSense Virtual controller :)

**Comment by Ryochan7** [comment]
This would be a request for @nefarius and the ViGEm project rather than DS4Windows. Some of the more recent DS4 emulation groundwork will probably be useful information when it comes to supporting emulating other devices in the future.

The other option would be to do something like DSX does and modify the UDP server to support additional payloads and transfer data in user space. Of course that would require making mods for games in order to support such a setup.

I do not have any game that natively supports the DualSense and the DS haptic features so it would not matter to me.

**Comment by nefarius** [comment]
It's in the works actually since first quarter of 2022 but I got a ton of other tasks in between so things got interrupted many times. I'm back at it though.

**Comment by TheMasterDingo** [comment]
Thank you both for your replies.
Those haptics when supported from the games are a total game changer and feel so good.

Also i wanted to add that Sony has released an official firmware updater for the DualSense
https://controller.dl.playstation.net/controller/lang/en/fwupdater.html
I have updated mine to latest firmware and it works fine with DS4W
Might be useful.

Thanks again both for the great work!

**Comment by rafa21k1** [comment]
How great it would be to be able to have a controller that emulates Dualsense as if it were connected with a cable and to be able to play with all the benefits of the controller but via wireless, @nefaruis, @ryochan7 this would be the boom in ds4windows. congratulations for the great job

**Comment by IceLancerSR** [comment]
lately Sony has learned its lesson from critics and started adding their gamepads to their games with native support.
Horizon Dawn has native all sony gamepads support. V1,V2, sense

**Comment by masterflitzer** [comment]
> started adding their gamepads to their games with native support

why they didn't do this from the beginning is beyond me

**Comment by nefarius** [comment]
> > started adding their gamepads to their games with native support
> 
> why they didn't do this from the beginning is beyond me

Because they either have to use community reverse engineered code or get into an NDA with Sony to get access to the official SDK. Both take time, money and decisions from management.

**Comment by masterflitzer** [comment]
but he was talking about sony's own games (the word 'their' in the sentence refers to sony)

**Comment by nefarius** [comment]
> but he was talking about sony's own games (the word 'their' in the sentence refers to sony)

Oh, haha, yeah, this I indeed cannot answer 😅

**Comment by Trihy** [comment]
Native wireless haptic, sound and adaptive by sony on sony games? Dont think so. Maybe wired and only on some.

**Comment by Masamune3210** [comment]
I dont think they will ever do wireless anything when it comes to their controllers in games, AFAIK they officially still state that the controllers only work with PC when connected through USB

**Comment by IceLancerSR** [comment]
> 

Im telling u it works perfectly , horizon and new requiem including adaptive triggers on sense all on wireless and not even using their Bluetooth but asus's

**Comment by Trihy** [comment]
Do they?

Tried requiem and didn't recognize the controller. Just steam input. But could be wrong.

**Comment by IceLancerSR** [comment]
> Do they?
> 
> Tried requiem and didn't recognize the controller. Just steam input. But could be wrong.

I did say disabling steam input. Steam is breaking down native support. Gog works without issues since no steam

**Comment by Trihy** [comment]
Doesn't work for me. But good it works for you.

**Comment by TheMasterDingo** [comment]
On my end requiem works only with USB, Sackboy adventure(just released, full support) works by USB only also.
When i played horizon zero dawn i remember it did not work with wireless.
One thing, i thing windows 11 has support for the ds4, when i connect it without additional software wia BT it shows the controller on gamepad test website working

**Comment by Trihy** [comment]
Sure, many games have full support for haptic and adaptive triggers when wired.

**Comment by Masamune3210** [comment]
gamepad test sites will show the controller even without bespoke support, since the controller by default will be in directinput mode until manually switched into enhanced mode

**Comment by Trihy** [comment]
Still couldn't find any game that supports adaptive triggers and haptic feedback wireless natively. Any official info?

**Comment by SK83RJOSH** [comment]
> [Horizon Zero Dawn](https://store.steampowered.com/app/1151640/Horizon_Zero_Dawn_Complete_Edition/) has native all sony gamepads support. V1,V2, sense
Wired and wireless. -Requires disabling steam input to function. GOG works out of box
I grabbed the latest GOG release explicitly to test this. HZD doens't use adaptive triggers at all, and I had to launch the game through steam with Steam Input enabled for input to work at all... 🙂

**Comment by Trihy** [comment]
I think introducing those features without a specific dongle will not be an option for Sony. Official Sony BT adapter for ds4 introduced more lag than any other adaptor in the market. And probably some improved or specific implementation of BT.

Don't think any BT adapter could handle 4 controllers with haptic, audio and adaptive. Some struggles to keep more than one connected without all those features.

On PC every manufacturer implements the protocols like they want. Look at Intel, they have BT 5.0 to 5.3 adapters that can't handle more than one controller.

**Comment by masterflitzer** [comment]
> I think introducing those features without a specific dongle will not be an option for Sony

sadly i have to agree, i don't like the idea of a dongle tho, i always loved how universal BT is

**Comment by Ryusennin** [comment]
> Requires disabling steam input to function.

No. Some recent Sony games like Spider-Man and Miles Morales will *not* work properly if you disable Steam Input (on the map for example, diagonal movements with the analog stick are broken without Steam Input).

**Comment by South-River** [comment]
> It's in the works actually since first quarter of 2022 but I got a ton of other tasks in between so things got interrupted many times. I'm back at it though. Plus I finally own a PS5 which took me forever to get a hold of.

Hello, I wonder if we can simply use a esp32 to emulate dualsense without customize its driver? By connecting it to PC through USB and send packet like dualsense 's usb protocol.

**Comment by South-River** [comment]
> > It's in the works actually since first quarter of 2022 but I got a ton of other tasks in between so things got interrupted many times. I'm back at it though. Plus I finally own a PS5 which took me forever to get a hold of.
> 
> Hello, I wonder if we can simply use a esp32 to emulate dualsense without customize its driver? By connecting it to PC through USB and send packet like dualsense 's usb protocol.

I heard Sony customized its protocol. In game, they use Isochronous USB Transfer to transfer data, and I don't know how to transfer its data into bluetooth connection, since the protocol is customized. And there seems no PC game that support its unique rumble, I can't get the packet send through bluetooth.

**Comment by Nikslg** [comment]
Wanted to bump this thread since I am having issues getting Dualsense to work over bluetooth.
It seems like Dualsense works perfectly fine when connected via USB, but when it's connected over BT, it requires emulation for most games.
One example I can specify is Guardians of the Galaxy. It has Dualsense support, but will not recognize dualsense when it's over BT, meanwhile Steam and DS4Windows will see it working properly :(

**Comment by Trihy** [comment]
Any more info? Only in tlou?

**Comment by TheMasterDingo** [comment]
For me only in TLOU, i am testing right now each time i use the pistol the R2 to aim gets harder to press. This is with DS4windows fully off and no steam emulation or other, just direct BT

**Comment by Trihy** [comment]
Let's see if they roll updates for older Sony games.

And let's hope they started using those features and it's not a bug, lol.

**Comment by andreycout** [comment]
> For me only in TLOU, i am testing right now each time i use the pistol the R2 to aim gets harder to press. This is with DS4windows fully off and no steam emulation or other, just direct BT

Unfortunately the described effect is not DualSense Advanced Haptics, but Adaptive Triggers. It's been known that Adaptive Triggers can be supported via bluetooth, as the DualSenseX app has demonstrated through it's proof of concept Adaptive Trigger demo and mods released for games to support Adaptive Triggers wirelessly. 

I think there's even some implementation of the Adaptive Trigger effects on DS4W that works wirelessly, it's just kind of pointless because they are static, they don't interface with the game.

DualSense advanced Haptics are a whole different beast to tackle, because they work by feeding audio data to the controller which reproduces it as very precise vibrations based on said audio files. Without some firmware level change to the DualSense controller that exposes its audio channel via Bluetooth, wireless haptics are very difficult to pull off on pc.

I'm still downloading the game to test the supposed feature, but I'd be very surprised if it's actually advanced haptics via bluetooth

**Comment by TheMasterDingo** [comment]
Only triggers, its the first game i can use the triggers via bt

**Comment by Trihy** [comment]
But this is native support. Totally different from dualsensex. 

Also will be nice to know if works on older controller firmware.

**Comment by Ryochan7** [comment]
Based on the current discussion on the DSX Steam forums, it really seems to sound like DualSense emulation support for ViGEmBus will likely be a closed source product only available to DSX. If that is true then there is no need to keep this topic open. Makes me wonder if ViGEmBus will go closed source entirely.
