### ISSUE TITLE
Crash log when apply save on edited profile

### ISSUE THREAD

**Issue by IceLancerSR** [Ryochan7/DS4Windows#2664]
Changing idle disconnect time ->apply app crashed.
I mean its nothing disastrous, just wanted to give you the info

[log.txt](https://github.com/Ryochan7/DS4Windows/files/9893494/log.txt)

Win10 x 64
3.19 ds4win

**Comment by IceLancerSR** [comment]
P.S
Happened again same profile, could be something bad with profile ? 
[ds4windows_log_20221029.3.txt](https://github.com/Ryochan7/DS4Windows/files/9893508/ds4windows_log_20221029.3.txt)
[Sony.zip](https://github.com/Ryochan7/DS4Windows/files/9893511/Sony.zip)

**Comment by Ryochan7** [comment]
Found the issue. It only happens when opening the Profile Editor from the Profiles tab with a controller connected and then disconnecting said controller before hitting Save or Apply. Added an additional null check.

https://github.com/Ryochan7/DS4Windows/commit/96a49ba259d656a52ca8b3e1c443e0e349652abc
