### ISSUE TITLE
DS4Windows does not open.

### ISSUE THREAD

**Issue by stressatoo** [Ryochan7/DS4Windows#2665]
**Describe the bug**
As title, DS4Windows does not open. The process does not get created, `perfmon /rel` returns that "DS4Windows.exe" and "DS4Updater.exe" stopped working for as many times as I opened them, problem signature is [APPCRASH KERNELBASE.dll e0434352](https://i.imgur.com/B6rj4iz.png)
I have checked the [Troubleshooting steps](https://docs.ds4windows.app/troubleshooting/ds4w-does-not-run/).

**To Reproduce**
1. Open `DS4Windows.exe` or `DS4Updater.exe`

**Expected behavior**
A process should start aswell as the program interface.

**Screenshots and Logs**
It doesn't generate any logs.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v2
 - OS: Windows 11 Home, 64-bit
 - DS4Windows Version: 3.1.9.0 (latest)

**Additional context**
//

**Comment by Yohoki** [comment]
What was the last working version? I ask this because D4W updated some things recently, and your system may need updated to use it now. Did you update your .Net Runtimes? The troubleshooter tips recommends .Net 5, but I believe this is outdated. D4W now needs .Net 6 to work correctly.

.Net Redistributable Links:
 - [x64 for 64bit OS](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.11-windows-x64-installer)
 - [x86 for 32bit OS](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.11-windows-x86-installer)
