### ISSUE TITLE
Macros containing controller operations are invalid on DualSense

### ISSUE THREAD

**Issue by ddcxxx** [Ryochan7/DS4Windows#2666]
**Describe the bug**
Setting a macro containing controller operations are invalid, but macros consisting of keyboard operations are valid

**To Reproduce**
1. I set my  DualSense to emulate xbox360 in Genshin impact.
2. I set "Share" to trigger "Alt+M" macro, and “PS” to trigger  “L2+Left Button” macro.
3. Then go in game, press "Share" button, macro is in effect, but press “PS”  button, nothing happened.

**Expected behavior**
Macros that contain controller operations should take effect.

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense
 - OS:Windows 10 Pro Build 22H2
 - DS4Windows Version  3.1.9

**Additional context**

**Comment by Ryochan7** [comment]
Tested it and macro output is working as designed. Unfortunately, the design is not good by default. 'For the most simple PS macro like you described, L2 and Left Button would only be active for one gamepad poll. You would have to insert a Wait period between the KeyDown and KeyUp events to insert a pause between the two events. That way the buttons will stay held for a period of time rather than immediately released.

![ps_macro_example](https://user-images.githubusercontent.com/581968/198894037-ed35e8da-ad1d-4ef6-85f4-5cc76e5a856d.png)

**Comment by ddcxxx** [comment]
> Tested it and macro output is working as designed. Unfortunately, the design is not good by default. 'For the most simple PS macro like you described, L2 and Left Button would only be active for one gamepad poll. You would have to insert a Wait period between the KeyDown and KeyUp events to insert a pause between the two events. That way the buttons will stay held for a period of time rather than immediately released.
> 
> ![ps_macro_example](https://user-images.githubusercontent.com/581968/198894037-ed35e8da-ad1d-4ef6-85f4-5cc76e5a856d.png)

Thanks for your answer, I tried to insert a Wait period, but it still not woek anymore, it seems that macros containing controller operations don't work at all on my DualSense.

Then I cran a test, set "Swipe Up" to "X Button", set "Swipe Down" to "X Button" via record marco, and go in game, "Swipe Up" can  trigger  "X Button", but "Swipe Down" without any reaction.

![屏幕截图 2022-10-31 141700](https://user-images.githubusercontent.com/41536081/198945085-714b3850-a9b2-473d-b234-ed18367cede1.jpg)
