### ISSUE TITLE
FPS drops when using DS4Windows and PS5 controller

### ISSUE THREAD

**Issue by weishen1121** [Ryochan7/DS4Windows#2678]
There seems to be an issue with DS4Windows and/or PS5 controller. I noticed this after 5 chapters with A Plague Tale Requiem. Most scenes were pretty much perfect, 120fps locked but sometimes it dropped into 80-90 FPS even though I have DLSS3 with Frame Generation on. I tried a few things but nothing seemed to work. 

I gave it one more test while controller was off, just with mouse/kb, and everything was perfect in the same area. I turned on the controller again and boom FPS dropped again. I then closed down DS4Windows and plugged in my PS5 controller with a USB cable and everything is perfect again.

What could I further test to see what is causing this issue as I really prefer the lightbar settings and shortcut/hotkeys of DS4Windows.

**Comment by Ryochan7** [comment]
Only really noticed any issue like this when playing around with Metal: Hellsinger (demo) recently. My PC can barely run the game at all so it was a challenge trying to record any gameplay footage. Between the DS4Windows video and SteamControllerTest mapper video, there is a slight difference in frame rate visible with the Steam Controller video being a bit smoother. Since there are so many factors involved, it would be hard to isolate which possible variable might be causing the biggest difference. In theory, the SteamControllerTest mapper is doing more work in the backend so it should have been at a disadvantage. Although, performance was better using that test mapper.

Even the effect of input poll rate would be hard to determine based on my current tests. The JoyCon average poll time is 16 ms as opposed to a average poll time of 8 ms for the Steam Controller (USB) but the JoyCon reader requires two input threads (one for each side). If I had to try something, I would test stripping out the single app instance check or I figure the use of WpfToolkit is causing some problems; SteamControllerTest uses the HandyControl package for rendering controls and windows.

All I know is that even current DS4Windows performance is better than most other mapper apps out there that people don't have a problem with. Just going to continue to hammer it out over time.

At those frame rates, it should not make any real difference. Pretty sure my PC cannot even run A Plague Tale: Requiem; checked it and my PC does not meet the minimum system requirements for the game.

**Comment by weishen1121** [comment]
> Only really noticed any issue like this when playing around with Metal: Hellsinger (demo) recently. My PC can barely run the game at all so it was a challenge trying to record any gameplay footage. Between the DS4Windows video and SteamControllerTest mapper video, there is a slight difference in frame rate visible with the Steam Controller video being a bit smoother. Since there are so many factors involved, it would be hard to isolate which possible variable might be causing the biggest difference. In theory, the SteamControllerTest mapper is doing more work in the backend so it should have been at a disadvantage. Although, performance was better using that test mapper.
> 
> Even the effect of input poll rate would be hard to determine based on my current tests. The JoyCon average poll time is 16 ms as opposed to a average poll time of 8 ms for the Steam Controller (USB) but the JoyCon reader requires two input threads (one for each side). If I had to try something, I would test stripping out the single app instance check or I figure the use of WpfToolkit is causing some problems; SteamControllerTest uses the HandyControl package for rendering controls and windows.
> 
> All I know is that even current DS4Windows performance is better than most other mapper apps out there that people don't have a problem with. Just going to continue to hammer it out over time.
> 
> At those frame rates, it should not make any real difference. Pretty sure my PC cannot even run A Plague Tale: Requiem; checked it and my PC does not meet the minimum system requirements for the game.

Sorry, a lot of that goes way over my head as I'm super dumb but one thing to note is that when I first starting playing Plague Tale Requiem, the game was pretty much locked at 120FPS even with DS4Windows running. Sometimes it would start having weird FPS issues, dipping below 100FPS, but that would be resolved by rebooting my computer. It was only when I hit a certain part in Chapter 5 that it was consistently dropping FPS to 70-90 with DS4Windows running, regardless of rebooting or trying many different things. The only thing that worked, in the same area/chapter 5, was closing DS4windows and using the PS5 controller with USB or just playing with mouse/kb - back to locked 120fps.

I did find something recently on google that led me to hopefully figure this out - https://steamcommunity.com/app/239140/discussions/0/604941528484450924/

The last post there mentions that the game natively supports the controller. In this case, Plague Tale Requiem natively supports the PS5 controller as well. 

I just turned on "Hide DS4 Controller" in the Settings tab of DS4Windows which seems to have resolved the issue for now. Instead of having XBOX 360 controller and Wireless controller listed in 'Game Controllers' it only has XBOX 360 controller now. So the game should not be trying to override it's own native support anymore... or at least that's what I think/hope is happening because I remember reading something about this setting being buggy/not working as intended sometimes.

I wish I had made a backup of my save game when I was in Chapter 5 but so far I have gone through 2 chapters with this setting and no issues yet... so hopefully that is it but I'll report back if the issue pops up again.

**Comment by Ryusennin** [comment]
Hide DS4 is an old obsolete option, you should use the HidHide application instead. Though I'm not sure that double input (caused by "XB360" and "Wireless" appearing in your Game Controllers) would explain such a huge difference of 40 fps.

I have Plague Tale 2 and it struggles to reach 50 fps on my AMD Vega 56. The game has severe performance issues on all architectures, especially those without DLSS support. No major patch has been released so far since release. For comparison, Plague Tale 1 runs around 80 fps on my system from start to finish.

**Comment by Ryochan7** [comment]
This discussion lead to some experiments which led to the changes in commit 6245c1ce1008e8922c339cc5a0337ed7fda4c9d9. Making small changes to the IPC command routine ended up making some significant changes to app performance even though I do not think it should have. Noticeably better input and smoother framerate although not necessary much higher average framerate. .NET Runtime is such a weird beast.

**Comment by tobiastimm** [comment]
I noticed with the latest version of DS4WIndows in combination with a PS5 Controller (wired) I sometimes get huge stuttering and performance issues of Unity Games (e.g. The Messenger). The game starts to stutter, the controller disconnects, connects, disconnects etc.

**Comment by Ryochan7** [comment]
>  If I had to try something, I would test stripping out the single app instance check or I figure the use of WpfToolkit is causing some problems; SteamControllerTest uses the HandyControl package for rendering controls and windows.

This issue will technically always be relevant but some recent changes have mattered. The single app instance check was recently changed with DS4Windows 3.2.13 and it actually made a big improvement on program performance; it really should not but the .NET Runtime is extremely odd and picky. Even a small upcoming change for DS4Windows 3.2.14 regarding the ViGEm.NET library has changed things a good amount.

Probably should do a side by side comparison with a much older version of DS4Windows but I doubt I will ever get around to it. Currently playing Quake 2 64 and performance is better.

**Comment by Ryochan7** [comment]
Never got around to making a comparison. Unless it would be for some YouTube video then doing such a comparison would probably be pointless. Also, it should be noted that using .NET and the .NET Runtime to begin with adds its own overhead. With the same code, the .NET 8 port of DS4Windows actually runs better and smoother than on .NET 6.

I do not think there is much reason to keep this issue open anymore. A fair amount has improved with DS4Windows since this issue was initially opened. Also, people do not seem to have issue with applications that run much worse and lag a PC running it.
