### ISSUE TITLE
DualSense Controller doesen't charge

### ISSUE THREAD

**Issue by krysanto** [Ryochan7/DS4Windows#2694]
**Describe the bug**
DualSense Controller doesent't charge, even loses battery while beeing plugged in.

**To Reproduce**
1. Plug in Controller
2. Turn on DS4Windows
3. Controller actually loses battery

**Expected behavior**
Controller gets charged while continue to be used.

**Screenshots and Logs**
[Log.txt](https://github.com/Ryochan7/DS4Windows/files/10026159/Log.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSenseCFI-ZCT1W
 - OS: Windows 10 Pro Build 19044
 - DS4Windows Version 3.1.10

**Additional context**
I've charged the controller to 25% via a wallcharger then plugged it into a USB cable connected to an usb 3.0 port.

**Comment by Masamune3210** [comment]
Charging is handled completely by the controller firmware, what you have connected to it has no say in the matter on if it charges or not.

**Comment by krysanto** [comment]
Okay, I get it now, the controller works fine on one PC, but not on another. It gets drained on the problematic PC when the PC is powered off. I've checked the BIOS and couldn't find any settings which help me, i run an AMD CPU with a taichi x370 motherboard. I'll leave this open for now just in case somebody has any ideas. If that bothers you, this issue can be closed.

**Comment by Masamune3210** [comment]
You are likely running into a couple of issues coming together as one. Most boards support Power over USB when shut off, some boards don't put out a lot of power when they do, and some boards are incredibly weird about what devices and ports they decide to send power to when off. My guess is the board is deciding the DualSense needs power, but doesn't supply enough power, and it slowly drains the DualSense instead of charging it

**Comment by krysanto** [comment]
Thank you mate ill look into that!
