### ISSUE TITLE
diagnosed with virus, how you can explain me please?

### ISSUE THREAD

**Issue by SlumpShady** [Ryochan7/DS4Windows#2695]
When i test the folder in the website "VirusTotal" it shows me this.

![DS4WINDOES](https://user-images.githubusercontent.com/95719321/202609043-cfb12c58-420a-4342-8859-8d1fa9a403e0.png)

How do you explain this?

**Comment by Ryochan7** [comment]
False positive. I don't have $70+ to pay for a passing test.

**Comment by Masamune3210** [comment]
I sincerely wish people would get it out of their head that just because it shows up on VirusTotal as a hit that it means the program is automatically malicious. Especially when its from some no name random Malware Engine, and ESPECIALLY one that is known to do shady things and is also owned by the same people who do other scammy AV stuff
