### ISSUE TITLE
Windows "Startup apps" not working because of DS4Windows

### ISSUE THREAD

**Issue by jeremybris** [Ryochan7/DS4Windows#2745]
**Describe the bug**
Hello, I think this may be a Windows 11 beta preview issue...

When I choose "Run at Startup" in the DS4Windows app. It creates a shortcut in "C:\Users\[Username]\AppData\Roaming\Windows\Start Menu\Programs\Startup", which causes Windows to make the task manager "Startup apps" menu appear empty. See pictures under screenshots for examples:

Is there a way to do "Run at Startup" without bugging Windows please?

**To Reproduce**
1. Activate "Run at Startup" in the DS4Windows app.
2. Go to Task Manager "Startup apps" tab. You will see it is empty.
3. Go to "C:\Users\[Username]\AppData\Roaming\Windows\Start Menu\Programs\Startup". Delete DS4Windows shortcut. Startup apps should return.

**Expected behavior**
When activating "Run at Startup", task manager "Startup apps" tab should not be effected.

**Screenshots and Logs**
1. "Run at Startup"
<img width="674" alt="Screenshot 2022-12-26 092831" src="https://user-images.githubusercontent.com/11889359/209559156-a4f8a9b2-02be-4480-b214-d5d7b9f4fd09.png">
2. Shortcut is present
<img width="637" alt="Screenshot 2022-12-26 092916" src="https://user-images.githubusercontent.com/11889359/209559173-26f879f7-f60f-49c6-a9e5-d031b8a0d81a.png">
3. No startup apps
<img width="722" alt="Screenshot 2022-12-26 093204" src="https://user-images.githubusercontent.com/11889359/209559189-b1fd5566-341f-46ba-bce0-e297c402ef7b.png">
4. Shortcut deleted, startup apps returns to normal
<img width="742" alt="Screenshot 2022-12-26 094118" src="https://user-images.githubusercontent.com/11889359/209559915-99182ca6-e8e7-4add-9ece-93f97c6835e3.png">

**Desktop (please complete the following information):**
 - Controller Make and Model: DuelSense (PS5 Controller)
 - OS: Windows 11, Latest, Beta Preview Build
 - DS4Windows Version: Latest

**Additional context**
If this is just a "Windows 11 Beta preview" issue, not on Windows 11 or Windows 10, this can be closed, because it is likely to be fixed by Microsoft. I will report the issue to them. Let me know if this is not reproducible outside of Windows 11 beta preview or if there are any questions.

**Comment by Ryochan7** [comment]
Microsoft broke more features in Windows 11? Imagine my shock. Pretty sure this is a Microsoft problem as that standard for establishing startup entries has been around since (I believe) at least Windows XP .

**Comment by jeremybris** [comment]
> Microsoft broke more features in Windows 11? Imagine my shock. Pretty sure this is a Microsoft problem as that standard for establishing startup entries has been around since (I believe) at least Windows XP .

If someone can confirm that this doesn't happen in Windows 10 or standard Windows 11, I will close this. And report this issue to Microsoft instead. (Because it seems more likely Microsoft will fix a bug if it is in the Beta Preview, IMO).

**Comment by ayeball** [comment]
I have Windows 11 Insider Preview Build 25267  = Windows Dev Channel.

And when i have " run at startup on ds4 3.1.12 activated "  its starting in taskbar. 

I can also see it if i go like this : 

How to find the personal Startup folder

"Press the Windows + R keys on your keyboard. This is going to bring up the Run utility.
Type in “%appdata%” without quotation marks and press the Enter key on your keyboard. This will launch File Explorer with the correct folder open.
Navigate to Microsoft → Windows → Start Menu → Programs → Startup."

I also see it if i " Search Bar -> Auto start / Same way " Settings -> Apps " .




I dont see any "start up " in my "Task Manager "  .But doesn't matter for me , because the app works and start with windows so function is working. 

But doesn't ds4 start with windows starting for you ? and working. 
____________________________________________________________________


https://blogs.windows.com/windows-insider/2022/12/14/announcing-windows-11-insider-preview-build-25267/

Maybee it is a difference if you have "Beta or Release Preview" . 
22621.1037 and 22623.1037 ,  Build 22621.898

/F

**Comment by Ryochan7** [comment]
Tested this on my up to date Windows 10 install and startup works as expected and all existing entries remain intact when DS4Windows writes its link.

**Comment by jeremybris** [comment]
Closing and reporting this issue to Microsoft instead, since it is not in Windows 10, I think it is a bug with Microsoft.

I am going to use Microsoft Feedback Hub to report this bug, for anyone else who wants to follow this issue or seperately report it.

![Screenshot 2022-12-26 172616](https://user-images.githubusercontent.com/11889359/209586418-d09811fb-664f-4974-8236-14d0343d6cb5.png)
