### ISSUE TITLE
Special Action not saving or loading correctly

### ISSUE THREAD

**Issue by Shinygati** [Ryochan7/DS4Windows#2775]
**Describe the bug**
Anytime you save a special action config the ds4windows will fail to load them correctly on startup their filename will be changed to have (toggle) at the end when looking at it from the controller config special action tab.

**To Reproduce**
1. Go to a controller config and hit edit
2. Click on special action
3. add a special action (tested with both press/toggle key and record macro)
4. save the changes
5. test that they are working and then exit the program.
6. launch the program and find that they no longer work

**Expected behavior**
special action should work after relaunching the program, as for macro recording the keybinds it displays here when you "edit" an existing config is not even what was previously saved.

**Screenshots and Logs**
![image](https://user-images.githubusercontent.com/17960201/211796621-97360457-4570-42b6-93da-0460a3f15d8c.png)
![image](https://user-images.githubusercontent.com/17960201/211797759-9ece4ba4-f97b-4331-b4f0-18bbdab4b724.png)
![image](https://user-images.githubusercontent.com/17960201/211797799-632dd4a8-0176-4cbd-a148-3f1e29ad250c.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS5 v.2 (CFI-ZCT1W)
 - OS: [e.g. Windows 11 Pro Build 22621.963]
 - DS4Windows Version [e.g. 3.2.4]

**Additional context**
I have updated and installed the latest ds4windows and installed the latest microsoft .NET Runtime installers.

**Comment by Thetruecesar** [comment]
I have exactly the same problem, I use the program on Windows 10 with a PlayStation 5 controller.
I hope they fix this problem soon

**Comment by legomanster** [comment]
The problem seems to be with saving rather than reading configs and this is likely ongoing since 3.2.0. A workaround is to make your macros in 3.1.12 and then switch back to the latest version (in case you are using portable mode, copy over actions.xml file  from 3.1.12 to latest after you finish making your macros)

**Comment by Shinigati** [comment]
> The problem seems to be with saving rather than reading configs and this is likely ongoing since 3.2.0. A workaround is to make your macros in 3.1.12 and then switch back to the latest version (in case you are using portable mode, copy over actions.xml file from 3.1.12 to latest after you finish making your macros)

Well this isn't exactly true, my issue started after updating the program and i had never changed or made any new macro's since early last year.

**Comment by ceedveed** [comment]
> The problem seems to be with saving rather than reading configs and this is likely ongoing since 3.2.0. A workaround is to make your macros in 3.1.12 and then switch back to the latest version (in case you are using portable mode, copy over actions.xml file from 3.1.12 to latest after you finish making your macros)

Thanks. As soon as I updated from 3.1.12 straight to 3.2.6, my Special Actions list was blank. I had to revert to 3.1.12.

I have not had a chance to try 3.2.7 yet to see if this was fixed.

**Comment by Ryochan7** [comment]
And yet nobody has shared their Actions.xml file so I can review what is happening. Besides, macros are cheating and you should not be using them according to the YouTube Warzone league.

**Comment by Shinigati** [comment]
> And yet nobody has shared their Actions.xml file so I can review what is happening. Besides, macros are cheating and you should not be using them according to the YouTube Warzone league.

Well if you had simply asked i would have been more than happy to share them, i didn't think it would help here since it seemed like the issue was happening without even changing anything after simply updating the program and not touching anything, and about macros.. they have many uses in different games and you can't exactly stop people from using them in competitive games, i personally don't really need the macro's but the press/toggle key is also breaking which i need with one certain game as the controller input has been broken with one specific action that has never been fixed by the devs so i 
used ds4windows to get around it by making it press a single keyboard key but after updating my special actions change to (toggle) and does not work when trying to active them unless i manually edit them and press save without making any changes to it, this is a temporary solution until the program is started up again but for macro's they need to be re-recorded every single time.
[Old Version.zip](https://github.com/Ryochan7/DS4Windows/files/10514429/Old.Version.zip)
[New Version.zip](https://github.com/Ryochan7/DS4Windows/files/10514440/New.Version.zip)
[New Version after pressing edit and save on special actions with no changes.zip](https://github.com/Ryochan7/DS4Windows/files/10514443/New.Version.after.pressing.edit.and.save.on.special.actions.with.no.changes.zip)

**Comment by ceedveed** [comment]
Only 3.1.23 will work with my Actions.xml file, which I've attached. My use case is couch/living room gaming where I don't use a keyboard and mouse.
[Actions.zip](https://github.com/Ryochan7/DS4Windows/files/10830429/Actions.zip)

**Comment by Ryochan7** [comment]
Thank you @ceedveed for providing an Actions.xml file. Took a bit but I found the problem. The use of an empty string in the Delay tags is the problem. XmlSerializer tries to parse the blank string as an integer and fails. An exception is thrown and caught but nothing is done after that; probably should add an error in the log. Putting a value of 0 within those tags allows DS4Windows to be able to read the Actions.xml file fine after that. Will have to look at the old code but I would consider that old markup to be wrong. 

```
<Delay>
</Delay>
```

**Comment by Ryochan7** [comment]
Made a temporary change to Delay tag processing.

6a17a3b84e46141ca52ee35a26cce55854c95a1f

**Comment by Mister-Curious** [comment]
Just posting here to get any possible news about updates, as I have a similar issue described here #2853

**Comment by Mister-Curious** [comment]
Thank you for the speedy patch. Can confirm that 3.2.9 is now loading Special Actions.

**Comment by ceedveed** [comment]
Performed some short testing. 3.2.9 shows all my Special Actions. I only executed a few special actions, but the few that I tried worked. THANK YOU
