### ISSUE TITLE
DS4 V2 Latency

### ISSUE THREAD

**Issue by Brandhor** [Ryochan7/DS4Windows#278]
I've bought ds4 v2 but the latency with a usb cable is 16ms, my old ds4 v1 had a latency of 4ms, as for bluetooth the v1 had 8-12ms and the v2 has 18-19ms
is this a known issue with the v2 or should I get a replacement?

**Comment by jonaaa20** [comment]
I have a V2, my latency is 4ms on USB and 1,25 - 3ms on Bluetooth.

**Comment by TristanYoung** [comment]
I can confirm my DS4 v2 has BT latency of 3ms or less.

I would try several things...  Re-orient your bluetooth adapter - it shouldn't be behind your PC - it should be on the front of your PC, or on an extension cord close to where your controller will be used.  If your keyboard has a USB port on it - plug the bluetooth radio there.  Make sure you don't have other devices in the 2.4GHz causing interference (microwave oven, cordless phone, cellphone, other bluetooth devices, etc.).

My latency increases if I plug my BT adapter into the back of my monitor, so I don't use those ports anymore.

Try a different BT adapter - maybe yours is on the fritz.  Also try a different controller.  Hopefully you can figure out the problem.

**Comment by Brandhor** [comment]
@TristanYoung it's integrated in the motherboard so I can't move it around, I also have a old bluetooth 2.0 dongle but the v2 doesn't work at all with it, the problem though is that I get 16ms on usb which is really weird

anyway I ordered a replacement so I'll see in a few days, it's just strange that an hardware bug could cause a increased latency

**Comment by diogocalgaro** [comment]
I usually get 4ms using cable and 8ms using Sony adapter in a v2 DS4.

**Comment by TristanYoung** [comment]
Thinking about it some more, I'm not sure if it really helps to post latency stats on their own.|

There are many things that can affect I/O latency including:
- bluetooth radio chipset and USB chipset
- number of devices on a hub or connected via bluetooth (congestion)
- drivers (all types) (google: what is DPC latency, DPC latency checker)
- page faults - memory which does not reside in RAM and must be loaded and added to the processes memory page table.  See next three points.
      - amount of RAM available (to reduce likelihood of hard page faults)
      - storage device speeds (affect the time to service hard page faults)
      - valid page faults are not errors.  One can't always have everything needed in RAM, sometimes must be paged in from a storage device such as a hard drive.
- system load
- interference
- cabling
- connectors
- controllers
etc.

When I created my system, my main focus was music production, with low DPC latency. Turns out to be a great gaming system too.

For example, if one of your drivers is misbehaving by taking longer than reasonable to process, you can expect all sorts of issues - DPC latency - the effects include increased I/O latency, increased storage drive access, controller lag, audio dropout or corruption, etc.  Sometimes doing something as simple as discontinuing use of dashboard software that monitors CPU speed/performance can have a measurable effect on overall system latency.  Keep in mind, a gaming machine should be lean and mean, not running a pile of unnecessary programs/processes/services that aren't required for gaming.

Crypto-currency miners and malware can also affect latency.

Some of the points above also affect overall FPS, and some games are heavily CPU-bound to begin with - lowering FPS, such as Elder Scrolls Online (all updates prior to the up-coming update 18).

I hope this helps.

**Comment by Brandhor** [comment]
I just got another v2 and I get 4ms in usb so there was definitely something wrong with the other one
