### ISSUE TITLE
Support DualSense Edge

### ISSUE THREAD

**Issue by Naworm** [Ryochan7/DS4Windows#2799]
Hello,
I have just received my DualSense Edge controller, but it is not being recognized by either DS4Windows or the "Firmware updater for DualSense(TM) wireless controller".
Do you plan to support it in the short term?

**Comment by dezerving** [comment]
Yep, and just to add to the OP. The PC will recognize the controller as "DualSense Edge" when I open the controllers panel.

Would love to be able to use this controller on PC through DS4Windows.

Also, and I'm not sure this is even possible for you, but if you could look into it, the customizable features (back buttons, stick sensitivity, etc) of the controller are currently locked to only being adjusted if you have a PS5. 

This is less than ideal for those of us who don't have a PS5 but just wanted a pro controller with swappable sticks.

Thank you!

**Comment by dickrocket** [comment]
Just found out [DSX](https://store.steampowered.com/app/1812620/DSX/) has DualSense Edge support already, seems to work pretty well so far

**Comment by ngws** [comment]
I managed to get it working by adding the following after line 132 of [DS4Devices.cs](https://github.com/Ryochan7/DS4Windows/blob/master/DS4Windows/DS4Library/DS4Devices.cs):

`new VidPidInfo(SONY_VID, 0x0DF2, "DualSense Edge", InputDeviceType.DualSense, VidPidFeatureSet.DefaultDS4, DualSenseDevice.DetermineConnectionType),`

I compiled it with that addition and it detects my Dualsense Edge, and reads the input correctly. Whatever the back buttons are mapped to also work. I haven't got time to do a PR, but it's an easy addition for whoever reads this.

**Comment by velocity7** [comment]
> I managed to get it working by adding the following after line 132 of [DS4Devices.cs](https://github.com/Ryochan7/DS4Windows/blob/master/DS4Windows/DS4Library/DS4Devices.cs):
> 
> `new VidPidInfo(SONY_VID, 0x0DF2, "DualSense Edge", InputDeviceType.DualSense, VidPidFeatureSet.DefaultDS4, DualSenseDevice.DetermineConnectionType),`
> 
> I compiled it with that addition and it detects my Dualsense Edge, and reads the input correctly. Whatever the back buttons are mapped to also work. I haven't got time to do a PR, but it's an easy addition for whoever reads this.

I don't know if it's related, but adding this also seems to have exposed a bug involving duplicate keys in ProfileDTO.cs at line 1747. If anyone else encounters this, change the following:

```shiftKeyTypeSerializer.CustomMapKeyTypes.Add(dcs.control, testFlag);```

to:

```
DS4KeyType tempFlags = DS4KeyType.Unbound;
if (shiftKeyTypeSerializer.CustomMapKeyTypes.ContainsKey(dcs.control))
{
    tempFlags = shiftKeyTypeSerializer.CustomMapKeyTypes[dcs.control];
    tempFlags |= DS4KeyType.Unbound;
    shiftKeyTypeSerializer.CustomMapKeyTypes[dcs.control] = tempFlags;
}
else
{
    shiftKeyTypeSerializer.CustomMapKeyTypes.Add(dcs.control, testFlag);
}
```

**Comment by ngws** [comment]
Any ideas what may cause that bug and if it actually is related to my proposed change? In what scenarios does that bug trigger? I'm not familiar with the DS4Windows codebase, but I could potentially investigate if I can get a bit more info.

**Comment by velocity7** [comment]
It seems to be related to buttons that have a shift key mapping, but for some reason were left unbound. The reason why I'm leaving it open to interpretation is that I don't know whether loading the new DS4Windows with the DualSense Edge PID code created this specific scenario somehow.

**Comment by Ryochan7** [comment]
Should do another check but made a preliminary workaround for the key type flag bug for shift modifiers. I cannot remember why I did that check differently than with normal key types used for normal button bindings.

**Comment by Ryunam** [comment]
Hello, thanks a lot first of all for implementing the initial Dualsense Edge detection. I have been using it consistently ever since I got the controller and so far everything works beautifully.

I'm wondering if there's any plan to also provide the ability to remap the 4 buttons that were added to the Edge, namely:
- Left FN
- Right FN
- LB (Left paddle)
- RB (Right paddle)

Many thanks in advance!

**Comment by Ryochan7** [comment]
Must be pretty well off to be able to buy a $200 gaming peripheral in this economy when most people are struggling to afford groceries or pay their energy bills. Aside from that, I obviously do not have access to that hardware so it would be up to someone else to figure out if those extra buttons are detectable in the input reports or if they exclusively mirror existing buttons. Updates to DSX seem to indicate that the extra buttons can be detected independently but I cannot confirm that.

**Comment by Ryusennin** [comment]
Only 200 bucks? It's about 350 euros on this side of the Atlantic 💰

**Comment by steffalon** [comment]
Attempted fix #2839

**Comment by asp0909** [comment]
edge... coming soon! works?

**Comment by steffalon** [comment]
It does work on my DS Edge, but someone else needs to test this feature to confirm its stability and functionality. I've managed to map these additional inputs. I've been looking through HID report and it appears to be reporting at mute input byte.

The changes have been made within the DualSense class. Maybe it's better to make it seperate?

Furthermore, there are several interesting features that could be added in DS4Windows, such as quick profile switching. The DS Edge does report which profile is set.

**Comment by Ryunam** [comment]
I have been testing the changes introduced with https://github.com/Ryochan7/DS4Windows/pull/2839. I can confirm that everything works nicely on my Windows 11 system. The four additional inputs are being remapped properly and work exactly as expected in all the games I've tried (multiple Steam games, as well as several emulators). Thanks a lot @steffalon!

One thing I noticed that seems to be missing in that PR is that the extra inputs are not listed yet among the triggers for "Special Actions". Just a negligible thing though, so far so good.

**Comment by Ryochan7** [comment]
Made the changes so the extra DS Edge buttons should work with Special Actions and Gyro triggers. Thank you @steffalon for finding out how to read the extra buttons from the HID report.

**Comment by Ryochan7** [comment]
Added support for the DualSense Edge in the test mapper. Getting some of the extra setup going was much easier with that mapper's design. Will probably need to clear up a few other issues before pushing an updated DS4Windows release.

https://github.com/Ryochan7/DS4MapperTest/releases/tag/v0.0.7

**Comment by steffalon** [comment]
There are a few things I've noticed when I was probing around using USB connection. Turns out that if the report id is set to 0x02 [0], you can report the edge controller to disable or enable feedback while changing profiles using one of the Fn + action button combination. It will write to the controller's memory and will be the same after reconnection.

<img width="614" alt="image" src="https://user-images.githubusercontent.com/20344094/223514349-80e0335f-6ed1-4816-84b6-2671dd7fd78b.png">

Especially useful for users who doesn't own a PlayStation 5 in order to configure their DualSense Edge controller.

**Comment by Nemitis** [comment]
The extra buttons are working fine for remapping, but they aren't available in the list of shift triggers. I do see "Side L" and "Side R" in the list, which I thought would be the paddle buttons, but it doesn't seem to be the case.

**Comment by fruwald** [comment]
> The extra buttons are working fine for remapping, but they aren't available in the list of shift triggers. I do see "Side L" and "Side R" in the list, which I thought would be the paddle buttons, but it doesn't seem to be the case.

First of all thank u for supporting the DS Edge so promtly, i rly enjoy the backpaddle key on PS5 and iam very pleased seeing them integreted on DS4 so quilky.

However, i can remap the new buttons quite fine but for me only the "Funktion Button L/R" seem to work.
The paddles on the back (it should be BottomPaddle L/R right?) dont seem to work in my case.
There was a Sony FW Update on the DualSenseEdge Controller wich i installed over my PS5 recently.
Could this have generally broken the support of BLP/BRP in DS4Windows or doesnt it work only for me?
FW-Version for the Controller is 0113

@steffalon mb u could shed me some light on this matter, since ur the one helping integrate Edge support according to patchnotes. 

some help in this matter would be much apreciated.

TY
all the best
