### ISSUE TITLE
No ability to switch audio from headphone to speaker in DS4Windows 3.2.7

### ISSUE THREAD

**Issue by mebalzer** [Ryochan7/DS4Windows#2801]
I noticed that there is no ability to switch between the headphone jack and the speaker, or both.  I noticed you removed a flag for audio and wondering why?

Latest build of DS4Windows 3.2.7

**Comment by Ryochan7** [comment]
There is a flag at the DS4 hardware level to set the output device between headphone to speaker. I have never checked whether performing that switch is possible when using the normal HID output report without sending audio data over. Never had a desire to try to use the speaker that way.

**Comment by Voha888** [comment]
In which version is audio output available?

**Comment by Ryochan7** [comment]
Never had the chance to test it since my previous post. That is how busy I am. Will have to try it out later. Even if changing the flag works and allows audio output from the speaker rather than the headphone, I doubt any setting will be put into DS4Windows to allow configuring that option. I will post a brief update here though. This project is pretty much on its last legs and I have no motivation left.

**Comment by Ryochan7** [comment]
Finally tried it out in USB mode. The flag does nothing in that case. Looks like that flag only matters when streaming audio to the DS4 via Bluetooth.

As it was, DS4AudioStreamer was about 90% of the way to getting clean audio streamed to the DS4 via BT but it would clip on occasion. It was definitely the best attempt put out by anybody and it mostly works. I am not sure if anything could be changed to make the experience slightly better.

https://github.com/asimonf/DS4AudioStreamer
