### ISSUE TITLE
PS Vita Support

### ISSUE THREAD

**Issue by krysztofz** [Ryochan7/DS4Windows#2816]
First of all, thanks a lot for your program, it runs magnificently and I've used it very happily with my PS4 controller. My request I realise is a little weird and not many people will find it useful, so I can understand it not being worth your time, but I thought perhaps it would be easy to implement. 

You see, there exists a plugin on the PS Vita which turns the console into a usb controller. You plug it in and it is detected as a game controller on Windows (and Linux) and if you look at the properties in the control panel all the inputs are detected, and also through the gamepad checker option on DS4Windows. That being said, it is not recognised in DS4Windows and any other solution for mapping the inputs simply failed when trying it in a game. It only seems to work in emulators such as gba, where you map the controller inside the app itself, or in some really old game, but all the inputs were wrong and unconfigurable.  

This is a very niche request, but posting it in case it's simply a matter of recognising an extra type of controller and not requiring any extra work, as everything seems to be detected fine otherwise. Thank you in advance.

**Comment by Ryusennin** [comment]
First you would need to provide the HID/VID of the Vita when connected as a USB controller.

**Comment by krysztofz** [comment]
Hmm, tried to find it in the Device Manager, is this it: HID\VID_054C&PID_1337&REV_0200 ?

**Comment by Ryochan7** [comment]
It would be up to you to try to make something work in DS4Windows since you have the hardware and it would likely require a completely new device reader class; just supplying the device VID and PID would likely not be enough. Not sure how much of a demand there would really be to use a PS Vita to emulate an Xbox 360 or DS4 controller on PC. I would assume that the Vita plugin allows the PC to see it as a generic HID gamepad that can be exposed through DirectInput. That would be the only way I know of that Steam would be able to use it to map the controller in any way although that would require mapping manually.
