### ISSUE TITLE
3.2.0 onward breaks support for DualSense

### ISSUE THREAD

**Issue by bangity** [Ryochan7/DS4Windows#2822]
**Describe the bug**
I have my PS5 DualSense controller connected through Bluetooth. Version 3.1.12 and below when start, they automatically recognize the controller and works fine. I downloaded many versions and tested each one from each extracted folder (x64.7zip). Version 3.2.0 is the break point.

**To Reproduce**
1. Start DS4Windows.exe version > 3.1.12 will fail to recognize DualSense controller. PS4 controllers still work.

**Expected behavior**
Expect the program to recognize the DualSense and function like PS4 controllers when connected.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense PS5
 - OS: Windows 11
 - DS4Windows Version 3.2.0 and above

**Comment by Ryochan7** [comment]
The very last note in the current Changelog (from version 3.2.8) disproves your original assertion.

```Grab firmware info for DualSense controller```

One possible problem that might cause DS4Windows to stop recognizing a DualSense controller is due to the settings reset bug from version 3.2.0. There was a bad copy paste in that version that caused Special Action data to override application settings in the Profiles.xml file. App settings saving was fixed in version 3.2.1. You will likely have to re-enable `DualSense Controller Support` in DS4Windows from `Device Options` so the app will open any detected DualSense controller; DS4Windows is set up to only work with DS4 controllers by default.

**Comment by bangity** [comment]
You are correct. Thank you so much. Maybe adding a popup message on the initial start up would be great as I have seen it has happened to several people not knowing where the Device Option button entails.
