### ISSUE TITLE
Trigger Effect no longer functions when switching profiles

### ISSUE THREAD

**Issue by raeleus** [Ryochan7/DS4Windows#2829]
If you have a trigger effect set for the Dualsense controller and switch profiles, the trigger effect deactivates and no longer works. This applies even when both profiles have the same trigger effect. Switching back to the previous profile does not activate the trigger effect either. To reactivate the trigger effect, you have to restart DS4Windows.

**Comment by Ryochan7** [comment]
Confirmed as a problem. The Trigger Effect setting saves properly in the profile so it looks like the backend event that changes the device is not fired. Got to look into it after Windows updates.

**Comment by Ryochan7** [comment]
Okay. The backend code is working as expected. The trigger mode is being set for the DualSenseDevice instance as expected. It just seems like the activation of the trigger effect is delayed for some reason. The trigger effect will not take affect until the lightbar color changes or rumble is activated. Looks like a secondary output report has to be sent before the trigger effect registers on the device. Not sure why.

**Comment by Ryochan7** [comment]
Found the issue and fixed it with commit 942ebec00b9504f9afa8a1f233f8b83d017b2a99. The core issue was that an output report was not being sent after the trigger effect was changed. No output report was being sent because the flag for sending reports was determined by the haptic state of the controller (rumble + lightbar). The trigger effects fall outside of those structs so the PrepareOutputReport routine would not set the flag to have the input thread run the WriteReport method.

In my case, the changed lightbar color would cause an output report to be sent. At that point, the old trigger effect (None) was still active. After the trigger effect was set for the device, PrepareOutputReport was being called but there was no way to tell the routine to calculate the CRC-32 hash and have the data sent to the device. Now the haptic state is set as dirty explicitly and the routine looks for that flag first.

**Comment by raeleus** [comment]
You're incredible! Thank you so much.
