### ISSUE TITLE
DS4Windows XBox Controller Model Doesn't Have it's Share Button

### ISSUE THREAD

**Issue by dropdan** [Ryochan7/DS4Windows#2862]
**Description**
So, I've started playing the new/old '_Fatal Frame: Mask of the Lunar Eclipse_' and in it's new(?) Photo Mode interface, it says we should Press F12 to snap the photo.
It's the only unbinded key in the interface while using a controller.
I believe it's because this button wasn't present on the original XBox 360 controller.

**Expected**
A Share Button on the XBox Controller keys layout to bind to it's share button.

**Additional**
I understand that DS4 Windows emulates the 360 Controller and this may not be possible and also it's not a huge deal since we can take screenshots on windows in the most different ways.
But it would be nice being able to bind the PS Controller Share button to it's counterpart on the XBox controller.

The share button is the one marked with the number 5.
![XBox New Buttons Controller Layout](https://user-images.githubusercontent.com/23439084/224065256-bf86fbae-3b1a-48bc-83b6-741effff5b26.png)

**Comment by Ryochan7** [comment]
Currently bound by the limits of what was available on the original Xbox 360 controller. Would need some means to support the expanded capabilities available with the Xbox One or Xbox Series S/X controllers in order to make this possible. IIRC, even Steam needs to install a custom driver to make this possible.

That would be more up Nefarius' alley as he is the one that makes the driver for emulating virtual controllers. DS4Windows just consumes the API exposed from his libraries; I have committed very little to the code base for the driver or libraries.

https://github.com/ViGEm/ViGEmBus
