### ISSUE TITLE
[Feature] Gyro jitter compenstation

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#2871]
Currently playing with the idea of adding a small jitter compensation curve on the low end of Gyro Mouse. It is just an adapted version of the jitter compensation Touchpad Mouse routine. The idea seems like it would help improve the overall Gyro Mouse experience and not have to rely on locking the cursor as often. Would need to find some decent baseline values before possibly adding such a feature.

Such a routine would probably also benefit Gyro Mouse-like Joystick.

**Comment by Dr-R100** [comment]
This would be fantastic, please let me know if I can help play with any baseline values

**Comment by Ryochan7** [comment]
Haven't checked back in a few days. Ended up lower the base values slightly from what I started with. Seems to be helpful overall. Similar routines have been added in to my test mappers as well and it helps with the Steam Controller.

I would like to compare the gyro behavior with other software (Steam Input primarily) to remind myself how much gyro gets throttled elsewhere.

**Comment by Dr-R100** [comment]
Any news on implementation? Thanks

**Comment by Dr-R100** [comment]
Thanks so much for adding! Any chance of adding for mouse joystick Gyro as well?

**Comment by midget35** [comment]
Good work on this. Was looking at the code around this myself. I've had a lot of luck mapping gyro to intercept analog stick inputs. This is a long term project to allow multiple lightgun support in MAME using DS4 constroller movement.

The only holdback I have now is the imprecision that things like gyro smoothing and your latest mouse jitter changes aim to fix.

A concise demonstration of the problem: If you move the gyro so the mouse cursor is at the bottom of the screen, then rapidly move the controller up so that the gyro takes the cursor to the top of the screen, the cursor will float back down again very slowly. 

We know it can be 'fixed' ('fully worked around' is probably the better term) as wii, wii u, switch emulators have mapped cursors with incredible accuracy for years. But we're not there yet. Know of any c# libraries out there that we might integrate into this project to facilitate this? 

Good work, again :)
