### ISSUE TITLE
DS4Windows causing multiple apps to hang

### ISSUE THREAD

**Issue by Ann1kaB** [Ryochan7/DS4Windows#2896]
DS4Windows is causing apps using WGI to hang when attempting to close them, also cant kill them in task manager or with wmic and taskkill.

**To Reproduce**
1. Open app that uses WGI
2. close app
3. go to task manager and the process will still be there
4. try to end task and it will give an "access denied" error.
5. open terminal and try to use `taskkill /im /f process` or wmic and the process cannot be found.

**Expected behavior**
The app using WGI closes successfully and will not appear in task manager.

**Images & Logs**
![image](https://user-images.githubusercontent.com/35402073/229211805-464f5d7d-9757-436d-b67b-85505567ea1e.png)
![image](https://user-images.githubusercontent.com/35402073/229211855-d6093311-ee5d-44da-99aa-0be41f1b3721.png)
![image](https://user-images.githubusercontent.com/35402073/229211903-17845ba7-41e8-47d6-8be4-d00ece2b6328.png)
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/11125301/ds4windows_log.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 11 Canary build 25330 22H2
 - DS4Windows Version: 3.2.9

**Additional context**
I used Visual Studio to figure out what went wrong with the process looking at a memory dump.

**Comment by Ryochan7** [comment]
Not sure if related but that looks like a real problem with pcsx2 more than anything else. Been a while since I actively worked with Qt but I have run across that QTimer problem in the past. I cannot remember what I have done to ensure the timer is stopped from the proper thread.

Also, it looks like controller hiding is not enabled so both the physical and virtual controllers are opened. Not enough to work off of to narrow down the issue. Doubt it has anything to do directly with DS4Windows itself. Might not even be an issue with ViGEmBus either based on the QTimer problem.

No matter what, nothing can be done about it at this point. Might as well close the issue.
