### ISSUE TITLE
Incorrect battery state and touch assigment with Sony DS4 adapter

### ISSUE THREAD

**Issue by jinkazama82it** [Ryochan7/DS4Windows#29]
Hi, I'm new here (I'm registered on gihub for write here), before yesterday I've used my ds4 on windows without problem but with the sony wirless adapter i noticed this problem:

1) when the DS4 controller (not the wirless adapter) are disconnected at reconnection DS4Windows set the battery state to 100% only close completely and restart DS4Windows solve the issue

2) when the DS4 controller (not the wirless adapter) are disconnected at reconnection the controller button binded with the touchpad don't work  only close completely and restart DS4Windows solve the issue

Isn't a big problem but if the user don't care of the state of connection before the start of the game can become frustrating to see not executed the given input or not receiving the right state of battery (just for fun yesterday I'm crashed my car into a wall because controller battery reached 0% but DS4Windows tell me 100% and not started to pulse the lightbar at 10%)

**Comment by Ryochan7** [comment]
Which version of DS4Windows are you using? I am not experiencing any of those problem with version 1.4.68.

**Comment by jinkazama82it** [comment]
Hi, thanks for the reply, I've started to use de adapter from v 1.4.68, I've tried to return at v 1.4.66 but the issue for battery persist, rather I would say it is even worse, not even a restart solves the battery problem, on the other hand I did not notice any problem with input from the touchpad in 1.4.66 version.

**Comment by Ryochan7** [comment]
I have seen some inconsistencies with the battery level being shown in the application. However, it does not seem like the problem is with DS4Windows as the battery level is updated once the reported battery state has changed. Unless there is something wrong with the current documentation for DS4 input reports, it seems like there is nothing that I can do about this. The input report is being interpreted as intended regarding charging state and battery status. It just seems that the DS4 puts out odd numbers sometimes.

I only have a version 1 Dualshock 4 but I would hope that nothing changed regarding how a DS4 reports its current battery level with the DS4 version 2.
