### ISSUE TITLE
[Feature Request] Working DS4 Touchpad when PC-Mouse is disconnected

### ISSUE THREAD

**Issue by fluffymadness** [Ryochan7/DS4Windows#291]
Hi, thanks for maintaining DS4Windows.
Do you think it would be possible to have the touchpad mouse controls still working when the physical mouse is disconnected?
Right now, as soon as I disconnect it from my computer, the mousepointer is gone and the DS4 Touchpad controls stop working.
I have a mini itx build that I mainly use it for gaming. When I use it on the tv,it is often the case that I don't have a mouse+ keyboard connected.
So this one would be a really nice feature addition.

**Comment by Ryochan7** [comment]
If I remember correctly, that is a limitation of the SendInput API offered by Windows. There is nothing that can be done by software to get around that problem. Out of curiosity, I might have to test vmulti and see if it has a similar limitation. vmulti is a driver that provides a virtual keyboard and mouse.

https://github.com/djpnewton/vmulti

**Comment by fluffymadness** [comment]
Hmm. I see. Thanks

**Comment by Ryochan7** [comment]
I cannot test the scenario like I would want. The vmulti driver does not allow the virtual keyboard to be disabled for some reason. I assume since Windows sees the virtual keyboard and mouse like physical devices that it would not suffer the same limitation. My main use for vmulti lately has been Touchmote but it is useful for using mapping utilities on games that have anti-cheat systems in place that block events generated by SendInput.
