### ISSUE TITLE
4 region touch button like ReWASD?

### ISSUE THREAD

**Issue by ClutterDrop** [Ryochan7/DS4Windows#2919]
Is there any special reason DS4Win Can't do the four region touch button like ReWASD can? 

Where Top right, Button Right, Top Left, and Button left touch on the touch bar/pad are all different buttons.

**Comment by Ryochan7** [comment]
I never tried how practical a 4 region touch setup would be but the DS4 / DualSense touchpad isn't that big. I would think it would be too easy to activate the wrong region button by accident when split to 4 regions. Steam Input can have the touchpad act as 2 region buttons similar to DS4Windows. Multitouch can be helpful in some situations although I do not really use it. I tend to use the extra top region binding more though.

It would be a bit difficult to attempt to change how virtual touchpad buttons are exposed in the mapper. The current buttons are fixed in the mapper routine. A different output mode for the touchpad would have to be made to attempt to allow for a change in virtual touchpad buttons. Probably not worth it.

**Comment by ClutterDrop** [comment]
Interesting. If it helps at all I can say from around 4,000 hours of game play with Rewasd and 4 region touchpad layout I'm fairly sure I had less than a couple dozen input errors and all of them were likely due to my own faulty memory more than it registering the wrong input.

I actually think it might be because the touch pad is so small that it works so well. it's really easy to aim for the corners of the touchpad with your thumb and always hit the top or button region.

Rewasd is so heavy and un-user friendly, I really want to stop using it, but nothing else splits the touchpad into 4 regions. Which is just such a handy layout for so many games since it gives me 4 extra easy/fast buttons to press.  With DS4Win I get the "top" touchbar button which Rewasd doesn't have, but it's not as useful as it's much harder and slower to hit accurately, and I actually do find that it miss triggers easily, I have to be very careful about how I press the top bar to avoid a left or right region button instead. 

As a side note:
I actually used DS4Win for about 1,000 hours before I moved to Rewasd for a few years, and have come back to trying DS4Win. So I did get quite a lot of testing/practice in with the the Left/Top/Right layout before I moved to the rewasd 4 region layout.

**Comment by Ryochan7** [comment]
Finally got around to trying it out again. The 4 region layout is actually feasible with the DualSense due to its slightly larger touchpad compared to the DS4. The DS4 touchpad is too small even for my somewhat small hands. I can easily end up touching the wrong region by mistake.
