### ISSUE TITLE
I can not create a custom macro

### ISSUE THREAD

**Issue by Blankylord** [Ryochan7/DS4Windows#292]
Hello I have a problem when creating a macro, I was used to the inputmapper method that was easier, since I can not make a macro in which I can press a button and consider it pressed until I return to another click on that same button, for example, I want to press X and stay pressed until X is pressed again, then the macro will be deactivated. How would it be possible? can you help me please. (thanks and sorry my bad english).

**Comment by TristanYoung** [comment]
I think what you're looking for is an on/off toggle.  One press to turn on, one press to turn off.  I don't think DS4Windows can do it right now.

May want to give this a better title, 'Toggle button triggers' since this isn't about creating a custom macro, but it is about adding a new method that can be used to trigger macros.

**Comment by Blankylord** [comment]
mmm I understand what you want to say, I assumed something so there is no possible option, I'm really happy with this wonderful tool and the way that Ryochan has focused on giving good support and improvements, I stopped using inputmapper because there were always problems in every update of windows and probe the tool of Ryochan and a wonder problems 0, the only thing that made less of inputmapper is its menu of creation and design of macros, it was fascinating, but I appreciate the help to my query thank you very much.

**Comment by Ryochan7** [comment]
There is no way to perform a toggle action for XInput bindings with the current backend setup; there is a minor toggle option for keyboard key bindings. The whole mapping system is really messy so that part of the project does not get touched that often. Doing more than adding minor improvements would probably require a complete rewrite at this point. For my use case, improving the output performance of XInput bindings has been the top priority. I would use Steam if I needed a more complex controller mapping setup to play a game.

I have never used the Macro Builder in InputMapper but some of the demo videos on the IM YouTube page have been interesting to watch.
