### ISSUE TITLE
Window is Off Screen after unplugging secondary monitor

### ISSUE THREAD

**Issue by crashedapp** [Ryochan7/DS4Windows#2941]
Use Two Monitors Side By Side.
Move the DS4Window to the Secondary Monitor.
Close the DS4Windows app
Disconnect the Secondary Monitor
Start DS4Windows.
The window will be off the screen.

**Comment by kurtanr** [comment]
I was able to reproduce this issue, and probably also the issue reported in #2626.
Cause of the issues is manual code which is trying to position the window, but there are a lot of edge cases which are difficult to cover. An unplugged monitor is one of them.

Another issue which is not covered is negative coordinates for window position - these should be allowed. In a multi-monitor system, a window which is located on a monitor to the left of the primary monitor will have negative coordinates. Multiple parts of the code contain clamping of window location to be > 0 - this is why window cannot be restored on some monitors.

Proposed solution (for which I have a working prototype) would use logic similar to this:
- https://github.com/microsoft/WPF-Samples/blob/main/Windows/SaveWindowState/MainWindow.cs

Instead of trying to manually cover all the edge cases, calculation of them is left to Windows and the [SetWindowPlacement](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowplacement) function.

If it is ok, I can create a PR?
