### ISSUE TITLE
There is a 150,000 millisecond delay before starting DS4Windows from sleep.

### ISSUE THREAD

**Issue by AmuletOfNight** [Ryochan7/DS4Windows#2948]
**Describe the bug**
Every single time I wake my computer from sleep, consistently, DS4Windows is unusable, for approximately 2 minutes.

It is PROBABLY this code:

https://github.com/search?q=repo%3ARyochan7/DS4Windows%20150000&type=code

https://github.com/Ryochan7/DS4Windows/blob/9cc2418364846abe9816cc0cd9d73d7dfde03b37/DS4Windows/DS4Forms/MainWindow.xaml.cs#L495

Needs to be changed to:

```
Task startupTask = Task.Run(() =>
{
    App.rootHub.Start();
});

```
Can we remove the over 2 minute delay on power resume, please?

**To Reproduce**
1. Wake computer from sleep
2. Observe.

**Expected behavior**
I would expect DS4Windows to resume in a reasonable amount of time, not 2+ minutes.

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Also, please add the most
log file (ds4windows_log.txt) from the Logs folder in your DS4Windows config folder.

![image](https://github.com/Ryochan7/DS4Windows/assets/502422/9f701a5c-acbb-49a2-ab5f-4181e5f67c5c)

[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/11523005/ds4windows_log.txt)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DualSense (CFI-ZCT1W)
 - OS: [Windows 11 Pro 22H2 22621.1702]
 - DS4Windows Version [3.2.10]

**Additional context**

**Comment by AmuletOfNight** [comment]
I did just build a copy of DS4Windows with this fix, and it appears to have resolved my issue.

**Comment by DistractionRectangle** [comment]
It was introduced as a work around for issue #2869

**Comment by Ryochan7** [comment]
> Can we remove the over 2 minute delay on power resume, please?

Unfortunately, no. The arbitrary delay is imposed because it seems like the ViGEmBus driver is not ready by the time the system is initially resumed. Trying to re-connect with ViGEmBus too early will result in a connection failure that cannot be fixed until DS4Windows is restarted. FakerInput does not seem to suffer from this problem and DS4Windows is able to connect to FakerInput almost immediately after the system is resumed.

My system barely ever resumes properly so I cannot readily test the suspend and resume routines.

**Comment by Ryochan7** [comment]
My system is somewhat cooperating with suspend currently; cannot guarantee how long that will last. Anyway, playing with the routine again. Ended up lowering the resume delay to 5 seconds and no problems so far. It has actually worked with no delay enabled on system resume but I cannot trust no delay to keep working reliably. Will temporarily re-open this issue since it is relevant again.
