### ISSUE TITLE
Controller failing to reconnect via BT

### ISSUE THREAD

**Issue by rafsanjani** [Ryochan7/DS4Windows#296]
After pairing my controller to a friend's laptop running DS4Windows, my laptop fails to connect to the controller again. I always have to go into the Bluetooth manager and forget the device and pair it again. Just like every Bluetooth device, I was hoping that the controller would connect to the device in closest proximity since my friend's laptop is no more in range but this doesn't happen. I always have to remove the device and pair it again using (options + share).

**Comment by Ryochan7** [comment]
That is outside the control of DS4Windows. I tried the scenario with multiple BT adapters and attempting to connect the controller to a previously paired adapter does not seem to work. Re-connecting only works with the most recently paired adapter. This was tested against the BlueZ BT stack on Xubuntu so that should eliminate the Microsoft BT stack being a factor.
