### ISSUE TITLE
DS4Windows breaks with Steam Open after Newest Steam Client Beta Update

### ISSUE THREAD

**Issue by WiseEXE** [Ryochan7/DS4Windows#2961]
**Describe the bug**
After updating to the newest Steam Beta client, my DS4 controller does a variety amount of inputs based on what button/stick is pressed. For starters once DS4Windows is enabled, the Steam on screen keyboard automatically comes to screen. Then more errors occur such as moving the left stick causes my system to ALT+TAB, hovering over any icon object immediately causes a click, etc. 

**To Reproduce**
1. Have the latest Steam Client Beta
2. Start DS4Windows
3. Connect DS4 Controller (what I currently use)

**Expected behavior**
Normally functions acts as a standard controller, but I believe the issue occurs due to a conflict with HIDHide and the new Steam Beta, though I haven't peeked too far into my logs to see any interactions.

**Screenshots and Logs**
Slight Demonstration
https://gyazo.com/2a70a6125c894d4fe173c2ceb7c41523 
(Sorry for the poor quality, its hard to record, with how it sort of takes over the system.)

[ds4windows_log_20230531.2.txt](https://github.com/Ryochan7/DS4Windows/files/11617338/ds4windows_log_20230531.2.txt)
**

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2A)
 - OS: Windows 10 22H2
 - DS4Windows Version 3.2.10

**Additional context
Closing Steam fixes this issue, but as its a new problem I've encountered I thought I should at least make the Bug report.

**Comment by Ryusennin** [comment]
You should change the name of your executable to something else (DS4Win.exe for example). Steam has been acting up for months when specifically detecting DS4Windows.

Also make sure DS4Windows.exe (as well as DS4Win.exe or whichever name you chose) are properly whitelisted in HidHide. And I should have to mention it, but verify that the physical "Sony Wireless Controller" is also blacklisted in HidHide, otherwise you *will* get double inputs.

Last but not least, completely disable Steam Input, which does obviously conflict with DS4Windows since both mappers do the same thing.

**Comment by Ryochan7** [comment]
I have experienced this as well since the most recent Steam client update. I do not even have PlayStation Configuration Support enabled but that does not seem to matter. My guess would be that Steam is not opening the device as an HID device but now going through the extra steps to use libusb (or something similar) to use the USB interface instead. If that is the case then HidHide can do nothing to block access currently; it does not set up any filter for the USB control class.

Would not be surprised if this breakage was intentional by Valve.

**Comment by Ryochan7** [comment]
Looks my experience was a consequence of my own recent experiments. Migrated to the latest HidHide but the vanilla driver is sluggish so I had to tweak and recompile it. My PowerShell history did not show an entry for re-applying the UpperFilter for the HIDClass so HidHide was not set up properly. Checked again and HidHide is able to hide controllers from Steam so nothing of consequence changed with the Steam client. So my experience was my own fault and is not relevant for this issue.

Now that the one scenario is ruled out, the next check would be to make sure the UpperFilter for the HIDClass still exists. Going to have to pull up regedit and check the following registry key

```HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Class\{745a17a0-74d3-11d0-b6fe-00a0c90f57da}```

![hidhide_upper_filters](https://github.com/Ryochan7/DS4Windows/assets/581968/3921e560-d144-424f-92da-6cbe2c42bde4)

Check for a value for `UpperFilters` and check that `HidHide` is listed there. IIRC, Windows Updates sometimes overwrites the value for UpperFilters during certain hotfixes. Looking at the HidHide.inf file, there is no listing for the UpperFilters entry but relies on devcon.exe to write it instead. In that case, Windows Update can reset the current value but not know to re-write HidHide back in when it is done. I want to think I mentioned potential complications regarding this in the HidGuardian days but that was a long time ago. Wasn't going to bother to bring it up for HidHide and get more backlash.

**Comment by andreycout** [comment]
Steam Input just broke in general in the May 30th beta update. They have released a fix today: https://store.steampowered.com/news/group/4397053?emclan=103582791433918461&emgid=3674420533442925819

> "Steam Input
> Fixed wacky input from Xbox controllers and periodic disconnect of Bluetooth Steam Controllers, introduced in yesterday's update"
