### ISSUE TITLE
The right stick always leads down - Switch Pro Controller

### ISSUE THREAD

**Issue by Alexey71** [Ryochan7/DS4Windows#2967]
**Describe the bug**
The right stick always leads down. Switch Pro Controller (IINE Phantom Elite Pro). I try used other program JoyShockMapper or BetterJoy, its fine

**To Reproduce**
1. Start DS4Windows
2. Connect Switch Pro Controller

**Screenshots and Logs**
[ds4windows_log.txt](https://github.com/Ryochan7/DS4Windows/files/11645435/ds4windows_log.txt)

![2023-06-04_135438](https://github.com/Ryochan7/DS4Windows/assets/10572914/49731a0f-302e-4fd1-9442-1adad9ad040a)

**Desktop (please complete the following information):**
 - Controller Make and Model: IINE Phantom Elite Pro
 - OS: Windows 11
 - DS4Windows Version 3.2.11 and previous version

**Comment by Alexey71** [comment]
@Ryochan7 How fix?

**Comment by Ryochan7** [comment]
That position is way off. Maybe no stick calibration data is read from the controller so DS4Windows has no idea what the stick bounds actually are. I do not know if some of the later JoyCon related changes would even help do anything about this sort of problem. Not sure why it would work in other programs but not DS4Windows. I do not think either program uses failsafe default values but rely on the same stick calibration data fetching. Hard to diagnose the problem without said hardware.

**Comment by Alexey71** [comment]
I tried the program https://github.com/CTCaer/jc_toolkit
Maybe this will help you?
![2023-06-24_205726](https://github.com/Ryochan7/DS4Windows/assets/10572914/d2c7541e-05d5-4def-9944-589c996f302f)

**Comment by Ryochan7** [comment]
So there is a user configuration available? I have only dealt with factory calibration data since I do not own a Switch console. Double checking the DS4Windows code now and it looks like user calibration parsing might actually be wrong for the Right Stick; stick max and min might be swapped. Need to check in BetterJoy but data indexes are changed for user calibration on RS but LS uses the same indexes for both factory and user calibration.

Also, that program does not work on my system anymore for some reason. I have used it in the past when I first got my JoyCons but very few features seem to work for me now; it can detect the controllers so that is not the issue.

**Comment by Ryochan7** [comment]
Double checked and RS user calibration is wrong. It was my own flaw as BetterJoy does not really do the couple extra steps I am doing.

https://github.com/Ryochan7/DS4Windows/commit/a7a22fa9de2b87c68e1994017d114e8b034105f6

**Comment by Alexey71** [comment]
Thanks, I'm waiting for the release to check the fix

**Comment by Alexey71** [comment]
Now fine.
![2023-06-26_014447](https://github.com/Ryochan7/DS4Windows/assets/10572914/c159dc00-6fa0-4224-8450-e3ee7e8d94c4)
