### ISSUE TITLE
[Feature Request] Macro Enhancements

### ISSUE THREAD

**Issue by stan-snf** [Ryochan7/DS4Windows#30]
I think 2 features that would be really helpful are:
1. Key combination trigger repeating macros.
2. Toggle macros.

Right now you can only assign "repeat while held" macros to one button instead of a key combination.
Just a few things to consider

**Comment by Ryochan7** [comment]
I have never played with the macro system but those options sound like they would be useful. I will have to see how feasible it would be to add that functionality.

**Comment by stan-snf** [comment]
Thanks.
Btw, if i ever want to contribute, is there any standards you'd want to implement?

**Comment by Ryochan7** [comment]
Looking back at this issue, I will have to file this request as not feasible. Besides not really liking the macro system, I don't even like how DS4Windows handles keyboard and mouse support in general. It is too easy for keys and buttons to remain active after removing a controller and there seems to be no easy way to fix that since there is no real association between controllers and keys.

For more complex keyboard mapping, I still end up having to rely on either Xpadder or antimicro.
