### ISSUE TITLE
[FEATURE REQUEST] Gyro Calibration Special Action

### ISSUE THREAD

**Issue by Yankwerks** [Ryochan7/DS4Windows#3000]
Title is quite self explanatory, seems like something that would require a minimal amount of work.

Currently there's no way to map a controller button to the gyro calibration option. This would be quite useful as it would get rid of the hassle of having to open DS4W and navitgate to the gyro tab of the respective controller profile constantly.

I currently have to re calibrate my controller (3rd party switch pro controller) each time I want to use its gyro controls because there's a notable drift despite it being stationary. It works perfectly fine otherwise.

**Comment by TheCarrotCR** [comment]
I'd also suggest some auto calibration option. I'm not sure how to implement this, but since Steam can do it then it's possible.

Though it's not that neccessary. Bind is way more simple solution I guess, since the app already has all needed functionalities implemented, and is definitely needed and required. I mean, why even there's combo bind function if you can't bind calibrations?

**Comment by Yankwerks** [comment]
Bump?
