### ISSUE TITLE
“ Using Shared Mode “ 

### ISSUE THREAD

**Issue by skorioo** [Ryochan7/DS4Windows#3009]
Hello i have a issue where every time i try to connect my ps5 controller to ds4 it doesn’t connect, its says “ using shared mode “ which i dont know what that mean, i try to look all over youtube to fix the problem. Couldn’t find nothing

**Comment by Ryochan7** [comment]
Everything other than DS4 support is disabled by default. Mainly it is due to trying to not cause conflicts with Steam Input. I plan on changing the first launch routine to give some options for enabling device support at some point.

Also, Shared Mode just means that other apps will be able to detect the original input controller. Exclusive Mode is when only DS4Windows will have access to the input controller so other apps will only see the virtual controller. The old workaround does not really work in modern Windows anymore so you would likely have to use the HidHide driver when you want to hide the input controller.

https://github.com/ViGEm/HidHide

**Comment by Sonic04Boom** [comment]
> Nevermind figured it out in devicd options turn on duslsense

I'm sorry but I'm having the same issue, and I can't understand how you got yours working. Where's device options?
