### ISSUE TITLE
No Vibration on DualShock 4 V2 Controller When Virtual Mode is Disabled or Dualshock Emulation is Enabled

### ISSUE THREAD

**Issue by ZazaryX** [Ryochan7/DS4Windows#3016]
Hello everyone,

I recently purchased a DualShock 4 V2 controller and have encountered an issue that I would like to discuss. My controller is connected to my computer via a wired connection (not using Bluetooth), and all the functions related to Xbox 360 emulation are working properly. However, I'm experiencing a problem with the vibration.

I have tried various solutions and tested the controller using a testing program, where the vibration works perfectly fine when using the DualShock 4 V2 or when the emulation is disabled. However, in games, the vibration doesn't work except when using Xbox 360 emulation.

I have tested games such as For Honor, Mortal Kombat 11, Dead Cells, and others, and found that vibration only works when using Xbox 360 emulation, not with the DualShock 4 V2 controller.

I'm reaching out for assistance. If anyone has a solution to this problem, please share your knowledge. I would appreciate any information or recommendations that can help me restore vibration functionality on the DualShock 4 V2 controller in the mentioned games.

Thank you in advance for your help!

**Comment by Ryusennin** [comment]
It could be a number of things that are not properly configured in DS4 mode, but the first that comes to mind is the lightbar. By nature it conflicts with the rumble feature, so make sure the lightbar mode is set on "normal" and not "passthrough".

You should also check that you have installed and correctly set up HidHide to mask your physical Sony controller, otherwise it will conflict with your emulated controller (be it X360 or DS4).

**Comment by ZazaryX** [comment]
Hello,

It's possible that the issue is related to incorrect HidHide settings, but I cannot say for certain that this is the exact cause. When I use Xbox 360 emulation, the Lightbar only turns on when there is vibration, otherwise it remains off. In the settings, I have it set to "Normal" mode. However, when I switch to Dualshock emulation, the Lightbar is always active, unlike in the Xbox 360 mode. I have verified that vibration works without using DS4Windows, both in games that support Sony controllers and elsewhere. However, in the game Dead Cells, vibration doesn't seem to work for some reason, and the Lightbar is also absent without using DS4Windows.
![1](https://github.com/Ryochan7/DS4Windows/assets/110578041/680282a8-f1cc-48e3-a649-ee331ff370a2)

**Comment by Ryochan7** [comment]
Which version of the ViGEmBus driver are you using? Probably should have included the DS4Windows Log file. If vibration on the DS4 works natively (if you are not actually using Steam Input by accident), DS4 vibration would only work if you are using ViGEmBus 1.21.442.0 with DS4Windows. Older versions of ViGEmBus did not process vibration data properly for DS4 emulation so support for emulated DS4 vibration is disabled when using older ViGEmBus drivers.

Version 1.21.442.0 has a different API to hand off the full data buffer to a client program which allows DS4Windows to process the various features (lightbar color, flashing, rumble) directly.

**Comment by Guzmaz** [comment]
I'm having the exact same issue but with my Dualsense controller instead, vibration works when tested in DS4, but doesn't work in game when emulating a Dualshock 4 controller, and does work when using 360 emulation, HidHide is setup correctly AFAIK. Heres my log
[log.txt](https://github.com/Ryochan7/DS4Windows/files/12479841/log.txt)

**Comment by Kanuan** [comment]
>  By nature it conflicts with the rumble feature, so make sure the lightbar mode is set on "normal" and not "passthrough".

DS4Windows separate both features and you can use any lightbar mode without interfering with rumble, the issue is not related.

>  where the vibration works perfectly fine when using the DualShock 4 V2 or when the emulation is disabled

Open the [gamepad tester website](https://hardwaretester.com/gamepad) and with the controller being detected in Virtual DS4 mode test the "vibration" button. If it vibrates in the site then it should vibrate in-game IF the game supports DS4 vibration.

There are some games that have superficial support for DS4 controllers: they can detect the controller, but don't set the lightbar or support rumble.

From a quick google search, Mortal Kombat 11 does not have vibration support, there are other people complaining about the same issue. Not sure about deadcells and others.

Some games may require using Steam PS controller support to have proper DS4, for example, I think Horizon Zero Dawn requires Steam Input enabled to have lightbar/vibration with PS controllers.
