### ISSUE TITLE
XInput port randomly increases when controller is disconnected and reconnected

### ISSUE THREAD

**Issue by jernejs** [Ryochan7/DS4Windows#302]
It appears that sometimes when controller is reconnected after it was disconnected, the XInput port number is increased - at first I thought DS4Windows simply stopped working (exiting and restarting DS4W sometimes -but not always- helps), however using Test Device in LillyPad shows that the controller is responding on higher-numbered XInput Pads.

**Comment by Ryochan7** [comment]
As long as DS4Windows is closed properly then that problem should not happen. There is no guarantee it will not fail if DS4Windows is forced closed although I have not experienced problems when killing the DS4Windows process while testing changes.

Even though it is not related to DS4Windows, I will mention that I recently had this problem with Touchmote. ScpVBus kept the first port even after Touchmote was closed and a real Xbox 360 controller was stuck getting assigned to port 2. I ended up rebooting my computer to get access to the first port again although a disable and enable of the ScpVBus device might have been sufficient.

It would be nice to be able to migrate to ViGEm at some point since I have not had problems with that driver holding on to a port.

**Comment by Ryochan7** [comment]
This was likely a problem due to Windows 7 BT connection quirks. A longer delay before attempting to detect devices fixed that problem as Windows presented and remove entries early for some reason. It would happen too quickly for ScpVBus to be able to handle so old ports would not be fully closed.

**Comment by jernejs** [comment]
Will report if this still happens. I'm on Windows 10 thought.
