### ISSUE TITLE
Rumble problems with DS4 gamepad

### ISSUE THREAD

**Issue by 0Karka** [Ryochan7/DS4Windows#3027]
Hello everyone. i want you to help me with my issue. So, when i connect my copycat DS4 gamepad to PC with bluetooth, my PC see that gamepad as wireless gamepad, i open DS4 windows app and go to profile edit to other, turn on test heavy and light. so it work. BUT, when i start playing some games, at least GTA 5, there is no any rumble. When i connect gamepad with usb cable, there is the same problem. Profile is default, rumble is ON, so i have no idea how to fix it.

**Comment by Ryochan7** [comment]
GTA 5 uses the DS4 as a DirectInput controller. There is no rumble because the game does not support it for anything but Xbox controllers. It is usually a safe bet to assume that rumble will not work for a DS4 or DualSense unless a game uses native DS4 or DS modes that support the other advanced features such as the lightbar.

**Comment by 0Karka** [comment]
I've already read the message from this page: https://github.com/Ryochan7/DS4Windows/issues/1196  and understood, that i need switch controller mode in profile to Xbox360, and it work. But when i use bluetooth there is some issues, like my controller rumble less then 1 sec with any action. I dont know the reason, but thank u for your work <3
