### ISSUE TITLE
Installer does not find .NET installation

### ISSUE THREAD

**Issue by svee4** [Ryochan7/DS4Windows#3028]
**Describe the bug**
When running the installer, it shows the message _.NET install was not found_, even though .NET is installed

**To Reproduce**
1. Download .NET runtime from the link provided in README.md (https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.16-windows-x64-installer)
2. Download and run the installer (https://github.com/Ryochan7/DS4Windows/releases/download/v3.2.13/DS4Windows_installer_x64_v3.2.13.exe)

**Expected behavior**
Installer finds .NET installation and proceeds as normal.

**Screenshots and Logs**

Registry editor shows .NET installed
![regedit](https://github.com/Ryochan7/DS4Windows/assets/85372594/4be26409-342b-4228-9980-f4f95cb146c0)

Dotnet CLI info
![dotnet-info](https://github.com/Ryochan7/DS4Windows/assets/85372594/d85c77d7-6ea1-434f-995c-dd986ee74b31)

**Info**
 - OS: Microsoft Windows 10 Home | 10.0.19045 N/A Build 19045
 - DS4Windows Version 3.2.13 (https://github.com/Ryochan7/DS4Windows/releases/tag/v3.2.13)
 - Fresh install of Windows, .NET was not installed previously

Also tried with .NET 6.0.20 and 7.0.9, no effect

**Workaround**
For those looking to install the app, just follow the instructions found in https://ds4-windows.com/get-started/

**Comment by raeleus** [comment]
I'm having the same issue on Windows 10 Pro 21H2. The zipped version runs fine.

**Comment by trowieuk** [comment]
same issue here, I've tried all zipped and installer.

**Comment by NicTech-1989** [comment]
Same issue here keeps showing this.
Have Installed Desktop Runtime 6.0.15 and 6.0.20
Windows 10 Pro 22H2 Build: 19045.3208
![Screenshot 2023-07-29 210740](https://github.com/Ryochan7/DS4Windows/assets/74213698/a0479eee-b14d-4388-8829-d80d7c0202d2)

**Comment by BustedSec** [comment]
Temporary Workaround - Use 7zip to extract the files from the installer and just then just run the .exe for the program

**Comment by Ryochan7** [comment]
Found an error with registry value enumeration with that routine. Although, that error should not have mattered in this case as only one value exists at that key. Also, that installer was still using helper apps compiled against VS 2022 redistributable rather than against 2019 like I wanted; that change might be relevant here. I will get an updated installer link posted here later.

**Comment by Ryochan7** [comment]
DS4Windows_installer_x64_v3.2.13_try2.exe
https://drive.google.com/file/d/1s-MCsds23p_rW7TUa3LBSyrNTalcLfsR/view?usp=sharing

**Comment by NeroSiegfried** [comment]
Still got the same error from the try2.exe file

**Comment by svee4** [comment]
Same for me, shows the same message as before.

**Comment by BustedSec** [comment]
I tried the two executables uploaded and has the same behavior happen. Perhaps it's best to comment out the function that checks for the .net framwork and replace it with a dialog box saying this software requires .net framework, such as "This application could not be started" you should download the framework from <url>" or something to that nature.

**Comment by InsanePanda** [comment]
Same issue for me

**Comment by Ryochan7** [comment]
Seriously wondering if this is all just stemming from Windows Defender refusing to allow the helper executables to launch on other people's machines since they are not signed? If it were not for the value enumeration, I would just move the .NET Runtime registry check into the install script. I guess I can just not have the install script exit if it fails to find the registry value.

**Comment by BustedSec** [comment]
I would remove the check completely and just put a popup letting the user know that the program requires .net framework.

**Comment by garberlog** [comment]
So, is there a solution to this problem yet? As I just tried to use the installer and got this same issue.

**Comment by svee4** [comment]
> So, is there a solution to this problem yet? As I just tried to use the installer and got this same issue.

You can install it manually, see https://ds4-windows.com/get-started/

**Comment by Ryochan7** [comment]
I suck. The installer is busted in at least 3 different ways.

I was mistaken about my current PC being unable to run Windows 10 in a VM. It is a stretch with 8 GB of RAM but it is doable as long as the host OS isn't running much; I got about 2.5 GB of RAM dedicated to the guest OS. Finally had a test target to use and the installer did not work. The primary problem was due to a misunderstanding about how to deal with temporary bundled executables using NSIS in the first place. The .NET install check was failing because the helper executable could not be found.

It was a lot more work to try to resolve the problems with getting the helper executables working properly outside my dev environment. Using the IfErrors call was not the proper check to be using for checking for the return code in some cases (when using ExecShellWait). Ended up changing some other checks in the process. Now the installer works in the VM as I originally intended.

I will attempt to get an updated installer posted here later today. Not sure it will actually happen though.

**Comment by Ryochan7** [comment]
Trying this again

DS4Windows_installer_x64_v3.2.13_try3.exe
https://drive.google.com/file/d/168Sn-BfYaNAjm4HK2QVsANJE6uBX01Z6/view?usp=sharing

**Comment by Ryochan7** [comment]
Already changed it up. Flagged FakerInput as an optional component.

DS4Windows_installer_x64_v3.2.13_try4.exe
https://drive.google.com/file/d/16xQ2a_Iuy5Mitd_v8_m10AjXXg7xrTi9/view?usp=sharing

**Comment by Ryochan7** [comment]
Again. Used outdated component. Fumbling too much AFK

DS4Windows_installer_x64_v3.2.13_try5.exe
https://drive.google.com/file/d/1Sy5J2RmFPDyzM-haLElaajhMdcelPDMT/view?usp=sharing

**Comment by svee4** [comment]
Still same issue for me with try5

**Comment by Ryochan7** [comment]
At this point, it might be the case that the Visual C++ Redistributable 2015-2022 package is not installed on your system; that package is noted as an explicit system requirement for the test mappers. The two helper executables are compiled against Visual C++ 2019 so you need at least that version installed on your PC. I ended up adding an additional check checking if the first executable failed to launch in the NSIS script and warn the user about it.

Will get an updated link here in a bit.

**Comment by Ryochan7** [comment]
DS4Windows_installer_x64_v3.2.13_try6.exe
https://drive.google.com/file/d/1JRq7B0pEz0C5eRIFnuNOkVEtmMvkrUNB/view?usp=sharing

**Comment by BustedSec** [comment]
Tested Try6 and it installed properly, it prompted for additional installer, which completed. Program launched and works fine without requested additional reboot. 
<img width="378" alt="2023-08-29 13_43_01-Greenshot image editor" src="https://github.com/Ryochan7/DS4Windows/assets/7432967/8436d380-6725-4cf6-933d-91f1d86b6cad">

**Comment by stefanelul2000** [comment]
Hello, 

I might have gotten a bit later into the party but even with the latest provided installer, I am not able to launch the app.  Although the installer ran without any issues for me.I am getting the following error:

![DS4Windows_8yV6rkXIzh](https://github.com/Ryochan7/DS4Windows/assets/42817352/8fe30bcf-2297-4b51-b70d-22c76583ef90)

The .NET runtimes I have installed are the following:
```
dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

And the SDKs:
```
dotnet --list-sdks
6.0.400 [C:\Program Files\dotnet\sdk]
7.0.102 [C:\Program Files\dotnet\sdk]
```

**Comment by Ryochan7** [comment]
That is good news. I got the email notification about the other post and that .NET Desktop Runtime check is bundled in the main executable when targeting the .NET Runtime. That error is actually Microsoft's problem. Maybe a reboot would have been enough to work around that problem.

Also, I uploaded more recent source files for the setup files

https://github.com/Ryochan7/NSIS-Setup-Files
