### ISSUE TITLE
Cannot Set DualSense Rumble Level to 0%

### ISSUE THREAD

**Issue by PhysicBerry** [Ryochan7/DS4Windows#3029]
The DualSense controller rumble motors activate with audio when using the headphone jack in surround sound applications. An effective workaround for this is to disable the rumble motors. However, under "DualSense specific rumble settings" the lowest value you can select is 12%, which improves the problem significantly but 0% would solve the problem completely. This is observable as an effective solution in DSX, which already supports this.

It is also worth noting that just setting regular Rumble to 0% doesn't resolve the issue, nor does setting "Rumble mode and strength level" to "disabled".

**Comment by Ryochan7** [comment]
I thought I responded to this but maybe not. Checked it out and the lower limit of 12% is dictated by the DualSense hardware for that setting. There isn't anything that can be done about that one.

Not sure why the Rumble Boost setting is not being used. Checked that and it does not seem to work currently at least with the DualSense. I will look into that.

**Comment by Ryochan7** [comment]
Looks like that Rumble Boost behavior is actually a feature. In order for Rumble Boost to be usable with the DualSense, you have to check the **Force usage of both % strength levels** setting in the **DualSense specific rumble settings** section. Otherwise, the rumble boost will always return as 100%. That was added in by Kanuan with commit 853d4cf20d2d366465dd1ca3fa9d6c0352ebb1b6.

Looks like you will probably want to enable that option if you want to force the rumble boost setting to be used.
