### ISSUE TITLE
Ds4 driver fails to install No log recorded.

### ISSUE THREAD

**Issue by Demonshaw** [Ryochan7/DS4Windows#305]
Have tried installing as an appdata save and as a programfile save neither will complete the driver install it just hangs on "opening installer" then fails and no logs are recorded so I can't post those. Any idea guys?.

**Comment by Ryochan7** [comment]
I am pretty sure that you are using the old Jays2Kings build. The web site where the driver installer is hosted was temporarily down at the end of last month due to exceeding the allocated bandwidth. This build hosts the ScpVBus driver installer on a different server and there have been no issues with downtime. I tested the installer a few days ago and it worked fine.
