### ISSUE TITLE
High Input Delay On BT Mode in comparison with Original Version of DS4Windows

### ISSUE THREAD

**Issue by orator89** [Ryochan7/DS4Windows#307]
Hi,

I have an originale Ds4 Controller (V2), and I have both the official version of Ds4Windows (1.4.52) and your version, ryochan7. I noticed, in Bluetooth mode, that when I use the Official version I have only 1,4ms Input Delay in bluetooth mode, instead using your version (last one updated, 1.4.119) I have 7/8ms input Delay.. Why?

Thanks in advance

**Comment by Ryochan7** [comment]
The input delay on the latest version should be around 4 ms by default. It seems like the last few releases of DS4Windows has caused people some problems regarding BT connection stability. Some changes have been made to how output packets are processed that seemed to help on my test VM; I did not experience problems on my main rig. Hopefully the next release will respect the default 4 ms delay.

You might be wondering why 4 ms is the default as opposed to the old ~1.4 ms delay being used in 1.4.52. The reason for that decision is due to ScpVBus. I have tested it on multiple occasions and using the smaller delay actually causes extra delay for ScpVBus and increases perceived input lag. That problem does not happen when using KB+M emulation and using the ~1.4 ms delay is clearly the winner in that situation. The emulated KB+M scenario was tested while playing the GOG release of Gex with emulated KB controls. Better battery life is another bonus of using 4 ms input delay.

The imposed Bluetooth input delay can be configured in the profile. Even though I almost always use the default 4 ms setting, I have come across a couple of situations where it has been useful to have the option available in profiles.

**Comment by orator89** [comment]
Really thanks for your reply, explained perfectly ;)
So it should be 4ms in Bluetooth mode (i set pool rate: 250mhz 4ms), but I see delay 7/8ms even if I set 4ms input delay...
Confirming your opinion, if we use USB mode, the input delay standard is 4ms, so even in BT mode it should be 4ms, you're right, the strange thing is that i see 7/8ms and not 4ms input delay, even if I set 4ms.. :)
However battery life is good ;)
Thanks for reply

**Comment by HeviSevi** [comment]
Hello, I just found out that you've been updating this gem, but I ran into a similar problem as orator89. For me, the input delay keeps bouncing to 10-15 ms range if I set the pool rate to 333 Hz (3 ms) or higher. At 500 Hz (2 ms) it stays at 2-3 ms, but I haven't had the chance to test for much yet, but there wasn't any notable issues for the few minutes I played using that setting.

**Comment by Ryochan7** [comment]
Some BT adapters seem to be weird. For a problem like that, I am going to blame the hardware since it really should not work that way. With my two BT adapters, the 4 ms poll rate seems to be the sweet spot in regards to performance with ScpVBus. My BT adapters can handle the faster poll rates and using faster poll rates would be useful for mapping to KB+M events exclusively. Battery life would diminish by using a faster poll rate of course.

Also, the raw numbers are not that useful in the end. The 1.25 ms poll rate used in Jays2Kings version feels far more laggy than using 4 ms in the current build. Part of that seems to be a buffering problem with ScpVBus itself but the amount of un-managed calls being performed probably affects .NET performance; ViGEm does not have this problem so my system can handle the Max poll rate setting fine. Evaluating based on feel seems to be a more useful metric even if it is more relative.

**Comment by HeviSevi** [comment]
That makes sense. My BT adapter is a pretty cheap one so I wouldn't ask any miracles from it, but I fooled around with the settings more. Normally I hold my controller about 50 cm away from the adapter and on Jays2Kings version it was pretty much the max distance without any issues with the input delay. On your version, the 2 ms setting gives me quite a lot more range, almost 4 meters. 3 ms setting works fine if I hold the controller right next to the adapter and on 4 ms setting the input delay drops to 4-5 ms, but according to DS4Windows' log it bounces over 10ms every second.

I'm going to stick to the 2 ms setting since it works for me, but I just wanted to inform you on my findings. Even though they might just be hardware related.
