### ISSUE TITLE
DS4 Not Code Signed

### ISSUE THREAD

**Issue by zaclohrenz** [Ryochan7/DS4Windows#3074]
DS4 for Windows is not signed with a valid certificate, causing an inability to run on any system with Smart App Control enabled.

What is Smart App Control? 
https://support.microsoft.com/en-us/topic/what-is-smart-app-control-285ea03d-fa88-4d56-882e-6698afdb7003

Code signing: https://learn.microsoft.com/en-us/windows/apps/develop/smart-app-control/code-signing-for-smart-app-control

There's a cost associated with doing this, it might make more sense to distribute via Microsoft store and let Microsoft do the signing.

**Comment by Ryochan7** [comment]
Do you rob hobos on the streets of their quarters? This hobo has not had an income since late 2017; my LinkedIn profile is public if you want to see it.

One option would require a minimum of $100 per year commitment. It happened one year (2021) due to Corona bucks but I cannot remember which DS4Windows versions were actually signed; likely some releases in the 2.x line. It is the only sure fire way to get rid of VirusTotal false positives and FakerInput needed the certificate in order to exist.

The other requires a user to be part of a vetted organization (like with current kernel mode driver signing) so that would require at minimum establishing an officially registered LLC business for myself and then spend more money on top of that; might still need a third party certificate anyway. Then I am sure I would not be allowed into the Azure program regardless.

**Comment by svensvond** [comment]
Are you absolutly sure about that? Iam using a certificate (pfx format) and the comodoca (timestamp.comodoca.com) for years  to sign some VisualStudio projects int the Post-Build Events using Microsoft SDKs.
It does not cost a penny.

**Comment by Ryochan7** [comment]
So this just leads to gaslighting rather than helping. I went through Sectigo (previously Comodo CA) for a Code Signing certificate (one year) in May 2021. Maybe things worked differently before but a free option no longer seems to exist for obtaining new Code Signing certificates.

Just wanting to complain and not provide any help. Typical.
