### ISSUE TITLE
I have to pair my controller often

### ISSUE THREAD

**Issue by juliankid** [Ryochan7/DS4Windows#308]
Hi! 
I'm having a problem with my controller
_Sometimes_ when I connect my controller in the computer for charging, the controller disconnects from BT (with or without quick charge) and then when I try to connect it via BT again, the controller flash white 6 times and will not connect anymore until I un-pair and pair it again.
I'm running DS4Windows as a Task/Admin
My controller is a v2

**Comment by Ryochan7** [comment]
Are you running Windows 7? I have not tried the scenario under a real install but I had similar problems while running Windows 7 in a VM. If a controller were disconnected from Bluetooth for more than about 5 seconds then the controller would have to be re-paired in order to be usable again; quick disconnects followed by reconnects worked just fine though. It seems to be an inherit problem with the Microsoft BT stack. I will test this scenario under a real Windows 7 install and see if I experience the same problem as before.

I do not experience these kinds of problems on Windows 10.

**Comment by Ryochan7** [comment]
Just tested it out. I am not experiencing the same problem on a Windows 7 install running on real hardware.

**Comment by juliankid** [comment]
Thanks a lot for replying so fast.
I think I discover the problem.
The Witcher 3 Native DS4 Support turn off BT connection with DS4 when I connect the it via USB with the game opened (Again Quick Charge, disabled).
After that the game take control of the DS4 for a breif moment until DS4W take control again.
But now if unplug the controller and try to connect it via BT, the 6 white flashes happen and won't connect.

It's not a DS4Windows problem since I close it and tried with Steam DS4 Support and has the same problem. I have to try with other DS4 Native games.

The solution in this case would be, not to connect the game via usb when playing the Witcher.

OT Question: Does Big Picture XBOX 360 configuration annoys DS4Windows in some way? because I really like the on screen keyboard that Steam has.

**Comment by Ryusennin** [comment]
I strongly suggest to disable global Steam controller support, which conflicts not only with DS4W but also standard X360 pads.

There are a few exceptions like Prey, which has broken XInput support and specifically requires either a third-party fix mod or the XBox Configuration Support to be enabled in the game profile (Big Picture mode).

**Comment by juliankid** [comment]
I tried with another DS4 Native game (Rocket League) and the problems doesn't happen, seems like a weird Witcher 3 Bug

> I strongly suggest to disable global Steam controller support, which conflicts not only with DS4W but also standard X360 pads.

Yes but even with the Xbox Configuration Support unchecked, still hijacks the Guide buttom, exactly how it conflicts?

**Comment by Ryochan7** [comment]
Thank you for the update. The only game that I have that has native DS4 support is Rocket League. I don't think I have encountered this kind of problem the few times I have played the game using its DS4 support.

I would not try to use Steam's PS4 or Xbox 360 Controller support at the same time as DS4Windows. Using Xbox 360 Controller support might work at the same time but that would just add more lag to the process and the experience is too laggy for my liking when using a real Xbox 360 controller.

I have never tried virtual keyboard support using PS4 Controller support. Using dual analog can't be as good as using the two touchpad method used by the Steam Controller.

**Comment by juliankid** [comment]
Yes I notice a lot of input lag on Rocket League with Steam PS4 Controller Support, difficult to double jump, heavy car feeling, etc, doesn't happen on your fork, thanks a lot.
I have some questions:

1) What's the difference between VIGEm and standard build? Which one you recommend? Is VIGEm "the future"? (the Witcher 3 problem its on VIGEm build too, but I already finish the game so is okay hehe)

2) "Flash lightbar at High Latency XX ms" always displays on log as 10ms no matter what value you have. 
I have a lot of flashing on when I put it on 10 ms but no visible input lag, is that normal?

3) Can you provide me a Bitcoin Private, Bitcore, and Bitcoin Atom address? I have a little bit of money on those.

**Comment by Banderi** [comment]
I've been getting a similar issue as well.

If I turn off DS4W before plugging/unplugging, it will reconnect fine after I turn it on again; but if DS4W is enabled while I plug in my controller, unplugging it makes it stop working with BT.

Moreover, if I stop DS4W at any time while connected on BT, it will not work again until I re-pair it (have to manually removing the Wireless Controller device in the Windows devices first). In both cases, if I try to turn on the controller it will flash, briefly appear in the Windows devices, then disconnect.

**Comment by Ryochan7** [comment]
@juliankid I have lag problems with the Steam client controller mapper as well. That holds true while using the Steam Controller as well as using the DS4. For the Steam Controller, I use SC Controller as the driver and it is a much better experience. It is a shame since the Steam mapper is probably the most versatile controller mapper that is available.

As for your questions:

1. The ViGEm build will hopefully be the standard build in the future. Benjamin has not released a newer version based on some changes that I submitted. There are some custom changes that were made to the driver and the .NET assembly that is used to work with the driver. It would be better if I could stick to working with upstream ViGEm rather than against a custom fork. I also have not updated the test installer to use dedicated installer programs for each version. The current test installer uses the same routine and checks for the latest known version but I am not sure that routine would hold up with changes to future versions.

2. That string has not been changed due to changes actually causing dips in application performance. I have tried various string concatenation techniques and all of them have caused performance issues; the .NET Runtime is weird sometimes. Maybe I can try it again sometime and see if the program will actually cooperate so the output string can adjust for the current setting.

**Comment by Banderi** [comment]
Update: I have cleared all of my Bluetooth drivers and changed dongle, disabled SCP and every other thing I could think of that could interfere, I ran all sorts of combinations of tests plugging/unplugging/replugging/turning DS4W on/off etc. and so far it seems to be working correctly. Maybe it was a conflict somewhere on my end.
I will update if anything changes or the problem pops up again.

**Comment by Ryochan7** [comment]
Thank you for the update. It does seem like some configurations can add on some weird problems. One big example is how many problems occur by running the GeForce Experience application.

**Comment by Spyrox99** [comment]
@Ryochan7  I have the same problem as @Banderi described. Also I tried all the fixes i can think of, uninstalig drivers, changing dongles, changing slots, multiple pc restarts in a progres, scp reinstals etc. But I still need to pair my controller every time it disconnects. I have it in windows bluetooth settings as paired but after using DS4Windows 1 time it cant connect to it again and i need to pair it again to work.

**Comment by Banderi** [comment]
Have you just reinstalled SCP, or also tried to uninstall it completely? I have ended up switching entirely to DS4W and so during the process one of the thing I did was disable it - maybe they interfere with each other?

**Comment by Spyrox99** [comment]
@Banderi yeah, I uninstalled it completely, deleted everything connected to it and even ran ccleaner after, than I restarted pc. And I did it like 2 or 3 times. I did the same with bluetooth drivers and all drivers connected to gamepad, even USB ones. I was using raw scp before and it was working normaly, but since i did fresh windows instalation 3 days ago i came acros this problems with bluetooth conectivity with gamepad.

**Comment by teijiIshida** [comment]
Hello, I am playing The Witcher 3 (GOG GOTY 1.31). And I have EXACTLY 100% the same problem as OP in post #1 and #4.

I am on Windows 10 1809 x64 and running DS4W v1.6.14 as admin with Hide DS4 Controller check (and Quick Charge unchecked).

To reiterate the problems:

Scenario 1: If I start BT and then start Witcher 3, I can play fine and DS4W works great.
Scenario 2: If I plug in USB and then start Witcher 3, I can also play fine and DS4W works great.
Scenario 3: If I use scenario 1, but once battery is low and I plug in the USB cable while the game is running, during that few seconds, The Witcher 3 native PS4 detection takes over and I am now having double inputs (from Native PS4 support and DS4W emulation). Also, once Witcher 3 native PS4 detection kicks in, if I unplug the USB cable, BT no longer works like OP said, and I have to remove the device and BT re-pair the controller if I want to use BT again.

I don't see any error in the DS4W log that it couldn't do exclusive mode, so I assume that DS4W still has exclusive mode, but then why isn't it preventing Witcher 3 native PS4 controller detection? Is it possible for DS4W to MAINTAIN exclusive mode during the transition from BT to USB (when the cable is plugged in) so native PS4 detection can't take over?

The only workaround I'm doing now is to quit the Witcher 3 when BT is low battery, then plug in the USB cable, then start the game again. It's getting a bit annoying. Hoping for a fix, if possible. :(

**Comment by Ryochan7** [comment]
The only possible fix would be to install HidGuardian. Exclusive access issues can pop up depending on the game. The only game in my library that has native PS4 controller support is Rocket League and this use case works fine in that game. However, this problem occurs when running Broforce or FIFA 19 even though those games only have basic DirectInput support. The game ends up getting first access to the device even after the disable and re-enable routine is run. HidGuardian would be needed to block the game from ever having access to the controller.

**Comment by teijiIshida** [comment]
I tried HIDGuardian before but it doesn't seem to do anything. I'll try again (maybe I didn't install it correctly the first time).

Questions: do I leave "Hide DS4 controller" unchecked if I install HIDGuardian? And how will I know if I install HIDGuardian correctly? (There's not a proper .exe installer or anything. Everything is copy/paste according to your guide.)

**Comment by Ryochan7** [comment]
HidGuardian v.1 support is deprecated and its use is mostly discouraged by the developer Nefarius. Version 4 is in the works but it is not at a stable state yet. Some form of HidGuardian integration might be considered when version 4 goes stable. Also, I don't use HidGuardian on a regular basis because it does introduce some minor input latency; given the way filter drivers work, that might always be the case but my test build of it does perform slightly better than the stable release.

I had made a small test installer for HidGuardian in the past but it has not gotten any major use. It was more a testing ground for learning about WPF.

https://drive.google.com/open?id=1pHLtOeD_Qfo3nt9Pa3jYWo5cc5C3iuGk

The problems with software configurations conflicting is unavoidable and this is an edge case that Windows does not handle too well. The worst part is actually due to the behavior of the DS4 hardware though. In BT mode, opening DS4Windows will cause the original DirectInput controller to be seen as a dead controller when not used in exclusive mode; this also occurs with Steam's mapper. That behavior does not happen when using a USB or SonyWA connection. This behavior makes it impossible to create DInput only profiles for use with games that already include native DS4 support.
