### ISSUE TITLE
Dualsense Led random flashing when switching profiles with touchpad swipe

### ISSUE THREAD

**Issue by Trihy** [Ryochan7/DS4Windows#3132]
**Describe the bug**

Led random white flashing when switching profiles with touchpad swipe. Can be confusing for quick profile change.

It wasnt that way on older builds (problem was introduced on 3.1.5)

I think the led random flashing problem was introduced with this change:

"Set DualSense's Lightbar to white when stopping DS4Windows. Contribution by Kanuan"

Since build 3.1.5

https://github.com/Ryochan7/DS4Windows/discussions/2597

So now it flashes white between every profile change with touchpad swipe.

**To Reproduce**

Just switch profiles with touchpad swipe.

**Expected behavior**

Dont flash random white led. This only affects dualsense. Dualshock 4 is not affected by this issue.

**Desktop (please complete the following information):**
 - Controller Make and Model: Dualsense
 - OS: Windows 11
 - DS4Windows Version [3.2.17]

**Comment by Ryochan7** [comment]
That is likely not the reason the lightbar flashes a different color when switching profiles. Only found this problem out recently by accident. The problem is due to the input thread still running while the old profile data is reset and before the new profile data is read in. The issue seems to affect BT connections more probably due to the extra output writes done in the device class. The issue likely surfaced with DS4Windows 3.2 with the move to using XmlSerializer for profile reading.

Not sure why the light would be White in your case as that is assigned as the default color for slot 8. Most people would likely see Blue flash for a brief second as Blue is the default color for slot 1. Do you have 7 other controllers connected?

https://github.com/Ryochan7/DS4Windows/commit/7f11dabec637d12efb5640f2d06758072c6b709a

**Comment by Trihy** [comment]
Oh I see I let a comment on that build a year ago about this :D

https://github.com/Ryochan7/DS4Windows/discussions/2597#discussioncomment-3963728

**Comment by Trihy** [comment]
Im using version 3.3.0 and looks like this issue is fixed.

Kudos :D

**Comment by Trihy** [comment]
Now only does that white flash when turning off with button combo. Not sure if this is expected.

**Comment by Trihy** [comment]
Version 3.3.2 also fixed the shutdown flash. Lets close this. Thanks.
