### ISSUE TITLE
DS4Windows not detecting hidden controller from HidHide if pointing to DS4Windows from a directory junction

### ISSUE THREAD

**Issue by sitiom** [Ryochan7/DS4Windows#3145]
**Describe the bug**
DS4Windows doesn't detect the controller if I add the application from the directory junction, meanwhile it works if I add it from the real directory

**To Reproduce**
- Install [`ds4windows`](https://scoop.sh/#/apps?q=ds4windows&s=0&d=1&o=true) from Scoop.
- Add the DS4Windows executable to the application whitelist from the directory junction (`current`)
- Hide the controller
- Open DS4Windows

**Actual result:** The controller is not detected in DS4Windows
**Expected result:** It is supposed to access the hidden controller.

### Screenshots
Real directory:
![image](https://user-images.githubusercontent.com/56180050/179337371-843cd70c-ada9-431f-9a24-360253cfae05.png)
Junction:
![image](https://user-images.githubusercontent.com/56180050/179337375-8f5e2d4b-bbcb-49c6-8950-8c2178286cf6.png)

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2U)
 - OS: Windows 11 23H2
 - DS4Windows Version: 3.2.18

**Additional context**
Opening from https://github.com/nefarius/HidHide/issues/79 as I am advised that this is an upstream issue from DS4Windows and not from HidHide.

**Comment by Ryochan7** [comment]
Never used scoop so it took a bit to figure out what you were talking about. I am going to assume the problem is because of using a symbolic linked directory rather than the real install directory. HidHide requires real paths in the application whitelist. Running DS4Windows from the junction directory (`current`) would add the incorrect path to the application whitelist.

I will look into how to resolve the symbolic link target into its real path. Also, I forgot how slow the circumspector fork was.

**Comment by Ryochan7** [comment]
Somewhat confirmed hypothesis. Running the app from the real install directory once to add the whitelist entry is enough to get the junction symbolic link to work afterwards.

**Comment by Ryochan7** [comment]
Good enough

https://github.com/Ryochan7/DS4Windows/commit/26ad3cd509feddd6c3384e6f190dc512e4f6cd00

**Comment by Omarock92** [comment]
I'm facing the same problem after 3.2.18 and HID Hide v1.4.181.0

**Comment by Ryochan7** [comment]
Was going to put out an update today to fix this but I unfortunately have a rather stupid matter to deal with. Being compelled to litter the source code with license notices after finding out I was getting screwed again. The DS4Windows source code will be licensed under the GPL version 3 going forward (used MIT license before). Maybe I will get around to publishing a new release tomorrow.

Also, as a side note, Nefarius tried to imply this issue was at least partially due to me not using his HidHide library. I reviewed his code and using his library would have made no difference when it came to this issue. I have many reason not to use his library. If his library did what I wanted then I would bundle it with DS4Windows. This is a very specific edge case.
