### ISSUE TITLE
[Feature request] Add option to loop same macro infinitely / until condition

### ISSUE THREAD

**Issue by Mugurell** [Ryochan7/DS4Windows#3165]
The option to "Repeat while held" exists but this spams the same macro at the same time.

What I propose is something similar to the "Loop" functionality from `PlaystationMacro` - the possibility to replay the same macro when the current one ends, loop it again and again, and again.

A special action 
"Loop while held"
or another way for a controller button to end this loop would be nice.

**Comment by Ryochan7** [comment]
Personally I do not use the macro system. It is an old hold over that has caused the most trouble for this app that I have barely tweaked to keep it working. The whole system could use a rewrite but I have no reason to do it. I have considered just removing macro functionality outright. Such a request is not going to happen before DS4Windows will be sunset by me (end of current year).

Also, that app literally existed for cheating and it does not work anymore since Sony broke ViGEmBus compatibility in Remote Play. But DS4Windows is the major cheating app that deserves hate because of me personally.
