### ISSUE TITLE
Whole profile wiped

### ISSUE THREAD

**Issue by shiny-ribbon** [Ryochan7/DS4Windows#3178]
Figured I'd share this since I ran into a big bug.
I made a Load Profile Special Action and it was for loading the exact same profile I was already on. When I pressed the button (Left on d-pad) it wiped the entire profile. I don't know if it's reproducible or if I just did something weird but it is what happened to me

**Comment by Ryochan7** [comment]
I cannot reproduce the problem on my end. Are you sure the profile is being wiped or is the controller seen as being dead? If it is the later, I am wanting to think that whatever app you are using to test this case is seeing the real Bluetooth controller rather than the virtual controller.

With the DS4 and DualSense on Windows, when connected via Bluetooth, the original DirectInput handle for the controller will still be visible to other apps if some form of exclusive mode is not used. That handle will be seen as a dead controller though. There is a good chance an app will see the dead controller first and open it.

**Comment by Ryochan7** [comment]
Could be a number of potential issues but I would assume it is likely the shared mode problem. It cannot be narrowed down without the profile and Actions.xml file in question.
