### ISSUE TITLE
D-pad is inconsistent and erratic when emulating the analog sticks

### ISSUE THREAD

**Issue by felixlang** [Ryochan7/DS4Windows#318]
The easiest way to see this problem is to set up a DS4Windows profile with a default XBox 360 layout, but with the D-pad assigned to emulate the left analog stick (D-pad up = Left Y-Axis- / D-pad right = Left X-Axis+ / etc).

Then download and run the freeware version of Spelunky (http://www.spelunkyworld.com/original.html), and skip the opening texts to get to the menu, where you can control your character. From here, if you use the left analog stick to move left and right, it works as it should. But if you hold down left or right on the D-pad, then the character will stop and start repeatedly, and sometimes he won't move at all.

This behavior can also be seen in the game controller properties in Windows, or whatever equivalent utility is available for other OSes - holding down a direction on the D-pad shows the X-axis / Y-axis target "pulsing" back and forth between a neutral centered position and the edges.

I hadn't used DS4Windows for a while until now, but this wasn't a problem I encountered the last time I remember using this layout (would have been around 1 to 2 years ago).

I am using the latest revision of the Dual Shock 4 - V2 (CUH-ZCT2U) - from September 2016. My OS is Windows 7 Pro SP1 64-bit, and my DS4Windows version is Ryochan7 1.4.120.

**Comment by Ryochan7** [comment]
I just tried this mapping and it is stable for me. Have you checked the base Wireless Controller device to see if the D-Pad is having problems? Can you post the profile that you are using?

On second though, have you implemented a dead zone for LS? That might explain the behavior. The D-Pad mapping and left stick mapping would conflict and I believe that the left stick mapping would have higher priority in the mapping system. DS4Windows used to have an implied dead zone if the profile used a setting of 0.00 for the left analog stick. That has not been the case for a while in this fork.

**Comment by felixlang** [comment]
You are correct. My stick deadzones were all set to 0 - can't imagine why or when I did that. Setting it to 0.10 seems to solve it.

Can I ask what the default analog settings are for a fresh install of this DS4Windows fork? Here are what my settings are at now:

Deadzone LS/RS - 0.10
Deadzone L2/R2 - 0.00
Deadzone Sixaxis X/Z - 0.25

Anti-Deadzone - All settings at 0.00
Max Zone - All settings at 1.00

**Comment by Ryochan7** [comment]
DS4Windows still uses the old 0.00 default for analog sticks. Before, there used to be an implicit dead zone if the setting was at 0.00; I will have to look at some old revisions and find out what that old implicit dead zone was. I have thought about it but I do not know if I would want to add an implicit stick dead zone back into DS4Windows. Also, the old dead zone calculation wasn't accurate in the Jays2Kings build so the output for the same stick position will be different now.

Also, the default dead zone for the sixaxis directions is different now. I cannot remember what it is but I think it is something like 0.03. The old dead zone calculation was not accurate because it was not based on the entire input range of the accelerometer. The default was changed after testing and playing Dirt Showdown using the DS4 as a racing wheel.
