### ISSUE TITLE
Trackpad during UAC prompt?

### ISSUE THREAD

**Issue by shad00m** [Ryochan7/DS4Windows#320]
Will it ever be possible to use the trackpad or any controller key during a UAC prompt? (Windows 10 1803)
Getting up and walking to my computer everytime to hit "left+enter" burns too many calories

**Comment by Ryusennin** [comment]
But it's good for your health.

**Comment by Ryochan7** [comment]
Unfortunately, that is a Windows security feature. Windows will not use events generated by SendInput while a UAC prompt is active. There are some ways around the problem that I know of to work around the problem but none are implemented. The most practical workaround would be to replace SendInput with vmulti. That would be yet another custom driver that would have to be installed on a system in order to use DS4Windows. The other real solution would be to pay Microsoft around $200 to get DS4Windows officially signed so that the ui access flag can be enabled and enforced by the system.

One big problem with the officially signed executable option is that there would still be problems with games that utilize anti-cheat software. The vmulti driver option would not present the same problem as the game would only see a keyboard and mouse being present.

**Comment by shad00m** [comment]
UAC+Logon movement works in JoyXoff (http://joyxoff.com/en/). And it seems to use SendInput() but it uses a service with localSystem privileges. (Sorry for the double post in the other issue, I'll continue in this one only)

**Comment by Ryochan7** [comment]
Never heard of that software or the localSystem account before. I checked it out and the localSystem technique works. What is more surprising is that the virtual keyboard works in exclusive fullscreen mode even when not using the localSystem account option. Something like that would make virtual keyboard support actually useful. It is too bad that the actual virtual mouse in JoyXoff is choppy and hard to control.

I don't see that option being useful for DS4Windows as it is. The little bit of reading that I have done seems to indicate that the localSystem account is only accessible to running services. DS4Windows would have to be split into a background mapping service and a frontend assignment application. Also, the anti-cheat problem would likely still exist so something like JoyXoff would not be useful for some applications. I cannot remember the main examples that I used in the past except for some Magicka spinoff game; it looks like Magicka: Wizard Wars was the old test game for testing if events would be block by anti-cheat software.

**Comment by shad00m** [comment]
I'm not very familiar with anti-cheat. But don't most anti-cheat programs look for dll injects?
I wanted to try Wizard Wars but it has shutdown in 2016. If you remember the game you used for testing I'll try it with joyxoff.
It does sounds like a lot of work to implement a background mapping service for DS4Windows and I don't know how many people are annoyed by the UAC prompts - I definitely am :-)

At least theres 1 more way how to achieve it now.

**Comment by Ryochan7** [comment]
As an aside, I have been testing out how Touchmote implements its overlay window for profile switching. Touchmote is open source and I have edited the program in the past. The vanilla implementation has problems with switching to desktop view when the overlay window appears so it is not very useful when playing many games. After some tweaking, I got the overlay window to work over exclusive fullscreen games just as well as JoyXoff.

I am not sure what it would require to get something made using Windows Forms or if it possible since Touchmote uses WPF for its interface. The primary use would be for implementing a keyboard overlay but having an overlay menu with some options could be very useful.

**Comment by Ryochan7** [comment]
It is possible to use the same technique for Windows Forms based applications. There are some quirks with the way the TopMost technique is utilized in all the programs that require some bad hacks to truly work around. Without a workaround, there are times after alt tabbing between windows that will cause the overlay window to be displayed and then go out of view due to displaying below the application window onto the desktop view.

**Comment by alpharou** [comment]
Sorry for bumping this issue, but it has been two full years, and maybe Ryochan knows now about some workaround for controlling uac protected prompts. It's one of the few barriers DS4Windows has to become a couch pc game must-have.

**Comment by zozo2247800** [comment]
ايوه تمام
