### ISSUE TITLE
no mic

### ISSUE THREAD

**Issue by mx62** [Ryochan7/DS4Windows#322]
hi ive got a issue when a plug my ds4 the mic works fine
when i start ds4 windows no sound 
any ideas?
thx

**Comment by Ryochan7** [comment]
Works for me&#8482;. Sorry. You might want to adjust the microphone volume level and see if that causes DS4Windows to refresh the audio level for the device. Unfortunately, DS4Windows has to keep track of the audio volume levels of the headphone and microphone devices because those volume levels have to be included in output packets. DS4Windows should grab the currently set audio level in Windows when it detects a device though.
