### ISSUE TITLE
Uplay and DS4Windows freeze.

### ISSUE THREAD

**Issue by Spairus** [Ryochan7/DS4Windows#324]
If DS4Windows has "Hide DS4Controller" enabled and the controller is plugged in, launching Uplay causes a system-wide freeze (even audio stops and mouse doesn't move). Disconnecting the controller immediately alleviates the freeze. It looks as if exclusive mode has something to do with it. (Uplay tries to gain control continuously?)

Games in UPlay are unplayable if one doesn't enable the "hide" option as they constantly switch between controllers many times per second causing a stream of micro-stuttering.

Is there any known workaround for this?

Thank you!

EDIT: In order to not be flagged as dupe, I have read the other references to this in the open Issues, but I did not seem to find a valid workaround for Windows 7. Also, users did not report that the freeze stops the instant the controller disconnects.

**Comment by Ryochan7** [comment]
I have not experienced that problem when using uPlay. On my system, DS4Windows will just fail to get exclusive access to the controller as long as uPlay is running. The only way to get exclusive access to the DS4 while uPlay is running is to use HidGuardian. DS4Windows has to be run in administrator mode in order to interface with HidGuardian due to having to edit registry keys that HidGuardian uses. DS4Windows will still attempt to use the old exclusive mode workaround if the program is run as a normal user.

Official website: https://vigem.org/
Test installer: http://ryochan7.xyz/ds4windows/test/DriverInstaller_Test_20180402.zip

**Comment by Spairus** [comment]
That fixes everything. Thank you very much!
