### ISSUE TITLE
Keep up the good work! and a question.

### ISSUE THREAD

**Issue by plsg08** [Ryochan7/DS4Windows#325]
DS4Windows has been my go to tool for my DS4 and the only thing I'd like to know is if there's a way to auto-restart DS4windows after turning it off temporarily from the auto profiles? 

I set DS4windows to Temporarily turn off when For Honor and Witcher 3  is open, but once those games close DS4windows is just stopped and doesn't restart by itself. 

It's a minor thing but a good QOL addition as well. maybe I missed something from the setup. 

anywho cheers and keep up the good work!

**Comment by Ryochan7** [comment]
I don't use the auto profile system so that portion of the program is not tested much. I guess there is no check if the DS4Windows device handling service is not running when switching auto profiles. DS4Windows should restart the service when switching to an auto profile that does not have the stop service option enabled.

**Comment by Ryochan7** [comment]
This is now a confirmed regression. DS4Windows 1.4.52 could perform that functionality.
