### ISSUE TITLE
Why is DInput not supported via Bluetooth?

### ISSUE THREAD

**Issue by Hexoka** [Ryochan7/DS4Windows#329]
Why is DInput not supported via Bluetooth?
I really would love to have that option for games that support DInput (Rocket League)

**Comment by Ryochan7** [comment]
I blame the Microsoft BT stack. The DInput controller pretty much becomes unusable after sending the first output packet in DS4Windows. An initial output packet is sent to switch input report modes. Without the change, additional data from the controller such as the touchpad data and gyro data would not be accessible. A DS4 connected via USB or the Sony Wireless Adapter does not experience the DInput problem so DS4Windows can be stopped temporarily to play games that support the DS4 natively. With a BT controller, you would have to disconnect the controller and sync it back up, without DS4Windows running, in order to have access to the DInput controller.
