### ISSUE TITLE
Question about latency

### ISSUE THREAD

**Issue by Ritaku01** [Ryochan7/DS4Windows#335]
I was wondering, how much latency does DS4Windows itself add?

**Comment by Ryochan7** [comment]
I have always judged input latency based on feel. My two main test games lately have been Gex and .hack//G.U. Last Recode. There are certain parts of the process that probably cannot be measured such as the time between transferring the Xbox controller state and when the updated state is read by the ScpVBus driver. The only portion that I would be able to reasonably measure would be the amount of time the mapping system adds to latency and even that is variable due to other components running in the application and the amount of features enabled in a profile.

DS4Windows works well enough for me and it seems to work better than most of the alternative programs out there. Also, some of the tweaks in DS4Windows actually improves the input performance over using the DInput controller; in Rocket League, using the emulated Xbox 360 controller is more snappy than using the native DS4 support in the game.

**Comment by Ritaku01** [comment]
Really? That's honestly surprising, I wouldn't think that a wrapper could reduce latency like that. Is this test over bluetooth, where DInput isn't a part of the equation, or with a USB cable, where I assume DInput is being mapped to XInput?

**Comment by Ryochan7** [comment]
When I tested it before I think it was only tested with a Bluetooth connection. I just tested Rocket League with BT and USB using both DInput and virtual Xbox 360 and there is some additional delay when using the DInput controller. Changing the input mode in DS4Windows is probably the biggest factor that affects the behavior of the emulated controller. The way data buffering is used might affect it as well.

**Comment by Ritaku01** [comment]
When you say "input mode in DS4Windows", are you talking about something hard-coded into the program, or an option? Only option I can think of that comes close to an "input mode" is "Hide DS4 Controller", though that really just prevents dual inputs in games that support both XInput and native DS4.

**Comment by Ryochan7** [comment]
The input mode I am referring to is the type of input report that is sent from the controller. One of the first tasks that DS4Windows performs after opening a device is to set the controller to use a different input report type than the default that is used for the DInput device. The reason for that is the initial input report type does not include extra data that is utilized by DS4Windows such as the touchpad data and the gyro data.

Initial report: http://eleccelerator.com/wiki/index.php?title=DualShock_4#0x01
Used input report: http://eleccelerator.com/wiki/index.php?title=DualShock_4#0x11

Besides changing the input report type, the output packet that is sent to the controller also allows for a different poll rate to be specified for a BT connected controller; USB and Sony Wireless Adapter connections have fixed poll rates (4 ms and 8 ms respectively).

Use DInput Only mode has a limited use case due to Bluetooth issues and exclusive mode. That mode only unplugs the virtual XInput controller associated with a DS4. For BT connections, the old DInput controller becomes mostly useless after DS4Windows changes the input report type for a controller although USB and Sony Wireless Adapter connections don't have that problem. Also, exclusive mode would make it so that the DInput controller would not be accessible anyway.

I mainly use "Use DInput Only" mode for playing games using KB+M emulation that would have certain issues if an XInput controller is connected at the same time. One that comes to mind now is Warhammer 40K: Space Marine. If I remember correctly, the mouse sensitivity is massively reduced when the game detects an XInput controller. Using stick camera controls is pretty bad in that game compared to using emulated mouse.

**Comment by Ritaku01** [comment]
Ok, I think I get it. If I get anything wrong, feel free to correct me, because some of this is new to me. User "plugs in" the DS4, whether through USB or Bluetooth, and the DS4 sends report 0x01, which contains information about the standard inputs. DS4Windows opens the controller, and switches the DS4's mode to send report 0x11, which has the info on gyros, touchpad, etc. From there, DS4Windows uses ScpVBus to "plug in" a 360 controller and wrap its inputs to those of the DS4's. 
If the DS4 was plugged in through USB, it's also interfacing with DInput, but that can be hidden, and DInput isn't even available through Bluetooth, but either way, I assume that in the 360-to-DS4 translation, DInput isn't even a part of the equation either way (this explains the double-input in games that support both DS4 and 360 inputs natively when you don't hide the DInput controller).
