### ISSUE TITLE
Use Gyro as Mouse Deadzones

### ISSUE THREAD

**Issue by BoDDEneR** [Ryochan7/DS4Windows#338]
Hello.

First i must say thank for all work you do, I never has imagine that DS4 may be so fun to use!
I start playing games with DS4 and gyro, and it is very fun. When you set trigger to activate gyro to, like, L2 everything working very well. But recently i start to play Doom and i have a little issues with that. I was try searching any post with that issue, but i find none, so:

Doom gameplay is 90% shooter , so you need to have gyro enable at all times. When you do that, gyro will catch any tiny movement you do, even your hand trembling. Add this to a high sensitivity (because in Doom you need watch your back and look up/down quickly) and you will have a headache. A simple dead-zones will work fine, but i not manage get them to work when gyro used as mouse. 
I can't say for sure, but when you use gyro as controls, deadzones working fine. But you can't aim in this state.

Does this is a software issue or i was doing something wrong?

**Comment by Ryochan7** [comment]
There is a small fixed dead zone for gyro mouse movement. It is relatively small so it might be possible to feel some jitter on the low end. Upping the in-game mouse sensitivity can amplify that movement. The current dead zone has been good enough for me for the games that I have played using gyro mouse. The lack of a custom dead zone setting has been due to lack of need and so the program can save some time in the mapping process. Besides allow a larger gyro dead zone, adding some extra resistance on the extreme low end might help.

**Comment by Ryochan7** [comment]
The gyro mouse deadzone is now configurable in version 1.6.9. The default is set to 10 which is what I normally use. The inclusion of this feature was possible due to changes in version 1.6.8 that allowed some more wiggle room for the mapping routine.
