### ISSUE TITLE
Driver window opens every startup but driver works fine

### ISSUE THREAD

**Issue by einsteinx2** [Ryochan7/DS4Windows#340]
I was previously using the older Jays2Kings release. Last night I upgraded to your latest release version 1.4.121. It prompted me to install the driver, which I did, and the controllers function perfectly. However, now every time on reboot, I get the window that asks me to install the driver. However the controllers work fine without reinstalling. Whatever detection method it's using is apparently not working. I'm using Windows 10 with whatever the latest update is at the moment.

I did not have this issue with the older build I was using, but I want to use yours as it's the active one.

**Comment by einsteinx2** [comment]
Sorry, totally my fault. My suspicion was correct, I needed to run the old version and choose Uninstall VBus driver. After that I switched back to your release and no more issues. I guess they were installed side by side causing the confusion.

**Comment by Ryochan7** [comment]
Both builds should use the same driver and not have problems. Did you try ScpToolkit at one point? I believe that software could present some problems if used alongside DS4Windows.

One other problem is that the older Jays2Kings builds of DS4Windows sometimes do not detect changes to Scp Virtual Bus Driver immediately so it is possible for the driver to get installed twice. The current builds of DS4Windows do not have this problem due to using the SetupAPI functions for detecting the driver rather than using WMI like the old builds did. WMI has caching problems so the current installation of a driver might not match what information is given from WMI.
