### ISSUE TITLE
[Feature Request] Actual Drivers

### ISSUE THREAD

**Issue by tamodolo** [Ryochan7/DS4Windows#350]
It's only an idea but shouldn't be more convenient to actually make a real inf driver for these controlers instead of hooking the DX one as it is today?

Correct me if I'm wrong but Linux have one that is packed with the system that work this way and is pretty much plug and play.

Making the DS4Win of today as a extension to control this driver would be an interesting way to do things as it could leave the DS4 as is, make it a DX controler or a Xinput controler.

I know it's a real lot of work but It's just an idea to solve a real lot of problems (like exclusive mode, maybe audio over bluetooth, the need of admin privileges to connect every single time, it would be possible to simple give the controler to games that actualy can use the native DS4's like Witcher 3 and Tomb Raider...)

Edit: forgot to mention. This is a way to force the controler to operate at PS4 mode on PC (like just plug the usb and bluetooth remember it by doing that. Don't know if this is possible. It is know this work with official adapter)

**Comment by Ryochan7** [comment]
Using a driver based approach would pretty much get rid of exclusive mode problems. One major downside is that using a driver based solution could interfere with every other controller mapping software that supports the DS4. Another really big downside is that, thanks to Microsoft, there would be a financial cost (~$200) to having to get the driver signed so it can actually be distributed without causing headaches for the end user. That major downside is why I have not just bundled a modified version of ViGEmBus and had DS4Windows use that instead of sticking with ScpVBus.

This reminds me that I have not tried out FireShock yet. I had tried out ScpToolkit in the past but it didn't work that well for me. The driver did recognize my DS4 v.1 controller and mapping worked but ScpToolkit was actually the worst solution in regards to input latency despite being a driver based solution. Hopefully FireShock is better in that regard.

https://github.com/ViGEm/FireShock

**Comment by tamodolo** [comment]
One way to workaround the first downside (the one that interfere with others softwares) is making the driver solution as a compatibility layer that will make the DS4 be what the user needs to be. I see 3 major needs for the DS4: the actual DX controler (this is it's default), the Xinput controler (this is what 99% try to do) and the PS4 mode (that some games on PC can do but it's easier to simply run as Xinput anyway). In the end I believe that the possibility of choice is aways better for everyone.

The second one is unfortunately unavoidable... (there are ways to artificialy sign the driver but it's too shady.... maybe it's better to leave that alone).

About fireshock, ViGEmBus is an amazing tool but a hell to common user to use as stand alone. So a second tool is nedeed. DS4Windows is that tool as you said it's using it. The idea of trying fireshock as a true driver solution and using DS4Win to control it is great! Maybe adding it as a side solution for the user to choose what they want is even better! I don't know the limits of fireshock btw...

If that is the way you choose to folow you can even do some statistics of users' adoption. It's all ideas to solve some problems.

For now I'd like to leave my thanks for this great software!

**Comment by Ryochan7** [comment]
I tried out the latest stable FireShock release. It does not seem like DS4 support is recommended since the hardware IDs for DS4 controllers are commented out in the INF file. I ended up changing the INF to add support back in but it did not work. Besides that, just having the driver active while using the vanilla version caused some lag for a DS4 v.1 connected via USB. The lag went away once I removed the FireShock driver from my system.

ViGEmBus is a good alternative to ScpVBus for creating virtual controllers but the current stable release does not have some optimizations that I contributed to the project. The stable release introduces some extra lag compared to ScpVBus so the ViGEm build of DS4Windows is mainly for people who have run into issues with ScpVBus. Building from the current code base with those optimizations included works great and I am using it on my system now instead of ScpVBus. Once a new version of ViGEmBus is released, I would like to finally have DS4Windows use ViGEmBus by default and ditch ScpVBus.

**Comment by Keltere** [comment]
Will ViGEmBus get rid of exclusive mode?

Thanks for your hard work Ryochan.

**Comment by tamodolo** [comment]
Not realy no... ViGEmBus is an alternative for ScpVBus. They work using the windows driver for the controler to emulate another. It's not a real driver but an emulation of one. If another software request exclusive mode before DS4Win that is using ViGEm, DS4Win will not be able to secure exclusive mode.

I was testing the ViGEm build and it is indeed better. The installation of ViGEm is manual by the way, so it's not easy to make it work properly.

Another thing that crossed my mind is that steam seems to override windows drivers and can actualy control it properly. The downside of that is that they don't offer an Xinput only option and this can be messy for a lot of games because it's recognized as a wrapper for keyboard even if Xinput is available for the game. Rumble functions are ignored for most games even when the support is there.

How about this aproach? It seems to be able to avoid exclusive mode and can do most of what DS4Win do (but not with the same focus...)

**Comment by Ryochan7** [comment]
ViGEmBus does not deal with the real HID device so that would not affect exclusive mode at all.

I don't see myself ever implementing a driver for DS4 controller support. Maybe I would play around with the FireShock source code out of curiosity but it would not be anything substantial. This is an interesting idea for discussion and it would be interesting if someone would try to implement this kind of solution for some sort of controller even if it is not for a DS4.

It seems like Steam reads from the HID device like DS4Windows does. One big difference is that Steam seems to perform DLL injection for presenting a game with XInput controllers similar to the approach used for x360ce.

As for XInput only, I have not encountered an issue with Steam when using XInput bindings exclusively. The problem is when a controller profile attempts to use both XInput bindings and KB+M bindings together (XInput + mouse camera). Some games just don't work well when using mixed controls and I just end up using KB+M bindings in that case because I want to use emulated mouse instead of right analog stick emulation. That is usually due to how the game handles input in general and similar problems would be experienced with DS4Windows and other controller mappers. Luckily, Steam will not present a game with an XInput controller if no XInput bindings are used in a profile.

**Comment by vpontin** [comment]
I always thought Let's Encrypt offered driver signatures too. Too sad its not the case.
