### ISSUE TITLE
Recommendation on Asus BT400 

### ISSUE THREAD

**Issue by desu01** [Ryochan7/DS4Windows#367]
Hey
So right now I'm rocking asus bt400 dongle along with dualshock 4, and with the normal version of ds4windows it seemed to be very laggish even on a close range (latency more than 10 very often). I checked your version and looks like it's been improved by a lot - completely new to your version @Ryochan7 . I've set up pool rate to 1ms, is this how it's supposed to be set? As I've checked the latency under controller readings and it varies from 1,25ms to 4ms which is a great score tbh but still there's the problem of range - as long as I'm close it's all good, but once I move 1m away it kinda is acting crazy. Any advices on how to improve it even by a small amount?

Regards!

**Comment by PapaPlastic** [comment]
ASUS BT400 user too, Windows 7 64.
Previously used the dead branch, which had issues but never latency issues. Repositioned BT dongle from the back to the front, high performance power plan, still get high latency pulsing spikes.

**Comment by Ryochan7** [comment]
PapaPlastic gave some good recommendations. Another recommendation that can possibly help is to buy a USB extension dock and connect your Bluetooth dongle to it instead of directly to a USB port on your computer. Other than that, I don't know what to tell you. My current Bluetooth adapter (Rosewill RNX-BT401) uses a CSR chipset and it has served me pretty well. My old Rocketfish BT 2.1+ adapter used a Broadcom chipset like the Asus BT400 supposedly does but the only problem I remember encountering was unstable latency readings when connecting multiple controllers. Some problems are down to the BT adapter itself.

As for the BT Poll Rate setting, I prefer using 4 ms because testing has shown that ScpVBus actually exhibits less latency when using the 4 ms setting as opposed to using the maximum possible rate that the DS4 can handle. ViGEmBus does not have that problem.

**Comment by Aldaviva** [comment]
I had the same issue with my Asus BT400, but only when I tilted the DS4 towards me. I resolved it the same way @PapaPlastic did. Previously I had the adapter connected to a USB port on my motherboard, about 3 feet away, so I moved it to a USB port on my monitor, about 1.5 feet away, and now I never get the 10ms latency spike red indicator light.

**Comment by PapaPlastic** [comment]
Switched over to UdpServer ViGEm build. 
Using 2 controllers over 5ft away no longer triggers waves of high latency spikes.

This is a fresh windows install, so I don't know if its the ViGEm build or the fresh start that fixed it.

**Comment by Ryochan7** [comment]
I'm going with the fresh install being the primary factor. I would not think that switching to ViGEm would make that much of a difference in that regard.
