### ISSUE TITLE
Switching screens

### ISSUE THREAD

**Issue by GuyWOaTat** [Ryochan7/DS4Windows#369]
Thanks for all you do on this. 

One issue I have noticed is that it won't stay on the screen I put it on.  Using multiple monitors I will game on my main monitor.  I like to have DS4W on one of the other monitors so I can see the charge level of the controller at a glance. But every time I start DS4W it appears on my main monitor and has to be moved to a secondary monitor.

It remembers the location on the screen, but not which screen I had it on.

**Comment by GuyWOaTat** [comment]
Also, while most popup screens appear on whatever monitor the main window is on, if you are editing a profile, choose special actions, and record a macro, that macro record screen appears on the default monitor. Note that this is not true for the macro record screen associated with a button; that popup appears on the same monitor as the main screen as it should.

**Comment by Ryochan7** [comment]
The button macro mode just uses the macro record form as a panel and places the form over the original window form controls. Going to the record macro form from special actions actually causes a new dialog window to appear. Because there is no owner set for the form and the StartPosition property is set to WindowsDefaultLocation, I am betting that Windows will just choose to use the primary monitor.

I don't have a way to test this because I only run a single monitor configuration.

**Comment by Ryochan7** [comment]
Finally got around to trying to correct this and attempts just ended up slowing the app down. So much for that.
