### ISSUE TITLE
Question about the ViGEm build

### ISSUE THREAD

**Issue by RedKage** [Ryochan7/DS4Windows#379]
Hello,

Sorry to bother, this not an 'issue' but rather a question.

Couldn't find anywhere else to ask this simple question:
What is the ViGEm build for?

I read a lot of issues here to try and understand, but I'm unsure I get it.
I may also get confused with ViGEm and HIDGuardian.

What I understand:
- DS4Windows standard build works just fine with the built in DS4 drivers config tool
- HIDGuardian, which although is from the ViGEM repo, is unrelated to the DS4Windows ViGEM build
- HIDGuardian's sole purpose is to hide some virtual controllers. This enables exclusive access (since other programs do not see the gamepads) and this fixes issues for some games which were seeing multiple gamepads when there was only one
- Running HIDGuardian does not require the DS4Windows ViGEM build
- Running HIDGuardian requires the WDK

That's all I got so far.
Are my assumptions correct?

Which leaves me with ... What's the use of the DS4Windows ViGEM build?

Thanks guys!

**Comment by RedKage** [comment]
After reading a bit more the issues, it looks like the above assumptions are right.

DS4Windows standard build is using Scarlet's SCP drivers
DS4Windows ViGEM build is using ViGEM Bus Driver to create the virtual pads

Which probably means I gotta install ViGEmBus_signed_Win7-10_x86_x64 from the ViGEM repo in order to make DS4Windows ViGEM build run.

**Comment by fagoatse** [comment]
Yeah, ViGEm is supposed to replace scp in the upcoming release.

**Comment by Ryochan7** [comment]
There are some reasons why moving to ViGEm would be a good idea in the future.

1. ScpVBus has not been maintained in years; the current driver is dated 05/05/2013. ViGEm is in active development.

2. ScpVBus cannot handle using the maximum possible data rate that the DS4 can provide. That is why a BT Poll Rate of 4 ms is the program default as latency is actually lower when using the higher poll rate compared to using the maximum possible data rate. ViGEmBus does not have that problem so it would be feasible to give it data as fast as the controller can give it.

3. ViGEmBus can emulate a DS4 controller. Remapping a DS4 would be possible and it could be useful for PS4 Remote Play. Also, based on my tests with Rocket League, bypassing the native DirectInput controller and emulating a virtual DS4 controller can lead to improved performance. I made a small demo showing DS4 controller emulation performance when using ViGEmBus.

https://www.youtube.com/watch?v=eFNXaXOiJxQ

4. ScpVBus has other issues such as keeping controller slots open despite attempts to close slots. It is mainly an issue with synchronization in the driver and Windows (7) hotplug issues that have been worked around.

Unfortunately, the current stable release of ViGEm actually performs slightly slower than ScpVBus does when using a 4 ms BT Poll Rate. The current ViGEm code does a better job and is the clear winner in regards to latency. Once Benjamin releases a new signed driver then I plan to have DS4Windows use ViGEmBus by default.

The current ViGEm builds are for people who want to use the ViGEm driver now. Outside of development, I use the ViGEm build with a recent version of the driver built from source. I have my computer in Test Mode so that using an unsigned driver is possible. Most people will not want to do that and getting a certificate for driver signing costs a lot of money (I think over $200).

**Comment by JarnoVgr** [comment]
There is also an open-source code signing certificate which is a lot cheaper: https://en.sklep.certum.pl/data-safety/code-signing-certificates/open-source-code-signing-976.html
It's capable of signing Windows executables, but I'm unsure if it also works with drivers. On top of that it looks like it isn't cross-certified by Microsoft.

**Comment by RedKage** [comment]
Yeah well, I got the answer of my question :)

Pretty much:
- Default build = uses Scp drivers. Scp drivers are bundled in DS4Windows and can be installed thanks to a little install wizard
- ViGEm build = uses ViGEm driver. Not bundled in DS4Windows, and there is no need of the Scp drivers. One can safely uninstall the Scp drivers then.

To install the Scp drivers I did Powershell this:
```Register-PSRepository -Name nuget.vigem.org -SourceLocation https://nuget.vigem.org/ -InstallationPolicy Trusted
Install-Module ViGEmManagementModule -Repository nuget.vigem.org
Install-ViGEmBusDeviceDriver
Add-ViGEmBusDevice
Install-ViGEmBusDeviceDriver
Get-ViGEmBusDevice

I report that all works fine. 
DS4Windows detects both my DS4 pads. One is a V1 and the other is a V2.
I'm using these pads wired.
BT doesn't work for me, but that's an issue on my end I think.
