### ISSUE TITLE
DS4Windows in combination with Steam Input API

### ISSUE THREAD

**Issue by RaideX101** [Ryochan7/DS4Windows#385]
You get a message when starting the new Monster Hunter: World that it detects a mapper program. After reading that I've noticed that it's actually possible to use a DS4 with Steam games using their own mapper.

This has many drawbacks, but one that is very noticeable is that Windows registers the DS4 controllers as XBOX 360 controllers. It seems that games read this information on controller supported games and they display their button images based on that. 

My question now is if it would either be possible to use the Steam Controller API together with DS4Windows or if there is a way of spoofing the system so that the games can read the correct controller type (in my case a Dualshock 4).

**Comment by Ryochan7** [comment]
There is no way, that I know of, that would allow DS4Windows to be able to utilize the Steam Controller API. As for creating a virtual DS4 controller instead of emulating an Xbox 360 controller, it is not possible to do that in DS4Windows right now. ViGEmBus is a driver that can be used to create virtual DS4 controllers.

There is an alt build of DS4Windows that uses ViGEmBus instead of the default ScpVBus driver but controller emulation is still limited to creating virtual Xbox 360 controllers. ViGEm support would have to be integrated into the main DS4Windows build before possibly implementing a way to present Windows with a virtual DS4 controller from DS4Windows.

I have made some test code to try out DS4 controller emulation and the end result actually turned out pretty well. Playing Rocket League with a DS4 v1 connected to the Sony Wireless Adapter actually seemed to perform better than using the native DS4 support in the game with the DS4 v1 connected via USB.

https://www.youtube.com/watch?v=eFNXaXOiJxQ

**Comment by RaideX101** [comment]
It's good to read that there is a possibility on the horizon. Is this something that you've planned to implement? According to the SCP Page, ViGEm Bus Driver seems to be the 'modern reincarnation' of the SCP drivers. I'm not sure what the upsides are but it seems to be maintained at least.

Anyhow, just for you to take into consideration. You're tool is by far the best I came across regardless of how you decide to move forward.

Keep it up!

**Comment by Ryochan7** [comment]
The issue keeping DS4Windows from using ViGEm by default is the current state of the stable ViGEm driver. The current stable ViGEm driver has some minor issues that make it perform a bit slower than ScpVBus does. Changes to the latest code fix the problems I had with it and it is my preferred driver.  Especially since the UDP server business finally got resolved, maybe I should get in touch with Benjamin and see when he might release a new signed version of the driver.

I am not so sure about DS4 emulation support though. I don't have a real use for it. Rocket League is the only game that I have in my game library that has native DS4 support. At least for that game, it isn't a big deal to see Xbox 360 button prompts.

**Comment by Corrodias** [comment]
I just want to point out that DS4Windows works fine with MHW. The message Steam gives you is simply because it detects that DS4Windows is running and is alerting you to the fact that the game has native support for the DS4 controller via the Steam API (that is, proper native support, better than if it were reading it as a DirectInput device).

The message is harmless and can be ignored.

**Comment by RaideX101** [comment]
Have you gotten it working with the Steam API while using DS4Windows? I've tried various things using my DS4 so that Steam might recognize my controller but it didn't work. I'm sure there is some sort of interference with Steam and DS4Windows.

I realize that it probably won't make the message disappear but I think that MH:W supports native DS4 (as you said) so I was looking for a way to detect the controller as a DS4 inside of Windows so that games could switch from using Xbox buttons to PS4 buttons. 

Granted, there are only a handful of games actually doing this differentiation but nonetheless it would be a great addition.

**Comment by Corrodias** [comment]
MHW doesn't actually display ds4 button icons anyway. You can find a mod
for it on Nexus mods, if you want that. To answer your question, no, it
does not get recognized as a ds4 gamepad via Steam. But in the sense that
it works fine in the game, with all your ds4windows remappings, it "works"
through the Steam API.

**Comment by Ryusennin** [comment]
Disable the Steam Controller support (through Big Picture Mode) and your DS4 (via DS4Windows) will be fully recognized as an X360 pad without any nagging from Steam.

**Comment by Corrodias** [comment]
It isn't enabled and hasn't been for a long time.

**Comment by Ryochan7** [comment]
That is a shame that MHW still shows Xbox 360 button prompts. If the game uses the Steam Controller API then I would hope that the game will get updated with PS glyph support for people using the DS4 controller.

The last game that I bought that had Steam Controller API support was .hack//G.U. I don't remember the support being that good. Testing it out now shows that I would much rather use DS4Windows and emulate an Xbox 360 controller than use the included SC API support.

**Comment by co5mo** [comment]
I encountered this when playing Dead Cells from GoG it shows x360 prompts when using ds4w, it would be cool to enable native ds4 for games that support ds4 and ds4 prompts

**Comment by jonaaa20** [comment]
Indeed, Rocket League also supports the native ds4.

**Comment by Corrodias** [comment]
If you want native DS4, you can simply stop and exit DS4Windows, but of course you don't get the remapping features. :) I've found it more useful simply to memorize the Xbox button layout. As a result, I'm good to go for all PC games without modding to change the button icons.

**Comment by pralima87** [comment]
This would be really awesome since Steam controller api offers a lot of cool customization for a DS4,
like radial / touch menus.
