### ISSUE TITLE
DS4Windows 1.5.4 seems to have huge MemoryLeak

### ISSUE THREAD

**Issue by Kajiryu** [Ryochan7/DS4Windows#388]
Just updated to the new 1.5.4 build. Played two hours in Cemu and the game startet to stutter. Quit the game and saw DS4Window using around 5GB of my RAM.

Started it again and it seems that it allocates more and more memory the longer it runs. Maybe because of the activated UDPServer.

**Comment by Ryochan7** [comment]
The UDP server does seem to steadily increase memory usage over time. However, on my system, the garbage collector kicks in around the 60 MB mark and application memory usage stays around 50 MB going forward. Apparently the garbage collector is not doing its job and freeing memory like it should.

**Comment by Ryochan7** [comment]
Do you have the same issue with version 1.5.3? I am wondering if the issue might be related to a recent change with timers as opposed to the UDP server.

**Comment by Kajiryu** [comment]
I didn't notice this problem in 1.5.3, so I can't say for sure. I will roll back and test that when I have time.

**Comment by Kajiryu** [comment]
Maybe it is related to the process priority of Cemu, which is above normal. But that shouldn't keep .NETs garbage collector from running.

**Comment by Ryochan7** [comment]
Okay. I have tested the UDP server while running PadTest as a client and I can see a memory leak. Apparently the async version of the packet sending routine is not freeing memory buffers that are being used so memory is being leaked with each call and never recovered by the garbage collector. The problem happens with both version 1.5.4 and 1.5.3.

**Comment by Ryochan7** [comment]
Implementing a small change was enough to fix the memory leak. Later I need
to test if input performance is impacted in game or not. The responsiveness
of PadTest seemed about the same.

**Comment by fersnake** [comment]
i though it was just me xD i started to notice this too on 1.5.3 while playing on cemu, got me like 6gb ram usage, thx @Ryochan7 for the hard work and hope for a fix late, thank god i finish already BoTW. btw i just need to disable UDP server on settings right?

**Comment by ceedveed** [comment]
I'm on 1.5.2 and commit size is about 650 MB. I've never seen DS4Windows go this high.

**Comment by Ryochan7** [comment]
That would be unrelated since the relevant changes were not introduced
until version 1.5.3. Can you share the profile that you are using along
with the other XML files? I need an idea about which settings and macros
you are using that might be causing a problem.

I will get a new version of DS4Windows uploaded sometime today.

**Comment by Kajiryu** [comment]
Thanks for fixing this so fast. I will send you a little thank you over Paypal. Keep up the good work.

**Comment by ceedveed** [comment]
Here is my appdata from 1.5.2
[ds4windows appdata.zip](https://github.com/Ryochan7/DS4Windows/files/2281280/ds4windows.appdata.zip)

**Comment by Ryochan7** [comment]
The new build has been released.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.5.5/DS4Windows_1.5.5_x64.zip

**Comment by cascardian** [comment]
I know @Kajiryu closed the issue, but I'd like to report that I still see high memory usages with 1.5.6. It hovers at around 265 MB with _UDP Server_ on (sometimes dropping to 215 and then creeping upwards again) and around 120 MB when off. Occasionally, especially when the app doesn't run minimised, I've seen it bloom to 325 MB, then garbage collection brings it down to 245 MB again after a bit of time. With the That still seems a bit high. On a fresh start (via admin-privileged task), usage is about 35 MB. It takes around fifteen to twenty minutes to reach the sizes at issue.

I use _Hide DS4 Controller_ in conjunction with HIDGuardian 1.14.0.0 on Windows 10 RS4. I haven't tried the ViGEm build, since you previously mentioned that the currently released signed driver doesn't contain some of your performance improvements, @Ryochan7.

[DS4Windows-AppData.zip](https://github.com/Ryochan7/DS4Windows/files/2306975/DS4Windows-AppData.zip)

**Comment by Ryochan7** [comment]
I ran Cemu with DS4Windows running the UDP server for over 12 hours and I did not experience a major memory leak. Peak memory usage was around 50 MB with the memory usage actually ending around 25 MB. Cemuhook was doing its job and motion control support was working in game.

I don't really know how server mode garbage collection mode works with .NET. The only thing that I know from experience is that input latency is much better off using that mode as opposed to using the default workstation mode. The major consequence is that more system memory is used because garbage collection happens less often. 

I will try out the appdata and see what happens on my system.
