### ISSUE TITLE
Could not connect to ViGEm

### ISSUE THREAD

**Issue by anphetamina** [Ryochan7/DS4Windows#391]
I'm not able to initialize the ViGEm build, I'm sure I've removed all the leftovers of the previous main DS4Windows installation but it doesn't work.

> 13/08/2018 15:10:29: DS4Windows version 1.5.5
> 13/08/2018 15:10:29: LinkedProfiles.xml can't be found.
> 13/08/2018 15:10:29: Could not connect to ViGEm. Please check the status of the System device in Device Manager

**Comment by Ryochan7** [comment]
The ViGEm build works fine for me. Is the Virtual Gamepad Emulation Bus device disabled in Device Manager for some reason?

**Comment by Ryochan7** [comment]
Did you try to install ViGEm recently? It looks like Benjamin removed the download archive that the test installer was using. Looking at the downloads section, I don't see a link to version 1.14.3.0 anymore; the most recent version that I could find is version 1.14.1.0. Luckily I still have a copy of the archive on my system.

https://vigem.org/2018/08/12/broke-downloads-page-fixed-it/

**Comment by anphetamina** [comment]
No, I simply uninstalled everything (HidGuardian and the SCP Virtual bus drivers), deleted the DS4Windows folder and all the scp drivers using driverexplorer, nothing else

**Comment by anphetamina** [comment]
Do I need to use HIDGuardian with the Vigem build aswell?

**Comment by Ryochan7** [comment]
HidGuardian is completely optional. Most of the times I still use the old exclusive mode workaround.

As for the "DS4 driver", you have to install ViGEmBus manually outside of DS4Windows. Even when using the ViGEm build, using the Welcome Dialog will still attempt to install ScpVBus instead of ViGEm. It is best to install ViGEmBus before attempting to run the ViGEm build of DS4Windows. There will probably not be any way to install ViGEm from DS4Windows until ViGEm support is put into the main build. I would just disable the Welcome Dialog entirely in that branch but DS4Windows runs worse without that window being utilized somehow.
