### ISSUE TITLE
Won't minimize to taskbar

### ISSUE THREAD

**Issue by InstallGentoo11** [Ryochan7/DS4Windows#395]
It launches minimized, but if I open the program then it won't minimize to the taskbar anymore. It first happened when I was installing DS4Windows on the PC of a friend. When I got home, after being away for a while. I experienced the same issue. It must have occurred in the last few builds (a week or two tops). Both PCs are working on Windows 7.

**Comment by Ryochan7** [comment]
Minimizing to the system tray is the default behavior. I ended up inverting the clause used unintentionally so that DS4Windows would minimize to the taskbar by default instead. In order to have DS4Windows minimize to the taskbar, you have to check the "Minimize to Taskbar" checkbox in the Settings tab.

**Comment by InstallGentoo11** [comment]
Ah, whatever. It was all my mistake, I guess. I meant the tray at that. Stupid me.
