### ISSUE TITLE
DS4Windows with 2 controllers

### ISSUE THREAD

**Issue by sandrik93** [Ryochan7/DS4Windows#396]
Hi,
I've been using DS4 with PC for the past couple years and all works well as long as you use only 1 controller wirelessly. Soft used - DS4Windows. Decided to get the second one. Both connected get the awful lag and one of them constantly disconnects. If I use the other one wired then all good vut it defeats the purpose of having a wireless controller. Tried all the lag fix suggestions I could find online. So far, no change. Connecting to Predator 15 with it's own bluetooth receiver.
Any suggestions?

**Comment by Ryochan7** [comment]
I had the same type of experience when I initially got my v.2 controller and tested multiple controller connections. Unfortunately, the real solution to the problem was to get a different BT adapter. With my older Rocketfish BT 2.1+ adapter, having one controller connected worked fine but latency was not consistent when multiple controllers were synced. The only workaround that worked for my older adapter was to choose a higher BT Poll Rate of 8 ms in my profiles. After using that setting in my profiles, the connection for both controllers became stable.

My current Rosewill BT 4.0 adapter is able to handle multiple controller connections just fine.

https://www.newegg.com/Product/Product.aspx?Item=N82E16833166126

**Comment by hopia2290** [comment]
I also had this problem before sir. The only way I solved this is by also changing my BT adapter to BT 4.0

**Comment by sandrik93** [comment]
It does look like the adapter issue since when I changed it to 4ms polling, both work just fine. Still, the laptop has the built-in BT 4.1 adapter. I can't fathom how an external one would make it better. Thanks for responses, by the way
