### ISSUE TITLE
1.4.71 - unhandled exception crashing on "Speacial Actions" tab

### ISSUE THREAD

**Issue by pralima87** [Ryochan7/DS4Windows#42]
I'm experiencing some **unhandled exception** crashing in the **Special Actions** tab when using 1.4.71.
I think it might have something to do with **Multi-Action Buttons** but I´m not sure.

It also happens when saving a profile.

**Comment by Ryochan7** [comment]
Can you provide a Windows log with the .NET Runtime error?

That whole ListView acts a bit weird. When working on 1.4.71, I encountered an error when an ItemChecked event fired for that ListView when the Options form wasn't even open. I changed a couple of portions to get around the error that showed up but maybe something was missed. At this rate, I will just change the form so that the EventHandler is dealt with manually rather than using the IDE generated hooks.

**Comment by pralima87** [comment]
Sure right now I'm far from the pc but I'll report back latter 👍

**Comment by Ryochan7** [comment]
I think I might have just stumbled upon the problem you are having. Got an index out of bounds runtime error when loading a profile from the Profiles tab instead of the Controllers tab. A couple of arrays in the BackingStore did not have a 5th element like the other arrays do so using a temp profile association would cause an error. The new ResetProfile routine just happened to expose the problem.

This is a big enough problem to justify a quick patch release. That will be uploaded soon.

**Comment by Ryochan7** [comment]
Hopefully the new release works out better.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.4.72/DS4Windows_1.4.72_x64.zip

**Comment by pralima87** [comment]
Yep can consider this one fixed in 1.4.72

**Comment by pralima87** [comment]
I think this issue is back in 1.4.95.
Some of my "heavy" profiles are crashing.

My guess is that is related to the multi-action special action since only profiles using this feature are crashing.
