### ISSUE TITLE
How can I set accel as separate axis?

### ISSUE THREAD

**Issue by MarioPL98** [Ryochan7/DS4Windows#423]
Hi. I want to set these readings as separate axis for simulation games. How can I do that?
![image](https://user-images.githubusercontent.com/16231640/45377887-3fb4ce00-b5fc-11e8-8544-39abc7c66ec9.png)

**Comment by BlackPowerade** [comment]
Doesn't look like you can. Nothing in the program about mapping it, nor any hidden settings in the config files... Looks like you are out of luck with this one, or you could ask Ryochan if he is willing to implement it.

**Comment by MarioPL98** [comment]
Is it possible to make Vjoy read udp server and create another controller with axis?

**Comment by BlackPowerade** [comment]
The UDP server is only feeding **Gyroscope** data, not **Accelerometer** data. I don't know what vJoy is capable of, but as far as I know the Accelerometer data is not exposed by the program.
You'll need to take a look at the source code if you are really dedicated to seeing if the data is available.

**Comment by MarioPL98** [comment]
Any kind of motion control as axis would be fine.

**Comment by BlackPowerade** [comment]
Theoretically, yes. If you wrote a feeder application for vjoy that would read from the UDP server you could  create a virtual joystick that provides the gyroscope data. This is essentially what Cemu does.
But, I do not know if any kind of feeder application specially for this purpose exists.

**Comment by Ryochan7** [comment]
Regarding the mapping, you can assign pitch and yaw to axes on an Xbox 360 controller; there is no way to assign roll to anything (corresponding to middle slider). It is a two step process since each direction would be handled as two half axes. There is no way to create another exposed axis to map the accel data to outside what is available on an Xbox 360 controller.

The UDP server transmits the entire state of the DS4, not just data about the gyroscope. You could make a program that reads the data from the UDP server and use Vjoy in order to create an arbitrary DirectInput controller with the axes that you want mapped. However, it would probably be better if you could read the data directly from the controller rather than relying on the UDP server connection. I need to update my small DS4 emulation test program anyway so maybe I should update the DS4Library portion used in it and create a small class library.
