### ISSUE TITLE
Exclusive/Hide DS4 Controller not working when Steam is open

### ISSUE THREAD

**Issue by yousie642** [Ryochan7/DS4Windows#424]
When Steam is open, Exclusive mode/Hide DS4 Controller doesn't work. For some reason this also causes the DS4 driver to corrupt or something because the next time I disconnect and reconnect the DS4, even with both Steam and DS4Windows closed, I have to remove the device from Devices and Printers and disconnect/reconnect again.

**Comment by jonaaa20** [comment]
In my case when steam is opened, the ds4 doesn't work on some games and on retroarch, if I close it and then reconnect the ds4 again, it works.

**Comment by BlackPowerade** [comment]
This is because steam already has "dibs" on the controller. If you open steam and connect the controller before you open DS4Windows, it will usually print an error message in the bottom right saying _controller XXXX could not be opened in exclusive mode_
As for the controller needing to be removed and repaired for proper function afterwords, Valve is retarded and Steam is a legacy code mess. Steam probably "tainted" your controller in one way or the other when it gets exclusive controller.

**Comment by yousie642** [comment]
Is there any way to stop Steam from getting "dibs" if I just so happen to have it open when I connect my DS4, short having to make sure it's closed every time I go to connect? I've disabled every setting for controller support I could find in Steam, but it still happens.

**Comment by BlackPowerade** [comment]
Go into steam big picture and disable Dualshock 4 gamepad support if that is enabled. This should stop steam from picking up the controller when you connect it. If that does not work, leave DS4Windows on in the background. It barely uses any resources when nothing is connected in the background, and usually never uses more than 50 MB of ram. Small price to pay for less hassle.

**Comment by Ryusennin** [comment]
Configure DS4W to run at Windows startup and always launch Steam manually instead of boot time.

As BlackPowerade describes, *always* make sure Steam controller support is completely disabled, you don't need it. The few games which bypass XInput to enforce Steam controls (like Prey) are broken and need to be patched (it took a year for Bethesda to listen to the players and fix their mess).

Also, you really should install HID Guardian. In my experience, the built-in exclusivity mode of DS4W is not enough and will not always work reliably.

**Comment by MuteButtonHero** [comment]
I'm actually not having any issue running both so long as, as has been suggested here, I start DS4W first.  In fact, having it hide the controller has resolved the double input bug Steam experiences with some games. I then let Steam see it as a XB360 controller.

Why bother with Steam at all? Because it is sensitive to where you are in various games. I'm using it with No Man's Sky and I want very different configurations based on whether I'm on foot, in an exocraft, in a starship, in the inventory screen, or using a quick menu. Nor does it matter if I use the keyboard/mouse to get in/out of those different states; it still knows where I am and gives me the right control set.

The problem I ran into with just Steam is that it was taking input from the controller as BOTH the setup I had customized AND the default.  So the X would jump per the default AND scan per my custom setup. This double input is an old and well know issue on Steam that they sometimes resolve and sometimes pops back up when they update, as happened with the latest update. Hiding the DS4 fixes that, at least for me.

I will say that just how Windows itself treats the DS4 is a witch's brew of bad functionality.  You can easily end up with a situation where you can't even pair the thing, regardless or whether you have DS4W, Steam, or anything else running. That can be a mess to untangle and that's before DS4W even gets a look at the controller. I suspect MS needs to be more agnostic about functionality with rival products.
