### ISSUE TITLE
Ds4 Locking up PC

### ISSUE THREAD

**Issue by kloperman** [Ryochan7/DS4Windows#428]
Updated to latest Windows 10 update (version 1803 OS build 17134.285) and now everytime I plug in my controller and start Ds4Windows it completely locks up my PC requiring a hard reboot.

**Comment by jinkazama82it** [comment]
You need to start Ds4Windows before connect your controller, use the option to start automatically DS4Windows.

**Comment by Ryochan7** [comment]
Are you using the main ScpVBus build or the ViGEm build? Freezing problems
would be more likely caused by the output driver than anything else. Both
current builds work fine for me. But as an example, the latest ViGEm alpha
driver causes some significant freezing. Reverting the ViGEm driver fixed
the feezing problems that I was experiencing.

**Comment by kloperman** [comment]
Im using the latest version available. I tried what jinkazama82it said to do and this time it worked properly, last time i tried it like that the controller wasn't getting picked up at all. Anyway, thank you the issue it solved and it works perfectly now.
