### ISSUE TITLE
[Request] Hide DS4

### ISSUE THREAD

**Issue by RKMN7** [Ryochan7/DS4Windows#432]
Can the "Hide DS4 Controller" functionality please be made profile specific? Rather than a global option like it is now. Since there is no way to enable/disable the hide with macros, having to open the program every-time to toggle it, is the only way, unless I'm missing something. Having it profile specific would allow for far greater flexibility of the application's use-cases.

**Comment by jinkazama82it** [comment]
in which case is usefull to have 2 controller that make the same action instead of 1?
I'm lost something?

**Comment by RKMN7** [comment]
So that one profile can be for DInput and one for XInput. I'm surprised that this wasn't implemented since it'd be quite useful.

**Comment by Ryochan7** [comment]
The current infrastructure would make implementing something like that fairly difficult as the process would involve having to stop all mapping routines for a controller, close an HID device and then open the HID device again in shared mode. Besides the coding complications, that functionality is pretty much impossible for controllers connected via Bluetooth. Due to the way that DS4Windows uses the HID device, the original DirectInput device presented to Windows becomes unusable once DS4Windows establishes a connection with the Bluetooth controller; only applications that already have an open handle on the DirectInput device can use it. The only way to get access to an applicable DirectInput controller again is to disconnect and then re-connect the controller when DS4Windows is not running.

I have thought about it before but the issues with Bluetooth connections pretty much destroys any possibility to have the option be moved to profiles.

**Comment by RKMN7** [comment]
Ah ya, makes sense. I hadn't considered Bluetooth when I was thinking about it. Was just thinking abt wired connections, where something like uplay would stop exclusive from running and a profile switch would be a simple way of handling that, since the 'DInput only' option was available. Anyway, thanks for the reply
