### ISSUE TITLE
Retroarch not working correct

### ISSUE THREAD

**Issue by alissongamer** [Ryochan7/DS4Windows#435]
I have a problem with Retroarch. Many times when I use Retroarch the joystick does not work. So I go into Retroarch input settings and select to use Xinput Controller, and it works there. But when I restart the PC it stops working again. Another thing I noticed is that it might do this because it recognizes 2 controls, Xinput and DualShock4, but the option to hide DS4 is selected in DS4 WIndows, so it should not be recognized in Retroarch.

**Comment by jinkazama82it** [comment]
You start DS4 Windows before or after Retroarch?
because it seems an issue of this type, if you run DS4W after an application that can control the controller it's aren't able to hide the extra controller.
is a good thing start DS4W at startup so you no need to remember to run it before run any type of allpication that use the controller.

**Comment by alissongamer** [comment]
Yes, DS4 Windows is already configured to start with Windows. Can it be Steam?

**Comment by jinkazama82it** [comment]
if you start Steam at Windows startup yes, because it start before of DS4W and grab the exclusivity for the controller configuration before DS4W that in this case can't configure in the right way the controller.

**Comment by jonaaa20** [comment]
The problem is steam "stealing" the access to the controller, the solution is to close Steam then reconnect the controller, then you can reopen steam.

**Comment by Ryochan7** [comment]
Steam is more likely to cause problems with obtaining exclusive access to the DS4 than other programs. If you have both DS4Windows and Steam set to run as Windows startup, I bet that Steam would probably initialize first because it takes the .NET Runtime some time to get started before actually launching a program. Using HidGuardian would be a way around the issue without having to add some delay to when Steam is started.
