### ISSUE TITLE
Please help me with understandin how udp server works.

### ISSUE THREAD

**Issue by MarioPL98** [Ryochan7/DS4Windows#437]
Hi. I'm trying to make an app that creates vjoy controller based on gyro data from udp server. I can't get the udp communication to work. What does the server expect to get as request? What format is used to return data? Is there any documentation on this? Which bits contain what information?

**Comment by Ryochan7** [comment]
As far as I know, there is no documentation on how to use the UDP server or the data structure that is used for packets. The wiki needs to be updated to document the data format used but I don't know how to interface with the server. You might want to contact @rajkosto since he is the original developer of the UDP server and CemuHook.

This weekend should be devoted to working on DS4Windows so I will hopefully finally migrate my DS4Library changes over and bundle that as a class library for other C# programs to use.

**Comment by MarioPL98** [comment]
I already tried sending email to admin@rajko.info (@rajkosto) but got no answer yet.

**Comment by Ryochan7** [comment]
That is a bummer. Maybe he will pop up sometime.

I will have to document it a bit later but I updated the library code and built a class library. I will post a link to the archive now. It is an x64 library as I am against using the AnyCPU platform target for the most part.

http://ryochan7.xyz/ds4windows/temp/DS4WindowsAPI.dll.zip

You can add the dll as a reference and the namespace DS4Windows will be made available to use. Here is some sample code that I had used to make the PS4 controller emulation tester. It uses the library code directly rather than using the class library. I made a different program to confirm that the class library works that I will also link here.

http://ryochan7.xyz/ds4windows/temp/ds4input_test.tar.gz
http://ryochan7.xyz/ds4windows/temp/DS4ImportTest.zip

**Comment by Ryochan7** [comment]
I will cover only a small amount here. Your program will have to handle hotplug detection. The main starting point for DS4WindowsAPI is the use of findControllers `DS4Windows.DS4Devices.findControllers()`. That will populate a Dictionary with HidDevices that are detected as DS4 controllers. A list of detected controllers can be retrieved by the client program afterwards using `DS4Windows.DS4Devices.getDS4Controllers()`.

For each device in the returned array, you would then add an event callback to the `DS4Windows.DS4Device.Report` event handler. Finally, a call to `DS4Windows.DS4Device.StartUpdate()` needs to be called to start reading input reports from the controller.

The main class that a client program will require will be an instance of DS4State which stores all relevant axes and button states for a gamepad poll. A reference to the current state object is obtained with `DS4Windows.DS4State.getCurrentStateRef()`. The state object can then be read and any translation can be done as desired.

Finally, the most minimal way to stop all detected DS4 controllers is to call `DS4Windows.DS4Devices.stopControllers()`. That will call the StopUpdate routine for all detected controllers and close the relevant HidDevice handles.

Here is a small snippet showing those steps in action.

https://gist.github.com/Ryochan7/6b4ef7e413755eeac9906e4b24634d69

The class file for DS4State is easy to read so I will link to the file as reference to that class.

https://github.com/Ryochan7/DS4Windows/blob/jay/DS4Windows/DS4Library/DS4State.cs

**Comment by Ryochan7** [comment]
Minor documentation so far. It is a work in progress that I will hopefully update further.

https://github.com/Ryochan7/DS4Windows/wiki/UDP-Server-Output-Packet-Information

**Comment by MarioPL98** [comment]
This is amazing. What about input?

**Comment by emko** [comment]
did you ever figure out what you need to send to get a response back?

**Comment by MarioPL98** [comment]
Nothing helpful. I had very little time since I got to university.
