### ISSUE TITLE
Bluetooth cant re-pair my controller.

### ISSUE THREAD

**Issue by fersnake** [Ryochan7/DS4Windows#441]
Sorry it's me again xD 

I really dont want help really, well kinda. i had to reinstall windows :S so my BT drivers worked again i got driver corrupted, got some error 28 while trying to install the drivers it was bad i had to format xD.

the thing is, at first everything was working right, easy install of ds4/bluetooth etc. the problem was when i used my ds4 on the ps4 and then try to re-pair it again on the pc. i just couldnt. windows didnt let me remove the wireless device (ds4) i tried to uninstall everything (ds4windows, the driver, bluetooth etc)  so if anyone had this problem i really wanted to know what happend there, i know its not directly a DS4Windows problem but just for the sake of curiosity and lear something new xD.

ps. i tried the controller wired and it worked, the thing was with the BT driver and windows. 

ps2. my windows had like 2 years since last reinstall so maybe that was the problem to begin with xD

this is my bt dongle.

https://www.amazon.com/Bluetooth-Receiver-Transfer-Wireless-Keyboard/dp/B0775YF36R/ref=sr_1_5?s=pc&ie=UTF8&qid=1538451253&sr=1-5&keywords=bluetooth+usb

**Comment by olokos** [comment]
My bet is that the dongle you're using has pretty crappy drivers. I bought Intel AC-8260 specifically so I'd get BT on my PC. I'd recommend you to buy some intel wireless card with bluetooth. I also had about 3 different BT dongles and none worked flawless, reception strenght aside. That one was about 25$ including m.2 to PCI-e adapter with 2 antennas thrown in as a bonus. Those aren't expensive, especially since a lot of them are installed in notebooks and then taken out and sold separately.
