### ISSUE TITLE
Disconnecting while Exclusive Mode is enabled leaves the controller disabled in Device Manager

### ISSUE THREAD

**Issue by slaugaus** [Ryochan7/DS4Windows#444]
I have a New DS4 and use Bluetooth, if it matters.

**Comment by Ryochan7** [comment]
Even with the work that has been done, that is still a possibility when using the older method of obtaining exclusive access. It happens far less often than it used to but it is still possible to have the DS4 get permanently disabled by Windows after disconnecting a controller. This problem is mentioned in the main README file.

https://github.com/Ryochan7/DS4Windows/blob/jay/README.md#device-detection-issue

I cannot even implement a fail safe workaround in DS4Windows without application performance degrading. Using HidGuardian might help get around this problem somewhat. It is still just better to be mindful of this problem and check the Device Manager if you encounter any problems.

With the recent change regarding hotplug detection, I am hoping that the problem might not come up anymore but I cannot be too sure about that.

**Comment by Ryochan7** [comment]
So far I have not encountered an issue with a permanently disabled device after the hotplug routine updates. The last time I had encountered problems before was a timeout issue when an elevated second instance of DS4Windows would be killed before the exclusive mode routine would finish. At that time, the tweak was to extend the timeout interval. As it is now, that old workaround will not be used anymore as DS4Windows now requires that a user run it as the administrator.
