### ISSUE TITLE
Why would my controller have less input lag when my Bluetooth dongle attached to a 15 foot USB extender? 

### ISSUE THREAD

**Issue by Jasparigus** [Ryochan7/DS4Windows#450]
My controller lags like crazy when the dongle is plugged directly in my computer and I'm 2 feet away but is totally stable when the dongle is on the end of a 15 foot USB extender in another room.

**Comment by Ryochan7** [comment]
I have heard similar reports before regarding a connecting becoming more reliable when connecting a dongle to an extender; nothing to that extreme though. I guess there could be some minor interference that even a case could produce depending on where you have a dongle connected. When performing a similar test, I only noticed minor differences but the connection was slightly better when connected to the extender. I don't usually plug my dongle into the back of my case but on some ports on the top.

The network configuration or use of other electronics close by could also impact the reliability of a Bluetooth connection. Either way, this is a hardware problem. Nothing in DS4Windows would affect this.

**Comment by TristanYoung** [comment]
Computer cases being metal and grounded can definitely affect wireless transmission (think Faraday cage, but not really a cage, more like a Faraday wall of sorts).  Considering the 2.4GHz spectrum is often congested due to the plethora of devices using the few available channels (other Bluetooth devices, cell phones, microwave ovens, Logitech wireless mice, thermostats and smoke detectors, wifi routers and range extenders, baby monitors, wireless cameras, etc.), and the signal absorbing and blocking properties of the case (even if the dongle is located just barely outside the case) - it's all cumulative.

If you want the best signal, gotta pull it away from the computer. But going too far has the other impact of reduced bandwidth (fall-back to slower speeds of USB1.1, and eventually to a point where the computer can't even see the dongle).

Your mileage will vary. There is no hard, fast rule.  You might also get a similar improvement by modding your bluetooth radio's antenna - by calculating the optimal antenna length, and soldering it to the circuit board on the radio.

Of you could just launch it in a slingshot - that'll make it go faster.

https://www.makeuseof.com/tag/usb-wi-fi-dongle-lagging-3-ways-fix/

**Comment by vvilkommen** [comment]
I'm sure there are way more fun, technical ways to address this, but when I was having a similar problem with case interference, I purchased a 6 ft. usb extender from Wal-Mart. It seems to be working well, with no discernable hit to latency. Not sure that I would go too far beyond 6 ft, though.

Good luck!
