### ISSUE TITLE
half life 2 

### ISSUE THREAD

**Issue by robinjoo1** [Ryochan7/DS4Windows#456]
half life 2 keeps disconnecting/connecting ps4 controllere please help

**Comment by Ryochan7** [comment]
Half-Life 2 was considered a Linux only game to me when SteamOS was still
kicking. Nowadays, it doesn't matter to me anymore especially since the
greater Linux community doesn't seem to care about native games. I'll
install the Windows version and try it out later.

Based on my past experiences, I am pretty sure that I would not like full
controller support. Mixed controller and emulated mouse support was my
preferred way to play Half-Life 2 with a controller.

**Comment by robinjoo1** [comment]
should i also attach a log file ?

**Comment by Ryochan7** [comment]
I played through the first hour of Half-Life 2 without any problems. I tried it using full controller support and mixed controller and mouse control profiles. Mixed controls feel much better than using analog stick controls for aiming.

**Comment by Ryochan7** [comment]
Continuing the tangent, my preferred mouse sensitivity is now 55. That would be equivalent to 2600 pixels per second. Enhanced Precision output curve is used for RS. I ended up playing up to chapter Black Mesa East.

**Comment by Ryochan7** [comment]
Looks like this issue is dead. Hopefully you figured out how to solve the problem. As a side note, I played all the way through the campaign without any issues. It helped me with tweaking the Enhanced Precision curve in the process.
