### ISSUE TITLE
Crash when use Gyro as mouse, connect via USB

### ISSUE THREAD

**Issue by Fireblossom** [Ryochan7/DS4Windows#469]
No fault under Bluetooth connection. But when I plug in the usb cable, it shows
`10/26/2018 7:47:58 PM: X360 Controller # 1 failed. Using DInput only mode`
And crashed when I try to use gyro as mouse.

Win10 Enterprise 1803
Version 1.5.13

Any ideas?

**Comment by Ryochan7** [comment]
I don't use Quick Charge most of the time especially since I use the Sony Wireless Adapter a lot. I just tested Quick Charge out and it worked just fine on my end.

**Comment by Fireblossom** [comment]
Thanks reply!

The issue is using gyro as mouse will cause crash when connect DS4 via USB, but Quick Charge.

I guess `DInput only mode` not compatible with using gyro as mouse.

**Comment by Ryochan7** [comment]
Gyro as Mouse when connected via USB works for me. Dinput only mode should work fine as well since that just controls whether a virtual XInput controller is plugged in and a report is generated. It should not matter if that mode is enabled in a profile or if ScpVBus fails to connect a controller for some reason. Having Quick Charge enabled should not matter and using Gyro as Mouse while the controller change happens works fine on my system.

**Comment by Ryochan7** [comment]
I am hoping that maybe the recent addition of an extra gyro calibration check has helped with the gyro mouse problem documented here. The few times I encountered an issue with DS4Windows crashing when Gyro Mouse has been enabled has been due to a division by zero error.
