### ISSUE TITLE
Adding an Alternate Fire Button to DS4 Windows

### ISSUE THREAD

**Issue by Bbridgewa** [Ryochan7/DS4Windows#471]
[Request]
Any chance we could get a way to set secondary key bindings for a single DS4 button? Like the way, the shift button works on a keyboard or the  "2nd" button on a Texas Instruments calculator. 

At the moment, we can set a special action for L1+Circle to perform any macro or keyboard action we want. However, when this special action is performed, any action bound to L1 will fire and any action bound to circle will also fire when we try to perform the special action.

I understand why this happens but it would be very nice to have the option to bind any DS4 button to "Switch to alt Fire". Then every other key could have an alt-binding that activates when that key+alt-Fire button are both pressed. This would allow every button on the controller essentially have a secondary binding, and it would give users access to much more complex control schemes through the software. 

 For example, a user could bind an alt-Fire button (Ex: L1) and use it to switch to secondary binding mode while L1 is held. The user could then bind circle to an action as well as binding alt-Fire-circle to a different action. Now, when the user presses L1+circle, only the alt-Fire-circle action is performed and the original primary action of circle is not.

**Is there already a way to do this that I am missing?** All I need to do is perform a special action but not the actions of the underlying buttons used to input the special action. Essentially, I would like to see special actions that could  'hide' the comprising button inputs. My apologies if this is not the correct place to ask questions.

**Comment by Ryochan7** [comment]
The closet thing that might be possible is to swap profiles via a Special Action. That would probably be a very slow way to do it though. There is no form of action set support in DS4Windows. There is mode shift modifier functionality so that can help add some extra mapping options.

Most of the time spent working on this program has been trying to improve the very basic mapping of a DS4 to an XInput controller. Some extra mapping options have been added over time but getting the most basic mapping configuration optimized has been the main goal. It would be nice to have some more advance mapping options like action sets especially for playing games with mixed XInput and mouse controls or with just KB+M mappings.

As it is now, you would probably be better off trying out the PlayStation Controller support in Steam. It is probably the most extensive controller mapping program out there but I find the final output fairly laggy on my system. It also doesn't help that I don't like the Steam Controller support that the program was originally meant for.

**Comment by Bbridgewa** [comment]
Yeah, I thought about doing something where it would attempt to switch profile's on a press of a button, then switch back on the release of that same button. That would give me similar functionality to what I am looking for, but I assumed it would be too slow constantly loading and unloading the profiles.

I admire the work you have done on this project and have been looking over source code out of curiosity. I know C# so maybe I will tinker around a bit and see if can implement what I am looking for on my end. I will let you know if I come up with anything potentially viable.

I'll also check out steam controller support. I was not aware steam allowed custom button mapping!
P.S. How do I access the mode shift modifier? Is it the same as the shift modifier found in the keyboard bind menu?
