### ISSUE TITLE
Assign Gryo functions.

### ISSUE THREAD

**Issue by puckle** [Ryochan7/DS4Windows#48]
Hi,
I wonder if it could be possible to re-assign the gryo functions?
If I select the 'use as mouse' option under the Gryro menu, tilting the controller left and right only works if I hold it with the light bar facing straight up towards the ceiling. 
Would it be possible to have the tilt left and right function work if I'm holding the controller with the light bar facing straight ahead, towards the monitor?  

Thanks again.

**Comment by Ryochan7** [comment]
Gyro mouse mode should work fine with the lightbar facing straight out. I have tested it out again and it works fine on my system. Gyro isn't something that I have played with that much with the DS4 in general. The limited time I have used it has mainly been in Steam. Gyro mouse in Steam is decent but I didn't like it that much; it does work better than gyro mouse mode in DS4Windows though. The gyro mouse mode routine could probably be improved but I don't know if I would end up using it. Having the gyro used for controls on tilting would probably be when I would use the gyro on the DS4. Tilting controls also work with the proper orientation.

**Comment by puckle** [comment]
HI and thanks for the response.
I find that I have to turn the controller like a bus steering wheel when holding the light bar facing out to get any left / right movement.
Possibly I'm doing something wrong, I'll have another play around.

**Comment by Ryochan7** [comment]
It looks like DS4Windows was reading the data for the gyro incorrectly. After changing a few aspects of gyro support, mouse control feels a lot better and, despite needing more work, it is actually usable. Only the "Use as Mouse" option will be edited for the time being so no other functionality that relies on improper data will stop working.

**Comment by Ryochan7** [comment]
Test build with gyro changes. Please be aware that the profile name for the option "Trigger Behavior - Turns Gyro" might change before an official release is made so any change made to that option might not carry over in future releases.

That option controls whether the assigned gyro trigger is used to either enable gyro mouse or temporarily disable gyro mouse. The default is for the trigger to enable gyro mouse. Unchecking that option will cause the gyro to behave like "Always on" is enabled until gyro mouse is disabled by activating the trigger. Personally, I prefer to have the option disabled since I prefer to have the gyro active most of the time.

https://drive.google.com/open?id=0B6yGHDx0CFzDdUxiS2FBZU5nU0E

**Comment by Ryochan7** [comment]
I ended playing through all of Turok using Gyro mouse and it worked out really well. It only took a little time to get used to but I am currently liking gyro aiming over using an analog stick. Since there has been no feedback on the gyro changes and it works well on my end, I am going to close this issue. Thanks for bringing up this issue as I would not have looked into changing the gyro routines otherwise.
