### ISSUE TITLE
Incorrect profiles when reconnecting controller

### ISSUE THREAD

**Issue by Yohoki** [Ryochan7/DS4Windows#480]
I have a controller that is shorting out through the USB plug, so it frequently disconnects and then reconnects. DS4Windows notices these, as shown in logs:

10/29/2018 9:59:21 PM: X360 Controller # 1 unplugged 10/29/2018 9:59:21 PM: Controller 1 was removed or lost connection 10/29/2018 9:59:22 PM: Found Controller:84:17:66:D4:7F:19 (USB) 10/29/2018 9:59:22 PM: Plugging in X360 Controller # 1 10/29/2018 9:59:22 PM: X360 Controller # 1 connected 10/29/2018 9:59:22 PM: Controller 1 is using Profile “Mouse Control"

One major issue is that DS4Windows does not follow "Auto Profiles" rules when reconnecting, and uses the option set under the "Controllers" tab for the chosen controller. In the scenario above, my controller is actually using a profile "Firefox" with special inputs related to browsing the web. When the controller is disconnected the log shows it going back to Profile "Mouse Control" which I have set under the "Controllers" tab to be the default when no other profile is being used. It looks like DS4Windows simply isn't checking what the active window is upon reconnect and adjusting the profile accordingly.

For some applications, this can be solved by Alt+Tab to another program and back. For others, this breaks the controller and requires a program restart. ~~For the absolute worst case scenario, even closing and re-opening the program and DS4Windows will not solve the issue and a full restart of windows is required. (The only program I've run that does this worst case scenario is "Sims 4", and it may just be my wife is computer illiterate and has broken something... I will have to get a log next time it happens, I'm sorry.)~~ Edit: Sims4 issue seems to be fixed in 1.5.15 -"Corrected KB+M action resetting when a device is disconnected"

~~Also, there doesn't seem to be a way to turn down the volume for the notifications that pop up when a controller dis/reconnects... this can get very loud when you have to turn the volume up for quiet videos.~~ After turning off notifications in settings, I cannot recreate this issue when turning them back on. Seems to be fixed in newer updates.

**Comment by mika-n** [comment]
Does the AutoProfile configurations work if you don't check the "link profile/ID" option in Controller screen? Based on the source code the profile linking uses pretty much the same code logic when dS4Win starts and when controllers are hotplugged.  Certainly there may be some corner cases which occur only under certain cirmumstances. 

What do you have in "Start minimized/Minimize in taskbar/close minimizes" settings options? The problem could be related to certain combinations where hotplugging doesnt properly recognize the foreground application name if DS4Win popups during hotplug and that's why it fails to link the correct profile and foreground appname.

The hotplug notification sound is coming from your Windows sound settings. Maybe you could change the notification sound setting there or set it as "empty" (ie. no sound at all).

**Comment by Ryochan7** [comment]
Auto profile rules not being followed upon reconnecting a device has been
brought up before. Unfortunately, the couple of approaches that I tried to
implement to resolve the problem made application performance worse. I will
try some approaches again.

It would be easier if the auto profile system just changed the reference to
the last profile used like the dropdown does rather than keeping track of
the current auto profile being used in temporary variables.

Not sure about the notification sound volume.

**Comment by Yohoki** [comment]
> Does the AutoProfile configurations work if you don't check the "link profile/ID" option in Controller screen?

Autoprofile works the same with or without it set. Shorting cable still drops back to default profile when reconnected. No change.

> What do you have in "Start minimized/Minimize in taskbar/close minimizes" settings options?

I have it set to Start minimized=on, Minimize to taskbar=off, Close minimizes=on. As far as I can tell, nothing pops up or takes focus off the desired program. Leaving DS4Windows open in the background, not minimized, also has no effect.

>  I will try some approaches again. 

Thanks! I'd be glad to test them out. If nothing else, I appreciate the quick reply.

> Not sure about the notification sound volume. 

It seems to be fixed now? I was getting a quiet notification from the system, and then a 2nd loud one from the program saying which profile was being used. I can't seem to make that notification box pop up now. Possibly just an issue with an older version/ Jays2Kings' version.

**Comment by Ryochan7** [comment]
This is unfortunately going to be filed as wontfix. Maybe when I finally get around to implementing a different program then this type of issue would be fixed.

**Comment by Yohoki** [comment]
Update 1.6.13 has fixed my issues and I don't notice any slowdowns. Great work. Whatever you did has fixed it. You can change the "wontfix" label to fixed.
