### ISSUE TITLE
Dead zones for gyro too high when using for steering

### ISSUE THREAD

**Issue by mrdc** [Ryochan7/DS4Windows#489]
Hello!

DS4Windows works fine most of the time I use it. Once I've tried to map gyro to LS for steering and got huge dead zone when tilt left&right: I should tilt DS4 a lot for a car to start steering. I've tried in Forza Horizon 3, Forza Horizon 4 and Forza Motorsport. I've made dead zones in games settings 0 - still no luck: a car drives not precisely at all. BTW when check controller readings in DS4Windows it shows that accel axis is used instead of gyro axis and it stays almost with no move when I tilt DS4.
Any ideas how to lower DS4 gyro dead zones?

**Comment by Ryochan7** [comment]
Besides changing the Sixaxis X dead zone, you will have to edit the dead zone for LS as well. In the mapping routine, LS will have priority over Gryo Tilt controls so using no dead zone on LS will likely cause the LS coordinates to be used rather than gyro. I usually use something like 0.09 for LS.

I am using Gyro Tilt controls to play American Truck Simulator currently and it works great. An anti-dead zone on Sixaxis X and lowering the Sixaxis X max zone were helpful for getting better controls.

**Comment by mrdc** [comment]
> In the mapping routine, LS will have priority over Gryo Tilt controls so using no dead zone on LS will likely cause the LS coordinates to be used rather than gyro.

Thanks, I've unbinded LS first, then have assigned gyro to the X axis.

> An anti-dead zone on Sixaxis X and lowering the Sixaxis X max zone

It helped a lot.

**Comment by Ryochan7** [comment]
I should have posted my settings as a reference.

```
Sixaxis X Dead Zone: 0.04
Sixaxis X Anti-Dead Zone: 0.20
Sixaxis X Max Zone: 0.95
LS Dead Zone: 0.09
LS Anti-Dead Zone: 0.17
```
