### ISSUE TITLE
Bug when controller is disconnected

### ISSUE THREAD

**Issue by extremeGEgaming** [Ryochan7/DS4Windows#49]
When I turn off the controller by holding down the home button, it still remains registered as connected and afterwards it won't connect unless restarting DS4 (it's still connecting to the bluetooth host since the light bar turns white). Also hitting stop while it's still registered as connected causes the app to freeze (it seems to get stuck in a loop?).
P.S. This doesn't happen when the controller disconnects from weak signal.

**Comment by Ryochan7** [comment]
The problem is Windows does not see the controller as disconnected when using that method. DS4Windows attempts to read from the dormant device and Windows never signals that no data can be read from the device. That causes the input thread to hang and that will cause problems later. The Task based async device reader would not have had this problem but creating those tasks bumped up the CPU a lot. I will see if I can find a way around this problem. For now, it would be better to either right click on the Bluetooth icon in the main window or use the Disconnect BT special action to disconnect the controller.

**Comment by Ryochan7** [comment]
A simple timeout method has been implemented. It should be good enough and it does not add any extra lag. It will only be effective with Bluetooth connections.
