### ISSUE TITLE
[Request] Please add NVIDIA IN-GAME to the exclusively Warning

### ISSUE THREAD

**Issue by ParadigmShift101** [Ryochan7/DS4Windows#493]
Please add to the Warning:

"Warning: Could not open DS4 AC:FD:93:8F:69:C7 exclusively. You must quit other applications like Steam, Uplay before activating the 'Hide DS4 Controller' option.""

I spend way to much time searching forums trying to figure out why DS4windows has stopped working again, only to realize NVIDIA has turned on the IN-GAME again.  It gets me every time because the IN-GAME is a service and not an active application.

**Comment by imbalancedzero** [comment]
It might (in fact very likely) require admin rights, but can it be set so that when the Hide DS4 Controller option command runs, it disables the NvContainerLocalSystem service, then once disabled and DS4 is in exclusive mode, that the service is also reenabled again? This would also need to be triggered  after the controller disconnects due to power saving.

I would also expect disabling the Steam service before running the Hide DS4 Controller would also help the success rate of getting into Exclusive mode.

**Comment by imbalancedzero** [comment]
Strangely after the DS4 disconnects and the NvContainerLocalSystem is stopped, exclusive mode fails. I have to remove the Wireless Controller device in Bluetooth Devices and pair the controller again. DS4 is then able to start exclusive mode again.

**Comment by imbalancedzero** [comment]
Ok I feel like I'm spamming but working my way through this....

It seems that stopping the NvContainerLocalSystem service isn't fully required. 

There is an option to disable a setting in the Nvidia In-Game Overlay. If you go to settings when the Overlay is open, choose Stream and untick Play Cooperatively. Exclusive mode will work along with the Nvidia In-Game Overlay.

**Comment by imbalancedzero** [comment]
One final thing...

In Control Panel, Devices and Printers, I right-click Wireless Controller and choose Game controller settings.

From here I have 2 controllers listed. Wireless Controller and Controller (XBOX 360 For Windows).

Then I click Advanced Settings. The preferred device is defaulted to Wireless Controller. If I change this to Controller (XBOX 360 for Windows). It appears I can use DS4Windows in shared mode without the issues I would normally face when using shared mode.

For example, when using shared mode in Forza Horizon 4. I get really weird input issues. Like the controls seem to stick. However when I set the option above. The issue seems to go away.

**Comment by mika-n** [comment]
You could do the "stop X service, stop Y service, Start DS4Windows app, sleep few seconds to give DS4Win enough time to acquire exlustive lock on the controller, Start X service, Start Y Service" type of thing by using a batch file to run DS4Windows. 

"SC stop serviceID" and "SC start serviceID" cmdline commands can be used to start and stop any service you like. Althought you need to run a batch file using elevated priviledges this to work ("Run as Administrator" right-mouse-button Explorer command or a service or taskManager with elevatedPriviledges option set).

DS4Windows doesn't support service option out of the box (at least not yet), but you could use a service wrapper to run any batch file or executable as a service. See http://nssm.cc/ application.
