### ISSUE TITLE
My right controller stick is moving the mouse

### ISSUE THREAD

**Issue by NimishMalla** [Ryochan7/DS4Windows#496]
If I try to use the controller on FIFA, I can move around the menu but the right stick also moves the mouse around.

**Comment by mika-n** [comment]
Make sure you haven't mapped any buttons or axis or touchpad of DS4 controller to "mouse events" in DS4Windows settings. 

Also, some games have an option to move a mouse icon based on controller sticks (for example ETS/ATS games have this kind of option). Don't know about FIFA but would it be case like that? See FIFA controller options and if there is an option to link stick movements as mouse movement.

**Comment by mika-n** [comment]
I have notice one strange thing in Mapping.cs file. There is "MapCustom" function and in there around line# 1651 is a call to calculateFinalMouseMovement function. The strange thing is that this function is always called even when touchpad and all axis are set NOT to move a mouse. If that function for any reason returns non zero values in deltaX/Y variables then MapCustom function eventually move a mouse cursor. Shouldn't there be a check to call this calculateFinalMouseMovement function only if isUsingSAforMouse is TRUE?

I haven't fully analyzed this part of the code but at first it did look to my eye a bit strange piece of code line.

**Comment by Ryochan7** [comment]
That won't work for a common use case of using the right stick for mouse. Other alternative controls are used more rarely for mouse controls but other controls can be bound to mouse. Both tempMouseDeltaX and tempMouseDeltaY should end up being 0.0 if no controls are bound to output mouse events. With that being the case, mouseDeltaX and mouseDeltaY should always return 0 after calculateFinalMouseMovement is called. There is the case of needing to reset the horizontal and vertical mouse remainder values so there is a reason to call the function even if no mouse event should be generated in a poll.

**Comment by Ryochan7** [comment]
I guess Steam is likely the culprit here. Supposedly a recent Steam client update enabled Xbox Controller Support for the controller mapper by default. Since FIFA was likely not launched from Steam then Steam would cause the virtual Xbox 360 controller to use desktop mode bindings. That would help explain the problem. You would have to go into BPM and disable the Xbox Controller Support option in the Steam client.

https://inputmapper.com/forum/inputmapper-1-5-support/1063-ds4-right-joystick-maps-to-mouse-trigger-buttons-are-mouse-buttons-and-more#4947

It looks like this will be a problem going forward for any external mapping program.
