### ISSUE TITLE
DS3 support

### ISSUE THREAD

**Issue by JarnoVgr** [Ryochan7/DS4Windows#5]
The original DS4Windows author didn't want to implement DS3 support because it would be too much work. Are you willing to look into this? ScpToolkit supports it just fine and DS4Windows uses the drivers from ScpToolkit. So maybe there is a possibility.

Why am I requesting this? When I have friends coming over I have to use ScpToolkit so my third controller (DS3) works as well. However, I'd rather use DS4Windows at all situations. Switching between both tools is kinda annoying as well.

**Comment by Ryochan7** [comment]
I don't think that I would go beyond supporting a DS4 controller for this application. Although it would be nice to have a generic DirectInput to XInput controller converter, this code base might not be the best resource for working on that. There are a lot of implicit assumptions in the code and profiles that assume that a DS4 controller is being used with its attributes being taken into account. It goes much further than just the DS4Device class. If something like this were to ever happen, the InputMapper approach would probably be taken with a new application being made based on the work done on DS4Windows.

For now, there has been a need to improve the actual experience of using a DualShock 4 as an XInput controller so that will be where the focus of the application will be.

**Comment by JarnoVgr** [comment]
Understandable. :) Guess it's time to buy a third DS4 controller.

**Comment by Ryochan7** [comment]
Before I had the money to buy a DS4, I had actually worked on a small program to make a DS1 work as an XInput controller. It worked out okay at that time and updates made things better. Other projects like Xiaomi Gamepad and DS4Windows helped with finding out how to interface with the ScpVBus driver. Working on that program is what led me to wanting to help improve DS4Windows. The project has only recently been uploaded to GitHub.

https://github.com/Ryochan7/xinput_scpcontrol_test

One disadvantage to using SDL support instead of HID support in that program is that there is no way to have proper exclusive mode access. The only way around it would be to also use x360ce and use passthrough mode on the emulated controller. On the other hand, the program would work with any gamepad that has a Game Controller mapping for it either in SDL or in an external mapping file; you could also create your own mapping outside of the program. Although mapping capabilities are pretty slim, when using a high poll rate, performance is better than where DS4Windows is now.

**Comment by Ryochan7** [comment]
With the most recent version, DS4Windows performance is pretty close when an action is assigned in a profile. When no actions have been assigned, performance is almost identical to what I had experienced using xinput_scpcontrol_test. There are probably a couple of other tweaks that could be done to improve the performance of the input thread but the major hurdles have been addressed.
