### ISSUE TITLE
Touchpad for aiming

### ISSUE THREAD

**Issue by dovah-kun** [Ryochan7/DS4Windows#501]
Hello

First of all, great job continuing the development for this.

There's an option in the profile settings which lets you use the touchpad as a mouse. This would be a wonderful way to aim during a game, and a much better alternative to using the Right Analog Stick. However, most games require a button (eg: LT) to be held to enter aiming mode, and the option to use the touchpad as a mouse doesnt work when some other button is pressed. I scoured the app to find an option to allow the touchpad to work as a mouse even with another key pressed, but I was not successful.

So is there a way to let the touchpad act as a mouse even with some other button pressed on the controller? 

P.S. I also tried the workaround where I mapped the touchpad (up down left right separately) to the right analog stick, but even though that works, its far too unwieldy and is much worse than actually using the Right Stick

**Comment by Ryochan7** [comment]
As long as a game allows mixed KB+M and XInput controls then using the touchpad along with LT should work fine; testing this out with HTML5 Gamepad Tester shows that it works. There are quite a few games that do not allow mixed controls so you would have to choose between either full gamepad emulation or full KB+M controls; Fallout 4 and Skyrim are two big examples of games that do not work well with mixed controls. This type of problem would actually be bigger problem for people using the Steam Controller. In that situation, I always end up choosing full KB+M  controls because emulated mouse works better for aiming than analog stick aiming in most games.

Due to the layout of the DS4, I don't find it comfortable to use the touchpad in combination with other controls. I use the touchpad mainly for the desktop and navigating menus. Aiming with RS or the Gyro feel better to me.

**Comment by dovah-kun** [comment]
Wow quick response. I was trying to do this on AC: Odyssey. After reading your comment, I tried that HTML5 emulator (and the one in DS4windows) and you're right the trackpad does work with LT pressed. But it doesnt work with the game. 

I see your point though. With LT pressed, even my actual physical mouse doesnt respond inside the game. The control scheme was set to auto switch. I tried changing it to Dualshock4 but that completely disables the touchpad in game. So I guess there is no way to make this happen. It seemed simple at first but now I see it cant be fixed on your end. Is there any other workaround that comes to mind though?

**Comment by Ryochan7** [comment]
I tested this scenario in Half-Life 2 a little later and it worked in that game fine.

There isn't much that can be done. You would have to decide which emulation scheme you want to use. I guess a game like Assassin's Creed would probably work better in full gamepad emulation mode.

With the Steam Controller, there is the compromise of the Touchpad Mouse-like Joystick mode (can't remember the actual name) that allows delta touchpad movement generate joystick events rather than using the current position on the touchpad. I have tried that mode in the past and I never liked it.
