### ISSUE TITLE
Hide DS4 controller does not work reliably 

### ISSUE THREAD

**Issue by Kaan88** [Ryochan7/DS4Windows#502]
DS4 seemingly randomly cannot use exclusive mode, I don't have steam or any other apps open. hidguardian needs to be brought back, ds4 worked wonderfully until this feature was removed. 

I have tried using white knight tool but ds4 cannot see the controller after a reboot, whitelisting it again doesn't work. I had to uninstall hidguardian.

**Comment by Ryochan7** [comment]
Whitelisting has to be done per application launch since PIDs of programs change. Limitations like that is why design changes were made with later versions of HidGuardian so that more useful rules could be made other than relying on an application's current PID. The idea is sound but not so much the implementation.

Based on what I have read, HG v.1 is considered deprecated according to Benjamin. A good replacement is not available at this time though. If HidGuardian 4.x ends up improving then I might reconsider supporting HidGuardian. I am not very hopeful though.

**Comment by Darthagnon** [comment]
Wondering, @Ryochan7, what do you use instead of HidGuardian these days in DS4Windows? Was going to post a suggestion on another project, where there's a problem with hiding controllers.

**Comment by Ryochan7** [comment]
I just use the Exclusive Mode workaround. It works a majority of the time.

**Comment by ceedveed** [comment]
Every version after 1.5.14 does not work with my PS4 controller (windows 10 x64). I'm launching ds4windows using task scheduler with highest privilege. I'm not seeing any controller in the "Controllers" tab of DS4Windows past 1.5.14.

I'm guessing this is due to the change in 1.5.15: "Removed HidGuardian usage and purged extra routines"

**Comment by Ryusennin** [comment]
The controller will stay invisible if you don't uninstall HidGuardian or at least remove the AffectedDevices registry key.

**Comment by ceedveed** [comment]
Thank you so much. I cleared the white list using DS4Windows. Then I uninstalled HIDguardian using the same test installer that ryochan7 posted. 

Now my controller works with the latest version 1.5.17

**Comment by freddyarcade** [comment]
Ryochan7,  you mentioned the "exclusive mode workaround"....what specifically are you referring too?

**Comment by Ryochan7** [comment]
It just refers to the old "Hide DS4 Controller" option. It is a hack that at least works more often than not but there are situations where it definitely cannot work. Another big problem previously was that using the option would potentially permanently disable the DS4 once it was disconnected from Windows. That type of problem was due to a few issues with hotplugging within DS4Windows. The change to hotplug support implemented in October seemed to get rid of the last bit of issues that I have ever encountered with the routine.

**Comment by freddyarcade** [comment]
thanks
freddy

**Comment by Syzard** [comment]
I still don't get why it was removed you can just clear your registry and everthing HID has done was gone. but whatever i mean srsly what can be out of date on a regedit software? jesus christ.

**Comment by Syzard** [comment]
https://github.com/nlp80/irFFB/wiki wheres it out of date the wiki is even nicer than this one.

**Comment by Ryochan7** [comment]
@Syzard keep your posts up bro

> I still don't get why it was removed you can just clear your registry and everthing HID has done was gone. but whatever i mean srsly what can be out of date on a regedit software? jesus christ.

> https://github.com/nlp80/irFFB/wiki wheres it out of date the wiki is even nicer than this one.

The driver has consequences just being installed outside of any registry key updating. My rig is old (late 2012 IIRC) and I can notice degraded performance when the driver is enabled; I have mostly fixed those issues on my end by using extra optimization options when compiling it in Visual Studio. Having even optional support for making the whitelist entry in DS4Windows required using a .NET assembly namespace that caused application slowdown. There was fall out with nefarius over a different issue as well.

I usually either refer to the official HidGuardian documentation on the ViGEm website or just use my own small installer if I want to test vanilla HidGuardian. With the installer, it would just be a matter of clicking next a few times to either install or uninstall HidGuardian. Currently, WhiteKnight would be required to have DS4Windows work with HidGuardian.

Installer: http://23.239.26.40/ds4windows/test/DriverInstaller_Test_20180402.zip
WhiteKnight: https://www.autohotkey.com/boards/viewtopic.php?p=164497

In the end, I don't use HidGuardian regularly and just supporting it made my own DS4Windows experience worse.

**Comment by Ryochan7** [comment]
As an aside, I just double checked the test installer and it does use URLs containing the soon to be expired domain name. The URLs are used to check for version number updates. The current test installer will no longer be functional after January 16th.

**Comment by Ryochan7** [comment]
@Syzard No updated feedback or trolling, huh?

As shown in issue #479 that started this timeline, testing has been done to work around the non-driver issues with the setup. Today I ended up testing integrating the C++/CLI class library in the DS4Windows solution and making some minor tweaks. It would work to my satisfaction and I have the diff backed up if I opted to go with that approach. Like before, DS4Windows would have to be run as the administrator. A way around that problem would be to require an extra executable that DS4Windows would have to launch. That method has not been implemented nor tested.

**Comment by Syzard** [comment]
No i wanted to write but it was garbage sometimes i've issues with english 😂

**Comment by Ryochan7** [comment]
That was a small hassle but the other version works now. The same workarounds were needed even with the second executable approach. More can be done later when I get on my main system.

**Comment by Ryochan7** [comment]
Determine that a try catch block is needed to handle the basic use case of a normal user not allowing execution. 6 hours later.

A revised patch has been made. No decision has been made about what to do next.

**Comment by Ryusennin** [comment]
Personally I need HidGuardian, but WhiteKnight is a cumbersome solution since for every Windows session I need to remember bringing DS4W's window in the foreground and unplug/replug the controller so that Cerberus can properly whitelist it.

Any solution that could eventually bring back the convenient integration of DS4W and HidGuardian would be fondly appreciated.

**Comment by Ryochan7** [comment]
I guess going with the secondary executable approach is the method that will be used. It works fairly well and there seems to be no impact if HidGuardian is not installed. Version 1.6.8 will likely have support for HG v.1 added back in but more testing will need to be done. Despite the current status of HG v.1 support, I should probably give HidCerberus one more try. I am hoping that HidGuardian v.4 will require less of a need for direct integration with HidGuardian via HidVigil.

Here is the current status of updated HidGuardian support. I can post a test build in a bit with the new changes. Even though a normal user will be able to use HG support now, a UAC prompt would pop up when launching the second exe in addition to the UAC prompts that already appear for using exclusive mode.

https://github.com/Ryochan7/DS4Windows/tree/hidguardpropexe
https://github.com/Ryochan7/HidGuardHelper

**Comment by Ryochan7** [comment]
Test build with HG v.1 support

http://23.239.26.40/ds4windows/test/DS4Windows_HG_Test_20190118.zip

**Comment by Ryochan7** [comment]
Updated test build. HidGuardHelper has been updated to ensure that the parent Whitelist key will be written as non-volatile. The PID keys are still written as volatile keys. Having the Whitelist key unintentionally get created as volatile affected HidCerberus functionality and it could have caused problems with other applications that write whitelist entries to the registry.

http://23.239.26.40/ds4windows/test/DS4Windows_HG_Test_20190119.zip

**Comment by Ryochan7** [comment]
Interacting with HidCerberus is pretty easy using its REST API. Unfortunately, enabling checking the status of the service using the ServiceController class causes some major application slowdown. HidCerberus performs about the same as I remember so I would not want to use it myself; based on my experience, just targeting native architectures rather than using the AnyCPU target would greatly improve performance.

It looks like the current plan will still be to run a second program to handle the whitelist entry.

**Comment by fearmear** [comment]
I my case using latest version of Windows 10 (Pro Version 1809 Build 17753.107) I had to kill MicrosoftEdgeCP.exe process first. It launches with Windows system and can be disabled with Group Policy ([guide](https://www.ghacks.net/2018/08/13/block-windows-10-from-preloading-microsoft-edge-on-start/)).
Hope this will be helpful.

**Comment by Ryochan7** [comment]
I have gotten no feedback but I might just end up pushing these changes out later tonight. Both cases, with and without HidGuardian, seem to work out better than the old build. That is especially true for the case when HidGuardian is not used.

The old helper tools will not be available. HidGuardian v.1 is mostly considered defunct and the method to whitelist applications will be different with version 4. There isn't much incentive to add the old links back in and I would not want to have to worry about them possibly changing application performance.

**Comment by Ryochan7** [comment]
HidGuardian version 1 support has been added into the main DS4Windows build again. I am counting this as a temporary measure though. There is no guarantee that support will stay included nor that HidGuardian version 4 will be supported when it gets a stable release. At least this build does not present some of the problems that existed previously. I should also note that I do not use HidGuardian myself.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.6.8/DS4Windows_1.6.8_x64.zip

**Comment by Geroyuni** [comment]
That one works flawlessly for me. I couldn't get your past releases to work with hide ds4 at all but this one didn't give me any issues.

**Comment by madcrow** [comment]
Since I upgraded to Win10 x64, exclusive mode stopped working. I've never had Steam or Uplay installed on this PC. And although I do have an NVidia card, I do not have Geforce Experience installed (I opted out of it during the driver installation). The only components present in my system are the NV graphics driver, NV physx driver and NV HD audio drivers.
And AFAIK, the Overlay is supposed to be a feature of the GeForce experience suite.

Do you know of any other SW which might cause a conflict?

**Comment by Syzard** [comment]
The nvidia overlay causes the issue, aswell the IE can be the reason (yeah ie not edge), also the sound driver of the controller causes this on one system of mine.

On another some windows apps caused it (i'm clueless why tho only thing i can imagine is again the sound driver cuz i cant see anything in windows log or anything, on this other system it was the new movie player) so there are many diffrent things causing it. On my main system i need to start it with the controller already plugged in on a 3.1 usb (only 3.1 the others wont be working on this thing) and if i deconnect it i gotta restart. Where on my labtop i have no problems at all with reconnecting or anything mentioned above.

**Comment by madcrow** [comment]
Thanks for the hints. I'll keep experimenting...
