### ISSUE TITLE
Crashing Forza Horizon 4 at random moments

### ISSUE THREAD

**Issue by SaltyNutella** [Ryochan7/DS4Windows#504]
Hey guys. I tried to play Forza Horizon 4 with ds4.exe and a ds4 controller. The game will always, inevitably crash at some point. It's annoying when it happens during races and stuff. When I said crash, I don't mean the game just shut down. I mean the whole computer becomes unresponsive until I painstakingly go to task manager and end the ds4 process. After ds4 closes, the game returns to normal. Please see this issue thanks!!

**Comment by Ryochan7** [comment]
Instead of killing DS4Windows, can you test this same use case but just disconnect the controller when the error happens instead? I have only experienced something like this with more recent builds of Broforce on Windows 7; it works fine on Windows 10 though. The game will lock up and refuse to load until the controller is disconnected. DS4Windows does pick up the disconnect and Broforce will load as normal from that point. The issue even occurs with older versions of DS4Windows that had been tested as being safe before.

Unfortunately, the issue is likely due to the output driver being used rather than DS4Windows. ScpVBus has not been maintained in years so there would be no luck getting a problem with that driver fixed.
