### ISSUE TITLE
[Notice] Updater Service Will Go Offline March 2019

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#531]
I hesitated bringing up this problem before but a recent email about my domain expiring has shown that the problem will affect others soon enough. My current ryochan7.xyz domain is set to expire January 19th but that won't really matter since DS4Windows and the DS4Updater use the server's IP address instead; I did not have a domain when I took over the DS4Windows project. What will affect others is not having a web host. I have enough money to pay the January payment for my hosting bill but I definitely will not have the money to pay beyond that.

**Comment by Nerdy314159265** [comment]
Could the updater be rewritten to look at Github directly so that you don't need to host anything?

I would think that you could have a file on the Github that lists the latest version and a link to the necessary files to update the program presumably also on Github on the release page or something. Then when the program checks for updates it can open a static link to the raw version of the file check the version number, if it's newer then download the files from the links below.

Do you think that would work?

**Comment by JarnoVgr** [comment]
I fully agree that the best way to go is to verify the GitHub release page and use that for the updater. The GitHub API calls are fairly easy to use.

**Comment by tremendoza** [comment]
Or we could donate 😐....

**Comment by mika-n** [comment]
Or auto-updater is removed and replaced with a simple notification that there is a newer version available (if that option is enabled in settings). People could then follow an URL link to Github release page and download the latest version whenever they want to.

Github already has a static URL link which takes to the latest release: https://github.com/Ryochan7/DS4Windows/releases/latest

The app could use that github "latest" URL (or use github API to do the same in standardized API way), parse the version tag from there and instruct people to navigate to the https://github.com/Ryochan7/DS4Windows/releases URL to download the latest or any other version they want.

I would prefer simple solution and let users to do the installation manually because auto-installer may have sometimes all sort of permission problems.

**Comment by Ryusennin** [comment]
I don't use the updater service. A simple notification would suit me just fine.

**Comment by Ryochan7** [comment]
I agree that changing the updater to rely on GitHub would be best. Technically the GitHub releases API could be used to obtain information about the latest DS4Windows release. I don't think I would want to add an extra assembly dependency for reading JSON files in DS4Windows though. It might be easier just to add the main version file to the DS4Windows repository and have the updater check it instead.

If this is implemented soon then there should be enough of a transition period so that most people won't be affected.

**Comment by Ryochan7** [comment]
I believe that I have everything set up now with DS4Windows and DS4Updater. The updates have been tested and downloading from the new locations works. I also had to copy over the "Virtual Bus Driver.zip" archive.

**Comment by Ryochan7** [comment]
The changes have been tested and a new version of DS4Windows has been released.

**Comment by Ryochan7** [comment]
Update. ryochan7.xyz is now officially dead. I am not going to go through previous issues and update any test build links. Just make sure to note that the server's IP address is 23.239.26.40 and update any links accordingly. For the time being, I will just have to start using Google Drive to host any new test builds.

As for the server itself, I got a few tips which will cover keeping the server online for one more month. No matter what, the server used to host old test builds and the old update files will go offline around March 1, 2019.

**Comment by JarnoVgr** [comment]
Have you looked into AppVeyor for generating builds? (continuous
integration) Lots of open-source projects use it.

**Comment by Ryochan7** [comment]
It has been done. The old server is now offline.

**Comment by Ryochan7** [comment]
This issue is no longer relevant so it can be closed now.
