### ISSUE TITLE
Issues with 1.6.2 build

### ISSUE THREAD

**Issue by vpontin** [Ryochan7/DS4Windows#535]
Hi!

I've updated DS4Windows to latest version, and, consequently, switched from ViGem back to SCP, removing the first following [this steps](https://docs.vigem.org/#!vigem-bus-driver-installation.md).

After that i installed SCP using the DS4W wizard and reconnected my Dualshock, but frustrating for me i cant make it work anymore with Retroarch, PCSX2 or any xinput game.

Although the virtual Xbox controller is listed on `joy.cpl` and is recognized by Retroarch, it doesn't react to any button press in the controller.

Plus i got heavy latency issues after connecting as shown in my log tab.

Here's my Settings tab (exactly same settings i've been using with Vigem builds and they were working fine):

![image](https://user-images.githubusercontent.com/3485505/50573114-c9a7c300-0db4-11e9-838f-a7f7a8928849.png)

About "Hide DS4 Controller" a explaination: i need to check it because i also play F1 Challenge 99-02, an old game supporting DirectInput devices. Instead of the non-rumble "Wireless Controller" i use the virtual "Xbox 360 controller" directinput interface exposed by DS4W [plus this driver](http://lavendy.net/special/driver/xi/index.html), what allows me to use the controller with rumble in that game. Unchecking it makes the game to always choose the Wireless Controller device over the virtual one.

So is those issues problems with SCP or a bug on DS4W? Thanks in advance!

**Comment by tremendoza** [comment]
Ideally you want the DS4 input hidden so that only the virtual X360 controller is seen, so don't worry about the hide ds4 option and leave it on. Your problem is most likely that the DS4 controller is still seen by Retroarch, PCSX2 and given priority over the virtual controller (since HID Guardian support has been dropped) or the virtual controller is not being seen as controller 1, restarting your pc fixes the latter but you'll need WhiteKnight and HID Guardian if your problem is the former. Use the attached file to test the virtual controller and see the numbering.

[XInputTest.zip](https://github.com/Ryochan7/DS4Windows/files/2719464/XInputTest.zip)

**Comment by vpontin** [comment]
Yeah, i dont know what is happening here, but after closing DS4W and waiting a few minutes and try running it again and reconnecting the controles made it work.

I suspect a bluetooth hardware/driver fault here, my laptop is old and started to do wreid things. I hope the parts of my new PC will arrive soon.

Anyway thanks for the support!

**Comment by Ryochan7** [comment]
That is odd. Good thing you got the problem figured out.
