### ISSUE TITLE
[feature request] Disable Gyro output

### ISSUE THREAD

**Issue by Tom-Neverwinter** [Ryochan7/DS4Windows#536]
Many pieces of software I use only accept Direct input mapping. However Gyro is read as a input before any other input can be entered.... (negative X rotation... J0_AXIS3_MIN or other annoying internal names for whatever software it is) making using a Ps4 controller useless, unless one wishes to tediously figure out the named mapping that is used for the controller in the desired software.

Having the simple option to "Disable gyro" would be very very useful, and improve comparability.

**Comment by Ryochan7** [comment]
J0_AXIS3_MIN corresponds to the L2 trigger. Each trigger is mapped to a DirectInput axis in the range of 0 - 65535. It looks like the DirectInput axis midpoint would be 32768 but the triggers are set to 0 when not being used. It looks like the behavior can cause issues with some applications that don't support the DS4 natively or don't make assumptions about axis layout.

This issue is not caused by DS4Windows. The behavior can be seen by using the original DirectInput controller when DS4Windows is not running. It looks like you would have to use the "Hide DS4 Controller" option and use the corresponding DirectInput interface for the virtual Xbox 360 controller. The 360 controller places both triggers on one DirectInput axis which is a bit limiting but it would work around issues like the one you have described.
