### ISSUE TITLE
special actions load profile doesn't seem to be working.

### ISSUE THREAD

**Issue by dudeman972** [Ryochan7/DS4Windows#540]
I can't get the profile toggling to work through special actions at all. I also don't understand the must-have of an unload trigger.

I simply chose a button, followed by the action, this being Load a Profile. Then chose a profile. Let's say I use X for the button, then I expect X to change the chosen profile. It changes nothing at all.

(As for the unload button: If I wanted an unload trigger, can't I just make another special action under the other profile changing back to the first?)

**Comment by Ryochan7** [comment]
I agree it doesn't make much sense for most use cases.

I don't use any special actions outside of DIsconnect BT so I don't get a chance to test those out much. I just tested the Load Profile special action and it does indeed work. The problem is that there is no real verification in the GUI that a profile has switched. The main combobox does not change to the new profile and no log message appears in the Log tab. However, switching from a DInput only profile to an XInput profile and back again shows that the special action is doing its job as the X360 connected and unplugged messages will appear in the log.

Like with auto profiles, DS4Windows loads the profile as a special temp profile instead of just switching the currently active profile shown in the program. It is a weird design decision.

**Comment by Ryochan7** [comment]
Ended up getting lucky this time around and I was able to add some minor log messages to the Load Profile special action. I could not do the same with the auto profile system without adding application slowdown though. At least now there will be some confirmation in the GUI that the profile has temporarily changed.
