### ISSUE TITLE
Cannot connect via bluetooth ( Windows Error code 10)

### ISSUE THREAD

**Issue by 3rasernl** [Ryochan7/DS4Windows#542]
Hello,

When I try to connect my  SONY PS4 dualshock  via bluetooth, ds4Windows does not see the controller. When I use USB everything works fine.

Windows 7
DS4Windows version 1.6.3
No Hidguardian

Reinstalling ds4windows and xbox drivers had no effect. When looking at the properties of the device I see a yellow !
Updating the driver through windows or troubleshoot has no effect.

Does anyone have a fix for me?
![ds4 bt](https://user-images.githubusercontent.com/22075724/50775508-a5595400-1296-11e9-83be-7003760c3777.png)

**Comment by 3rasernl** [comment]
> Can you connect any other BT devices with your laptop/PC?
> If not then somehow your BT stack may be broken. In that case uninstall BT device driver and let Windows Update to re-install the driver or use laptop/PC manufacture's own driver update tool.

Thanks for the reply,

I am able to connect and send files to my phone via bluetooth.

When I remove the wireless controller in "devices and printers", reboot and try to connect my ps4 controller I hear the windows connected sound. I get the message new device connected. Followed within 20 secs by the windows disconnected sound. All this time DS4Windows does not see the controller

**Comment by Ryochan7** [comment]
I would suggest that you just try getting the controller to work outside of DS4Windows first. If Windows recognizes the controller then the DS4 will be exposed as a DirectInput controller; it will be seen in the Device Manager as "HID-compliant game controller". You can check the Game Controller settings window from Devices and Printers and see that Windows can read events from the controller.

You can then try to get the controller to work in DS4Windows. DS4Windows is only needed if you want to use the extra functionality available on the controller (touchpad, gyro, lightbar, etc.) or you play games that only accept input from XInput controllers like the Xbox 360 controller.

**Comment by 3rasernl** [comment]
I found a youtube vid with the same problem. Unfortunately the suggested fix does not work for me.

Is this a driver problem of should I buy the official Sony Wireless Adapter?

https://www.youtube.com/watch?v=N7DUV4T8744

**Comment by mika-n** [comment]
It is a fact that some BT chipsets simply don't support DS4 BT communication. Your BT chipset may be one of those unlucky ones (if you have troubleshooted all driver and BT pairing issues already). SonyWireless BT Adapter works for sure.

**Comment by mika-n** [comment]
If WinOS cannot see the DS4 controller as HID compatible controller then there is no way DS4Windows app helps there. At first the device should be visible as plain DS4 wireless controller in WinOS level. You can test this by running "joy.cpl" control panel applet directly without using DS4Win app or ScpVBus virtual xbox360 driver at all.

 To start from a clean table I would recommend you to try following:
- Make sure HIDGuardian tool is uninstalled if you have ever used it (google for proper uninstallation instructions because it is possible to leave it in "problematic" semi-uninstalled state)
- Uninstall ScpVBus driver
- Uinstall ScpToolkit (ScpToolkit was needed for DS3 controller but it is not needed for DS4 controller)
- Make sure DeviceManager doesn't show any HID devices as disable or in "warning" state
- Reboot the laptop/PC everytime you uinstalled something to make sure driver store is cleaned up
- Make sure PS4 console is turned off (take power cord off to be sure) to make sure that DS4 controller doesn't BT link itself there (or wakeup PS4) before controller tries to BT connect to PC
