### ISSUE TITLE
Controller ID 

### ISSUE THREAD

**Issue by freddyarcade** [Ryochan7/DS4Windows#547]
I have 4 DS4 controllers that are hardwired into specific USB jacks.  
The controllers won't be switched between jacks.  They are locked into their specific jack.
Each controller is for a specific player.
Each player is a specific color that is specified in the profile that is "linked" to a specific profile that turns the controller's lightbar to that color.
Very cool and all working great with DS4Windows.

Now the issue:
I know XINPUT slot#s can change based on the order in which Windows 10 sets up the controllers
when it reboots.  So, I'm trying not to rely on the Xinput slot# being persistent between reboots to identify which controller is pressing a button.

I noticed that DS4 has a four controller IDs on its main controller tab and also that it writes that controller ID out into the XML file that denotes the profile that each controller is linked to it.

Is the controller ID that DS4Windows displays specific to the physical controller? I’m hoping that it is something that DS4windows reads directly from the controller....I found some sources that indicate its a MAC address...Is this correct and is it encoded by manufacturer in the DS4 controllers?  Is it persistent and unique?

If so, then I'm hoping I'm hoping that I can write a script to parse the Controller ID/Mac address from the XML file that DS4 outputs to identify which specific controller is pressing a button.  

I would still need to figure out how to map that controller ID/MAC address to the Xinput slot#.  Any idea how I could do this?

Am I going down the right road?

Thanks again for the help
And DS4Windows is really a great tool 👍

Freddy

**Comment by Ryochan7** [comment]
The controller ID is a MAC address that is specific to each controller. It is read from the controller with the HidLibrary package. The routine used does differ depending whether a USB or BT connection is used.

https://github.com/Ryochan7/DS4Windows/blob/jay/DS4Windows/HidLibrary/HidDevice.cs#L473

As far as I know, the XInput slot associated with a controller is entirely determine by the order which devices are detected. ScpVBus does have a way to specify an index associated within the driver itself but it does not matter outside of ScpVBus. The device enumeration routine would have to be changed to enforce some kind of device order in order to specify specific XInput slots for each controller.

**Comment by Ryochan7** [comment]
On my hardware, device enumeration is fairly consistent using two DS4 controllers and one Sony Wireless Adapter acting as a controller (three controllers exposed total). I would think that the device enumeration routine would depend on the device instance path which would depend on which USB ports are used to connect controllers.

**Comment by freddyarcade** [comment]
And I guess there is no way to know which XInput slot # is associated with which MAC address ?

Reason I'm asking is because Mame identifies the controllers based on XInput slot # .....

Otherwise, I'll just hope enumeration order keeps staying consistent after reboots

Thanks alot and tremendous job with DS4Windows !

I really appreciate the help.

Freddy
