### ISSUE TITLE
pad keeps appearing as player 2?!

### ISSUE THREAD

**Issue by garyneville** [Ryochan7/DS4Windows#557]
I click 'hide wireless controller' and only 1 pad shows up Windows 10 USB Game Controllers.

But when I load up a game (like Rocket League) it is detecting my pad as a second controller, or player 2..!

Any ideas?

**Comment by grimmute** [comment]
I had the same problem once and also with Rocket League, I just restarted my computer and it was fixed. Didn't happen again.

**Comment by garyneville** [comment]
Just leaving this comment in case it helps anyone else. Perhaps I'm too far out of the loop (haven't done much gaming in the past 18 months) - but Steam itself acts as a bluetooth driver for the DS4 pad.

This was the solution that worked for me for Rocket League and other titles, including non-steam games.

Shame because I preferred using DS4Windows for the extra customisation; but I simply couldn't make it work.

**Comment by Ryochan7** [comment]
The Steam controller mapper is probably the most feature filled controller mapper out there. The biggest issue is that actual output performance is quite laggy based on my experience. I don't even use the Steam mapper for my Steam Controller; I prefer the Kozec SC-Controller program for mapping the Steam Controller but that program is only available on Linux for now. The Steam controller mapper is a decent option to try and it might work well enough for most people.

Without much to go on, I am going to assume that the ScpVBus driver is causing the problems that you are experiencing. DS4Windows still depends on that driver to expose an Xbox 360 controller to the system and send gamepad state reports for the virtual controller. It is still my preferred driver but it is quite ancient and has some known issues; I have not experienced an issue like the one you have described in a long time.

Before extra delays were added to some routines, it was possible for ScpVBus to leave an old controller exposed after an unplug routine was called. This was especially true with using BT controllers in Windows 7 because Windows would cause a quick disconnect and reconnect cycle upon connecting a new controller to the system; that quirk can be experienced outside of DS4Windows so it seems to be a real problem with Windows 7. If the problem occurs then you would have to either disable and re-enable the Scp Virtual Bus Driver device in Device Manager or reboot your system.

I guess I would suggest that you connect a BT controller before starting DS4Windows to avoid that type of problem.
