### ISSUE TITLE
Kodi Auto Scroll Bug

### ISSUE THREAD

**Issue by Willi991** [Ryochan7/DS4Windows#558]
If you share Kodi and DS4Windows and have a controller connected, Kodi will go it alone.

The menu just starts to move it just scrolls.

Can one fix that maybe.

Sorry Google Translate

**Comment by Willi991** [comment]
No change

What I noticed when the controller is on and Kodi starts it works quite normal.

If Kodi is running and you connect the controller, you have the automatic scrolling again.

**Comment by Zaazu** [comment]
Hi,

I also had this problem, my solution was to completely uninstall everything and reinstall. Also you need to make sure to install HidGuardian or most applications won't work I've found.

**Comment by Ryochan7** [comment]
I am betting that exclusive access to the DS4 could not be obtained so the original controller is exposed to the system. Kodi is probably using the DirectInput DS4 device rather than the virtual Xbox 360 controller. I will get the latest version of Kodi and try this out.

**Comment by Ryochan7** [comment]
The initial assumption was only half right in regards to Bluetooth controllers. Having both the virtual Xbox 360 controller and DirectInput DS4 exposed does cause Kodi to randomly spam scrolling despite dead zone settings within Kodi. However, the same behavior can be experienced after closing DS4Windows and then launching Kodi. Kodi does not have a problem if the DS4 has just been connected and then Kodi is launched.

With the mode change that DS4Windows performs with BT controllers, the original DirectInput DS4 will be seen as a dead controller if it is still exposed to the system. It looks like Kodi does not handle the dead controller properly and interprets constant input. There is no way to allow the original DirectInput controller to work as expected without first disconnecting and reconnecting the controller and making sure to not run DS4Windows.

Make sure that DS4Windows can obtain exclusive access to the DS4 in order to avoid this type of issue.

**Comment by Willi991** [comment]
Thank you for the info, and how do I use that with the exclusive mode to fix the problem.

**Comment by mika-n** [comment]
Set "Hide DS4 Controller" option in DS4Win options AND you have to make sure that DS4Windows is started before you start Kodi app or background service. This way DS4Win app can acquire and hold exclusive lock on the original HID device and later on Kodi cannot "steal" it.

If you cannot make sure that DS4Win is the first app you start (the same applies to few other apps also) then alternative to use of "Hide DS4 Controller" option is to use 3rd party HidGuardian application to hide the original DS4 controller and just to expose the virtual x360 controller HID device to applications. See other posts in this forum to see instructions how to use HidGuardian (note! It is not part of DS4Win app).
