### ISSUE TITLE
BSOD when controller is connected 

### ISSUE THREAD

**Issue by plainsbison** [Ryochan7/DS4Windows#56]
Hello, I'm on Windows 10 and recently whenever I plug my controller in via USB or connect via Bluetooth, the moment DS4windows recognizes it, I get BSODed with DRIVER_VERIFIER_IOMANAGER_VIOLATION with ScpVBus.sys as the culprit. DS4 controller seems to be fully functional and works perfectly fine with Steam Big Picture still, so I don't believe that to be the problem.

**Comment by Ryochan7** [comment]
Some people have mentioned problems on the ScpToolkit issue tracker as well. Since the problem is with the Scp Virtual Bus driver, there isn't anything that I can do about that. Luckily I have not run into problems myself. Even migrating to ViGEm doesn't seem to be a viable option right now since it has its own stability problems. Unfortunately, if you continuously have this problem then DS4Windows will likely not work out for you unless you only want to use KB+M emulation.

**Comment by araujorm** [comment]
I once had that because of having had installed some other 3rd party tool that left their buggy drivers hanging around even after I uninstalled it (the infamous motioninjoy).

Could that be your case? If so, uninstall it completely and then clear up old ghosted devices.

To clear the ghosted devices I recommend using the open source utility GhostBuster to do it without much effort. Some links that may help:
https://www.raymond.cc/blog/uninstall-hidden-devices-calling-ghostbuster/
https://ghostbuster.codeplex.com/

After that, I'd suggest reinstalling the Scp driver using DS4windows and you should be good to go.

**Comment by araujorm** [comment]
Oh, I just looked better at the error you mentioned... it means you have Windows Driver Verifier turned on. I've ran through this too some time ago.

Driver verifier is a debug/troubleshooting utility that comes with windows and continuously tests every active driver on your system to test for bugs. Obviously, it isn't on by default so either you turned it on to check for something else (you might have seen on a forum and then forgot about it?) or some other utility did it for you. You should turn it off for normal operation, as it hogs your system.

And yes, Scp drivers have bugs and don't pass the driver verifier tests. But alas, since no one is actively maintaining them, and they work for normal operation, no one ever bothered to fix those bugs (at least that I know of).

So turn Driver Verifier and you won't have those blue screens anymore. To do so, you can google for more details, but this will work:

https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/driver-verifier

Quoting:

"To stop or reset Driver Verifier

1. Open a Command Prompt window (Run as administrator) and type verifier to open the Driver Verifier Manager.
2. Select Delete existing settings.
3. Reboot the computer."

Best luck.

**Comment by plainsbison** [comment]
Thank you both for responding! Arajorum, your second solution was exactly what ended up solving this issue. I discovered the fix mere hours ago and failed to update this in time, so apologize that you had to write that out, but I'm deeply appreciative.

**Comment by Ryochan7** [comment]
Thank you for mentioning this. Hopefully people will find that information if they run into this problem in the future.
