### ISSUE TITLE
installed current version on my windows 10 pro clicked on install dswindows driver it appears then goes away... i restarted the computer ... my pc still won't  see my controller..

### ISSUE THREAD

**Issue by thebrazz510** [Ryochan7/DS4Windows#564]

**Comment by MiLL10N** [comment]
+1

**Comment by mika-n** [comment]
What about if you try to download the ScpVBus driver manually and install it before installing DS4Win app? Or in this case you don't have to use DS4Win app to install the driver if you do it yourself.

Link to ScVBus driver installation package: https://github.com/Ryochan7/DS4Windows/tree/jay/extras

**Comment by thebrazz510** [comment]
I did also manually dl the driver still didn't work

**Comment by Ryochan7** [comment]
Installing the driver from DS4Windows works fine on my end. You have to either stop and restart the DS4Windows service routine using the button or restart the program in order to have DS4Windows detect controllers. Anything more than that seems like it is more an issue outside the scope of DS4Windows.

Is the **Scp Virtual Bus Driver** device (under System devices) found in Device Manager? Is the applicable **HID-compliant game controller** marked as disabled in the Device Manager?

**Comment by Ryochan7** [comment]
No longer relevant since the migration to ViGEmBus.
