### ISSUE TITLE
Is Nacon Revolution Controller 2 still usable with latest release?

### ISSUE THREAD

**Issue by MiLL10N** [Ryochan7/DS4Windows#567]
Today I just got this new controller so I plug it to my laptop and its detected controller just fine and I can use windows normal USB game controllers setting to see it working or not and it works fine. Then I open DS4Windows and update the app to the latest version but DS4Windows does not detect Nacon Revo 2.

**Comment by Ryochan7** [comment]
The program does look for the Nacon Revolution Pro Controller 2 while performing device enumeration. I do not own that controller so I cannot provide support for it. That process is up to the community and then pull requests can be made so those changes can be included in DS4Windows.

I am getting conflicting reports from searches so I should ask something. Can you provide the VID and PID combination for your Nacon Revolution Pro Controller 2? You can pull that information from the Device Manager by finding the applicable "HID-compliant game controller" and then check the "Device instance path"; looking at "Hardware Ids" would also present the information. The PID for the controller that is checked has a value of 0x0D02 and the Steam controller mapper database shows that as a valid value. However, other pages show a PID for some controllers to be 0x0602 and that PID is not checked in the current DS4Windows controller database.

**Comment by MiLL10N** [comment]
My Revo 2 VID and PID is

**Comment by MiLL10N** [comment]
My Revo 2 VID and PID is HID\VID_146B&PID_0D02&MI_03&COL01\8&26377BE6&0&0000

**Comment by Ryochan7** [comment]
The computer should not matter for the VID and PID information; the later portion of the Device instance path will likely be different. That information is written to the controller hardware. DS4Windows should be able to detect that version of the controller.

I would normally recommend that you check if the device is still marked as enabled in the Device Manager. You mentioned that it is detected when checking the Game Controller settings window from Devices and Printers so that is not a problem.

**Comment by MiLL10N** [comment]
Somehow it working now on both PC and laptop. VID and PID are the same as when I plugged it to pc. So I think this issue can be closed now. If it happens again I will see device VID and PID and report later.
