### ISSUE TITLE
Serious issue with remapping sticks ever since build 1.4.62

### ISSUE THREAD

**Issue by CorpusBava** [Ryochan7/DS4Windows#577]
Whenever I attempt to do this, it will usually go into repeating mode as if the sticks on the controller are stuck or defective. All other buttons on the DS4 using DS4Windows will re-map will no issues but the analogue sticks are a mess. I know it's not my controllers since Xpadder has no problem whatsoever allowing the analogue sticks to be re-mapped. Is this a common problem? Otherwise this is a brilliant program and i thank the author for continuing to update and maintain it.

Update: Well, I discovered the exact build that this problem first occurred, and every subsequent build after it has this issue right up to v1.6.10. The problem started with DS4Windows v1.4.62. Since I need that ability to re-map the left and right sticks to keyboard keys, I have stopped using all builds after v1.4.61. Hopefully this issue will be fixed someday since i find DS4Windows a valuable app but for the present I'm forced to use older builds closer to the original developer's last builds.

**Comment by Ryochan7** [comment]
It looks like the contributor to the issue is likely related to this message from the 1.4.62 changelog.

> Have sticks mapped to keyboard keys or mouse actions honor dead zone settings assigned in a profile

DS4Windows used to use implicit dead zones in many mapping routines. I removed that detail a long time ago so the profile settings mostly determine whether a control should be considered active or not. There is one main exception regarding stick to mouse event generation which will use an implicit dead zone of around 0.02 (2%) if no explicit dead zone has been set.

XPadder uses an explicit dead zone for sticks set at around 25% by default.

In recent versions of DS4Windows, you need to assign explicit dead zones for LS and RS when mapping to keyboard and mouse actions. The default dead zone setting of 0.0 is only useful when mapping the DS4 to a virtual Xbox 360 controller. Even then, I use modified dead zone and anti-dead zone settings in my profiles when mapping directly to an Xbox 360 controller.

For my KB+M profiles, I usually use something like the following (only posting relevant settings):

```
LS Dead Zone: 0.10
RS Dead Zone: 0.02
RS Max Zone: 0.90
RS Output Curve: Enhanced Precision
```

The low RS Dead Zone setting does allow for some small mouse drift at times in exchange for a looser feeling mouse. You could use a slightly higher dead zone for RS if that is a problem.

**Comment by Ryochan7** [comment]
Here is a copy of the profile that I used when playing Judge Dredd: Dredd vs. Death.

https://drive.google.com/open?id=17QqrAX_qduvVrIdrIKp2j16uwfhGgqlO

**Comment by CorpusBava** [comment]
Thank you!  Setting the dead zones on the stick to Xpadder's 25% fixed one of the two major issues I was having with the latest builds of DS4Windows. No more repeating mode for any keyboard key I assign to sticks.  I just posted about the other problem in its own header.
