### ISSUE TITLE
Question: Discord?

### ISSUE THREAD

**Issue by hydraheim** [Ryochan7/DS4Windows#582]
First and foremost; Thanks for keeping this software updated and more up to speed than the original source. 

Would it be an idea to have a Discord server for DS4Windows to aid in development and testing? It would probably be helpful for many.

**Comment by Ryochan7** [comment]
Although I have a Discord account, I hardly ever use it. Discord has shown its hostility towards right wing politics so I am leery of using it regularly. It really doesn't offer any real functionality for me outside of an IRC server with integrated media hosting.

Apart from that, I don't know how useful a chat server would be for this project. There isn't much activity here and almost all the development is done by me. If there is enough of a demand, I would reconsider.

**Comment by hydraheim** [comment]
You're probably looking at it from the wrong angle; it's not about _you_ per se, it's about getting in touch with the community and getting their feedback. Kids these days use Discord (and have moved on from IRC).

**Comment by mika-n** [comment]
Experiences in other projects has shown that Discord (and similar online chat platforms) are great for chatting but are not that great when providing technical help or discussing about features among people in several different time zones. In Discord people keep asking the same questions because it doesn't have good history or search functionalities to find out if the question has been already answered. And when people are from all around the world +/-12h time zones then "online" discussion is anyway a bit abstract concept.

**Comment by Ryochan7** [comment]
I have some major reservation for most major social media outlets nowadays. My most active account would probably be YouTube and even then my main account is restricted. My dislikes don't count and most of my comments seem to get flagged no matter what I say. My Facebook account is still available but confirmed shadow banned; couldn't get found to receive a wedding invitation. I almost never use that account anyway so that isn't a big loss.

**Comment by Ryochan7** [comment]
It might be a mistake but I guess I will consider this fighting the good fight. Discord server invite link below.

https://discord.gg/zrpPgyN
