### ISSUE TITLE
touchpad remaping it stops working in certain applications

### ISSUE THREAD

**Issue by asp0909** [Ryochan7/DS4Windows#586]
before it worked on emulators like pcsx2 or dolphin, but it does not remap keys for example F1 volume.and keys of keyboard in general on the touchpad no longer do it ... if it goes back to the desktop they return to work normal. in some games it also happens ... in retroarch it works perfect!

**Comment by Ryochan7** [comment]
That sounds like a UAC problem. Some apps that need elevated privileges make actions generated using SendInput not work. That mainly happens with games. Going back to the desktop would allow actions generated via SendInput to work as intended. The only thing that you can do is launch DS4Windows as the Administrator in order to have SendInput work in more situations; UAC popups would still cause virtual mouse and keyboard actions to not work.

**Comment by asp0909** [comment]
you are the genius ... fixed! thank you! your ds4 is the maximum
