### ISSUE TITLE
Max Zone is working for me and while testing a window keeps popping up

### ISSUE THREAD

**Issue by ZimZon767** [Ryochan7/DS4Windows#587]
My issue is pretty basic to the rest in this forum.
The current R2 Button isnt working perfectly so I wanted to change the MaxZone to 0,7 so I only need to press RS2 70% in to get 100% of output, if I understood that correctly. Tried it out in gta but didnt work.
The second problem I have is that when I am testing the RS2 Button in the program, the 'Select an option for R2' keeps popping up when I press R2. But I dont want to change the button, I just want to see the output of the key in the Controller Readings.

Please do remember that I am a peasant and that you guys are experienced in this topic.

**Comment by mika-n** [comment]
> The second problem I have is that when I am testing the RS2 Button in the program, the 'Select an >option for R2' keeps popping up when I press R2. But I dont want to change the button, I just want to see the output of the key in the Controller Readings.

If you have a profile open in EDIT state in DS4Win forms then it behaves like this. Save (or Cancel) editing the profile file and it shouldn't popup the "select an option for R2" message.

**Comment by ZimZon767** [comment]
Ah okay, thank you.

I fixed my main issue, because the option is was hoping to find was the sensitivity and not MaxZone.

**Comment by Ryochan7** [comment]
Max Zone on R2 works for me. Sensitivity is another option that you can use for that purpose. Max Zone would be easier for defining the 100% output mark.

The other issue is likely due to having the **Use Controller x for Mapping and readout** option enabled in a profile when you don't need it.

**Comment by Ryochan7** [comment]
Also, I should mention that the change in Max Zone will not be reflected in the Controller Readings tab. Those widgets only take a few older mapping options into account. Sensitivity for L2 and R2 are taken into account and the output is different in Controller Readings. I have been paranoid to touch those widgets.

You would have to use a different program to see the output from the virtual XInput controller. I usually recommend HTML5 Gamepad Tester but that won't help with L2 and R2 because the program shows the triggers as digital buttons. I ended up testing Max Zone using Xpadder to read the XInput controller.
