### ISSUE TITLE
Recursive mapping not working as expected

### ISSUE THREAD

**Issue by Lombra** [Ryochan7/DS4Windows#59]
Just installed this branch after having experienced the same issue in the original branch.

I have mapped the physical triggers to send output for left stick X. This works. I have then mapped two other physical buttons to send output for the triggers. Pressing these buttons instead go through the previous mapping and also send output for left stick X. I'm assuming and hoping this is not intended!

**Comment by Ryochan7** [comment]
There is no recursive mapping functionality. In that mapping, the button should be sending out LT and RT values. The buttons would not be sending out stick axes values in that mapping. Can you post your profile so I can check the behavior on my system? I have tried to duplicate the mapping on my end and it works as expected. One thing to note is that you cannot have the stick directions mapped to the stick otherwise you will have conflicting values.

**Comment by Lombra** [comment]
Seems to be related to Steam input. It was for a DS4W profile I had set up to be applied when launching one of my Steam games. Works as expected once I disable Xbox configuration support in Steam.

Here is the profile, anyway.
[Spintires.txt](https://github.com/Ryochan7/DS4Windows/files/1065806/Spintires.txt)

**Comment by pedrovay2003** [comment]
I believe this may be related to an issue that I posted, also only occurring when Steam is launched:

https://github.com/Ryochan7/DS4Windows/issues/64

I'll attach my profile here, as well, if it helps, but I didn't customize nearly as much.

[Default.txt](https://github.com/Ryochan7/DS4Windows/files/1076304/Default.txt)
