### ISSUE TITLE
White blinking light and having to pair everytime I reset/power up the machine.

### ISSUE THREAD

**Issue by tokidensetsu** [Ryochan7/DS4Windows#590]
Everytime the controller powers off, either by timeout or by shutting down the machine, when I try to power it up again, it simply blinks the led white a random number of times and DS4 never connects to it.
I have to unpair the controller completelly and pair it again from scratch.
Windows 10.

**Comment by mika-n** [comment]
So, you are using BT connection instead of USB. 

Does the same thing happen to the controller without DS4Win app (ie. in WinOS level)? Is WinOS capable to find the device again after the controller was shutdown? You can verify this via gameapd ControlPanel options or using some other app which supports DS4 controller natively. The first step is to make sure that WinOS doesn't mess up with the BT pairing because if it does then DS4Win app cannot help there.

When this happens then make sure that DeviceManager didn't leave any of the HID devices in disabled state (open Win DeviceManager and take a look at list of HID devices/Controllers).

If you restart DS4Windows application then what it shows in its Logs option screen when this happens?

**Comment by tokidensetsu** [comment]
Solved the issue by installing the DS4 driver in safe mode and restarting after.
Seems that the "SCP" drivers from the toolkit (the one I've used before) didn't get removed when I unistalled it and were causing conflicts.

**Comment by Ryochan7** [comment]
I always made Restore Points when I tested ScpToolkit. ScpToolkit and the forked ScpVBus used have been deprecated for a while. As far as I know, progress is being made on an alternative to the whole toolkit but all the pieces have not been made yet.

**Comment by Bugelnoiz** [comment]
Hi there. I have the exact problem. Have tried to install and uninstall drivers. And tried to update my bluetooth with no change. Also tried to install in safe mode. I did had the jay2king version installed and erased everything with Scpdriver. Any suggestions to get my ds4 to reconnect after shutdown?

**Comment by mika-n** [comment]
> I did had the jay2king version installed and erased everything with Scpdriver. Any suggestions to get >my ds4 to reconnect after shutdown?

Double check that the old version of ScpToolkit is really uninstalled. https://github.com/nefarius/ScpToolkit/wiki/Manual-driver-removal

When the controller shutoff and doesn't reconnect again then at that point check the DeviceManager and make sure there are no HID (Human Interface Devices) devices in disabled state. Plug and un-plug the controller and try to see if this list of HID devices is updated and the new devices appears there.

See the following Wiki page for tips about potentially problematic apps with exclusive access (Hide DS4 Controller option in DS4Win options screen). For example there has been reports that Windows Store app may hold a handle to HID device even when DS4 controller is disconnected (I think that issue was with Sony Wireless Adapter because it has a weird way of acting like a controller even when the actual DS4 Controller is not connected).
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
