### ISSUE TITLE
Steam not detecting controller if ds4windows is open

### ISSUE THREAD

**Issue by powerpuffboysz** [Ryochan7/DS4Windows#593]
ds4windows works great if I'm emulating a 360 controller but if I use profiles and autoprofiles to temporarily disable the 360 emulation steam does not recognize it. it recognizes it just fine if a 360 pad is being emulated but I have to completely close down ds4windows and disconnect and reconnect the controller for steam to be able to see it as a normal ds4 controller for games that support it natively because I like seeing playstation button prompts if I have the option. its a v2 over Bluetooth btw

**Comment by Ryochan7** [comment]
I believe a DS4 opened from Steam's controller mapper suffers the same problem but I will double check. This issue is a side effect of the mode change used to gain access to the additional features of the DS4 not exposed from DirectInput (touchpad, gyro, lightbar, rumble). The original DirectInput controller will still be seen by the system when not using exclusive mode but it will be seen as a dead controller. This problem only affects Bluetooth connected controllers.

**Comment by Ryochan7** [comment]
I have confirmed that Steam works the same way.

**Comment by Ryochan7** [comment]
Unfortunately, this is standard behavior that you have to be aware of when using the DS4 outside of DirectInput. It would be nice to have DS4 mapping support in DS4Windows so button prompts would match the controller. The thing is that ViGEmBus support would have to be included first.
