### ISSUE TITLE
Ds4 windows 10 multiple controllers

### ISSUE THREAD

**Issue by David-hod** [Ryochan7/DS4Windows#600]
when connecting the cable to ds4 it creates on
Control Panel\Hardware and Sound\Devices and Printers
a new device _wireless controller_ after installing the ds4 driver it creates a device 
_xbox 360 controller for windows_
when starting apex legends, it seems like apex legends use the default driver i.e. _wireless controller_ and not using ds4 device.
which means that any changes to a profile does not affect in game.

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by Ryochan7** [comment]
It looks like you will have to make sure exclusive access to the DS4 can be obtained. That can be done using the old "Hide DS4 Controller" option or by using HidGuardian.

**Comment by David-hod** [comment]
I saw on the logs "Using exclusive mode", but now     when connecting the ds4 to the pc it is not recognized at all by the application.

**Comment by mika-n** [comment]
Is DS4 controller recognized by Windows OS? If not then check Device Manager and make sure that there are no HID device entries in disabled state.

Anyway. Try to get WinOS to recognize the controller as HID device at first because if WinOS cannot do it then DS4Win application cannot do it either.

I guess you are NOT using HIDGuardian tool? If you are then there is no need to use both exclusiveMode and HidGuardian tool at the same time. If you are using HIDGuardian tool then check HIDGuardian documentation how certain devices and applications are white listed.

**Comment by Ryochan7** [comment]
Closing due to lack of feedback
