### ISSUE TITLE
V2 BT polling rate can't be changed

### ISSUE THREAD

**Issue by nsmvykonqd** [Ryochan7/DS4Windows#603]
just got a v2 after my original dies. The input delay is around 4ms no matter what poll rate i set(low or high). Also it have squared stick mapped by default. Is it working as intended or just my unit is faulty?

**Comment by Ryusennin** [comment]
/off topic

I'm curious, what can be the practical use for a square sensitivity on PC? Compatibility with old DInput games/emulators? I believe the last controller that used square sticks was the DS3.

**Comment by Ryochan7** [comment]
I don't have a use case for it. The feature was requested since other applications, like Durazno, have the option. Steam also has this type of option available for analog sticks. I would assume that the feature might be useful for some DirectInput games.

**Comment by nsmvykonqd** [comment]
thanks for the reply. i tried saving and reconnecting but still no luck even on another pc. And on a fresh profile the stick can still somehow reach the corner of input. My old v1 didn't have both of these problem so i guess it's a v2 thing. I'll get a replacement and see.
the square stick can reach max value of both axis at the same time, which may enable you move and turn faster? i heard some people use ds3 to play Rocket league because of this.

**Comment by Ryochan7** [comment]
I have tested a fresh install against my version 2 and DS4Windows is working as expected. Before you write off the controller as defective, you should check the behavior of the original DirectInput controller without running DS4Windows. My main test application is HTML5 Gamepad Tester but it looks like a recent update messed it up a bit. Axis index numbers don't show up anymore. You can check if the analog stick is mapped to square output from there. You can check the first two boxes in the second row to see the output from LS.

https://html5gamepad.com/

![gamepad_test_20190312](https://user-images.githubusercontent.com/581968/54197409-d79f5180-4491-11e9-94c5-e0fa18fc998e.png)

Out of the controllers that I have used in the past, I remember the Logitech F310 having square output for the analog sticks. That was one reason I didn't like using it; the hardware stick dead zone was a much worse problem though. I ended up having to code a square stick input to circle output routine in a previous piece of software in order to get a better experience using the Logitech F310.

**Comment by Ryochan7** [comment]
Also, can you share the profile that you are using when you get squared output for the analog sticks?

**Comment by nsmvykonqd** [comment]
I think the unit is indeed defective as the replacement works perfectly fine. The profile I used is a new one from fresh install so nothing could go wrong there. Thanks for your reply, i really appreciate your work.
