### ISSUE TITLE
devil may cry 5 not working with DS4Windows

### ISSUE THREAD

**Issue by fersnake** [Ryochan7/DS4Windows#604]
i just try this game and what i found was it doesnt work when ds4windows is loaded, try to hide the controller, stop it the app with no luck it really needs to be completly shutdown in order to work with steam already configured to detect the ds4 controller. not really a big issue to me but just wanna know if it could be a fix or an explanation cuz i really dont like having this issue i cant fix on my mind xD.

**Comment by Ryusennin** [comment]
Have you tried disabling controller support in Steam? You don't need it as it will conflict with DS4W.

**Comment by Ryochan7** [comment]
> ...in order to work with steam already configured to detect the ds4 controller.

You cannot use Steam's PlayStation Configuration Support and DS4Windows at the same time. Also, I don't have DMC 5 but the previous spinoff title DmC had support for DirectInput and XInput controller support. You will likely need to make sure that DS4Windows can obtain exclusive access to the DS4 in order to not run into double input or HUD problems.

**Comment by fersnake** [comment]
thanks guys, yes i had to do that.
