### ISSUE TITLE
[Suggestion] Auto-profile option to disable Exclusive mode temporarily?

### ISSUE THREAD

**Issue by reecespieces** [Ryochan7/DS4Windows#605]
In the Auto-profile options, there is an option to temporarily disable DS4Windows.

I was wondering if another option could be added to temporarily disable exclusive mode (Hide DS4)??

Basically I want my default profile to hide the DS4 device, but when loading a certain program have auto-profile temporarily override the "hide DS4" setting and show both the DS4 and Xinput devices. 

------

Why? Well when I launch RPCS3 (PS3 Emulator), I want to have both the DS4 and Xinput devices. I'll set RPCS3 to only use the DS4 device, and I'll use the Xinput device to control Steam Big Picture (and Steam won't even recognize the input from the DS4 Device) 

I don't want to permanently have "hide DS4" disabled because then I'll get double input when playing PC games where I want to only use Xinput.

-----

(ignore the renaming and closing and re-opening I did)

**Comment by Ryochan7** [comment]
This is likely not feasible thanks to the behavior of the DS4 when using Bluetooth. After opening the DS4 in DS4Windows, the original DirectInput controller will be seen as a dead controller until the controller is disconnected from Windows and then reconnected. That behavior also happens with Steam when using its PlayStation Configuration support.

For a controller connected via USB or the Sony dongle, the issue would be a matter of closing the underlying HID device and then re-opening it in Shared mode. I have never tried to test that. The current code might be able to pull that off without changing too much.

Because Bluetooth is the most popular connection type for using the DS4, this type of feature is likely not worth worrying about. It is definitely impossible with Bluetooth.

**Comment by reecespieces** [comment]
Bummer.


I guess I'll have to hope that the RPCS3 team will add a way to quit the emulator using their Dualshock 4 handler.

**Comment by mika-n** [comment]
Using HidGuardian to hide the original controller instead of exclusive mode of DS4Win app might be one way to do what you want. However, it would require you (or someone else needing this kind of functionality) to program a little tool or script to modify the white listed apps of HidGuardian filter driver on the fly.
