### ISSUE TITLE
FIFA 19 cant reconnect ingame

### ISSUE THREAD

**Issue by egz12** [Ryochan7/DS4Windows#608]
hey,

when i'm playing weekend league in fifa 19 and if there is a connection cut happens its not reconnecting well and i'm just closing game with emotion of angry. can't you fix that? i believe there is so much people using this for fifa

**Comment by mika-n** [comment]
Please be a bit more specific because the issue description doesn't give much detail info. 
What version of DS4Win app? 
USB or Bluetooth (BT) connectivity? 
If you use BT then are you using some BT dongle/adapter or Sony Wireless Adapter or built-in BT in your laptop/PC?
What do you see in DS4Win logs screen?
Is the controller lost from Windows OS level also or just in FIFA game/DS4Win app when this happens? 
If you leave the controller connected in PC and try to use FIFA or some other game directly as DS4 controller (ie. without DS4Win app) then do you see the same disconnection? Or do you experience this disconnection event only when DS4Win app is running?
Are other apps/games able to re-connect the controller during in-game session? If, so then it may be a problem in FIFA19 and nothing can be done except asking EA to fix their game.

**Comment by Ryochan7** [comment]
It has been a while since I tested the demo but I think that FIFA 19 does not allow the normal Hide DS4 Controller routine to work. The game always grabs controller access first. The game will end up using the original DirectInput controller as the primary input device causing button mappings to be wrong and HUD issues. The only known way around the problem would be to install and configure HidGuardian so FIFA 19 will not be able to see the original DirectInput controller at all. The only other alternative is the rage inducing action of being forced to close the game and restart.

https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian---Install-and-Setup-Guide

**Comment by mika-n** [comment]
Jep. FIFA19 hijacks the original "Wireless Controller" HID device as soon as the controller is re-connected if the FIFA game is already running. Therefore DS4Win cannot hide it anymore via exclusive mode option. After this FIFA goes crazy because of double inputs. The strange thing is that FIFA doesn't natively support DS4 controller, so why it hijacks a controller it doesn't use? EA stupidity.

**Comment by Ryochan7** [comment]
Downloaded the demo again and I have confirmed that exclusive mode will not work while FIFA 19 is running. Removing some of the safeguard delays did not help either. It looks like HidGuardian would be required to make it work.

**Comment by egz12** [comment]
what should i do? my mind confused

**Comment by egz12** [comment]
i have to download whole things right there? it will work?

https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian---Install-and-Setup-Guide

**Comment by mika-n** [comment]
> what should i do? my mind confused

Either ask EA to fix the problem of hijacking a controller device it doesn't use.

Or install HidGuardian tool and use it to hide the original controller from FIFA game instead of using ExclusiveMode in DS4Win app. Follow the instructions in the Wiki page to install HidGuardian. Those instructions are a bit old but the main parts are still valid (ie. what to download and how to install HidGuardian device driver).

**Comment by egz12** [comment]
i can install that but it will work or not?

i just used it on ds4win app now. i was playing fifa 19 ultimate team and we cant go back to windows when we ingame. so my controller disconnected cause of battery or smth. i just tried to reconnect it again and it reconnected. but the main problem is, controls are changed again. its happened like my shoot, pass, and other buttons changed to upside like L1, L2, R1, R2. when i press my normal buttons it was working like that left controller. let me explain you with a screenshot

https://vgy.me/a94Seg.jpg

**Comment by Ryochan7** [comment]
Installing HidGuardian is the only way around the problem. Using the driver should help guarantee that FIFA 19 will not see the DirectInput controller so DS4Windows will be able to obtain exclusive access to the DS4. FIFA 19 should only ever see the virtual Xbox 360 controller if HidGuardian is working. Here is a link to the current test installer.

https://drive.google.com/open?id=1pHLtOeD_Qfo3nt9Pa3jYWo5cc5C3iuGk

Maybe I should make a dedicated program for installing HidGuardian rather than relying on the old combined ViGEmBus and HidGuardian installer.
