### ISSUE TITLE
PS4 controller is detected as dummy "Wireless controller", not as an Xbox 360 one.

### ISSUE THREAD

**Issue by DavidG777** [Ryochan7/DS4Windows#620]
I'm using the latest version and pulling my hair out trying to get it to work.
Everything in the app is fine, no errors, controller shows up in the app normally and is configurable.
Here's the log:
3/21/2019 7:20:06 PM: DS4Windows version 1.7.0
3/21/2019 7:20:06 PM: Starting...
3/21/2019 7:20:06 PM: Connection to ViGEmBus established
3/21/2019 7:20:06 PM: Searching for controllers...
3/21/2019 7:20:06 PM: Using Exclusive Mode
3/21/2019 7:20:10 PM: Found Controller:28:C1:3C:54:04:D9 (BT)
3/21/2019 7:20:10 PM: Controller 1 is using Profile “Default"

But on Windows control panel, it only shows up as Wireless Controller:
https://i.imgur.com/TgmmTS3.png

If I check Game Controller settings, it'll show up as Wireless Controller that doesn't work in case I have Hide DS4 Controller off, and if I turn that on, then it straight up won't show anything at all, despite the controller being connected and detected by the DS4Windows app:
https://i.imgur.com/rk14laC.png

The controller is an official Dualshock 4, latest model with the lightbar in front.
What's the issue here?

EDIT: BTW, on the configuration/controller readings part of the app, the controller works fine, every input works fine, even in exclusive mode. It's just Windows 10 that refuses to see the Xbox 360 controller, no matter what. Please help me this is infuriating

**Comment by InstallGentoo11** [comment]
Did you install the 360 driver too? Did you restart the PC? "Wireless controller" is normal to show up, though also it should show up a 360 icon too.
Trying with to make it work with the USB cable before jumping to BT might be preferable. What happens if you connect it with the cable?

**Comment by DavidG777** [comment]
I'm using Windows 10, so 360 driver shouldn't be needed, but I installed it anyway, no difference.
No difference using BT or USB, same thing happens.

**Comment by InstallGentoo11** [comment]
Have you used DS4Windows before? If so, maybe you installed HidGuardian back then?

**Comment by DavidG777** [comment]
I used it but I don't remember installing HidGuardian. How do I check?

**Comment by InstallGentoo11** [comment]
The Device Manager under System Devices. It will say HidGuard Virtual Device. If you do have left installed use this guide to uninstall it. It is a bit stubborn and it requires a bit more than normal.
https://docs.vigem.org/#!hidguardian-v1-installation.md#Driver_removal

**Comment by DavidG777** [comment]
Hmm, no such device in my device manager, I don't think it's installed.
Thanks for the help, but I'm still clueless.

**Comment by Ryochan7** [comment]
Did you have the ViGEmBus driver installed prior to using DS4Windows? Which version of the ViGEmBus driver are you using? I only support people using version 1.14.3.0. I cannot guarantee compatibility with any older versions of ViGEmBus.

**Comment by mika-n** [comment]
If you have "Use DInput only" checkbox option set in a profile with "Hide DS4 Option" then result would be exactly what you described (I happened to run into the same issue and I was wonder why my virtual x360 doesn't show up until I realized I had played around with UseDInputOnly option and forgot it there).

- If DS4Windows is not running then the normal "Wireless Controller" (=native DS4 directinput device) gamepad is shown in JOY.CPL controlPanel applet (you can run "joy.cpl" command to open the gamepad controlPanel applet).
- When you launch DS4Win with both UseDInputOnly and HideDS4Controller options set then DS4Win app will hide the native "Wireless Controller" device and it is no longer available in joy.cpl device list. But because of UseDInputOnly option DS4Windows won't create a virtual x360 gamepad controller device so you end up without gamepad controllers.

So, please make sure your profiles don't have "Use DInput only" option set.

**Comment by qtbear** [comment]
Thank you @mika-n I've spent several hours getting this to work. I might have been able to save all this time by just not using "Use DInput only"

**Comment by DavidG777** [comment]
Oh my god @mika-n 
Thank you so much!

**Comment by Ryochan7** [comment]
I cannot remember when it was fixed but there was a bug when switching profiles that accidentally changed the profile option for Use DInput Only instead of the runtime value. Use Dinput Only has two main uses. The first is for temporarily disabling DS4Windows support for games that have native support for the DS4; that functionality is not available when using a Bluetooth connection though.

The other main reason is when emulating KB+M actions and a game has issues when it detects a controller. In my experience, Warhammer 40K: Space Marine throttled the mouse sensitivity when a controller was detected by the game so Use DInput Only was used to not expose that virtual controller and allow much higher camera speed than what was possible before.
