### ISSUE TITLE
Not working with Sekiro.

### ISSUE THREAD

**Issue by Swordsage** [Ryochan7/DS4Windows#622]
The program doesn't seem to work with Sekiro. I tried hiding the controller, resetting Steam, resetting the PC, and still not able to get DS4 WIndows and Sekiro to get along. Thought there might be a conflict with a DirectInput and XInput controller support file in the game folder, but those aren't in there. Looking forward to a fix.

**Comment by InstallGentoo11** [comment]
No problem here. Make sure you install the new driver and restart the PC after the 1.7.0 update.

**Comment by Swordsage** [comment]
Not sure what I'm doing wrong. I made sure I got the new version, updated the driver, and restarted my PC 3 times. Still not working. I'm not sure if maybe Steam is getting in the way somehow? I do notice that it treats my touchpad like a mouse, even though I specifically set it to not see my controller, even going into the settings for Sekiro and set the Steam input per game to "Forced Off". I don't have this problem with Dark Soul's 3, so I'm not sure what's going on now.

**Comment by InstallGentoo11** [comment]
I saw a few other people to mention they have problems on a certain site, though they didn't say exactly what they were using. The only that did said he was using an xbox360 controller. Some guy with a random ass Chinese controller said he had no problems at all. On the Steam forums I found this thread https://steamcommunity.com/app/814380/discussions/0/1850323802572872991/
But it is often hard to  understand if people are doing something wrong or maybe the game is just screwed up somehow. So far it doesn't seem like you are doing anything wrong. I don't use the Steam controller support at all, though.  You sure it is completely turned off? Or maybe the fact you turned it off has fucked it up? I really would suggest not using it at all.

**Comment by aef8234** [comment]
Yeah I think the problem might just be Sekiro itself instead of steam or DS4Windows, remapping to keyboard inputs still won't let the game read it, even if it works everywhere else.

**Comment by Ryochan7** [comment]
There have been a ton of controller problems brought up on the Steam forums for Sekiro. Even real Xbox 360 and Xbox One controllers don't work in the game for a lot of people. My PC does not meet the minimum system requirements for Sekiro so I could not test it even if I could afford it.

https://steamcommunity.com/app/814380/discussions/0/1850323802572872991/

One thing that you definitely have to make sure of is that Exclusive Mode has to be working. You can either attempt to use the "Hide DS4 Controller" option or use HidGuardian to hide the original DirectInput controller. The user artic- on the Discord server posted a script for killing ShadowPlay before launching DS4Windows since ShadowPlay was causing exclusive mode to constantly fail. Here is a link to the script.

https://cdn.discordapp.com/attachments/549028012323241993/558515179864850434/DS4Windows-Start.cmd

**Comment by dem0z** [comment]
Only worked when i used Hide DS4, Otherwise it doesn't detect it all.

**Comment by aef8234** [comment]
I think I found out a potential source of the problem, Hide DS4 might hide DS4, but it doesn't hide the sound drivers for the DS4, which the game still picks up as a seperate controller.

The fix for this is by disabling the HID-compliant drivers one by one (while undisabling any drivers that are actually important) until you find the "sound drivers."

**Comment by nossr50** [comment]
Hide DS4 fixed it for me, you guys will probably also want to turn Vsync from application controlled to fast in nvidia settings if you have a gsync display

**Comment by SalahAdDin** [comment]
Well, it does not fix my proble, i have "Hide DS4 Controller" by default, and it does not work.

**Comment by Ryochan7** [comment]
The option might be enabled but you need to check if DS4Windows could actually get exclusive access to the controller. A warning message in the Log tab, and possibly a message in the bottom of the window if it is the last message, will appear if DS4Windows failed to open the controller with exclusive access. There are many pieces of software that are being discovered that can cause the old exclusive mode hack to fail.

**Comment by SalahAdDin** [comment]
Well, i reinstalled the new driver, and after that i did reboot to the computer, finally it works.
Thanks.

**Comment by SalahAdDin** [comment]
Well, i have the same problem again, Sekiro does not recognize the controller.
