### ISSUE TITLE
Some Problems

### ISSUE THREAD

**Issue by SiTWulf** [Ryochan7/DS4Windows#623]
Hi @Ryochan7 
Im a old user of your fantastic tool... but i stay in the old version 1.5.14 and works like a charm... not problems with "Exclusive Mode" always is Exclusive Mode and not problems.

I have two folders with the old version 1.5.14 and another folder with 1.7.1

But today i install the version 1.7.1 and now the problems come, i cant get the "Exclusive Mode" working again... trying to downgrade again to 1.5.14 and not work

I lost the working Exclusive Mode

Warning: Could not open DS4 90:FB:A6:CD:3D:CC exclusively. You must quit other applications like UWP apps (Netflix), Steam, Uplay, NVIDIA IN-GAME before activating the 'Hide DS4 Controller' option. For more info check https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

More info:
DSWindows 1.5.14
HIDGuardian: InputMapper HidGuardian.exe
Not opened any problems like UWP, Netflix, Steam or Uplay.
Nvidia Installed

**Comment by SiTWulf** [comment]
I try to use "HidGuardian Test Installer" and Install of HidGuardian Fails

**Comment by SiTWulf** [comment]
Ok, looks fixed for now...

I need to unsintall everything, HidGuardian and ViGEmBus removing using the HidGuardian Test Installer, and remove FileRepository HidGuardian and ViGEmBus files and restart windows.

After the restart install all again using the same tool and works like a charm, now the Exclusive Mode works again in the lastest version 1.7.1

**Comment by InstallGentoo11** [comment]
HIDGuardian support was dropped, because it was not needed in any way any more, and having it will only make things not work.

**Comment by Ryochan7** [comment]
The old test installer does not delete the driver store copy from the system. I did not know how to access and delete the driver store copy when I made that program. I only recently found out which calls are necessary to delete the driver store copy of the driver when I made the temporary ViGEmBus installer that DS4Windows now uses. Maybe I will get around to updating the HidGuardian Test Installer to delete the driver store copy.

The prior removal of HidGuardian support was partially due to performance concerns but some of it was due to drama happening at the time. Luckily both of those issues have been dealt with. The approach being used in DS4Windows now does not affect performance for people not using the driver; the underlying problem was due to .NET assemblies being used. I don't use HidGuardian on a regular basis but I do pay attention to the status of the project. Maybe I will attempt to contribute to the ViGEm project again in the future.

**Comment by Ryusennin** [comment]
@InstallGentoo11 

HidGuardian is definitely needed by many people, as it's by far the better solution to get exclusive access to the controller. Just look at the forum.

"having HidGuardian will only make things not work"

What? You're actually confusing people with that kind of statement.

**Comment by Ryochan7** [comment]
HidGuardian has its problem but it has proven to be very useful. I am just a stickler for performance and a filter driver will likely always have some small latency associated with it. The version I have tweaked on my system is very close to native performance but I bet that there is more that can be changed that I don't know about. HidGuardian is charting new territory and it is a work in progress.

More direct support for HidGuardian in DS4Windows might be included around the time version 4 goes stable. HG v.1 support is mostly discouraged, even by Nefarius, unless a user deems it necessary. Version 4 will work differently than HG v.1 does.

**Comment by SiTWulf** [comment]
For uninstall FileStorage files i use the tool named: [Driver Store Explorer](https://github.com/lostindark/DriverStoreExplorer).
I try using a Admin CMD with not luck, access denied... but with the tool works.

**Comment by Ryochan7** [comment]
I made a small update to the test installer. It now deletes the driver store copy of the drivers during the uninstall process. Also, the ViGEmBus portion has been tested again and is confirmed to work.

https://drive.google.com/open?id=1hs6AgM6yLeyr3htP9kY0T4N2vklRI2s9

**Comment by SiTWulf** [comment]
@Ryochan7 Any new update for this driver test installer?
Is really the best thing!

**Comment by Ryochan7** [comment]
The old code was pretty much split into two separate projects. The ViGEm portion is not needed anymore due to the availability of the official ViGEm installer from Nefarius. There is still an unofficial HidGuardian installer that is a bit better than the old HidGuardian installer routine.

HidGuardianInstaller_20191218.zip:
https://drive.google.com/file/d/1PNL3uv_4KektN00S9fm61djypSQ-3HED/view?usp=sharing
