### ISSUE TITLE
camera spinning sekiro

### ISSUE THREAD

**Issue by holala02** [Ryochan7/DS4Windows#629]
hello guys

when i plug the controller (just i plug it) the game start to spinning x) and the jump bouton is not enable oO i think wrong driver or something turn in background, is there any solution or upgrade for DS4Windows

thank you

**Comment by mika-n** [comment]
Maybe you need to add deadzone to left and right stick? Those analog sticks are never completely stable, so those need a small deadzone to avoid constantly sending some "movements" to a game.

**Comment by Ryochan7** [comment]
Exclusive mode has to be working to play Sekiro. You can attempt to use the older "Hide DS4 Controller" option or install HidGuardian to hide the original controller from the game. A message would appear in the Log tab if Exclusive Mode failed.

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide

The Windows version of Dark Souls 1 has the same type of problem so I will assume that it is the same problem. The problem is likely due to how the game reads the values for the two triggers from the original DirectInput controller. The game will read a trigger at maximum negative pull which is mapped to camera X-; can't remember which one caused the problem. That would cause constant camera spinning until you pull the trigger about half way.

Dark Souls would only work as intended when using XInput. You have to make sure Sekiro can only see the virtual Xbox 360 controller in order to avoid that problem.

**Comment by teeedubb** [comment]
Hi Ryochan7. 
Bit off topic, but which method of hiding the direct input controller is best these days? Hide DS4 Controller or HIDGuardian?

**Comment by Ryochan7** [comment]
Approaches to tackling the whole exclusive mode problem have been a mixed bag. The safer route is probably to use HidGuardian. The easier and snappier route is to use the old "Hide DS4 Controller" option. Unfortunately, the old "Hide DS4 Controller" option has become increasingly less reliable as more software implement features that conflict with the exclusive mode hack. Also, there is a small chance that the old exclusive mode hack can permanently disable the DS4 in Windows which would require fixing it in the Windows Device Manager.

I still use the old "Hide DS4 Controller" option. It works well enough for me and I have not had an issue with a device getting permanently disabled since October 2018.

There might be a point that the option might be removed entirely and HidGuardian becomes the only option.

**Comment by SalahAdDin** [comment]
I have a problem with it too: It does not work.

I tested  it with DevilMyCray5 and it works fine, but not with Sekiro.

**Comment by teeedubb** [comment]
Thanks for the explanation.
Originally,  was going to say that I havent had any issues with exclusive mode, but today DS4W was not able to grab it (I usually colde boot, this time my pc was resumed from sleep). 
Ill give HIDGuardian a go to see if it makes any difference.

**Comment by holala02** [comment]
can the developper make a simple option in ds4windows that we can choose easly 360 mode or not :/ am not pro with all this programs

**Comment by Ryochan7** [comment]
The answer is honestly it depends. Technically, the option already exists for profiles as **Use DInput only**.  That will cause a virtual Xbox 360 controller to get unplugged if one exists so the system would only see the DirectInput DS4 controller. No re-mapping would be possible of course.

Now here are some problems. Shared Mode has to be used to expose the original DirectInput controller. Also, the process won't work when using a BT connection anyway. The mode change that happens to get the extra data from the DS4 causes the original DS4 controller to be seen as a dead controller by the system; the same behavior happens when using the Steam controller mapper. It is a hardware issue.

Back on topic, as far as I know, Sekiro will only work right if it detects and uses an XInput controller so that option would not matter in this case.
