### ISSUE TITLE
Could not connect to Vigem Bus too

### ISSUE THREAD

**Issue by Krako13** [Ryochan7/DS4Windows#632]
Hey,
I'm an user of ds4windows for couple years and everything was fine till the 1.7.2 update that i made this morning.
I usually donwload and install updates everytime the soft ask me so i guess i was on 1.7.0 before
Then, ds4windows doesn't recognize my pad anymore and tells me "could not connect to vigembus please check the status of the system device in device manager". So i installed the HIDguardian (that i haven't before) after i've read some issues here, reboot my machine and still have the same problem...
I'm on Windows 10 and have an oculus (i know it can cause problems sometimes with other soft....) 

Could you help me please ?

PS : sorry about my english as it's not my native langage, thx.

Edit : i downgrade to the previous version (1.7.0) and it works now i won't reinstall the update while it's not solved :)

**Comment by Ryochan7** [comment]
The connection code is the same between the two versions of DS4Windows. That is all handled by the ViGEmClient class library made by Nefarius. Something else has to be happening. The documented problem created by Oculus is more likely to cause a problem for Oculus Rift users more than the difference between those two versions of DS4Windows. There is a chance that the client code can find one exposed bus in one instance and find the forked Oculus version during a different run.

https://forums.vigem.org/topic/47/psa-oculus-software-can-crash-your-machine

**Comment by reecespieces** [comment]
I'm a bit out of the loop here. When did you make the switch from scp to ViGEM? And why?

**Comment by Ryochan7** [comment]
The switch was made with DS4Windows 1.7.0. There are a few reasons that the switch was made.

The big reason is that the version of ScpVBus that was being used (Scarlet Crush version) has not been updated since May 2013. A forked version of that driver was put out by Nefarius some time ago and bundled as a part of ScpToolkit. ViGEmBus was made as a successor to that driver and ScpVBus use has not been supported for a while. ViGEmBus is being actively maintained.

Another reason is that ViGEmBus works better than ScpVBus did. ViGEmBus does not suffer from some bugs that people have experienced from using ScpVBus; the big one being ViGEmBus does not leave old virtual controllers exposed in certain situations. It took a long time to get a configuration figured out but raw output performance is actually better when using ViGEmBus; initially testing even showed that ViGEmBus worked much better when using a ~1 ms BT poll rate than ScpVBus did. Testing has also shown that ViGEmBus puts less strain on my system, just by being exposed, than ScpVBus had.

Lastly, many people had requested it and there was an alt build of DS4Windows with support for it before. Transitioning to ViGEmBus was planned for around one year before finally diving in and making the switch.

**Comment by reecespieces** [comment]
I'm familiar with the problems ScpVBus had. I had some issues with the X360 controller failing to connect on Windows 7 and asked you for the hybrid ViGEM/UDP Server version.


Interestingly enough, a while back I had a problem with ViGEM involving rumble. Some situations would cause the rumble motor to turn on without stopping until I disconnect the controller. So, because of that I switched back to the ScpVBus version, and I was no longer getting that issue with not being able to connect the X360 controller. I can't pinpoint exactly which version fixed it for me, but ScpVBus was working perfectly for a while now, for me anyway.



And so now it looks like ViGEM still has these rumble problems. In dolphin for example, I can only use 1 of the rumble motors. If I try to use both motors simultaneously in dolphin by using the OR operator like: `Motor L` | `Motor R`

then as soon as a vibration is triggered in-game the 2nd motor specified in the OR clause just starts to rumble as doesn't stop until the controller is disconnected. 



I am upgrading to Windows 10 soon, so I guess I'll see if that changes anything but I'll be using the same XBOX360 drivers.
