### ISSUE TITLE
[Bug] Touchpad mouse not working since ViGEmBus migration (only on older profiles)

### ISSUE THREAD

**Issue by ExpatUK** [Ryochan7/DS4Windows#637]
Hi again,

Did some testing today on multiple computers and pads - the long and short of it is that since the driver bus migration, touchpad mouse input doesn't work using profiles from older versions.

Making new profiles, etc, returns desired behaviour. Might be worth noting on the releases page to save any backtracking. :)

Obviously if you stick with the new bus (and from the testing I've done it seems *so* much better thus far), then this should fade into obscurity anyway.

**Comment by mika-n** [comment]
Could you please share such an old profile file causing this issue? There may be something missing or some extra "wrong" default value, but in general DS4Win should not break even when it is used with an old profile file. When such a profile file is modified and saved then the profile file is updated and all missing entries are added there with default values. However, existing entries are left there and maybe some property now has a conflicting value.

**Comment by ExpatUK** [comment]
Sure thing! I'll provide two examples later this evening if I have time.

**Comment by ExpatUK** [comment]
Hmm. When testing, re-enabling on the faulty configs (ticking "Slide") makes everything behave as expected. Seems it's just the "Slide enabled" is the issue.

**Comment by mika-n** [comment]
That "Slide" option is indirectly related to a touchpad sensitivity property. If an old profile doesn't have TouchSensitivity option at all then the value remains as "0" and this option is disabled. This affects how DS4Win handles touchpad events (it probably sometimes interprets touchpad tickling as a "click" event instead of "slide" event).

**Comment by Ryochan7** [comment]
It seems like this could be an issue with the Toggle Touchpad functionality. When the Touchpad is disabled via Touch and PS, DS4Windows sets the Touchpad Sensitivity (Slide value) down to zero. There might a chance that someone edits and saves a profile in that state so Touchpad Mouse will become permanently disabled for that profile. DS4Windows should be using a separate runtime value instead of manipulating a profile option but it does not.
