### ISSUE TITLE
Confusing/broken update process

### ISSUE THREAD

**Issue by lewisohn** [Ryochan7/DS4Windows#638]
I'm not quite sure what's going on, or why, but updating DS4Windows on my PC is either very confusing or broken.

It starts when DS4Windows reports it has a new update and asks if I'd like to download it. When I click "Yes", a number of things seem to happen almost simultaneously:

1. DS4Updater starts running and reaches the "Download Complete" stage, with its progress bar about 90% full. I can't interact with this window.
2. Another window pops up to inform me that DS4Windows is still running and must be closed to continue the update. I can interact with this window.
2. Another window pops up saying "Please Download the Updater Now, place it in the programs folder and rename to DS4Updater.exe if on x86, then check for update again". I can't interact with this window.
3. A new tab is opened in my browser, Chrome, and a new copy of DS4Updater.exe is downloaded.
4. I'm asked to confirm that I want to disconnect my controllers. I can interact with this window.

It ends up looking like this:

![DS4WindowsUpdate](https://user-images.githubusercontent.com/6399657/55258665-30316580-526c-11e9-862e-5c6fbe5f5337.png)

After I click "Yes" and "OK" on the various windows, DS4Windows closes, but when I next open it I find that it **hasn't updated**.

I'm running Windows 10 Home, version 1803, 64-bit. My installation folder is in `C:\Program Files\DS4Windows` and it already contains DS4Updater.exe.

**Comment by Ryochan7** [comment]
I ran across this when doing the GitHub migration. The path encountered seems like a side effect of using AppData for storing config files. I believe that DS4Updater expects to be run from the same directory as DS4Windows. Running DS4Windows as a normal user from Program Files makes it so that the new updater cannot be downloaded to that path. The execution path still tries to launch the old existing updater though.

This issue has existed since the Jays2Kings builds. If nothing else, that method should be changed to skip launching the old DS4Updater.exe if DS4Windows could not download the new updater.

**Comment by lewisohn** [comment]
> Running DS4Windows as a normal user from Program Files makes it so that the new updater cannot be downloaded to that path.

I run it as an administrator from Program Files, if that helps.

**Comment by Ryochan7** [comment]
That takes one factor out. Then it should just be a matter of using AppData or Program Folder for storing config files. That scenario should only happen using the AppData option.
