### ISSUE TITLE
Win10, Bluetooth keeps seeing wireless controller to pair with, even when it's turned off, not letting me connect.

### ISSUE THREAD

**Issue by TheKrzysiek** [Ryochan7/DS4Windows#640]
I had this problem since I tried to connect my DS4 to PS3. I can still use it normally with USB, but I can't connect to Bluetooth at all, since I can't even pair with my PC. I have newest ver of DS4Windows.

**Comment by mika-n** [comment]
DS4Win has nothing to do with the BT pairing, it is your Win10 OS and the controller itself taking care of that. If you cannot see the controller in Win10 gampad settings without DS4Win application then DS4Win app won't help there. You have to try to reset your Win10 BT stack and/or DS4 controller. Mr Google knows how to reset BT settings in W10 and the DS4 controller itself.

Anyway. When you try to connect the controller to PC then make sure that your PS3 and PS4 are switched off because otherwise the controller may connect there. Take off the power cord completely from those consoles to make sure those won't wakup when you press PS btn in DS4 controller.

**Comment by TheKrzysiek** [comment]
I have my PS3 plugged off, but I'll try to reset BT stack.

**Comment by Ryochan7** [comment]
You have to remove the old HID controller device that Windows has a reference to and then pair the controller to your PC again. That same problem would happen whenever you connect the DS4 controller to a different PC or the PS4. This inconvenience has nothing to do with DS4Windows.
