### ISSUE TITLE
Triggers won't work in-game, but every other button works?

### ISSUE THREAD

**Issue by Gumgajua** [Ryochan7/DS4Windows#643]
Trying to play Sekiro (but it happens in a lot of other games that I can't name off the top of my head too) and every button works on the controller except L2 and R2? I've tried connecting straight through Steams controller support but it doesn't recognize the controller at all in game.

I'm asking here now because I can't seem to find any of the old posts talking about DS4Windows and the Triggers.

**Comment by Ryochan7** [comment]
Trigger mappings work fine on my end. Firstly, I will need to look at the profile that you are using to see how controls are being mapped.

**Comment by Gumgajua** [comment]
Sure thing. I'm not super adept at computers, so I'm not sure what or where exactly the profile file is.

Essentially I'm just using the default profile except I increase the BT Poll Rate. Like I said, I've had these problems with other games before, and Dark Souls being one of them, maybe this is just another issue with FromSoft?

**Comment by Ryochan7** [comment]
Something like that sounds like it could be an exclusive mode problem. I cannot directly test against Sekiro because my PC could not run it but problems that people have brought up are ones I have experienced with Dark Souls 1. Similar routines are probably being used in both games.

Mapping conflicts will occur if both the DS4 and the virtual Xbox 360 controller are exposed. One big problem is that the triggers will actually be mapped to camera rotation. The way the triggers of the DS4 are read makes the camera constantly spin. For those games, the original DS4 controller has to be hidden from the game by either attempting to use the **Hide DS4 Controller** option in DS4Windows or use HidGuardian.
