### ISSUE TITLE
Special Actions only work 1 layer deep

### ISSUE THREAD

**Issue by medwatt** [Ryochan7/DS4Windows#646]
I am trying to load different profiles through the use of the "Special Actions" option. Let me give an example:

I have 3 profiles named profile1, profile2, and profile 3.
Let's say I'm in profile1. If I press the "PS" button, it should go into profile2. If I press the "PS" button again, it should return back to profile1.
Let's say I'm in profile2. If I press the "Share" button, it should go into profile3. If I press the "Share" button again, it should return back to profile2.
What I've just described works at the moment. However, if I'm in profile1 and press the "PS" button, it goes to profile2. Now, if I press the "Share" button, it doesn't go to profile3.

Is this a feature or is this a bug ?

**Comment by mika-n** [comment]
It is not a bug but just how it is implemented. Special action type of "Load profile" loads a so called "temporary adhoc profile" and it requires an unload trigger key definition (unload trigger can be the same or different key than the regular "load a profile" key). 

When you have pressed the load-profile special action key then the app won't do another "second level" load profile until you press the unload trigger of the first action key. So, in this case you could do Profile1->Profile2 and Profile1->Profile3 linking using different special action keys but you cannot jump from Profile2 to Profile3 without "unloading" the first temp profile (ie. jumping back from profile2 to the original regular profile1).

This thing has been there probably for ages since the original version of DS4Win app. It does make it a bit difficult to make multiple "load profile" sequences and bind it to the same action key. For example someone might wanna set SHARE button clicks to cycle through Profile1->Profile2->Profile3->Profile1->etc...  At the moment this cannot be done without first unloading the first "temporary profile".

This could be easily fixed (actually in my own version of DS4Win app I have done it by disabling the logic of unload trigger in load-profile action and setting the action key to load a reqular profile instead of temp profile). However, the code change should be done somehow that it would support both the existing method (I'm sure someone finds it handy) and the new "unlimited" linking of load profile actions. 

Maybe this should be this way: 
Now DS4Win options requires an unload trigger to be set for LoadProfile action key, but if this is left blank then LoadProfile action key would simply load a new regular profile and not setting temporary profile at all. The new profile could have a different profile binding (ie. another action key definition and the previous action definition disabled in the second profile) in the same "Load profile" action key and so on....

**Comment by mika-n** [comment]
Here is a link to diff commit change which allows the use of unlimited linking of loadProfile action keys. 
https://github.com/mika-n/DS4Windows/commit/1e82db0f9e600e1d0a76ad058a9260d226ffaae4

**Comment by Ryochan7** [comment]
mika-n described the situation pretty well. As it is currently designed, Load Profile does only work 1 layer deep. I have only made minor changes to the routine that controls Special Actions to maintain compatibility with changes made elsewhere. Personally, I do not use the Special Actions feature that much

**Comment by medwatt** [comment]
> mika-n described the situation pretty well. As it is currently designed, Load Profile does only work 1 layer deep. I have only made minor changes to the routine that controls Special Actions to maintain compatibility with changes made elsewhere. Personally, I do not use the Special Actions feature that much

I appreciate your reply. I am still happy there's even the option to have special actions, even if it's just one layer deep. Having the ability to switch profiles is very important when using playing games on an emulator. Let me give you an example:

It is impossible to have one profile to play all Wii games because of Wii many controllers. For instance, I have a separate profile for games like New Super Mario Bros that have control schemes that can be easily mapped to controllers like DS4. I also have a separate profiles for games that require a gyroscope such as Super Mario Galaxy and Metriod Prime. In fact, in Super Mario Galaxy, I need to switch between two profiles because I need to switch between using the left analog stick for general movement and using the left analog stick as the tilt control. As you can see, having the ability to quickly switch between profiles while you're in exclusive full screen mood is extremely handy.

Obviously, all of this would not be necessary if there was a way profiles can be switched automatically based on the game chosen inside the emulator's GUI.
