### ISSUE TITLE
Special Actions don't load when using Auto Profiles

### ISSUE THREAD

**Issue by medwatt** [Ryochan7/DS4Windows#647]
When I put the program under AutoProfile to load a profile automatically when the program starts, I can no longer use use special actions to load another profile. But if the program is not under AutoProfile, then I can load other profiles using special action.

For instance: I want a profile called "retroarch_default" to load automatically when I start retroarch. I also have another profile "retroarch_switch_dpad" that I sometimes use when I want to use the analog stick instead of the dpad. I have made a special action that loads "retroarch_switch_dpad" when "Share" button is pressed when the profile used is "retroarch_default". Switching to another profile doesn't work when the program used has an entry in AutoProfile. If I remove it under AutoProfile, it works, but this means I always have to switch profile manually.

**Comment by mika-n** [comment]
This is because of the same "temporary profile logic" I described in another post. https://github.com/Ryochan7/DS4Windows/issues/646#issuecomment-480576923

AutoLoadProfile feature uses the similar "temp profile" than specialActionKeys,and while DS4Win app is under a temporary profile it won't do LoadProfile special action keys unless few code lines are changed.
