### ISSUE TITLE
Keybindings/macros

### ISSUE THREAD

**Issue by obibram** [Ryochan7/DS4Windows#654]
hello, i have had my controller setup with ds4windows so if i press buttons or move the stick it does keybindings for Rocket League. But suddenly it just spams aaaaaa or wwwwww on my pc. I read other issues with this but i have found no solution. So how can i fix this.

**Comment by Ryusennin** [comment]
Have you tried adding some dead zone, as suggested in #648?

**Comment by Ryochan7** [comment]
This is very likely a dead zone problem. When switching to a KB+M profile, you have to have some form of dead zone set for the analog sticks or actions will likely get activated.

**Comment by obibram** [comment]
I tried it, to what do i set it? and i used the macros for 3 months and no problem, how can it suddenly be a problem?. and it also happens when i dont even move a stick

**Comment by mika-n** [comment]
Remember that analog sticks are "unstable" in hardware level and there are differences between controllers and over time sticks may come more and more "loose" (springs in a stick wear out). I'm sure you have seen this post explaining the issue in more details: https://github.com/Ryochan7/DS4Windows/issues/648

You should just try out which deadzone works best with your controller. You can tweak LS and RS deadzone values per profile. Take a look at the documentation Wiki pages for more info about various settings in DS4Win profile editor. https://github.com/Ryochan7/DS4Windows/wiki/Settings

**Comment by obibram** [comment]
I changed my deadzone but still when doing nothing it just  spams aaaaa or wwwww. What can i do? it worked fine first

**Comment by mika-n** [comment]
- Which version of DS4Win app?
- Try with different controller or the other stick axis (in case the existing stick and axis has something weird)
-Try setting the deadzone of the keyboard mapped stick axis to 0.90 value to make sure it is "big enough" and work it down from there until you are happy with the responsiveness of the stick. 
- Make sure you haven't accidentally mapped gyro tilting to any of the keys. 
- Post the profile file you are using, because there may be something you have accidentally tweaked and it causes the problem.

I just tested with the latest DS4Win app (V1.7.3) and keyboard bindings to analog sticks work just fine as long the deadzone value of the re-mapped axis is big enough. And so many people are using keyboard bindings in re-map tables that I doubt that the existing version of DS4Windows app itself has major bugs with keyboard bindings. If there was then noise would be a lot louder.

**Comment by obibram** [comment]
i use 1.7.3 x64. if u map a key on the other stick it still happens. 
![image](https://user-images.githubusercontent.com/49496082/55945350-ecb30000-5c4a-11e9-8043-a4ba0021c9b0.png)

**Comment by mika-n** [comment]
The screenshot shows that you have 0.00 deadzone for LS and RS options. This means that left stick and right stick has zero deadzone, so the result would be exactly what you are seeing if a stick axis is mapped to a keyboard with zero deadzone. Analog stick axies are hardly ever completely stable in a hardware level especially if you rest your thumb on top of the stick.

Try setting 0.50 value to Deadzone LS (or RS if you are using right stick) option.

**Comment by mika-n** [comment]
And if you really cannot make it to work then post the whole profile file as an XML file attachment.

**Comment by obibram** [comment]
I already did a higher deadzone but it didnt work. It also spammes when im not even doing anything and the controller read isnt doing anything either, so i think the program is clitched. also i cant share an xml file, it doesnt support it.

**Comment by obibram** [comment]
[po.zip](https://github.com/Ryochan7/DS4Windows/files/3068047/po.zip)

**Comment by mika-n** [comment]
Hmm... You must be doing something wrong because that PO profile file doesn't even have any re-mapping rules in left or right stick (or anyother re-maps between DS4 controller and keyboard).

Are you sure you have set the controller to use that profile file? Maybe you have several profile files and you now have set the controller to use some other profile where you haven't set deadzone values and therefore it keeps on feeding re-mapped keyboard events.

What do you see in the Log tab page of DS4Win options screen? If should show you what profile is used when you plug in a controller.

Controllers tab page of option sreens let's you choose an active profile unless you have also set "autoprofile" settings to change the active profile automagically based on running applications.

**Comment by obibram** [comment]
Yeah but when i map a key it glitches out. So i unmaped it.

**Comment by obibram** [comment]
[po.zip](https://github.com/Ryochan7/DS4Windows/files/3068535/po.zip)
here is the one with a keybinding

**Comment by mika-n** [comment]
You have "sensitivity LS, RS, R2 and L2" set as 0.95. Revert those back to default 1.00 values.  Non-default sensitivity values with keyboard bindings may create create some unwanted events (artificially too sensitive axis).

Also, you have checked "Flush HID queue" option. I recommend you to uncheck it because flushing hid queue each time it is read just causes extra IO traffic in the diver level and you may loose some controller events (ie. events are flushed in Windows OS driver level before DS4Win app has a chance to read those events).

**Comment by obibram** [comment]
Thank you for the help though

**Comment by obibram** [comment]
> You have "sensitivity LS, RS, R2 and L2" set as 0.95. Revert those back to default 1.00 values. Non-default sensitivity values with keyboard bindings may create create some unwanted events (artificially too sensitive axis).
> 
> Also, you have checked "Flush HID queue" option. I recommend you to uncheck it because flushing hid queue each time it is read just causes extra IO traffic in the driver level and you may loose some controller events (ie. events are flushed in Windows OS driver level before DS4Win app has a chance to read those events).

Wow, i dont know what to say. It worked :DD 

thank you so mmuch

**Comment by mika-n** [comment]
glad you got it working. I believe the non-default 1.00 sensitivity option was the root cause. Unchecking FlusHIDOption is just a bonus benefit and I believe it should be unchecked in all new default profiles (and sensitivity is 1.00 by default in new profiles). Happy gaming...

**Comment by Ryochan7** [comment]
The sensitivity code was flawed. It still relied on 127 being interpreted as the axis center point instead of 128. I don't use the sensitivity option so I did not catch that problem. The final difference would be minor.
