### ISSUE TITLE
Shift modifier

### ISSUE THREAD

**Issue by sergserg2** [Ryochan7/DS4Windows#658]
Is there a way to use more than one key as shift modifier?
I need same macro for the button when  L1 or L2 is holding.
Would be possible some grouping positions on shift modifier selection list: L1 or L2, R1 or R2?

**Comment by mika-n** [comment]
In the same profile? No.  
But different profiles can have a different shift modifier key.

**Comment by sergserg2** [comment]
I know, but this not help. In game (like MMORPG) there are action for button with and without modifier, and modifiers are two (layout is for 20+ different actions). When I try to change something in default layout (i.e. for touchpad using), I need one action on button without and second (other) action with both modifiers (same for both) in minimum (best would be two independent actions with each modifier plus third action without).

**Comment by Ryusennin** [comment]
You're asking too much of DS4W. That's the job of JoyToKey.

**Comment by mika-n** [comment]
It is possible to implement and change everything but unfortunately time is a limited resource. Ryochan is playing with a new version of the whole mapping thing (re-designed completely), so maybe this "multilayer/multikey shift modifier" thing belongs there as a potential new feature. To change the shift modifier logic in the existing app version would require quite an extensive testing phase to make sure nothing breaks and the profile editor GUI should be slightly modified to make multikey shift modifier mapping possible. But unfortunately time is limited resource.

**Comment by sergserg2** [comment]
Meantime I try something with profiles and did like that: profile A, all needed buttons with modifier L1 (combat actions) and default non-combat. Profile B, same, but with L2 as modifier. Default is profile A. Next I added special action, on L2 change profile to B, return on L1. This work OK (I have 2 modifier per button plus other default action), but mess when I press two modifiers together (another actions set in game) then release L1, profile is back to A, but I have still pressed L2 (which is modifier in profile B). So, maybe there is easy way to implement the unload trigger of special actions "load a profile" on button release? Pressing L2 will load profile B, releasing L2 will return to profile A.

**Comment by mika-n** [comment]
> So, maybe there is easy way to implement the unload trigger of special actions "load a profile" on >button release? Pressing L2 will load profile B, releasing L2 will return to profile A.

The existing development version already has one change in this "Load Profile" special action. Now in the official version you probably have it is required to set unload trigger for LoadProfile action. This prevents linking of profiles (or it supports only two levels). This means that you can have ProfileA->ProfileB linking but you cannot have ProfileA->ProfileB->ProfileC->ProfileN linking without first pressing the unload trigger and going back to the original profile.

When the new version is released then it no longer require unload trigger for LoadProfile actions. If LoadProfile special action doesn't have an unload trigger then you can link loadProfile actions to cycle through any number of profiles (ProfileA->ProfileB->ProfileC->ProfileD->ProfileA and so on) by setting a new loadProfile definition to the same action key per profile.

You suggested a feature where a profile is unloaded when a special action key is released (ie. no need to press an unload trigger key which could be the same key as the action key). 

Yes, I can see that it might be sometimes useful feature to extent mapping possibilities of the same gamepad keys when the existing LoadProfile-Unloadprofile key presses is considered to be too slow process (ie. requires two key presses instead of just releasing the trigger key). 

LoadProfile special action could have an "automatically unload the temporary profile when a regular trigger key is released" option to enable this functionality. This would be reasonable easy way to implement this kind of "adhoc temporary profile" logic. Let's see if I find some time to do this change and release it as a pull request.

**Comment by sergserg2** [comment]
> LoadProfile special action could have an "automatically unload the temporary profile when a regular trigger key is released" option to enable this functionality. This would be reasonable easy way to implement this kind of "adhoc temporary profile" logic. Let's see if I find some time to do this change and release it as a pull request.
This is great idea, better than modifier(s) per button. I think, this will replace the current "modifier per button" funcionality with better "profile per button" flexibility (and gives easy way to define any numbers of actions pinned to buttons / different layout per trigger and so on).

**Comment by mika-n** [comment]
I just created a new pull request with a new feature doing this "automatically unload a profile on regular trigger key release" functionality.. See the above linked pull request link. Once Ryochan has a time to review it then it will hopefully be merged into master branch and is included in some of the upcoming public releases. 

I have tried this new feature with few games and it is actually quite handy if aiming/moving/menu/pitstop/whatever scene in a game needs a bit different profile but I still need to be able to quickly switch back to the previous profile. This is sort of like "shift modifier" for a whole profile instead of just a single key.
