### ISSUE TITLE
Can DS4Windows simulate the motion of the right rocker of the handle with six axes when pressing L2?

### ISSUE THREAD

**Issue by qqjp** [Ryochan7/DS4Windows#659]
Can DS4Windows simulate the motion of the right rocker of the handle with six axes when pressing L2? I know it can simulate the mouse, but it can't simulate the right rocker.

The function of simulating the right rocker of the handle with gyroscope can be realized in STEAM, but STEAM is not as general as your tool. I hope to add this feature. I like to use six axes to aim, but in many games, the mouse can't coexist with the handle.

**Comment by Ryochan7** [comment]
I am guessing you mean that you have the Gyro mapped to Mouse-like Joystick in Steam to emulate the right analog stick rather than emulating a mouse. That feature is not available in DS4Windows and it probably won't get added. I have tried to use the Mouse-like Joystick output mode in Steam a few times but I never could find a setting that I liked. If I had a usable reference then maybe incorporating that feature would be more likely.

**Comment by qqjp** [comment]
Ds4 Windows is an excellent software. Thank you for your work. At present, in most games, the operation of the handle will conflict with the mouse and keyboard, which brings a lot of trouble to the players who want to target with six axes. I think Steam has done a good job in this area, but it can only be used in steam games, and more and more games are reluctant to be published in steam, so your software is the future of ds4. I sincerely hope that you can join such a function. Thank you again for your work.

**Comment by Ryochan7** [comment]
Version 1.7.16 now has Mouse-like Joystick support for the gyro.

https://github.com/Ryochan7/DS4Windows/releases/tag/v1.7.16
