### ISSUE TITLE
[Feature Request] Invert Sixaxis controls

### ISSUE THREAD

**Issue by Excalibaard** [Ryochan7/DS4Windows#661]
Hi man,

Thanks for the continued updates. 
I've been looking for a way to invert the sixaxis controls but was not able to find this, so I figured it may not have been implemented yet. I'm trying to use the sixaxis controls in a few older racing games (NFS: Most Wanted (2005) and NFS: Carbon) but the steering direction is reversed when linking it to a stick X or Y axis, no matter the way I map them in-game. I've also not been able to fake the DS4 as a 'steering wheel' for the games. Could you maybe include an extra 'inverted linear' option or a checkbox to use in combination with the existing output options?

Cheers!

**Comment by mika-n** [comment]
Hmm... I find it quite surprising that a racing game interprets X axis of left/right stick as opposite direction when mapped to sixaxis. Are you sure you are using the latest version of DS4Windows? 

Anyway. If you use "Tilt Left" or "Tilt Right" gyro mapping options then you can set those to any analog axis. Just remember that using these gyro options in analog axies requires you to unmap the original stick axis or set a big enough deadzone values in LS or RS options. Otherwise both gyro and the original stick feeds the same axis and the result may not be what you wanted.

The "steering wheel axis" emulation and option in DS4Windows app is an alternative way to use gyro and DS4 as a steering wheel.  Please see this Wiki page of DS4Windows for more info about "steering wheel emulation": https://github.com/ViGEm/ViGEmClient/issues/3
https://github.com/Ryochan7/DS4Windows/pull/491

I haven't found a single racing game yet which would not work with this steering wheel emulation feature. 

What kind of problems you have with NFSMostWanted/NFSCarbon? 
What options you have set in a profile and and what do you see in Logs tab page of DS4Windows options screen?

I know that some people use this sixaxis steering wheel emulation with NFS Rivals, Grid2, Crew, ProjectCars, RaceRoomExperience, LFS and so on. I would be very surprised that the emulation would not work with NFSWanted or NFSCarbon.

**Comment by Excalibaard** [comment]
I'm using V1.7.3.

Thanks for linking the Wiki. I was trying to use the steering wheel emulator and this explains a bit more than I was able to find elsewhere. The settings used were 180deg, linking the emulator to the RS X-axis. I mapped it to the RS X-axis in-game as well (tried both normal and reversed mapping, but got similar results). I'll try again with your suggestions. NFSCarbon/NFSWanted work fine otherwise, it's just that the steering was reversed trying to use sixaxis.

Thanks for your support, will report back with the findings.

**Comment by mika-n** [comment]
> Steering wheel emulator still doesn't behave properly. I've found it's not reversing the controls, but is >highly sensitive (90deg) or unresponsive (180deg+). 

I forgot to mention that (and the Wiki page doesn't mention it clear enough) that the steering wheel emulation works best (and probably is usable only) if DS4 controller is attached to a do-it-yourself rig (as seen in the picture https://github.com/Ryochan7/DS4Windows/pull/491#issuecomment-439821245). This way gyro sensor values are more predictable and calibration is more accurate. Not to mention that steering wheel immersion is 100x better than trying to hold the controller steady in thin air :-)

**Comment by Excalibaard** [comment]
Ah, that does clear up a lot :) I was holding it in the air! (You can play airguitar, surely you can drive aircars as well!)
I have set an anti-deadzone value, but I'm still tinkering with it (as well as linear vs quadratic curve steering and sensitivity to get the right feel). Those are things I can figure out on my own though :) Thanks a lot for the quick responses!

**Comment by mika-n** [comment]
Don't tweak Sensitivity values in the current official version of DS4Windows app because that feature is broken. The bug is fixed in the latest development version but it is not yet released. Set all sensitivity options to default 1.00 value for now. https://github.com/Ryochan7/DS4Windows/issues/655
