### ISSUE TITLE
Constant rumble after updating to 1.7.5

### ISSUE THREAD

**Issue by bentwookie** [Ryochan7/DS4Windows#666]
Looks like there's been some work around rumble the past few releases. I too had noticed that sometimes it rumbled after it should have stopped a few releases back. Not a big deal, but after updating to 1.7.5 it never stops rumbling. Even after reboot, when DS4Windows comes up, my controller starts vibrating off the desk :)

[DS4WindowsLog.txt](https://github.com/Ryochan7/DS4Windows/files/3104231/DS4WindowsLog.txt)

**Comment by mika-n** [comment]
Does it do the same over BT and USB connections?
Have you tried to create a new "clean" default profile without any re-mapping and scaling things? Does it work better?

Anyway, this is a bit strange because DS4Win app itself doesn't generate rumble events unless you press "Test rumble" buttons in DS4Win options screen. Other people haven't reported this kind of problem, so I doubt it is DS4Win app problem but more like some "environment combination" issue. 

Anyway. If you want to disable a rumble events sent from a game via ViGEmBus driver to the DS4Win app then you set rumble level down to 0% in DS4Win profile options.

**Comment by bentwookie** [comment]
USB. What was strange was that it started to rumble right after a reboot. I hadn’t even launched a game (though maybe some background thing did?)

I played some last night and didn’t have any problems though. So hopefully it’s a ghost.

Scott

**Comment by Ryochan7** [comment]
The ViGEmBus driver does produce one rumble notification event when a new virtual controller is plugged in but it will normally be a 0 feedback state. I would not think that the driver would return anything else from a fresh queue as any previous WDF Queue is removed when a virtual controller is unplugged. If nothing else, the fallback feedback timer should kick in around 2 seconds to stop the controller from rumbling in the worst case scenario.

Pretty much all tested cases of force feedback problems have been dealt with and the problem was not caused directly by DS4Windows code. Hopefully no more rumble problems happen on your end.
