### ISSUE TITLE
DS4Windows issue/Controller Issue/Both? Help

### ISSUE THREAD

**Issue by FazedLucifer** [Ryochan7/DS4Windows#670]
I'm not sure if this is the best place to post it but this seems more active than the Reddit.
I have been using DS4 Windows for a month or so and this only recently became a problem. I have been playing some assassins creed unity and syndicate. Now it wasn't a huge problem in unity and only started happending around when I had beaten the game but in syndicate L2 is used for aiming/slowing carriages while L1 is used for the zipline/getting on top of carriages. I know there are other things it does but they aren't coming to my head right now. Now I am unsure if this is just a controller thing or a ds4 thing or if there is some in between but some help would be much appriciated. Also yes it does it for R2/R1 but the L2/L1 is much more annoying.

**Comment by mika-n** [comment]
I must admit that I didn't understand what is the problem you described? Maybe there is a some kind of language barrier.

**Comment by Ryusennin** [comment]
I didn't understand the issue either, maybe a sentence or two are actually missing from the post. For info, Unity and Syndicate work as expected on my system.

What's Reddit?

**Comment by FazedLucifer** [comment]
I am playing Assassins creed syndicate. To aim to shoot or throw an Item you need to press L2/Left Trigger. The Grappling Hook/Zipline use L1/Left Bumper. Sometimes when pressing L2/Left Trigger instead of aiming down sight it uses L1/Left Bumper and uses the Grappling Hook/Zipline. IDK Y but it shouldn't do that.

**Comment by mika-n** [comment]
Aah. You mean that sometimes the game registers wrong key combination when you press two DS4 keys at the same time (like L1 key + L2 analog trigger).

Open "joy.cpl" Control Panel applet (you can use "Run" command to run joy.cpl command). What do you see there? There should be a list of gamepad controllers the system can use. Do you see two "Wireless Controller" devices or just one when you have plugged in one DS4 controller? 

If you test keys and triggers via this joy.cpl screen then try to press those L2/L1 whatever keys at the same time and see whether this screen detects correct keys being pressed. I just tested this and did't see wrong keys being reported as pressed down.

If you see two WirelessController devices then you may have a "double input" issue where the game see both the physical DS4 controller and the virtual re-mapped DS4 controller device. In that case try to enable "Hide DS4 Controller" option in DS4Windows to hide the physical controller from a game (and from Windows OS) and leaving just the virtual controller visible.

If/When you enable "Hide DS4 Controller" and re-connect the controller then please check DS4Windows Log tabpage in options screen. If this hide option doesn't work then you will see a warning message that exclusive mode failed. Read through the following Wiki page for more info about "double inputs" and why exclusive mode is sometimes required:
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by FazedLucifer** [comment]
This was it. It shows 2. I'm gonna test it now.

**Comment by FazedLucifer** [comment]
Now a new problem has popped up. This fixed the L2/L1 R2/R1 thing but the reason was that the other controller thing L2 is L1 and L1 is L2 same for R. Square is X. Triangle is O. So yea

**Comment by FazedLucifer** [comment]
I love how if it isn't one thing it's another. Now Hide controller wont work becuase it wants programs shut that are already shut

**Comment by HiagoPereira** [comment]
> I love how if it isn't one thing it's another. Now Hide controller wont work becuase it wants programs shut that are already shut

Shut down your PC. Don't open Steam or Uplay, just open DS4Windows and tick 'Hide DS4 Controller'. After that, you can start your game, It'll only show one controller.

**if you want DS4 Prompts (X, O, Square or Triangle buttons showing up ingame)** _Create a new profile and use this settings_ https://i.imgur.com/iUTCKTZ.png

**Comment by FazedLucifer** [comment]
Already did that earlier and still saying stuff needs to be shut
I have killed nearly every program that I am sure won't have repercussions for shutting down and it still won't work.

**Comment by mika-n** [comment]
the "Hide DS4 Controller" (=exclusive mode) can be sometimes tricky to get working. The fact is that DS4Windows app MUST BE THE FIRST app using the physical DS4 controller. Otherwise exclusive access fails because other app has already "stolen" the hid device handler and does not let DS4Windows app to use it in exclusive mode (ie. the controller remains in a normal shared mode).

The Wiki page tried to list few of the usual apps which may hold an open access to a gamepad controller, but the list there is no where near a complete list of apps. Sometimes very unexpected app may hold an open handle to a controller (ie. Win10 Store app, NetFlix Win10 Store app, chat app, etc).

If you cannot get the "Hide DS4 Controller" option to work and figure out which other app "steals" the controller then HidGuardian device driver is an alternative way to hide the original controller. HidGuardian driver goes down to WinOS kernel mode and can do this hiding before any app can steal the controller, but there are few issues with that driver.

For example, if you have rev1 DS4 controller (ie. not the newer PS4 "Pro" controller) then HidGuardian would hide both the physical rev1 DS4 controller and the virtual DS4 controller (those share the same hardware ID).  See this discussion: https://github.com/Ryochan7/DS4Windows/issues/639

If you have the newer rev2 DS4 controller then there is a workaround to this HidGuardian issue with virtual DS4 controllers (see the above linked discussion how to hide only rev2 DS4 controller and leaving rev1 DS4 still visible).

**Comment by Ryochan7** [comment]
That message is just a list of the most common problem applications. There is a way to find out which program has an open handle for the device but it requires using Process Explorer and the scan can be a little slow.

https://github.com/Ryochan7/DS4Windows/issues/573#issuecomment-462189394

The most sure way of getting exclusive access to work is by installing and configuring HidGuardian.

https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide

**Comment by HiagoPereira** [comment]
So, I got it fixed, the controller is working flawlessly on Ac Unity, but there's another thing: to open the Map, you should tap the touchpad. The thing is that my Dualshock is the v2, and I'm emulating the first one. Is there a way to actually emulate the touchpad so I can open the map ingame?

**Comment by Ryochan7** [comment]
Only the touchpad click button can be emulated. There is no way to map the touch event coordinates in ViGEmBus.

**Comment by HiagoPereira** [comment]
How can I map the click button?

**Comment by FazedLucifer** [comment]
Meant t post earlier but I forgot. I restarted my computer cause I'm like whats the worst that can happen. It just started working so yea. I hate technology sometimes.

**Comment by Ryochan7** [comment]
That button is being reset in the remapping routines. It does not work in the current version.
