### ISSUE TITLE
Profile Save Location

### ISSUE THREAD

**Issue by DoganM95** [Ryochan7/DS4Windows#673]
please add support to save all profiles in one github gist, so users can just enter gist-id and github api token after a fresh install. this can also be used as profile save location instead of saving them locally.

also please add an option to set the profiles folder (if using a local folder) to be set manually. this would also enable users, which are not using github, to save their profiles in a sync-folder like onedrive or gdrive.

**Comment by mika-n** [comment]
Maybe you could use MKLINK "symbolic link" (yeah, Windows version of Unix/Linux symlinks) to synchronize %APPDATA%\DSWindows folder to your master OneDrive sync folder. The idea is that you can created a symlink in OneDriver folder which physically points to DS4Windows profile folder even when it is not exactly below the root OneDrive folder.

The following command line assumes that your DS4Windows profile folder was installed below default application folder (%APPDATA% profile variable in WinOS). You may have to run this in "Run as Administrator" cmdline shell.

`MKLINK /j "<PathToYourNormalOneDriveSyncRootFolder>\DS4Windows" "%APPDATA%\DS4Windows"`

The same trick with mklink works with OneDrive/GoogleDrive/whatever cloud sync app you use. Just create the symlink folder below your cloud synced root folder. Mklink won't physically copy any files because it is just a symbolic link to the actual target folder, but apps won't see the difference.

**Comment by Ryochan7** [comment]
I don't think it would be a good idea to use GitHub's resources to store a bunch of profile data. The profile format will likely change in the future so that data will not be very useful in the future. You would be better off linking the Profiles folder to a cloud storage system or use something like SyncThing to back up that folder locally.
