### ISSUE TITLE
Newest updates will not install virtual 360 driver.

### ISSUE THREAD

**Issue by cohfan5** [Ryochan7/DS4Windows#676]
V 1.7.6 and 1.7.7 are not allowing driver install of the virtual 360 controller. I can only see the wireless controller in control panel. Plugging into USB does not help. I've also tried uninstalling and reinstalling DS4, ViGEm and HidGuardian(currently uninstalled) using your much appreciated WpfApp1. Not sure what else to do or what else to test. Using 1.7.5 just fine for now. Thanks!

**Comment by mika-n** [comment]
What do you see in Logs tabpage in DS4Windows option screens? There should be some error/warning messages if DS4Win app cannot create (=connect on the fly) a virtual controller device. 

Do you have "Use DInput Only" option checked in a DS4Win profile? Uncheck that option because if that option is selected then the app won't create a virtual output device.

If you suspect that there could be something wrong in the existing profile then try to diagnose any issues with a fresh new default profile without any custom re-mapping rules. 

Open DeviceManager in WinOS. Do you see any yellow warning icons there (especially in HID device or in gamepad devices)? Make sure any of the HID devices are not in disabled state when you connect a controller without DS4Windows app running.

**Comment by cohfan5** [comment]
Got it working. Thanks for your help. The issue was that there was no profile assigned to the controller. I've never seen it remove the default profile after updating. Thanks again and hopefully this helps someone!
