### ISSUE TITLE
X / Square Macro not working

### ISSUE THREAD

**Issue by eclipsaa** [Ryochan7/DS4Windows#678]
Trying to create a Rapid Fire X / Square button.  Just hold down the button so it dose X,x,x,x,x,x and so froth tell I release it.

Acroding to DS4windows I have version 1.7.7
Windows 10.
I have checked different games and restarted DS4 windows and games many times and nothing.

The macro I created is Is I hit the Square button.  Record Delay Selected.  Repeat while held selected.

Its a Down press X,  Wait 100ms (with some change)  and Up release on X
This is repeated 3 or so times.

After trying to get this to work I have nothing to show for it.  I even created a macro with the Square button to type "h"  and "i"   And that didnt work either.   

So can anyone help me?

(Side note.  Seems trying to make these macros also disables the touch pad on my ps4 controller...  Have to delete the macros (that dont work)  and restart DS4windows to get the touchpad working again

**Comment by mika-n** [comment]
I just tested to record a macro with "auto fire" type of sequence (X btn down, short wait, X btn up, short wait and repeating the same few times). I set the macro to execute via Options btn.

Enabled this macro in a profile and Options btn repeated the X btn events with defined wait intervals just fine.

When you edit a macro then did you remember to press "Save" button on the bottom of the macro special action screen? You have to press this macro specific "Save" button before you press the "Save" on top toolbar to save the whole profile. It is easy to forget to press the save button on the bottom of the spec action screen and just pressing the top toolbar Save for a profile.

After you have saved a special action (macro, load Profile, whatever) then you have enable the spec action in a profile by selecting the checkbox in a list of spec actions and then save a profile.

Another issue you mentioned was about using a touchpad for mouse controlling. There was a small bug there but it is already fixed in the latest development version. The next release should have that touchpad fix.

**Comment by eclipsaa** [comment]
Try executing it via the X button so the macro dose the X button spam.   

And yes i saved the macro and then saved the profile for each one.   Reason i know this is i would do that before testing each thing (Assumed that if i didnt save the profile the macro wouldent work anyways)   Plus when I re open the profile the macro I made would still be in there.

The only thing that makes me question what I did was the Special Actions menu you mention.  How do i set that up?   I didnt do anything in the special actions menu when trying to create a macro

**Comment by mika-n** [comment]
I tested a "X auto-fire repeating" macro again and set the trigger to be the same "X" DS4 button. The macro played through the macro just fine repeating X button presses several times with a short delay between X button events.

"The special action menu per profile" is not really a menu but a list of all macros. There you can define which one of those is enabled for a selected profile by ticking the checkbox on the spec action line.

If you really cannot get this working then maybe you should zip and share your Actions.xml and a profile XML files. Or start from scratch by creating a new default profile.

![DS4Win_ProfileEnabledSpecActions](https://user-images.githubusercontent.com/35538525/57028451-ced42c00-6c47-11e9-8c0e-3f7112d70a9f.png)

**Comment by eclipsaa** [comment]
This is my profile 

Though I do have a question.  You keep setting other buttons to macro Square but not square... Is there a reason why you never do the same button to macro itself?


[profile.zip](https://github.com/Ryochan7/DS4Windows/files/3135237/profile.zip)

**Comment by mika-n** [comment]
Aah. Sorry. Mixed Cross and Square buttons. Anyway, my test macro using Cross trigger simulated number of cross btn presses. Anyway. Tested it again using the square btn as macro trigger key and the macro repeated square button presses. Worked just fine.

Couple notes about your profile:
- You have "Flush HID" option checked. I recommend you to untick this because by flushing the HID message queue each time an event is read from a hid device may loose some events (ie. events in a queue which haven't been processed yet are flushed to hyper space). Also, flushing the hid queue several times a second just creates unnecessary overhead.

- I guess you have recorded the macro and assigned it to Square button via the Controls tab page of profile editor (ie. opening the keyboard and mouse icon picture and pressing Record button there and assigned it directly to square button). I have never used macros like this. I always create macros as "special actions" in SpecialActions tab page and select there for example Square button as the trigger for the macro.  I did my tests like this, so maybe you should try it this way?

**Comment by eclipsaa** [comment]
I did and still dosent work.  I even tried creating a new profile and all my settings from my other profile are "default"  so starting a new profile still didnt really help...   is there a guide to create macros the way you say to.  Because all i can find is the way i been doing it according to 'guides"  i have found

**Comment by mika-n** [comment]
I created the macro like this:
- Open a profile for editing
- Go to "Special Actions" tab page (see the picture in earlier post)
- Press "New Action" button
- Give a name for the spec action
- Select an action as "Record macro"
- Select Square as trigger key
- Press "Record a macro" button to record a sequence
- Select "record delays" checkbox option
- Press "record" and press whataever keys you need to
- Press "Stop" and "Save" buttons to save the recorded sequence
- Press again "Save" button on the bottom of the "Special actions" tab page
- You should be now back in the screen listing all special actions. Make sure the newly created spec action is checked and press "Save profile" button on the top toolbar.

After this the selected trigger key for a macro should play the macro. You don't have to map the trigger key (fex square) in a Controls tab page (it can be left as default bind to "X Button" as it is called in x360).

I tested the macro sequence in "Joy.cpl" controlPanel applet (run this command or choose "Control Panel" link in Settings tab page in DS4Win app) and in HTML5 gamepad tester app
https://html5gamepad.com/

The macro sequence and square DS4 button as a macro trigger worked fine in both tests.

**Comment by eclipsaa** [comment]
Yeah still dosent work for me.  I tried the Joy.cpl and it just shows a constant light (if the macro worked it should flicker?)   so not working there... As for that website the controller dosent show up on there...   Just says not detected 

So somethings going on and I have no clue...

Im just using a PS4 controller connected by USB with DS4windows running.  Thats all

**Comment by mika-n** [comment]
Jep. Joy.cpl screen should show flickering light in a button when a button is pressed and released during a macro re-playing. Or if you press those buttons in a normal way.

HTML5gamepad test web page doesn't detect a controller until you press some controller buttons. But I'm sure you tried to press several keys, so very strange if it didn't detect your controller. Try doing it without running DS4Windows app because the htmlgamepad tester should detect the native DS4 controller also. Does it work? By the way I used Chrome browser. Not sure if IE browser even supports html5 gamepad API interface.

What do you see in DS4Win Logs tab page when you connect a controller? Post those log messages.

By the way. Please share also the actions.xml file because a special action macro is saved there and not within a profile file.  Profile file just specifies which macros are enabled for the profile but the actual "implementation" of the macro is in actions.xml file (one folder above the profile file folder).

**Comment by eclipsaa** [comment]
[Actions.zip](https://github.com/Ryochan7/DS4Windows/files/3135785/Actions.zip)

I got the website to see my controller.  Even with the macro set up like discirbed above its only saying im pressing 1 time 



4/30/2019 7:38:55 PM: DS4Windows version 1.7.7
4/30/2019 7:38:55 PM: Starting...
4/30/2019 7:38:55 PM: Connection to ViGEmBus established
4/30/2019 7:38:55 PM: Searching for controllers...
4/30/2019 7:38:55 PM: Using Shared Mode
4/30/2019 7:38:55 PM: Found Controller:1C:96:5A:A3:F2:15 (USB)
4/30/2019 7:38:55 PM: Plugging in DS4 Controller #1
4/30/2019 7:38:55 PM: DS4 Controller #1 connected
4/30/2019 7:38:55 PM: Controller 1 is using Profile “euphy"
5/1/2019 10:33:33 AM: Controller 1 is using Profile “Euphamia"
5/1/2019 10:33:33 AM: Unplug DS4 Controller #1
5/1/2019 10:33:33 AM: X360 Controller #1 connected
5/1/2019 10:38:22 AM: Unplug X360 Controller #1
5/1/2019 10:38:22 AM: DS4 Controller #1 connected
5/1/2019 11:02:58 AM: Controller 1 is using Profile “euphy"
5/1/2019 11:03:00 AM: Controller 1 is using Profile “Euphamia"
5/1/2019 11:50:55 AM: Closing connection to ViGEmBus
5/1/2019 11:50:55 AM: Connection to ViGEmBus established
5/1/2019 11:51:00 AM: Plugging in X360 Controller #1
5/1/2019 11:51:00 AM: Warning: Could not open DS4 1C:96:5A:A3:F2:15 exclusively. You must quit other applications like UWP apps (Netflix), Steam, Uplay, NVIDIA IN-GAME before activating the 'Hide DS4 Controller' option. For more info check https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
5/1/2019 11:51:00 AM: X360 Controller #1 connected
5/1/2019 11:51:39 AM: Closing connection to ViGEmBus
5/1/2019 11:51:39 AM: Connection to ViGEmBus established
5/1/2019 11:51:39 AM: Plugging in X360 Controller #1
5/1/2019 11:51:39 AM: X360 Controller #1 connected
5/1/2019 12:01:08 PM: Unplug X360 Controller #1
5/1/2019 12:01:08 PM: DS4 Controller #1 connected


For some reason I get that Warning about hiding.  I have to hide and un hide my controller sometimes for some games that "require"  hidden to be checked to function  (monster hunter world and a few others)  As of right now Hide is unchecked even though the warning is in this log

**Comment by Ryochan7** [comment]
I will give this a try but I will be upfront and say that I have never liked the macro system that DS4Windows has.

**Comment by mika-n** [comment]
See this wiki page for more info about the exclusive mode (=Hide DS4 Controller -option). 
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Hiding the physical DS4 controller is often must have for many games because otherwise those may do all sort of weird things because of "double inputs" (ie. events coming from the phyiscal DS4 controller and from a virtual controller at the same time).

If you cannot get exclusive mode (=HideDS4Option) to work reliable then alternative option is to use HidGuardian tool (the wiki page has instructions how to install it). HidGuardian can hide the physical controller in scenarios where exclusive mode fails.

Also, your logfile shows several "controller #1 using this-and-that profile". Are you using auto-profile opion to switch profiles automagically based on running foreground apps? If yes then try without auto-profile linking because it may have something to do with special actions (ie. which actions are enabled per profile).

**Comment by eclipsaa** [comment]
No I only use a main profile.  The other profiles I have were remapping attempts to make RTS's use a controller for "lazy gaming"  

The only profile I use is the main one (witch you suggested starting a new profile and thats what im using now)   

I play FFXIV mainly and it never had any issues with hiding option.  If I do hide DS4windows then FFXIV cant see the controller.    So i have to keep the option turned off

**Comment by mika-n** [comment]
And third the special action you have recorded didn't use "Record Delays" option. This means that all events are sent out as one big burst and if those are sent out too fast then the system may register just one key press (or you are not able to observe but one press because the sequence went so fast).  Okey, you are trying to record a veeery fast rapid fire but as a test please test how it goes when you tick the "record delays" option also when you record a macro sequence.

**Comment by Ryochan7** [comment]
> Though I do have a question. You keep setting other buttons to macro Square but not square... Is there a reason why you never do the same button to macro itself?

Okay. You can't set it up like this. The Special Action system is separate from the profile mapping. The mapping in the profile will end up taking priority so the X Button Up event will never be sent. I have tested other controller button bindings in a macro and those work as expected.

**Comment by mika-n** [comment]
> Okay. You can't set it up like this. The Special Action system is separate from the profile mapping. The mapping in the profile will end up taking priority so the X Button Up event will never be sent. I have tested other controller button bindings in a macro and those work as expected.

Jep. I have never used that Controls tabpage to bind a key to a macro. I have always used it via special actions and it works fine. But if Eclipsa tested these special actions by using a default new profile then there shouldn't be any custom bindings in Square or Cross or whatever key.

**Comment by eclipsaa** [comment]
Square dose what square dose,  I want square to do auto fire using the square command.  I dont want trigger to use square auto fire....  
 
Plus i have tried with the delay and without.  nothing works

**Comment by Ryochan7** [comment]
You have to set unbound for Square in the profile in order for that Special Action to do anything. Also, it seems like only a Play Once macro can be bound in Special Actions. You can move that macro to a profile assignment mapped to Square and then use Repeat While Held. That configuration works.

**Comment by eclipsaa** [comment]
Okay Ryochan7.  I did what you said and i got the macro from that system to work.  Had to unbound the Square and X button for it to even work.   Strange....  But now with the other macro system theirs no  "Hold button to repeat"  function....  How do I get it to work so if i hold down the button it repeats ?

**Comment by mika-n** [comment]
I tested this again via "Controllers" re-mapping. It works but I had to use "record delays" option to record square button down and up events. Then I used Notepad to edit a profile file to fine tune the delay a bit shorter to make it behave like a fast rapid key.

If I bind and recorded (in Controllers key binding screen) a macro to square button without delays and set that macro to "repeat while held" option, it didn't seem to do what I expected it to do. Or it does key down and up events so fast (because there is no delay) that I and ControlPanel Joy.cpl and html5gamepad test app were not able to register that button event. Could be that it works but goes through and repeats "too fast" to be visually observed.

However, when I bind and recorded a macro to square button with "record delays" option and did square down -> wait fraction of a second -> square up -> wait faction of a second type of sequence then "repeat while hold" bind macro seemed to do what I expected it to do (or I was now able to visually observe the btn triggering in test apps).

It is a bit difficult to fine tune the length of the delay between events through macro recorder but after saving the profile I opened the "default.xml" profile file in Notepad (or whatever profile you have) and modified the square binded macro as follows:

```
  <Control>
    <Macro>
      <Square>263/330/263/330</Square>
    </Macro>
    <KeyType>
      <Square>HoldMacro</Square>
    </KeyType>
  </Control>
```

The first 263 is square btn down and then delay 30ms (value 330 = 30ms).
The second 263 is square btn up and another delay of 30ms before optionally repeating the cycle if the square button is hold down (keytype is HoldMacro to repeat).

This way it was not necessary to use specialActions and multi-action macro option. Although it is a matter of taste which way is easier and more intuitive to do it.

One thing is true that special actions "Record macro" option should probably have "repeat while trigger key hold down" option just like Controllers bind/recordMacro screen has. I can see how it could be useful in some scenarios. If certain macro sequence is something you want to use with different profiles then special actions make it easier to share the same macro definition in all profiles.
