### ISSUE TITLE
left analog not working properly

### ISSUE THREAD

**Issue by apoklyps3** [Ryochan7/DS4Windows#679]
not sure when this went wrong, but now my left anal stick chockes when holding a direction.
noticed this after I wanted to play some crash bandicoot where left analog stick is used alot. and while I hold up the character just stops trepidates on the screen as if I'm holding up and down at the same time and only starts to go up again after I release the stick and then hold it up again.

**Comment by mika-n** [comment]
I doubt that there is common bug in how the LS is handled because it would have generated tons of bug reports.  Maybe you are experiencing a deadzone issue? In this case LS deadzone in DS4Win profile settings is too small because your gamepad is physically wear out and LS stick is no longer as stable as it used to be.

Open WinOS gamepad properties screen for the virtual controller and see how it registers button, LS and RS. L1 and L2 movements. If it really gets stuck then you should see it here also. DS4Win app itself has a similar tabpage also where you can see analog axis and gyro movements. That screen would also show the size of deadzone "circle" around the axis center point.

![DS4Win_JoyControlPanel](https://user-images.githubusercontent.com/35538525/57029071-66864a00-6c49-11e9-8755-393ca20faa70.png)

**Comment by apoklyps3** [comment]
no issues there.
I think you missunderstood the situation. it doesn't get stuck in up direction....it just stops from going up

**Comment by mika-n** [comment]
Very strange. I have to say that if that bug is because of physical controller or DS4WinApp then the same behaviour should be seen in Joy.cpl controlPanel applet because DS4Win app doesn't really care about which app is using the virtual re-mapped output controller.  Hmmm.... Unless rumble has something to do with this issue. Does the game use rumble motor? If it does then try to set rumble to 0% level in DS4Win app to disable it. 

Or do you have "Flush HID" option checked in a profile? Untick it because flushing a hid message queue may cause some hid events to be lost (ie. WinOs level hid queue is flushed down the toilet before events waiting there were actually handled by DS4Win app).

**Comment by Ryochan7** [comment]
I would need access to the profile to get an idea about what is happening. If it is not just some sort of mapping conflict in the profile, there are some other common problems that can come up.  Maybe it could be an exclusive mode problem when the game is trying to use both controllers at the same time and getting confused. Flush HID is another possible issue as that option is known to cause lost input states; the option has only been left in the program for backwards compatibility although the current default for new profiles is false.
