### ISSUE TITLE
[Feature Request] Remaining Settings for Sixaxis Controls

### ISSUE THREAD

**Issue by Aurmeilius** [Ryochan7/DS4Windows#68]
Thanks for picking up the project!

This is probably a niche request, but could there be anti-deadzone, max zone, curve (input), and output curve settings for sixaxis controls (L2/R2 for the latter two as well) in a future update?

**Comment by Ryochan7** [comment]
Adding the extra settings for L2 and R2 would be feasible. I haven't had a use for those settings for the triggers so there had been no reason to add them. Doing the same for the sixaxis controls might not be so feasible. For now, I am just focusing on getting the most common uses for the gyro working. Those two use cases would be Gyro mouse and tilt controls for lean actions in some games.

I will take a look at this in the future.

**Comment by Aurmeilius** [comment]
Hmm.. I guess I could try to add this feature for myself in the meantime. What is your setup during compilation though? I get a whole bunch of errors from your latest version of source code.

**Comment by rafsanjani** [comment]
it depends on some nuget packages so you will have to be connected to the internet for VS to automatically download and include those packages.

**Comment by Ryochan7** [comment]
I am using VS2015 on my setup. TaskScheduler is the main nuget package that DS4Windows depends on but Visual Studio should download and install the dependency automatically when you open the DS4Windows solution. Also, the build target framework for DS4Windows should be .NET Framework 4.5. I am not sure if DS4Windows will compile properly when using other versions of .NET. The only thing I know for sure is that there are some portions of the source code that utilize features that require at least .NET Framework 4.0 to be used. Overall, there shouldn't be any major manual setup required to get Visual Studio ready to compile DS4Windows.

**Comment by Ryochan7** [comment]
A lot of refactoring had to be done but additional settings have been made for sixaxis controls in version 1.4.86. The main one left out is the old curve (input) option since I consider it a deprecated option. That tab has been moved to show its decreased importance in the application. L2 and R2 now have curve options as well.

**Comment by Ryochan7** [comment]
Adding a programming note here for future reference. Like the README file stated previously, .NET 4.5 was the minimum version needed to compile and run DS4Windows. I had no idea what exactly enforced that requirement before. The use of the async C# keyword and some I/O routines were the reasons that version 4.5 was required to build DS4Windows.

As of now, .NET 4.5.2 is the minimum supported version of .NET needed to build DS4Windows. The version number bump is due to Microsoft discontinuing support for version 4.5 back in January 2016.
