### ISSUE TITLE
Driver Issue Virtual Gamepad Emulation Bus

### ISSUE THREAD

**Issue by Dopenope1** [Ryochan7/DS4Windows#690]
Virtual Gamepad Emulation Bus Driver Error 52
![Capture](https://user-images.githubusercontent.com/50360661/57288766-b69f5980-70ec-11e9-89c1-be91dc4cde5a.PNG)

**Comment by Dopenope1** [comment]
I just Installed ViGEmBus_Setup_1.16.112 then it say Failed and Tried To Restart then nothing work 
![Capture](https://user-images.githubusercontent.com/50360661/57289152-6bd21180-70ed-11e9-999a-873f7972c92d.PNG)

**Comment by mika-n** [comment]
See https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting page for more info.

There it is explained what to do in Windows 7 to make it support ViGem digital signature (ie. install Microsoft Win7 SP1 + additional MS encryption protocol hotfixes).

I'm assuming you have Win7 because this is a typical problem in Win7 platform. If not then please read through the Troubleshooting page to list all required information about your environment. It is a bit difficult to help if you provide only half of the information.

**Comment by Dopenope1** [comment]
Thanks
