### ISSUE TITLE
auto update doesent work

### ISSUE THREAD

**Issue by hanswurst31** [Ryochan7/DS4Windows#693]
auto update doesent work

**Comment by mika-n** [comment]
In which version you are currently?  
Do you have a screenshots of what happens when the app tries to update itself? Any error messages?

If you are in very old version then downoad the latest (at the moment V1.7.8) version manually because there has been some changes in the updater app in couple recent version. Could be that veeeeery old version doesn't know how to update itself anymore.
https://github.com/Ryochan7/DS4Windows/releases

**Comment by Ryochan7** [comment]
THE THING DON'T WORK. Closing.
