### ISSUE TITLE
Language selection does not work

### ISSUE THREAD

**Issue by ssc19940105** [Ryochan7/DS4Windows#694]
Language selection does not work!!!

**Comment by mika-n** [comment]
Works here at least between English and Finnish languages in the latest V1.7.8 version.
What languages you are trying to use? 
Try other languages just for testing purposes. Is it so that none of the languages work there (except default English) or just certain language resources don't work? For example Finnish language (Suomi) works here. Does it work there too? It this works but your own language doesn't work then please provide more info.

Please take a look at this page for tips what information (at minimum) to provide in an issue post while submitting a bug report.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting
