### ISSUE TITLE
DS4Windows 1.7.8 Wont open 

### ISSUE THREAD

**Issue by Darkdeity9194** [Ryochan7/DS4Windows#695]
For some reason the DS4Windows app just wont open or even appear in task manager despite it having admin privileges. I deleted my install and re-downloaded and nothing has worked. Before this issue I was also noticing that having it open minimize on start up wasn't working either but it wasn't too much a hassle since the program was working until today. Any idea what I can do?

**Comment by mika-n** [comment]
Take at look at this page: https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

As a testing purpose try to run the app from CMD shell in case it dumps out some error messages to a console. If you run the app via FileExplorer then you won't see these error messages because the console closes automagically (too quickly to be seen).
- Run "cmd.exe" command using "Run as Administrator" option (right mouse button)
- CD to DS4Windows installation folder and run DS4Windows.exe executable

**Comment by mika-n** [comment]
Could be the same case as in this issue https://github.com/Ryochan7/DS4Windows/issues/697

**Comment by Darkdeity9194** [comment]
I ended up restarting my computer again, re-installing DS4W and it just fixed itself. Still won't launch at boot up but it works again which counts.

**Comment by Ryochan7** [comment]
> DS4Windows app just wont open or even appear in task manager despite it having admin privileges

That would explain why it does not launch at boot. You cannot use that option when using Run at Startup. It is a Windows security feature.
