### ISSUE TITLE
DS4Windows will not open

### ISSUE THREAD

**Issue by Evernow** [Ryochan7/DS4Windows#697]
Hello! Question, whenever a friend of mine tries to launch DS4Windows now, the application simply doesn't launch. Even when he selects to run it as admin, a white box simply shows up for 2-3 seconds and nothing happens. Any advice?

Using latest 1.7.8
Windows 10
Official Playstation 4 controller

**Comment by Evernow** [comment]
![DeepinScreenshot_select-area_20190509170542](https://user-images.githubusercontent.com/44484725/57486803-e3827680-727c-11e9-9f02-ae4e2fcd2ac4.png)
Unfortunately get no errors

**Comment by mika-n** [comment]
Did you upgrade an existing version of DS4Windows and it worked just fine? What version was that?

Or is this a new fresh installation?

Would it be possible to test previous releases one by one to see if some of those earlier versions work? It would help Ryochan7 to track down potential changes in the launch and installation procedure causing this kind of problems.
https://github.com/Ryochan7/DS4Windows/releases

Take a look at the following doc page. There is a paragraph about required VC++ and MS .NET Framework library versions. Make sure you have those installed:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

Try to install ViGem virtual gamepad driver before launching DS4Windows because DS4Win checks if this driver is installed and tries to install it automagically if the required ViGem is missing. If this is a new fresh installation and ViGem is missing then could be that something goes wrong while checking and installing the driver. ViGem installer for the latest ViGem version:
https://github.com/ViGEm/ViGEmBus/releases/latest

**Comment by Evernow** [comment]
> Would it be possible to test previous releases one by one to see if some of those earlier versions work? It would help Ryochan7 to track down potential changes in the launch and installation procedure causing this kind of problems.

Question how exactly do we test older versions? When we try to install one, it just says its up to date? 
Also not 100% sure when the problem occurred, may have been on 1.7.7 then updated to 1.7.8 when it started not working

**Comment by mika-n** [comment]
You can download those old ZIP files and extract to a new folder. And then run DS4Windows.exe executable.  Your existing profile probably has "check updated version" option enabled, so that's why DS4Windows executable checks an existing version. 

You can disable it even when you cannot open DS4Win app. Navigate to "%APPDATA%\DS4Windows" folder (type that in FileExplorer address field) and modify Profiles.xml file. Set CheckWhen option to value 0 to disable the version check at startup time.

`<CheckWhen>0</CheckWhen>`

And now when we are talking about previous version and settings/profiles then maybe there are something in existing profile files causing weird problems. 

To test this theory backup (zip or copy to other location) all files from "%APPDATA%\DS4Windows" folder location (and subfolders), delete all files and profile subfolder in "%APPDATA%\DS4Windows " folder. Then try to start DS4Windows app. It will create new default config and profile files (actually at first time it will ask if you want to use programfiles or appdata folder as config file location. Usually appdata is better option because sometimes programfiles location has permissions problems).

Did you try to install the latest version of ViGem driver manually using the link I mentioned in the previous comment? There has been some changes in DS4Win app relating how it checks and installs ViGem driver (if it is missing or too old version). Anyway, you can always download and install ViGem driver before running DS4Win app to make sure that the driver is OK.

**Comment by Evernow** [comment]
> You can download those old ZIP files and extract to a new folder. And then run DS4Windows.exe executable. Your existing profile probably has "check updated version" option enabled, so that's why DS4Windows executable checks an existing version.
> 
> You can disable it even when you cannot open DS4Win app. Navigate to "%APPDATA%\DS4Windows" folder (type that in FileExplorer address field) and modify Profiles.xml file. Set CheckWhen option to value 0 to disable the version check at startup time.
> 
> `<CheckWhen>0</CheckWhen>`

He just ran 1.7.4 just fine with that option! 

He then tried to run 1.7.7, same issue as before. 

He then tried to delete the all the subfolders in the DS4Windows directory, and then tried to install the latest 1.7.8 and it worked! Thank you very much! Seems to work perfectly now! Thank you very much!

**Comment by mika-n** [comment]
Do you still have a backup copy of those problematic profile and config files? 
If you have those then would it be possible to zip those files and add as an attachment into this issue thread? 

It would  be interesting to know which option causes this problem because DS4Windows should not behave like that no matter what there are in the profile and config files.

**Comment by Evernow** [comment]
I am sorry for such a late reply, I believe this is what you wanted? 
[OldDS4Windows.zip](https://github.com/Ryochan7/DS4Windows/files/3178972/OldDS4Windows.zip)

**Comment by mika-n** [comment]
Thanks for the zip file. The content of Actions.xml and Auto_Profiles.xml files were a bit weird. Those files had nothing but empty space characters. Definetly not what DS4Windows app expects to find from those files. And the name of the "Auto_Profiles.xml" file is weird because it should be nowadays "Auto Profiles.xml" file.

Either those are some veeeeeeery old config files from some ancient DS4Windows version or from an abandoned JayKing version of DS4Win app.

Cleaning of the config and profile folder fixed the issue of corrupted/bad/unsupported xml config files. But maybe DS4Win app needs some error checking/exception handling while reading those XML files to make sure that it doesn't crash if those files are empty or nothing but space chars.
