### ISSUE TITLE
ViGem driver have updated itself, asked to reboot, then DS4 Windows wont detect it

### ISSUE THREAD

**Issue by mooms06** [Ryochan7/DS4Windows#701]
ViGem driver asked for update, I let it update itself, it asked to reboot, then on next reboot DS4 Windows wont detect it and asked for install.

Installing it trough DS4Windwos failed, I had to uninstall ViGem driver then I could install it from DS4Windows again.

Using v17.8. 

If we should not update ViGem driver, maybe a message saying it would be a goo didea

**Comment by Ryusennin** [comment]
That's because you overlooked the (admittedly confusing) instructions given by ViGem.

ViGem didn't update your driver, it actually uninstalled it while asking you to manually run the new 1.16.115 installer after that.

https://github.com/ViGEm/ViGEmBus/releases

**Comment by mika-n** [comment]
The ViGem updater tool is NOT part of DS4Windows app, so DS4Windows app cannot control what that vigembus updater does or doesn't work and shows on screen. If you want to disable the VigemBusUpdater then disable "ViGemBusUpdater" TaskScheduler job or modify C:\Program Files\Nefarius Software Solutions\ViGEm Bus Driver\ViGemBusUpdater.ini file and set CheckFrequency option to something less frequent than 1 or 2 days.

**Comment by mooms06** [comment]
I have disabled the task.

DS4Windows have downloaded & installed ViGEm bus version 1.16.112, since it works fine, I suppose there is no need to update to .115 ?

**Comment by mika-n** [comment]
No because the ViGemBus driver is identical in 1.16.112 and in .115 versions. The newer version has just some installer fixes, but nothing in the driver itself.

**Comment by mooms06** [comment]
That's what I thought.

One more question: at install time, is DS4Windows downloading the latest version or a fixed version of ViGEm ?

**Comment by mika-n** [comment]
At the moment DS4Windows app uses a fixed URL to download the latest TESTED and "approved by DS4Win app" version. 

`InstallerDL = https://github.com/ViGEm/ViGEmBus/releases/download/v1.16.112/ViGEmBus_Setup_1.16.112.exe`

But, feel free to update the ViGemBusDriver using vigem updater, because if the new vigem driver still has the same driver identifier (usually should be the same unless it is a major new gadget) then DS4Win app won't try to downgrade the driver. You just have to hope that the ViGem API interface has remained the same and the new driver still works over the same API communication.

**Comment by mooms06** [comment]
Thanks for the answer, I will let DS4Windows use the approved version and don't update unless needed.

**Comment by Ryochan7** [comment]
Only the installer has changed. The same driver version (1.6.112) gets installed with the newest installer. DS4Windows now links to the updated installer.
