### ISSUE TITLE
Exclusive Mode No Longer Works for Windows 10 1903

### ISSUE THREAD

**Issue by parkel42** [Ryochan7/DS4Windows#708]
Just updated my computer to Windows 10 1903 (May update). 

Exclusive mode was working with Windows 10 1803/1809, but broke with 1903. Behaviour is as if HID Guardian was never installed or the AffectedDevices reg key was never changed.

**Comment by teijiIshida** [comment]
According to the guide, you have to reinstall the HID Guardian every time you update Windows to a new major version, which is what you did.

**Comment by Geroyuni** [comment]
I reinstalled HID Guardian after the 1903 update and couldn't get it to work regardless

**Comment by Ryochan7** [comment]
I want to think this has happened to me once after a Windows update but I cannot remember when that was. If I remember correctly, the problem is that Windows can overwrite the UpperFilters registry value to a default state. Unfortunately, that registry value is used to get HidGuardian registered to Windows as a filter driver so HidGuardian will not be active despite the driver still being installed on a system. Overwriting that registry value during certain updates seems like a deliberate design decision made by Microsoft so it would be a pain to work around that when it happens again.

**Comment by parkel42** [comment]
I managed to fix the issue, thanks @teijiIshida. Had to completely uninstall HidGuardian, restart, then install HID Guardian again. 

I did make a backup of HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HidGuardian before uninstalling HidGuardian and reimported the reg key post installation. 

@Ryochan7 - seems like a small price to pay to use DS4 controllers on Win 10 I suppose.
