### ISSUE TITLE
Support for DS4 Wired Controller (Multilaser Warrior)

### ISSUE THREAD

**Issue by GalahadBR** [Ryochan7/DS4Windows#713]
Hi,

I saw on the issue #312 that you were able to add support to a Generic DS4 controler by using the VID and HID from the controller. I have one DS4 wired controller which seems to be generic, although, the company that build it seems to have the license to do so:

https://www.multilaser.com.br/controle-warrior-ps4-multilaser-preto---js083-/p

The controller works fine on PS4 and on PC as well, but as DINPUT. If possible, can you add the support for this controller? This is the VID and PID I was able to find, hope it is the right one:

HID\VID_0C12&PID_57AB&REV_0100&Col01
VID 0C12
PID 57AB

Thanks in advance.

**Comment by mika-n** [comment]
Here is a test version which (hopefully) adds support to the Warrior Joypad JS083 gamepad. 

If this doesn't work then please post what do you see in DeviceManager / HumanInterfaceDevices list for the controller (especially Properties/Details and DeviceDescription, HardwareIDs, Capabilities, DisplayName and Provider property values).

[DS4Windows_WarriorJoypad083_Test_64bit.zip](https://github.com/Ryochan7/DS4Windows/files/3226732/DS4Windows_WarriorJoypad083_Test_64bit.zip)

Try to test the functionality of buttons, triggers, axies, lightbar, touchpad and gyro sensors (if there are gyro sensors in the gamepad because some 3rd party gamepads don't have DS4 type of gyro sensors).

**Comment by GalahadBR** [comment]
Hi mika-n,

It works! I tested all the buttons, trigger and axies and it worked flawlessly. Touchpad and gyro are not a thing in this controller, touchpad only has one click button which did work also. The only thing that I was not able to configure, was the lightbar. It starts with stock color and I was not able to change it.

Regards

**Comment by mika-n** [comment]
Okey. Good to hear that at least all crucial things of the Warrior gamepad works just fine. 

The lightbar issue is a bit annoying, but it is a bit difficult to debug without having an actual controller device. It could be an issue in the Warrior gamepad driver, also.  Someone with the device should debug it in more details. Sorry.

I will post the code change for Ryochan7, so he can review and include it in one of the upcoming releases. Once the code change is integrated into the official release then "What's New" should have a note about it. Keep eye on the new releases web page: https://github.com/Ryochan7/DS4Windows/releases

Meanwhile you can continue to use the test version, because it is based on the currently latest V1.7.9 version (added with unofficial Warrior gamepad support).

**Comment by GalahadBR** [comment]
I thought so. But it does not bug me at this time. I appreciate all the help =). Have a nice day!
