### ISSUE TITLE
Nothing works after removing HIDGuardian

### ISSUE THREAD

**Issue by RHReaper** [Ryochan7/DS4Windows#715]
Hello everyone.

Apologies if this has been asked before, I couldn't seem to find it.

I was trying to get DS4Windows in exclusive mode, wasn't working so I found out about HIDGuardian and used that. Worked fine.

However I just wanted to try it out, now when I uninstall HIDGuardian, my controller doesn't work at all.

I've tried reinstalling all the drivers from DS4Windows, removing the controller from the Device Manager, rebooting after each step, followed the guides online about enabling the controller or reinstalling those drivers, nothing worked.

I tried using InputMapper and that didn't work, so I guess the issue is with HIDGuardian not being removed properly. I reinstalled it, and it's working again but in exclusive mode, which I do not want.

Hope anyone can help because I'm at a loss, and really don't want to have to reinstall Windows.

Edit: I removed HIDGuardian from the device manager. Ideally I'd like to be able to toggle it on and off, even if a reboot is required, but Disabling it from the device manager didn't work.

Thank you.

Kind regards.

**Comment by mika-n** [comment]
If you want to temporarly disable HidGuardian functionality then you don't have to uninstall or disable it. You can simply modify HidGuardian registry setting "AffectedDevices". This setting lists which devices HidG driver hides from other apps (or from processes NOT listed in Whitelist entry).

If you want to disable the hiding (ie. gamepad should be visible to all processes in a normal way) then you can either clear AffectedDevices entry or add some dummy tag at the end of device path string. Now when you re-connect the gamepad then HidG won't hide the device because it is not listed as "affected device".

You could have a reg file with correct AffectedDevices value and another reg file with with dummy appended tags (or completely empty AffectedDevices option value). If you have a desktop shortcut to these REG files then you could define the behaviour of HidG by clicking these shortcuts (ie. import one of the reg files into system registry to modify the registry on the fly). You can export registry values into a REG text file with "regedit" Windows tool.

![DS4Win_HidGuardian_DisableHidingOfDevices](https://user-images.githubusercontent.com/35538525/58643236-8facff80-8307-11e9-9d31-7bd03fe86506.png)

**Comment by RHReaper** [comment]
Hello mika-n, thank you for your reply.

That's loads of info, thank you for taking the time to write all of it and follow it up with screenshots too, very much appreicated.

I do have a few minor questions, I haven't used regedit much before. I can 'Export' when I right click on the 'Parameters' folder, to get the shortcut's to the edit. Is that correct to export it, or wrong? I'm hesitant to try on my own as I don't want to cause any problems I don't know how to fix.

When I modify the entry, I have these 5 lines listed:

HID\VID_054C&PID_05C4
HID\VID_054C&PID_09CC&MI_03
HID\VID_054C&PID_0BA0&MI_03
HID\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&05c4
HID\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002054c_PID&09cc

I'd prefer a dummy tag. Do I add the tag to all 5 of these lines? Or just the 2 you listed?

And just to confirm, I export the regedit as it is (working) then modify it to disabled, then export that one too, as a file to disable HidG?

Sorry for all the questions, and thank you again for your help.

Kind regards.

**Comment by mika-n** [comment]
>I can 'Export' when I right click on the 'Parameters' folder, to get the shortcut's to the edit. Is that correct to export it, or wrong? 

Yes. The "EXPORT" menu command in regedit tool is the correct way to export a selected section (the selected registry section and all children).

I recommend you to export "Parameters" section of the HidGuardian entries and then open the export file in Notepad (*.reg files are text files) and remove WDF and Whitelist entries from the exported file. Leave just the definition of "AffectedDevices" entry.

![DS4Win_HidGuardian_RegFileEdit](https://user-images.githubusercontent.com/35538525/58662495-001d4600-8333-11e9-9e68-8289215face4.png)


> When I modify the entry, I have these 5 lines listed:
> I'd prefer a dummy tag. Do I add the tag to all 5 of these lines? Or just the 2 you listed?

In practice the first two are probably relevant with DS4 gamepads, but it doesn't hurt anything even when you add a dummy tag to all 5 lines.


> And just to confirm, I export the regedit as it is (working) then modify it to disabled, then export that one too, as a file to disable HidG?

Exactly. This way you have two REG text files and the first one has default values you use when HidGuardian needs to hide defined devices (=DS4 gamepads). Then you can modify the AffectedDevices entry in regedit tool and re-export the selected registry section to a new file. Now you have the second reg file with dummy tags (= device IDs which don't match with DS4 gamepad device IDs).

If you place these REG files on a desktop (or shortcuts to the files) then you can double click those files and import the value of AffectedDevices registry entry. This way it is easy to toggle HidGuardian on/off to hide or not to hide DS4 gamepads.

**Comment by RHReaper** [comment]
Hey.

Thank you again for the reply.

I've done all of that and it's working just fine. Thank you very much for all the help.

I do need to reboot to get it to work, I expected that and I'm ok with it, just mentioning it incase anyone else comes across this.

I do have one final question, if you know the answer, and that is how to uninstall HidG? I don't want to just yet, but maybe when I don't need it again.

It keeps coming up with a UAC prompt when I log in, even when disabled. Not a big deal, but I rarely use exclusive mode so perhaps removing it would be for the best, and reinstalling it when the need arises once or twice a year. Alternatively, a way to 'auto allow' that particular prompt would work, as I do like to keep UAC on. I could look that up online I would think.

Thank you once again.

Kind regards.

**Comment by Ryochan7** [comment]
Unfortunately, the UAC prompt appears because DS4Windows launches a second program that requires access to the system registry to make the necessary Whitelist entry for HidGuardian. If you are running DS4Windows at login, you would have to start the program as a Task in order to allow the program to get admin privileges with no UAC prompt. Running DS4Windows normally and using HidGuardian will require a UAC prompt to appear.

![runastask](https://user-images.githubusercontent.com/581968/58675514-44501c80-831a-11e9-986b-197c49936647.png)

**Comment by mika-n** [comment]
> I've done all of that and it's working just fine. Thank you very much for all the help.
> I do need to reboot to get it to work, I expected that and I'm ok with it, just mentioning it incase anyone else comes across this.

Strange. Here this AffectedDevices sysreg import trick works without reboot. However, the controller needs to be disconnected and re-connected to the PC to "refresh" the status of visible controllers. Some apps probably won't see the status change until you re-start the game/app because HidGuardian does its magic when an app tries to open a connection to gameapad controller device.

 
> I do have one final question, if you know the answer, and that is how to uninstall HidG? I don't want to just yet, but maybe when I don't need it again.

One way to do it is to use DeviceManager and choose "Uninstall device" menu command for "System Devices/HidGuardian Virtual Device" device AND check the option "delete the driver software for this device" checkbox option in uninstall confirmation screen.

**Comment by RHReaper** [comment]
Hey Ryochan7, thanks for your input.

Alright, makes sense. I am running it at login, it's pretty much always running. Does it only need to be run as admin once, when setting it to run as a task? Or would it always have to be run as admin for that to apply?

Is uninstalling HidG very complicated? If it is then I won't try, a UAC prompt isn't too much of a bother.

Also I would like to take this opportunity to thank you very much for all the work you've done since picking up DS4Windows. It's a great program I've recommended to many mates. Thank you.

Kind regards.

**Comment by mika-n** [comment]
> Alright, makes sense. I am running it at login, it's pretty much always running. Does it only need to be run as admin once, when setting it to run as a task? Or would it always have to be run as admin for that to apply?
 > Is uninstalling HidG very complicated? If it is then I won't try, a UAC prompt isn't too much of a bother.

There is a workaround to "eliminate" UAC admin prompt when you have disabled the use of HidGuardian by using the system registry trick described earlier. You don't have to uninstall HidGuardian device driver if you rename the HidGuardHelper.exe tool in DS4Windows installation folder to something else, for example, HidGuardHelper.exe.disabled

DS4Windows.exe application itself doesn't try to modify system registry on the fly (ie. sysreg editing requires UAC privledges), it is the HidGuardHelper.exe tool in the same folder.

Now, if you rename this tool then DS4Windows.exe won't find it and doesn't call it to modify HidGuardian Whitelisted sysreg entries. Whitelisted HidGuardian sysreg entry tells to HidGuardian device driver which processes should see the DS4 gamepad device. The device is hidden from all other processes (ie. not whitelisted processes).

So, try to do this:
- Generate those two sysreg text files described earlier (hidGuardian_on.reg and hidGuardian_off.reg)
- If you use HidGuardian_off.reg file to modify or clear AffectedDevices entry then rename HidGuardHelper.exe to HidGuardHelper.exe.disabled name at the same time. Now the next time you launch DS4Windows app it won't ask for UAC priviledges (or hidguardhelper doesn't ask it because it is not called).
- When you want to enable HidGuardian then import the HidGuardian_on.reg sysreg file AND rename the hidguardhelper.exe.disabled file back to the origial hidguardhelper.exe name and re-launch DS4Windows application.

If you do a BAT batch script file then all these steps can be done as "one click process".

**Comment by RHReaper** [comment]
Hey mika-n,

Sorry, I missed your previous message.

I actually never tried to reconnect the controller, I tried restarting DS4Windows instead. I just tried it now and that works, so I don't need to reboot at all. Thanks for that =)

In regards to uninstalling HidG, I had done it that way before and it stopped DS4Windows from detecting the controller at all (and later I tried InputMapper too, with the same results). Reinstalling all the drivers, nothing worked until I put HidG back on.

To your above post, thank you for explaining that. It makes sense and I have tried it, it works exactly how you said.

Doing a BAT file seems like the best way to do it, so I would need to make it rename the EXE to .disabled and run the REG file that disables the entries you explained above.

So, would I need to make 1 BAT file to enable it all and another to disable it, or just 1 BAT file that will toggle it?

Thank you again, your help is very much appreciated.

Kind regards.

**Comment by mika-n** [comment]
> Doing a BAT file seems like the best way to do it, so I would need to make it rename the EXE to .disabled and run the REG file that disables the entries you explained above.
> So, would I need to make 1 BAT file to enable it all and another to disable it, or just 1 BAT file that will toggle it?

Like all car dealers say: "your gasoline mileage may vary".  Either way works. 

It might be a bit easier to do via 2 separate batch files because then you don't have to try to detect the existing status.
If you do it via 1 toggle batch file then one way to detect the "status" would be to check the existence of hidguardhelper.exe file. This way the toggle batch file knows whether it needs to import xxx_on.reg or xxx_off.reg file and how to rename hidguardhelper file.

**Comment by RHReaper** [comment]
Hey, thanks for the reply.

Great, all done. Working just as  you said, thank you both very much!

I've pasted the BAT files contents at the bottom, incase anyone else with the same issue comes here and wants to use it. Just googled it so there may be room for improvement. Just remember to adjust the path to the EXE accordingly.

I'll also leave the thread open for a day or 2, incase anybody points out an error with the batch files or has anything else to say.

Thank you once again for your help, changing an evening of frustrating driver reinstalls of no avail, to something working better than how I hoped for.

Thank you.

I wish you all the best.

Kind regards.

************************************************************************************************
**HidGuardian Enable.bat**
@echo off
rem  set __COMPAT_LAYER=RunAsInvoker  
REGEDIT.EXE  /S  "E:\Programs\DS4Windows\HidGuardian Toggle\HidGuardian Activated.reg"
RENAME "E:Programs\DS4Windows\HidGuardHelper.exe.disabled" "HidGuardHelper.exe"
pause


**HidGuardian Disable.bat**
@echo off
rem  set __COMPAT_LAYER=RunAsInvoker  
REGEDIT.EXE  /S  "E:\Programs\DS4Windows\HidGuardian Toggle\HidGuardian Deactivated.reg"
RENAME "E:Programs\DS4Windows\HidGuardHelper.exe" "HidGuardHelper.exe.disabled"
pause
