### ISSUE TITLE
I can not use keyboard letters

### ISSUE THREAD

**Issue by HadesIzanami** [Ryochan7/DS4Windows#717]
I will be brief in what happens, when I try to use the letters of my keyboard to place them in a control button, the program simply goes crazy, I even try to put a name and the letter that you assign to that control button is typed alone many times. After assigning two letters to different buttons, it just does not let me assign more buttons, the program just does not allow me to continue using it.

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

Take a look at notes about deleting all files (well, DS4Win config files) and let DS4Windows app to re-create those files with default values. There has been cases where veeeeery old config files have had something strange after upgrading to a new version of DS4Win app. Delete everything (or backup/copy to some other place) from %APPDATA%\DS4Windows\ folder structure.

If that doesn't help then follow instructions in the troubleshooting page for posting log messages here.

**Comment by Ryochan7** [comment]
This is likely a dead zone problem. You probably don't have a dead zone set for your analog sticks so it is likely that any keyboard keys mapped to the analog stick will get activated inadvertently. Because of that behavior, the control assignment window will see a keyboard key as being held down and then map it to the selected input control.

I was playing Shadows of the Empire with a DS4 mapped to keyboard and mouse actions so keyboard output is working as expected. I can also use the keyboard to map many different input controls just fine.
