### ISSUE TITLE
mouse drifting to down-right (but never up or left) when using sticks for mouse moving

### ISSUE THREAD

**Issue by geovens** [Ryochan7/DS4Windows#724]
When i use this profile to move mouse cursor using left or right stick, the cursor sometimes drifts to right or down or both-right-and-down in a constant slow velocity even if I don't touch the stick. This does happen in 1.7.10 but not in an old version 1.4.x.

[mouse.xml.zip](https://github.com/Ryochan7/DS4Windows/files/3269165/mouse.xml.zip)

**Comment by mika-n** [comment]
You probably have too small deadzone in the left and right sticks. Remember that analog stick axies are hardly ever completely stable in hardware level even when you are not resting a thumb on them. There may be a slight movement, so to avoid those small movements you have to set a small deadzone to LS/RS.

_"DS4Windows profile editor and "Controller Readings" tab page in options. This will show you input from an analog axies and the size of deadzone range (if defined in DS4Windows profile settings)"_
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

_"A deadzone represents the region of an axis that should be considered as having zero output. Having a deadzone in place will better ensure that there is no accidental output value generated by having your finger at rest on an analog stick"_
https://github.com/Ryochan7/DS4Windows/wiki/Settings#deadzone

**Comment by Corgano** [comment]
You can see the condition of your sticks with https://html5gamepad.com/. Chances are that one of your sticks doesn't center all the way when you release it. Try another controller

**Comment by geovens** [comment]
I changed the deadzone from 0 to 0.1 and no more drifting. Thank you mika-n and Corgano. When in game there was no drifting even though the deadzone is set as 0, which I guess is because games have their own deadzone.

**Comment by mika-n** [comment]
Many games do have built-in deadzone. Sometimes this is a problem especially in racing games. Anti-deadzone feature of ds4win app can be used to overcome built-in deadzone issue.

**Comment by Ryochan7** [comment]
That is odd since binding mouse movement actions is one place where implicit dead zone settings still apply. If a dead zone of 0.0 is used for LS or RS, a default value around 0.02 will be used. Setting an appropriate dead zone is required when mapping keyboard and mouse actions to analog inputs.

I usually use around a 0.02 or 0.03 value for dead zone when mapping RS to mouse. There is a small chance for drift still when using a low dead zone but it can be easily compensated; the extra looseness of the mouse is worth it as well. A more practical value would probably be a dead zone value around 0.08 for RS.
