### ISSUE TITLE
Heavy Rain Sixaxis controls

### ISSUE THREAD

**Issue by kot-shrodingera** [Ryochan7/DS4Windows#725]
I was trying to play Heavy Rain on PC with DualShock 4 and DS4Windows (I changed controller to DualShock 4 in profile settings). Everything seemed ok, but when it comes to sixaxis controls (shaking controller), it didn't work. I'm using bluetooth adapter (NOT ofiicial Sony's). Do I need to change some settings or this isn't supported yet?

**Comment by mika-n** [comment]
DS4Win app uses VigEm device driver in the background. Unfortunately the current version of VigEm driver doesn't support touchpad regions (only touchpad click) and gyro/accelerometer sensor feeding.

**Comment by kot-shrodingera** [comment]
So there is no way to play Heavy Rain on PC with DS4 wireless (without official adapter)?

**Comment by mika-n** [comment]
Are you playing HeavyRain remotely on PC via Sony's RemotePlay for PS4? 
Have you tried connecting the DS4 controller to PC via USB cable? It should work for sure with PC and RemotePlay app without using DS4Windows app at all.  However, bluetooth connection without using Sony's official adapter may require DS4Windows app.

If you want to use button remapping capabilities with RemotePlay then DS4Windows app+dualshock4 virtual controller output type is required, BUT that combination doesn't support touchpad regions or gyroscope, yet.  But if you connect the DS4 controller to PC via usb cable then you don't need any official Sony adapters if you don't utilize re-mapping and macro capabilities of DS4Win app.

**Comment by kot-shrodingera** [comment]
No, I playing Heavy Rain Demo in Epic Games Store
- If I connect DS4 via cable everything is working, including gyro/accelerometer.
- If I connect DS4 via bluetooth and NOT using DS4Windows, noting works at all, not a single button (but in Steam, controller work perfectly this way and is fully configurable)
- If I connect DS4 via bluetooth and using DS4Windows with default profile and controller type set to DualShock 4, I can play, but not gyro/accelerometer, so cant go past controller shaking moments

**Comment by mika-n** [comment]
Jep. That's the way it is.

Bluetooth on Win10/Win7 without Sony's official adapter is a bit problematic, because not all bluetooth chips work with DS4 out of the box. Or even if it connects then nothing seems to happen when you press buttons. This is because of some Windows and DS4 hardware issues. Sure, Win10 could fix that natively in DirectInput interface, but unfortunately it doesn't. That's why bluetooth WITHOUT an official SonyWirelessAdapter needs DS4Windows application or Steam client.

Steam client does a bit like what DS4Windows does and supports also virtual gyro sensor feeding, but naturally this works only with Steam client compatible games (and launched via Steam).

DS4Windows + ViGem device driver doesn't support feeding of touchpad regions and gyro sensor, so that's why those don't work yet in DS4Win app. Author of ViGem driver (Nefarius) is working on those features in ViGem driver level and as soon those are available then I'm sure DS4Win app will support those also. Feel free to ask about it in ViGem forums.
https://forums.vigem.org/topic/224/feeding-gyro-information-into-the-emulated-ds4

**Comment by kot-shrodingera** [comment]
Ok, thanks for clarification. I'll close hthe issue
