### ISSUE TITLE
Center/Calibrate Stick Inputs

### ISSUE THREAD

**Issue by schm0** [Ryochan7/DS4Windows#729]
Hi!
On my controller, both sticks don't perfectly center.
They are always off in the same position. Is my controller broken?
Is it possible to center/calibrate the input of the analog sticks?
The windows gamepad calibration only works for the left stick (tested with html5 gamepad tester).
Currently, I work around this by setting a dead zone between 0.10-0-15.
Thanks for this great piece of software and keeping it up2date.

**Comment by mika-n** [comment]
Sounds like hardware issue. Thumbstick replacement is possible but requires soldering skills and tools, unless you are lucky one and all it takes is to cleanup dust from stick axies (still you have to open the controller case cover). 
https://www.google.com/search?q=ds4+thumbstick+fix

**Comment by Ryochan7** [comment]
It is likely a hardware problem. Even brand new sticks don't go back to absolute center a lot of times. It is best to use some amount of dead zone to work around that problem. The dead zone (and max zone) value will likely have to be changed slightly as the sticks wear out. AFAIK, a dead zone value of about 10% (0.10) is usually used in PS4 games for the analog sticks.

**Comment by Oxmaster** [comment]
I would like to see this addition.

I've replaced my left joystick because it was sticking to a side when flicked. I've ordered the orange ones, but these are 103B and the original ones are 102B but they feel much smoother. The problem is that the readings are offset slightly.
![image](https://user-images.githubusercontent.com/3867507/110520532-e0719f00-810e-11eb-88b5-a04019aae778.png)
