### ISSUE TITLE
Command line argument to turnoff

### ISSUE THREAD

**Issue by ferrelll** [Ryochan7/DS4Windows#733]
Good evening! I'm trying use DS4Windows only for motion in CEMU emulator, and I got stuck because I would need some kind of command line argument to stop and close DS4Windows. I have already tested force closing it, but it keeps the controller stuck and it doesn't revert to Steam input. Is there any possibility to add a feature like this? Something like "--turnoff" that it would behave like middle clicking the tray icon? Thanks in advance!

**Comment by Ryochan7** [comment]
Using command line argument parsing in the second instance would be feasible. However, it is likely not worth doing. What you are experiencing is an issue with using a Bluetooth connection. Once the mode change happens that is needed to get extra data from the controller (touchpad, gyro, etc.), the original DS4 DirectInput will be seen as a dead controller. You would have to manually disconnect the DS4 and re-connect it to your PC while DS4Windows is not running in order to use the DirectInput controller. That behavior is not isolated to DS4Windows. The Steam mapper exhibits the same behavior when using a Bluetooth connection. USB and Sony Wireless Adapter connections do not exhibit that type of behavior.

This is not worth pursuing.

**Comment by ferrelll** [comment]
I do understand that just disconnecting and expecting a reconnect is unrealistic. What I wanted to achieve is to automate DS4Windows to turn off the controller, using the function to turn them off when closing the program. Right now, if I kill DS4Windows, the controller just get stuck. But if this is too much of a hassle to implement, just ignore this response. Thanks for the support!
