### ISSUE TITLE
How to uninstall latest version?

### ISSUE THREAD

**Issue by harddk** [Ryochan7/DS4Windows#736]
Tried this project, but while it works, it also overwrites my other games which recognize PS4 natively.

How do I stop that from happening?

Even after deleting the project folder and %appdata%/roaming/ds4windows -folder, every game thinks my ps4 controller is an xbox one :-/

**Comment by harddk** [comment]
Tried using:
https://github.com/Ryochan7/DS4Windows/issues/390
for inspiration, but that's not up-to-date. I at least didn't find any **Scp Virtual Bus Driver**.

**Comment by mika-n** [comment]
If you are using this Ryochan7 fork of DS4Windows (ver 1.7.10) and not the old (obsolete) Jay2Kings version then you can forget ScpVirtualBusDriver links and docs. ScpVBus haven't been used for a while at all because the current version of DS4Win uses ViGemBus virtual gamepad driver.

Anyway. Games should see your DS4 gamepad as a native ds4 pad if DS4Windows application is not running. There won't be any DS4->xbox360 remaps if DS4Win app is not running.

But if you really want to uninstall everything then you can use the DS4Win TestInstaller tool to uninstall ViGemBus driver and HidGuardian (if you use HidGuardian).
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer

After uninstalling ViGem (and optional HidGuardian driver) then you can remove the DS4Win app folder, BUT that shouldn't be necessary because it really doesn't do anything if it is not running.

**Comment by Ryochan7** [comment]
I am inclined to believe that the Steam mapper is being used unintentionally so that will emulate an Xbox 360 controller.

**Comment by harddk** [comment]
Thanks for the fast and detailed replies.
Did some testing, and while not solved this issue, I've gotten a clearer picture of what's happening.

**What happend:**  Played some Dead Cells on Steam with my ps4 controller and had ps4 button promts. Got a reply from support on gog, to use this software to solve a controller problem for Bloodstained - Ritual of the Night, as that only supports xinput. Downloaded it, opened it, looked through the menu and thought I'll look at it later. Closed the app, and booted up Dead Cells again, but this time had Xbox button-promts. Tried removing the software and all data I could find, but the buttons always showed as X,Y,A,B from now on in my games. Even did a system restore to try and solve this.

A really good tip was the comment on the Steam mapper being unintentionally used, and I then started testing on DRM-free games vs steam, and that is very much the case. I got no idea why it's happening, but will try and reach out to steam support about this. Attached a picture that shows it loads up a profile now when starting Dead Cells. All I can say is, this started exactly when I started using this software. The software works, yes, booting it up confused steam on my end.

![Dead Cells Screenshot 2019 06 24 - 15 59 16 36](https://user-images.githubusercontent.com/22270175/60026671-48165b00-969c-11e9-9d5a-2ccb8703754b.png)
