### ISSUE TITLE
Z rotation not working

### ISSUE THREAD

**Issue by nicsman** [Ryochan7/DS4Windows#739]
My Z rotation (vertical right stick) is not working but Z axis (horizontal right stick)is working as usual. It does not have this problem with steam controller support but it have this problem while playing other games that is out of steam

**Comment by mika-n** [comment]
Have re-mapped right stick axies? Or accidentally unmapped the axis?
If you are unsure then try creating a new default "empty" profile without any re-map rules. If it works then check your real profile file and re-mapping rules.

Also, what do you see in "Controller Readings" tab page of DS4Windows settings screen?

And please go through the following Troubleshooting wikipage to see how to send logfiles and DS4Win app version as part of the issue post. And how to reset all DS4Windows settings in case some old or wrong config file or profile file causes weird side effects.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

**Comment by Ryochan7** [comment]
Without seeing the profile being used, there is pretty much nothing to help diagnose the issue. The most likely reasons would be that either RY is not mapped or there is a mapping conflict in the profile.

**Comment by nicsman** [comment]
My controller readings tab work. It can sense it. The last image is my joy.cpl which I am not sure why got 3 when I plug in one. 1 work normally, 1 is not connected at all and wireless one is the one with the vertical right stick not working
![image](https://user-images.githubusercontent.com/49552972/60171650-9adb4880-983d-11e9-9ba7-05a5d3e4ba56.png)
![image](https://user-images.githubusercontent.com/49552972/60171697-acbceb80-983d-11e9-867a-ee608b7734f7.png)
![image](https://user-images.githubusercontent.com/49552972/60171718-b9414400-983d-11e9-8fcb-4e5101c02941.png)

**Comment by nicsman** [comment]
> Have re-mapped right stick axies? Or accidentally unmapped the axis?
> If you are unsure then try creating a new default "empty" profile without any re-map rules. If it works then check your real profile file and re-mapping rules.
> 
> Also, what do you see in "Controller Readings" tab page of DS4Windows settings screen?
> 
> And please go through the following Troubleshooting wikipage to see how to send logfiles and DS4Win app version as part of the issue post. And how to reset all DS4Windows settings in case some old or wrong config file or profile file causes weird side effects.
> https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

Deleting the profile work. Thanks

**Comment by mika-n** [comment]
In your screenshot you have mapped "gyro steering wheel emulation axis" to Right X-Axis option. This means that the rightstick x-axis is controlled by gyro angle of your controller (motion sensitive) and not the stick X axis itself. 

Also, you had gyro tilting options set to up/down/right/left options. Usually if steering wheel emulation is used then those other gyro tilting options should be set as "unassigned" because I don't see much point of using both features at the same time. 
https://github.com/Ryochan7/DS4Windows/wiki/Settings#steering-wheel

And having three gamepads in Joy.Cpl screen is normal if you don't use "Hide DS4 Controller" (exclusive mode) option of DS4Win app or additional HidGuardian tool to hide the original physical controller.  Please read through the following help/wiki page for more info about hiding the original controller and why it is sometimes needed and how to hide the controller (if a game requires it).
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Now in Joy.cpl list you are seeing the original physical controller and a virtual gamepad controller created by DS4Windows app (and this virtual controller has all custom re-map rules applied to buttons and axies). 

Additional "PS4 Fun Controller" is probably just some PS4Fun specific driver thing. I guess you see those two PS4Fun controllers even when you are not running DS4Windows application? DS4Win app has nothing to do with those original device drivers.

**Comment by Ryochan7** [comment]
So the gyro mapping is what caused the conflict. I don't know what is happening with the PS4 Fun Controller issue but that is not due to DS4Windows. If the controller is disconnected then it would not show up in the Game Controllers settings window. It would still appear in the Devices and Printers section of the Control Panel but it would be greyed out.
