### ISSUE TITLE
When I plug in my controller it says the last device malfunctioned 

### ISSUE THREAD

**Issue by TMGSupreme** [Ryochan7/DS4Windows#746]
The controller used to work fine but now everytime i plug it in it says that ''the last device you plugged in malfunctioned''. It used to turn blue but now it doesnt. The controller still works as i can hold down the ps4 button and it will flash the leds. I've tried reenabling the devices from device manager, reinstalling the programme, unplugging the controller and plugging it back in all the usb ports, replugging the power supply, checking the drivers for updates. None of which have worked

**Comment by Ryusennin** [comment]
Seems unrelated to DS4Windows.

Try to reset your controller:
https://support.playstation.com/s/article/DualShock-4-Troubleshooting?language=en_US

**Comment by Ryochan7** [comment]
This problem is very likely not due to anything with DS4Windows. It could have been due to a faulty USB cord or a USB port. In my case, I have to avoid using one USB port on my case or this type of problem would be guaranteed to come up no matter what device I plug in. You might want to uninstall the appropriate controller device listed in the Device Manager and attempt to have Windows detect the controller again. Make sure to NOT run DS4Windows while testing this. The device needs to be working in Windows first before adding DS4Windows back to the mix.
