### ISSUE TITLE
A few questions regarding DS4windows

### ISSUE THREAD

**Issue by Bluesurfer6** [Ryochan7/DS4Windows#759]
Hello I'm interested in using DS4Windows to control 2 characters simultaneously using a PS4 controller. I've done this before by using inputs via blue tooth and wired conection and wish to reproduce the same effect on Wild Guns Reloaded on steam but it doesn't accept inputs from triggers or right analog sticks. I'm on the fence about using this software and have a few concerns.

1. Does this version have an uninstaller to remove the program and any drivers it may install completely?

2. Can I shut the program off to use a PS4 controller normally without having to uninstall it or any drivers it may install?

3. Can this remap inputs for both wired and blue tooth conections separetely while using inputs from both conections simutaneously?

**Comment by mika-n** [comment]
> 1. Does this version have an uninstaller to remove the program and any drivers it may install completely?

This app requires minimum of two components. The DS4Windows application itself which does the magic of re-mapping buttons or turning DS4 gamepad as x360 gamepad for those games which don't natively support DS4 gamepad. The DS4Windows application itself is easy to uninstall because you can simply remove the folder where you installed it. And if you don't run this app then it doesn't do anything in the background (it just wastes few megabytes of disk space).

However, the DS4Windows app alone doesn't do much because it needs a device driver to expose a physical gamepad controllers as a new virtual gamepad controller which outputs your custom re-map keys and axis and buttons. DS4Windows application can install this required driver when you first launch DS4Windows app. 

Uninstallation of this driver needs to be done via DeviceManager or using a badly named "Test Installer" installer app (why "Test Installer" when it actually does this install/uninstall as one click process? don't know.).
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer

The TestInstaller talks about HidGuardian driver also, but you don't have to worry about that unless a game really requires it. Take a look at this help page (all this is not required unless a game require it so you can try your game without these exclusive mode or hidguardian device tools at first):
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues


> 2. Can I shut the program off to use a PS4 controller normally without having to uninstall it or any drivers it may install?

Yes. When DS4Windows is not running then it does nothing in the background (actually, it is not even running in background because it does't have any background services) and DS4 gamepad works business as usual.

However, please note that if you use an optional HidGuardian device driver (it is not DS4Windows tool, but part of other projects. However, it may be useful to those people who run into badly programmed games which are confused when they see more than one gamepad controllers).


> 3. Can this remap inputs for both wired and blue tooth conections separetely while using inputs from both conections simutaneously?

Yes. DS4Windows supports up to 4 controllers at the same time and each controller can share the same re-map profile or each controller can have a different active re-map profile.

**Comment by Ryusennin** [comment]
"Test Intaller" because it used to be a beta test installer ;)

**Comment by Bluesurfer6** [comment]
> > 3. Can this remap inputs for both wired and blue tooth conections separetely while using inputs from both conections simutaneously?
> 
> Yes. DS4Windows supports up to 4 controllers at the same time and each controller can share the same re-map profile or each controller can have a different active re-map profile.

Thank you, to go further: My playstation 4 controller is connected to the PC 2 ways simutaneously via wired and bluetooth, can I use DS4 Windows to use 2 different profiles simutaneously from a single controller?

**Comment by Ryochan7** [comment]
No. DS4Windows can check for duplicate controllers via the hardware serial number. DS4Windows checks the controller's serial number before attempting to create the background controller threads used for the mapping process. It will detect if the serial number is already registered and keep a reference to the newer HID device if exclusive mode is used.

DS4Windows will make sure that only one controller is used in the program.

**Comment by Bluesurfer6** [comment]
> No. DS4Windows can check for duplicate controllers via the hardware serial number. DS4Windows checks the controller's serial number before attempting to create the background controller threads used for the mapping process. It will detect if the serial number is already registered and keep a reference to the newer HID device if exclusive mode is used.
> 
> DS4Windows will make sure that only one controller is used in the program.

Then I don't even need to check hide DS4 box in the menu?

**Comment by Ryochan7** [comment]
If you want to hide that controller from the system then you want to have it checked. Leaving that option unchecked will still present an issue with games that have some form of DirectInput controller support.
