### ISSUE TITLE
USB Adapter disables keyboard when turning controller off

### ISSUE THREAD

**Issue by pedrovay2003** [Ryochan7/DS4Windows#76]
Since you can't use the PS+Options combo to turn the DualShock 4 off when using the official USB adapter, you have to hold the PS button for 10 seconds to turn the controller off. When doing this, and the controller turns off, my Windows and ALT keys stop working until I either a) connect my controller again, or b) stop and restart DS4Windows.

This only happens if I hold the PS button to turn the controller off, and not if I set the profile to turn the controller of automatically after a certain amount of time. It has something to do with a button being held when the controller turns off that makes the system thing that the button is ALWAYS being held; this doesn't happen when the controller is completely disconnected from standard Bluetooth, but only when the official Sony USB adapter is used.

**Comment by Ryochan7** [comment]
The problem is the adapter continues to output the last controller state since the adapter is the device seen by Windows and the associated HID device is still present. There isn't much that can be done in DS4Windows to work around that issue since that is the way the hardware behaves. The input report from the adapter does change to show that the controller is disconnected so I do not know why the adapter doesn't just revert the virtual DirectInput controller to a default state when no controller is connected. When a DS4 connected via Bluetooth is disconnected, the associated HID device is removed from the system when the controller is disconnected.

In theory, the problem can be dealt with as long as Exclusive Mode is enabled and DS4Windows has grabbed exclusive access to the adapter device. DS4Windows can detect when a DS4 disconnects from the adapter so the controller state for the emulated XInput controller could be set to a default state; currently, DS4Windows only updates the associated serial number for the adapter device when a DS4 disconnects. If exclusive access could not be obtained then problems will still exist.

**Comment by pedrovay2003** [comment]
Yeah, as much as I like the official adapter, it definitely doesn't play nicely with custom software. Is there a way to make absolutely sure that DS4Windows is exclusively grabbing and keeping the DS4, or is the adapter just too finicky of a thing to allow that to happen?

**Comment by Ryochan7** [comment]
The issues with Exclusive Mode are mainly Windows related problems; to a lesser extent, other software running at the time contribute to making the process more difficult. The hardware devices don't really factor into whether exclusive mode is obtained or not. The only possible workaround that I have heard about is through the use of HidGuardian. The software needs some work and it didn't work on my machine when I tried it.

**Comment by Ryochan7** [comment]
A change has been made that would work around this problem when Exclusive Mode is active. The virtual XInput controller will only be connected when a controller is currently connected to the Sony dongle.

**Comment by pedrovay2003** [comment]
Oh, that sounds fantastic! It's version 1.4.82 that has that fix? I'll download it when I get home from work and report back.

Thanks for all of your hard work on this, by the way.

**Comment by Ryochan7** [comment]
The change is currently only in the source code.

**Comment by pedrovay2003** [comment]
Okay, I see. Still, that's exciting. Thanks for looking into this!

**Comment by Ryochan7** [comment]
A new release is out that incorporates this change.

https://github.com/Ryochan7/DS4Windows/releases/download/v1.4.83/DS4Windows_1.4.83_x64.zip

**Comment by pedrovay2003** [comment]
This is really fantastic. Thanks for looking into that issue. I'm definitely donating when I get home from work.
