### ISSUE TITLE
Default Auto-Profile for all applications

### ISSUE THREAD

**Issue by Nerdy314159265** [Ryochan7/DS4Windows#760]
I think there should be a way to explicitly select an Auto-Profile to use when in any application that doesn't have a specific profile set.

I sometimes have to have to use a profile that switches my controller to appear as an Xbox 360 controller because a game may not support DS4 controllers. However, this has caused a minor issue in that the which profile the program will switch to when out of that program or opening another is vague/undefined for the end user.

To try and remedy this, I thought to add a specific Auto-Profile for some apps that use DS4 to use the DS4 profile but this has caused there to be occasional unnecessary profile switching when alt-tabbing to fiddle with Explorer or Chrome.

If it was possible to specify a default profile to use for all applications not specifically set, then the functionality becomes clearly defined and switching profiles unnecessarily can be eliminated or at least reduced.

**Comment by Ryochan7** [comment]
When an auto-profile entry cannot be found, DS4Windows will revert back to whatever profile is selected in the Controllers tab for that controller slot. That is basically what would be considered the "Desktop" profile with the current behavior. The auto-profile system is not that great and it has only been tweaked to maintain compatibility with other program changes. I consider it a deprecated portion of the program.

**Comment by mika-n** [comment]
Few days ago I made a major re-implementation to AutoProfile logic. The original AutoProfile monitoring and switching logic used in the current version probably dates back to years and years. Anyway, there were couple missing features and it had nasty "features". For example, if you are at the moment in AppProfile1 and you alttab to an another application which should use AppProfile2 then instead of going from directly from AppProfile1 to AppProfile2 the current version at first reverts back to a default profile (can be see in DS4Win Controllers tab page) and then after few secs switches to AppProfile2. So, it goes like AppProfile1->defaultProfile->AppProfile2.

The new version shown in the following pull requests re-designed this autoprofile thing to support new features (wildchar support to match an app and profile, match with both application path and window title, much better performance and less RAM usage) and fixes the nasty profile1->revert back to default->profile2 sequence. The new version makes a direct profile switch instead of always going through default profile before choosing the new app specific profile.

Also, the new autoprofile logic allows to set certain application with "no profile change" status in order to avoid the switching to default profile and leaving the current profile active. For example in the new version one could define "appPath=c:\windows\explore  windowTitle=task switching" with "(none)" profile option and this way DS4Win autoprofile system would not force switch back to default profile while alttabbing between processes (unless you really want it to force switch back to default while alttabbing). 

The pull request: https://github.com/Ryochan7/DS4Windows/pull/745#issuecomment-510665102
