### ISSUE TITLE
[Feature Request] Unity Support

### ISSUE THREAD

**Issue by aleffeh** [Ryochan7/DS4Windows#761]
Hi, Unity 2019 has a very good support for HID devices, such as ds4, and recognizes pretty well. But, has no lightbar support, as a developer it would be very nice to have this feature on windows, and because you are manteining and updating the ds4 windows code, could you expose a dll with only the essential for control lightbar ? I can create all the Unity part, making the asset and publishing for free on unity asset store for everyone which want to implements this feature.
I could do this for myself, but I would need to read all ds4Windows code and it would take a long time.
Hoping you understand, thank you.

**Comment by Ryochan7** [comment]
The only resource for that would be the DS4WindowsAPI assembly. An older version was made to work with UCR but I ended up using the same technique to make a more up-to-date version. I have had no reason to update it with the latest code because I have not used it since reinstalling Windows. I don't think I have a copy of the old test projects that used the assembly.

https://github.com/Ryochan7/DS4WindowsAPI
