### ISSUE TITLE
changing the controller from xbox to dualshock4 causes crashes

### ISSUE THREAD

**Issue by SandrosMaximus** [Ryochan7/DS4Windows#764]
if I change the controller in a profile from xbox to ds4 it causes crashes every time i try to start it and a controller starts with this profile. the only way to run it again is to turn off bluetooth, change the profil again and then turn on bluetooth again. is there any way that I can use this feature?

![Unbenannt](https://user-images.githubusercontent.com/47694565/61255413-c1b7db00-a768-11e9-9a4a-734fe722551e.PNG)

**Comment by Ryochan7** [comment]
I'm not sure what would be causing an issue. I have profiles that use either setting so switching controller types works on my end. I have just tested it again and changing output controller types works for me. Which version of DS4Windows are you using? Maybe posting the profile(s) being used would help narrow down the problem as well.

**Comment by SandrosMaximus** [comment]
Thanks for the response. I tried multiple profiles and even used the standard settings of the program and the default profile and it still happens. I'm using the latest version of ds4windows(at least that's what's the updater says).

**Comment by mika-n** [comment]
There has been cases in the past when Updater has failed to report that an updated version is available or failed to install the new version automatically. See this page if you really have the latest version
https://github.com/Ryochan7/DS4Windows/releases

Try to clear all existing config and profile files and start from scratch because sometimes some weird config/profile setting combinations have caused difficult to trace problems. You can navigate to the current config by clicking the "Profile Folder" link in DS4Windows settings screen. Or navigating to "%APPDATA%\DS4Windows" folder using FileExplorer. Backup everything everything in this DS4Windows folder and in Profiles subfolder and then delete all files (just leave the empty profile subfolder). Then launch DS4Windows and it will re-create these files with default values.

**Comment by SandrosMaximus** [comment]
I looked it up and i have the newest version of the program.

what I ment by "using the standard settings of the program and the default profile" is exactly that. I deleted all the settings and profiles and let the program create new ones.

> There has been cases in the past when Updater has failed to report that an updated version is available or failed to install the new version automatically. See this page if you really have the latest version
> https://github.com/Ryochan7/DS4Windows/releases
> 
> Try to clear all existing config and profile files and start from scratch because sometimes some weird config/profile setting combinations have caused difficult to trace problems. You can navigate to the current config by clicking the "Profile Folder" link in DS4Windows settings screen. Or navigating to "%APPDATA%\DS4Windows" folder using FileExplorer. Backup everything in this DS4Windows folder and in Profiles subfolder and then delete all files (just leave the empty profile subfolder). Then launch DS4Windows and it will re-create these files with default values.

**Comment by Ryochan7** [comment]
Can you find a crash log in the Event Viewer? Control Panel > System and Security > Administrative Tools > Event Viewer. I believe it should show up with the level Error and the source should be something like .NET Runtime; I cannot remember off hand how it shows up in the log.

**Comment by SandrosMaximus** [comment]
> 

> Can you find a crash log in the Event Viewer? Control Panel > System and Security > Administrative Tools > Event Viewer. I believe it should show up with the level Error and the source should be something like .NET Runtime; I cannot remember off hand how it shows up in the log.

This is what it says 

svchost (5396,R,98) TILEREPOSITORYS-1-5-18: Fehler -1023 (0xfffffc01) beim Öffnen von Protokolldatei C:\WINDOWS\system32\config\systemprofile\AppData\Local\TileDataLayer\Database\EDB.log.

which means in english:

svchost (5396,R,98) TILEREPOSITORYS-1-5-18: Error-1023 (0xfffffc01) opening logfile C:\WINDOWS\system32\config\systemprofile\AppData\Local\TileDataLayer\Database\EDB.log.

**Comment by SandrosMaximus** [comment]
and I overlooked this:

Anwendung: DS4Windows.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: Ausnahmecode c0000005, Ausnahmeadresse 6B8E220C
Stapel:

----

Name der fehlerhaften Anwendung: DS4Windows.exe, Version: 1.7.12.0, Zeitstempel: 0x5d205713
Name des fehlerhaften Moduls: vigemclient.dll, Version: 0.0.0.0, Zeitstempel: 0x5cc0d096
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0000220c
ID des fehlerhaften Prozesses: 0x1c48
Startzeit der fehlerhaften Anwendung: 0x01d53c10fd97cb04
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\DS4Windows\DS4Windows.exe
Pfad des fehlerhaften Moduls: C:\Users\Megaport\AppData\Local\Temp\Costura\A464B6D26598CA43553BC1F80778A238\32\vigemclient.dll
Berichtskennung: a7caec38-e4c7-4d07-9825-a108ed400937
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by Ryochan7** [comment]
The error looks like it is directly due to the C++ ViGEmClient library. It also looks like this is something specific with the x86 version based on the temp file path. It is too bad that there is no version number available since it is hard to tell if the latest library is being used. There have been a few x86 specific bugs that have been fixed with the ViGEm libraries. The more prominent ones have been due to force feedback routines. I am wondering if an old bug is making an appearance or if this is something new. It would probably be impossible to tell without running the code through a debugger.

Also, is there a reason that the x86 build of DS4Windows is being used at all? That version only had one real use and that was for a user with a Windows tablet that had a 32 bit processor installed. Almost anyone else should be using the x64 version.

**Comment by SandrosMaximus** [comment]
so what do I do to fix it then?

**Comment by Ryusennin** [comment]
First uninstall your x86 version of DS4Windows and try the x64 version.

https://github.com/Ryochan7/DS4Windows/releases

**Comment by SandrosMaximus** [comment]
okay thanks alot for the help!

**Comment by SandrosMaximus** [comment]
So... i tried it and it didnt work. But i managed to fix it deleting the files and creating new ones in "Programms" instead of "Programm(86)"

**Comment by SandrosMaximus** [comment]
well... now i can select it but it doesnt work. steam for example recognises it when I select the Xbox Controller but not the DS4 Controller

**Comment by mika-n** [comment]
See this post about Steam and how it actively tries to hide controllers if DS4Windows.exe or InputMapper.exe processes are running.
https://github.com/Ryochan7/DS4Windows/issues/750#issuecomment-512657735

Maybe the issue you have is the same? Try renamning DS4Windows.exe to, for example, DS4WinApp.exe to fool Steam to think that DS4Windows is not running.

**Comment by SandrosMaximus** [comment]
wow thats so strange... why does it block the ds4 but not the xbox emulation?! 

also... it works but it recognises two ds4 controllers.

**Comment by SandrosMaximus** [comment]
ah ok but only one works so it doesnt matter

Well thanks for everything guys!
