### ISSUE TITLE
[Suggestion] Separate action for triggers when pressed all the way down

### ISSUE THREAD

**Issue by 64px** [Ryochan7/DS4Windows#77]
The program recognizes when the triggers are pressed all the way down, so can we bind a special action to that? 
For example: Halfway = charge gun | All the way = fire gun

**Comment by Ryochan7** [comment]
Making the new controls would probably not be that much of a problem. One big issue is that the assignments would likely only be done using a simple threshold as opposed to having a hip fire mode active.

**Comment by AKA-Syenite** [comment]
Seconding the utility of a change like this. There are a variety of situations where it would be helpful to have two separate actions on partial/full presses.

**Comment by Serfrost** [comment]
Just want to say this would be really helpful for Gamecube emulation, etc.  Secondly, it's also viable as an option for DualSense given the extra trigger room.

**Comment by Ryochan7** [comment]
I have thought of a way that this might be doable with recent mapping changes. One big problem would also affect a new Gyro Directional Swipe action idea that I want. As it is, I still have not had a use for a Two Stage Trigger action in a profile so it keeps getting ignored. Over 3 years

**Comment by Serfrost** [comment]
@Ryochan7 I can see it's been on the backburner. lol  I think the main benefit to having this is additional buttons where controllers otherwise wouldn't have them.  As mentioned, this would primarily help for Gamecube due to how its triggers work, but the other things that come to mind are macros that rebind actions and in general how you could actually use the function to your benefit; albeit likely in unintended ways from what was first thought.

The first games of relevance would really be any First Person Shooter or those that make use of archery (i.e. Horizon Zero Dawn, Breath of the Wild) - being able to aim and shoot with a single trigger would free up the other trigger for alternative tasks or macros.  Currently, most titles have you aim with the left, fire with the right.  Let's not forget most games make use of all buttons, and not having extras leads having your hands tied when trying to create useful macros.

With DualSense and possible Haptic Feedback support, this would be even more beneficial when used together with it.  There are already quite a few racing games out there that make use of analogue triggers with an additional action at peak of the trigger usage.  Haptic Feedback via controller profile for a given game would give these games some next-level immersion, even if artificial.  If a game doesn't support an action at the peak of the analogue press, this is where being able to bind a task to it yourself would come in handy.

Failing to come up with any additional ideas on the spot however; I blame my lack of playing anything recently.

--

As far as Gyro Directional Swipe, what would this entail; how would it be affected by further analogue trigger options?  With only the name itself I can't really picture what this is. lol

In either case, I hope you consider both options and perhaps find a way to work it in with the Directional Swipe you wish to implement.

**Comment by Ryochan7** [comment]
Seems to work. Instead of making a new Output mode, it just takes advantage of most of the settings already available. One additional feature that would be nice for DualSense users would be a way to add extra tension towards the end of the trigger pull.

![twostagetrigger_draft](https://user-images.githubusercontent.com/581968/106054926-4b609c80-60b2-11eb-9d83-22875e9a5b27.png)

**Comment by Ryochan7** [comment]
> As far as Gyro Directional Swipe, what would this entail?; how would it be affected by further analogue trigger options? With only the name itself I can't really picture what this is. lol

Tbh, I have not messed around with the feature myself yet. That output mode was a recent addition to Steam Input for Gyro and Touchpad input. RambleTan has made some videos showing the new feature and some Steam Input profiles that take advantage of it.

Directional Gesture Swipes for Increased Immersion - Steam Controller Input Tutorial:
https://www.youtube.com/watch?v=OeBmQodx64s

Swipe controls pretty much handle that mode for the Touchpad. The Gyro mode looks like it would be a more subtle version of shake controls for mapping actions to Gyro motion. It might be more subtle than the current Tilt controls that are available. I can see myself using it for JoyCon profiles for mapping some extra actions on the Left JoyCon.

**Comment by Serfrost** [comment]
Awesome. When it comes to tension, there is that project mentioned in one of these other issues that has this type of functionality already. (https://github.com/Mxater/DualSenseSupport)

Pairing it with DS4Windows does work, so perhaps you could implement it in your own way.

Glad to see you taking interest. :)

**Comment by Ryochan7** [comment]
Progress. Got some preset effects going. Full Click would probably be the one people would use for a Two Stage trigger setup. Might add a tiny amount of extra resistance to the click action than what is configured currently; one big consideration was to make sure the Soft Pull action allowed for the largest possible range before encountering resistance.. Rigid and Pulse are available as well. There is no sort of custom option and I am not sure it is necessary. The option is meant to be more device agnostic so I wouldn't want something that defines a specific data structure; the backend device classes will handle setting the data structure from an assigned preset.

Regular Hip Fire behavior has been fixed. As it is now, Hair Trigger and Hip Fire modes should work like they do in Steam Input. Been testing the behavior in Half-Life 2.

![twostagetrigger_draft3](https://user-images.githubusercontent.com/581968/106178446-663d1a80-615f-11eb-934b-a9f9c8224e68.png)

**Comment by Ryochan7** [comment]
These changes have now been merged into the main jay branch.

**Comment by Serfrost** [comment]
Fantastic.  Looking forward to the next release.

**Comment by Ryochan7** [comment]
Version 2.2.3 is now out.

**Comment by Serfrost** [comment]
'berry noice.  Feels good.  I haven't played anything that needs it recently, but I think I'm going to keep the Full Click option enabled.  Also, I would recommend adding an explanation/pop-up-on-hover to the Two Stage Mode features as many people might pass them up not knowing what they do.

In either case, great work. :)

**Comment by Serfrost** [comment]
@Ryochan7 The only issue I've encountered so far is that the Full Press Btn action will activate before the actual Full Click option happens.  Is there any way to have the Full Press Btn's action occur at the true Full Press position?

I believe this is due to the Analogue reading 255 (max) before it's fully pressed, but from what I recall this is standard behavior.  Is there no way to reach the Analogue value beyond 255; or perhaps artificially extend it to its full capacity?

**Comment by Ryochan7** [comment]
Gyro Swipe mode has now been added in version 2.2.4. That was a feature that I would have liked in version 2.2.3 but I figured it was best to get that release out. Figuring out the Two Stage trigger feature helped a lot with figuring out the process of adding more virtual binding buttons.

There are probably some other options that could be added to that Gyro mode but the essentials are there. It mostly duplicates Gyro Directional Swipe from Steam Input with a different default sensitivity. I have not used the feature outside of testing yet.
