### ISSUE TITLE
Increasing memory usage by DS4Windows

### ISSUE THREAD

**Issue by alexeynikitin** [Ryochan7/DS4Windows#774]
I noticed that once you got your controller connected, DS4Windows memory usage is gradually growing up.
I got Windows 10 Pro 1809 build 17763.292, 
DS4Windows 1.7.12

What could be the reason?

**Comment by mika-n** [comment]
The RAM consumption increases for a while, but eventually it will level out once .NET garbage collector kicks in.
https://github.com/Ryochan7/DS4Windows/issues/730#issuecomment-507787762

**Comment by Yohoki** [comment]
Shoot... I should have come here BEFORE restarting DS4Windows, because my fan has been at 100% for over 24 hours and Task Manager showed it at +30% CPU. If windows doesn't decide to update my computer for no reason (...I hate windows 10...) I'll continue leaving my computer on to see if it keeps happening and take a look at Performance Monitor.

I find it hard to believe that normal garbage collection is using more CPU and RAM than firefox is with 15 tabs open. Oo

I wasn't aware there were better tools to see how specific things are impacting those numbers. Would there be any other things that would be helpful to look at if this starts using way to much CPU again? I have Gen 0-2 Collections and % Time in Collections monitoring right now. I'll look at Performance Monitor next time to hopefully get some more valuable info for you. :D

**Comment by mika-n** [comment]
+30% cpu consumption is not normal for ds4win. Some reports have indicated that sleep-wakeup cycle may cause something weird. Restart helps with that issue or doing automatic ds4win start-stop scripts in sleep and wakeup system events. RAM consumption is normal because by default ds4win usea server gc mode and not workstation gc mode. But still it should not cause 30 plus cpu load.

**Comment by Yohoki** [comment]
Mine may be a weird case, because my computer is kind of a media server setup in the living room. It doesn't go to sleep, only uses screensaver when idle. It also doesn't get turned off (or at least shouldn't) so it could be a very slow buildup that I've never noticed. I'll just keep monitoring it again over several days and see if it keeps doing it. I hadn't noticed ds4win doing that before, but if it takes several days to get into that state, I can't say that someone hasn't restarted the computer at some point or another.

Like I said, I wish I had come here before restarting ds4win, because that instantly fixed the issue, but I didn't get any info about why it was doing it. So, sorry I don't have anything better than "Hey, this is broken! I want money back!" I'll try to bring more info next time. XD

**Comment by Ryochan7** [comment]
Normal garbage collection is not being used in the standard configuration. Server mode garbage collection is being used in DS4Windows by default. That mode makes the .NET Runtime much less aggressive when it comes to running the garbage collector. It really helps improve input latency and overall application performance. CPU usage should not be impacted much by using server mode.

Portions of DS4Windows have been changed to better manage memory but there is only so much that can be done without completely depending on the garbage collector. The UDP server is especially memory consuming with its constant byte array allocations. Some of those allocations have been changed to use a pre-defined buffer but some portions cannot reasonably be changed. The use of stackalloc and Span would actually be very useful to work around the problem but that technique is not usable in the normal .NET Framework as of yet; it can be used in the latest .NET Core.

If you want to test using normal workstation mode, you can edit the DS4Windows.exe.config file and modify the **gcServer** tag and set enabled to **false**. On my system, DS4Windows makes out at around 70-80 MB of memory before the garbage collector is invoked.

```
<gcServer enabled="false"/>
```

**Comment by Yohoki** [comment]
Sorry, it's been a while to get it to act up again. I've had to restart the computer a few times lately for other reasons. But it IS starting to kick back up on the CPU again. It's not a BIG issue for me, because it's fixed simply by restarting the program. But, if you'd like to take a look at it, I can run anything you need to get info from it while it's acting up. Here's a quick screenie with Taskman and Performance Monitor up.
![image](https://user-images.githubusercontent.com/44595371/62644420-aaa37d80-b90f-11e9-9ca1-eae569c5010d.png)

**Comment by mika-n** [comment]
@Yohoki  Have you updated the DS4Windows to V1.7.14 because there are some tweaks relating this sleep-wakeup cycle. 
Do you still get the same "excessive use of CPU" problem after the controller and/or PC wakes up from a sleep even in V1.7.14 version?
https://github.com/Ryochan7/DS4Windows/releases

**Comment by Yohoki** [comment]
Yes. This is 1.7.14 .

It is probably not related to sleep/wake cycling, as this PC is active 24/7. I have sleep/hibernate disabled on it. It uses a screensaver that turns on after 10 minutes, but I don't believe that works the same way.

The think controller is also never asleep because it's USB not bluetooth. I might be wrong about that, because I cannot exit the screensaver with the controller, but the light is still lit.
![image](https://user-images.githubusercontent.com/44595371/62807711-addb6c80-babb-11e9-8b01-a0be01af7c61.png)

**Comment by mika-n** [comment]
This is still a mystery.

The latest version of DS4Windows supports couple new command line commands which may be handy if you want to restart the DS4Windows process using just "one click". You can create a following kind of BAT/CMD file and then double click it to shutdown existing DS4Windows process and to launch a new fresh process.
https://github.com/Ryochan7/DS4Windows/wiki/Command-line-options

Create a "RESTART_DS4WINDOWS.CMD" file in the same folder where you have DS4Windows.exe executable (or add a path reference to DS4Windows.exe executable lines in the BAT/CMD file) and then place a shortcut to this batch file in a desktop. Then it will be "one click" trick to restart DS4Windows.exe application.

```
@echo off
echo [%DATE% %TIME%] Shutting down existing DS4Windows background process. Please wait...
DS4Windows.exe -command Shutdown
TIMEOUT /NOBREAK /T 3

echo [%DATE% %TIME%] Starting DS4Windows process
start /B "" DS4Windows.exe

echo [%DATE% %TIME%] Completed DS4Windows restart
```

**Comment by Yohoki** [comment]
Caught it kicking up EXTREMELY badly while playing Hitman2. It does not normally lag on my PC, especially with the res only at 720p and most graphics turned to med-low. But the game is unplayable. Looking at TaskMan, D4W is at +40%. So, here's another screenie of performance mon and taskman.
![image](https://user-images.githubusercontent.com/44595371/62828299-346d7800-bba8-11e9-8b1a-47874b9a220d.png)
I thought MAYBE it's actually hitman acting up, and making D4W show high numbers. But, closing hitman, firefox and bigbox (the 3 main memory hogs open) doesn't affect the CPU% at all. I'm afraid I can't leave my computer like this much longer, as the fan is getting very loud now, so I added everything from .NET CLR Memory in case it shows anything weird.

**Comment by Yohoki** [comment]
Here's also everything from the .NET categories of Performance Monitor And also from Process category:
![image](https://user-images.githubusercontent.com/44595371/62828353-ea859180-bba9-11e9-8b0f-a708375e344d.png)
![image](https://user-images.githubusercontent.com/44595371/62828354-f1140900-bba9-11e9-9510-e510f1b6d035.png)
![image](https://user-images.githubusercontent.com/44595371/62828360-fbce9e00-bba9-11e9-9463-bb41eda03612.png)
![image](https://user-images.githubusercontent.com/44595371/62828385-b494dd00-bbaa-11e9-9060-4fb4875e2a13.png)

**Comment by Yohoki** [comment]
Update:
I did a quick google search for "# of current logical cores" and was immediately taken to this page: https://stackoverflow.com/questions/9377558/current-logical-threads-increasing-thread-stack-is-leaking

It seems in his case, the culprit was a "System.Timers.Timer". I did a quick and dirty Alt+F through a lot of files on this and found it being used in DS4Form.cs, RecordBox.cs and WelcomeDialog.cs . I think only RecordBox.cs actually is using it though, on line 129 for the Ds4_Tick.

The SuperUser OP said that his solution was to use a DispatcherTimer instead of System.Timers.Timer . I dunno how easy it is to change or test out or if I'm even REMOTELY in the right area. Hopefully it helps?

**Comment by mika-n** [comment]
@Yohoki  Good catch. You could be on something interesting about how threads behave or are cleaned up when a profile switches between x360-vs-dualshock4 modes.  

I just tested this and while manually switching between two profiles with the same output controller type then thread count didn't keep on rising. But if those two profiles had a different controller type then I could clearly see how the thread count on perfMonitor kept on increasing for DS4Windows process.

This is clearly a problem in scenarios where profiles use different virtual output controller type. Thanks for tracking down this problem... Now the next step is to find out why this happens and is it a problem in DS4Windows app or in ViGem driver level. @Ryochan7  Any good ideas?

**Comment by Yohoki** [comment]
It's so small, it probably isn't an issue for most people. But I use both controller types often and hardly ever shut down the computer, so these little things would eventually (and do) become huge cpu hogs. I'm glad I could help at all. It's such an awesome program and I use it for every program I have. :D

**Comment by alexeynikitin** [comment]
Solution with
`<gcServer enabled="false"/>`
worked for me.
