### ISSUE TITLE
Start button is not working properly

### ISSUE THREAD

**Issue by xxMikhailx** [Ryochan7/DS4Windows#776]
When I start the DS4Windows it doesn't go to "Find controllers mode" so I try to click `Start` button but it doesn't turn into `Stop`.

There are 2 lines in log:
```
Starting...
Connection to ViGEmBus 1.16.112.0 established
```

As a result I cannot connect to my DS4.

Tried this on previously worked version 1.7.10 and then on 1.7.12 but nothing changes.

**Comment by Ryochan7** [comment]
Are you using shared mode or exclusive mode? Try using shared mode by unchecking "Hide DS4 Controller" in Settings. If the controller search routine hangs trying to get exclusive access then I think the button might still be shown up as Start despite that the Start routine is already running. It has been something that happens so rarely that I have not looked into why it happens. Pretty sure it is not my doing though.

That exclusive mode routine would eventually timeout so it should work no matter what. It would be best to test without having that routine run though.

**Comment by xxMikhailx** [comment]
Yesterday, I tried both with "Hide DS4 Controller" checked and unchecked and "Start" was still showing up

**Comment by Ryochan7** [comment]
Just checked the Jays2Kings code and confirmed that it works the same way. The button status does not change until after the routine is finished. I think I will change the form to at least disable the button while the routine is running.

Does DS4Windows eventually (< 30 sec.) operate as intended if left alone? The only other possibility that I could see from the code is that the UDP server would raise an exception, if the UDP server is enabled, and cause the Start routine to stop.

**Comment by xxMikhailx** [comment]
Basically, what you suggest is to open the application with "Hide DS4 Controller" checked and give it some time (<30 sec), then to try click Start button again?

**Comment by xxMikhailx** [comment]
I just tried uncheking the "Hide DS4 Controller", gave the program time (>2 min). Nothing happens, I'm clicking "Start" button and it doesn't do anything. I can't connect my DS4.
![image](https://user-images.githubusercontent.com/8850869/61972764-0f470a00-afeb-11e9-978c-a778cdd38a90.png)

![image](https://user-images.githubusercontent.com/8850869/61972787-1a019f00-afeb-11e9-90b5-7d6bba1b7988.png)

**Comment by mika-n** [comment]
What happens if you tick "Use DInput Only" option in a profile? This is just to test if the app works without VigEm virtual gamepad devices. If the app works with UseDInputOnly option then maybe you should remove the VigEm driver via DeviceManager (tick option to remove the driver file) and re-install it.

Note! Normally you don't want to use UseDInputOnly option if you want to do any of the key/button/axis re-mapping because only mouse and keyboard re-mapping works in UseDInputOnly mode.

**Comment by xxMikhailx** [comment]
@mika-n, ticked "Use DInput Only" option in profile and nothing changes I'm still can't make it go to Find controller mode and "Start" button is not switch to "Stop".

**Comment by mika-n** [comment]
Hmmm.... That is very strange because UseDInputOnly enabled means that virtual output gamepad device is not used at all, so the problem must be somewhere in more general level.

Maybe there is some kind of unhandled exception and the app goes in undefined state. There may be cases where the app doesn't log all exceptions in a log file if the exception happens in a separate thread and not in the main thread.

How about if you try to run the DS4Windows.exe executable from an administration CMD shell?
- Open CMD.EXE shell using "run as administrator" option
- Navigate to the DS4Windows installation folder (CD c:\myapp\ds4windows\ or whatver) and run ds4windows.exe from the cmdshell. 
- When you do this then do you see any error messages in a cmdshell window?

Maybe you should try to update .NET framework version, VisualC++ and ViGem runtime libraries.
- Microsoft .NET 4.8.x: https://dotnet.microsoft.com/download/dotnet-framework
- Microsoft VisualC++ 2017 and 2018: https://dotnet.microsoft.com/download/dotnet-framework
- ViGem and its prerequisites 1.16.x: https://github.com/ViGEm/ViGEmBus/releases/tag/v1.16.112

**Comment by xxMikhailx** [comment]
In cmd I can't see any log because it just finishes executing the command immediately:
![image](https://user-images.githubusercontent.com/8850869/62007415-cc557580-b155-11e9-820d-f75e43953b81.png)

**Comment by mika-n** [comment]
I would try to solve that component store corruption at first because Windows Update service probably fails to install new updates. After fixing this issue I would install all missing Windows updates and .NET framework updates.

**Comment by xxMikhailx** [comment]
Hello @Ryochan7, with new updates 1.7.13, 1.7.14 I even can't start the application. It just shows nothing but one of the interesting things is that I stated getting windows defender screen when I try to start the app.

**Comment by xxMikhailx** [comment]
Finally, I was able to resolve all of this. So, @mika-n was right about the root cause of the problem which was the error `Final Result: Installation failed with error code: (0x00003712), "The component store has been corrupted. " (Elapsed time: 0 00:01:20).`. Because of this error Windows was not able to update itself as well as the Microsoft .NET Framework.

I tried many ways to repair this component store corruption using DISM (from Windows Updates, from installation USB, network shared Windows folder) and non of them helped. **So, I was able to repair it only with Windows Media Creation Tool which upgraded my Windows.**

Thank you @Ryochan7. @mika-n for your help!
