### ISSUE TITLE
Wii U Pro Controller

### ISSUE THREAD

**Issue by vico93** [Ryochan7/DS4Windows#780]
I was watching some videos about controllers, and noticed how ergonomic the Wii U Pro Controller was.

![image](https://user-images.githubusercontent.com/3485505/62201386-b1ede880-b35d-11e9-8642-a9c0d5c91d90.png)

Is there any chance we see DS4Windows have support for Wii U Pro Controller as well? It would be amazing!

**Comment by Ryochan7** [comment]
There is no planned support for controllers other than variants of the DS4. A lot of portions of the code base depend on properties specific to the DS4 controller.

Besides that reason, I have used the Wii U Pro controller a couple of time before and I didn't really like it for the most part. The main reason is that ZL and ZR act as digital buttons instead of axes. I don't remember liking the feeling of those buttons either. Support for the newer Switch Pro controller would be more likely if I ever get back to working on a DS4Windows successor.
