### ISSUE TITLE
Virtual Controller batter level match DS4's

### ISSUE THREAD

**Issue by FusionLord** [Ryochan7/DS4Windows#787]
Not sure if it is an oversight or if there is a limitation in ViGEm.

Would it be possible to make the virtual xInput controller's battery meter match that of the DS4's?
I use a program that displays the battery level of my XBone and X360 controllers, it would be nice if it would show the virtual controllers as well.

**Comment by mika-n** [comment]
The existing version of ViGem driver doesn't support "virtual" battery level status information in its current version. Maybe it does in the future because there are some changes in the latest ViGemVBus devel version to support battery level (batterCharged vs batteryLvl) and DS4 touchpad regions (ie. multi-finger touchpad support where the existing version supports only touchpad click).

**Comment by Ryochan7** [comment]
That is a limitation of the ViGEmBus driver. There is no way to change the battery level reading on a virtual device. If that capability gets added then it wouldn't be hard to transfer that information.
