### ISSUE TITLE
Issues with binding RS Up/Down/Left/Right to D-pad buttons

### ISSUE THREAD

**Issue by eggw** [Ryochan7/DS4Windows#792]
I'm using a program where the only way to pan the camera is with the D-pad.

What I'm trying to do is bind RS Up/Down/Left/Right to the D-pad buttons so I can also use RS for panning. What ends up happening though is that the camera keeps panning and doesn't stop, which means that the buttons become "held down". As soon as I undo the RS to D-pad bindings, it stops. Just wondering if I'm missing something simple to make this work as expected.

Thanks

**Comment by mika-n** [comment]
Maybe you need to set a deadzone to RS stick to avoid it constantly "toggling" the re-mapped D-pad output button. From a hardware level RS/LS stick is hardly ever completely stable even when you dont move around t, so mapping this analog axis to a digital "axis" may cause unwanted toggling if you don't have a deazone for RS stick.

I just tested to map LS "left X-" and "left X+" axies to D-pad left and right keys. Worked just fine, but I had set a small deadzone in LS stick.

**Comment by Ryusennin** [comment]
A button or a key is a digital switch, it is either 0 or 1.

An analog stick is _never_ resting at zero, and thus setting a minimum dead zone value is mandatory to map a stick to a button/key, to prevent it from "drifting".

It would be helpful to mention it in the DS4Windows guide, because too many people seem to ignore this and keep reporting the same issue.

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping

**Comment by eggw** [comment]
Thanks - setting a 0.15 deadzone gave me optimal results.

Cheers
