### ISSUE TITLE
Joystick Misaligned

### ISSUE THREAD

**Issue by jbabcock024** [Ryochan7/DS4Windows#804]
i would get a new controller, but $50 is ridiculous. is there any way to change the joystick position so that my pc thinks its centered even though its not?

**Comment by mika-n** [comment]
In theory it would be possible through a custom output curve/deadzone/maxzone settings. But the problem is that in the current version of DS4Win these settings are symmetrical for left/right (and  up/down) sides of analog sticks. Therefore the result may not be optimal using these symmetrical output curve settings in your case.

**Comment by Ryochan7** [comment]
I think I'm just going to start forcing adding a default dead zone and anti-dead zone in profiles. Too many reports like this. The DS4, even when brand new, has analog sticks that wll not return to absolute center a lot. Values can deviate as far as 6% from center. On the PS4, it seems like the typical default dead zone for the sticks set in games is around 10%.

**Comment by mika-n** [comment]
Jep. I agree. New installations should have a bit bigger deadzone value in a default profile file because of "drifting stick" questions. However, if a stick is somehow broken/wear out and it is waaaaaaay off centered then symmetrical deadzone may not produce an optimal solution because it is calculated based on the true "128" center position. So is the question here about small drifting (=normal instability of analog axies which happens with ALL controllers and a default deadzone setting is for a good reason) or that the stick centers waaay off center because the spring in it is broken?

**Comment by jbabcock024** [comment]
thank you so much!

**Comment by Ryochan7** [comment]
Some people have asked about adding a cross based dead zone option before. Maybe something like that would help with that situation a little bit since the X and Y axis dead zones could be set separately. I wouldn't be so sure about going for a more extreme angle of allowing per direction dead zones.

The big issue that held back the idea of implementing at least a cross based dead zone option for the sticks was lack of space in the interface. Turning the current panels into scrollable tab pages would make room for more controls. Trying to implement that didn't work out last time. Performance issues came up so the idea was scrapped at the time.
