### ISSUE TITLE
Question: Make games detect Controller as DS4

### ISSUE THREAD

**Issue by dovahkiin98** [Ryochan7/DS4Windows#814]
When I use my controller wirelessly, games use the **Xbox** icons for buttons.

I recently connected my controller to USB and the game detected the controller as a **DS4**, giving me the **PS4** icons. But when I switched back to wireless (bluetooth), the icons were back to Xbox.

Is there a thing I can do to make the icons PS4 with wireless use too?

> The game was Shadow of the Tomb Raider.

**Comment by mika-n** [comment]
Are you using a DS4Win profile with "dualshock4" output controller type? The default output controller type is xbox360..

Are you using an exclusive mode or HidGuardian tool?
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

Maybe you are not using exclusive mode and when you connected the controller using USB connection the game detected the native DS4 gamepad device (ie. did not use DS4Windows created virtual controller at all)? But when you use BT connection the game detects the DS4Windows virtual controller and by default it is in x360 mode. 

Check your the Controller option in your DS4Windows profile settings.

And if you don't use ExclusiveMode or HidGuardian tool to hide the original physical controller instance then a game may detect it by default or randomly chooses between physical controller and DS4Windows created virtual controller.

If the game supports natively DS4Windows controller and you don't use re-mapping rules of DS4Windows then there is no need to use the app at all. This usually works fine over USB, but BT connection doesn't work in all PCs without DS4Windows app. In that case you need to use DS4Windows AND set a profile to use dualshock4 controller type if you want the game to see the controller as DS4 gamepad instead of x360 gamepad.

**Comment by dovahkiin98** [comment]
Switching the mode in the profile settings fixed it. Guess I haven't noticed it before, or it's new.

Thanks.

**Comment by dovahkiin98** [comment]
@mika-n 
A small sub issue. Games now detect the touch pad as the Back button from the Xbox controller, instead of using the Share button on the DS4 controller.

**Comment by mika-n** [comment]
Have you re-mapped the touhpad click events in DS4Windows profile? Check left / right / upper region touchpad events because you can define different events depending on did you click left or right or upper side of the touchpad panel.

**Comment by dovahkiin98** [comment]
I haven't changed the default settings of the touchpad. It just seems to be the default of all games to use the touchpad's right click.

**Comment by mika-n** [comment]
Yes. By default left and right click of touchpad are mapped as left mouse button. Upper touchpad click is  right mouse btn click and "two finger touchpad click" as middle mouse btn click. You can unmap these if you don't use touchpad as a mouse.
