### ISSUE TITLE
Bluetooth does not work but USB working

### ISSUE THREAD

**Issue by tkytky** [Ryochan7/DS4Windows#816]
DS4Windows app version: 1.17.16 
Windows Version: Windows 10 Home 
Gamepad: Dualshock 4 Ver 2

I am trying to connect the PS4 controllers to my HTPC but they are only able to work via USB but not via bluetooth. However, on bluetooth, the following works:

on Joy.cpl, the "wireless controller" is able to detect all inputs, same for HTML5gamepad. The "Controller (XBOX360 for WIndows)" is shown in Joy.cpl but does not detect any inputs.

On DS4Windows, log shows that controller is connected but does not show up on the controllers tab. Curiously the text "Controller 1 is using the profile "Default"" can be seen at the bottom. Attachment shows what i am seeing. Note that controller 2 is connected by USB and is working normally.

As wireless controller is detected by my HTPC, i don't think my bluetooth is not compatible. I am using the ASROCK B450I Fatality MOBO with a ver 4.2 bluetooth. Moreover, steam detects the controller perfectly and plays steam games well. However i need DS4windows to play non-steam games. 

I have been looking all over the internet for answers but to no avail. Hope someone can help!

Log (looks normal)

9/6/2019 7:39:29 PM: DS4Windows version 1.7.16
9/6/2019 7:39:29 PM: LinkedProfiles.xml can't be found.
9/6/2019 7:39:29 PM: Starting...
9/6/2019 7:39:29 PM: Connection to ViGEmBus 1.16.112.0 established
9/6/2019 7:39:29 PM: Searching for controllers...
9/6/2019 7:39:29 PM: Using Shared Mode
9/6/2019 7:39:29 PM: Found Controller:**:**:**:**:**:** (BT)
9/6/2019 7:39:29 PM: Plugging in X360 Controller #1
9/6/2019 7:39:29 PM: X360 Controller #1 connected
9/6/2019 7:39:29 PM: Controller 1 is using Profile “Default"
9/6/2019 7:39:29 PM: Found Controller:**:**:**:**:**:** (USB)
9/6/2019 7:39:29 PM: Plugging in X360 Controller #2
9/6/2019 7:39:29 PM: X360 Controller #2 connected
9/6/2019 7:39:29 PM: Controller 2 is using Profile “Default"
![Capture](https://user-images.githubusercontent.com/54985140/64426111-4aefec00-d0e0-11e9-8c05-f2eef1846b0e.PNG)

**Comment by tkytky** [comment]
Other similar issues on the forum involve the bluetooth not working at all. But in this case bluetooth is working the "wireless controller" as steam is working and games with native support like PES is also working. Something broke between receiving the input from wireless controller to output of xbox360..

**Comment by tkytky** [comment]
i purchased 2 more controllers and surprisingly one of the controllers worked. 

DS4windows recognised one of them and could gain information about the battery. The number of the controller which worked is also slightly different then the other 3. Does DS4windows only work with a certain type of DS4windows controller?

![image](https://user-images.githubusercontent.com/54985140/64472054-47fe0580-d18b-11e9-970f-9138a3f230ae.png)

**Comment by mika-n** [comment]
Hmm.. This is very strange. The virtual "x360" or "dualshock4" output controller object won't be created by DS4Windows if the controller is not detected as "supported". Still, it sounds like those couple controllers are not detected properly.

Do you see any activity in "DS4Windows / Controller Readings" tab page with those problematic controllers? And try to do it while connecting only one controller at a time.

Are all those controllers genuine Sony DS4 gamepads or some "compatible" models? 

What do you see as a model code in the back of the controller? And how about what is the hardware id in DeviceManager (vid and pid code)? See the following post for more info about how to check the vid/pid hardware identifier. There is also a link to a special debug version of DS4Windows which prints out detailed info of HID devices. That would be interesting to see.
https://github.com/Ryochan7/DS4Windows/issues/803

Also, try to start with a fresh new configuration and profile files just in case old profiles and config files have something strange. Navigate to DS4Win profile folder (and one step above it) and delete/backup all files from there and start from scratch.

**Comment by Ryochan7** [comment]
This project only supports first party DS4 hardware that I have access to. Any 3rd party DS4 controller support is left up to the community. I can't tell what the problem would be based on the posted reports.

DS4Windows does detect that the controllers exist and they match entries listed in the program. Not obtaining a serial number for a controller would probably cause problems within DS4Windows. Not obtaining battery and other information would indicate that input packet reading failed. The connection to the controller still exists though.

This issue would probably be best dealt with by debugging the program directly. There isn't much I would be able to do on my end to figure out what could be going wrong.

**Comment by naeem76** [comment]
I have the same issue, on usb mode everything works fine, except the battery level percentage, and the bluetooth connection it will add the VigEm controller, but no input works and also doesn't show it in the Grid of DS4Windows. After debugging it seems like the HID read data is invalid for bluetooth. If you need any other data let me know

**Comment by mika-n** [comment]
@naeem76  Make sure you have the latest version V1.7.17 (https://github.com/Ryochan7/DS4Windows/releases) because it prints out the type of DS4 controller (Sony rev1 or rev2 or some 3rd party supported). What do you see in Logs tab in DS4Win app?

What do you see in "Controller Readings" tab page?  This tab page is shown when you edit a profile. Does it show any reactions to L2/R2/LS/RS/gyro activity?

What is the hardware ID in DeviceManager for the controller in case the controller is not an official Sony controller? What do you see in the model and version labels in the back of the controller?

Does the controller work over BT without DS4Windows app in html5gamepad.com web site?

**Comment by naeem76** [comment]
I am using latest commits from the repo and running it from VS directly.

On logs it shows up as a DS4 v.2. But I'm pretty sure it was advertised as a 90 percent PS4 controller, something like proper motherboard, but aftermarket casing.

Controller works perfectly fine in USB mode, EXCEPT the battery reading, Gyro, Six all works fine.

In bluetooth mode, in windows it works fine, shows up as Wireless Controller, and all buttons work.
Also in DS4 Windows, it picks up some kind of inputs in bluetooth mode in 'Controller Readings' in the Right stick, but subtle, even the buttons make the Right Sticks readings react lol.
On the back it says Model CUH-ZCT2U.

I can post a HID input data log for both wired and bluetooth if you want.

For some reason I decided to remove the bluetooth connection in windows, and now I can't pair it again, doesn't show in add bluetooth devices, how to make the controller pair again? I held the button for 3 secs, it was blinking.

**Comment by naeem76** [comment]
Update: Everything works fine in bluetooth mode on html5gamepad.com

**Comment by naeem76** [comment]
Oh also normally in bluetooth mode it doesn't show up in the controller list, log says controller 1 connected, so I removed some of the fail checks to make it show up, thats how i got the weird readings in 'Controller readings'

**Comment by mika-n** [comment]
Hmmm.... That's interesting. The gamepad is detected as genuine DS4 revision 2 controller and the hardware vid/pid identifer code in html5gamepad confirms this also.

I think there has been few similar reports about a controller working over USB, but not over BT even when the controller was supposed to be an official Sony gamepad. Almost like the HID reports is something unexpected and "non-standard" data block even when the gamepad clearly works over BT if used outside of DS4Win app. Almost like the HID input report is something else than usually seen with DS4 gamepads.

It might be interesting to see a dump of HID data blocks coming from BT:
- When you are not pressing anything
- When you press a single button
- When you press a single Dpad key
- When you move RS stick all the way in one direction

But, if there really is a different kind of HID input report coming from your gamepad version then it may be a bit difficult to debug this without having an actual gamepad. But it seems that you are in a position to debug this in more details by adding some diagnosing messages and data checks in the VisualStudio code. See DS4Device.cs and line# 885 (performDS4Input function). There the hid input report is converted as cState object of DS4Win app.

**Comment by naeem76** [comment]
Interesting, The right stick moves the left stick axes perfectly.

Also for the Hid input report
byte[0] = 1
byte[1] = 128
byte[2] = 128
byte[3] = 128
byte[4] = 128
byte[5] = 15

rest are all zeroes

**Comment by naeem76** [comment]
According to this page, it seems very similar to the HID interrupt report here 0x01 here.
https://eleccelerator.com/wiki/index.php?title=DualShock_4#0x01

**Comment by naeem76** [comment]
Found an interesting repo, that manages to actually make some changes.
https://github.com/todbot/node-hid-ds4-test

**Comment by mika-n** [comment]
> Interesting, The right stick moves the left stick axes perfectly.
> Also for the Hid input report
> byte[0] = 1
> byte[1] = 128
> byte[2] = 128
> byte[3] = 128
> byte[4] = 128
> byte[5] = 15
> rest are all zeroes

Was this byte dump from the original btInputBuffer[] or from the "copied" imp[] buffer? 
The original "raw" btInputBuffer from DS4 gamepad is copied to imp[] byte array which points to inputBuffer[] byte array in case of BT connection. When the raw btInputBuffer is copied to imp (=inputBuffer) byte array then the first two bytes are skipped.

Maybe you should dump the content of the original raw btInputBuffer from BT connectivity and another dump from inputBuffer when using USB connection? It would be interesting to see the differences between these dumps.

Also, take a dump of btInputBuffer (=BT connection data buffer) when you don't press anything, press just one button, just one DPad key and move RS Y-axis to just one direction and RS X-axis to just one direction. Do these as separate data dumps because it will be easier to see differences in those raw buffers when you have activated just one button or analog axis.

By the way. Do you have Win7 or Win10? And you have the latest DS4 device drivers installed? Maybe you could try to remove the DS4 gamepad driver in DeviceManager and let Windows Update to install the latest driver.

**Comment by naeem76** [comment]
I got it from line 798
HidDevice.ReadStatus res = hDevice.ReadWithFileStream(btInputReport);

I thought that's where the input was being read, might be wrong.

Triggers and buttons all work and are sent in this 0x01 mode 

[0] | Report ID (always 0x01)
[1] | Left Stick X (0 = left)
[2] | Left Stick Y (0 = up)
[3] | Right Stick X
[4] | Right Stick Y
[5] | TRI | CIR | X | SQR | D-PAD (hat format, 0x08 is released, 0=N, 1=NE, 2=E, 3=SE, 4=S, 5=SW, 6=W, 7=NW)
[6] | R3 | L3 | OPT | SHARE | R2 | L2 | R1 | L1
[7] | Counter (counts up by 1 per report) | T-PAD | PS
[8] | Left Trigger (0 = released, 0xFF = fully pressed)
[9] | Right Trigger

I think the problem lies in the fact that its not changing from 0x01 to 0x11 mode, which is the detailed data. 

I have win10 and drivers installed via Windows update.

Also I cant change colours with DS4Windows, but with the node-hid-ds4-test i can, as well as rumble.

I will post more dumps later if you need

**Comment by mika-n** [comment]
Interesting indeed. 

>I got it from line 798
>HidDevice.ReadStatus res = hDevice.ReadWithFileStream(btInputReport);

Yes. This ReadWithFileStream(btInputReport) is the place where the "raw" HID report is read from a BT communication stream. However, few lines below that this btInputReport is copied to imp[] buffer point AND the first two bytes are skipped. Then later on this copied buffer is used via inputBuffer[] array when a specific key or axis is interpreted. Anyway, this "skipping the first two bytes" might explain why right stick seems to move left stick in DS4Win app and in a virtual output driver because the raw buffer is now off aligned.

Normally the USB connection uses the raw buffer directly without skipping any bytes, because it doesn't have those extra 2 bytes in the beginning of the raw buffer.

Maybe you should try to use the btInputBuffer in a similar way as the DS4Device uses the USB InputBuffer? You could force the incoming BT hid input report to go through USB input report handling by doing following change in DS4Device.cs file:

Original Line# 786: _if (conType == ConnectionType.BT)_
Change this to: _if (false && conType == ConnectionType.BT)_
(and the check "if (conType == ConnectionType.BT && btInputReport[0] != 0x11)" in line# 879 should be also be commented out as you have already done).

The idea is to force the "conType==ConnectionType.BT" check in performDSInput function to be always FALSE and by this to handle the incoming report as it was in USB hid format (the ELSE block in this IF-THEN-ELSE logic).

Does the input work better after these changes? What do you see in "Controller Readings" tab page in DS4Win and in Joy.cpl controlPanel applet for the virtual output controller?

**Comment by naeem76** [comment]
Yes that would be a nice hack to at least make the buttons and axes work in DS4Windows bluetooth. 

But is there no other way to get full functionality from the bluetooth mode? that is all the gyro and other data as well.

According to docs, The 0x01 barebones report is sent until the GET REPORT FEATURE 0x02 is received by the ds4. I have tried using HID to send these reports, but no success, and i dont know much about it either. 

Looks like controller wont work fully in bluetooth, oh well.

**Comment by mika-n** [comment]
Does the gyro and lightbar work over BT when you use, for example, Sony's own "PS4 Remote Play" app (ie. no DS4Win app running in background) and remotely try to use some PS4 game with a touchpad and/or gyro support? 
https://remoteplay.dl.playstation.net/remoteplay/lang/fi/index.html

If that works then definitely it should be possible to make all those additional features to work in DS4Win, but someone should debug why and what handshaking is now missing in BT communication and why your controller doesn't reply with the "standard" BT hid reports. It is veeeery difficult to debug this without actually having a DS4 gamepad device with this communication problem.

**Comment by naeem76** [comment]
PS4 remote play detects it in USB mode, but not when paired with windows in bluetooth mode.

I don't have a ps4, so can't proceed further

**Comment by mika-n** [comment]
How about Steam and some game there with a native Ds4 support and with touchpad and gyro functionality? If you find that gyro and touchpad works over BT without Ds4Win app in Windows then this is just a matter of debugging and testing hid data reading and hid output messages.

But I wonder what are those controllers? Are those really genuine Sony devices or some wanna-be copies?

Did you get button and axis activity to work in Ds4Win by doing the code tricks I described?

**Comment by naeem76** [comment]
There is no gyro data in BT mode in windows, unless someone can make some kind of handshake that will make the controller send 0x11 data. I give up for now lol.

**Comment by mika-n** [comment]
So, it looks like these controllers are having problems in BT communication line. The DS4 gamepad doesn't respond or handle properly the "change BT to DS4 feature mode" handshaking message sent by DS4Win app. By default DS4 gamepad is in PC-friendly mode (0x01 hid report) in bluetooth and reports activities only in buttons, sticks and triggers. 

By doing those few code changes (ultimately there could be an option in DS4Win to use just this "PC friendly mode" in BT) these problematic gamepad devices would work over BT in DS4Win, but without gyro and touchpad.

@tkytky, @naeem76  I believe you both have this same issue. TKytky might get his/her gamepads to work over BT (without gyro and touchpad) also if there would be an option in DS4Win to ignore touchpad and gyro in BT communication.

One last question as an academic curiosity. @tkytky @naeem76  Have you tried these problematic controllers in PS4 console and does it work perfectly over BT (touchpad and gyro)? This might reveal if those are real genuine DS4 gamepads or not.

**Comment by naeem76** [comment]
I will test as soon as I can get my hands on a PS4, I have a feeling they won't work, lets see, fingers crossed.

**Comment by myxture** [comment]
Though not exactly the same, I have a similar issue. Until yesterday, USB and BT connections worked fine, but now DS4Windows can't see the controller over BT. Still works over USB.

I can connect my DS4 to Windows, but can't seem to do anything with it. It doesn't even show up in Device Manager or Devices and Printers in Control Panel. DS4Wiindows doesn't detect anything, no messages show up in the log after startup.

I can't think of any changes that could cause this. All that has happened is a definition update for Windows Defender. Things I've tried so far, with no success:

- Updating DS4Windows from from 1.7.15 to 1.7.17,
- Removing the device drivers while connected over USB,
- Rebooting my PC.

**Comment by mika-n** [comment]
@myxture  If you are not using HidGuardian tool then the controller should show up in Joy.cpl controlPanel applet when you connect it via USB or Bluetooth (without running DS4Win app). If it doesn't show up there then there is not much DS4Win app can do. In that case the issue is in Windows OS settings and/or BT pairing.

Make sure there are no error icons and warning icons in WinOS Device Manager.

Take a look at the troubleshooting documentation page for tips about BT connectvity and how to re-pair the DS4 gamepad and WinOS in BT.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

Try to disable GeForce Overlay because there has been few reports that new versions of GeForce Overlay feature may cause some weird problems in DS4 gamepads.

**Comment by myxture** [comment]
Thanks for the reply @mika-n! It didn't even show up in Joy.cpl, but now it's working again somehow after re-adding the controller as a BT device. So it wasn't a DS4Windows issue after all.
