### ISSUE TITLE
Wi-Fi Drops out after 30 minutes of DS4Windows Bluetooth connection.

### ISSUE THREAD

**Issue by Lemagex** [Ryochan7/DS4Windows#820]
Did not have this issue until the last update, rolling back does solve it but would still like to open this as an issue and have it looked at. As the title states, after updating 30-40 mins of use of controller on Bluetooth causes Wi-Fi to drop out, rolling back DS4Windows fixes the issue, not sure what's going on?

**Comment by mika-n** [comment]
Please see the "Troubeshooting" for tips about BT connectivity and how to debug connections and to provide more info (DS4Windows Log tabpage content, versions, Win environment description etc):
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

What is your BT polling rate in DS4Windows? Try to make it bigger because "too fast" polling rate may cause problems if BT device driver can't keep up with the pace.

Do you really mean that WIFI drops out? Not just BT drops out? Hmmm.... Can't see how WIFI can even theoretically break because of DS4Windows application unless your PC has an integrated BT/WIFI chipset and device driver and there is a bug (memory leak?) . Some cheap BT implementations share the chipset with WIFI connectivity, but still something like what you described sounds like a device driver issue. Make sure you have the latest updates fo Windows and to the BT/WIFI device driver. Jump into manufactures page to see if there is updated driver available.
