### ISSUE TITLE
Fifa 20 and ds4 controller

### ISSUE THREAD

**Issue by Wixglo** [Ryochan7/DS4Windows#821]
I have two problems: the first being that on the demo of fifa 20 we can not do anything in the menus and the second being that I can not hide the controller ds4 and therefore I can not play with my friends as I wish .
thanks for the help

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by Ryochan7** [comment]
This has been the case with the previous 2 installments of FIFA. This is not something that can be fixed in DS4Windows. The easiest way around the problem is to install HidGuardian. Getting rid of some extra software (GeForce Experience tools) would be helpful as well. As long as exclusive access to the DS4 is obtained then it should work fine.
