### ISSUE TITLE
Less key when I connect the controller via Bluetooth

### ISSUE THREAD

**Issue by Ansem93** [Ryochan7/DS4Windows#836]
Hi everyone!
I'm trying to use my PS4 controller (ps4 pro model) with my computer.
I noticed that if I connect it via cable I have this key:
![immagine](https://user-images.githubusercontent.com/6626218/65465609-06dd4500-de5d-11e9-8725-e1da1183032a.png)

and if I connect it via Bluetooth I have this ones instead:
![immagine](https://user-images.githubusercontent.com/6626218/65465640-1b214200-de5d-11e9-8396-69fa174c0820.png)

Is it normal? How can I have the same key on both cable and BT?

**Comment by mika-n** [comment]
The screenshot showing less buttons is from x360 controller which is the virtual controller created by DS4Windows app. Those are the standard buttons available in x360 controller. For example touchpad click button is missing because it is not supported in x360 gamepads.

The first screenshot is probably from the original physical DS4 gamepad controller device (ie. not created by DS4Win app) and it has more buttons than x360 gamepad profile. Those extra buttons are touchpad click and (for some reason) DS4 duplicates analog L2 and R2 triggers both as analog axis and digital button. You should see this if you press L2/R2 analog trigger keys while you are looking at WireslessController activity in those controlPanel screens

So, even if those screens have different number of buttons then you are actually missing just one digital button in x360 controller screen (ie. touchpad click button). Other two missing are L2 and R2 trigger digital buttons, but it doesn't matter because L2 and R2 is actually an analog "rotational" key. Fourth missing key is "PS" button which is emulated as a special X360 gamepad "Guide" key and it is not shown in x360 gamepads as a "normal" digital key..

So, you were actually comparing apples and oranges.

**Comment by Ansem93** [comment]
Thanks for the answer! I would like to use the touchpad clicks of the ps4 controller, so I'll try to change the option as you suggested!
