### ISSUE TITLE
PS4 controller connected acting on it's own

### ISSUE THREAD

**Issue by Dearrx** [Ryochan7/DS4Windows#851]
Hello, 

For me it's possible to connect the controller and i see it in the tab Controllers.
But when i start DS4Windows connect the controller. 
Then start Origin > start Fifa 20 
The controller works but it's also selecting things on its own while i give no input at all. 

I already tried to remove the profile and add the controller again but didn't work. 
Got Windows 10 64x

**Comment by mika-n** [comment]
You probably have an issue with double inputs (ie. both the physical DS4 gamepad and a virtual gamepad created by DS4Windows app sends inputs and FIFA doesn't know how to handle that situation properly). See the following post:
https://github.com/Ryochan7/DS4Windows/issues/608

Are you using exclusive mode (="Hide DS4 controller" option in DS4Windows settinsg) or HidGuardian 3rd party device driver to hide the original physical controller?
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

If "exclusive mode" doesn't work in your PC enviroment then HidGuardian is the ultimate tool to hide the physical controller from FIFA (and other games having problems with double inputs).
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer

Another reason for weird things in games may be deadzone settings in analog sticks and gyro. If you have zero deadzone in LS/RS sticks or in gyro (if you use gyro for some control) then you might get small drift because LS/RS/gyro is not completely stable in a hardware level (ie. LS/RS stick doesn't always return to the same exact resting position because of HW springs, wear out and dust).
https://github.com/Ryochan7/DS4Windows/wiki/Settings#axis-zone-mapping
