### ISSUE TITLE
Charging (USB) during bluetooth use, possible without the UAC prompt?

### ISSUE THREAD

**Issue by PoliteTimesplitter** [Ryochan7/DS4Windows#853]
Though I like to top up my battery when I can, I generally prefer to play wireless and playing wired can really mess up if the wire becomes loose and disconnects; if I'm mid-game, I can't restart it in exclusive mode. So I play bluetooth but would like to plug in just to charge without the inputs / connection going through wired.

As far as I can tell, the best way to do this is to connect via bluetooth, have Quick Charge disabled and then connect USB - when the UAC comes up, if I hit 'yes' it pauses for a second and then asks again, in an infinite loop if I keep saying yes. If I say 'no' then it starts charging and the connection is still bluetooth. It doesn't look like it interrupts the process so if I'm playing something, I keep exclusive mode, thankfully.

However, it might cause issues because it pops up over everything else, or if selecting 'no' does something that might end up breaking exclusivity mode or somesuch.

Is this the best way to charge while maintaining bluetooth connection? Is there any way to plug-to-charge without having the UAC prompt pop up?

**Comment by mika-n** [comment]
I have several usb cables which charge only but doesnt connect. With those cables DS4 works only over BT. Try to find some cables which dont connect all data lines of usb channel.
https://github.com/Ryochan7/DS4Windows/issues/541

Or plug usb to a wall charger or to a monitor (ie. not to PC).

UAC prompt of Ds4win is because of exclusive mode or HidGuardHelper app, so you cannot use exclusive mode without elevated priviledges. You could run Ds4Win app by choosing ”run as administrator” option or set it to launch via taskScheduler with elevated priviledges option set.

**Comment by PoliteTimesplitter** [comment]
> You could run Ds4Win app by choosing ”run as administrator” option or set it to launch via taskScheduler with elevated priviledges option set.

Set it to run at startup as a task with admin privileges and now it works flawlessly; thanks a ton!
