### ISSUE TITLE
High latency with multi-action mapped button

### ISSUE THREAD

**Issue by HadMatter** [Ryochan7/DS4Windows#854]
I set a few buttons using the multi-action option (under special actions) that allows you to set a macro to a tap, hold, and double tap of each button, and I'm noticing significant latency from those buttons now - specifically from the tap trigger. For instance, I have jump mapped to the tap trigger, and roll to the double tap trigger. Roll appears to work as expected, but jump lags bad. If I had to guess I'd say in the neighborhood of 500ms. I only see this lag for buttons set using that multi-action option; if jump is just mapped normally the lag disappears. I guess I'm just curious if this is just something that's inherent in the way these multi-action setups work, a fluke, or if maybe I'm doing something wrong. Anybody else experience this as well?

**Comment by mika-n** [comment]
Yes. That's the way how the multi-action key works. The feature needs to identify if the key was just tapped or hold down or double tapped. There is a time based (ms) calculation to identify each of these states. Especially the difference between tap and double tap because multi-action macro doesn't know "in advance" if the click was just a single tap or double tap. There is a short delay which waits for a second tap, but if it doesn't come in then the key is treated as single tap event.

Multi-action speckey macro is derived from an original JayKings version and it is a bit of a mess.
