### ISSUE TITLE
[Memory leak] DS4Windows uses more than 200MB of RAM

### ISSUE THREAD

**Issue by SkyEmie** [Ryochan7/DS4Windows#866]
Hi, 

I noticed that DS4Windows uses a lot of ram, probably a memory leak. When you launch it, DS4Windows uses about 20mo of ram. But when you connect a controller, the ram used increases (about 0.5mo/sec with the default pool rate at 4ms) until it reaches more than 200/300mo, where it stabilizes

![ds4windows ram usage](https://user-images.githubusercontent.com/29162548/67403371-1a8ddf80-f5b2-11e9-8864-a8b7ddefee01.png)

I use the default configuration, and when trying to change the settings I noticed when I set a low pool rate (like 1/2ms) the "memory leak" is more important (1mo/sec), and when I set the pool rate at 8/10ms it turn around 0.1mo/sec but still here. It looks like a queue list not cleared? Any solution to that?

Thank you for your work and ur activity :)

**Comment by mika-n** [comment]
take at look at this: https://github.com/Ryochan7/DS4Windows/issues/730#issuecomment-508849483

The memory usage is high because by default DS4Windows.exe.config config file enables server .NET garbage memory collection mode. It is better with CPU performance, but uses a bit more RAM than normal "client mode" .NET apps. You can change the config option if you worry about the RAM. However, .NET garbage collection will eventually kick in and releases unused memory blocks.

**Comment by Ryochan7** [comment]
As mika-n mentioned, that is mostly a consequence of using server mode garbage collection for the .NET Runtime. The .NET Runtime garbage collector will be much less aggressive than normal so the memory usage can be a bit higher than expected before the garbage collector kicks in. The limit will depend on your system and currently used system resources. On my system, it usually tops off around the 80 MB - 100 MB range. Especially with how many times the controller input thread loops, using server mode garbage collection makes a big difference regarding perceived input latency.

Running the garbage collector manually is technically an option but tests before have shown that even linking to the routine, not even calling it, caused application slowdown across the board. My current efforts with the WPF app led to finding a different overload that seemed to work better for a minor test. I have not looked into it further as I have been trying to get other functionality ported over first.

**Comment by Ryochan7** [comment]
It seems that the moral of the story is don't use .NET if both speed and a low footprint matter in an application. I have been trying out different garbage collection strategies and it might not work out. I have gotten the WPF dev version to use up to 250 MB of memory on my system so just allowing the .NET Runtime to handle it probably won't be an option. Manually invoking the garbage collector can work depending on how it is called and app speed can be pretty close to normal. However, despite the .NET Runtime freeing objects on the heap, it looks like it will keep allocated memory reserved until the Runtime determines that it needs to release memory to the system.

**Comment by Ryochan7** [comment]
I think I might have a garbage collection strategy that can be used now. Got it to the point where the WPF dev version is around 44 MB after 2.5 hours (peaked at 46.2 MB before GC freed some memory) rather than 250 MB in 30 minutes. Performance seems to be on par as well.

I checked the current WinForms build as well and peak memory was around 85 MB before the GC kicked in; garbage collection occurred after running the app for about 14 minutes.

**Comment by Ryochan7** [comment]
This seems to be working fairly well in the latest release. This ticket came about at the right time with the work going into the WPF version.
