### ISSUE TITLE
Fortnite bt controller

### ISSUE THREAD

**Issue by Arrif4** [Ryochan7/DS4Windows#868]
So I've been playing bluetooth for so long however today when I got on fortnite my input is recognized as controller if i press a button however nothing responds. If i press X nothing will happen. My controller works for everything without fortnite and I have all correct gamepad settings on in settings. Also no other fortnite players have this issue so idk what to do since fortnite wont respond to me

**Comment by Ryochan7** [comment]
Does DS4Windows have exclusive access to the DS4? IIRC, Fortnite has support for the DS4 in DirectInput mode so there is a chance the game will try to use the BT DS4 controller rather than the virtual Xbox 360. The problem is that the DirectInput DS4 will be seen as a dead controller due to the mode switch DS4Windows does to activate the extra controller features (lightbar, gyro, touchpad). USB connections don't have that problem though. Please make sure DS4Windows has exclusive access to the DS4 before launching Fortnite.

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

**Comment by Black00Z** [comment]
Can confirm the issue with Fortnite since the last update. Seems like Fortnite tries to override the input or sees the DS4 input as dead and causes the controller to behave weird. Using DS4Windows after connecting the controller normal over Bluetooth changes nothing.

How to give "exclusive access" as you mentioned @Ryochan7  ?

**Comment by mika-n** [comment]
> How to give "exclusive access" as you mentioned @Ryochan7 ?

Read the Wiki docs linked in the previous post (wiki page about exclusive-mode) and then general Troubleshooting page. Anyway, you are most likely experiencing "double input" problem and those linked Wiki pages explains what it means and how to solve it.
- Option 1: Enable "Hide DS4 Controller" in DS4Windows application options (general app options, not a profile specific)
- Option 2: If you cannot get HideDS4Controller to work (=exclusive access feature of DS4Windows app) then you could use HidGuardian device driver solution to solve the "double input" problem. This works for sure because HidGuardian is a kernel level driver, so it can do much more than an application level apps.
