### ISSUE TITLE
ps4 controller higher input delay while on wireless

### ISSUE THREAD

**Issue by bernovan11** [Ryochan7/DS4Windows#875]
so i just tried ds4windows to my ps4 controller yesterday, everything was good but when i went to wireless i got 8-10 ms input delay. It should be around 1-2 ms right, any idea ?

**Comment by Ryochan7** [comment]
It depends. If you are using the Sony Wireless adapter then the poll rate should be around 8 ms. The adapter forces a fixed poll rate for the controller. If you are using a Bluetooth connection then the default in DS4Windows should be around 4 ms. The old Jays2Kings version only supported the maximum poll rate and that poll rate was a bit too fast for ScpVBus.

Getting a slower connection with a Bluetooth connection will likely mean that the BT adapter is not up to the task. You definitely need a BT 4.0 adapter in order to ensure a decent connection with the DS4. An older BT 2.1+ adapter might work under certain circumstances as long as you only use one conroller.

**Comment by bernovan11** [comment]
im using the cheap Orico usb bluetooth adapter 4.0 (BTA-403), is that the problem ? should i buy the better one ?

**Comment by Ryochan7** [comment]
Missed the reply. Maybe you can try disabling some power management options or run the High Performance power profile. Power Management can make the USB ports uses less power which can limit throughput and cause lag. Checking general system (especially Disk) usage should also be done.

There is also the option that the USB hub that the port is on is just taxed too much. I had a problem with my webcam dropping frames every once in a while. I thought the problem might have been an OBS configuration issue but the problem went away when I plugged the webcam into a different USB port.
