### ISSUE TITLE
DS4 Windows often completely locks up system (100% CPU usage)

### ISSUE THREAD

**Issue by aburke20** [Ryochan7/DS4Windows#879]
So really not sure what is triggering this as it happens sometimes on startup, sometimes while connecting using the controller, and sometimes randomly when not even using the app (open but no controllers connected).

My system will pretty much lock, and in the task manager it shows as "system interrupts" taking up 100% of resources. HOWEVER, I am using rainmeter and a CPU widget, which locks up showing the last highest CPU user as DS4 Windows (kinda like in a murder mystery when the deceased's watch is broken at the time of death).

Obviously once I manage to get the desktop to crawl to "end process" the computer resumes and is totally fine.

Any particular reason this might be happening ?

**Comment by Ryochan7** [comment]
Haven't had any lockup problems since switching from ScpVBus to ViGEmBus; that would be the 1.7.x releases. The closest thing would be failing to obtain exclusive access. Depending on what is running, it will take some time before the GUI shows a newly connected controller if DS4Windows takes a long time trying to obtain exclusive access; it will usually fail when that happens. The program should not lock up during that process though.

**Comment by mika-n** [comment]
@aburke20  Please see the following Troubleshooting web page for more tips about various issues and how to provide more details as part of the problem description (version of DS4Windows, content of Logs tab page, make sure you have the latest .NET framework installed, etc).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

**Comment by Ryochan7** [comment]
I just had this happen to me actually. Ended up switching profiles and then CPU usage jumped to 20%. Even restarting DS4Windows did not help. Found out that switching to a pure KB+M brought the CPU usage to a normal level. Switching back to a 360 profile caused a CPU spike again. 

I looked and there was an error with the emulated 360 controller shown in the Device Manager. An error must have occurred within ViGEmBus to cause the problem. I tried disabling the bus device and it wouldn't disable. Tried rebooting and Windows blue screened after waiting a few minutes.

Unfortunately, there is likely nothing that can be changed in DS4Windows to keep that problem from possibly happening again.

**Comment by mika-n** [comment]
Hmmm..... Did you switch between xbox360 and dualshock4 profiles? Because if the new profile uses the same output controller type than the previous one then DS4Windows doesn't create a new virtual output device, so this case shouldn't cause any extra logic in Vigem driver level. But if the new and old profiles use different output type then ViGem driver is commanded to close the previous output device and to create a new one. 

Maybe there are some race conditions in ViGem driver in those cases if profile switching is done rapidly back and forth? 

Maybe a short delay when old and new profile uses different output type? In most cases different output type probably means that the new profile is used in a new application (ie. not switching a profile in-game), so short delay may not be that crucial in those cases?

Or DS4Windows app could do a gamepad connection pool (x360 and ds4 output types having an own connection pool), so when a profile is switched then DS4Win would not actually close and re-open output devices. It would just re-use the existing device from this connection pool. Each physical controller would have own separate pool. If PC has only one physical controller then pool would hold only one x360 and one dualshock4 gamepad objects (if any of those have been used at all). This would also solve issues with FIFA game if gamepad is disconnected in the middle of a game then re-connected. FIFA would not see the disconnection event because the pool would keep the existing output gamepad object alive even when a physical gamepad was briefly disconnected.

**Comment by Ryochan7** [comment]
I cannot remember whether it was a switch from Xbox 360 to DS4 or Xbox 360 to a "Use DInput only" profile. There was definitely an unplug message in the Log. The last profile that I switched to was my ATS 360 steering wheel profile. I was just testing to make sure the lightbar button color changed with profile changes when the problem happened.

Maybe getting an output slot manager created will be needed so that it can be easier to add a delay for plug and unplug events. There was an unplug delay when using ScpVBus but it was removed with the transition to ViGEmBus. I never ran into that type of problem when using ViGEmBus before so it didn't seem like the delay was needed anymore. An output slot manager would make the device switch process easier and it will be needed when attempting to implement persistent devices and Xbox One controller emulation.

**Comment by genova447** [comment]
Hello - (sorry in advance, I'm not a programmer, and this is my first comment on Github - and I am just really new to this - so sorry also if what I will mention isn't actually relevant to here, though I thought it might be)

With what you wrote here Ryochan7: "I looked and there was an error with the emulated 360 controller shown in the Device Manager. An error must have occurred within ViGEmBus to cause the problem. I tried disabling the bus device and it wouldn't disable. Tried rebooting and Windows blue screened after waiting a few minutes."

It is the same issue that I have experienced quite a bit as well.

This exact same thing happens to me for certain, every day, if I leave my controller connected via bluetooth for hours (The issue doesn't occur when connected via USB), suddenly any game I'll be playing, will suddenly just cease to accept any input, and then I will usually proceed to check DS4Windows - which shows that the controller is seemingly connected fine - but if disconnect the controller (the Options + PS-button combination doesn't turn off the controller either, I have to hold the PS-button to force it off), it will still remain in DS4Windows as if it's connected - and of course in Device Manager it is as you said too, that it's there and bugged.
And finally too, when that happens, I can always expect that I will have to force-shutdown my PC, or I'll just get a bluescreen anyway.

But, for me it was never because I change profiles, it was always just the fact that it is connected for several hours over bluetooth (Being afraid to disconnect, since I often end up not being able to get it back on virtual port #0 )

I mean, I know nothing about what goes on in the background, so maybe this is utterly useless.
I would not be offended if anyone would decide to delete my comment therefore.

And well, also related to this issue (https://github.com/Ryochan7/DS4Windows/issues/877), the controller at times will suddenly move itself to port #1   rather than #0 - making it so that I have to restart my PC to get it to work*... but as far as I'm aware there's no program in the background suddenly starting up and forcing that to happen... but, I mean - it could be as well, and I'm just not bright enough to see that it happened.

*Well, I do at times manage to get it back on port #0, but it isn't usually because I turn off anything - it just suddenly seems to start working again. (Oh and, this specific thing happens on USB as well, unlike the other issue above which only happens on Bluetooth)

Of course, if there is any chance that I can supply any useful information, I will of course try to give it - though bear with me, I'll be slow probably.  (Sorry for the wall of text - not good at being concise)

**Comment by mika-n** [comment]
The way how DS4Windows handles physical controller disconnections is known to cause problems in some games (if the game is running while gamepad disconnects/dies/idle poweroffs). The problem is that some games don't seem to be able to pickup re-connected virtual gamepad device until the game is restarted. Maybe someday there will be connection pool to keep the virtual controller alive even when physical controller was disconnected. And when the same gamepad (identifier my MAC serial#) is re-connected then DS4Windnows will feed inputs from that physical controller into an existing virtual controller connection (kept alive in connection pool). This might solve some of those problems you described.

**Comment by Ryochan7** [comment]
The first step is being tested now. The most recent WPF beta build has an added 100 ms delay when changing the output device type. I am a bit leery about the change so it has not been added to DS4Windows stable as of yet. Hopefully the change works as intended.

https://drive.google.com/file/d/128XDikjRcYEFbwgfqzqKBJfS0m9Q92Zl/view?usp=sharing

I have not had an error with virtual devices happen since the one time I posted about. It does appear that the problem has also happened with the Windows builds of SC Controller as well. I will keep an eye on this situation.

**Comment by aburke20** [comment]
I'm not changing profiles or anything.

Literally just launching DS4Windows is enough to lock up my entire desktop. I'll occasionally launch it with task manager open and see it ramp up like:
20->40->60->80->100% CPU and then my system is locked.

Other times, my computer starts, there doesn't seem to be an issue, but as soon as I "interact" with DS4 in my task bar or something, same thing: instantly freezes with 100% CPU usage.

Sometimes I'm lucky and it will unfreeze, but a lot of time it just stays frozen until Explorer crashes, or it lets me very slowly get into task manager, and then kill the process.

I just tried using Ultrasearch to delete any old DS4Windows-related files, and downloaded a fresh version. Launched, and it instantly did the exact same thing: freeze system.

I'm so frustrated because I love this program and really don't want to have to use another one, but for me at least it's completely unuseable right now. Not a single clue why. Especially since it works flawlessly on my laptop.

**Comment by mika-n** [comment]
@aburke20  Is still still sometimes happening even when a gamepad is not connected? Just launch DS4Windows app and leave it "idling" in the background?  And did this problem start with V2.x releaase and V1.7.x release works fine?

If this happens only with V2.x releases then some users have had issues with WPF graphical interface and MSI AfterBurner/RTSS apps (those apps do Direct3D injections to monitor D3D app performance). If you use those apps then try running DS4Windows without them.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#nothing-works-and-ds4windows-app-and-vigem-driver-connection-silently-doesnt-do-anything

If this happens with the latest V1.7.x release also then the problem is not WinForms->WPF GUI transition. Is it DS4Windows app itself or Vigem driver causing the issue? Hmmm......  Do you have some old Oculus drivers installed in PC? Som very old version of Oculus caused conflicts with ViGem driver (oculus/Facebook used a rip off version of ViGem driver).
https://forums.vigem.org/topic/47/psa-oculus-software-can-crash-your-machine

When the CPU peaks to 100% then do you see anything in "%APPDATA%\ds4windows\log logfiles? If there is some environment specific issue and DS4Windows app starts to generate loooots of error exceptions then those might bring down the CPU if exception happens several times in a second. Exceptions should be seen in the logfile (V2.x versions).

**Comment by aburke20** [comment]
Gonna give a try to what you've said:

-It shoots up to 100% within 3 seconds of being launched, nothing to do with controller connected or not.

-I don't use MSI AfterBurner/RTSS apps, and the logs seem to show that ViGem is loading just fine.

-I might have Old Oculus stuff, but thought I had wiped it all. Ultrasearch says I have 21 folders that mention Oculus. Can it affect stuff even by just being there, not active ?

-Log says nothing out of the ordinary:
2020-01-18 10:24:28.7249|INFO|DS4Windows version 2.0.4
2020-01-18 10:24:28.7299|INFO|Logger created
2020-01-18 10:24:29.9907|INFO|Starting...
2020-01-18 10:24:29.9907|INFO|Connection to ViGEmBus 1.14.3.0 established
2020-01-18 10:24:29.9907|INFO|Searching for controllers...
2020-01-18 10:24:29.9907|INFO|Using Shared Mode

For the time being, I'm using Battle Encoder S., and it seems to have completely reined it in. No issues whatsoever. It stays under 1% usage, and works just fine.

No clue what is causing it to freeze up my system if BES can just tell it "hey, please don't" and it listens.

**Comment by mika-n** [comment]
This is weird. DS4Windows should not do much if a controller is not connected. Don't understand why CPU would go woooooe

DS4Windows is implemented on top of .NET framework engine, so it could be something with .NET framework also, but I guess you already tried to download and install the latest .NET Framework from Microsoft.

DS4Windows.exe.config file has `<gcServer enabled="true" />` line. It instructs the app to use server mode garbase collection of .NET framework engine. Try setting this value to false if it makes any difference (ie. false = workstation RAM garbage collection mode).

DS4Windows app does change few thread/process priorities to "above normal" (or high) state. This is because the app tries to make the gamepad reading thread as efficient as possible. This could be one reason why CPU load in your PC goes high, but I don't understand why it would go to 100% level. 

What is the CPU model in your PC/laptop?

**Comment by Ryochan7** [comment]
Had ViGEmBus take a dive last night. Switching controller types caused a CPU spike taking up one CPU core. No virtual controller was usable and the virtual device had errored out. Having no virtual controller plugged in made the CPU spike go away.

Also, had a system crash trying to reboot.

![20200121_214614](https://user-images.githubusercontent.com/581968/72908179-c1416380-3cfa-11ea-85b1-9d1406d2ed6e.jpg)

**Comment by mika-n** [comment]
Maybe "connection pooling" technique (as discussed earlier in other posts) would be useful to workaround potential bugs in ViGem driver when it connects/disconnects virtual gamepad devices rapidly (there were those thread cleanup bugs we helped ViGem team to fix, but maybe there are still some cleanup bugs waiting for to trigger in some circumstances).

Having a connection pool of xbox360 and dualshock4 gamepads would mean that even when a profile and output type is changed in DS4Windows then ViGem connection is opened only once per output type (per physical controller). Maybe optional setting to enable the use of connection pool? Hmm....... Shouldn't be too hard to implement into Startup/HotPlut (or into DualShock and Xbox360 classes) methods when those try to create a new vigem object.

**Comment by aburke20** [comment]
I do have the latest .Net (4.8)

Regular i7-8700K CPU in my personal build.

Sadly still keeping this thread open, as I suffer from the exact same issue all these months later (and despite updating everything regularly).

**Comment by Ryochan7** [comment]
That is fair. Luckily I have not run into CPU spike issues in a while but I have gotten a device unplug issue and BSOD in the past couple of days. I am going to assume any CPU spike that occurs will likely still be due to the force feedback thread. The actual error would likely be with the ViGEmClient library and not anything directly in the DS4Windows code though.

The only workaround to test the problem would be to disable the hooks for force feedback so no background thread would get created.

**Comment by aburke20** [comment]
**I STAND CORRECTED, ISSUE IS RESOLVED !!!!!**

I'd started the program for so long with Battle Encoder, that I never realized it was actually fixed by itself; and no longer thanks to Battle Encoder.

Discovered this as I was _just now_ making a short video to illustrate my sad predicament:

https://mega.nz/#!UgBR3IzC!yhjtiu_Kse2CSxY5QAo0LDI6XNY0RJfeBUtO8ug6obE

Thanks a million to everyone who tried to help over the months, to you @Ryochan7 obviously (forever grateful for this tool. PS: I'm actually still credited to this day as one of the French translator, and it makes me so happy that I was able to help in some small way) and @mika-n for the suggested fix which finally slayed this beast !!!

FIX WAS:

> DS4Windows.exe.config file has `<gcServer enabled="true" />` line. It instructs the app to use server mode garbase collection of .NET framework engine. Try setting this value to false if it makes any difference (ie. false = workstation RAM garbage collection mode).

**Comment by aburke20** [comment]
Just to make sure the video and "issue" are clear:

-00-42s = DS4Windows.exe.config is set with **gcServer enabled="true"**, it jumps to 100% and locks the computer every time DS4W is launched.

-42s-53s = DS4Windows.exe.config is set with **gcServer enabled="false"**, it seems (for now, but no reason to doubt) to be working completely normally.

**Comment by aburke20** [comment]
@Ryochan7 The above fix has still been working wonders, except that it switches back to "true" after every update, so my computer locks up after very update.

So, I'm wondering how important is it _really_ that it be set to true by default ? Because if it isn't ... is there any way to implement it to be set to false by default ?

Let me know either way,
Thanks for all the work you do !

**Comment by aburke20** [comment]
Hey, mind if we temporarily re-open this issue ?

The most recent update has changed the way the app works with HidGuard ... and now I am no longer able to manually edit the gscServer to be set to "false".

This was the only thing stopping my desktop from locking up with 100% CPU usage.

Unfortunately I'm back to square one with this new update, since it seems to ignore the HidGuardHelper.exe.config and DS4Windows.exe.config settings where I was manually editing the gscServer config line

**Comment by Ryochan7** [comment]
.NET 5 changed the app config file standard to use a JSON formatted file rather than XML file. The appropriate config file for HidGuardHelper would be `HidGuardHelper.runtimeconfig.json`. The new key for gcServer is "System.GC.Server" under "configProperties". Set the value to false.

**Comment by aburke20** [comment]
Worked flawlessly, thanks a million.
