### ISSUE TITLE
Re-pair feature

### ISSUE THREAD

**Issue by romi1996** [Ryochan7/DS4Windows#881]
Ds4 cannot BT Reconnect to paired PC because it's already connected and paired with the Ps4.
The manual solution is removing the whole device and pair it again.

**Comment by Ryusennin** [comment]
You can not officially connect one Bluetooth device (mouse, controller...) to several devices. You need to manually re-pair your controller each time you switch platforms.

**Comment by romi1996** [comment]
> You can not officially connect one Bluetooth device (mouse, controller...) to several devices. You need to manually re-pair your controller each time you switch platforms. That's why I mainly use my DS4 through USB.

I have switched to SCPDriver's latest build and it has re-pair function smooth as silk. (of course without the cost of my normal Bluetooth interface) Although it doesn't have any fancy features like Ds4Windows and at least it met my requirement.

**Comment by mika-n** [comment]
Do you mean ScpToolkit and its embedded "bluetooth driver"? ScpToolkit driver hijacks the bluetooth host. You may not be able to connect other BT devices to the same BT host when ScpToolkit has hijacked the BT host and driver. ScpToolkit does some fancy and non-standard stuff with BT drivers and that's why it works without re-pairing but the downsize is that you cannot use BT mouse/keyboard/headset with the same BT host. DS4Windows doesn't try to overwrite BT drivers, so it works with standard Windows BT drivers. This also means that you have to re-pair the DS4 gamepad if you want to use the same device between PS4 and PC.

**Comment by TristanYoung** [comment]
I solved this issue by having one or more controllers dedicated to the PS4, and a bunch of different controllers dedicated to my PC.  I didn't want to re-pair all the time, and I wanted to have backup controllers, which comes in handy when in the middle of a raid and the controller battery runs low.

I can't put myself up to connecting by USB.

**Comment by Ryochan7** [comment]
Luckily the DS4 is a PC only controller for me. I do not own a PS4 so I initially bought my first DS4 to use in Steam. I didn't end up liking Steam's support that much though despite its feature set. Also, the Sony Wireless Adapter makes switching between operating systems more convenient otherwise I would have to re-pair the DS4 each time I switch to a different version of Windows or use Xubuntu.

**Comment by romi1996** [comment]
> Luckily the DS4 is a PC only controller for me. I do not own a PS4 so I initially bought my first DS4 to use in Steam. I didn't end up liking Steam's support that much though despite its feature set. Also, the Sony Wireless Adapter makes switching between operating systems more convenient otherwise I would have to re-pair the DS4 each time I switch to a different version of Windows or use Xubuntu.

Well, I'm not playing on ps4 much but every time I played, I have to re-pair 2 controllers at the same time. Sometimes it doesn't work and requires complete controller removal from the system and start as new. I'm not using any dongle because I can't think of any use from my Bluetooth device so I chose to stay simple: use SCP if I use ps4 frequently and ds4windows if I'm not.
