### ISSUE TITLE
Strikepack FPS dominator support, how to go about it?

### ISSUE THREAD

**Issue by kurisu-gh** [Ryochan7/DS4Windows#882]
I just read #253 (now closed) and I'm also interested in getting support for the Strikepack FPS Dominator with DS4. I can reconfirm that the strikepack+ds4 v.1 VID+PID combinations in the referenced issue is the same as mine (SONY VID and 0x05C5 -> increment of the PID of the ds4 v.1's PID).

I cloned the DS4Windows project and simply added `
            new VidPidInfo(SONY_VID, 0x05C5, "Strikepack + DS4 v.1"), //Collective Minds Strikepack FPS Dominator add-on + DS4 controller` to the `knownDevices` array, built the solution, and ran the DS4Windows.exe but unfortunately it could not find the controller. @Ryochan7, would that be the correct first try? I'm not so familiar with the codebase, was just hoping it would be as easy as that.

The Strikepack+DS4 combination does not show up under the Game Controllers panel. Does this matter? The Strikepack+DS4 combination does show up under Device Manager as an HID. 

On a separate note, the Strikepack+DS4 combination can be successfully used with [ScpToolKit](https://github.com/nefarius/ScpToolkit). But I'd prefer to get this to work in DS4Windows somehow. If you can help point me in the right direction on how to develop this, I can give it a try.

**Comment by mika-n** [comment]
@kurisu-gh  Please try to run the "DeviceDetect" debug version of DS4Windows app to generate a more detailed log messages about the controller connection and VID/PID details. Download the linked ZIP file, extract it into the existing DS4Windows folder (the latest V1721 release) and run DS4WindowsDebug.exe app. Logs tab page of DS4Windows should show more details about detected HID devices.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems
https://github.com/Ryochan7/DS4Windows/releases

Anyway. When you run the debug version then keep eye on the list of detected HID devices. Is this 0x05C5 device shown in the list and detected as "potential ds4 gamepad"? Keep also eye on the Usage attribute of that device line. DS4Win app expects to find Usage=0x05 hid devices because usage 5 is a gamepad device. If your device is not registered with Usage=5 then the code should be modified to accept other usage types also for this device.

**Comment by kurisu-gh** [comment]
@mika-n thank you so much the suggestion. I tried it out and unfortunately, the device does not exactly show up with the expected VID+PID. Instead, it is the following:

`Path=\\?\hid#vid_0d8c&pid_0014&mi_03#9&2c5a111d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}  Description=HID-compliant consumer control device  VID=0x0D8C  PID=0x0014  Usage=0x1  Version=0x100`

So it is not Usage=5 and the VID is not as the expected 0x054C value. I'm thinking it's just detecting it as some sort of audio device? (probably detecting the audio interface of the adapter but not recognizing the complete controller?)

Using [EventGhost](https://github.com/EventGhost/EventGhost), I captured the device attached strings upon plugging in the Strikepack+ds4 v.1 into my computer and got the following:

```
System.DeviceAttached [u'\\\\?\\USB#VID_054C&PID_05C5#7&34f71c81&0&2#{a5dcbf10-6530-11d2-901f-00c04fb951ed}']
System.DeviceAttached [u'\\\\?\\USB#VID_0D8C&PID_0014#7&34f71c81&0&1#{a5dcbf10-6530-11d2-901f-00c04fb951ed}']
System.DeviceAttached [u'\\\\?\\HID#VID_0D8C&PID_0014&MI_03#9&2c5a111d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}']
```

So the first device string is really the controller I believe (VID 0x054C, PID 0x05C5). But it's not detected as an HID and thus it does not show up in the Device enumeration of DS4WindowsDebug (I guess I was incorrect in my previous post when I said it shows up as an HID under Device Manager). 

I don't know exactly how ScpToolKit works but it does successfully detect the Strikepack+DS4 v.1 device and create the 360 controller wrapper. I've already used this in various games such as Rocket League with no problem so I imagine we can somehow get this to work in DS4Win as well.

What else should I try?

**Comment by mika-n** [comment]
I believe ScpToolkit used custom USB and BT drivers and maybe it reads that device through that custom USB driver (using WinUsb.dll WinAPI service calls and interfaces). However, raw USB api is quite different than HID interface API used in DS4Windows, so even when it would be possible to read raw usb devices in DS4Windows it would need a completely new interface to do it.  And then the interface should be integrated with the rest of the DS4Windows data stream logic (writeOutputReport and readOutputReport interfaces in DS4Win code).

Anyway. I'm not sure if the custom usb/bt driver in ScpToolkit was only for DS3 gamepads because DS3 was always a bigger problem in PC than DS4 gamepad support. DS4 usb gamepads may work over standard Windows WinUSB API interfaces without any custom driver installations.

All I can recommend as the next step is that take a look at WinUsb_XXX API calls to query and read usb devices. Then try to integrate those calls into existing writeOutputReport and readOutputReport calls in DS4Windows code base (at the moment those methods assume that the attached device supports HID API calls).

**Comment by kurisu-gh** [comment]
Thank you for your guidance! Yes, this would indeed be my first time diving into USB API communication, so it is a bit out of my comfort zone for what I thought would have been a quick fix but totally some thing I'd like to look into. 

But an interesting thing happened when I digged through the Device Manager once again to confirm  how the Strikepack+DS4 v.1 device was categorized. I noticed there was a category I didn't recognize from before called `libusbK USB Devices` which contained a Game Controller with the VID+PID I mentioned before. A Google search showed this came from ScpToolKit which I already installed before playing around with DS4Win. I followed the [driver removal instructions for ScpToolKit](https://forums.vigem.org/topic/250/scptoolkit-removal-guide) to get rid of `libusbK USB devices` and by doing so, the device was released and re-categorized as an HID device!

And with that done, DS4Win can successfully detect Strikepack+DS4 v.1 and unexpectedly, it works using the latest release. I didn't have to use my build with the controller's VID+PID added to the `knownDevices` array.

So now my controller works in DS4Win emulated as 360 controller but I can't get it to work as a DS4 controller in Rocket League. Seems a similar issue is https://github.com/Ryochan7/DS4Windows/issues/871 so I'll be reading up on that.

Closing this issue because DS4Win can properly detect the Strikepack add on + DS4 v.1 as long as you have no other drivers messing with the device attachment (in my case ScpToolKit + libusbK drivers had to be fully uninstalled).

**Comment by kurisu-gh** [comment]
Finally got the Strikepack+DS4 v.1 to appear as a DS4 controller instead of a 360 controller in DS4Windows v1.7.21 so I'm writing one more comment here in case someone wants to know how I got it to work.

Seems the main problem as mentioned before was that I had ScpToolKit installed previously. It was not obvious that this was the problem because I can use a normal DS4 controller in DS4Windows without any problem while ScpToolKit was installed, so I assumed the Strikepack+DS4 should also work in the same way.

So to get it to work, I did the following:
* Ran the normal uninstaller for ScpToolKit
* Followed the [driver removal instructions for ScpToolKit](https://forums.vigem.org/topic/250/scptoolkit-removal-guide) to get rid of the `libusbK USB devices`. Seems the link is not working but it basically involves using [Driver Store Explorer](https://github.com/lostindark/DriverStoreExplorer) to scan the computer for drivers and remove everything under `libusbK`.
* In my Device Manager, I still had a lingering unknown HID/USB device which was trying to reference `Root\ScpVBus`. Using the command line with admin rights, I ran `devcon.exe remove Root\ScpVBus` to remove the lingering driver.

When I plug in the Strikepack+DS4, two "Wireless controller" devices should in the control panel USB Game Controllers. They both are not usable but it's OK. DS4Win will then detect the Strikepack+DS4 and you can set the controller to DualShock 4 mode in the controller profile ("Other" tab).

I've tested this in Rocket League. The DS4 button icons appear in the UI and DS4Win can also properly "suqare" the inputs of the analog sticks which is ideal for Rocket League.
