### ISSUE TITLE
Macro functionality simply doens't work

### ISSUE THREAD

**Issue by daninthemix** [Ryochan7/DS4Windows#884]
I assign the right touchpad to a simple macro - A button, hold while repeat.

I press the right touchpad - nothing happens. At all.

**Comment by mika-n** [comment]
You probably have "right mouse btn" event assigned to right touchpad event at the moment? RMB is assigned to RightTouchpad "key" by default, so unmap this because it may conflict with special action macros. At least here a special action macro with "repeat while hold / synchronized" options seem to work just with with RightTouchpad click event when the default mouse button assignment it unmapped.

If you still cannot get it to work then please see the following page for tips about how to log more detailed issue tickets (app version, provide a profile file as zipped attachment in the ticket):
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting
