### ISSUE TITLE
[HELP] PS4 controller over BT

### ISSUE THREAD

**Issue by Niggolo** [Ryochan7/DS4Windows#887]
Hello, 
I was trying use my ps4 controller over BT but DS4 not even detect it
It is already paired to windows
I tryed with TPlink BT-400 and ASUS BT-400, both not success
Can anyone help me?

**Comment by mika-n** [comment]
See "Troubleshooting" page and a "DeviceDetect" debug version of DS4Windows. Try running the debug version and provide the detailed logfile here for further analysing.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

Is it ta genuine DS4 gamepad or some 3rd party compatible gamepad?
Does it work over USB cable?
What do you see in "joy.cpl" (run that command) controlPanel applet once you have paired and connected the gameapd over BT? Is "Wireless Controller" listed there and does it show any activity when you press buttons?

Make sure you try the latest version of DS4Windows app? What is the version you are tyring to use?
https://github.com/Ryochan7/DS4Windows/releases

**Comment by Niggolo** [comment]
i uploaded the log
[Log.txt](https://github.com/Ryochan7/DS4Windows/files/3837194/Log.txt)
the device not showing up in joy.cpl untill i plug it thought usb (wireless controller and xbox360 showing up and both have activity when i try buttons)

**Comment by mika-n** [comment]
Hmmm... The logfile tells that the connection type is USB instead of BT and the gamepad is revision 1 DS4. The initial connection works and DS4Windows is able to read the serial# (=MAC address) of the controller but then the connection is immediately disconnected. Maybe bad USB cable because I have few cables which do exactly the same but other cables work just fine?

Are you trying to charge the gamepad from PC at the same time you connect the gamepad over BT? Usually that doesn't work if the USB cable is "fully connected" (ie. both data and power lines connected).

**Comment by Niggolo** [comment]
The controller is working OVER USB!
It is not even detected over BT (no cable connected)

**Comment by mika-n** [comment]
Have you gone through the Troubleshooting page and BT tips and tricks? 
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#gamepad-connection-over-bluetooth-bt

Try reseting the gamepad and then re-pair it with Windows PC (see Troubleshooting instructions about pairing in PC). You can hardware reset DS4 gamepads by using a paper clip to press a button on the bottom of small hole (backside of the DS4 gamepad).
https://www.playstation.com/en-in/get-help/help-library/accessories/controller--headset---playstation-camera/fix-ds4-controller-issues/

And when you pair and try to connect the gamepad to PC then unplug a powercord from PS4 console (if you have one nearby) because otherwise the gamepad may accidentally pair to PS4 console instead to PC.

After pairing you should see "Wireless Controller" in JOY.CPL controlPanel applet even without DS4Windows app (however touchpad/lightbar/rumble/gyro etc special features don't work over BT without DS4Windows app). If you don't see the gamepad in JOY.CPL then there is not much DS4Windows app can do. The issue may be then in a BT chipset/dongle in PC (=incompatible with DS4).

**Comment by Niggolo** [comment]
I did almost everything in the troubleshotting page but it is not showing in the joy.cpl
i dont even have a ps4...
I tryed with 2 BT adapter and the compatible one that is write in the wiki , asus bt-400 and tp link 400

**Comment by mika-n** [comment]
Sorry to say, but this seems to be a Pc/bt receiver/bt driver/gamepad issue if the pad doesnt show up in WinOS controller list when using BT. After all it is WinOS which creates the HID device object for other apps. You could try some live Linux usb bootable distribution to see if Linux can see the BT ds4 gamepad. If it works there then you know the BT receiver is OK but WinOS drivers are somehow buggy.

**Comment by mika-n** [comment]
@Niggolo   Any recent distro (Ubuntu, ArchLinux) probably supports gamepads and DS4 out of the box. You can test PS4 gamepad in Linux by using
Option 1: html5gamepad.html web site with Chrome browser in Linux
Option 2: Steam client for Linux
Option 3: Separately installed DS4DRV driver package if your distro doesn't support ds4 out of the box. DS4DRV has some cmdline tools to test ds4.

**Comment by Niggolo** [comment]
Almost corrupted my win10 system for try ubuntu shits lol, unable to try much thing because it have keyboard to US layout and i cant type anything in the terminal, i just got Ds4DRV detect the device mac andress pairing it with BT but i coulnt try button event, i will post more info when im able to try it

**Comment by Ryochan7** [comment]
Linux support for the DS4 is not that great. It does not help that the main driver changed the button mapping in later versions. ds4drv has not been actively in development for a long time and nobody seems to want to pick up development.

**Comment by Niggolo** [comment]
well so i think i will just use it over usb even if it is realy annoying

**Comment by Niggolo** [comment]
EDIT:
i removed every bluetooth software/driver and did everything fresh then i runned joy.cpl and paired the ps4 controller, it got detected from joy.cpl and buttons working but after 15/20 sec the controller turn off itself and disconnecting!
after installing ds4windows and vingen bus driver the joy.cpl stop detecting the controller!

**Comment by mika-n** [comment]
Sorry to say, but this really sounds like incompatibility between the BT receiver chipset/driver and DS4 gamepad (BT). Especially if WinOS also dropped the connection even when DS4Windows was not running.

Installing DS4Windows app and VigEm driver should not have anything to do with how WinOS bluetooth stack pairs and connects with devices, so I don't understand why WinOS won't see the gamepad after installing those apps even when you don't run DS4Windows app. 

One thing you could check in DeviceManager is to make sure that there are no warning icons in any of the devices (especially HID and gamepad devices) or device in disabled state. If you use "Hide DS4 Windows" option in DS4Windows app and the app happens to crash at "wrong time" then it may leave behind disabled HID/gamepad device. The fix is to re-enable the disabled device in DeviceManager.

**Comment by Niggolo** [comment]
i give up with this, i keep get the same result with multiple bt chipset!
Now i have a different problem with USB connection, im playing gta5 and after some minute the controller arrows stop working, only the arrows, every other button are working... why im so unlucky omg

**Comment by mika-n** [comment]
Maybe it is time to borrow DS4 gamepad from a friend and test if the original gamepad is faulty and causing those BT problems also?

**Comment by Niggolo** [comment]
after 2 months i finaly got the time to borrow a ds4 from friend and i can confirm everything is working.... now i have to undestand what is wrong? i saw somewhere ds4 have different firmware version and it might be this the problem? the ds4 i bought was original "from the description" but how i can know if that is true?

**Comment by mika-n** [comment]
The log file shows that you have DS4 revision1 gamepad. Those have been manufactured in years, because when PS4 Pro was released then the gamepad was updated to DS4 revision2. Those for sure have different firmware, but I don't know if there are differences between revision2 units.

**Comment by Niggolo** [comment]
they have the same model, i start think my one is pretty fake... anyway this one im using say DS4 v.2 in the log

**Comment by Niggolo** [comment]
i bought a new v2 ps4 controler and everything is ok now :D sorry!
