### ISSUE TITLE
Nacon Pro Controller 2 - not detected

### ISSUE THREAD

**Issue by Balda93** [Ryochan7/DS4Windows#889]
Hi i've just bought the controller and it is not detected by the DS4 program. How can I do?

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/issues/887#issuecomment-552842409

Download the debug version and provide a logfile. See the linked troubleshooting page and deviceDetect debug app version.

**Comment by Niggolo** [comment]
i have an usb with ubuntu, but for know if it is work there is something like joy.cpl but for ubuntu?

**Comment by Ryochan7** [comment]
It has been a while since I played around with Linux gaming so there might be newer tools than the ones I am familiar with. The utils that I know of are jstest-gtk and evtest (command line program). I would recommend using evtest to check your controller since most any new Linux game uses evdev support rather than joydev support.
