### ISSUE TITLE
Enter Button only recognised by Rayman 2 when not in a macro

### ISSUE THREAD

**Issue by RibShark** [Ryochan7/DS4Windows#89]
When I assign a button to the enter key outside of a macro, Rayman 2 will detect it, but when I create a macro where the enter key is pressed (even if that is all the macro contains), Rayman 2 will not detect that the key is pressed. Other games work fine, but I think Rayman 2 is very specific with scancodes etc...

**Comment by Ryochan7** [comment]
I will have to check this out. The proper scancode should be used in the output event even if it is being used in a macro.

**Comment by Ryochan7** [comment]
I just got around to testing this. Looking at the program Key Scan Codes, it appears that the proper event is fired in the macro. One main problem is that a key down event is immediately followed by a key up event. I am betting that Rayman 2 ends up ignoring that key input since there is no point in between when the game sees the Enter key as being pressed. Personally, I do not use the macro system.

http://delphiforfun.org/programs/Utilities/KeyCodes.htm
