### ISSUE TITLE
Xinput Doesnt show up with the version of ds4windows on cemu

### ISSUE THREAD

**Issue by JoelLindsey** [Ryochan7/DS4Windows#893]
Why does the jays2kings version work without any of these issues? xinput messes up always on this.

**Comment by mika-n** [comment]
messes up how? Doesn't work at all or works but some errors? 
Do you happen to have a controller shown with 00:00:00:00:00:00 MAC address in Controllers list in DS4Windows screens? If so then upgrade to the latest V1.7.22 version because there is a workaround to those problematic gamepads. 
https://github.com/Ryochan7/DS4Windows/releases

**Comment by JoelLindsey** [comment]
cemu or any game doesnt detect the controller as xinput only dinput. If i use the version you provided. @mika-n

**Comment by mika-n** [comment]
Hmmmm...... What kind of gamepad you have? Official Sony pad? 
What kind of DS4Windows profile you use? A profile in DS4Win can be set to output gamepad events as xbox360 or dualshock4 gamepad.
Do you have "Use DInput Only" option checked in a DS4Windows profile? If you have this option set then DS4Windows uses the original physical gamepad directly without doing any "DS4Win re-map magic". Try to uncheck this option in a profile.

https://github.com/Ryochan7/DS4Windows/wiki/Settings
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting

**Comment by IceLancerSR** [comment]
I just ran into this problem he vaguely described, cemu and retroarch exhibit same problem. All happened after installing hid guardian and registry. gamepad became exclusive alright, but for some reason it weirded out retroarch and cemu.
Launch RA = on screen shows xinput detected and connected, but gamepad is not responsive. Switching to dinput in RA and restart , made RA accept gamepad input.. even tho it still says using xbox ..i am going to stay away from hidguardian from now on ..if i can revert back registry and its drivers painlessly

**Comment by Ryochan7** [comment]
That might explain it. The DirectInput fallback interface presents itself to Windows as a "HID-compliant game controller" device. HidGuardian will likely end up hiding the DirectInput interface for the virtual Xbox 360 controller. You would have to make sure RetroArch is actively using the XInput Joypad Driver in order to have the Xbox 360 controller work in RA.

I had not gotten around to closing this issue until now. This just started as a "The thing don't work" post. Luckily your post added some feedback that could explain the problem in detail. Thank you IceLancerSR.

The easiest way to go about uninstalling HidGuardian is to use a utility that I had written a while back. It will present an uninstall option if HidGuardian is detected.

https://drive.google.com/open?id=1hs6AgM6yLeyr3htP9kY0T4N2vklRI2s9

https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer
