### ISSUE TITLE
PS4 STRIKEPACK F.P.S. Dominator - Support

### ISSUE THREAD

**Issue by sourceAida** [Ryochan7/DS4Windows#894]
There is no support for the PS4 STRIKEPACK F.P.S. Dominator.

I was wondering if it's in the works or the developer has no idea of the controller adapter??

**Comment by Ryochan7** [comment]
It looks like it is an independent piece of hardware. It would alter the input report sent from the controller before it is sent to the final device (PS4, PC). I would hope that the device sends normal VIP and PID codes associated with the DS4 for compatibility reasons. No matter what, DS4Windows should just see it as a normal DS4 controller. If that is not the case, I need the VID+PID pair for the device. You can find that info from the Device Manager by looking at the registered Hardware Ids. Here is an example for the Sony Wireless Adapter.

![hardware_ids_sonywa](https://user-images.githubusercontent.com/581968/69002417-aa266580-08b4-11ea-901c-7d9f180e146d.png)

**Comment by Ryochan7** [comment]
Watching a video detailing the Configuration Tool now. The first vid covered mapping changes that could be made from the device itself. There would be no need to make some form of replacement for that utility within DS4Windows. That would probably be better done as a separate project. Also, someone with the hardware would have to figure out the protocol used by the device and make a replacement utility.

**Comment by sourceAida** [comment]
First off thank you for your response. Also, I found those Hardware Ids you were looking for:

HID-compliant Game Controller
HID\VID_054C&PID_05C5&REV_0100&Col01
HID\VID_054C&PID_05C5&Col01
HID\VID_054C&UP:0001_U:0005
HID_DEVICE_SYSTEM_GAME
HID_DEVICE_UP:0001_U:0005
HID_DEVICE

Also when connected to the PC, this also pops up:
HID-compliant consumer control device
HID\VID_0D8C&PID_0014&REV_0100&MI_03
HID\VID_0D8C&PID_0014&MI_03
HID\VID_0D8C&UP:000C_U:0001
HID_DEVICE_SYSTEM_CONSUMER
HID_DEVICE_UP:000C_U:0001
HID_DEVICE

Furthermore, there is a mapping software built to map the buttons Yes. However, sadly that is where the support ends. You see the PC doesn't react to the controller as a quote on quote real controller. Example: Any game that you would run on (PC) with the StrikePack on will not detect it as a controller. That is why the DS4windows is essential to the StrikePack. To enable the StrikePack to utilize the 360 drivers, it would be absolutely amazing!

**Comment by mika-n** [comment]
kurisu-gh has reported that Strickpack FPS Dominator works already with the latest DS4Windows version. Is it so that in your setup DS4Windows doesn't recognize the gamepad at all or do you mean that the gamepad is recognized but you would like to use one of those non-standard DS4 features of Strickpack?
https://github.com/Ryochan7/DS4Windows/issues/882

**Comment by kurisu-gh** [comment]
Just chiming in here to add to what @mika-n already mentioned.

Yep, in #882 I also requested support for the Strikepack FPS dominator, but it turns it's already supported through the CronusMax device handle. In my environment, it did not work right away because I was using other software/drivers to get it to work (specifically ScpToolkit) and it prevented DS4Win from picking up the controller as an HID device. Details are in #882.

In your case, it looks like your computer is recognizing the controller already as an HID device. Definitely try the debug version of DS4Windows that @mika-n has mentioned to see what HID devices are being enumerated and make sure the Strikepack FPS dominator+DS4 is being seen. If so, the log should mention some thing like `Found Controller: 26:93:56:4A:00:00 (USB) (CronusMax (PS4 Mode))`.

I didn't do anything special to the Strikepack itself aside from just setting it to Tournament Mode and mapping buttons to the paddles. I'm also using the latest firmware available for the Strikepack. I also completely disabled controller support in my Steam settings in case you are using Steam.

I currently have DS4Windows set to create a virtual DS4 controller instead of Xbox, but I did briefly try the Xbox mode and it works perfectly fine too.

I don't use the Strikepack's MOD mode so I don't know if using that mode changes anything. But in Tournament mode, the controller works perfectly fine even with the mapped paddles. I can also change the paddle mappings on the fly in game without any problems.

**Comment by sourceAida** [comment]
Wow it actually works NOW!!(I just tested it) I remember months ago that the Strikepack not being able to work on PC even with DS4windows. I even look into workarounds on Youtube for solutions since this was a common known issue for the PS4 Strikepack community. Since then I kept looking at the "change logs" for DS4windows and never seen anything regarding "Strikepack Support" as I was hoping to see eventually. Thus, I finally decided to try it again due to "Kurisu-gh" response since he said it work for him and I'm glad I did! So I don't know really what Ryochan7 has done to fix the issue since then, but man all I gotta say is THANK YOU! 😁

**Comment by kurisu-gh** [comment]
That's great to hear!

I think it was just by coincidence that the Strikepack is supported. It happens to have the same VID+PID as the CronusMax and I guess that was added some time after you tried it a few months ago.

**Comment by mika-n** [comment]
Jep. CronusMax support was added in V1.7.9 version and Strikepack must be physically identical device or those two products use the same custom DS4 chipset in some parts in hardware level. It is quite typical to have the same Chinese DS4 wanna-be product under several commercial brands.
https://github.com/Ryochan7/DS4Windows/releases?after=v1.7.10
