### ISSUE TITLE
Updating is not working to the latest version 1.7.22

### ISSUE THREAD

**Issue by oliverbevan** [Ryochan7/DS4Windows#895]
I am on 1.7.21 and the program is telling me to update, however when I click yes, nothing happens.

**Comment by kurisu-gh** [comment]
Same thing happened to me, actually. I just closed DS4Windows and ran DS4Updater.exe myself.

**Comment by nandocova** [comment]
Same problem. Had to update manually.

**Comment by Ryochan7** [comment]
I have not had a chance to check this out yet. Luckily I am at a point where I need to double check the updater anyway.

**Comment by George3011** [comment]
Running the updater regularly didn't work for me, but running it as admin worked fine

**Comment by 3941** [comment]
From 1.7.21 changelog:
"Fixed old bug when checking for DS4Updater that could have caused a thread lock"

I suppose whatever that was completely broke it.

DS4Updater worked fine for me, without admin mode, but I guess that depends on where DS4Windows is located. Mine isn't on drive C.

**Comment by Ryochan7** [comment]
Pretty sure that is not the change that broke it but 1.7.21 is the version when launching the updater stopped working. The following commit seems like the more likely candidate.

"Tweak update checker routine"
https://github.com/Ryochan7/DS4Windows/commit/8c12fe742cb8bec6e33f32acc2380302011073d9

**Comment by Ryochan7** [comment]
This bug is legit embarrassing. The main problem was that the dialog result was not even being grabbed. The No result was always being used. Funny enough, the WPF version of this routine does not have this problem.

The initial change was made to improve app performance. The use of Func and using Close in the try block had a major negative performance problem. Trying to carry that code over to the WPF version made the application bog down big time so a changed snippet was made.

Unfortunately, version 1.7.23 will have to be downloaded manually.

**Comment by Ryochan7** [comment]
Version 1.7.23 has been released. Please run DS4Updater.exe directly in order to update DS4Windows to the latest version. The update check bug has been fixed so hopefully a problem like this will not happen again.
