### ISSUE TITLE
Nacon wired controller

### ISSUE THREAD

**Issue by Edilio1995** [Ryochan7/DS4Windows#900]
It's possible to add compatibility to this type of controller?

VID_146B&PID_0603

[profile.txt](https://github.com/Ryochan7/DS4Windows/files/3880681/profile.txt)

**Comment by Edilio1995** [comment]
I tried to add new VidPidInfo(NACON_VID, 0x0603, "Nacon Wired Controller"), but I got an error...

**Comment by Ryochan7** [comment]
Was it a bad copy paste from other code? Maybe a comma was missing. I just tried it on my machine and the line works fine.

**Comment by mika-n** [comment]
@Edilio1995  Please try the latest DeviceDetect debug version. There is experimental support for the NaconWired gamepad. 
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

And when you say you tried the gamepad VID/PID and got an error then please be more specific. What is the error message? Did you get it at compile time or at runtime?  Anyway. Download the latest debug version because there is support for this gamepad identifier. Please test run it and provide the logfile here.

**Comment by Edilio1995** [comment]
The log file of the debug tool is "profile.txt".

**Comment by Edilio1995** [comment]
In my first comment

**Comment by mika-n** [comment]
@Edilio1995  Yes but it was run with older version of the deviceDetect debug version. The new version was updated today.

**Comment by Edilio1995** [comment]
Oh okay Sorry, I'll send you the report asap.

**Comment by Edilio1995** [comment]
[profile.txt](https://github.com/Ryochan7/DS4Windows/files/3882319/profile.txt)

**Comment by mika-n** [comment]
Hmm.... Did you connect the game bad using USB cable or bluetooth (BT)? The topic of this thread is "Nacon Wired" which implies that the gamepad supports only USB connection but for some reason DS4Win app detected the connection type being BT. Which one is it?

Do you have a link to some internet store listing this gamepad? It might tell us a bit more about his device and what it support. Does it have gyro? Touchpad? Lightbar? Rumble motors?

The first warning message is about failing MAC serial# reading. This is a problem in some DS4 compatible gamepads and can be ignored. The fallback logic is to use device HID identifier as a dummy generated MAC address and it is OK.

But then more serious problems start. Gyro calibration fails but it may be because the gamepad doesn't have gyro or the connection really was USB but DS4Win accidentally detected it being as BT (there is a different how gyro calibration goes in DS4 gamepads in USB and BT connetions).
 
Later on reading and writing to DS4 gamepad fails also so DS4Win app cannot do anything else but to stop using the gamepad.

However, there are few things you can still try. The debug version has DS4WindowsDebug.exe.config configuration file. Try to set following options there to false and zero value (compared to a default value). Quit DS4Win app while editing this config file.
  <add key="Debug_GyroCalibration"             value="false" />
  <add key="Debug_SendRumbleLightbarData"      value="false" />
  <add key="Debug_ReadTouchpadData"            value="false" />
  <add key="Debug_ReadGyroData"                value="false" />    
  <add key="Debug_ReadBatteryData"             value="false" />  
  <add key="Debug_HidDSetNumInputBuffers"      value="0" />

**Comment by Edilio1995** [comment]
The gamepad is USB connected. It's provvide with light, touchpad, Rumble but I don't remember gyro. I'll try that option you poster me

**Comment by mika-n** [comment]
Okey. No gyro and no lightbar (just some led player indication) but that should be OK. The real problem may be a confusion between USB vs BT connection types. I'll try to see what can be done about that.. Maybe adding a debug option to force DS4Windows to use certain connection type if the automatic detection doesn't work for some reason with this gamepad.

**Comment by Edilio1995** [comment]
Okay Should I still try config:
  <add key="Debug_GyroCalibration"             value="false" />
  <add key="Debug_SendRumbleLightbarData"      value="false" />
  <add key="Debug_ReadTouchpadData"            value="false" />
  <add key="Debug_ReadGyroData"                value="false" />    
  <add key="Debug_ReadBatteryData"             value="false" />  
  <add key="Debug_HidDSetNumInputBuffers"
??

**Comment by Edilio1995** [comment]
Okay Should I still edit the config file with that setting?

``  <add key="Debug_GyroCalibration"             value="false" />
  <add key="Debug_SendRumbleLightbarData"      value="false" />
  <add key="Debug_ReadTouchpadData"            value="false" />
  <add key="Debug_ReadGyroData"                value="false" />    
  <add key="Debug_ReadBatteryData"             value="false" />  
  <add key="Debug_HidDSetNumInputBuffers"

**Comment by mika-n** [comment]
Yes. The debug config file trick may help because it can be used to ignore those extra ds4 gamepad features. Anyway... I'll try to see a trick to that USB-vs-BT confusion also at some point.

**Comment by Edilio1995** [comment]
Ok the message is changed and: "findController Idx=0 Potential DS4 gamepad...

[profile.txt](https://github.com/Ryochan7/DS4Windows/files/3882391/profile.txt)

**Comment by Edilio1995** [comment]
Oh another question, It's possibile make this joypad recognize as a true DualShock 4? Cause I want to use it on PsNow.

**Comment by mika-n** [comment]
@Edilio1995  Now when the debug version recognized the gamepad and the virtual "Controler xbox 360 or Windows" gamepad is visible in a gamepad configuration screen then does it mean that the gamepad actually works? Does the "Controller xbox 360 for windows" show any activity when you press buttons and move LS/RS stick? Are those registered correctly (ie. not in wrong order and left/right stick reversed)?

If you leave Debug_GyroCalibration=FALSE but enable other debug options then does rumble work?


>Oh another question, It's possibile make this joypad recognize as a true DualShock 4? Cause I want to use it on PsNow.
Yes. Take a look at the Controller configuration option in a profile settings. There you can define the type of virtual output device (Xbox360 vs dualshock4).
https://github.com/Ryochan7/DS4Windows/wiki/Settings#controller

Based on the debug log you provided this gamepad is a bit weird because it seems to send HID data packets which other DS4 compatible gamepads send over bluetooth (inputReportLen=545). This is very strange because there are few difference in USB and BT HID data packets and a wrong packet type may confuse DS4Windows app (buttons and LS/RS axis activity not recognized correctly).

Try to download the latest DeviceDetect debug version because it supports a new DS4WindowsDebug.exe.config configuration option (Debug_ForceConnectionType). It can be used to force a connection type to be either USB or BT if autodetect logic goes wrong (like it does with your gamepad).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by Edilio1995** [comment]
Okay right now It can read it, there is only a error that make unusable the application. An index out of bound.

[profile.txt](https://github.com/Ryochan7/DS4Windows/files/3883386/profile.txt)

The application start to became crazy and move alone.

**Comment by Edilio1995** [comment]
Ok i try with the new debug application, right now It can recognize the joypad but the mouse go crazy and i can't use my mourse normally. 

[profile.txt](https://github.com/Ryochan7/DS4Windows/files/3883479/profile.txt)

**Comment by Edilio1995** [comment]
Also, If i put in the config file everything to false the mouse work correctly. I think the touchpad is working right now but mapped wrong.

**Comment by mika-n** [comment]
OK. So this confirms that this gamepad sends messages which are normally sent over via BT connections only (in official Sony DS4 gamepads and 3rd party controllers following the same logic) 

Just leave the "Debug_ForceConnectionType" to default zero value, so the incoming data is handled properly even when the connection type is accidentally identifier as BT. DS4Win app recognizes the connection type by HID message size and structure and now your gamepad sends "BT" data packets over USB cable.

> I think the touchpad is working right now but mapped wrong.

What do you mean by that? Mapped wrong? How it behaves? DS4Windows app recognizes the touchpad but you cannot use it to control a mouse cursor? 

If you use the game with Debug_ForceConnectionType=0 and Debug_SendRumbleData=False then are gamepad buttons and LS/RS sticks recognized correctly by DS4Windows app and works as expected? 

It would be possible to support this gamepad, but it is a bit difficult to debug this without the actual hardware because it seems to behave differently than standard DS4 gamepads. As one last thing I might try to make DS4Windows app to handle incoming HID data packets as those are in BT format, but all read and write operations should go like the connection is USB. At the moment this combination is not possible.

**Comment by Edilio1995** [comment]
> Just leave the "Debug_ForceConnectionType" to default zero value, so the incoming data is handled properly even when the connection type is accidentally identifier as BT. DS4Win app recognizes the connection type by HID message size and structure and now your gamepad sends "BT" data packets over USB cable.

If I leave the default value zero the joypad is not show in the home and the log file display this warning.

[profile.txt](https://github.com/Ryochan7/DS4Windows/files/3883711/profile.txt)

> What do you mean by that? Mapped wrong? How it behaves? DS4Windows app recognizes the touchpad but you cannot use it to control a mouse cursor?

When the joypad is recognize (so the Debug_ForceConnectionType is set to 2) then my mouse act strange and i can't use right click or left click so I have to unplug the joypad.

> If you use the game with Debug_ForceConnectionType=0 and Debug_SendRumbleData=False then are gamepad buttons and LS/RS sticks recognized correctly by DS4Windows app and works as expected?

No the joypad work wrong.

**Comment by mika-n** [comment]
Aah. Okey. Then the problem is that when Debug_ForceConnectionType=2 (USB) then joypad is recognized BUT the incoming HID data packets are also handled like those were in USB data format. This may cause problems that for example LS/RS axis is mapped reversed or touchpad data is mapped as LS/RS so the result goes woooooh.

I'll try to do a tweaked version where connection type can be forced as being USB, but incoming ds4 data packet format is handled through BT format logic.

**Comment by Edilio1995** [comment]
>  This may cause problems that for example LS/RS axis is mapped reversed or touchpad data is mapped as LS/RS so the result goes woooooh.

Exactly what was happening.

**Comment by Edilio1995** [comment]
> Aah. Okey. Then the problem is that when Debug_ForceConnectionType=2 (USB) then joypad is recognized BUT the incoming HID data packets are also handled like those were in USB data format. This may cause problems that for example LS/RS axis is mapped reversed or touchpad data is mapped as LS/RS so the result goes woooooh.
> 
> I'll try to do a tweaked version where connection type can be forced as being USB, but incoming ds4 data packet format is handled through BT format logic.

Ah another thing the joypad Is recognized and everything go Crazy when DebugForceConnection Is set to 1 (USB)

**Comment by mika-n** [comment]
@Edilio1995   Yet another debug version available. This one tries to automatically identify Nacon Wired Compact controller and handle it as USB device even when the input data buffer is a bit like offical DS4 gamepads use in BT connections.

Try to use following debug options in DS4WindowsDebug.exe.config file:
  <add key="Debug_SendRumbleLightbarData"  value="false" />
  <add key="Debug_ForceConnectionType"         value="0" />  
  <add key="Debug_PrintoutInputDataBuffer"     value="true" />  

The ForceConnectionType option can be "autodetect" because the new version should handle it automatically as USB. If not then you can use ForceConnectionType=1 value.

The last Debug_PrintoutInputDataBuffer=true option is just an additional debug option to dump out incoming HID data to external text file during the first 60 seconds (see %APPDATA%\DS4Windows configuration folder). Please provide the generated inputreportdata_usb.txt file because it should tell us if the HID data has few BT specific extra bytes in the beginning of the niputdata buffer even when the gamepad is connected over USB.

https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by Edilio1995** [comment]
Okay, give me some minute and I'll post the txt file.

**Comment by Edilio1995** [comment]
With that configuration the application crash after few seconds. But if i set ForceConnectionType=2 I print out the txt file.
[inputreportdata_bt.txt](https://github.com/Ryochan7/DS4Windows/files/3884106/inputreportdata_bt.txt)

**Comment by mika-n** [comment]
Hmm.... How about if you set Debug_ReadBatteryData/TouchpadData/Gyrodata options to FALSE one by one or all of them? Is the crash "fixed" after disabling all these or one of those options while using autodetect or "force usb" connection option?

And please provide the content of Logs tab page because there are few extra messages also.

**Comment by Edilio1995** [comment]
I take a screen of log before the crash
![image](https://user-images.githubusercontent.com/19685535/69501432-2c420a00-0f05-11ea-8b05-891ae7fb9d0d.png)

**Comment by Edilio1995** [comment]
Ok If I disable all, the controller is recognized and this is the log file
[profile.txt](https://github.com/Ryochan7/DS4Windows/files/3884117/profile.txt)

**Comment by Edilio1995** [comment]
Ok found it
`<add key="Debug_ReadTouchpadData"            value="true" />`
This make the application crash

**Comment by Edilio1995** [comment]
Of found it, this line make the application crash `
 <add key="Debug_ReadTouchpadData"            value="false" />
  <add key="Debug_ReadGyroData"                value="true" />    
  <add key="Debug_ReadBatteryData"             value="false" />`

**Comment by Edilio1995** [comment]
This is the output without any crash but with all setting to false and forceconnection=0
[inputreportdata_usb.txt](https://github.com/Ryochan7/DS4Windows/files/3884123/inputreportdata_usb.txt)

**Comment by mika-n** [comment]
That's weird because now there is something different than in previous profile.txt logfiles. The new file shows InputReportLen=15 when files from yesterday shows InputReportLen=545. Anyway, this explains the crash because the buffer is too small.  Hmm.... Maybe the gamepad sends at first few records using this smaller buffer but then moves over to use the normal buffer size 64 or 545. But because DS4Win app expects the buffer to be at least size of 64 bytes then it crashes when it tries to access touchpad data outside of index 15.

**Comment by Edilio1995** [comment]
And this happen with the touchpad and battery information?

**Comment by Edilio1995** [comment]
Oh wait I notice one thing, 
DEBUG: DS4Device. Nacon Wired conType=BT InputReportLen=545 OutputReportLen=78 

This is with the BT connection, with the wired is smaller

**Comment by Edilio1995** [comment]
Yesterday with BT connection: DEBUG: DS4Device. Nacon Wired Compact conType=USB InputReportLen=15 
Now with the wired connection: DEBUG: DS4Device. Nacon Wired conType=BT InputReportLen=545

**Comment by mika-n** [comment]
Yes. The same thing with battery, touchpad and gyro data. Those are beyond index 15 in standard DS4 gamepad data packets. The difference in BT and USB inputReportLen is normal and that's how DS4Win app does it. In BT it is always 545 but in USB the size is different.

**Comment by Edilio1995** [comment]
even the inportreportusb is smaller then inpotreportbt and this should be normal?

**Comment by Edilio1995** [comment]
Ok, so there's some solution to this? Change the buffer size for these controller?

**Comment by mika-n** [comment]
There is now yet-another debug version available just now. It should no longer crash. But the inputBuffer content of this gamepad is really different than in official DS4 gamepads (inputdatabuffer_usb.txt file reveals this). Looks like the gamepad is not fully standard DS4 gamepad in PC but some Nacon specific stuff.

Did the gamepad work in PC (without DS4Windows app) without any Nacon Wired Compact specific driver? Or did you have to install some Nacon drivers before the gamepad worked in PC?

**Comment by Edilio1995** [comment]
> Did the gamepad work in PC (without DS4Windows app) without any Nacon Wired Compact specific driver? Or did you have to install some Nacon drivers before the gamepad worked in PC?

No plugged and play with any games but not on psnow touchpad games, and the curios things is that this controller work well on PS4.

**Comment by Edilio1995** [comment]
Ok same situation, now the controlle work but there is the touchpad out of bound ecc. as earlier. and the command are still wrong.

**Comment by Edilio1995** [comment]
Oh another Things, this joypad when plugged was install a Xbox 360 driver

**Comment by Edilio1995** [comment]
Ah another Things in Windows hex registry the joypad record is not show. Idk of it may be a problem. But the joypad work well without any nacon of other driver installed. But in device manager this controller is display as Xbox 360 controller.

**Comment by mika-n** [comment]
Okey. So the gamepad registered as Xbox360 gamepad while connected to PC. It is a problem because DS4Windows app expects to communicate with DS4 compatible gamepads. The gamepad you have probably listens some USB messages sent by PS4 console and then it switches over to use DS4 mode. This is how BT connection works with standard DS4 gamepads, but USB connected DS4 gamepads don't require it. 

Anyway. I did one last test into the debug version. Assuming the Nacon Wired Compact controller needs a normal DS4 gyro and "send rumble/lightbar" messages in USB in order to switch over to DS4 mode then the new debug version should do this for Nacon Wired conroller also.

You can test the new version with "Debug_GyroCalibration=TRUE" and "Debug_SendRumbleLightbarData=TRUE" and "Debug_PrintoutInputDataBuffer=TRUE" options. Provide a new Logs tabpage content and inputdatabuffer_usb.txt content here.

https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

If this doesn't help then I have to give up. It is too difficult to "virtually debug". If you want to use the gamepad with PSRemotePlay in PC then maybe VDX does what you need? https://github.com/ViGEm/VDX

**Comment by Edilio1995** [comment]
When plugged it lost connection
[profile.txt](https://github.com/Ryochan7/DS4Windows/files/3886695/profile.txt)

**Comment by Edilio1995** [comment]
> If you want to use the gamepad with PSRemotePlay in PC then maybe VDX does what you need? https://github.com/ViGEm/VDX
I think this can't enable the touchpad.

**Comment by Edilio1995** [comment]
https://www.touslesdrivers.com/index.php?v_page=23&v_code=56167

I found this driver, idk if they can be useful

**Comment by mika-n** [comment]
Sorry. I have to give up. The gamepad really doesn't talk like a standard DS4 gamepad in PC, so it would require unique support. It is too difficult to do without having an actual hardware to debug. DS4Windows app does support number of other Nacon gamepads, but this Nacon Wired Compact seems to be different kind of gamepad while connected to PC.

**Comment by Edilio1995** [comment]
Don't worry, thanks anyway for the hard work :)

**Comment by Edilio1995** [comment]
Oh, one last thing I just tried to put the forcedebugconnection to 2 and I got the txt file.
[inputreportdata_bt.txt](https://github.com/Ryochan7/DS4Windows/files/3887724/inputreportdata_bt.txt)

**Comment by Edilio1995** [comment]
Oh wait, the controller with forcedebugconnection to 1 is recognized, but the setting are still broken.

**Comment by Edilio1995** [comment]
These are the usb data 
[inputreportdata_usb.txt](https://github.com/Ryochan7/DS4Windows/files/3887738/inputreportdata_usb.txt)

**Comment by Edilio1995** [comment]
```
   <add key="Debug_GyroCalibration"             value="false" />
   <add key="Debug_ReadGyroData"                value="false" />    
   <add key="Debug_ReadBatteryData"             value="false" />  
```
These three line if set true make the joypad lose connection.

**Comment by mika-n** [comment]
InputReportData_usb/bt.txt content is not in the same format as with other DS4 compatible gamepads. The format is probably xbox360 data content and I suspect that it doesn't even have touchpad data because xbox data structure doesn't know anything about it. I think the gamepad needs some initialization commands in order to switch over to DS4 mode and then incoming data would be in DS4 format. But I have no idea what kind of initialization that Nacon gamepad is waiting for.

**Comment by Edilio1995** [comment]
But for the Nacon Revolution and the other Nacon controller there aren't any of this issue?

**Comment by mika-n** [comment]
Jep. Nacon Revolution version1/ver2/ver3 and Nacon Revolution UltimatePro works just fine.  Those send standard DS4 compatible inputData HID messages in correct format (ie. not in xbox360 format). Other difference is that in PC those are DirectInput (DS4 gamepads are dinput devices) devices and not Xinput devices as Nacon Wired Compact seems to be. Or maybe one of those drivers supplied with NaconWiredCompact forces the device to be xinput device in PC (=xiput doesn't support those extra DS4 features).

**Comment by Ryusennin** [comment]
This gamepad is barely compatible with the PS4.

* PC COMPATIBLE (XINPUT ONLY).
* LED HAS NO FUNCTION WITH THE PLAYSTATION® CAMERA.
* LIGHT BAR, MOTION SENSOR AND BUILT-IN SPEAKER NOT INCLUDED.
