### ISSUE TITLE
Cant emulate Nacon Revolution Pro 2 controller as DS4 controller

### ISSUE THREAD

**Issue by JakobLund** [Ryochan7/DS4Windows#905]
When you connect a nacon revolution pro 2 controller, and changes the "Controller" setting to "DualShock 4" in "other" tab under profile, then Steam/games wont regonize it. Works fine when its on "Xbox 360"

**Comment by mika-n** [comment]
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

**Comment by JakobLund** [comment]
Thanks that works for steam. But that only seems to work for steam. I have star wars jedi: fallen order, which cant recognize the DualShock 4 config, but can with xbox 360 config

**Comment by JakobLund** [comment]
I should also add, that it works perfectly with a normal day controller

**Comment by Ryochan7** [comment]
Someone on the Discord is running into a different problem with the same game. That problem is regarding inconsistent movement when using LS but the game does recognize the controller as a DS4. I have not gotten an answer to a question that I asked yet but my guess again is that shared access is causing problems. Make sure that DS4Windows has exclusive access to the DS4 before launching Star Wars Jedi: Fallen Order.

https://github.com/Ryochan7/DS4Windows/wiki/Exclusive-Mode-(Hide-DS4-Controller-config-option)-tips-and-issues

**Comment by JakobLund** [comment]
The "Hide DS4" option did not work for me. Let me know if you have gotten an answer to your question.

**Comment by mika-n** [comment]
@JakobLund If you cannot get HideDS4Controller option to work (some app "steals" a connection to the gamepad before DS4Windows tries to open an exclusive lock on the physical gamepad then alternative way to hide the original device is to use HidGuardian tool.

See the link Ryochan7 provided in the previous post and discussions in #878 post. There is explained what AffectedDevices and WhiteListed sysreg entries does in HidGuardian tool. HidGuardianTestInstaller is an easy way to install HidG device driver tool.
https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide#hidguardian-test-installer
