### ISSUE TITLE
Bluetooth connected but not showing up 

### ISSUE THREAD

**Issue by roldantapalla** [Ryochan7/DS4Windows#910]
![1](https://user-images.githubusercontent.com/58339427/69881928-81b55700-1309-11ea-967a-5bce00fe0292.png)
Controller 1 is using Profile but it says "No controllers connected"

**Comment by mika-n** [comment]
What do you see in "Logs" tab page?
Are you using an official DS4 Sony gamepad?
Are you using a profile with "Use DInput only" option AND at the same time "Hide DS4 Controller" option? Don't use those two at the same time because it leads to a scenario you described. Try using a new default profile to verify that a profile confusion is not causing the problem.

Try running the DeviceDetect debug version to generate looooots of detail log messages from the gamepad connection (export the Logs tabpage content and attach the logfile here).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting
https://github.com/Ryochan7/DS4Windows/wiki/Settings

**Comment by roldantapalla** [comment]
[debug.txt](https://github.com/Ryochan7/DS4Windows/files/3906521/debug.txt)

**Comment by mika-n** [comment]
Looks like the gyro calibration fails in CRC32 check failure. Gyro calibration is a step where the DS4 gamepad is switched from a "PC-friendly mode" (=a bit like xbox pad without gyro/lightbar/touchpad/rumble support) to a true "DS4 mode" in BT connection. DS4 gamepad won't send (in hardware level) any data for those extra features until the gamepad is switched to a true DS4 mode. 

Now for some reason this writing of gyro calibration data (ie. DS4Windows app and PC sends certain data to the gamepad over BT communication channel) fails in your PC (Crc32 check failure).  

Later on there are warnings about incoming data packets being in wrong format. This is because DS4Windows expects to receive data packets in DS4 mode and not in PC-friendly mode. However, the debug version will eventually fallback to accept PC-friendly data packets, but those won't have gyro and touchpad information at all (only data for normal buttons and LS/RS sticks).

Does the gamepad show up in DS4Windows in this debug version and are those "standard" buttons working?

When you connect the gamepad to PC over BT without opening DS4Windows app then does the gamepad show up in JOY.CPL controlPanel applet as "Wireless Controller" and are buttons and LS/RS sticks working? Gyro and touchpad won't work because WinOS doesn't know how to switch the gamepad to DS4 mode in BT. 

If you connect the gamepad using USB cable then is gyro and touchpad working (in DS4Win profile you can map those to control mouse cursor to test those features)? This may work better because DS4 gamepad doesn't need mode switch in USB.

There has been cases that BT receiver/chipset/driver in PC is not fully compatible with DS4 gamepad especially in DS4 mode. In this mode DS4 gamepad sends a lot more data to PC than in default PC-friendly mode. Try to install all WinOS/BT chipset driver updates. Unpair the controller from PC and re-pair it after reseting the gamepad (small hole in the backside of the DS4 gamepad).

The debug version has DS4WindowsDebug.exe.config configuration file and there are couple Debug_xxx tweaks you can try. For example try increasing the Debug_HidDSetNumInputBuffers value from the default 2 to 3 or 4 or uncomment the line to use WinOS default buffer size.

You can also try to disable gyro calibration by setting Debug_GyroCalibration=false but leave Debug_SendRumbleLightbarData=true because if this writing succeeds then it should also switch the gamepad to DS4 mode.

**Comment by Ryochan7** [comment]
The controller never switches to PS4 mode so there is no way for the controller to work. The main window currently only shows a controller in the interface after the app receives the first valid packet. The WPF build will show a controller when it is first detected and then update info as packets are read.

Are you using a knock-off controller or an official Sony DS4 controller?
