### ISSUE TITLE
Dpad idling after ~10 mins

### ISSUE THREAD

**Issue by kanjiowl** [Ryochan7/DS4Windows#917]
Got myself a knock off PS4 controller from Ali Express. Weirdly, the Dpad seems to die out after 10 mins(rest of the buttons continue to work including the touchpad) -- only to be revived upon a re-plug. During that 10 minutes it works perfectly. I am connecting over USB. Wonder if there is away to debug this. 

The timing seems consistent to be a total hardware malfunction. The controller was never connected to the console. I am thinking perhaps it's a case of "partial idling".  Any ideas?

Sorry, I realize that it's not strictly an issue with DS4Windows.

**Comment by mika-n** [comment]
When you use the gamepad without DS4Windows then is DPad dying the same way?

The debug version has a "Debug_PrintoutInputBuffer" option (DS4WindowsDebug.exe.config file) which generates a text file output from a received input buffers. It could be used to verify if DPAD fields are zero after certain time. The problem is that the debug version dumps out the debug output during the first minute  or two after gamepad connection. If you have a VisualStudio then you could modify the debug version to dump out that data for a longer period or use some hotkey to enable/disable the debug output on the fly.

(A word of warning. At the moment the debug version is based on newer libraries than the official DS4Windows release, so you may want to copy it to different folder than the official version).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems
https://github.com/mika-n/DS4Windows/tree/debugVer

**Comment by 1Percy1** [comment]
> Got myself a knock off PS4 controller from Ali Express. Weirdly, the Dpad seems to die out after 10 mins(rest of the buttons continue to work including the touchpad) -- only to be revived upon a re-plug. During that 10 minutes it works perfectly. I am connecting over USB. Wonder if there is away to debug this.
> 
> The timing seems consistent to be a total hardware malfunction. The controller was never connected to the console. I am thinking perhaps it's a case of "partial idling". Any ideas?
> 
> Sorry, I realize that it's not strictly an issue with DS4Windows.

You found some way to fix this?
