### ISSUE TITLE
Constant JoyStick Drift in Destiny 2

### ISSUE THREAD

**Issue by AgentMovar** [Ryochan7/DS4Windows#920]
I just installed this version of DS4Windows in hopes that it would fix the latency issue I get with the regular DS4Windows. Well it does seem to resolve that issue, but now when idling in the game the left joystick will constantly drift down and the right will drift left. Don't know if anyone else is experiencing these issue and would like some help. Thank.s

**Comment by Ryochan7** [comment]
Sounds like it is very likely a deadzone problem. Can you share the profile you are using? Also, please check the values from the output controller in HTML5 Gamepad Tester.

https://html5gamepad.com/

**Comment by AgentMovar** [comment]
I am using the default profile from the program. I have included screen shots of whats going on when I go to HTML5 Gamepad Tester. It seems when I am using this DS4 that the joysticks stay where they are moved to and won't reset back to there default positioning after being touched.
![regular](https://user-images.githubusercontent.com/58714480/70494373-11f95600-1ad9-11ea-8108-85ce2dfd842d.jpg)
![fork](https://user-images.githubusercontent.com/58714480/70494376-13c31980-1ad9-11ea-8124-de13ebeb392a.jpg)

**Comment by AgentMovar** [comment]
The top photo is when using regular DS4Windows.

**Comment by Ryochan7** [comment]
Okay. I see what is happening. Luckily both input values are the same. The difference is the application of the anti-dead zone. You have no dead zone set for either stick in that profile. Jays2Kings had no concept of an anti-dead zone setting to combat in-game dead zone settings. This version defaults to a 0.25 (25%) anti-dead zone as that is about the standard dead zone value that most XInput games use by default. That offset created by the anti-dead zone is why the output coordinate is further from the center initially. Either set a dead zone for LS and RS or remove the anti-dead zones in the profile. I would recommend adding around a 0.08-0.10 dead zone for the sticks.

**Comment by AgentMovar** [comment]
That fixed it! Thank you so much. I do have another question then though. Why isn’t the default profile already set up with those values?

**Comment by Ryochan7** [comment]
Creating a new profile should use 0.08 for dead zone and 0.20 for anti-dead zone for each stick by default; just found a problem between the GUI and main profile code that does not exist in the WPF code base. The problem is when carrying over old profiles from Jays2Kings DS4Windows version 1.4.52. The same dead zone variable is used but the default anti-dead zone will end up being used as that variable does not already exist in a profile.

**Comment by Stehny** [comment]
I tried to use your first link @Ryochan7 but HTML5 Gamepad Tester doesn't seem to work, im using a Sony DS4 Controller, ive tried usb and wireless, i am connected to bluetooth.

**Comment by mika-n** [comment]
@Stehny  What version of DS4Windows you are using? 
When you say that "html5 gamepad" web testapp doesn't work then do you mean that the gamepad is not recognized by the web app or it is recognized, but RS/LS stick axies don't work there? Please note that the html5gamepad web testapp recognizes a gamepad only after you have pressed some gamepad button key at least once.

Check the Controller Readings tab page in DS4Windows profile editor screen because it is an easy way to see if gyro or LS/RS stick needs a bigger deadzone (or if you can make the existing deadzone smaller).

**Comment by Stehny** [comment]
> @Stehny What version of DS4Windows you are using?
> When you say that "html5 gamepad" web testapp doesn't work then do you mean that the gamepad is not recognized by the web app or it is recognized, but RS/LS stick axies don't work there? Please note that the html5gamepad web testapp recognizes a gamepad only after you have pressed some gamepad button key at least once.
> 
> Check the Controller Readings tab page in DS4Windows profile editor screen because it is an easy way to see if gyro or LS/RS stick needs a bigger deadzone (or if you can make the existing deadzone smaller).

I'll try html5 again, yeah the controller wasnt being recognised at all. Also, in ds4 windows i had to delete the Destiny 2 profile (its not like i had edited much anyway), i created that profile on 1.4.52 i believe. So now ds4 windows is working :).
