### ISSUE TITLE
[Feature Request] Advanced Key Combination

### ISSUE THREAD

**Issue by http403** [Ryochan7/DS4Windows#923]
Hi,

I'm trying to config to use the controller with some programs that doesn't support it natively. The game requires using key combinations from simple like `Shift + X`, which can be done by marco, to complicated like `Right mouse click + Mouse movement`, which can not be done by marco.

I hope it can be implemented some day.

Thank you.

**Comment by Ryochan7** [comment]
Having more robust mapping support would be nice but that might not happen in DS4Windows. The mapping backend code is a mess for the most part. My main focus with DS4Windows has been just trying to improve the general gamepad emulation routine.

The hope is to make a future successor to DS4Windows with more robust mapping features and additional device support. Some work was done but I have not done any work on it in a few months. The WPF build of DS4Windows has been a higher priority. It was useful to learn that software stack anyway since any future successor would be built with the same tools.

https://github.com/Ryochan7/mappingtest

**Comment by Ryochan7** [comment]
I thought about this again with the recent mapping and stick control changes. I don't think I want to deal with refactoring the profile schema to attempt to make something like that work. Besides the bindings themselves, there are other flags in place that assume the type for the output action for the binding. It might not be worth the effort to attempt to refactor everything to use List objects and use an intermediate data structure for keeping things in check.

I am going to close this issue for now. Maybe I would consider looking into this again but I would rather keep trying to work on a newer mapper. A lot of these considerations have been made in my little experiments.

https://gitlab.com/ryochan7/switchpromappertest/-/tree/action_ideas
