### ISSUE TITLE
Windows 10 won't start screen saver or go to sleep after ds4windows runs

### ISSUE THREAD

**Issue by an303042** [Ryochan7/DS4Windows#927]
Even if I close ds4windows screensaver won't start. I have to reboot and not start ds4win in order for things to work properly...

**Comment by mika-n** [comment]
Any difference if you use wireless BT or USB connection with a gamepad?
Any difference if you launch DS4Windows app, but don't connect any gamepads? 
If the issue happens only after you have connected a gamepad at least once per boot then are you using a profile where DS4 gamepad keys or touchpad or gyro are mapped as mouse or keyboard keys?

**Comment by an303042** [comment]
Sorry for disappearing. I think I was wrong in my initial description - It seems that now the screensaver won't turn on while the DS4 controller is plugged in, regardless of whether ds4windows has run or not. Thing is, I don't remember it behaving this way before running ds4windows and installing the drivers.
Anyway, I don't really have much time to look into this, and I'm just keeping the controller unplugged for now to solve the issue, so I guess we can close this..

**Comment by mika-n** [comment]
Jep. Looks like this is not a DS4Windows issue, but WinOS issue. "Mr and Mrs Google" told that Windows 10 has a bug in its HID drivers where a connected gamepad or joystick may prevent a system to enter idle state. Make sure you have the latest Win10 updates installed because some people reported that an update fixed the issue in some cases.
