### ISSUE TITLE
Steam doesn't detect controller as Dualshock4 unless DS4Windows is closed

### ISSUE THREAD

**Issue by khanghugo** [Ryochan7/DS4Windows#937]
Hi,

I have "Hide DS4 Controller" option on with DS4Windows running as task when starting up while the controller is connected through cable and marked as DS4 in its profile. However, I cannot play with my DS4 as a DS4. So I stop the program through the "Stop" button and Steam still does not detect it. As for the controller, no light is showing up. When I re-plug the cable, it is showing the breathing orange light (I assume it means charging) and no progress is made. Then, I close DS4Windows (I mean terminate it), the controller works and is detected as a DS4 with my custom lights on.
When I check the device manager, the HID does disappear normally. 

I don't know what cause this but it may be considered as a bug, I think.

**Comment by Ryusennin** [comment]
You first need to completely disable gamepad support (both Xbox and PS4) in Steam, otherwise it will conflict with DS4W.

It also appears that Valve is actively blacklisting DS4W, so you might want to try renaming the DS4Windows.exe app into something else.

If the built-in DS4W exclusive mode doesn't work on your system, you'll have to disable "Hide DS4 Controller" and install HidGuardian instead.

https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide

PS: the "DualShock 4" mode in DS4W only works for genuine DS4 v2 controllers. It's only purpose is to display DS4 icons instead of X360 ones in a few compatible games.

**Comment by Ryochan7** [comment]
Valve has confirmed before that the behavior is actually a feature in the Steam client. Steam will implictly disable PlayStation Configuration Support if it detects that either DS4Windows or InputMapper is running. You would have to rename the DS4Windows.exe executable in order to try to use both mappers at the same time.

**Comment by mika-n** [comment]
This Steam client problem/bug feature/stupid functionality is explained in Troubleshooting wiki page:
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#steam-doesnt-see-the-virtual-output-controller-if-a-profile-uses-the-dualshock4-output-type-steam-sees-the-ds4-controller-only-if-ds4windows-uses-xbox360-output-controller-type

**Comment by khanghugo** [comment]
Damn, this is really questionable from Valve. I guess they really want people to use their big picture web browser.
