### ISSUE TITLE
[issue] Bluetooth connection problem

### ISSUE THREAD

**Issue by tmnt3** [Ryochan7/DS4Windows#944]
Im using a new bt 4.0 adapter and it won't connect my controller like before with a 2.0 bt adapter
![ps4](https://user-images.githubusercontent.com/59228224/71446673-3df61780-2726-11ea-9865-71e73f8cadf3.png) Bluetooth diveces tab shows sometimes this. I'm able to find a device, but it won't connect at all. Sometimes it connects, but it's not asking for any pair codes, and it works for a few seconds.
![ps42](https://user-images.githubusercontent.com/59228224/71446714-a3e29f00-2726-11ea-9a83-f36cb8948c3a.png)
Is this an issue with the bt adapter? Can I do anything about this?
The software for this bt is "CSR Harmony Wireless Software Stack Version 2.1.63.0
Copyright Cambridge Silicon Radio Limited"

**Comment by Ryochan7** [comment]
From the README

> CSR BT stack is confirmed to not work with the DS4 even though some CSR adapters work fine using Microsoft BT stack. Toshiba's adapters currently do not work.

Also, Windows 7 will not be supported by me starting at the beginning of 2020. That is due to Microsoft officially ending support and updates to Windows 7. The version of the Microsoft BT Stack included with Windows 7 is not that good anyway. I preferred the Toshiba BT Stack back then but that has not been an option for a while.
