### ISSUE TITLE
2.0 Missing Taskbar Menu Options

### ISSUE THREAD

**Issue by shinra358** [Ryochan7/DS4Windows#947]
Taskbar menu options of Start, Stop, and Open Location is missing

**Comment by Ryochan7** [comment]
This must have been the case where I did not use those features so they initially got ignored. Never got back around to implementing those features though.

**Comment by shinra358** [comment]
Ok, those are still much needed. Especially when troubleshooting.

**Comment by shinra358** [comment]
2.0.1 - Pressing [STOP] anywhere makes the open program folder and disconnect menu options disappear from the taskbar menu

**Comment by Ryochan7** [comment]
I had a refactor made before my compy took a dive again. The issue is that some menu items are not re-created when no controllers are connected.

Also, the Disconnect item is meant to not be shown when no controllers are connected. Maybe it can just get disabled instead.

Profile switching via the tray menu was working. I will check again when I get VS redownloaded.

**Comment by shinra358** [comment]
for the disconnect item thing, it doesn't come back when controllers are reconnected unless the whole program is restarted.

[also, lifehack] have windows installed on an ssd. Have all your programs installed on separate hdds. Thanks me later :P

**Comment by shinra358** [comment]
thx
