### ISSUE TITLE
Defining button(s) for multiple roles (tap, hold for x seconds, etc.)

### ISSUE THREAD

**Issue by TristanYoung** [Ryochan7/DS4Windows#95]
I was hoping to define the PS button to perform two roles:

1.  Tap PS - initiate macro that reveals/dismisses Gforce Experience (ALT-Z)
2.  Long-press PS (1 second) - turn off controller

I can define both actions, however when I long-press the PS button, it thinks I'm tapping and runs the macro, and then turns off the controller.  It would be nice if there was a way to have the first action ignored if the button press isn't specifically a tap.

This also becomes an issue if you want to define different length presses for different actions.

While trying to work around this, I discovered that it's impossible to define a macro to run after the associated button(s) are held for a user-definable amount of time.  That means I can't define one button to produce different results (mixing actions, macros, running a program, etc.).  Seems this functionality is reserved for pre-defined actions only (eg: turn off controller).

**Comment by Ryochan7** [comment]
It looks like the only way that you could do this currently is to use a combination of a Multi-Action Button and Disconnect from Bluetooth special actions. You can bind only the Tap Macro to Alt-Z which should fire if you tap a button; I cannot remember the time cutoff for a tap that is set in the program. I am not sure how much work would have to be done to add conditions to other actions to only fire upon a button release instead of a hold.
