### ISSUE TITLE
DS4Windows has stopped working

### ISSUE THREAD

**Issue by mindah0** [Ryochan7/DS4Windows#954]
hi guys I have an issue when I lunch DS4windows and I click on Instal vigembus, DS4Windows stops working with a windows message error "DS4Windows has stopped working" 
help please.

**Comment by mika-n** [comment]
Try downloading and installing the latest VigemBus driver directly without letting DS4Windows app to do it when the app is launched for the first time. And check other pre-requisites (.NET Framework/VisualC++).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

**Comment by mindah0** [comment]
thanks half fixed ahahah,  I don't have the error now, but it doesn't detect my controller, any idea why ?

**Comment by mindah0** [comment]
fixed I just changed to port of the USB thanks !

**Comment by Ryochan7** [comment]
You might want to double check and make sure the one HID device was not unintentionally disabled. Changing USB ports makes Windows see the connected controller as a new device so that would be one reason why the controller works in one USB port but not another.

https://github.com/Ryochan7/DS4Windows/blob/jay/README.md#device-detection-issue
