### ISSUE TITLE
ViGEmBus

### ISSUE THREAD

**Issue by Okami23** [Ryochan7/DS4Windows#955]
I've got a @play ps4 controller (https://static.raru.co.za/cover/2019/04/17/7302248-2-l.jpg?v=1555492014) and ive tried to make it work on pc but sadly the DS4Windows doesnt recon the controller. So i was given a new link with a updated version but now i cant install ViGEmBus. 
My system is x64 and so ive downloaded the x64 but when installing GiGEmBus says "This app cant run on your pc"and that i need to find a version for my pc.

**Comment by mika-n** [comment]
See the following troubleshooting page and "DeviceDetect" debug version of DS4Windows app. Try running the debug version and provide the content of Logs tab page of DS4Windows app here (export the Logs content to txt file). 
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

Anyway, you need to successfully install VigemBus driver before DS4Windows works. If you tried the old JayKings version using ScpVBus driver then uninstall all traces of ancient ScpVBus driver before installing the newer VigemBus driver.

Make sure your PC meets all requirements (.NET Framework, VisualC++ runtime libaries. the latest version of ViGem installer).
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list

**Comment by Section8TR** [comment]
Try this. Im solved with setup.
https://github.com/ViGEm/ViGEmBus/releases/download/v1.16.112/ViGEmBus_Setup_1.16.115.exe

**Comment by Okami23** [comment]
> Try this. Im solved with setup.
> https://github.com/ViGEm/ViGEmBus/releases/download/v1.16.112/ViGEmBus_Setup_1.16.115.exe

Thanks so much! It worked ! i can finally use the controller! it detected thank you! Thank You both to try and help! Happy new year!

**Comment by Ryochan7** [comment]
Installing ViGEmBus did not work from the Welcome Dialog in DS4Windows version 2.0. A later refactor to the WPF code made it so an object was not initialized by that point. DS4Windows would crash when it attempted to start downloading the installer executable. The process had worked before I added the command line parser in the code.

I have made a fix so that the needed HttpClient instance is created before the Welcome Dialog in that execution path. Plenty of fixes have already been added to the latest DS4Windows code. An updated version will be released within a day.

**Comment by GundamApex** [comment]
I posted this comment on Jays, but I'll post here too just in case it helps any.

This is my first time installing this program, so I've never had any version prior to 2.0. I'm having the same problem. I know you're working on it, as you just said above, but I wanted to ask is it a bad idea to install this while Steam is running? Just wondering if this program will clash with Steam since Steam also recognizes the DS4 controller and has drivers for it?

I'm also on Windows 10 64 bit and I chose the install to app data option and (Edit: the portable option too lol).

**Comment by mika-n** [comment]
No need to stop Steam client while installing DS4Windows app or VigemBus driver tool. Of course it doesn't hurt anything to stop all unnecessary apps in case some of the pre-requirements need to be updated (.NET Framework or VC++ runtime libraries because those apps may use those 3rd party libraries and lock files. Anyway, in that case the installer should ask you to reboot PC to finalize the installation).

See following web pages for more info about pre-requirements and a link list to directly downloading .NET framework, VC++ and VigEm driver installer files (for example the bug in the first release of DS4Windows 2.0 version fails to install Vigem driver, but you can download the vigem installer package and run it yourself. The end result will be the same).
https://github.com/Ryochan7/DS4Windows#requirements
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#link-list
