### ISSUE TITLE
Change to player two?

### ISSUE THREAD

**Issue by Ub3rZ4cH** [Ryochan7/DS4Windows#958]
How do I make the PS4 controller become PL2, I already have a controller connected via bluetooth as player 1, the PS4 controller I am using wired, but it is acting like its PL1. When I launch the game both controllers control PL1, so I cant click join as PL2.

I have clicked "hide ds4 controller".

The controllers appear like so in gamepad settings;

Bluetooth XINPUT compatible input device (8bitdo controller)
Controller (xbox 360 for windows) (PS4 controller)

So windows knows they are seperate how do I get the game to detect them as two different controllers?

**Comment by Ryochan7** [comment]
That behavior sounds like it is dependent on the game rather than anything with the emulation layer. What game are you trying to play?

Anyway, there is no way to specify a slot for the output Xbox 360 controller. XInput assigns controller slots as devices are detected. The only possible way to mimic controller slot selection would be to plug in multiple virtual Xbox 360 controllers and then assign the input DS4 controller to a specific virtual controller. An output controller manager will hopefully be added to DS4Windows in the future.

**Comment by Ub3rZ4cH** [comment]
The game is Halo: The masterchief collection on PC but through the xbox beta app. 
I have also tried the PS4 controller on bluetooth and its odd windows shows both controllers as seperate, but the game thinks they are the same. Also tried another controller (a knock off switch pro controller) which again detects fine in windows but not in the game.

> The only possible way to mimic controller slot selection would be to plug in multiple virtual Xbox 360 controllers and then assign the input DS4 controller to a specific virtual controller.

I have multiple controllers so should I try to plug them all in at once, then how to I asign the ps4 controller to a specific virtual controller?

**Comment by Ryochan7** [comment]
I have played through Halo: Reach via XGP. The game has some weird behavior that even makes mapping options a bit limiting. The biggest issue is that gamepad and KB+M controls cannot be used together at the same time. Gamepad actions will stop registering if mouse movement is detected.

This issue would affect Steam Controller users more than people running DS4Windows but I usually like mapping mouse to RS and XInput controls to the rest of the DS4. Ended up playing the game with Mouse Joystick mapped to the Gyro rather than using RS as an analog stick for most of the game; vehicle sections pretty much require using RS as the camera speed in vehicles is so slow for camera sweeps.

Unfortunately, I do not have the game installed right now as I had to reinstall Windows 10 twice recently due to hardware problems. I would test it out otherwise just out of curiosity. I cannot justify re-downloading the full game again just to test that quirk until the beginning of January (bandwidth caps).

There is no way to assign controller slot now.

**Comment by fefo-dev** [comment]
"There is no way to assign controller slots now." @Ryochan7 is this still true? I was reading issues before opening a new one and found this to be the closest. If so, no workarounds either?

It's a pain on stuff like emulators that tie the input to the controller number and there's no easy way to cycle then outside of disconnecting everything and reconnecting in order.

Thanks.
