### ISSUE TITLE
GUI issue and crashes

### ISSUE THREAD

**Issue by reyaz006** [Ryochan7/DS4Windows#959]
Issue:
Selected profile drop-down list under Controllers tab has a small fixed width, and it's not centered. Probably should expand along with a column.

Crash:
From Controllers tab, press Edit near current profile. Profile tab will open. Leave it like that.
Return to Controllers tab, press Edit again. Profile tab will contain 2 sections. This can go on and on. If you Cancel one, it will not crash. If you go there and Cancel it second time, DS4W will crash.

Crash:
Under Settings, quickly uncheck and check Hide DS4 Controller option. At some point DS4W may crash in Nefarius.ViGEm.Client module. At any point, doing this repeatedly seem to crash DS4W every time.

**Comment by Ryochan7** [comment]
The first crash is likely due to a null value. The Profile Editor is meant to be closed before a new profile is created or before opening an existing profile. People don't use the app the same way I do as this is the second post about that behavior.

Not sure about the second crash. That checkbox should disable while stopping and re-enable after ViGEmBus is closed. There should be no issue with running conflicting routines at the same time. I will double check and make sure that is the case. Either way, that crash is minor as nobody should encounter that under normal circumstances.

**Comment by Ryochan7** [comment]
That checkbox does not get disabled. Need to fix that.

**Comment by reyaz006** [comment]
>Not sure about the second crash. That checkbox should disable while stopping and re-enable after ViGEmBus is closed. There should be no issue with running conflicting routines at the same time. I will double check and make sure that is the case. Either way, that crash is minor as nobody should encounter that under normal circumstances.

Yes, it's minor and happening only when clicking the checkbox quickly and repeatedly. Also only when DS4 is connected I think.

>That checkbox does not get disabled.

No such problem for me. Btw, I have ViGEmBus 1.16.112.0.

**Comment by Ryochan7** [comment]
There was no code to disable the checkbox. Made a minor tweak to make sure the checkbox is disabled while changing the status of the background service. All of the listed concerns have been fixed in the current code. I plan to get a new release out within a day with some fixes that have been added in recent commits. Many commits have been added today.
