### ISSUE TITLE
[Feature Request] Separate Analog Stick Sensitivity

### ISSUE THREAD

**Issue by TheJackTrades** [Ryochan7/DS4Windows#96]
Splatoon 1 and 2 does an interesting thing where you aim normally with a stick but also are able to fine tune your aiming with gyro controls and it really improves aim precision once you learn that method.

I wanted to recreate that on a DualShock 4 to see if it would also work.
DS4W does let me additionally bind an analog stick to the gyro but for that method to work you'd have to lower the sensitivity on the emulated analog stick that's controlled by the gyro but unfortunately DS4W doesn't have the functionality to set separate analog stick sensitivity to different input methods.

It would be really neat if it was possible to do that.

**Comment by Ryochan7** [comment]
Version 1.4.86 and later should allow changing various settings for sixaxis controls so you can have greater control over the sensitivity of the output stick values. Using tilt controls for this kind of functionality might not be the best idea though. You might want to give an experimental fork of DS4Windows a try. An attempt is being made to hack Cemu so that games like Splatoon can be played with gyro controls. There are no plans to add the same functionality into this version of DS4Windows currently.

https://sshnuke.net/cemuhook/padudpserver.html
