### ISSUE TITLE
[ENHANCEMENT] More reliable way of automatically disabling emulation

### ISSUE THREAD

**Issue by Nucleoprotein** [Ryochan7/DS4Windows#965]
Hello,

As more games gets native DS4 support i think DS4Windows needs more reliable way of disabling in auto-profiles.
For my current tests:

- Detroit Become Human - works fine (game has full DS4 support but only in USB mode with PS4 buttons on screen, touchpad and gyro also supported)
- MK11 - game detection seems to crash game after splash screen, may be related to DRM as detection is using OpenProcess call which can be prohibited by DRMs and anticheat software (game have full support in both modes with PS4 buttons on screen)
- Tekken 7 - not reliable, as splash screen is different exe file and DS4Windows switches on and off and on causing game to not detect gamepad at all

I will test Spyro later (as it seems it has DS4 support too).

@Ryochan7 
Thanks for this great software!

**Comment by mika-n** [comment]
Maybe setting up a special autoprofile rules to choose a profile with "Use DInput only" checkbox enabled? However, this DInputOnly works best only over USB connection because BT connection has certain WinOS level limitations when the gamepad is switched from PC-friendly mode to true DS4 gamepad mode..

Or the app uses some other adhoc processes and this causes unnecessary "profile switching" in DS4Windows app then you can setup a special "catch all" rule to indicate DS4Windows app NOT to revert back to default profile when an "unknown" process is detected. 

Or autoprofile rule using "Turn off DS4Windows temporarly" option.

https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules


Whatever you want to do then please remember that BT connection has WinOS level limitations if DS4 gamepad is used without a special Sony Wireless Adapter BT dongle. USB connection doesn't have this "dead BT hid device" problem. . So, it is not possible to do pure software level "disable / enable" DS4 gamepad on the fly while the gamepad is connected over BT. It is possible only while connected using USB cable or using SonyWirelessAdapter gadget. And even then if you use exclusive mode (=Hide DS4 Controller option in DS4Windows app) or HidGuardian tool to hide the original physical controller then it makes the "on the fly" enable/disable a bit difficult. You still may have to disconnect and re-connect the gamepad in order to revert it back to original state in WinOS device list.

Following post explains a bit more about this "dead BT hid device after DS4 mode switch over" problem
https://github.com/Ryochan7/DS4Windows/issues/952#issuecomment-569124621

**Comment by Nucleoprotein** [comment]
This does not change the problem with detection itself, like MK11 problem.
Also i tried to use DS4 profile and  "Use DInput only" for Tekken and nope, gamepad is dead until gamepad restart, seems it's the problem you described, i try later using USB cable.

**Comment by mika-n** [comment]
closed as "the dead BT DS4 gamepad device handle is a WinOS issue unless one is using Sony's own BT wireless adapter". Nothing DS4Windows app can do about it. USB connection doesn't suffer from the same "dead device after switching the gamepad from PC-friendly mode to native DS4 mode".
