### ISSUE TITLE
Auto profile help or issue?

### ISSUE THREAD

**Issue by Tiberiusmoon** [Ryochan7/DS4Windows#967]
So im just grasping the auto profile functionality following this: https://github.com/Ryochan7/DS4Windows/wiki/Profile-selection-using-auto-profile-rules

I do not know where to put the "do not change profile" rule or what to type in as the rule specifically.
Im not sure about other users but the whole revert to none or default profile when explorer.exe is detected by default is a wierd approach, simply changing the profile when the key program is detected and stay there unless another key program is detected would be much simpler than setting a rule to not automatically switch.
If a user wanted the profile to switch when closing or switching like it currently does then explorer.exe can be chosen.
A current profile check in the code could reduce DS4 app usage if not already applied.

Thoughts?

**Comment by mika-n** [comment]
Agree. The auto-profile logic has a loooong history and the way it works is a bit mess. Small bits here and there has been added to that functionality over the years by several developers, so the end result is what it is. Well, it used to be a bigger mess than it is nowadays, but for example that "revert automagically back to a default profile when an unknown app is detected" logic comes from the original implementation. 

It would be better to have there "auto-profile on unknown process = Revert back to default profile / Keep existing profile" option. By setting this one option would make it possible to support the existing old logic and the "keep existing profile" logic without doing the "catch all choose none" profile trick as explained the Wiki page.

Anyway. As it is now you can do this by adding a following kind of auto-profile entry as the very last rule:
- Process name = ^C:    (ie. wildchar match to all processes below C: path. If you have D disk also then do the same rule for ^D: process names also)
- Controller1..4 = (none)

If you need to change the order of existing rules then unfortunately the current GUI doesn't let you do it. You have to open the autoprofile.xml configuration file in a text editor and modity the order there (as explained in the Wiki doc page).

Anyway. I think I will look into this "auto-profile on unknown process" option and implement it in hear future because it has been requested couple times before. And I would use that feature also instead of doing the "catch all" dummy rule trick.

**Comment by mika-n** [comment]
The current version of DS4Windows has an option in AutoProfile screen to optionally enable "revert back to default profile on unknown process" type of functionality. There is no longer need to add the "catch all - do nothing" type of action as described above.
