### ISSUE TITLE
L2 and R2 sensitivity change? 

### ISSUE THREAD

**Issue by viottiz** [Ryochan7/DS4Windows#968]
Hello, first off sorry to all if i am not putting this comment in the right spot as i am new to GitHub. 

I had been previously using DS$4 windows (before the 2.0 update) with a controller profile config named "testing". This config had my L2 and R2 sensitivity set to 10.00, meaning (with combination of the other settings) that i could breathe on my triggers (not really maybe a push with hardly any force at all) and it would register completely (as in L2/R2 symbol instantly surpassing the slider that indicates show much youve actually pushed down). Upon updating to the new 2.0 version i decided to delete that profile (testing) and start all over (stemmed from the rainbow lightbar setting not working properly) and i ended up losing the 10.00 sensitivity. Now when I try to change my sensitivity, it caps at 1.0 and the L2/R2 symbols (the ones that indicates what the game is receiving) is stuck to the slider (that shows how much youve actually pushed down the triggers) despite whatever settings i try changing. I just want to see if theres any way i can go back to that 10.00 sensitivity, if theres any way i can still make the sensitivity for the triggers as sensitive as they were (or at all considering i cant get it to budge anymore) or at least understand whats going on. thank you for your time reading this. thanks for your continuation of this amazing program and i hope you read this soon, thanks.

**Comment by mika-n** [comment]
#962  post probably talks about the same issue. V2.0 had a bug in R2/L2 sensitivity settings in a profile editor. The linked ticket shows more about the bug and fix. The next release probably has that fix. Meanwhile you can try to modify the xml profile file with "Powered by Noteapd" hightec tehnology and set the sensitivity value as you wish (but you will loose it as soon you try to edit the profile in V2.0 version until the fix is released).

**Comment by Ryochan7** [comment]
This issue has been fixed in the code. It was mainly just not editing values after performing a copy paste. I don't use the Sensitivity option so it got ignored. I tend to use the more granular settings to define the sensitivity of the sticks and triggers.

I am still working on tweaks. A new release should be out sometime today.

**Comment by viottiz** [comment]
You guys are the best. Gave you guys 4 hours before I decided to check again and see where the progress in my comment being seen is and there’s already a fix coming out soon (maybe next one). Incredible and I thought the comments were gonna be blank, thanks so much
