### ISSUE TITLE
Hide DS4 not working in 1.4.87

### ISSUE THREAD

**Issue by IceyFlames** [Ryochan7/DS4Windows#97]
Updated to 1.4.87 today from 1.4.86 and exclusive mode has stopped working regardless of Steam, etc running or not. I've regressed back to 1.4.86 and everything is working properly again.

**Comment by Ryochan7** [comment]
Nothing has changed with the device detection routine so the behavior should be the same between the two versions. Maybe the .NET Runtime is behaving differently between the two versions. Exclusive mode works fine on my system still.

**Comment by SeemsFishy** [comment]
Same problem. Exclusive mode does not work on 1.4.87 for me. Works just fine on 1.4.85. What kind of additional information do you need?

**Comment by Ryochan7** [comment]
With the most recent Windows update, I am having occasional problems with Exclusive Mode using version 1.4.86 as well as the current version. This is happening when no gaming related applications are running at the time. I will try to tweak some routines to see if anything can help.

**Comment by Ryochan7** [comment]
Can anyone give this test version a try? I seem to have better luck with the couple of minor changes that have been made. This build has not been tested thoroughly though.

https://drive.google.com/open?id=0B6yGHDx0CFzDYXhzWjVySkVPUjA

**Comment by SeemsFishy** [comment]
No luck with that version, exclusive mode still not working. Windows 10 Pro Build 1703 (15063.483)

**Comment by Ryochan7** [comment]
A couple of more changes. So far exclusive mode has not failed once even while Steam has been open.

https://drive.google.com/open?id=0B6yGHDx0CFzDYXEtd2RkLWhVS2s

**Comment by SeemsFishy** [comment]
Still does not work on my end. No matter Steam is launched or not.

**Comment by SiTWulf** [comment]
Yes... same problem for me today.
Same windows version v1703 (15063.483).

**Comment by Ryochan7** [comment]
I am currently running build 15063.483. For some reason, exclusive mode seems to work better on my system with all versions today than it has in the past few days. Not sure why that is the case.

Also, people on the InputMapper forum have mentioned that the newest Nvidia GeForce Experience version causes Exclusive Mode to consistently fail for InputMapper. I don't have GeForce Experience installed on my system so that problem does not affect me.

**Comment by SiTWulf** [comment]
Yeah!!!... this is the trick!.
I remember... i updated GeForce Experience today at windows start.
Is a problem with GFE....

**Comment by SeemsFishy** [comment]
Disabling Nvidia Share not solving the problem on my system =( May be I will try to uninstall geforce expirience and make some tests later

**Comment by SiTWulf** [comment]
Ok, i find a easy trick for use it at the same time Nvidia Share and DS4 Hide.

Simply need to make a Taskkill /im "Nvidia Share.exe" /f when the two process are closed conect the gamepad, the Hide DS4 works, not problem, Nvidia Share are always auto open after a few secs again.

Maybe @Ryochan7 can implement this into "test version" for test if works.

**Comment by Taskkill** [comment]
@SiTWulf 
I  must say, I feel little bit like some genie summoned unintentionally 😆 sadly I cannot give you 3 wishes neither resolve your issue. Anyways I like the project, be well guys.

**Comment by pedrovay2003** [comment]
Holy crap, I was going out of my mind trying to figure out the problem. Thanks for the input! It looks like it was discovered over on the InputMapper forums, too:

https://inputmapper.com/forum/inputmapper-1-5-support/692-exclusive-mode-with-latest-nvidia-driver

**Comment by Ryochan7** [comment]
Out of curiosity, I tried out HidGuardian since that would probably be the best solution to this problem in the future.

HidGuardian does its main job and keeps specified devices hidden from all processes that are not whitelisted. The main problem is that it looks like some flags are not being used when opening the handle to the HID device in HidGuardian which results in noticeable input lag. I am assuming that the HID device is not being opened the same way in HidGuardian as what is done in DS4Windows currently. It does not seem like HidGuardian is ready for prime time yet.

**Comment by pedrovay2003** [comment]
I couldn't even get my controller to work after I installed HidGuardian, so I'm glad we figured out that it was the Nvidia stuff causing issues.

**Comment by Ryochan7** [comment]
I had to use WhiteKnight once HidGuardian and HidCerberus were installed in order to whitelist DS4Windows temporarily. A controller can be plugged in after that. Once DS4Windows has the HID device handle, WhiteKnight can be closed.

https://autohotkey.com/boards/viewtopic.php?t=34890
