### ISSUE TITLE
(v2.0.1) lightbar colours sometimes don't stick

### ISSUE THREAD

**Issue by nr1995** [Ryochan7/DS4Windows#979]
I'm not able to reproduce this,
because it seems to be working all fine now (don't know what I changed)
but before when I clicked on the lightbar on the clickable DualShock4 image,
it would take me to the very basic little colour chooser pop-up,
and within there it would change the colour just fine,
but after clicking the little “X” in the top-right corner,
it would change to some other colour.
Like I'd have chosen blue, and after hitting the “X” it'd change to green or something.
Almost like it was mixing with some other colour, or conflicting with another value.
Using the “Lightbar” tab on the right side seems much more reliable,
and also perhaps what has fixed the problem, and made me unable to reproduce it.

**Comment by Ryochan7** [comment]
I have checked this and I cannot reproduce the issue on my end. I am going to assume that the code is working as intended and the issue is similar to what I had experienced in much older versions of DS4Windows. Current DS4Windows sends multiple output packets (3 IIRC) to the DS4 whenever it detects a change in the output report array as sometimes the DS4 does not change the lightbar color on the first received packet update.

If that is the issue then the only course of action that I would know of is to increase the number of output packets send to the DS4 upon output change. Output reports are not sent via BT all the time due to adding latency to the connection and weak BT dongles being bogged down with the increased traffic especially when using a 1 ms poll rate.
