### ISSUE TITLE
Not working on PS4 Remote Play via BT.

### ISSUE THREAD

**Issue by carljtc** [Ryochan7/DS4Windows#983]
Tried the 2.00 and 2.01 sadly PS4 RP wont detect it as a PS4 Wireless Controller...

Would be awesome to use DS4Windows to allow PS4 RP to use any BT with DS4 :) 

Sorry if it seems off topic.

**Comment by Ryochan7** [comment]
I don't own a PS4 so I have no way to test Remote Play; I use the DS4 exclusively as a PC controller. You have to make sure to emulate a virtual DS4 in order for the application to see it. Based on previous reports, it should work but some functionality is not possible due to current limitations of the ViGEmBus driver. Those limitations are no gyro and no touchpad touch support (only click is detectable).

**Comment by mika-n** [comment]
DS4Windows app and PS4RemotePlay on Windows 10 works and can be used to play PS4 games remotely both using BT and USB connections. Just remember to use a DS4Windows profile with Controller=dualshock4 output type and not the default xbox360 output type.

To be 110% sure I just tested the latest V2.0.1 version and DS4 gamepad over BT connection with PS4RemotePlay on Win10. Worked great. 

Even the gyro steering wheel 360 emulation mode can be used to play PS4 racing games on PC (the game uses LS stick to steer a car but gyro sensors drive the "virtual movements" of LS stick). This proves that DS4Windows app works and PS4RemotePlay uses the re-mapped virtual ds4 gamepad and not the original physical gamepad device.
