### ISSUE TITLE
Problem with FIFA20

### ISSUE THREAD

**Issue by schmiegii17** [Ryochan7/DS4Windows#989]
Your not able to use the right stick. doesnt work. in other games its fine.
Also its delayed.. the connection ist okay

**Comment by Ryochan7** [comment]
The FIFA series of games (FIFA 18 and later) requires Exclusive Mode to be working otherwise there will be input conflicts. First try to use the "Hide DS4 Controller" option in Settings. If that doesn't work on your machine then you will probably have to look into using HidGuardian.

https://github.com/Ryochan7/DS4Windows/wiki/DS4Windows-and-HIDGuardian-Install-and-Setup-Guide
