### ISSUE TITLE
V2.00 onwards  controller readings Issue 

### ISSUE THREAD

**Issue by puckle** [Ryochan7/DS4Windows#992]
Hi, I have 2 V1 DS4 controllers plugged in.  Going into one the edit menu for either seems to be reading from the same controller.  

For example, I can go into the readings for the 1st controller and see the gyro reading move along with the controller, but if I go into controller 2 and move my 2nd controller I get no readings from it, but moving controller 1 gives a reading. 

They are both showing different ID's. I can create 2 different profiles and it will apply them correctly, so it looks like it's just taking readings from one controller for both.

This issue started with V2.00. V1.7.28 works as it should.

Many thanks for continuing with this fantastic software, you work is hugely appreciated.

**Comment by mika-n** [comment]
See "Other" tab page in a profile editor and "Use Controller X for readout" (check that option to make the profile editor actively ilsten for gamepad events during the editing). The X here also tells the editor which gamepad to listen for in editor. In practice it really doesn't matter which gamepad you use to set btn mapping rules because profiles are not tied to a specific gamepad unless you set "link id/profile" option.

**Comment by puckle** [comment]
Thanks for the reply. I can put a tick in the checkbox, but the 'X' is greyed out so I can't select which controller to use. It's not a huge issue for me, just a little confusing deciding which controller I'm actually editing.

**Comment by Ryochan7** [comment]
Maybe I just need to compromise and get some sort of reload functionality for the Profile Editor back in order. I am fairly certain that you are trying to select the Edit option while the Profile Editor is still technically open (neither Save nor Cancel clicked). Doing that just causes the Profile Editor to gain focus again but still utilize the original device slot number and profile values.

The behavior in version 1.7.28 would have been wrong in a different way. With that version, a second Profile Editor would be created and placed over top of the original editor. Closing the second editor would still leave the first editor open but with the top toolbar no longer visible. That type of situation would very likely read to a crash on application close due to a null pointer problem.

The expected behavior is to close the Profile Editor before going to one of the other tabs. The Profile Editor is not meant to be in memory at all times like it was back in the Jays2Kings 1.4.52 build. That was one design decision that caused a great amount of unnecessary application slowdown.

**Comment by Ryochan7** [comment]
Decided to go with the other option and just disable most of the other tabs while the Profile Editor is still open. With the change, only the Profile and Log tabs will be enabled while the Profile Editor is open. I figured that people might still need to look at the Log if something goes wrong.

**Comment by puckle** [comment]
Seems to work okay now. Thanks :)
