### ISSUE TITLE
Rumble doesn't work normally

### ISSUE THREAD

**Issue by AsterXML** [Ryochan7/DS4Windows#995]
When the vibration process starts in the program, the vibration only works for a while (2 or 3 seconds, then it turns off). Also in the ds4windows program. I noticed that small vibrations work a little longer, large ones. So it should be?

**Comment by mika-n** [comment]
The 2-3 secs max duration of rumble is a historical "watchdog timer" safety net to make sure that rumble won't get stuck on infinitely. There were times when Vigem Client driver had a bug and it sometimes lost rumble events and if the lost event happent to be "rumble 0" command then game left the rumble on forever. Not good.

Before the bug was fixed in Vigem client drivers DS4Windows app had this 2-3 secs max duration between different rumble commands. Usually games send several rumble commands within few seconds, so this watchdog timer is not a problem in real world situations (the watchdog timer is reset everytime game sends a rumble command). This watchdog timer is probably not needed anymore but it is still there because of those historical bugs.

The duration of small or large motor must be a random variation because the watchdog timer is not a real time timer, so it can be small differences depending on when the timer was reset and the running timer expired.

**Comment by AsterXML** [comment]
> The 2-3 secs max duration of rumble is a historical "watchdog timer" safety net to make sure that rumble won't get stuck on infinitely. There were times when Vigem Client driver had a bug and it sometimes lost rumble events and if the lost event happened to be "rumble 0" command then game left the rumble on forever. Not good.
> 
> Before the bug was fixed in Vigem client drivers DS4Windows app had this 2-3 secs max duration between different rumble commands. Usually games send several rumble commands within few seconds, so this watchdog timer is not a problem in real world situations (the watchdog timer is reset everytime game sends a rumble command). This watchdog timer is probably not needed anymore but it is still there because of those historical bugs.
> 
> The duration of small or large motor must be a random variation because the watchdog timer is not a real time timer, so it may have small differences depending on when the timer was reset and the running timer expired.

but in program from Jays2Kings rumble works correctly, btw.

**Comment by mika-n** [comment]
Yes because the Jay2Kings versions used the now outdated ScpVBus driver and not the newer and supported Vigem driver. ScpVBus did't have this "lost rumble events" bug, but it had all other potential problems.

**Comment by AsterXML** [comment]
> ScpVBus did't have this "lost rumble eve

by the way, can i fix this on new drivers?

**Comment by AsterXML** [comment]
> ScpVBus did't have this "lost rumble events" bug
but, can i know, why Vigem driver have this bug?

**Comment by Ryochan7** [comment]
I'm not going back to find the issue about it but the bug initially existed in the embedded ViGEmClient C++ library that DS4Windows uses. Unlike ScpVBus which required the client to poll for rumble state data each gamepad poll, ViGEmBus tries to do things in a more async fashion using notification messages sent from the bus to a connected routine running in its own thread. The original design had some flaws that made it so some rumble events could be missed which could make the controller rumble indefinitely. Me and mika-n added fixes to in the upstream client code to correct some issues we had encountered.

Nowadays, the old failsafe timer is likely not needed. It would probably interfere with games that do not send periodic rumble updates when holding an effect for a long time. Luckily I do not encounter that in any games I play but I think supposedly GTA 5 is a problem game.

**Comment by mika-n** [comment]
> "ScpVBus did't have this "lost rumble events" bug"
> but, can i know, why Vigem driver have this bug?

Just like Ryochan7 mentioned Vigem client driver no longer has that "lost rumble events" bug because we (me and Ryochan7) helped Vigem team to fix it. So, no need to fix anything there. 

The "watchdog timer 2-3 secs" safety net in DS4Windows app could be removed or maybe there could be a configuration option to set it per profile (0=no watchdog timer, >0 watchdog duration in secs). However, most games and rumble effects won't even "see" this watchdog timer because games usually update the rumble value every few seconds, so the watchdog doesn't do anything. In DS4Windows "test rumble" buttons does trigger the watchdog timer, but I don't see it as a problem. Theoretical "stuck rumble motor" issue is more annoying problem.

@AsterXML  Do you have some game which suffers from this 2-3 secs watchdog timer in rumble effect? 

At some point I will probably change this fixed rumble watchdog timer to be a profile option (0...N secs), so users can decide when to use it or how many secs it should be.

**Comment by Ryusennin** [comment]
Profile option would be good, although as mentioned by Mika and Ryochan I personally haven't met any recent case where the rumble would stop working unexpectedly because of the fail-safe.

**Comment by AsterXML** [comment]
@mika-n all my games have this rumble effect. But on the last driver (Scpbusdriver) - everything worked perfectly.

**Comment by mika-n** [comment]
> @mika-n all my games have this rumble effect. 

@AsterXML What are those games? It would be nice to know the name of those games for reference in case someone else comes here and runs into the same effect.

>But on the previous driver (Scpbusdriver) - everything works perfectly (rumble).

The latest version of ScpVBus didn't have that "lost rumble events" bug then again it doesn't mean anything because VigemBus driver is a completely different thing. Bugs come and go. It is a state of fact in every software development tasks. Even when ScpVBus didn't have this "lost rumble bug" it had lots of other bugs. Anyway. The current version of VigEm driver no longer has this "lost rumble event" bug, so nothing to worry about it.

At some point newer version of DS4Windows may contain a new user option to disable or set the rumble watchdog timer duration anything you want, so just wait and hope for the best.

**Comment by AsterXML** [comment]
> What are those games?

For example NFS Payback, Alice - Madness Returns, Warframe.

> At some point newer version of DS4Windows may contain a new user option to disable or set the rumble watchdog timer duration anything you want, so just wait and hope for the best.

Oh, okay, thanks for the information. I will close this issue.
