### ISSUE TITLE
Automatic updates don't work

### ISSUE THREAD

**Issue by lmills87** [Ryochan7/DS4Windows#998]
When a new version is available, a box pops up asking me if I wish to download it when I first log into Windows. However, clicking "Yes" seemingly does nothing. If I manually run the auto updater, it seems to update correctly.

**Comment by Ryochan7** [comment]
That was an issue introduced in version 1.7.21 with a bad refactor. The issue was corrected in version 1.7.23. Running the auto updater was the only course of action until version 2.0 was released. Limitations with the old updater made it so only an update from 1.7.28 to 2.0 would be safe. Nowadays, you either have to download the latest updater manually before updating or just start with a fresh install.
